### ISSUE TITLE
restart canal-server, canal stuck at at sun.nio.ch.Net.poll(Native Method)

### ISSUE THREAD

**Issue by warrenwx** [alibaba/canal#1007]
Server and client works normally, restart server,  client will disconnect and try to connect and subscribe, while I found client thread stuck.
Do someone have got this, or come up with some ideas about this.

Callstack and information as follow:
2018-10-16 10:01:41  ERROR [CustomCanalClient]  Main Loop outter Exception.com.alibaba.otter.canal.protocol.exception.CanalClientException: java.io.IOException: end of stream when reading header
2018-10-16 10:01:41  WARN [HttpConnectionPool] object == null
2018-10-16 10:01:41  TRACEBACK [CustomCanalClient]com.alibaba.otter.canal.client.impl.SimpleCanalConnector.getWithoutAck(SimpleCanalConnector.java:317) 
com.alibaba.otter.canal.custom.CustomCanalClient.process(CustomCanalClient.java:106) 
com.alibaba.otter.canal.custom.CustomCanalClient$1.run(CustomCanalClient.java:67) 
java.lang.Thread.run(Thread.java:748) 

2018-10-16 10:01:43  ERROR [CustomCanalClient]  Main Loop outter Exception.com.alibaba.otter.canal.protocol.exception.CanalClientException: java.net.ConnectException: Connection refused
2018-10-16 10:01:43  WARN [HttpConnectionPool] object == null
2018-10-16 10:01:43  TRACEBACK [CustomCanalClient]com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:190) 
com.alibaba.otter.canal.client.impl.SimpleCanalConnector.connect(SimpleCanalConnector.java:114) 
com.alibaba.otter.canal.custom.CustomCanalClient.process(CustomCanalClient.java:101) 
com.alibaba.otter.canal.custom.CustomCanalClient$1.run(CustomCanalClient.java:67) 
java.lang.Thread.run(Thread.java:748)

   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.Net.poll(Native Method)
        at sun.nio.ch.SocketChannelImpl.poll(SocketChannelImpl.java:954)
        - locked <0x0000000094054d90> (a java.lang.Object)
        at sun.nio.ch.SocketAdaptor$SocketInputStream.read(SocketAdaptor.java:204)
        - locked <0x0000000094054d80> (a java.lang.Object)
        at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
        - locked <0x0000000094054e98> (a sun.nio.ch.SocketAdaptor$SocketInputStream)
        at java.nio.channels.Channels$ReadableByteChannelImpl.read(Channels.java:385)
        - locked <0x0000000094054f08> (a java.lang.Object)
        at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.read(SimpleCanalConnector.java:429)
        at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.readNextPacket(SimpleCanalConnector.java:419)
        - locked <0x00000000c038e900> (a java.lang.Object)
        at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.readNextPacket(SimpleCanalConnector.java:403)
        at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.receiveMessages(SimpleCanalConnector.java:322)
        at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.getWithoutAck(SimpleCanalConnector.java:315)
        at com.alibaba.otter.canal.custom.CustomCanalClient.process(CustomCanalClient.java:106)
        at com.alibaba.otter.canal.custom.CustomCanalClient$1.run(CustomCanalClient.java:67)
        at java.lang.Thread.run(Thread.java:748)

**Comment by agapple** [comment]
client example : https://github.com/alibaba/canal/blob/master/example/src/main/java/com/alibaba/otter/canal/example/SimpleCanalClientTest.java

**Comment by warrenwx** [comment]
Thank you
