### ISSUE TITLE
canal 过滤的表达式 Expression is too large.

### ISSUE THREAD

**Issue by suhuaguo** [alibaba/canal#1044]
Caused by: com.alibaba.otter.canal.filter.exception.CanalFilterException: org.apache.oro.text.regex.MalformedPatternException: Expression is too large.
Caused by: org.apache.oro.text.regex.MalformedPatternException: Expression is too large.
	at org.apache.oro.text.regex.Perl5Compiler.compile(Unknown Source)
	at org.apache.oro.text.regex.Perl5Compiler.compile(Unknown Source)
	at com.alibaba.otter.canal.filter.PatternUtils$1.apply(PatternUtils.java:30)
	at com.alibaba.otter.canal.filter.PatternUtils$1.apply(PatternUtils.java:25)
	at com.google.common.collect.ComputingConcurrentHashMap$ComputingValueReference.compute(ComputingConcurrentHashMap.java:356)
	at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.compute(ComputingConcurrentHashMap.java:182)
	at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.getOrCompute(ComputingConcurrentHashMap.java:151)
	at com.google.common.collect.ComputingConcurrentHashMap.getOrCompute(ComputingConcurrentHashMap.java:67)
	at com.google.common.collect.MapMaker$ComputingMapAdapter.get(MapMaker.java:885)
	at com.alibaba.otter.canal.filter.PatternUtils.getPattern(PatternUtils.java:41)
	at com.alibaba.otter.canal.filter.aviater.RegexFunction.call(RegexFunction.java:24)
	at Script_1540529734651_0.execute0(Unknown Source)
	at com.googlecode.aviator.ClassExpression.execute(ClassExpression.java:53)
	at com.alibaba.otter.canal.filter.aviater.AviaterRegexFilter.filter(AviaterRegexFilter.java:74)
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseRowsEventForTableMeta(LogEventConvert.java:456)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:247)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:222)
	at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by suhuaguo** [comment]
这个问题很奇怪，我后面再执行的话，没有问题了。

**Comment by agapple** [comment]
你的表达式有多长啊？

**Comment by suhuaguo** [comment]
"flight_fuwu_issue_log\\\\..*,fuwucore_operation_log\\\\..*,tts_operation_log0\\\\..*,tts_operation_log1\\\\..*,pub_operation_log0\\\\..*,pub_operation_log1\\\\..*,pub_operation_log2\\\\..*,pub_operation_log3\\\\..*,";

但是，我自己跑了 demo 好像没有问题了。

**Comment by suhuaguo** [comment]
我debug一下。在 canal 表达式计算模块中:
pattern="^pub_operation_log2.tb_operation_log_429$|^pub_operation_log2.tb_operation_log_428$|^pub_operation_log0.tb_operation_log_201$|^pub_operation_log2.tb_operation_log_427$|^pub_operation_log0.tb_operation_log_200$|^pub_operation_log2.tb_operation_log_426$|^pub_operation_log2.tb_operation_log_425$|^pub_operation_log2.tb_operation_log_424$|^pub_operation_log0.tb_operation_log_205$|^pub_operation_log2.tb_operation_log_423$|^pub_operation_log0.tb_operation_log_204$|^pub_operation_log2.tb_operation_log_422$|^pub_operation_log0.tb_operation_log_203$|^pub_operation_log2.tb_operation_log_421$|^pub_operation_log0.tb_operation_log_202$|^pub_operation_log2.tb_operation_log_420$|^pub_operation_log0.tb_operation_log_209$|^pub_operation_log0.tb_operation_log_208$|^pub_operation_log0.tb_operation_log_207$|^pub_operation_log0.tb_operation_log_206$|^pub_operation_log2.tb_operation_log_419$|^pub_operation_log2.tb_operation_log_418$|^pub_operation_log2.tb_operation_log_417$|^pub_operation_log2.tb_operation_log_41"

target= "tts_operation_log0.tb_operation_log_244"

**Comment by suhuaguo** [comment]
我在 otter 中配置了即使用了分库也使用了分表：

pub_operation_log[0-4] | tb_operation_log_[0-499]

**Comment by suhuaguo** [comment]
但是，单独跑demo 没有问题。

**Comment by suhuaguo** [comment]
我看了一下，确实是 。表名太长了，2500 个^pub_operation_log2.tb_operation_log_417$ 类似的这种表达式，我在跑demo 的时候，都跑不下去了。
idea 直接说：Error:(109, 60) java: 常量字符串过长

**Comment by suhuaguo** [comment]
在使用分库分表的时候，需要注意下：字符串不能太长。

**Comment by agapple** [comment]
你这是分库分表的吧, 可以用正则匹配一下

**Comment by BaliStarDUT** [comment]
> 在使用分库分表的时候，需要注意下：字符串不能太长。

能再详细说一下吗？怎么解决的？你不分库分表了？你的表明也不是很长啊。

**Comment by suhuaguo** [comment]
很有可能你的字符串 ，在里面的正则表达式里面，产生的字符太多了，超过 3w + 。你看看，正则表达式是不是你想要的结果
