### ISSUE TITLE
canal启动正常，客户端取不到binlog

### ISSUE THREAD

**Issue by panholly** [alibaba/canal#1052]
# mysql版本
5.7

# canal
1.1.1

# logs/example/example.log
```
2018-10-28 09:20:28.615 [main] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Loading properties file from class path resource [canal.properties]
2018-10-28 09:20:28.630 [main] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Loading properties file from class path resource [example/instance.properties]
2018-10-28 09:20:28.860 [main] WARN  o.s.beans.GenericTypeAwarePropertyDescriptor - Invalid JavaBean property 'connectionCharset' being accessed! Ambiguous write methods found next to actually used [public void com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.setConnectionCharset(java.lang.String)]: [public void com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.setConnectionCharset(java.nio.charset.Charset)]
2018-10-28 09:20:28.967 [main] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Loading properties file from class path resource [canal.properties]
2018-10-28 09:20:28.967 [main] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Loading properties file from class path resource [example/instance.properties]
2018-10-28 09:20:29.289 [main] ERROR com.alibaba.druid.pool.DruidDataSource - testWhileIdle is true, validationQuery not set
2018-10-28 09:20:29.736 [main] INFO  c.a.otter.canal.instance.spring.CanalInstanceWithSpring - start CannalInstance for 1-example
2018-10-28 09:20:29.916 [main] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - subscribe filter change to .*\..*
2018-10-28 09:20:29.916 [main] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - start successful....
2018-10-28 09:20:29.918 [destination = example , address = /192.168.255.129:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - prepare to find start position just show master status
2018-10-28 09:20:59.976 [New I/O server worker #1-1] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - subscribe filter change to .*\..*
2018-10-28 09:23:20.777 [destination = example , address = /192.168.255.129:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - find start position : EntryPosition[included=false,journalName=mysql-bin.000009,position=383,serverId=1,gtid=<null>,timestamp=1540689592000]
2018-10-28 09:25:09.385 [New I/O server worker #1-2] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - subscribe filter change to .*\..*
~           
```    

canal/canal.log报错:
```
2018-10-28 12:13:15.534 [New I/O server worker #1-2] ERROR c.a.otter.canal.server.netty.handler.SessionHandler - something goes wrong with channel:[id: 0x26e93058, /192.168.255.1:65515 => /192.168.255.129:11111], exception=java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:322)
        at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:281)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:201)
        at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by agapple** [comment]
Connection reset by peer, 估计空闲链接被关闭了

**Comment by panholly** [comment]
> Connection reset by peer, 估计空闲链接被关闭了

怎么解决？请指教

**Comment by panholly** [comment]
已解决。

**Comment by wangximingit** [comment]
怎么解决的..

**Comment by lynch0227** [comment]
应该是在链接jdbc时添加autoReconnect=true属性

**Comment by zhengqz** [comment]
> 已解决。

怎么解决，我这边 一个星期就有一次

**Comment by dingyufei615** [comment]
请问怎么解决的 现在也遇到这个问题了
