### ISSUE TITLE
canal 解析mysql异常

### ISSUE THREAD

**Issue by rusongit** [alibaba/canal#107]
2015-01-07 17:37:51.436 [destination = example , address = /192.168.0.20:3306 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - dump address /192.168.0.20:3306 has an error, retrying. caused by
com.alibaba.otter.canal.parse.exception.CanalParseException: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
java.lang.IllegalArgumentException: bad format, x exceed: 2121395706, 1000000000

这个是什么问题引起的，mysql是slave，并且binlog不是在默认目录下面

**Comment by agapple** [comment]
请提供一下mysql版本信息和canal版本信息

**Comment by rusongit** [comment]
mysql5.6.21,canal1.0.20一，在slave库上测试报：2015-01-14 10:19:05.121 [main] WARN  org.springframework.beans.TypeConverterDelegate - PropertyEditor [com.sun.beans.editors.EnumEditor] found through deprecated global PropertyEditorManager fallback - consider using a more isolated form of registration, e.g. on the BeanWrapper/BeanFactory!2015-01-14 10:19:05.231 [main] INFO  c.a.otter.canal.instance.spring.CanalInstanceWithSpring - start CannalInstance for 1-example2015-01-14 10:19:05.365 [main] INFO  c.a.otter.canal.instance.spring.CanalInstanceWithSpring - start successful....2015-01-14 10:19:05.366 [destination = example , address = /192.168.0.20:3306 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - prepare to find start position by switch ::14207065360002015-01-14 10:19:05.770 [destination = example , address = /192.168.0.20:3306 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - ERROR ## parse this event has an error , last position : [EntryPosition[included=false,journalName=mysql-bin.000092,position=59469,timestamp=1421036672000]]com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.java.lang.IllegalArgumentException: bad format, x exceed: 2016149504, 1000000000        at com.taobao.tddl.dbsync.binlog.LogBuffer.getDecimal0(LogBuffer.java:1635) ~[canal.parse.dbsync-1.0.19.jar:na]        at com.taobao.tddl.dbsync.binlog.LogBuffer.getDecimal(LogBuffer.java:1561) ~[canal.parse.dbsync-1.0.19.jar:na]        at com.taobao.tddl.dbsync.binlog.event.RowsLogBuffer.fetchValue(RowsLogBuffer.java:335) ~[canal.parse.dbsync-1.0.19.jar:na]        at com.taobao.tddl.dbsync.binlog.event.RowsLogBuffer.nextValue(RowsLogBuffer.java:95) ~[canal.parse.dbsync-1.0.19.jar:na]        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseOneRow(LogEventConvert.java:449) ~[canal.parse-1.0.19.jar:na]        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseRowsEvent(LogEventConvert.java:364) ~[canal.parse-1.0.19.jar:na]        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:109) ~[canal.parse-1.0.19.jar:na]        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:62) ~[canal.parse-1.0.19.jar:na]        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser.parseAndProfilingIfNecessary(AbstractEventParser.java:323) ~[canal.parse-1.0.19.jar:na]        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3$1.sink(AbstractEventParser.java:176) ~[canal.parse-1.0.19.jar:na]        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:124) [canal.parse-1.0.19.jar:na]        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209) [canal.parse-1.0.19.jar:na]


















        at java.lang.Thread.run(Thread.java:744) [na:1.7.0_51]二，在master测试报：015-01-14 10:10:28.992 [main] WARN  org.springframework.beans.TypeConverterDelegate - PropertyEditor [com.sun.beans.editors.EnumEditor] found through deprecated global PropertyEditorManager fallback - consider using a more isolated form of registration, e.g. on the BeanWrapper/BeanFactory!2015-01-14 10:10:29.118 [main] INFO  c.a.otter.canal.instance.spring.CanalInstanceWithSpring - start CannalInstance for 1-example2015-01-14 10:10:29.278 [main] INFO  c.a.otter.canal.instance.spring.CanalInstanceWithSpring - start successful....2015-01-14 10:10:29.279 [destination = example , address = /192.168.0.21:3306 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - prepare to find start position by switch ::14207065360002015-01-14 10:10:29.371 [destination = example , address = /192.168.0.21:3306 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - Didn't find the corresponding binlog files from mysql-bin.000001 to mysql-bin.000002




2015-01-14 10:10:29.376 [destination = example , address = /192.168.0.21:3306 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - dump address /192.168.0.21:3306 has an error, retrying. caused bycom.alibaba.otter.canal.parse.exception.CanalParseException: can't find start position for example 李迅（ruson） 上海-hadoop工程师，ELEME IncEmail：xun.li@ele.me | Mobile:18201873319http://ele.me 饿了么                             原始邮件                             发件人: agapple<notifications@github.com>收件人: alibaba/canal<canal@noreply.github.com>抄送: rusongit<xun.li@ele.me>发送时间: 2015年1月13日(周二) 18:41主题: Re: [canal] canal 解析mysql异常 (#107)请提供一下mysql版本信息和canal版本信息

**Comment by agapple** [comment]
mysql-bin.000092,position=59469,timestamp=1421036672000，方便提供一下对应的binlog文件给我不？本地测试了对应的mysql 5.6.22版本的decimal类型，解析是正常的

**Comment by rusongit** [comment]
这是我们线上库，不方便提供binlog，我们库是slave库，是不是这个引起的？李迅（ruson） 上海-hadoop工程师，ELEME IncEmail：xun.li@ele.me | Mobile:18201873319http://ele.me 饿了么                             原始邮件                             发件人: agapple<notifications@github.com>收件人: alibaba/canal<canal@noreply.github.com>抄送: rusongit<xun.li@ele.me>发送时间: 2015年1月14日(周三) 15:17主题: Re: [canal] canal 解析mysql异常 (#107)mysql-bin.000092,position=59469,timestamp=1421036672000，方便提供一下对应的binlog文件给我不？本地测试了对应的mysql 5.6.22版本的decimal类型，解析是正常的

**Comment by agapple** [comment]
不确定，我试过5.6.22版本是正常的。可以试着在你们测试库中重现一下问题，到时候发我binlog即可

**Comment by agapple** [comment]
初步怀疑是这类问题，先关闭.  see : https://github.com/alibaba/canal/issues/119
