### ISSUE TITLE
canal1.1.1运行client中KafkaClientRunningTest报错

### ISSUE THREAD

**Issue by brightsong** [alibaba/canal#1071]
在1.1.0版本中是Message message = connector.getWithoutAck(3L, TimeUnit.SECONDS);
在1.1.1版本中是List<Message> messages = connector.getList(3L, TimeUnit.SECONDS);
运行1.1.0版本没有问题，可以看到message数据包，运行1.1.1到这一行代码处报错。
是否还不是稳定版本

**Comment by rewerma** [comment]
把deploy中的配置mq.yml文件中flatMessage设置为false, KafkaClientRunningTest中为原生Message接收

**Comment by brightsong** [comment]
配置mq.yml文件中flatMessage设置为false，KafkaClientRunningTest改为原生Message，
connector.getWithoutAck(batchSize,5L, TimeUnit.SECONDS);
执行还是运行不了。

**Comment by brightsong** [comment]
配置mq.yml文件中flatMessage设置为false，KafkaClientRunningTest改为原生Message，
connector.getWithoutAck(batchSize,5L, TimeUnit.SECONDS);
执行还是运行不了。

在 2018-10-30 09:45:54，"rewerma" <notifications@github.com> 写道：


把deploy中的配置mq.yml文件中flatMessage设置为false, KafkaClientRunningTest中为原生Message接收

**Comment by brightsong** [comment]
报com.alibaba.otter.canal.protocol.exception.CanalClientException: mq not support this method

**Comment by rewerma** [comment]
connector.getWithoutAck(batchSize,5L, TimeUnit.SECONDS);这个不是kafkaConnector所提供的方法
测试类不要修改, 就使用这段代码没有问题
```
executor.submit(new Runnable() {

            @Override
            public void run() {
                connector.connect();
                connector.subscribe();
                while (running) {
                    try {
                        List<Message> messages = connector.getList(3L, TimeUnit.SECONDS);
                        if (messages != null) {
                            System.out.println(messages);
                        }
                        connector.ack();
                    } catch (WakeupException e) {
                        // ignore
                    }
                }
                connector.unsubscribe();
                connector.disconnect();
            }
        });
```

**Comment by brightsong** [comment]
使用上述测试类代码，并将mq.yml文件中flatMessage设置为false后，
报`Caused by: com.alibaba.otter.canal.protocol.exception.CanalClientException: deserializer failed
	at com.alibaba.otter.canal.client.CanalMessageDeserializer.deserializer(CanalMessageDeserializer.java:52)
	at com.alibaba.otter.canal.client.CanalMessageDeserializer.deserializer(CanalMessageDeserializer.java:14)
	at com.alibaba.otter.canal.client.kafka.MessageDeserializer.deserialize(MessageDeserializer.java:24)
	at com.alibaba.otter.canal.client.kafka.MessageDeserializer.deserialize(MessageDeserializer.java:1)
	at org.apache.kafka.common.serialization.ExtendedDeserializer$Wrapper.deserialize(ExtendedDeserializer.java:65)
	at org.apache.kafka.common.serialization.ExtendedDeserializer$Wrapper.deserialize(ExtendedDeserializer.java:55)
	at org.apache.kafka.clients.consumer.internals.Fetcher.parseRecord(Fetcher.java:967)
	at org.apache.kafka.clients.consumer.internals.Fetcher.access$3300(Fetcher.java:93)
	at org.apache.kafka.clients.consumer.internals.Fetcher$PartitionRecords.fetchRecords(Fetcher.java:1144)
	at org.apache.kafka.clients.consumer.internals.Fetcher$PartitionRecords.access$1400(Fetcher.java:993)
	at org.apache.kafka.clients.consumer.internals.Fetcher.fetchRecords(Fetcher.java:527)
	at org.apache.kafka.clients.consumer.internals.Fetcher.fetchedRecords(Fetcher.java:488)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollOnce(KafkaConsumer.java:1155)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1115)
	at com.alibaba.otter.canal.client.kafka.KafkaCanalConnector.getListWithoutAck(KafkaCanalConnector.java:173)
	at com.alibaba.otter.canal.client.kafka.KafkaCanalConnector.getList(KafkaCanalConnector.java:159)
	at com.alibaba.otter.canal.client.running.kafka.KafkaClientRunningTest$1.run(KafkaClientRunningTest.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Protocol message end-group tag did not match expected tag.
	at com.google.protobuf.InvalidProtocolBufferException.invalidEndTag(InvalidProtocolBufferException.java:110)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.checkLastTagWas(CodedInputStream.java:660)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readGroup(CodedInputStream.java:869)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:541)`

**Comment by brightsong** [comment]
使用上述测试类代码，flatMessage设置为false后，运行后没反应，把catch块改为Exception,后，看到报错信息为
`Caused by: com.alibaba.otter.canal.protocol.exception.CanalClientException: deserializer failed
	at com.alibaba.otter.canal.client.CanalMessageDeserializer.deserializer(CanalMessageDeserializer.java:52)
	at com.alibaba.otter.canal.client.CanalMessageDeserializer.deserializer(CanalMessageDeserializer.java:14)
	at com.alibaba.otter.canal.client.kafka.MessageDeserializer.deserialize(MessageDeserializer.java:24)
	at com.alibaba.otter.canal.client.kafka.MessageDeserializer.deserialize(MessageDeserializer.java:1)
	at org.apache.kafka.common.serialization.ExtendedDeserializer$Wrapper.deserialize(ExtendedDeserializer.java:65)
	at org.apache.kafka.common.serialization.ExtendedDeserializer$Wrapper.deserialize(ExtendedDeserializer.java:55)
	at org.apache.kafka.clients.consumer.internals.Fetcher.parseRecord(Fetcher.java:967)
	at org.apache.kafka.clients.consumer.internals.Fetcher.access$3300(Fetcher.java:93)
	at org.apache.kafka.clients.consumer.internals.Fetcher$PartitionRecords.fetchRecords(Fetcher.java:1144)
	at org.apache.kafka.clients.consumer.internals.Fetcher$PartitionRecords.access$1400(Fetcher.java:993)
	at org.apache.kafka.clients.consumer.internals.Fetcher.fetchRecords(Fetcher.java:527)
	at org.apache.kafka.clients.consumer.internals.Fetcher.fetchedRecords(Fetcher.java:488)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollOnce(KafkaConsumer.java:1155)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1115)
	at com.alibaba.otter.canal.client.kafka.KafkaCanalConnector.getListWithoutAck(KafkaCanalConnector.java:173)
	at com.alibaba.otter.canal.client.kafka.KafkaCanalConnector.getList(KafkaCanalConnector.java:159)
	at com.alibaba.otter.canal.client.running.kafka.KafkaClientRunningTest$1.run(KafkaClientRunningTest.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Protocol message end-group tag did not match expected tag.
	at com.google.protobuf.InvalidProtocolBufferException.invalidEndTag(InvalidProtocolBufferException.java:110)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.checkLastTagWas(CodedInputStream.java:660)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readGroup(CodedInputStream.java:869)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:541)`

**Comment by rewerma** [comment]
groupId 换一个, 你消费到的还是老的faltMessage

**Comment by brightsong** [comment]
ok了，谢谢大师！
