### ISSUE TITLE
请教canal v1.1.1 版本配置pwdPublicKey问题????

### ISSUE THREAD

**Issue by hackxboy1985** [alibaba/canal#1072]
example/instance.properties中如下配置项，mysql用户名、密码都配置了，这个pwdPublicKey是配置什么公钥？配空了启动不了，注释掉也启动不了,
canal.instance.dbUsername=canal
canal.instance.dbPassword=canal
canal.instance.pwdPublicKey=
查看spring/memory-instance.xml文件中,如下配置，是必须要有的配置吗？
<property name="pwdPublicKey" value="${canal.instance.pwdPublicKey:retl}" />

以下为log:
Caused by: java.lang.IllegalArgumentException: String length must be a multiple of four.
        at com.alibaba.druid.util.Base64.base64ToByteArray(Base64.java:122) ~[druid-1.1.9.jar:1.1.9]
        at com.alibaba.druid.util.Base64.base64ToByteArray(Base64.java:107) ~[druid-1.1.9.jar:1.1.9]
        at com.alibaba.druid.filter.config.ConfigTools.decrypt(ConfigTools.java:150) ~[druid-1.1.9.jar:1.1.9]
        at com.alibaba.druid.filter.config.ConfigTools.decrypt(ConfigTools.java:65) ~[druid-1.1.9.jar:1.1.9]
        at com.alibaba.otter.canal.parse.support.AuthenticationInfo.initPwd(AuthenticationInfo.java:28) ~[canal.parse-1.1.1.jar:na]

**Comment by agapple** [comment]
默认参数做了修改
