### ISSUE TITLE
canal1.1.1 ClientAdapter 同步到hbase报错java.lang.NullPointerException

### ISSUE THREAD

**Issue by brightsong** [alibaba/canal#1077]
`2018-10-31 10:26:48.345 ERROR 5095 --- [           main] c.a.o.c.a.l.loader.CanalAdapterService   : ## something goes wrong when starting up the canal client adapters:

java.lang.NullPointerException: null
        at com.alibaba.otter.canal.adapter.launcher.loader.CanalAdapterLoader.init(CanalAdapterLoader.java:61) ~[classes!/:na]
        at com.alibaba.otter.canal.adapter.launcher.loader.CanalAdapterService.init(CanalAdapterService.java:48) ~[classes!/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_73]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_73]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_73]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_73]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:365) [spring-beans-5.0.5.RELEASE.jar!/:5.0.5.RELEASE]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:308) [spring-beans-5.0.5.RELEASE.jar!/:5.0.5.RELEASE]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:135) [spring-beans-5.0.5.RELEASE.jar!/:5.0.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:422) [spring-beans-5.0.5.RELEASE.jar!/:5.0.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1694) [spring-beans-5.0.5.RELEASE.jar!/:5.0.5.RELEASE]`

修改了config/application.yml ,base/mytest_person2.yml ，启动了canal-deployer-1.1.1，deployer中的canal.serverMode=kafka，执行java -jar canal-adapter-launcher.jar报以上错误。

**Comment by agapple** [comment]
config/application.yml  配置文件看下内容

**Comment by brightsong** [comment]
`[root@hadoop01 config]# cat application.yml
server:
  port: 8081
logging:
  level:
    com.alibaba.otter.canal.client.adapter.hbase: DEBUG
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null


hbasezookeeper.quorum: 127.0.0.1
hbase.zookeeper.property.clientPort: 2181
hbase.zookeeper.znode.parent: /hbase

canal.conf:
  canalServerHost: 127.0.0.1:11111
#  zookeeperHosts: slave1:2181
#  bootstrapServers: slave1:6667 #or rocketmq nameservers:host1:9876;host2:9876
  flatMessage: true
  canalInstances:
  - instance: example
    adapterGroups:
    - outAdapters:
#      - name: logger
      - name: hbase
        properties:
          hbase.zookeeper.quorum: 192.168.206.128
          hbase.zookeeper.property.clientPort: 2181
          zookeeper.znode.parent: /hbase
#  mqTopics:
#  - mqMode: kafka
#    topic: example
#    groups:
#    - groupId: g2
#      outAdapters:
#      - name: logger
#  mqTopics:
#  - mqMode: rocketmq
#    topic: example
#    groups:
#    - groupId: g2
#      outAdapters:
#      - name: logger

adapter.conf:
  datasourceConfigs:
    defaultDS:
      url: jdbc:mysql://192.168.206.136:3306/can_db?useUnicode=true
      username: canal
      password: canal
  adapterConfigs:
  - hbase/mytest_person2.yml`

**Comment by brightsong** [comment]
`[root@hadoop01 config]# cat application.yml
server:
  port: 8081
logging:
  level:
    com.alibaba.otter.canal.client.adapter.hbase: DEBUG
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null


hbasezookeeper.quorum: 127.0.0.1
hbase.zookeeper.property.clientPort: 2181
hbase.zookeeper.znode.parent: /hbase

canal.conf:
  canalServerHost: 127.0.0.1:11111
#  zookeeperHosts: slave1:2181
#  bootstrapServers: slave1:6667 #or rocketmq nameservers:host1:9876;host2:9876
  flatMessage: true
  canalInstances:
  - instance: example
    adapterGroups:
    - outAdapters:
#      - name: logger
      - name: hbase
        properties:
          hbase.zookeeper.quorum: 192.168.206.128
          hbase.zookeeper.property.clientPort: 2181
          zookeeper.znode.parent: /hbase
#  mqTopics:
#  - mqMode: kafka
#    topic: example
#    groups:
#    - groupId: g2
#      outAdapters:
#      - name: logger
#  mqTopics:
#  - mqMode: rocketmq
#    topic: example
#    groups:
#    - groupId: g2
#      outAdapters:
#      - name: logger

adapter.conf:
  datasourceConfigs:
    defaultDS:
      url: jdbc:mysql://192.168.206.136:3306/can_db?useUnicode=true
      username: canal
      password: canal
  adapterConfigs:
  - hbase/mytest_person2.yml`

**Comment by rewerma** [comment]
你是用kafka模式, 不用用canalInstances模式接收, 把下面这段注释掉
```
  canalInstances:
  - instance: example
    groups:
    - outAdapters:
      - name: logger
      - name: hbase
        properties:
          hbase.zookeeper.quorum: ${hbase.zookeeper.quorum}
          hbase.zookeeper.property.clientPort: ${hbase.zookeeper.property.clientPort}
          zookeeper.znode.parent: ${hbase.zookeeper.znode.parent}
```

从 mqTopics: 这里开始配置adapter

**Comment by brightsong** [comment]
`[root@hadoop01 config]# cat application.yml
server:
  port: 8081
logging:
  level:
    com.alibaba.otter.canal.client.adapter.hbase: DEBUG
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

canal.conf:
  zookeeperHosts: 192.168.206.128:2181
  bootstrapServers: 192.168.206.128:9092
  flatMessage: true
  mqTopics:
  - mqMode: kafka
    topic: canal1
    groups:
    - groupId: g2
      outAdapters:
      - name: logger

adapter.conf:
  datasourceConfigs:
    defaultDS:
      url: jdbc:mysql://192.168.206.136:3306/can_db?useUnicode=true
      username: canal
      password: canal
  adapterConfigs:
  - hbase/mytest_person2.yml`
配置文件改为上面的，现在报
'2018-10-31 16:07:26.543  INFO 9749 --- [           main] c.a.o.c.a.l.loader.CanalAdapterLoader    : Load canal adapter: logger succeed
2018-10-31 16:07:26.590  INFO 9749 --- [           main] c.a.o.c.a.l.loader.CanalAdapterLoader    : Start adapter for canal instance: example succeed
2018-10-31 16:07:26.591  INFO 9749 --- [           main] c.a.o.c.a.l.loader.CanalAdapterLoader    : Load canal adapter: logger succeed
2018-10-31 16:07:26.594  INFO 9749 --- [       Thread-2] c.a.o.c.a.l.loader.CanalAdapterWorker    : =============> Start to connect destination: example <=============
2018-10-31 16:07:26.627 ERROR 9749 --- [       Thread-2] c.a.o.c.a.l.loader.CanalAdapterWorker    : process error!

com.alibaba.otter.canal.protocol.exception.CanalClientException: java.net.ConnectException: Connection refused
        at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:189) ~[canal.client-1.1.1.jar!/:na]
        at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.connect(SimpleCanalConnector.java:113) ~[canal.client-1.1.1.jar!/:na]
        at com.alibaba.otter.canal.adapter.launcher.loader.CanalAdapterWorker.process(CanalAdapterWorker.java:66) ~[classes!/:na]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_73]
Caused by: java.net.ConnectException: Connection refused
        at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_73]
        at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_73]
        at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_73]
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_73]
        at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:148) ~[canal.client-1.1.1.jar!/:na]
        ... 3 common frames omitted '

zookeeper\kafka\hbase\canal1.1.1 都启动了。

**Comment by rewerma** [comment]
你在工程里把application.yml 的canalInstances: 和   mqTopics: 下的内容全部注释掉, 重新打包, 然后再在里面添加mqTopics: 下的内容
由于springboot包里面的application.yml有canalInstances:  内容会和config中的application.yml合并, 导致还是能加载到canal-client的配置

**Comment by brightsong** [comment]
重新打包后，ok了。多谢多谢。重新打包后我那几个jar包重新覆盖掉，然后改了application.yml文件。看到修改表数据后，看到DML语句了。GOOD

**Comment by brightsong** [comment]
新打包后，ok了。多谢多谢。重新打包后我把原先几个jar包重新覆盖掉，然后改了application.yml文件。修改mysql表数据后，看到DML语句了。GOOD

**Comment by brightsong** [comment]
还有一个问题，可以看到DML语句，但hbase中为啥看不到数据。
`hbase(main):014:0> scan 'CAN_DB.USER_TEST'
ROW                                        COLUMN+CELL                                                                                                                 
0 row(s) in 1.1130 seconds
`
mytest_person2.yml配置内容为：
dataSourceKey: defaultDS
hbaseMapping: 
#  mode: PHOENIX  #NATIVE   #STRING
  mode: STRING
  destination: example
  database: can_db  # 数据库名
  table: user_test     # 数据库表名
  hbaseTable: CAN_DB.USER_TEST   # HBase表名
  family: CF  # 默认统一Family名称
  uppercaseQualifier: true  # 字段名转大写, 默认为true
  commitBatch: 3000 # 批量提交的大小
  #rowKey: id,type  # 复合字段rowKey不能和columns中的rowKey重复
  columns:
    # 数据库字段:HBase对应字段
    id: ROWKEY$UNSIGNED_LONG
    name: NAME
    age: AGE
    # type: $DECIMAL
    # c_time: C_TIME$UNSIGNED_TIMESTAMP
    # birthday: BIRTHDAY$DATE
#  excludeColumns:
#    - lat   # 忽略字段
