### ISSUE TITLE
新版本编译代码提示内存溢出

### ISSUE THREAD

**Issue by NewsGitHub** [alibaba/canal#108]
parse events has an errorjava.lang.OutOfMemoryError: Java heap space
	at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:57) ~[na:1.7.0_67]
	at java.nio.ByteBuffer.allocate(ByteBuffer.java:331) ~[na:1.7.0_67]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.readNextPacket(SimpleCanalConnector.java:364) ~[classes/:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:129) ~[classes/:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.connect(SimpleCanalConnector.java:97) ~[classes/:na]
	at com.alibaba.otter.canal.example.AbstractCanalClientTest.process(AbstractCanalClientTest.java:110) ~[classes/:na]
	at com.alibaba.otter.canal.example.AbstractCanalClientTest$2.run(AbstractCanalClientTest.java:80) ~[classes/:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.7.0_67]
## stop the canal client## canal client is down.

**Comment by agapple** [comment]
运行的是mvn？尝试调整下mvn的jvm参数
