### ISSUE TITLE
10.1.22-MariaDB版本数据库 journalName乱码

### ISSUE THREAD

**Issue by haopangxu** [alibaba/canal#1081]
你好，我使用10.1.22-MariaDB和1.1.1版本canal，启动后报如下错误
2018-11-01 09:40:42.663 [destination = cloud , address = /192.168.1.21:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - prepare to find start position just last position
 {"identity":{"slaveId":-1,"sourceAddress":{"address":"192.168.1.21","port":3306}},"postion":{"gtid":"","included":false,**"journalName":"mysql-bin.000607Æ\u009E´U"**,"position":91598031,"serverId":1,"timestamp":1541028888000}}
2018-11-01 09:40:42.674 [destination = cloud , address = /192.168.1.21:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - find start position : EntryPosition[included=false,journalName=mysql-bin.000607Æ´U,position=91598031,serverId=1,gtid=,timestamp=1541028888000]
2018-11-01 09:40:42.690 [destination = cloud , address = /192.168.1.21:3306 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - I/O error while reading from client socket
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102) ~[canal.parse-1.1.1.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:216) [canal.parse-1.1.1.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:252) [canal.parse-1.1.1.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]
2018-11-01 09:40:42.691 [destination = cloud , address = /192.168.1.21:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address /192.168.1.21:3306 has an error, retrying. caused by 
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102) ~[canal.parse-1.1.1.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:216) ~[canal.parse-1.1.1.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:252) ~[canal.parse-1.1.1.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]
2018-11-01 09:40:42.692 [destination = cloud , address = /192.168.1.21:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:cloud[java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:216)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:252)
	at java.lang.Thread.run(Thread.java:748)
]
看到是journalName有乱码，请问怎么解决

**Comment by agapple** [comment]
@haopangxu 可以试一下我的改法.  

主要原因: mariadb在处理checksum行为上和mysql有点不太一致，针对rotate_event这个binlog对象，mariadb会执行checksum，而mysql不会，需要有特殊判断处理

**Comment by baby1937** [comment]
mariadb 10.1的binlog_checksum默认是关闭的，我们测试服务器也是没有设置这个参数的
https://mariadb.com/kb/en/library/replication-and-binary-log-system-variables/#binlog_checksum
验证了下，把master分支下面两个类替换了canal.parse-1.1.1.jar里的跑了下
com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection
com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor

问题依旧存在,debug发现启动后收到RotateLogEvent解析总长度47减header27等于body的20，所以文件名乱码了，麻烦看看这是什么情况？

![image](https://user-images.githubusercontent.com/8623402/47948350-870b6b00-df6a-11e8-97f6-593295c52d23.png)
![image](https://user-images.githubusercontent.com/8623402/47948353-95f21d80-df6a-11e8-8401-b02b849f61fc.png)

**Comment by agapple** [comment]
正常的RotateLogEvent的文件名字节应该是16 bytes, 最后的4 bytess肯定是checksum. 我看过mariadb和mysql的区别, 就是在RotateLogEvent事件的发送上, mariadb默认也会在RotateLogEvent带上checksum.  

mysql/mariadb发送binlog的顺序: RotateLogEvent -> FomatXXEvent -> 正常的事务事件.  FomatXXEvent这里会有这个binlog是否开启checksum的标记位, 所以第一个RotateLogEvent是否开启checksum ,只能是在链接建立时获取一下数据库的checksum变量

**Comment by agapple** [comment]
@baby1937 你帮忙查询一下 SELECT @@version 和 select @@global.binlog_checksum  结果给我

**Comment by baby1937** [comment]
![image](https://user-images.githubusercontent.com/8623402/47949708-bcbc4e00-df82-11e8-8541-922e4a9c3f8c.png)
![image](https://user-images.githubusercontent.com/8623402/47949711-c5ad1f80-df82-11e8-9870-7052ef4717ad.png)

**Comment by baby1937** [comment]
[image]
[image]
________________________________
发件人: agapple <notifications@github.com>
发送时间: 2018年11月3日 7:11
收件人: alibaba/canal
抄送: baby1937; Mention
主题: Re: [alibaba/canal] 10.1.22-MariaDB版本数据库 journalName乱码 (#1081)


@baby1937<https://github.com/baby1937> 你帮忙查询一下 SELECT @@Version<https://github.com/Version> 和 select @@global.binlog_checksum 结果给我

―

**Comment by agapple** [comment]
@baby1937 你传了啥？没看到

**Comment by baby1937** [comment]
就是SELECT @@Version 和 select @@global.binlog_checksum 的结果跟上面图片一样啊

**Comment by agapple** [comment]
这个得等我装好mariadb再试试了，以前的环境没了

**Comment by Jerryd99** [comment]
我也出现这个问题，版本是10.2.12-MariaDB-log，用的1.1.1版本出现的，之前用canal.kafka-1.1.0没事

**Comment by baby1937** [comment]
@agapple mariadb环境恢复没，这个问题能否解决？

**Comment by agapple** [comment]
可以试试1.1.2+的版本,有修复过
