### ISSUE TITLE
 Could not find first log file name in binary log index file

### ISSUE THREAD

**Issue by NewsGitHub** [alibaba/canal#109]
2015-01-15 10:40:01.756 [destination = example , address = /127.0.0.1:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:95)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:116)
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209)
        at java.lang.Thread.run(Thread.java:662)

我在data目录下看到了mysql-bin.index和mysql-bin.000001,
可是报错说找不到index file，我用的是ubuntu的系统，不知道是不是和系统有关系，我在windows下测试没有问题的。

**Comment by agapple** [comment]
这个应该和你的mysql又关吧，指定一个canal起始位点，如果有问题，可以通过命令验证下mysql binlog
show binlog events in 'mysql-bin.000001' from xxx limit 10;

**Comment by NewsGitHub** [comment]
已经解决了 是linux文件权限问题

**Comment by changsong** [comment]
@NewsGitHub 请问是哪个文件的权限问题，我这边也碰到相同的问题了

**Comment by songjian0270** [comment]
@NewsGitHub  亲，给了日志-R 777的权限貌似不行的呢

**Comment by wayneFly** [comment]
@changsong  删除canal下面的meta.dat，然后重启一下就行。

**Comment by aiaix** [comment]
这问题的解决没描述清楚啊，我指定了位置点还是不行

**Comment by boboChina** [comment]
我也是卡在这里。在mysql端发现canal这个用户一直在执行Binlog Dump

**Comment by jiatianyao** [comment]
这个怎么能和权限有关系呢？如果canal读的不是本机呢？
