### ISSUE TITLE
我们的阿里云RDS主库mysql在purge binlog的时候，mysql主库日志里面显示binlog正在被读取，无法purge以致于于日志空间被打满了，是因为canal启动以后一直在read引起的吗？

### ISSUE THREAD

**Issue by dukeshiny** [alibaba/canal#1134]
大家好，帮忙看一个问题，我们的主库mysql在purge binlog的时候，mysql主库日志里面显示binlog正在被读取，无法purge以至于日志空间被打满了，是因为canal启动以后一直在read引起的吗？谢谢
报错日志如下：
2018-11-11 12:02:02.004 [destination = t_dom_cabinet_status , address = rm-.mysql.rds.aliyuncs.com/192.168.120.88:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - prepa
re to find start position just last position
 {"identity":{"slaveId":-1,"sourceAddress":{"address":"rm-.mysql.rds.aliyuncs.com","port":3306}},"postion":{"gtid":"","included":false,"journalName":"mysql-bin.016787","position":290802006,"serverId":3
15847219,"timestamp":1541789260000}}
2018-11-11 12:02:02.004 [destination = t_dom_cabinet_status , address = rm-.mysql.rds.aliyuncs.com/192.168.120.88:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - find
start position : EntryPosition[included=false,journalName=mysql-bin.016787,position=290802006,serverId=315847219,gtid=,timestamp=1541789260000]
2018-11-11 12:30:07.846 [destination = t_dom_cabinet_status , address = rm-.mysql.rds.aliyuncs.com/192.168.120.88:3306 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - Soc
ket timeout expired, closing connection
java.net.SocketTimeoutException: Timeout occurred, failed to read 87 bytes in 25000 milliseconds.
        at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:123) ~[canal.parse.driver-1.1.1.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:174) ~[canal.parse-1.1.1.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:85) ~[canal.parse-1.1.1.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:216) [canal.parse-1.1.1.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:252) [canal.parse-1.1.1.jar:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]
2018-11-11 12:30:07.846 [destination = t_dom_cabinet_status , address = rm-.mysql.rds.aliyuncs.com/192.168.120.88:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump
address rm-.mysql.rds.aliyuncs.com/192.168.120.88:3306 has an error, retrying. caused by
java.net.SocketTimeoutException: Timeout occurred, failed to read 87 bytes in 25000 milliseconds.
        at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:123) ~[canal.parse.driver-1.1.1.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:174) ~[canal.parse-1.1.1.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:85) ~[canal.parse-1.1.1.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:216) ~[canal.parse-1.1.1.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:252) ~[canal.parse-1.1.1.jar:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]
2018-11-11 12:30:07.846 [destination = t_dom_cabinet_status , address = rm-.mysql.rds.aliyuncs.com/192.168.120.88:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destin
ation:t_dom_cabinet_status[java.net.SocketTimeoutException: Timeout occurred, failed to read 87 bytes in 25000 milliseconds.
        at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:123)
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:174)
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:85)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:216)
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:252)
        at java.lang.Thread.run(Thread.java:748)
MySQL主库报错日志如下：
2018-11-11 08:13:38 55733 [Warning] file /home/mysql/data3008/mysql/mysql-bin.016778 was not purged because it was being readby thread number 151449924

**Comment by agapple** [comment]
你看下当时的canal位点，是否刚好在读取这个文件

**Comment by dukeshiny** [comment]
> 你看下当时的canal位点，是否刚好在读取这个文件
我从canal的日志里面查过了没有2018-11-11 08:13:38的日志，有2018-11-11 08:18:36的日志如下：
		
2018-11-11 08:18:36.106 [destination = t_dom_cabinet_battery , address = rm-.mysql.rds.aliyuncs.com/192.168.1.1:3306 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - So
cket timeout expired, closing connection
java.net.SocketTimeoutException: Timeout occurred, failed to read 87 bytes in 25000 milliseconds.
        at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:123) ~[canal.parse.driver-1.1.1.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:174) ~[canal.parse-1.1.1.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:85) ~[canal.parse-1.1.1.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:216) [canal.parse-1.1.1.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:252) [canal.parse-1.1.1.jar:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]
这里是binlog的信息
2018-11-11 08:18:48.569 [destination = t_dom_cabinet_battery , address = rm-.mysql.rds.aliyuncs.com/192.168.1.1:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - prep
are to find start position just last position
 {"identity":{"slaveId":-1,"sourceAddress":{"address":"rm-.mysql.rds.aliyuncs.com","port":3306}},"postion":{"gtid":"","included":false,"journalName":"mysql-bin.016781","position":437008398,"serverId":3
15847219,"timestamp":1541786346000}}

**Comment by agapple** [comment]
那位点明显不是了，都已经读到016781

**Comment by dukeshiny** [comment]
> 那位点明显不是了，都已经读到016781

是的 那可以说明不是因为我的canal读取主库binlog引起的问题吗？也就是主库无法purge

**Comment by agapple** [comment]
是的

**Comment by dukeshiny** [comment]
@agapple 你好 我们压测yc库又试了一下，发现数据库服务器磁盘又被打满了，还是提示数据库日志was not purged .................然后停掉canal后空间就下来了，请问这个有什么好的解决方案吗？学习

**Comment by agapple** [comment]
@dukeshiny 还是要关注canal消费的位点情况，如果消费比较慢，那就没啥好办法

**Comment by dukeshiny** [comment]
> @dukeshiny 还是要关注canal消费的位点情况，如果消费比较慢，那就没啥好办法

嗯，现在是canal把mysql的binlog监控后把数据发送到kafka了，还没消费kafka的数据，canal会读取所有mysql的binlog的位点，我在想是不是和网络带宽有关系？
