### ISSUE TITLE
canal tcp模式启动成功， 修改数据记录后报错

### ISSUE THREAD

**Issue by Czjcunzhang** [alibaba/canal#1135]
canal-1.1.1

错误日志：
2018-11-13 11:27:12.638 [destination = example , address = /10.0.0.61:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address /10.0.0.61:3306 has an error, retrying. caused by 
java.lang.IllegalArgumentException: null
	at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1314) ~[na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1237) ~[na:1.8.0_191]
	at java.util.concurrent.Executors.newFixedThreadPool(Executors.java:151) ~[na:1.8.0_191]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor.start(MysqlMultiStageCoprocessor.java:84) ~[canal.parse-1.1.0.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:238) ~[canal.parse-1.1.0.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]
2018-11-13 11:27:12.638 [destination = example , address = /10.0.0.61:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[java.lang.IllegalArgumentException
	at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1314)
	at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1237)
	at java.util.concurrent.Executors.newFixedThreadPool(Executors.java:151)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor.start(MysqlMultiStageCoprocessor.java:84)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:238)
	at java.lang.Thread.run(Thread.java:748)
]

**Comment by agapple** [comment]
升级使用1.1.1版本，已知问题
