### ISSUE TITLE
canal-1.1.1 tcp模式启动，日志正常， client没收到消息

### ISSUE THREAD

**Issue by Czjcunzhang** [alibaba/canal#1137]
canal.log:
2018-11-13 13:26:09.610 [main] ERROR com.alibaba.druid.pool.DruidDataSource - testWhileIdle is true, validationQuery not set
2018-11-13 13:26:09.641 [main] INFO  com.alibaba.druid.pool.DruidDataSource - {dataSource-1} inited
2018-11-13 13:26:09.929 [main] INFO  c.a.o.c.p.inbound.mysql.tsdb.DefaultTableMetaTSDBFactory - example init TableMetaTSDB with classpath:spring/tsdb/h2-tsdb.xml
2018-11-13 13:26:09.932 [main] INFO  com.alibaba.otter.canal.prometheus.CanalInstanceExports - Successfully register metrics for instance example.
2018-11-13 13:26:09.932 [main] INFO  com.alibaba.otter.canal.prometheus.PrometheusService - Register metrics for destination example.
2018-11-13 13:26:09.981 [destination = example , address = /10.0.0.61:3306 , EventParser] INFO  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - start heart beat.... 
2018-11-13 13:26:10.004 [destination = example , address = /10.0.0.61:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - connect MysqlConnection to /10.0.0.61:3306...
2018-11-13 13:26:10.027 [destination = example , address = /10.0.0.61:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - handshake initialization packet received, prepare the client authentication packet to send
2018-11-13 13:26:10.033 [destination = example , address = /10.0.0.61:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - client authentication packet is sent out.
2018-11-13 13:26:10.070 [destination = example , address = /10.0.0.61:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - connect MysqlConnection to /10.0.0.61:3306...
2018-11-13 13:26:10.071 [destination = example , address = /10.0.0.61:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - handshake initialization packet received, prepare the client authentication packet to send
2018-11-13 13:26:10.071 [destination = example , address = /10.0.0.61:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - client authentication packet is sent out.
2018-11-13 13:26:10.124 [main] INFO  c.a.otter.canal.server.embedded.CanalServerWithEmbedded - start CanalInstances[example] successfully
2018-11-13 13:26:10.174 [destination = example , address = /10.0.0.61:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - prepare to find start position just show master status
2018-11-13 13:26:10.175 [destination = example , address = /10.0.0.61:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - disConnect MysqlConnection to /10.0.0.61:3306...
2018-11-13 13:26:10.176 [destination = example , address = /10.0.0.61:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - connect MysqlConnection to /10.0.0.61:3306...
2018-11-13 13:26:10.177 [destination = example , address = /10.0.0.61:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - handshake initialization packet received, prepare the client authentication packet to send
2018-11-13 13:26:10.208 [destination = example , address = /10.0.0.61:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - client authentication packet is sent out.
2018-11-13 13:26:10.215 [main] INFO  com.alibaba.otter.canal.deployer.CanalLauncher - ## the canal server is running now ......
2018-11-13 13:26:10.220 [destination = example , address = /10.0.0.61:3306 , EventParser] INFO  c.a.otter.canal.parse.inbound.mysql.MysqlConnection - COM_BINLOG_DUMP with position:BinlogDumpCommandPacket[binlogPosition=4,slaveServerId=1234,binlogFileName=mysql-bin.000004,command=18]
2018-11-13 13:26:10.249 [destination = example , address = /10.0.0.61:3306 , EventParser] INFO  com.taobao.tddl.dbsync.binlog.LogEvent - common_header_len= 19, number_of_event_types= 35

example.log:
2018-11-13 13:26:08.708 [main] INFO  o.s.context.support.ClassPathXmlApplicationContext - Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@10dba097: startup date [Tue Nov 13 13:26:08 CST 2018]; root of context hierarchy
2018-11-13 13:26:08.751 [main] INFO  o.s.beans.factory.xml.XmlBeanDefinitionReader - Loading XML bean definitions from class path resource [spring/file-instance.xml]
2018-11-13 13:26:08.891 [main] INFO  o.s.beans.factory.xml.XmlBeanDefinitionReader - Loading XML bean definitions from class path resource [spring/base-instance.xml]
2018-11-13 13:26:09.038 [main] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Loading properties file from class path resource [canal.properties]
2018-11-13 13:26:09.039 [main] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Loading properties file from class path resource [example/instance.properties]
2018-11-13 13:26:09.057 [main] INFO  o.s.beans.factory.support.DefaultListableBeanFactory - Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@68999068: defining beans [com.alibaba.otter.canal.instance.spring.support.PropertyPlaceholderConfigurer#0,socketAddressEditor,org.springframework.beans.factory.config.CustomEditorConfigurer#0,baseEventParser,instance,alarmHandler,metaManager,eventStore,eventSink,eventParser]; root of factory hierarchy
2018-11-13 13:26:09.201 [main] WARN  o.s.beans.GenericTypeAwarePropertyDescriptor - Invalid JavaBean property 'connectionCharset' being accessed! Ambiguous write methods found next to actually used [public void com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.setConnectionCharset(java.nio.charset.Charset)]: [public void com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.setConnectionCharset(java.lang.String)]
2018-11-13 13:26:09.235 [main] INFO  o.s.context.support.ClassPathXmlApplicationContext - Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@13b13b5d: startup date [Tue Nov 13 13:26:09 CST 2018]; root of context hierarchy
2018-11-13 13:26:09.237 [main] INFO  o.s.beans.factory.xml.XmlBeanDefinitionReader - Loading XML bean definitions from class path resource [spring/tsdb/h2-tsdb.xml]
2018-11-13 13:26:09.317 [main] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Loading properties file from class path resource [canal.properties]
2018-11-13 13:26:09.318 [main] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Loading properties file from class path resource [example/instance.properties]
2018-11-13 13:26:09.326 [main] INFO  o.s.beans.factory.support.DefaultListableBeanFactory - Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@4e7912d8: defining beans [com.alibaba.otter.canal.instance.spring.support.PropertyPlaceholderConfigurer#0,tableMetaTSDB,dataSource,sqlMapClient,metaHistoryDAO,metaSnapshotDAO]; root of factory hierarchy
2018-11-13 13:26:09.610 [main] ERROR com.alibaba.druid.pool.DruidDataSource - testWhileIdle is true, validationQuery not set
2018-11-13 13:26:09.641 [main] INFO  com.alibaba.druid.pool.DruidDataSource - {dataSource-1} inited
2018-11-13 13:26:09.929 [main] INFO  c.a.o.c.p.inbound.mysql.tsdb.DefaultTableMetaTSDBFactory - example init TableMetaTSDB with classpath:spring/tsdb/h2-tsdb.xml
2018-11-13 13:26:09.932 [main] INFO  com.alibaba.otter.canal.prometheus.CanalInstanceExports - Successfully register metrics for instance example.
2018-11-13 13:26:09.932 [main] INFO  com.alibaba.otter.canal.prometheus.PrometheusService - Register metrics for destination example.
2018-11-13 13:26:09.932 [main] INFO  c.a.otter.canal.instance.spring.CanalInstanceWithSpring - start CannalInstance for 1-example 
2018-11-13 13:26:09.981 [destination = example , address = /10.0.0.61:3306 , EventParser] INFO  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - start heart beat.... 
2018-11-13 13:26:10.004 [destination = example , address = /10.0.0.61:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - connect MysqlConnection to /10.0.0.61:3306...
2018-11-13 13:26:10.027 [destination = example , address = /10.0.0.61:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - handshake initialization packet received, prepare the client authentication packet to send
2018-11-13 13:26:10.033 [destination = example , address = /10.0.0.61:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - client authentication packet is sent out.
2018-11-13 13:26:10.070 [destination = example , address = /10.0.0.61:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - connect MysqlConnection to /10.0.0.61:3306...
2018-11-13 13:26:10.071 [destination = example , address = /10.0.0.61:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - handshake initialization packet received, prepare the client authentication packet to send
2018-11-13 13:26:10.071 [destination = example , address = /10.0.0.61:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - client authentication packet is sent out.
2018-11-13 13:26:10.123 [main] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - subscribe filter change to .*\..*
2018-11-13 13:26:10.124 [main] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - start successful....
2018-11-13 13:26:10.124 [main] INFO  c.a.otter.canal.server.embedded.CanalServerWithEmbedded - start CanalInstances[example] successfully
2018-11-13 13:26:10.174 [destination = example , address = /10.0.0.61:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - prepare to find start position just show master status
2018-11-13 13:26:10.175 [destination = example , address = /10.0.0.61:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - disConnect MysqlConnection to /10.0.0.61:3306...
2018-11-13 13:26:10.176 [destination = example , address = /10.0.0.61:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - connect MysqlConnection to /10.0.0.61:3306...
2018-11-13 13:26:10.177 [destination = example , address = /10.0.0.61:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - handshake initialization packet received, prepare the client authentication packet to send
2018-11-13 13:26:10.208 [destination = example , address = /10.0.0.61:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - client authentication packet is sent out.
2018-11-13 13:26:10.220 [destination = example , address = /10.0.0.61:3306 , EventParser] INFO  c.a.otter.canal.parse.inbound.mysql.MysqlConnection - COM_BINLOG_DUMP with position:BinlogDumpCommandPacket[binlogPosition=4,slaveServerId=1234,binlogFileName=mysql-bin.000004,command=18]
2018-11-13 13:26:10.249 [destination = example , address = /10.0.0.61:3306 , EventParser] INFO  com.taobao.tddl.dbsync.binlog.LogEvent - common_header_len= 19, number_of_event_types= 35

**Comment by Czjcunzhang** [comment]
show slave host是正常的
mysql> show slave hosts;
+-----------+------------+-------+-----------+--------------------------------------+
| Server_id | Host       | Port  | Master_id | Slave_UUID                           |
+-----------+------------+-------+-----------+--------------------------------------+
|      1234 | 10.0.0.100 | 39032 |         1 | a4a2ada2-e705-11e8-8522-000c29257093 |
+-----------+------------+-------+-----------+--------------------------------------+

**Comment by agapple** [comment]
jstack看一下线程

**Comment by Czjcunzhang** [comment]
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.191-b12 mixed mode):

"Attach Listener" #33 daemon prio=9 os_prio=0 tid=0x00007f6290021800 nid=0xc7a waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"MultiStageCoprocessor-other-example-1" #32 daemon prio=5 os_prio=0 tid=0x00007f6298251800 nid=0xc68 runnable [0x00007f629c388000]
   java.lang.Thread.State: RUNNABLE
	at com.lmax.disruptor.BlockingWaitStrategy.waitFor(BlockingWaitStrategy.java:59)
	at com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(ProcessingSequenceBarrier.java:56)
	at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:159)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"MultiStageCoprocessor-other-example-0" #31 daemon prio=5 os_prio=0 tid=0x00007f629825a800 nid=0xc67 waiting on condition [0x00007f629c3c9000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000712e80ed0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at com.lmax.disruptor.BlockingWaitStrategy.waitFor(BlockingWaitStrategy.java:47)
	at com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(ProcessingSequenceBarrier.java:56)
	at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:159)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"destination = example , address = /10.0.0.61:3306 , HeartBeatTimeTask" #30 daemon prio=5 os_prio=0 tid=0x00007f6298010800 nid=0xc66 in Object.wait() [0x00007f629c80a000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.util.TimerThread.mainLoop(Timer.java:552)
	- locked <0x000000070f60d0e0> (a java.util.TaskQueue)
	at java.util.TimerThread.run(Timer.java:505)

"destination = example , address = /10.0.0.61:3306 , EventParser" #29 daemon prio=5 os_prio=0 tid=0x00007f62a4364000 nid=0xc65 runnable [0x00007f629c84b000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	- locked <0x0000000712e0cb60> (a java.io.BufferedInputStream)
	at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:108)
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:174)
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:77)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:216)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:252)
	at java.lang.Thread.run(Thread.java:748)

"pool-6-thread-1" #28 prio=5 os_prio=0 tid=0x00007f62a4357800 nid=0xc64 waiting on condition [0x00007f629c88c000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000070eb9c828> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"[scheduler-table-meta-snapshot]" #27 daemon prio=5 os_prio=0 tid=0x00007f62a4354000 nid=0xc63 waiting on condition [0x00007f629c8cd000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000070d6a6ba0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"MVStore background writer nio:/usr/local/canal/conf/example/h2.mv.db" #25 daemon prio=5 os_prio=0 tid=0x00007f62b005f800 nid=0xc62 in Object.wait() [0x00007f629cd0e000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.h2.mvstore.MVStore$BackgroundWriterThread.run(MVStore.java:2715)
	- locked <0x000000070dc4da90> (a java.lang.Object)

"Druid-ConnectionPool-Destroy-1252249603" #23 daemon prio=5 os_prio=0 tid=0x00007f62a42fa800 nid=0xc60 waiting on condition [0x00007f629cd4f000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at com.alibaba.druid.pool.DruidDataSource$DestroyConnectionThread.run(DruidDataSource.java:2538)

"Druid-ConnectionPool-Create-1252249603" #22 daemon prio=5 os_prio=0 tid=0x00007f62a42f9800 nid=0xc5f waiting on condition [0x00007f629cd90000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000070c842038> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2441)

"Abandoned connection cleanup thread" #21 daemon prio=5 os_prio=0 tid=0x00007f62a428e800 nid=0xc5e in Object.wait() [0x00007f629cdd1000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
	- locked <0x000000070d05efa0> (a java.lang.ref.ReferenceQueue$Lock)
	at com.mysql.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:43)

"Hashed wheel timer #1" #19 prio=5 os_prio=0 tid=0x00007f6298009000 nid=0xc5d waiting on condition [0x00007f629d412000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at org.jboss.netty.util.HashedWheelTimer$Worker.waitForNextTick(HashedWheelTimer.java:436)
	at org.jboss.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:367)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at java.lang.Thread.run(Thread.java:748)

"DestroyJavaVM" #18 prio=5 os_prio=0 tid=0x00007f62cc00c000 nid=0xc49 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"New I/O server boss #1 ([id: 0x6ce139a4, /10.0.0.100:11111])" #16 prio=5 os_prio=0 tid=0x00007f62cc7d3000 nid=0xc5b runnable [0x00007f629d694000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x0000000706324f38> (a sun.nio.ch.Util$3)
	- locked <0x0000000706324f28> (a java.util.Collections$UnmodifiableSet)
	- locked <0x0000000706324e10> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink$Boss.run(NioServerSocketPipelineSink.java:241)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"canal-instance-scan-0" #15 daemon prio=5 os_prio=0 tid=0x00007f62cc7a0800 nid=0xc5a waiting on condition [0x00007f629d6d5000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000070603b490> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"Thread-3" #14 prio=5 os_prio=0 tid=0x00007f62cc71d800 nid=0xc59 runnable [0x00007f62b8062000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x0000000702f6c7d0> (a sun.nio.ch.Util$3)
	- locked <0x0000000702f6c7c0> (a java.util.Collections$UnmodifiableSet)
	- locked <0x0000000702f6c6a8> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:352)
	at java.lang.Thread.run(Thread.java:748)

"server-timer" #13 daemon prio=5 os_prio=0 tid=0x00007f62cc718800 nid=0xc58 in Object.wait() [0x00007f62b80a3000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.util.TimerThread.mainLoop(Timer.java:552)
	- locked <0x0000000702f6dee0> (a java.util.TaskQueue)
	at java.util.TimerThread.run(Timer.java:505)

"main-EventThread" #12 daemon prio=5 os_prio=0 tid=0x00007f62cc6b5000 nid=0xc57 waiting on condition [0x00007f62b80e4000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000702c9c3d8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:491)

"main-SendThread(localhost:2181)" #11 daemon prio=5 os_prio=0 tid=0x00007f62cc6bd000 nid=0xc56 runnable [0x00007f62b8125000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x0000000702c84b68> (a sun.nio.ch.Util$3)
	- locked <0x0000000702c84ae0> (a java.util.Collections$UnmodifiableSet)
	- locked <0x0000000702c84698> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:338)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1068)

"ZkClient-EventThread-10-localhost:2181" #10 daemon prio=5 os_prio=0 tid=0x00007f62cc6a1800 nid=0xc55 waiting on condition [0x00007f62b8166000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000702c13f78> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at org.I0Itec.zkclient.ZkEventThread.run(ZkEventThread.java:68)

"Service Thread" #8 daemon prio=9 os_prio=0 tid=0x00007f62cc0db000 nid=0xc53 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread1" #7 daemon prio=9 os_prio=0 tid=0x00007f62cc0d8000 nid=0xc52 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #6 daemon prio=9 os_prio=0 tid=0x00007f62cc0d5800 nid=0xc51 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #5 daemon prio=9 os_prio=0 tid=0x00007f62cc0d3800 nid=0xc50 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Surrogate Locker Thread (Concurrent GC)" #4 daemon prio=9 os_prio=0 tid=0x00007f62cc0d2000 nid=0xc4f waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=0 tid=0x00007f62cc09f000 nid=0xc4e in Object.wait() [0x00007f62ba41d000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x0000000700008ed0> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
	- locked <0x0000000700008ed0> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:216)

"Reference Handler" #2 daemon prio=10 os_prio=0 tid=0x00007f62cc09c800 nid=0xc4d in Object.wait() [0x00007f62ba45e000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x0000000700006bf8> (a java.lang.ref.Reference$Lock)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	- locked <0x0000000700006bf8> (a java.lang.ref.Reference$Lock)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

"VM Thread" os_prio=0 tid=0x00007f62cc093000 nid=0xc4c runnable 

"Gang worker#0 (Parallel GC Threads)" os_prio=0 tid=0x00007f62cc01d000 nid=0xc4a runnable 

"Concurrent Mark-Sweep GC Thread" os_prio=0 tid=0x00007f62cc040000 nid=0xc4b runnable 

"VM Periodic Task Thread" os_prio=0 tid=0x00007f62cc0e0800 nid=0xc54 waiting on condition

**Comment by Czjcunzhang** [comment]
@agapple

**Comment by Czjcunzhang** [comment]
解决了， 虚拟机 CPU核数给了1核， canal估计要至少2核才能跑起来

**Comment by kaibi12** [comment]
修改canal.properties文件中的 canal.instance.parser.parallel 属性    改为 false就可以了
