### ISSUE TITLE
空闲链接被关闭

### ISSUE THREAD

**Issue by SteveFrank** [alibaba/canal#1139]
```
2018-11-13 15:22:59.377 [New I/O server worker #1-5] ERROR c.a.otter.canal.server.netty.handler.SessionHandler - something goes wrong with channel:[id: 0x7c3711e5, /10.174.99.91:33523 => /**.**.**.**:50401], exception=java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:322)
        at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:281)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:201)
        at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

请问1.1.1 版本这个问题需要怎么处理呢

**Comment by jianghaibolxy** [comment]
这个有解决吗？

**Comment by SteveFrank** [comment]
> 这个有解决吗？

使用 Canal - Client 的架构会偶尔出现这样的问题，但是我们换成了直接使用Canal-1.1.1，直接从canal测发送Kafka消息，重写一下发送消息相关的代码适配自己的业务，这样可以从根本上直接杜绝这个问题。

**Comment by jianghaibolxy** [comment]
意思是你们重写canal的代码吗？
