### ISSUE TITLE
canal1.1.0 exception:setl:java.lang.NullPointerException

### ISSUE THREAD

**Issue by powqabc** [alibaba/canal#1156]
pid:431 nid:21 exception:setl:java.lang.NullPointerException
at com.alibaba.otter.shared.arbitrate.impl.setl.rpc.RpcStageController.getLastData(RpcStageController.java:88)
at com.alibaba.otter.shared.arbitrate.impl.setl.rpc.LoadRpcArbitrateEvent.await(LoadRpcArbitrateEvent.java:62)
at com.alibaba.otter.shared.arbitrate.impl.setl.delegate.LoadDelegateArbitrateEvent.await(LoadDelegateArbitrateEvent.java:36)
at com.alibaba.otter.shared.arbitrate.impl.setl.delegate.LoadDelegateArbitrateEvent$$FastClassByCGLIB$$df5299b2.invoke()
at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:191)
at org.springframework.aop.framework.Cglib2AopProxy$CglibMethodInvocation.invokeJoinpoint(Cglib2AopProxy.java:689)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
at com.alibaba.otter.shared.arbitrate.impl.interceptor.LogInterceptor.invoke(LogInterceptor.java:53)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:622)
at com.alibaba.otter.shared.arbitrate.impl.setl.delegate.LoadDelegateArbitrateEvent$$EnhancerByCGLIB$$92cc207f.await()
at com.alibaba.otter.node.etl.load.LoadTask.run(LoadTask.java:55)

**Comment by agapple** [comment]
这是otter的问题，估计是当时有rollback事件发生，重启一次同步就可以恢复
