### ISSUE TITLE
c.a.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta - parse faield

### ISSUE THREAD

**Issue by zlandyberg** [alibaba/canal#1159]
2018-11-19 14:56:04.996 [destination = example , address = /192.168.47.130:3306 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta - parse faield : CREATE USER 'canal'@'%' IDENTIFIED WITH 'mysql_native_password' AS '*E3619321C1A937C46A0D8BD1DAC39F93B27D4458'
com.alibaba.fastsql.sql.parser.ParserException: syntax error, error in :'ord' AS '*E3619321C1A937C46A0D8BD1D, pos 66, line 1, column 64, token AS
	at com.alibaba.fastsql.sql.parser.SQLParser.printError(SQLParser.java:363) ~[fastsql-2.0.0_preview_644.jar:2.0.0_preview_644]
	at com.alibaba.fastsql.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:534) ~[fastsql-2.0.0_preview_644.jar:2.0.0_preview_644]
	at com.alibaba.fastsql.sql.SQLUtils.parseStatements(SQLUtils.java:525) ~[fastsql-2.0.0_preview_644.jar:2.0.0_preview_644]
	at com.alibaba.fastsql.sql.repository.SchemaRepository.console(SchemaRepository.java:439) ~[fastsql-2.0.0_preview_644.jar:2.0.0_preview_644]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta.apply(MemoryTableMeta.java:73) ~[canal.parse-1.1.1.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.applyHistoryOnMemory(DatabaseTableMeta.java:409) [canal.parse-1.1.1.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:137) [canal.parse-1.1.1.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:87) [canal.parse-1.1.1.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:190) [canal.parse-1.1.1.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_74]

这是什么错  我把canal用户删掉了 配置文件里用的root用户有这个错，后来把canal用户加上还是有问题

**Comment by spccold** [comment]
看看这个#450 ，一样的问题

**Comment by zlnickname** [comment]
> 看看这个#450 ，一样的问题

都快一年了，还没改好么

**Comment by agapple** [comment]
DCL的语法目前不支持，不影响TABLE TSDB的使用

**Comment by agapple** [comment]
先暂时忽略吧，高优先级解决alter table的问题
