### ISSUE TITLE
客户端连接报错 Error handling event ZkEvent[

### ISSUE THREAD

**Issue by jianghaibolxy** [alibaba/canal#1165]
[20 16:22:01,853 ERROR] [] [ZkClient-EventThread-67-zookeeper.dev.vivo.xyz:2183] org.I0Itec.zkclient.ZkEventThread- Error handling event ZkEvent[Data of /otter/canal/destinations/bdsp8/1001/running changed sent to com.alibaba.otter.canal.client.impl.running.ClientRunningMonitor$1@54930f4c]
com.alibaba.otter.canal.protocol.exception.CanalClientException: something goes wrong in initRunning method. 
	at com.alibaba.otter.canal.client.impl.running.ClientRunningMonitor.initRunning(ClientRunningMonitor.java:146)
	at com.alibaba.otter.canal.client.impl.running.ClientRunningMonitor$1.handleDataDeleted(ClientRunningMonitor.java:71)
	at org.I0Itec.zkclient.ZkClient$9.run(ZkClient.java:825)
	at org.I0Itec.zkclient.ZkEventThread.run(ZkEventThread.java:72)
Caused by: java.lang.NoSuchMethodError: com.alibaba.otter.canal.protocol.CanalPacket$Handshake.getSupportedCompressionsList()Ljava/util/List;
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:162)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.access$000(SimpleCanalConnector.java:51)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector$1.processActiveEnter(SimpleCanalConnector.java:449)
	at com.alibaba.otter.canal.client.impl.running.ClientRunningMonitor.processActiveEnter(ClientRunningMonitor.java:211)
	at com.alibaba.otter.canal.client.impl.running.ClientRunningMonitor.initRunning(ClientRunningMonitor.java:122)
	... 3 more

**Comment by jianghaibolxy** [comment]
版本号是1.1.0

**Comment by jianghaibolxy** [comment]
最新生产环境推荐使用1.1.1吗

**Comment by agapple** [comment]
Caused by: java.lang.NoSuchMethodError: com.alibaba.otter.canal.protocol.CanalPacket$Handshake.getSupportedCompressionsList()Ljava/util/List;

client的protobuf和你自己业务的有冲突吧，先检查这个
