### ISSUE TITLE
too long 'report-password'

### ISSUE THREAD

**Issue by code-hipster** [alibaba/canal#1166]
最新master版本，启动报错：ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[java.io.IOException: Error When doing Register slave:ErrorPacket [errorNumber=1105, fieldCount=-1, message=Failed to register slave; too long 'report-password', sqlState=HY000, sqlStateMarker=#]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.sendRegisterSlave(MysqlConnection.java:297)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:218)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:257)
	at java.lang.Thread.run(Thread.java:748)
]

**Comment by agapple** [comment]
第一次遇到，检查一下mysql的密码要求吧

**Comment by Fanduzi** [comment]
我也遇到了. 我mysql复制账号一开始是23位的密码, 后来把密码直接改短就好了. 1.1.2同样的密码没有这个问题
