### ISSUE TITLE
kafka producer  max.request.size  配置

### ISSUE THREAD

**Issue by woshijay7788** [alibaba/canal#1179]
2018-11-22 10:34:54.486 [pool-12-thread-4] ERROR com.alibaba.otter.canal.kafka.CanalKafkaProducer - org.apache.kafka.common.errors.RecordTooLargeException: The message is 1190153 bytes when serialized which is larger than the maximum request size you have configured with the max.request.size configuration.
java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.RecordTooLargeException: The message is 1190153 bytes when serialized which is larger than the maximum request size you have configured with the max.request.size configuration.
        at org.apache.kafka.clients.producer.KafkaProducer$FutureFailure.<init>(KafkaProducer.java:1150) ~[kafka-clients-1.1.1.jar:na]
        at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:846) ~[kafka-clients-1.1.1.jar:na]
        at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:784) ~[kafka-clients-1.1.1.jar:na]
        at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:671) ~[kafka-clients-1.1.1.jar:na]
        at com.alibaba.otter.canal.kafka.CanalKafkaProducer.send(CanalKafkaProducer.java:129) ~[canal.server-1.1.1.jar:na]
        at com.alibaba.otter.canal.server.CanalMQStarter.worker(CanalMQStarter.java:138) [canal.server-1.1.1.jar:na]
        at com.alibaba.otter.canal.server.CanalMQStarter.access$000(CanalMQStarter.java:21) [canal.server-1.1.1.jar:na]
        at com.alibaba.otter.canal.server.CanalMQStarter$1.run(CanalMQStarter.java:76) [canal.server-1.1.1.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_172]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_172]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_172]
Caused by: org.apache.kafka.common.errors.RecordTooLargeException: The message is 1190153 bytes when serialized which is larger than the maximum request size you have configured with the max.request.size configuration.

**Comment by agapple** [comment]
调低batch大小

**Comment by woshijay7788** [comment]
retries: 0
batchSize: 16384
lingerMs: 1
bufferMemory: 33554432

# Canal的batch size, 默认50K, 由于kafka最大消息体限制请勿超过1M(900K以下)
canalBatchSize: 50
# Canal get数据的超时时间, 单位: 毫秒, 0为不限超时
canalGetTimeout: 100
flatMessage: true

按照默认的，应该很小了吧，还是不行

**Comment by yvesyuan** [comment]
@agapple  我也碰到了这个问题, 看了源码, 应该是你们担心message大小超过kafka的默认大小1M. 但实际上kafka的是可以调整的,  你们的这个设置, 即便是kafka调整了, 你们也不允许发送给kafka.
我目前修改的是修改了你们的CanalKafkaProducer.java
增加max.request.size属性设置, 将其调大.
建议你们将这个也加到配置里面去, 允许用户手动配置调整.

**Comment by woshijay7788** [comment]
是大字段，可以提交，目前把相关大字段的表去掉了

**Comment by bruse-peng** [comment]
> [@yvesyuan](https://github.com/yvesyuan) 可以考虑把你的修改提交一个代码PR

这个是canal的限制吗？
