### ISSUE TITLE
NPE问题

### ISSUE THREAD

**Issue by dienh880426** [alibaba/canal#1192]
- mysql版本：5.6.26
- canal版本，最新的1.1.2-SNAPSHOT
- 用的是内置kafka client
- canal日志文件和instance日志文件都报该异常
- 在用最新的快照版本之前是有些instance可以跑起来，有一个也是报该异常。Issus里面没找到类似问题

2018-11-24 00:25:37.842 
[main-SendThread(cdh14.com:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x166d3d8e2d8a74b, packet:: clientPath:null serverPath:null finished:false header:: 28,3  replyHeader:: 28,38655499345,-101  request:: '/otter/canal/destinations/t_uc_linkman_info/running,T  response::  
2018-11-24 00:25:37.842 [canal-instance-scan-0] DEBUG org.I0Itec.zkclient.ZkClient - Subscribed data changes for /otter/canal/destinations/t_uc_linkman_info/running
...skipping...
java.lang.NullPointerException: null
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.afterDump(MysqlEventParser.java:139) ~[canal.parse-1.1.2-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:304) ~[canal.parse-1.1.2-SNAPSHOT.jar:na]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
2018-11-24 00:25:37.937 [main-SendThread(cdh14.com:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x166d3d8e2d8a74b, packet:: clientPath:null serverPath:null finished:false header:: 32,8  replyHeader:: 32,38655499346,0  request:: '/otter/canal/destinations/t_uc_linkman_info,F  response:: v{'running,'cluster} 
2018-11-24 00:25:37.937 [main-SendThread(cdh14.com:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x166d3d8e2d8a74b, packet:: clientPath:null serverPath:null finished:false header:: 32,8  replyHeader:: 32,38655499346,0  request:: '/otter/canal/destinations/t_uc_linkman_info,F  response:: v{'running,'cluster} 
2018-11-24 00:25:37.938 [canal-instance-scan-0] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - start successful....
2018-11-24 00:25:37.938 [canal-instance-scan-0] INFO  c.a.otter.canal.server.embedded.CanalServerWithEmbedded - start CanalInstances[t_uc_linkman_info] successfully
2018-11-24 00:25:37.938 [canal-instance-scan-0] INFO  com.alibaba.otter.canal.server.CanalMQStarter - ## Start the MQ work of destination:t_uc_linkman_info
2018-11-24 00:25:37.938 [canal-instance-scan-0] INFO  com.alibaba.otter.canal.server.CanalMQStarter - ## Start the MQ work of destination:t_uc_linkman_info
2018-11-24 00:25:37.938 [canal-instance-scan-0] INFO  c.a.o.canal.deployer.monitor.SpringInstanceConfigMonitor - auto notify start t_uc_linkman_info successful.
2018-11-24 00:25:37.938 [canal-instance-scan-0] INFO  c.a.o.canal.deployer.monitor.SpringInstanceConfigMonitor - auto notify start t_uc_linkman_info successful.
2018-11-24 00:25:37.938 [pool-3-thread-2] INFO  com.alibaba.otter.canal.server.CanalMQStarter - ## start the MQ producer: t_uc_linkman_info.
2018-11-24 00:25:37.938 [pool-3-thread-2] INFO  com.alibaba.otter.canal.server.CanalMQStarter - ## start the MQ producer: t_uc_linkman_info.
2018-11-24 00:25:37.949 [main-SendThread(cdh14.com:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x166d3d8e2d8a74b, packet:: clientPath:null serverPath:null finished:false header:: 33,1  replyHeader:: 33,38655499347,-101  request:: '/otter/canal/destinations/t_tc_project_invest_order/cluster/172.20.200.13:11111,,v{s{31,s{'world,'anyone}}},1  response::  
2018-11-24 00:25:37.949 [main-SendThread(cdh14.com:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x166d3d8e2d8a74b, packet:: clientPath:null serverPath:null finished:false header:: 33,1  replyHeader:: 33,38655499347,-101  request:: '/otter/canal/destinations/t_tc_project_invest_order/cluster/172.20.200.13:11111,,v{s{31,s{'world,'anyone}}},1  response::  
2018-11-24 00:25:37.949 [main-SendThread(cdh14.com:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x166d3d8e2d8a74b, packet:: clientPath:null serverPath:null finished:false header:: 34,4  replyHeader:: 34,38655499347,-101  request:: '/otter/canal/destinations/t_uc_linkman_info/1001/cursor,F  response::  
2018-11-24 00:25:37.949 [main-SendThread(cdh14.com:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x166d3d8e2d8a74b, packet:: clientPath:null serverPath:null finished:false header:: 34,4  replyHeader:: 34,38655499347,-101  request:: '/otter/canal/destinations/t_uc_linkman_info/1001/cursor,F  response::  
2018-11-24 00:25:37.949 [pool-3-thread-2] INFO  c.a.otter.canal.server.embedded.CanalServerWithEmbedded - subscribe successfully, ClientIdentity[destination=t_uc_linkman_info,clientId=1001,filter=] with first position:null 
2018-11-24 00:25:37.949 [pool-3-thread-2] INFO  c.a.otter.canal.server.embedded.CanalServerWithEmbedded - subscribe successfully, ClientIdentity[destination=t_uc_linkman_info,clientId=1001,filter=] with first position:null 
2018-11-24 00:25:37.949 [pool-3-thread-2] INFO  com.alibaba.otter.canal.server.CanalMQStarter - ## the MQ producer: t_uc_linkman_info is running now ......
2018-11-24 00:25:37.949 [pool-3-thread-2] INFO  com.alibaba.otter.canal.server.CanalMQStarter - ## the MQ producer: t_uc_linkman_info is running now ......
2018-11-24 00:25:37.957 [main-SendThread(cdh14.com:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x166d3d8e2d8a74b, packet:: clientPath:null serverPath:null finished:false header:: 35,1  replyHeader:: 35,38655499348,0  request:: '/otter/canal/destinations/t_uc_linkman_info/1001,,v{s{31,s{'world,'anyone}}},0  response:: '/otter/canal/destinations/t_uc_linkman_info/1001 
2018-11-24 00:25:37.957 [main-SendThread(cdh14.com:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x166d3d8e2d8a74b, packet:: clientPath:null serverPath:null finished:false header:: 35,1  replyHeader:: 35,38655499348,0  request:: '/otter/canal/destinations/t_uc_linkman_info/1001,,v{s{31,s{'world,'anyone}}},0  response:: '/otter/canal/destinations/t_uc_linkman_info/1001 
2018-11-24 00:25:37.962 [main-SendThread(cdh14.com:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x166d3d8e2d8a74b, packet:: clientPath:null serverPath:null finished:false header:: 36,1  replyHeader:: 36,38655499349,-101  request:: '/otter/canal/destinations/t_tc_project_invest_order/cluster,,v{s{31,s{'world,'anyone}}},0  response::  
2018-11-24 00:25:37.962 [main-SendThread(cdh14.com:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x166d3d8e2d8a74b, packet:: clientPath:null serverPath:null finished:false header:: 36,1  replyHeader:: 36,38655499349,-101  request:: '/otter/canal/destinations/t_tc_project_invest_order/cluster,,v{s{31,s{'world,'anyone}}},0  response::  
2018-11-24 00:25:37.962 [main-SendThread(cdh14.com:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x166d3d8e2d8a74b, packet:: clientPath:null serverPath:null finished:false header:: 37,8  replyHeader:: 37,38655499349,-101  request:: '/otter/canal/destinations/t_uc_linkman_info/1001/mark,F  response:: v{} 
2018-11-24 00:25:37.962 [main-SendThread(cdh14.com:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x166d3d8e2d8a74b, packet:: clientPath:null serverPath:null finished:false header:: 37,8  replyHeader:: 37,38655499349,-101  request:: '/otter/canal/destinations/t_uc_linkman_info/1001/mark,F  response:: v{} 
2018-11-24 00:25:37.970 [main-SendThread(cdh14.com:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x166d3d8e2d8a74b, packet:: clientPath:null serverPath:null finished:false header:: 38,1  replyHeader:: 38,38655499350,0  request:: '/otter/canal/destinations/t_tc_project_invest_order,,v{s{31,s{'world,'anyone}}},0  response:: '/otter/canal/destinations/t_tc_project_invest_order 
2018-11-24 00:25:37.970 [main-SendThread(cdh14.com:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x166d3d8e2d8a74b, packet:: clientPath:null serverPath:null finished:false header:: 38,1  replyHeader:: 38,38655499350,0  request:: '/otter/canal/destinations/t_tc_project_invest_order,,v{s{31,s{'world,'anyone}}},0  response:: '/otter/canal/destinations/t_tc_project_invest_order 
2018-11-24 00:25:37.983 [main-SendThread(cdh14.com:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x166d3d8e2d8a74b, packet:: clientPath:null serverPath:null finished:false header:: 39,1  replyHeader:: 39,38655499351,0  request:: '/otter/canal/destinations/t_tc_project_invest_order/cluster,,v{s{31,s{'world,'anyone}}},0  response:: '/otter/canal/destinations/t_tc_project_invest_order/cluster 
2018-11-24 00:25:37.983 [main-SendThread(cdh14.com:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x166d3d8e2d8a74b, packet:: clientPath:null serverPath:null finished:false header:: 39,1  replyHeader:: 39,38655499351,0  request:: '/otter/canal/destinations/t_tc_project_invest_order/cluster,,v{s{31,s{'world,'anyone}}},0  response:: '/otter/canal/destinations/t_tc_project_invest_order/cluster 
2018-11-24 00:25:37.995 [main-SendThread(cdh14.com:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x166d3d8e2d8a74b, packet:: clientPath:null serverPath:null finished:false header:: 40,1  replyHeader:: 40,38655499352,0  request:: '/otter/canal/destinations/t_tc_project_invest_order/cluster/172.20.200.13:11111,,v{s{31,s{'world,'anyone}}},1  response:: '/otter/canal/destinations/t_tc_project_invest_order/cluster/172.20.200.13:11111 
2018-11-24 00:25:37.995 [main-SendThread(cdh14.com:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x166d3d8e2d8a74b, packet:: clientPath:null serverPath:null finished:false header:: 40,1  replyHeader:: 40,38655499352,0  request:: '/otter/canal/destinations/t_tc_project_invest_order/cluster/172.20.200.13:11111,,v{s{31,s{'world,'anyone}}},1  response:: '/otter/canal/destinations/t_tc_project_invest_order/cluster/172.20.200.13:11111 
2018-11-24 00:25:38.004 [main-SendThread(cdh14.com:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x166d3d8e2d8a74b, packet:: clientPath:null serverPath:null finished:false header:: 41,1  replyHeader:: 41,38655499353,-110  request:: '/otter/canal
...skipping...
java.lang.NullPointerException: null
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.afterDump(MysqlEventParser.java:139) ~[canal.parse-1.1.2-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:304) ~[canal.parse-1.1.2-SNAPSHOT.jar:na]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
2018-11-24 00:25:38.089 [main-SendThread(cdh14.com:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x166d3d8e2d8a74b, packet:: clientPath:null serverPath:null finished:false header:: 46,8  replyHeader:: 46,38655499354,0  request:: '/otter/canal/destinations/t_tc_project_invest_order,F  response:: v{'running,'cluster} 
2018-11-24 00:25:38.089 [main-SendThread(cdh14.com:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x166d3d8e2d8a74b, packet:: clientPath:null serverPath:null finished:false header:: 46,8  replyHeader:: 46,38655499354,0  request:: '/otter/canal/destinations/t_tc_project_invest_order,F  response:: v{'running,'cluster} 
2018-11-24 00:25:38.089 [canal-instance-scan-0] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - start successful....
2018-11-24 00:25:38.089 [canal-instance-scan-0] INFO  c.a.otter.canal.server.embedded.CanalServerWithEmbedded - start CanalInstances[t_tc_project_invest_order] successfully
2018-11-24 00:25:38.089 [canal-instance-scan-0] INFO  com.alibaba.otter.canal.server.CanalMQStarter - ## Start the MQ work of destination:t_tc_project_invest_order
2018-11-24 00:25:38.089 [canal-instance-scan-0] INFO  com.alibaba.otter.canal.server.CanalMQStarter - ## Start the MQ work of destination:t_tc_project_invest_order
2018-11-24 00:25:38.090 [canal-instance-scan-0] INFO  c.a.o.canal.deployer.monitor.SpringInstanceConfigMonitor - auto notify start t_tc_project_invest_order successful.
2018-11-24 00:25:38.090 [canal-instance-scan-0] INFO  c.a.o.canal.deployer.monitor.SpringInstanceConfigMonitor - auto notify start t_tc_project_invest_order successful.
2018-11-24 00:25:38.090 [pool-3-thread-3] INFO  com.alibaba.otter.canal.server.CanalMQStarter - ## start the MQ producer: t_tc_project_invest_order.
2018-11-24 00:25:38.090 [pool-3-thread-3] INFO  com.alibaba.otter.canal.server.CanalMQStarter - ## start the MQ producer: t_tc_project_invest_order.
2018-11-24 00:25:38.091 [main-SendThread(cdh14.com:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x166d3d8e2d8a74b, packet:: clientPath:null serverPath:null finished:false header:: 47,4  replyHeader:: 47,38655499354,-101  request:: '/otter/canal/destinations/t_tc_project_invest_order/1001/cursor,F  response::  
2018-11-24 00:25:38.091 [main-SendThread(cdh14.com:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x166d3d8e2d8a74b, packet:: clientPath:null serverPath:null finished:false header:: 47,4  replyHeader:: 47,38655499354,-101  request:: '/otter/canal/destinations/t_tc_project_invest_order/1001/cursor,F  response::  
2018-11-24 00:25:38.091 [pool-3-thread-3] INFO  c.a.otter.canal.server.embedded.CanalServerWithEmbedded - subscribe successfully, ClientIdentity[destination=t_tc_project_invest_order,clientId=1001,filter=] with first position:null 
2018-11-24 00:25:38.091 [pool-3-thread-3] INFO  c.a.otter.canal.server.embedded.CanalServerWithEmbedded - subscribe successfully, ClientIdentity[destination=t_tc_project_invest_order,clientId=1001,filter=] with first position:null 
2018-11-24 00:25:38.091 [pool-3-thread-3] INFO  com.alibaba.otter.canal.server.CanalMQStarter - ## the MQ producer: t_tc_project_invest_order is running now ......
2018-11-24 00:25:38.091 [pool-3-thread-3] INFO  com.alibaba.otter.canal.server.CanalMQStarter - ## the MQ producer: t_tc_project_invest_order is running now ......
2018-11-24 00:25:38.102 [main-SendThread(cdh14.com:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x166d3d8e2d8a74b, packet:: clientPath:null serverPath:null finished:false header:: 48,1  replyHeader:: 48,38655499355,0  request:: '/otter/canal/destinations/t_tc_project_invest_order/1001,,v{s{31,s{'world,'anyone}}},0  response:: '/otter/canal/destinations/t_tc_project_invest_order/1001 
2018-11-24 00:25:38.102 [main-SendThread(cdh14.com:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x166d3d8e2d8a74b, packet:: clientPath:null serverPath:null finished:false header:: 48,1  replyHeader:: 48,38655499355,0  request:: '/otter/canal/destinations/t_tc_project_invest_order/1001,,v{s{31,s{'world,'anyone}}},0  response:: '/otter/canal/destinations/t_tc_project_invest_order/1001 
2018-11-24 00:25:38.103 [main-SendThread(cdh14.com:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x166d3d8e2d8a74b, packet:: clientPath:null serverPath:null finished:false header:: 49,8  replyHeader:: 49,38655499355,-101  request:: '/otter/canal/destinations/t_tc_project_invest_order/1001/mark,F  response:: v{} 
2018-11-24 00:25:38.103 [main-SendThread(cdh14.com:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x166d3d8e2d8a74b, packet:: clientPath:null serverPath:null finished:false header:: 49,8  replyHeader:: 49,38655499355,-101  request:: '/otter/canal/destinations/t_tc_project_invest_order/1001/mark,F  response:: v{} 
2018-11-24 00:25:58.095 [main-SendThread(cdh14.com:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Got ping response for sessionid: 0x166d3d8e2d8a74b after 1ms
2018-11-24 00:25:58.095 [main-SendThread(cdh14.com:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Got ping response for sessionid: 0x166d3d8e2d8a74b after 1ms
2018-11-24 00:26:18.115 [main-SendThread(cdh14.com:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Got ping response for sessionid: 0x166d3d8e2d8a74b after 1ms
2018-11-24 00:26:18.115 [main-SendThread(cdh14.com:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Got ping response for sessionid: 0x166d3d8e2d8a74b after 1ms
2018-11-24 00:26:38.133 [main-SendThread(cdh14.com:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Got ping response for sessionid: 0x166d3d8e2d8a74b after 1ms
2018-11-24 00:26:38.133 [main-SendThread(cdh14.com:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Got ping response for sessionid: 0x166d3d8e2d8a74b after 1ms
2018-11-24 00:26:58.152 [main-SendThread(cdh14.com:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Got ping response for sessionid: 0x166d3d8e2d8a74b after 1ms
2018-11-24 00:26:58.152 [main-SendThread(cdh14.com:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Got ping response for sessionid: 0x166d3d8e2d8a74b after 1ms
2018-11-24 00:27:18.173 [main-SendThread(cdh14.com:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Got ping response for sessionid: 0x166d3d8e2d8a74b after 2ms
2018-11-24 00:27:18.173 [main-SendThread(cdh14.com:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Got ping response for sessionid: 0x166d3d8e2d8a74b after 2ms
2018-11-24 00:27:38.193 [main-SendThread(cdh14.com:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Got ping response for sessionid: 0x166d3d8e2d8a74b after 1ms
2018-11-24 00:27:38.193 [main-SendThread(cdh14.com:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Got ping response for sessionid: 0x166d3d8e2d8a74b after 1ms
2018-11-24 00:27:58.205 [main-SendThread(cdh14.com:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Got ping response for sessionid: 0x166d3d8e2d8a74b after 1ms
2018-11-24 00:27:58.205 [main-SendThread(cdh14.com:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Got ping response for sessionid: 0x166d3d8e2d8a74b after 1ms
2018-11-24 00:28:18.226 [main-SendThread(cdh14.com:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Got ping response for sessionid: 0x166d3d8e2d8a74b after 1ms
2018-11-24 00:28:18.226 [main-SendThread(cdh14.com:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Got ping response for sessionid: 0x166d3d8e2d8a74b after 1ms
2018-11-24 00:28:38.241 [main-SendThread(cdh14.com:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Got ping response for sessionid: 0x166d3d8e2d8a74b after 1ms

**Comment by agapple** [comment]
本地没有重现，有条件的话做一下代码debug

**Comment by dienh880426** [comment]
- 本地不好重现
- 现在大概理清了重现步骤，这边又重新部署了一遍。步骤如下
1. 第一次启动前配置为自动扫描且自定义扫描目录,并在instance目录下添加一个instance
```
canal.destinations = 
# conf root dir
canal.conf.dir = ../instance
```
2. 启动并测试第一个instance能将数据发送到kafka
3. 准备好另一个instance并拷贝到instance目录下，能自动scan到，但instance日志里面报错如下，跟之前一样

2018-11-25 15:40:20.748 [canal-instance-scan-0] DEBUG o.s.core.env.PropertySourcesPropertyResolver - Could not find key 'spring.liveBeansView.mbeanDomain' in any property source. Returning [null]
2018-11-25 15:40:20.748 [canal-instance-scan-0] DEBUG o.s.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'tableMetaTSDB'
2018-11-25 15:40:20.748 [canal-instance-scan-0] INFO  c.a.o.c.p.inbound.mysql.tsdb.DefaultTableMetaTSDBFactory - t_tc_project init TableMetaTSDB with classpath:spring/tsdb/h2-tsdb.xml
2018-11-25 15:40:20.748 [canal-instance-scan-0] DEBUG o.s.beans.factory.support.DefaultListableBeanFactory - Finished creating instance of bean 'eventParser'
2018-11-25 15:40:20.749 [canal-instance-scan-0] DEBUG o.s.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'eventSink'
2018-11-25 15:40:20.749 [canal-instance-scan-0] DEBUG o.s.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'eventStore'
2018-11-25 15:40:20.749 [canal-instance-scan-0] DEBUG o.s.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'metaManager'
2018-11-25 15:40:20.749 [canal-instance-scan-0] DEBUG o.s.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'alarmHandler'
2018-11-25 15:40:20.749 [canal-instance-scan-0] DEBUG o.s.beans.factory.support.DefaultListableBeanFactory - Creating shared instance of singleton bean 'mqConfig'
2018-11-25 15:40:20.749 [canal-instance-scan-0] DEBUG o.s.beans.factory.support.DefaultListableBeanFactory - Creating instance of bean 'mqConfig'
2018-11-25 15:40:20.749 [canal-instance-scan-0] DEBUG o.s.beans.factory.support.DefaultListableBeanFactory - Eagerly caching bean 'mqConfig' to allow for resolving potential circular references
2018-11-25 15:40:20.749 [canal-instance-scan-0] DEBUG o.s.beans.factory.support.DefaultListableBeanFactory - Finished creating instance of bean 'mqConfig'
2018-11-25 15:40:20.749 [canal-instance-scan-0] DEBUG o.s.beans.factory.support.DefaultListableBeanFactory - Finished creating instance of bean 'instance'
2018-11-25 15:40:20.749 [canal-instance-scan-0] DEBUG o.s.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'alarmHandler'
2018-11-25 15:40:20.749 [canal-instance-scan-0] DEBUG o.s.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'zkClientx'
2018-11-25 15:40:20.749 [canal-instance-scan-0] DEBUG o.s.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'metaManager'
2018-11-25 15:40:20.749 [canal-instance-scan-0] DEBUG o.s.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'eventStore'
2018-11-25 15:40:20.749 [canal-instance-scan-0] DEBUG o.s.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'eventSink'
2018-11-25 15:40:20.749 [canal-instance-scan-0] DEBUG o.s.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'eventParser'
2018-11-25 15:40:20.749 [canal-instance-scan-0] DEBUG o.s.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'mqConfig'
2018-11-25 15:40:20.749 [canal-instance-scan-0] DEBUG o.s.context.support.ClassPathXmlApplicationContext - Unable to locate LifecycleProcessor with name 'lifecycleProcessor': using default [org.springframework.context.support.DefaultLifecycleProcessor@a044b]
2018-11-25 15:40:20.749 [canal-instance-scan-0] DEBUG o.s.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'lifecycleProcessor'
2018-11-25 15:40:20.749 [canal-instance-scan-0] DEBUG o.s.core.env.PropertySourcesPropertyResolver - Searching for key 'spring.liveBeansView.mbeanDomain' in [systemProperties]
2018-11-25 15:40:20.750 [canal-instance-scan-0] DEBUG o.s.core.env.PropertySourcesPropertyResolver - Searching for key 'spring.liveBeansView.mbeanDomain' in [systemEnvironment]
2018-11-25 15:40:20.750 [canal-instance-scan-0] DEBUG o.s.core.env.PropertySourcesPropertyResolver - Could not find key 'spring.liveBeansView.mbeanDomain' in any property source. Returning [null]
2018-11-25 15:40:20.750 [canal-instance-scan-0] DEBUG o.s.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'instance'
2018-11-25 15:40:20.750 [canal-instance-scan-0] INFO  com.alibaba.otter.canal.prometheus.CanalInstanceExports - Successfully register metrics for instance t_tc_project.
2018-11-25 15:40:20.750 [canal-instance-scan-0] INFO  com.alibaba.otter.canal.prometheus.PrometheusService - Register metrics for destination t_tc_project.
2018-11-25 15:40:20.750 [canal-instance-scan-0] INFO  c.a.otter.canal.instance.spring.CanalInstanceWithSpring - start CannalInstance for 1-t_tc_project 
2018-11-25 15:40:20.753 [canal-instance-scan-0] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - start successful....
2018-11-25 15:40:20.753 [canal-instance-scan-0] INFO  c.a.otter.canal.server.embedded.CanalServerWithEmbedded - start CanalInstances[t_tc_project] successfully
2018-11-25 15:40:20.759 [destination = t_tc_project , address = null , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - parse events has an error
java.lang.NullPointerException: null
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.afterDump(MysqlEventParser.java:139) ~[canal.parse-1.1.2-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:304) ~[canal.parse-1.1.2-SNAPSHOT.jar:na]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
(END)

**Comment by agapple** [comment]
![image](https://user-images.githubusercontent.com/834743/48977655-72d60c00-f0d9-11e8-8d14-a4a9e9850920.png)

不太确定你是拿的1.1.2的哪个commit的代码，如果是139行的报错是connection对象为空，这个也不太可能

**Comment by agapple** [comment]
我本地用最新的代码按照你的操作步骤实验了，没发现这个问题.  你先用最新的master代码再测试一次

**Comment by dienh880426** [comment]
![image](https://user-images.githubusercontent.com/19534785/48979265-1253c880-f0f3-11e8-8968-6a0737fd3b59.png)

- 再次更新后，重新部署了一遍，还是一样的问题。
- 日志显示139行确实有点不解。
- ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - parse events has an error 为啥是rds这个类的错误

**Comment by agapple** [comment]
@dienh880426 再更新一下代码，我加了点空值判断，再帮我测试一下看看，或者你自己加更多的日志

**Comment by dienh880426** [comment]
2018-11-25 21:37:23.142 [destination = t_tc_project , address = null , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - parse events has an error
com.alibaba.otter.canal.parse.exception.CanalParseException: illegal connection is null

确实是空的，有可能是什么原因引起的呢

**Comment by agapple** [comment]
除非是MysqlEventParser .buildErosaConnection返回了异常

**Comment by dienh880426** [comment]
![image](https://user-images.githubusercontent.com/19534785/48980978-d298db00-f10a-11e8-8379-e60fafe40382.png)

远程debug了下，address为null引起的。用户是retl，但instance里面配的是跟第一个可用的instance一样为canal

**Comment by dienh880426** [comment]
原因大概找到了，是自定义的配置目录（非../conf目录），后面新增的实例属性资源，spring没有加载到，导致用的默认配置

**Comment by agapple** [comment]
找到问题就好
