### ISSUE TITLE
v1.1.2 adapter 启动主线程失败

### ISSUE THREAD

**Issue by Near-Zhang** [alibaba/canal#1203]
失败日志：
>Exception in thread "main" java.lang.IllegalArgumentException: Cannot instantiate interface org.springframework.context.ApplicationContextInitializer : org.springframework.boot.autoconfigure.SharedMetadataReaderFactoryContextInitializer
        at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:448)
        at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:427)
        at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:418)
        at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:266)
        at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:247)
        at com.alibaba.otter.canal.adapter.launcher.CanalAdapterApplication.main(CanalAdapterApplication.java:17)
Caused by: java.lang.NoClassDefFoundError: org/springframework/core/KotlinDetector
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:169)
        at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:444)
        ... 5 more
Caused by: java.lang.ClassNotFoundException: org.springframework.core.KotlinDetector
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more

**Comment by yyjjww00** [comment]
老哥，解决了吗。我也有一样的问题

**Comment by adam-lsc** [comment]
> 老哥，解决了吗。我也有一样的问题
1.1.2确实有这个问题，直接下载1.1.3的 adapter 就好了。https://github.com/alibaba/canal/releases
