### ISSUE TITLE
1.0.25升级到1.1.2无法启动server

### ISSUE THREAD

**Issue by xuminwlt** [alibaba/canal#1204]
修改debug模式后一直在循环

```
2018-11-27 19:14:49.299 [destination = example , address = /10.200.200.8:3306 , EventParser] DEBUG c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - set EntryPosition[included=false,journalName=mysql_bin.000025,position=1823164,serverId=1001,gtid=<null>,timestamp=1530344599000] to be pending start position before finding another proper one...
2018-11-27 19:14:52.106 [destination = example , address = /10.200.200.8:3306 , EventParser] DEBUG c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - set EntryPosition[included=false,journalName=mysql_bin.000025,position=3645838,serverId=1001,gtid=<null>,timestamp=1530344599000] to be pending start position before finding another proper one...
2018-11-27 19:14:52.107 [destination = example , address = /10.200.200.8:3306 , EventParser] DEBUG c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - set EntryPosition[included=false,journalName=mysql_bin.000025,position=3645983,serverId=1001,gtid=<null>,timestamp=1530344602000] to be pending start position before finding another proper one...
2018-11-27 19:14:55.216 [destination = example , address = /10.200.200.8:3306 , EventParser] DEBUG c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - set EntryPosition[included=false,journalName=mysql_bin.000025,position=5468676,serverId=1001,gtid=<null>,timestamp=1530344602000] to be pending start position before finding another proper one...

```

查看端口，11111没有生成
min-xufpdeMacBook-Pro% netstat -an | grep 11111
min-xufpdeMacBook-Pro% netstat -an | grep 11112
tcp46      0      0  *.11112                *.*                    LISTEN

关闭时提示
```
2018-11-27 19:17:22.480 [destination = example , address = /10.200.200.8:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - parse events has an error
com.alibaba.otter.canal.parse.exception.CanalParseException: dump address /10.200.200.8:3306 has an error, retrying. 
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: com.alibaba.otter.canal.parse.exception.CanalParseException: com.alibaba.otter.canal.parse.exception.CanalParseException: fetch failed by table meta:`fotoplacedb2`.`user_tags`
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: com.alibaba.otter.canal.parse.exception.CanalParseException: fetch failed by table meta:`fotoplacedb2`.`user_tags`
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: fetch failed by table meta:`fotoplacedb2`.`user_tags`
Caused by: java.io.IOException: should execute connector.connect() first
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlQueryExecutor.<init>(MysqlQueryExecutor.java:30) ~[classes/:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.query(MysqlConnection.java:104) ~[classes/:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.TableMetaCache.getTableMeta(TableMetaCache.java:170) ~[classes/:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.getTableMeta(LogEventConvert.java:915) ~[classes/:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseRowsEventForTableMeta(LogEventConvert.java:475) ~[classes/:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:274) ~[classes/:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:246) ~[classes/:na]
	at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168) ~[disruptor-3.4.2.jar:na]
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125) ~[disruptor-3.4.2.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_101]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_101]
```
再次启动并关闭每次提示的 table 会变化

1.0.25一直跑的很正常

**Comment by xuminwlt** [comment]
我的问题，配置了kafka，issue close
