### ISSUE TITLE
RocketMQCanalConnector#subscribe(String filter) 这个入参filter的实际作用是什么,filter不应该就是tag吗, 根据tag做消息筛选,然而这个filter入参都没有用到, 和接口定义的功能不符合

### ISSUE THREAD

**Issue by sunlightzy** [alibaba/canal#1220]
`rocketMQConsumer.subscribe(this.topic, "*"); ` 不是应该替换成 
 `rocketMQConsumer.subscribe(this.topic, filter); ` 更加合理吗
```java
    public synchronized void subscribe(String filter) throws CanalClientException {
        if (connected) {
            return;
        }
        try {
            if (rocketMQConsumer == null) {
                this.connect();
            }
            rocketMQConsumer.subscribe(this.topic, "*");
            rocketMQConsumer.registerMessageListener(new MessageListenerOrderly() {

                @Override
                public ConsumeOrderlyStatus consumeMessage(List<MessageExt> messageExts, ConsumeOrderlyContext context) {
                    context.setAutoCommit(true);
                    boolean isSuccess = process(messageExts);
                    if (isSuccess) {
                        return ConsumeOrderlyStatus.SUCCESS;
                    } else {
                        return ConsumeOrderlyStatus.SUSPEND_CURRENT_QUEUE_A_MOMENT;
                    }
                }
            });
            rocketMQConsumer.start();
        } catch (MQClientException ex) {
            connected = false;
            logger.error("Start RocketMQ consumer error", ex);
        }
        connected = true;
    }
```

**Comment by sunlightzy** [comment]
一个topic里 不可能全都是canal发的消息,也有别的业务系统发的消息,这些消息都是通过tag区分的, 然而`rocketMQConsumer.subscribe(this.topic, "*");` 这里订阅了所有的tag,那RocketMQCanalConnector 解析到其他系统的消息就出错了

**Comment by sunlightzy** [comment]
服务端发送消息也没有tag 
`com.alibaba.otter.canal.rocketmq.CanalRocketMQProducer#send`,
 应该做成可配置吧 
```java
Message message = new Message(destination.getTopic(), CanalMessageSerializer.serializer(data, mqProperties.isFilterTransactionEntry()));
```

**Comment by agapple** [comment]
目前filter主要发生在写入MQ这一段，后续可以考虑将表名加到tag里，允许客户端进行过滤

**Comment by duhengforever** [comment]
@sunlightzy 现在我们在收集下需求，有什么具体的需求可以详细说下吗？

**Comment by sunlightzy** [comment]
> @sunlightzy 现在我们在收集下需求，有什么具体的需求可以详细说下吗？
@duhengforever 
1. `server`端`RocketMQ`的消息可以全都投递到指定的`tag`,或者自动根据库+表的名字自动生成`tag`两种策略. 
       现实: 目前的模式是以`topic`维度,而不指定`tag`, 消费端也必须按照topic的维度去订阅也就是`tag="*"`,没有细化到`tag`, 这里可以考虑我上面说的用入参`filter`作为`tag`
       一个案例:  当一个项目共用一个`topic `时, 只要`topic`中包含了其他业务消息, 消费端就会报错,因为消费端订阅`tag="*" `
2. `client`端也有 `subscribe(String filter)`, 目前这个`filter`入参是没有用上的, 可以用这个参数指定`tags`,替代`rocketMQConsumer.subscribe(this.topic, "*");`

除此之外还有另外一点:
描述:  一次测试Client端的`ClusterCanalConnector`，我看这个类的注释是写的**自带了failover功能**, 但是测试时误操作把所有的`canal-server`都停掉了, 然后过了几个小时, 机器磁盘被`error`日志打爆了, 虽然是一个误操作, 但是也不应该日志打爆磁盘, 看了一下代码,有这么一个递归方法: 
`com.alibaba.otter.canal.client.impl.running.ClientRunningMonitor#initRunning`
```java
    public synchronized void initRunning() {
        if (!isStart()) {
            return;
        }
        String path = ZookeeperPathUtils.getDestinationClientRunning(this.destination, clientData.getClientId());
        // 序列化
        byte[] bytes = JsonUtils.marshalToByte(clientData);
        try {
            mutex.set(false);
            zkClient.create(path, bytes, CreateMode.EPHEMERAL);
            processActiveEnter();// 触发一下事件
            activeData = clientData;
            mutex.set(true);
        } catch (ZkNodeExistsException e) {
            bytes = zkClient.readData(path, true);
            if (bytes == null) {// 如果不存在节点，立即尝试一次
                initRunning();
            } else {
                activeData = JsonUtils.unmarshalFromByte(bytes, ClientRunningData.class);
                // 如果发现已经存在,判断一下是否自己,避免活锁
                if (activeData.getAddress().contains(":") && isMine(activeData.getAddress())) {
                    mutex.set(true);
                }
            }
        } catch (ZkNoNodeException e) {
            zkClient.createPersistent(ZookeeperPathUtils.getClientIdNodePath(this.destination, clientData.getClientId()),
                true); // 尝试创建父节点
            initRunning();
        } catch (Throwable t) {
            logger.error(MessageFormat.format("There is an error when execute initRunning method, with destination [{0}].",
                destination),
                t);
            // 出现任何异常尝试release
            releaseRunning();
            throw new CanalClientException("something goes wrong in initRunning method. ", t);
        }
    }
```
日志内容全都是重复的,重复内容如下, 非常的可怕, 我本地也试了一下, 仅仅10多秒钟就把IDE工具打爆了,然后看到了递归方法也就不惊讶了, 虽然是误操作, 但是这种防护措施希望还是做一下的好,不要一直递归:
```sh
199834 [ZkClient-EventThread-11-127.0.0.1:2181] ERROR org.I0Itec.zkclient.ZkEventThread - Error handling event ZkEvent[Data of /otter/canal/destinations/example/1001/running changed sent to com.alibaba.otter.canal.client.impl.running.ClientRunningMonitor$1@135c8bd8] 
com.alibaba.otter.canal.protocol.exception.CanalClientException: something goes wrong in initRunning method. 
	at com.alibaba.otter.canal.client.impl.running.ClientRunningMonitor.initRunning(ClientRunningMonitor.java:146)
	at com.alibaba.otter.canal.client.impl.running.ClientRunningMonitor$1.handleDataDeleted(ClientRunningMonitor.java:71)
	at org.I0Itec.zkclient.ZkClient$9.run(ZkClient.java:825)
	at org.I0Itec.zkclient.ZkEventThread.run(ZkEventThread.java:72)
Caused by: com.alibaba.otter.canal.protocol.exception.CanalClientException: no alive canal server
	at com.alibaba.otter.canal.client.impl.ClusterNodeAccessStrategy.nextNode(ClusterNodeAccessStrategy.java:76)
	at com.alibaba.otter.canal.client.impl.ClusterCanalConnector$1.getNextAddress(ClusterCanalConnector.java:51)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:146)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.access$000(SimpleCanalConnector.java:50)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector$1.processActiveEnter(SimpleCanalConnector.java:422)
	at com.alibaba.otter.canal.client.impl.running.ClientRunningMonitor.processActiveEnter(ClientRunningMonitor.java:211)
	at com.alibaba.otter.canal.client.impl.running.ClientRunningMonitor.initRunning(ClientRunningMonitor.java:122)
	... 3 common frames omitted
199835 [ZkClient-EventThread-11-127.0.0.1:2181] ERROR c.a.o.c.c.i.r.ClientRunningMonitor - There is an error when execute initRunning method, with destination [example]. 
com.alibaba.otter.canal.protocol.exception.CanalClientException: no alive canal server
	at com.alibaba.otter.canal.client.impl.ClusterNodeAccessStrategy.nextNode(ClusterNodeAccessStrategy.java:76)
	at com.alibaba.otter.canal.client.impl.ClusterCanalConnector$1.getNextAddress(ClusterCanalConnector.java:51)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:146)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.access$000(SimpleCanalConnector.java:50)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector$1.processActiveEnter(SimpleCanalConnector.java:422)
	at com.alibaba.otter.canal.client.impl.running.ClientRunningMonitor.processActiveEnter(ClientRunningMonitor.java:211)
	at com.alibaba.otter.canal.client.impl.running.ClientRunningMonitor.initRunning(ClientRunningMonitor.java:122)
	at com.alibaba.otter.canal.client.impl.running.ClientRunningMonitor$1.handleDataDeleted(ClientRunningMonitor.java:71)
	at org.I0Itec.zkclient.ZkClient$9.run(ZkClient.java:825)
	at org.I0Itec.zkclient.ZkEventThread.run(ZkEventThread.java:72)
199837 [ZkClient-EventThread-11-127.0.0.1:2181] ERROR org.I0Itec.zkclient.ZkEventThread - Error handling event ZkEvent[Data of /otter/canal/destinations/example/1001/running changed sent to com.alibaba.otter.canal.client.impl.running.ClientRunningMonitor$1@135c8bd8] 
com.alibaba.otter.canal.protocol.exception.CanalClientException: something goes wrong in initRunning method. 
```

**Comment by duhengforever** [comment]
@sunlightzy 那个tag的需求我们在考虑实现，或者你也可以提个PR，包括下面的那个优化，有没有兴趣也提个PR优化一下，为开源社区贡献一下，我们来帮你完成这些PR。

**Comment by sunlightzy** [comment]
> @sunlightzy 那个tag的需求我们在考虑实现，或者你也可以提个PR，包括下面的那个优化，有没有兴趣也提个PR优化一下，为开源社区贡献一下，我们来帮你完成这些PR。

of course, 这些我还没自测完, 最近太忙, 周末我会继续

**Comment by agapple** [comment]
@sunlightzy 重试过于频繁的做了下sleep处理
