### ISSUE TITLE
canal_adapter消费消息到mariadb时，语法报错

### ISSUE THREAD

**Issue by Near-Zhang** [alibaba/canal#1224]
源数据库使用命令：
``` sql
INSERT INTO `mirror` (`id`, `key`, `value`, `type`, `op_time`) VALUES     (3,'3','{}','meta','2016-11-11 11:11:11');
```

adapter 报错：
>com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'key) VALUES ('2016-11-11 11:11:11',3,'meta','{}','3')' at line 1

按现在情况看来，同步过来的语句是比源语句少了 `` 转义的，因此产生的语法错误，请问一下有什么方法可以避免这个问题？

**Comment by Near-Zhang** [comment]
> 应该是jdbc驱动的问题, 把canal-adapter/lib 中的mysql-connector-java-5.1.40.jar删掉, 替换对应mariadb的jdbc

 把驱动文件替换掉之后，开始报驱动的错误了，需要修改什么其他东西吗？
>2018-11-29 14:07:42.191 ERROR 9283 --- [           main] c.a.o.c.client.adapter.rdb.RdbAdapter    : ERROR ## failed to initial datasource: jdbc:mysql://127.0.0.1:3306

>java.sql.SQLException: org.mariadb.jdbc.Driver
        at com.alibaba.druid.util.JdbcUtils.createDriver(JdbcUtils.java:600) ~[druid-1.1.9.jar:1.1.9]
        at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:815) ~[druid-1.1.9.jar:1.1.9]
        at com.alibaba.otter.canal.client.adapter.rdb.RdbAdapter.init(RdbAdapter.java:87) ~[client-adapter.rdb-1.1.3-SNAPSHOT-jar-with-dependencies.jar:na]

**Comment by Near-Zhang** [comment]
> > 应该是jdbc驱动的问题, 把canal-adapter/lib 中的mysql-connector-java-5.1.40.jar删掉, 替换对应mariadb的jdbc
> 
> 把驱动文件替换掉之后，开始报驱动的错误了，需要修改什么其他东西吗？
> 
> > 2018-11-29 14:07:42.191 ERROR 9283 --- [           main] c.a.o.c.client.adapter.rdb.RdbAdapter    : ERROR ## failed to initial datasource: jdbc:mysql://127.0.0.1:3306
> 
> > java.sql.SQLException: org.mariadb.jdbc.Driver
> > at com.alibaba.druid.util.JdbcUtils.createDriver(JdbcUtils.java:600) ~[druid-1.1.9.jar:1.1.9]
> > at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:815) ~[druid-1.1.9.jar:1.1.9]
> > at com.alibaba.otter.canal.client.adapter.rdb.RdbAdapter.init(RdbAdapter.java:87) ~[client-adapter.rdb-1.1.3-SNAPSHOT-jar-with-dependencies.jar:na]

另外我还是认为是语句转义的问题，因为 key 如果没有转义符号时是会报错的，因此有这种情况：
表结构存在 key 这个段时，插入数据：
``` sql
INSERT INTO `mirror` (`id`, `key`, `value`, `type`, `op_time`) VALUES (3,'3','{}','meta','2016-11-11 11:11:11');
```
报错！

重新定义表结构后，插入数据
``` sql
INSERT INTO `mirror` (`id`, `value`, `type`, `op_time`) VALUES  (3,'{}','meta','2016-11-11 11:11:11');
```
正常！

**Comment by rewerma** [comment]
rdb adapter 报出来的吗

**Comment by Near-Zhang** [comment]
> rdb adapter 报出来的吗

是的, 这是换了驱动的报错：
>2018-11-29 14:30:11.898  INFO 15536 --- [           main] c.a.o.c.c.a.rdb.config.ConfigLoader      : ## Rdb mapping config loaded
2018-11-29 14:30:11.947 ERROR 15536 --- [           main] com.alibaba.druid.pool.DruidDataSource   : {dataSource-1} init error
>
>java.sql.SQLException: org.mariadb.jdbc.Driver
        at com.alibaba.druid.util.JdbcUtils.createDriver(JdbcUtils.java:600) ~[druid-1.1.9.jar:1.1.9]
        at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:815) ~[druid-1.1.9.jar:1.1.9]
        at com.alibaba.otter.canal.client.adapter.rdb.RdbAdapter.init(RdbAdapter.java:87) [client-adapter.rdb-1.1.3-SNAPSHOT-jar-with-dependencies.jar:na]
        at com.alibaba.otter.canal.adapter.launcher.loader.CanalAdapterLoader.loadConnector(CanalAdapterLoader.java:146) [client-adapter.launcher-1.1.3-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.adapter.launcher.loader.CanalAdapterLoader.init(CanalAdapterLoader.java:117) [client-adapter.launcher-1.1.3-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.adapter.launcher.loader.CanalAdapterService.init(CanalAdapterService.java:51) [client-adapter.launcher-1.1.3-SNAPSHOT.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_191]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_191]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_191]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:365) [spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:308) [spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:135) [spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:422) [spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1694) [spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:579) [spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:501) [spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$1(AbstractBeanFactory.java:353) [spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
        at org.springframework.cloud.context.scope.GenericScope$BeanLifecycleWrapper.getBean(GenericScope.java:390) ~[spring-cloud-context-2.0.0.RELEASE.jar:2.0.0.RELEASE]
        at org.springframework.cloud.context.scope.GenericScope.get(GenericScope.java:184) ~[spring-cloud-context-2.0.0.RELEASE.jar:2.0.0.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:350) [spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) [spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1089) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
        at org.springframework.cloud.context.scope.refresh.RefreshScope.eagerlyInitialize(RefreshScope.java:126) ~[spring-cloud-context-2.0.0.RELEASE.jar:2.0.0.RELEASE]
        at org.springframework.cloud.context.scope.refresh.RefreshScope.start(RefreshScope.java:117) ~[spring-cloud-context-2.0.0.RELEASE.jar:2.0.0.RELEASE]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_191]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_191]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_191]
        at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:264) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
        at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:182) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
        at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:144) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:400) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:354) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:888) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:161) ~[spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) ~[spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395) ~[spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) ~[spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
        at com.alibaba.otter.canal.adapter.launcher.CanalAdapterApplication.main(CanalAdapterApplication.java:19) ~[client-adapter.launcher-1.1.3-SNAPSHOT.jar:na]
Caused by: java.lang.ClassNotFoundException: org.mariadb.jdbc.Driver
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_191]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_191]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[na:1.8.0_191]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_191]
        at java.lang.Class.forName0(Native Method) ~[na:1.8.0_191]
        at java.lang.Class.forName(Class.java:264) ~[na:1.8.0_191]
        at com.alibaba.druid.util.JdbcUtils.createDriver(JdbcUtils.java:598) ~[druid-1.1.9.jar:1.1.9]
        ... 44 common frames omitted

**Comment by Near-Zhang** [comment]
> > rdb adapter 报出来的吗
> 
> 是的, 这是换了驱动的报错：
> 
> > 2018-11-29 14:30:11.898  INFO 15536 --- [           main] c.a.o.c.c.a.rdb.config.ConfigLoader      : ## Rdb mapping config loaded
> > 2018-11-29 14:30:11.947 ERROR 15536 --- [           main] com.alibaba.druid.pool.DruidDataSource   : {dataSource-1} init error
> > java.sql.SQLException: org.mariadb.jdbc.Driver
> > at com.alibaba.druid.util.JdbcUtils.createDriver(JdbcUtils.java:600) ~[druid-1.1.9.jar:1.1.9]
> > at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:815) ~[druid-1.1.9.jar:1.1.9]
> > at com.alibaba.otter.canal.client.adapter.rdb.RdbAdapter.init(RdbAdapter.java:87) [client-adapter.rdb-1.1.3-SNAPSHOT-jar-with-dependencies.jar:na]
> > at com.alibaba.otter.canal.adapter.launcher.loader.CanalAdapterLoader.loadConnector(CanalAdapterLoader.java:146) [client-adapter.launcher-1.1.3-SNAPSHOT.jar:na]
> > at com.alibaba.otter.canal.adapter.launcher.loader.CanalAdapterLoader.init(CanalAdapterLoader.java:117) [client-adapter.launcher-1.1.3-SNAPSHOT.jar:na]
> > at com.alibaba.otter.canal.adapter.launcher.loader.CanalAdapterService.init(CanalAdapterService.java:51) [client-adapter.launcher-1.1.3-SNAPSHOT.jar:na]
> > at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
> > at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_191]
> > at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_191]
> > at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_191]
> > at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:365) [spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
> > at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:308) [spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
> > at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:135) [spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
> > at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:422) [spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
> > at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1694) [spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
> > at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:579) [spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
> > at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:501) [spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
> > at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$1(AbstractBeanFactory.java:353) [spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
> > at org.springframework.cloud.context.scope.GenericScope$BeanLifecycleWrapper.getBean(GenericScope.java:390) ~[spring-cloud-context-2.0.0.RELEASE.jar:2.0.0.RELEASE]
> > at org.springframework.cloud.context.scope.GenericScope.get(GenericScope.java:184) ~[spring-cloud-context-2.0.0.RELEASE.jar:2.0.0.RELEASE]
> > at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:350) [spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
> > at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) [spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
> > at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1089) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
> > at org.springframework.cloud.context.scope.refresh.RefreshScope.eagerlyInitialize(RefreshScope.java:126) ~[spring-cloud-context-2.0.0.RELEASE.jar:2.0.0.RELEASE]
> > at org.springframework.cloud.context.scope.refresh.RefreshScope.start(RefreshScope.java:117) ~[spring-cloud-context-2.0.0.RELEASE.jar:2.0.0.RELEASE]
> > at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
> > at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_191]
> > at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_191]
> > at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_191]
> > at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:264) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
> > at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:182) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
> > at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:144) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
> > at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
> > at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
> > at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
> > at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:400) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
> > at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:354) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
> > at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:888) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
> > at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:161) ~[spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
> > at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
> > at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
> > at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) ~[spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
> > at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395) ~[spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
> > at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) ~[spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
> > at com.alibaba.otter.canal.adapter.launcher.CanalAdapterApplication.main(CanalAdapterApplication.java:19) ~[client-adapter.launcher-1.1.3-SNAPSHOT.jar:na]
> > Caused by: java.lang.ClassNotFoundException: org.mariadb.jdbc.Driver
> > at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_191]
> > at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_191]
> > at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[na:1.8.0_191]
> > at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_191]
> > at java.lang.Class.forName0(Native Method) ~[na:1.8.0_191]
> > at java.lang.Class.forName(Class.java:264) ~[na:1.8.0_191]
> > at com.alibaba.druid.util.JdbcUtils.createDriver(JdbcUtils.java:598) ~[druid-1.1.9.jar:1.1.9]
> > ... 44 common frames omitted



> rdb adapter 报出来的吗

即便不换驱动，继续使用mysql驱动，如果语句不涉及 `ssl`、 `key` 等字符作为段名时，均不会报错

否则会报语法错，报的语法错误和语句不使用 ` `来扩住字符时一致，但在原数据库的执行语句因为使用了 `` 是正常执行的

**Comment by rewerma** [comment]
更新最新的代码, 在rdb的配置中设置:
```
......
  mapAll: false
  targetColumns:
    id:
    name:
    role_id:
    c_time:
    "`key`": key
```
即可转译关键字字段

另外你换了驱动需要把mariadb的jar包单独放到adapter/lib 下

**Comment by Near-Zhang** [comment]
> 更新最新的代码, 在rdb的配置中设置:
> 
> ```
> ......
>   mapAll: false
>   targetColumns:
>     id:
>     name:
>     role_id:
>     c_time:
>     "`key`": key
> ```
> 即可转译关键字字段
> 
> 另外你换了驱动需要把mariadb的jar包单独放到adapter/lib 下

好的，感谢

**Comment by rewerma** [comment]
也可以这样配置:
```
  mapAll: true
  targetColumns:
    "`key`": key
```
