### ISSUE TITLE
otter同步报错Timeout occurred, failed to read 4 bytes in 25000 milliseconds.

### ISSUE THREAD

**Issue by zk19930911** [alibaba/canal#1257]
2018-12-06 03:00:57.042 [destination = online_mryt_tms_canal , address = /ip:3306 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - Socket timeout expired, 
closing connection
java.net.SocketTimeoutException: Timeout occurred, failed to read 4 bytes in 25000 milliseconds.
        at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:123) ~[canal.parse.driver-1.1.1.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:174) ~[canal.parse-1.1.1.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:77) ~[canal.parse-1.1.1.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:154) [canal.parse-1.1.1.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:266) [canal.parse-1.1.1.jar:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
2018-12-06 03:00:57.049 [destination = online_mryt_tms_canal , address = /ip:3306 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - dump address ip/1
0.13.11.122:3306 has an error, retrying. caused by 
java.net.SocketTimeoutException: Timeout occurred, failed to read 4 bytes in 25000 milliseconds.
        at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:123) ~[canal.parse.driver-1.1.1.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:174) ~[canal.parse-1.1.1.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:77) ~[canal.parse-1.1.1.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:154) ~[canal.parse-1.1.1.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:266) ~[canal.parse-1.1.1.jar:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
2018-12-06 03:00:57.049 [destination = online_mryt_tms_canal , address = /ip:3306 , EventParser] WARN  c.a.o.s.a.i.setl.zookeeper.termin.WarningTerminProcess - nid:4[2:canal:online_mryt
_tms_canal:java.net.SocketTimeoutException: Timeout occurred, failed to read 4 bytes in 25000 milliseconds.
        at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:123)
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:174)
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:77)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:154)
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:266)
        at java.lang.Thread.run(Thread.java:748)
]
2018-12-06 03:01:09.095 [destination = online_mryt_tms_canal , address = /ip:3306 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - prepare to find start posit
ion just last position
 {"identity":{"slaveId":-1,"sourceAddress":{"address":"ip","port":3306}},"postion":{"gtid":"","included":false,"journalName":"mysql-bin.000172","position":619737365,"serverId":96029,"ti
mestamp":1544036431000}}
2018-12-06 03:01:09.095 [destination = online_mryt_tms_canal , address = /ip:3306 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - find start position : Entry
Position[included=false,journalName=mysql-bin.000172,position=619737365,serverId=96029,gtid=,timestamp=1544036431000]
2018-12-06 03:01:09.100 [destination = online_mryt_tms_canal , address = /ip:3306 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - I/O error while reading 
from client socket
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102) ~[canal.parse-1.1.1.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:154) [canal.parse-1.1.1.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:266) [canal.parse-1.1.1.jar:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
2018-12-06 03:01:09.100 [destination = online_mryt_tms_canal , address = /ip:3306 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - dump address ip/1
0.13.11.122:3306 has an error, retrying. caused by 
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102) ~[canal.parse-1.1.1.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:154) ~[canal.parse-1.1.1.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:266) ~[canal.parse-1.1.1.jar:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]

**Comment by agapple** [comment]
errmsg = Could not find first log file name in binary log index file
