### ISSUE TITLE
canal 启动的时候报错, 但是能正常监听

### ISSUE THREAD

**Issue by l617388617** [alibaba/canal#1271]
### environment

* canal version 1.1.3-SNAPSHOT
* mysql version 5.7

### Issue Description
canal 启动的时候报下面的错误

2018-12-11 12:24:17.157 [MultiStageCoprocessor-other-example-0] WARN  c.a.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta - parse faield : CREATE USER 'root'@'%' IDENTIFIED WITH 'mysql_native_password' AS '*279649DDB35DC1FF8B0A8FF854874CFCCC88230A'
com.alibaba.fastsql.sql.parser.ParserException: syntax error, error in :'ord' AS '*279649DDB35DC1FF8B0A8FF85, pos 65, line 1, column 63, token AS
	at com.alibaba.fastsql.sql.parser.SQLParser.printError(SQLParser.java:363) ~[fastsql-2.0.0_preview_644.jar:2.0.0_preview_644]
	at com.alibaba.fastsql.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:534) ~[fastsql-2.0.0_preview_644.jar:2.0.0_preview_644]
	at com.alibaba.fastsql.sql.SQLUtils.parseStatements(SQLUtils.java:525) ~[fastsql-2.0.0_preview_644.jar:2.0.0_preview_644]
	at com.alibaba.fastsql.sql.repository.SchemaRepository.console(SchemaRepository.java:439) ~[fastsql-2.0.0_preview_644.jar:2.0.0_preview_644]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta.apply(MemoryTableMeta.java:78) ~[canal.parse-1.1.3-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.apply(DatabaseTableMeta.java:154) [canal.parse-1.1.3-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.TableMetaCache.apply(TableMetaCache.java:231) [canal.parse-1.1.3-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseQueryEvent(LogEventConvert.java:269) [canal.parse-1.1.3-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:114) [canal.parse-1.1.3-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:292) [canal.parse-1.1.3-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:246) [canal.parse-1.1.3-SNAPSHOT.jar:na]
	at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168) [disruptor-3.4.2.jar:na]
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125) [disruptor-3.4.2.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]

**Comment by NathanDataPlayer** [comment]
同样遇到这个问题，你解决了吗?

**Comment by l617388617** [comment]
没有呢, 想看看有没有网友能帮忙解决

**Comment by NathanDataPlayer** [comment]
这两天一直启动后，查看canal下的日志就是这个'ord' AS '*279649DDB35DC1FF8B0A8FF85, pos 65, line 1, column 63, token AS类似错误，不知道哪里的问题。有头绪了，就告诉下哈

**Comment by NathanDataPlayer** [comment]
> 不影响使用, 不支持create user语法解析而已, 忽略就行

这种错误不影响使用?另外，我这样启动后，写好client端，但是消费不出来数据.求指教.

**Comment by NathanDataPlayer** [comment]
> 不影响使用, 不支持create user语法解析而已, 忽略就行


还有遇到这种错误是为什么?怎么解决?
[New I/O server worker #1-1] ERROR c.a.otter.canal.server.netty.handler.SessionHandler - something goes wrong with channel:[id: 0x0651290b, /192.168.1.1:52254 => /192.168.1.101:11111], exception=java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:322)
	at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:281)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:201)
	at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by warrenwx** [comment]
同样碰到类似问题，会出现1：server日志循环报错，2：消费停止消费数据

**Comment by agapple** [comment]
Connection reset by peer , 估计是client主动关闭了链接

**Comment by nickhuang1127** [comment]
@agapple  为什么client会主动断链接呢，用的是官方client demo，如何重新建立链接？
