### ISSUE TITLE
kafka连接不上

### ISSUE THREAD

**Issue by yysen919** [alibaba/canal#1275]
### environment

* canal version 1.1.1 
* mysql version  5.5
* kafka version 2.13_1.1.1
### Issue Description

kafka总是提示是连接不上，请问是为啥？？？
### Expected behaviour
2018-12-11 21:37:32.154 [kafka-producer-network-thread | producer-1] DEBUG org.apache.kafka.common.network.Selector - [Producer clientId=producer-1] Connection with localhost/127.0.0.1 disconnected
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_74]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_74]
	at org.apache.kafka.common.network.PlaintextTransportLayer.finishConnect(PlaintextTransportLayer.java:50) ~[kafka-clients-1.1.1.jar:na]
	at org.apache.kafka.common.network.KafkaChannel.finishConnect(KafkaChannel.java:106) ~[kafka-clients-1.1.1.jar:na]
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:470) [kafka-clients-1.1.1.jar:na]
	at org.apache.kafka.common.network.Selector.poll(Selector.java:424) [kafka-clients-1.1.1.jar:na]
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:460) [kafka-clients-1.1.1.jar:na]
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:239) [kafka-clients-1.1.1.jar:na]
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:163) [kafka-clients-1.1.1.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_74]
2018-12-11 21:37:32.154 [kafka-producer-network-thread | producer-1] DEBUG org.apache.kafka.common.network.Selector - [Producer clientId=producer-1] Connection with localhost/127.0.0.1 disconnected
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_74]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_74]
	at org.apache.kafka.common.network.PlaintextTransportLayer.finishConnect(PlaintextTransportLayer.java:50) ~[kafka-clients-1.1.1.jar:na]
	at org.apache.kafka.common.network.KafkaChannel.finishConnect(KafkaChannel.java:106) ~[kafka-clients-1.1.1.jar:na]
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:470) [kafka-clients-1.1.1.jar:na]
	at org.apache.kafka.common.network.Selector.poll(Selector.java:424) [kafka-clients-1.1.1.jar:na]
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:460) [kafka-clients-1.1.1.jar:na]
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:239) [kafka-clients-1.1.1.jar:na]
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:163) [kafka-clients-1.1.1.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_74]
2018-12-11 21:37:32.154 [kafka-producer-network-thread | producer-1] DEBUG org.apache.kafka.clients.NetworkClient - [Producer clientId=producer-1] Node -1 disconnected.
2018-12-11 21:37:32.154 [kafka-producer-network-thread | producer-1] DEBUG org.apache.kafka.clients.NetworkClient - [Producer clientId=producer-1] Node -1 disconnected.
2018-12-11 21:37:32.154 [kafka-producer-network-thread | producer-1] WARN  org.apache.kafka.clients.NetworkClient - [Producer clientId=producer-1] Con

**Comment by zwangbo** [comment]
查一查防火墙配置吧，然后看一看kafka实例机器的netstat
