### ISSUE TITLE
master--1.1.3-SNAPSHOT版本，启用GTID，启动失败

### ISSUE THREAD

**Issue by gsfeng179** [alibaba/canal#1288]
### environment
按照Issue #950  中说的master已经修复采用的master代码

* canal version
master--1.1.3-SNAPSHOT

* mysql version
5.6.28-cdb2016-log

### Issue Description
**canal.properties 配置的HA**
canal.zkServers =10.50.8.6:2181
canal.instance.global.spring.xml = classpath:spring/default-instance.xml

**example的instance.properties配置为**
canal.instance.gtidon=true

canal.instance.master.address=127.0.0.1:3306
canal.instance.master.journal.name=
canal.instance.master.position=
canal.instance.master.timestamp=
canal.instance.master.gtid=61724ebf-67d8-11e8-82af-6c92bf5dc258:1-4652108982,
b6eb3e25-975a-11e5-a87b-0241b539c4e5:242-58439:58442-115485,
cc5b5f77-91a6-11e5-834b-02b39697b809:357187369-381556259:383857565-384113697

canal.instance.defaultDatabaseName =shop
canal.instance.filter.regex=.*\\..*
其他都是默认设置

启动报下面错误。
2018-12-14 14:23:08.104 [destination = example , address = 127.0.0.1:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> find start position successfully, EntryPosition[included=false,journalName=mysql-bin.001462,position=24358459,serverId=90255,gtid=,timestamp=1544765205000] cost : 420ms , the next step is binlog dump
2018-12-14 14:24:14.922 [destination = example , address = 127.0.0.1:3306 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - I/O error while reading from client socket
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = The slave is connecting using CHANGE MASTER TO MASTER_AUTO_POSITION = 1, but the master has purged binary logs containing GTIDs that the slave requires.
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102) ~[classes/:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:253) [classes/:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:250) [classes/:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]

**Comment by westonlee** [comment]
Duplicate of #1010

**Comment by agapple** [comment]
show variables like '%gtid%'，看一下对应的gtid_purge的值

**Comment by wingerx** [comment]
see #1305

**Comment by wingerx** [comment]
将instance.properties 的canal.instance.tsdb.enable 这个设置为false 看看，如果运行正常，see #1305

**Comment by gsfeng179** [comment]
我测一下关闭false的方式。
再测一下你pr的代码。

**Comment by gsfeng179** [comment]
设置 canal.instance.tsdb.enable=false ，1.1.2+版本，开启GTID，是否设置canal.instance.master.gtid值，服务正常运行，数据没有丢失。
希望1.1.3版本可以修复tsdb.enable与GTID同时开始问题。 @agapple

**Comment by agapple** [comment]
@gsfeng179 你是重置了位点之后第一次启动么？

**Comment by gsfeng179** [comment]
是的。
canal version v1.1.2 ； mysql version 5.6.28-cdb2016-log
操作步骤：
1、清空zk的数据(暴力删除了/otter)
2、canal.instance.tsdb.enable=true、是否设置canal.instance.master.gtid值。
重新启动，报错。

**Comment by Jolin-blank** [comment]
最新版本的镜像同时开启
canal.instance.gtidon=on
canal.instance.master.gtid=afa1e25e-60dd-11ed-8555-42010a440102:1-33774 一样会出现这个问题
只要把canal.instance.tsdb.enable=false 就可以

**Comment by h-wq** [comment]
> 最新版本的镜像同时开启 canal.instance.gtidon=on canal.instance.master.gtid=afa1e25e-60dd-11ed-8555-42010a440102:1-33774同样会出现这个问题 只要把canal.instance.tsdb.enable=false就可以

想问一下 这个问题有解决吗
