### ISSUE TITLE
阿里云RDS高可用版mysql5.6同步binlog错误

### ISSUE THREAD

**Issue by raighneweng** [alibaba/canal#1298]
### environment

* canal version 
1.1.2
* mysql version
阿里云RDS高可用版 mysql5.6

### Issue Description
阿里云日志管理错误日志:
```
Start binlog_dump to master_thread_id(50359726) slave_server(756032110), pos(mysql-bin.000708, 12816103)
```
canal无法继续同步之后的binlog
```
WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> find start position successfully, EntryPosition[included=false,journalName=mysql-bin.000708,position=12816103,serverId=<null>,gtid=<null>,timestamp=1544937640000] cost : 277ms , the next step is binlog dump
```

**Comment by raighneweng** [comment]
卡在这里之后，之后的binlog都无法接收到

**Comment by agapple** [comment]
1. 不要去连接RDS只读实例
2. show binlog events in 'mysql-bin.000708' from 12816103 limit 100 ， 看一下是否有对应符合filter条件的binlog

**Comment by raighneweng** [comment]
1. 连接的是常规实例
2. 筛选出来有符合fillter的log

另外长时间运行后有 Connection reset by peer 错误
```
2018-12-17 10:40:04.284 [New I/O server worker #1-4] ERROR c.a.otter.canal.server.netty.handler.SessionHandler - something goes wrong with channel:[id: 0x7c9b58e5,], exception=java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:322)
        at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:281)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:201)
        at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by agapple** [comment]
Connection reset by peer ， 一般是空闲链接导致， 默认1个小时

**Comment by raighneweng** [comment]
binlog 已经更新到000715, 但 canal 依然停在 000712 ，导致消费端一直取不到新log

### show binary logs;
```
mysql-bin.000712	49688834
mysql-bin.000713	28550274
mysql-bin.000714	2814828
mysql-bin.000715	6231513
```

### canal log;
```
EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> find start position successfully, EntryPosition[included=false,journalName=mysql-bin.000712,position=19408500,serverId=<null>,gtid=<null>,timestamp=1545028776000] cost : 378ms , the next step is binlog dump
```

### rds日志错误
```
2018-12-17 14:39:38 9157 [Note] Start binlog_dump to master_thread_id(34011432) slave_server(756032110), pos(mysql-bin.000712, 19408250)
```

rds 错误信息的点在 canal log 点之前，应该不是这个错误导致的。

**Comment by raighneweng** [comment]
首先检查客户端是不是正确的返回ack了connector.ack(batchId)

**Comment by hookover** [comment]
本地是kafka，为啥也不行？

**Comment by gin-ctl** [comment]
问题解决了没，我也是卡在这里不动了
