### ISSUE TITLE
能设置HBase Adapter，组合行键的分隔符吗？

### ISSUE THREAD

**Issue by nd49782** [alibaba/canal#1301]
能设置HBase Adapter，组合行键的分隔符吗？
之前做数据全量同步的时候用的“_”做分隔符，我在文档中看到hbase adapter默认是用“|”，这个可以设置吗，如果不能，以后版本的话能不能增加个配置的选项？谢谢
还有用的是最新的1.1.2，发现hbase adapter启动报错
Exception in thread "main" java.lang.IllegalArgumentException: Cannot instantiate interface org.springframework.context.ApplicationContextInitializer : org.springframework.boot.autoconfigure.SharedMetadataReaderFactoryContextInitializer
at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:448)
at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:427)
at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:418)
at org.springframework.boot.SpringApplication.(SpringApplication.java:266)
at org.springframework.boot.SpringApplication.(SpringApplication.java:247)
at com.alibaba.otter.canal.adapter.launcher.CanalAdapterApplication.main(CanalAdapterApplication.java:17)
Caused by: java.lang.NoClassDefFoundError: org/springframework/core/KotlinDetector
at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:169)
at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:444)
... 5 more
Caused by: java.lang.ClassNotFoundException: org.springframework.core.KotlinDetector
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

**Comment by agapple** [comment]
尝试一下最新版1.1.3 , 已经修复
