### ISSUE TITLE
example里面的报错

### ISSUE THREAD

**Issue by 13772134994** [alibaba/canal#1304]
2018-12-17 14:52:50.576 [WrapperSimpleAppMain] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Loading properties file from class path resource [canal.properties]
2018-12-17 14:52:50.582 [WrapperSimpleAppMain] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Loading properties file from class path resource [example/instance.properties]
2018-12-17 14:52:50.771 [WrapperSimpleAppMain] WARN  o.s.beans.GenericTypeAwarePropertyDescriptor - Invalid JavaBean property 'connectionCharset' being accessed! Ambiguous write methods found next to actually used [public void com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.setConnectionCharset(java.nio.charset.Charset)]: [public void com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.setConnectionCharset(java.lang.String)]
2018-12-17 14:52:50.787 [WrapperSimpleAppMain] INFO  c.a.otter.canal.instance.spring.CanalInstanceWithSpring - start CannalInstance for 1-example 
2018-12-17 14:52:50.798 [WrapperSimpleAppMain] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - start successful....
2018-12-17 14:52:50.809 [canal-instance-scan-0] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - stop CannalInstance for null-example 
2018-12-17 14:52:50.817 [destination = example , address = /127.0.0.1:3308 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - parse events has an error
com.alibaba.otter.canal.parse.exception.CanalParseException: dump address /127.0.0.1:3308 has an error, retrying. 
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: connect /127.0.0.1:3308 failure
Caused by: java.io.IOException: connect /127.0.0.1:3308 failure
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:77) ~[canal.parse.driver-1.1.2.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.connect(MysqlConnection.java:88) ~[canal.parse-1.1.2.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.preDump(MysqlEventParser.java:86) ~[canal.parse-1.1.2.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:175) ~[canal.parse-1.1.2.jar:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_77]
Caused by: java.net.SocketException: Socket already closed.
	at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.write(BioSocketChannel.java:39) ~[canal.parse.driver-1.1.2.jar:na]
	at com.alibaba.otter.canal.parse.driver.mysql.utils.PacketManager.writePkg(PacketManager.java:31) ~[canal.parse.driver-1.1.2.jar:na]
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.negotiate(MysqlConnector.java:186) ~[canal.parse.driver-1.1.2.jar:na]
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:74) ~[canal.parse.driver-1.1.2.jar:na]
	... 4 common frames omitted
2018-12-17 14:52:50.818 [canal-instance-scan-0] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - stop successful....

**Comment by agapple** [comment]
stop successful....  , 找找哪里触发关闭了
