### ISSUE TITLE
The binlog can be printed, but can't be applied to target instance

### ISSUE THREAD

**Issue by lynch0227** [alibaba/canal#1309]
### environment
* canal version
1.1.2
* mysql version
source: 5.7.24
target: 5.7.23
### Issue Description
I use the canal adapter to sync the data from source to target, which is also mysql instance.
When I update one record in source instance, then meet the below errors:
2018-12-18 15:52:21.517 ERROR 22671 --- [pool-3-thread-1] c.a.o.c.c.a.rdb.support.BatchExecutor    : You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE id=2' at line 1

com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE id=2' at line 1
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_131]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_131]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_131]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_131]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.46.jar:5.1.46]
        at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.46.jar:5.1.46]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944) ~[mysql-connector-java-5.1.46.jar:5.1.46]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976) ~[mysql-connector-java-5.1.46.jar:5.1.46]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912) ~[mysql-connector-java-5.1.46.jar:5.1.46]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[mysql-connector-java-5.1.46.jar:5.1.46]
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[mysql-connector-java-5.1.46.jar:5.1.46]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2486) ~[mysql-connector-java-5.1.46.jar:5.1.46]
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858) ~[mysql-connector-java-5.1.46.jar:5.1.46]
        at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1197) ~[mysql-connector-java-5.1.46.jar:5.1.46]
        at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:498) ~[druid-1.1.9.jar:1.1.9]
        at com.alibaba.otter.canal.client.adapter.rdb.support.BatchExecutor.execute(BatchExecutor.java:62) ~[client-adapter.rdb-1.1.2-jar-with-dependencies.jar:na]
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.update(RdbSyncService.java:252) [client-adapter.rdb-1.1.2-jar-with-dependencies.jar:na]
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.sync(RdbSyncService.java:133) [client-adapter.rdb-1.1.2-jar-with-dependencies.jar:na]
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$null$2(RdbSyncService.java:104) [client-adapter.rdb-1.1.2-jar-with-dependencies.jar:na]
        at java.util.ArrayList.forEach(ArrayList.java:1249) ~[na:1.8.0_131]
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$sync$3(RdbSyncService.java:104) [client-adapter.rdb-1.1.2-jar-with-dependencies.jar:na]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]

2018-12-18 15:52:21.518 DEBUG 22671 --- [pool-3-thread-1] c.a.o.c.c.a.rdb.service.RdbSyncService   : DML: {"data":{"id":2,"name":"xx","asset_tag":"xxxx","model_id":1,"serial":"Null","purchase_date":1521561600000,"purchase_cost":10,"order_number":null,"assigned_to":null,"notes":"2","image":null,"user_id":null,"created_at":1539125002000,"updated_at":1539652565000,"physical":1,"deleted_at":1541727965000,"status_id":5,"archived":0,"warranty_months":36,"depreciate":null,"supplier_id":90,"requestable":0,"rtd_location_id":248,"accepted":null,"last_checkout":null,"expected_checkin":null,"company_id":26,"assigned_type":"App\\Models\\User","last_audit_date":null,"next_audit_date":null,"location_id":248,"checkin_counter":0,"checkout_counter":4,"requests_counter":0},"database":"snipeitdb","destination":"example","old":{"notes":null},"table":"assets","type":"UPDATE"}

### Steps to reproduce
1. the canal server is started successfully, there is no errors.
2. the example instance is also successful, there is no errors.
3. I only sync some table columns, not hole table.
4. Here is application.xml:
server:
  port: 8081
logging:
  level:
    org.springframework: DEBUG
    com.alibaba.otter.canal.client.adapter.hbase: DEBUG
    com.alibaba.otter.canal.client.adapter.es: DEBUG
    com.alibaba.otter.canal.client.adapter.rdb: DEBUG
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

canal.conf:
  canalServerHost: xxxxx:11111
#  zookeeperHosts: slave1:2181
#  mqServers: slave1:6667 #or rocketmq
#  flatMessage: true
  batchSize: 500
  syncBatchSize: 1000
  retries: 0
  timeout:
  accessKey:
  secretKey:
  mode: tcp
  srcDataSources:
    defaultDS:
      url: jdbc:mysql://xxxxxxx:3306/xxx?useUnicode=true
      username: root
      password: xxxx
  canalAdapters:
  - instance: example
    groups:
    - groupId: g1
      outerAdapters:
#       - name: logger
       - name: rdb
         key: mysql1
         properties:
           jdbc.driverClassName: com.mysql.jdbc.Driver
           jdbc.url: jdbc:mysql://xxxxx:3306/xxx?useUnicode=true
           jdbc.username: root
           jdbc.password: xxx
5. here is the rdb configure:
dataSourceKey: defaultDS
destination: example
outerAdapterKey: mysql1
concurrent: false
dbMapping:
  database: source_db
  table: source_table
  targetTable: target_db.target_table
  targetPk:
    id: id
#  mapAll: false
  targetColumns:
    id:
    name:
    asset_tag:
    notes:
    assigned_to:
    created_at:
    updated_at:
    deleted_at:
    status_id:

### Expected behaviour
I want to know why the DML can be printed, but can't be applied to target instance.

Thank you.

**Comment by lynch0227** [comment]
I have fix it when upgrade to 1.1.13
