### ISSUE TITLE
java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by lynch0227** [alibaba/canal#1316]
### environment

* canal version
1.1.3
* mysql version
5.7

### Issue Description
I do the columns level sync, when inserting the records, meeting the NULL exception:
java.lang.NullPointerException: null
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.insert(RdbSyncService.java:252) [client-adapter.rdb-1.1.3-SNAPSHOT-jar-with-dependencies.jar:na]
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.sync(RdbSyncService.java:193) [client-adapter.rdb-1.1.3-SNAPSHOT-jar-with-dependencies.jar:na]
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$null$0(RdbSyncService.java:106) [client-adapter.rdb-1.1.3-SNAPSHOT-jar-with-dependencies.jar:na]
        at java.util.ArrayList.forEach(ArrayList.java:1249) ~[na:1.8.0_131]
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$sync$1(RdbSyncService.java:106) [client-adapter.rdb-1.1.3-SNAPSHOT-jar-with-dependencies.jar:na]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]

2018-12-19 16:40:30.682 DEBUG 17523 --- [pool-3-thread-1] c.a.o.c.c.a.rdb.service.RdbSyncService   : DML: {"data":{"id":12002,"name":"测试数据","asset_tag":"xxx","model_id":529,"serial":"1","purchase_date":1544112000000,"purchase_cost":1,"order_number":"123455","assigned_to":1,"notes":"测试用机","image":"1","user_id":1,"created_at":1544758500000,"updated_at":1544758500000,"physical":1,"deleted_at":1544758500000,"status_id":5,"archived":0,"warranty_months":12,"depreciate":0,"supplier_id":1,"requestable":0,"rtd_location_id":219,"accepted":"1","last_checkout":1544758500000,"expected_checkin":1544716800000,"company_id":1,"assigned_type":"App\\Models\\User","last_audit_date":1544716800000,"next_audit_date":1544716800000,"location_id":219,"checkin_counter":0,"checkout_counter":1,"requests_counter":0},"database":"snipeitdb","destination":"example","old":null,"table":"a","type":"INSERT"}

**Comment by lynch0227** [comment]
I have fix it, please close it.
Reason:
When we set the targetColumns and mapAll  attribution, the insert sql will be prepared by all srcColumnName, but the ctype parameter only have partitial columns.
So when call BatchExecutor.setValue(values, type, value); functions wil get the NULL type value for mismatch columns.
(check the insert function in client-adapter\rdb\src\main\java\com\alibaba\otter\canal\client\adapter\rdb\service\RdbSyncService.java)

Solution:
When setting the targetColumns, the mapAll attribution must be false.
