### ISSUE TITLE
运行一段时间会出异常   CanalParseException

### ISSUE THREAD

**Issue by shyboy0358** [alibaba/canal#1317]
.mysql.rds.aliyuncs.com/xxxx has an error, retrying. caused by 
com.alibaba.otter.canal.parse.exception.CanalParseException: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: java.lang.IndexOutOfBoundsException: Index: 12, Size: 12
        at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[na:1.8.0_60]
        at java.util.ArrayList.get(ArrayList.java:429) ~[na:1.8.0_60]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseOneRow(LogEventConvert.java:640) ~[canal.parse-1.1.2.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseRowsEvent(LogEventConvert.java:539) ~[canal.parse-1.1.2.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$DmlParserStage.onEvent(MysqlMultiStageCoprocessor.java:330) ~[canal.parse-1.1.2.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$DmlParserStage.onEvent(MysqlMultiStageCoprocessor.java:316) ~[canal.parse-1.1.2.jar:na]
        at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) ~[disruptor-3.4.2.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_60]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_60]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
2018-12-19 14:50:17.674 [destination = mavericks , address = rds9bqff31333g29hfr9o.mysql.rds.aliyuncs.com/123.56.209.14:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:mavericks[com.alibaba.otter.canal.parse.exception.CanalParseException: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: java.lang.IndexOutOfBoundsException: Index: 12, Size: 12
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseOneRow(LogEventConvert.java:640)
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseRowsEvent(LogEventConvert.java:539)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$DmlParserStage.onEvent(MysqlMultiStageCoprocessor.java:330)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$DmlParserStage.onEvent(MysqlMultiStageCoprocessor.java:316)
        at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
]

**Comment by agapple** [comment]
应该是rds的隐藏主键的问题，可以使用1.1.3版本，修复过

**Comment by shyboy0358** [comment]
从1.1.2升级，是不是只是替换lib中的1.1.2相关的jar包即可呢。

**Comment by agapple** [comment]
老版本会解析失败，会影响同步

**Comment by general1990** [comment]
这个问题是因为你表结构修改了吧，我使用的时候也遇到过这个问题，升级后也不行，弃用了

**Comment by runningship** [comment]
同样问题，1.1.3好用吗
