### ISSUE TITLE
数据同步到kafka之后，canal client 消费kafka消息的时候提示错误

### ISSUE THREAD

**Issue by xForMe** [alibaba/canal#1318]
数据同步到kafka之后，canal client 消费kafka消息的时候提示
`Error deserializing key/value for partition customerCountries-0 at offset 10. If needed, please seek past the record to continue consumption.`

**Comment by xForMe** [comment]
20:12:40.144 [Thread-0] ERROR c.a.o.c.c.r.k.CanalKafkaClientExample - Error deserializing key/value for partition tiosfetch-0 at offset 6. If needed, please seek past the record to continue consumption.
org.apache.kafka.common.errors.SerializationException: Error deserializing key/value for partition tiosfetch-0 at offset 6. If needed, please seek past the record to continue consumption.
Caused by: com.alibaba.otter.canal.protocol.exception.CanalClientException: deserializer failed
	at com.alibaba.otter.canal.client.CanalMessageDeserializer.deserializer(CanalMessageDeserializer.java:54) ~[classes/:na]
	at com.alibaba.otter.canal.client.CanalMessageDeserializer.deserializer(CanalMessageDeserializer.java:14) ~[classes/:na]
	at com.alibaba.otter.canal.client.kafka.MessageDeserializer.deserialize(MessageDeserializer.java:24) ~[classes/:na]
	at com.alibaba.otter.canal.client.kafka.MessageDeserializer.deserialize(MessageDeserializer.java:16) ~[classes/:na]
	at org.apache.kafka.common.serialization.ExtendedDeserializer$Wrapper.deserialize(ExtendedDeserializer.java:65) ~[kafka-clients-1.1.1.jar:na]
	at org.apache.kafka.common.serialization.ExtendedDeserializer$Wrapper.deserialize(ExtendedDeserializer.java:55) ~[kafka-clients-1.1.1.jar:na]
	at org.apache.kafka.clients.consumer.internals.Fetcher.parseRecord(Fetcher.java:967) ~[kafka-clients-1.1.1.jar:na]
	at org.apache.kafka.clients.consumer.internals.Fetcher.access$3300(Fetcher.java:93) ~[kafka-clients-1.1.1.jar:na]
	at org.apache.kafka.clients.consumer.internals.Fetcher$PartitionRecords.fetchRecords(Fetcher.java:1144) ~[kafka-clients-1.1.1.jar:na]
	at org.apache.kafka.clients.consumer.internals.Fetcher$PartitionRecords.access$1400(Fetcher.java:993) ~[kafka-clients-1.1.1.jar:na]
	at org.apache.kafka.clients.consumer.internals.Fetcher.fetchRecords(Fetcher.java:527) ~[kafka-clients-1.1.1.jar:na]
	at org.apache.kafka.clients.consumer.internals.Fetcher.fetchedRecords(Fetcher.java:488) ~[kafka-clients-1.1.1.jar:na]
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollOnce(KafkaConsumer.java:1155) ~[kafka-clients-1.1.1.jar:na]
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1115) ~[kafka-clients-1.1.1.jar:na]
	at com.alibaba.otter.canal.client.kafka.KafkaCanalConnector.getListWithoutAck(KafkaCanalConnector.java:177) ~[classes/:na]
	at com.alibaba.otter.canal.client.running.kafka.CanalKafkaClientExample.process(CanalKafkaClientExample.java:110) [test-classes/:na]
	at com.alibaba.otter.canal.client.running.kafka.CanalKafkaClientExample.access$000(CanalKafkaClientExample.java:20) [test-classes/:na]
	at com.alibaba.otter.canal.client.running.kafka.CanalKafkaClientExample$3.run(CanalKafkaClientExample.java:79) [test-classes/:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_172]
Caused by: com.google.protobuf.InvalidProtocolBufferException$InvalidWireTypeException: Protocol message tag had invalid wire type.
	at com.google.protobuf.InvalidProtocolBufferException.invalidWireType(InvalidProtocolBufferException.java:115) ~[protobuf-java-3.6.1.jar:na]
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:551) ~[protobuf-java-3.6.1.jar:na]
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:514) ~[protobuf-java-3.6.1.jar:na]
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:633) ~[protobuf-java-3.6.1.jar:na]
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:295) ~[protobuf-java-3.6.1.jar:na]
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readGroup(CodedInputStream.java:868) ~[protobuf-java-3.6.1.jar:na]
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:541) ~[protobuf-java-3.6.1.jar:na]
	at com.google.protobuf.GeneratedMessageV3.parseUnknownFieldProto3(GeneratedMessageV3.java:305) ~[protobuf-java-3.6.1.jar:na]
	at com.alibaba.otter.canal.protocol.CanalPacket$Packet.<init>(CanalPacket.java:475) ~[classes/:na]
	at com.alibaba.otter.canal.protocol.CanalPacket$Packet.<init>(CanalPacket.java:409) ~[classes/:na]
	at com.alibaba.otter.canal.protocol.CanalPacket$Packet$1.parsePartialFrom(CanalPacket.java:1396) ~[classes/:na]
	at com.alibaba.otter.canal.protocol.CanalPacket$Packet$1.parsePartialFrom(CanalPacket.java:1390) ~[classes/:na]
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:163) ~[protobuf-java-3.6.1.jar:na]
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:197) ~[protobuf-java-3.6.1.jar:na]
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:209) ~[protobuf-java-3.6.1.jar:na]
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:214) ~[protobuf-java-3.6.1.jar:na]
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49) ~[protobuf-java-3.6.1.jar:na]
	at com.alibaba.otter.canal.protocol.CanalPacket$Packet.parseFrom(CanalPacket.java:867) ~[classes/:na]
	at com.alibaba.otter.canal.client.CanalMessageDeserializer.deserializer(CanalMessageDeserializer.java:22) ~[classes/:na]
	... 18 common frames omitted

**Comment by agapple** [comment]
com.google.protobuf.GeneratedMessageV3.parseUnknownFieldProto3(GeneratedMessageV3.java:305) ~[protobuf-java-3.6.1.jar:na]

server和client的protobuf不一致？

**Comment by RobinDu325** [comment]
遇到同样的问题，protobuf版本是一致的。  必须把flatmessage设置成true ，才能成功启动kafka client
