### ISSUE TITLE
Bug: tablecolumns sync

### ISSUE THREAD

**Issue by lynch0227** [alibaba/canal#1320]
I do the tablecolumns sync, when updating some columns that doesn't need to be sync, then will meet the below errors:
2018-12-20 11:32:27.996 ERROR 29081 --- [pool-3-thread-1] c.a.o.c.c.a.rdb.support.BatchExecutor    : You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE id=12002' at line 1

com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE id=12002' at line 1
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_131]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_131]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_131]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_131]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.40.jar:5.1.40]
        at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.40.jar:5.1.40]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943) ~[mysql-connector-java-5.1.40.jar:5.1.40]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3970) ~[mysql-connector-java-5.1.40.jar:5.1.40]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3906) ~[mysql-connector-java-5.1.40.jar:5.1.40]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524) ~[mysql-connector-java-5.1.40.jar:5.1.40]
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2677) ~[mysql-connector-java-5.1.40.jar:5.1.40]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2549) ~[mysql-connector-java-5.1.40.jar:5.1.40]
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861) ~[mysql-connector-java-5.1.40.jar:5.1.40]
        at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1192) ~[mysql-connector-java-5.1.40.jar:5.1.40]
        at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:498) ~[druid-1.1.9.jar:1.1.9]
        at com.alibaba.otter.canal.client.adapter.rdb.support.BatchExecutor.execute(BatchExecutor.java:62) ~[client-adapter.rdb-1.1.3-SNAPSHOT-jar-with-dependencies.jar:na]
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.update(RdbSyncService.java:322) [client-adapter.rdb-1.1.3-SNAPSHOT-jar-with-dependencies.jar:na]
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.sync(RdbSyncService.java:195) [client-adapter.rdb-1.1.3-SNAPSHOT-jar-with-dependencies.jar:na]
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$null$0(RdbSyncService.java:106) [client-adapter.rdb-1.1.3-SNAPSHOT-jar-with-dependencies.jar:na]
        at java.util.ArrayList.forEach(ArrayList.java:1249) ~[na:1.8.0_131]
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$sync$1(RdbSyncService.java:106) [client-adapter.rdb-1.1.3-SNAPSHOT-jar-with-dependencies.jar:na]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]

2018-12-20 11:32:27.996 TRACE 29081 --- [pool-3-thread-1] c.a.o.c.c.a.rdb.service.RdbSyncService   : Update target table, sql: UPDATE qq_data.t_assets SE WHERE id=?

Reason:
For this scenario, the targetColumnNames is actually empty in 'update' function in client-adapter\rdb\src\main\java\com\alibaba\otter\canal\client\adapter\rdb\service\RdbSyncService.java.

Solution:
I add the new parameter isEmpty, which is used to judge targetColumnNames whether is none.
If isEmpty is true, then return directly.
Could you please fix it next verison?

            boolean isEmpty = true;
            for (String srcColumnName : old.keySet()) {
                List<String> targetColumnNames = new ArrayList<>();
                columnsMap.forEach((targetColumn, srcColumn) -> {
                    if (srcColumnName.toLowerCase().equals(srcColumn)) {
                        targetColumnNames.add(targetColumn);
                    }
                });
                logger.trace("targetColumnNames: {}", targetColumnNames);
                if (!targetColumnNames.isEmpty()) {
                    isEmpty = false;
                    for (String targetColumnName : targetColumnNames) {
                        updateSql.append(targetColumnName).append("=?, ");
                        Integer type = ctype.get(Util.cleanColumn(targetColumnName).toLowerCase());
                        logger.trace("type: {},value: {}", type,data.get(srcColumnName));
                        logger.trace("values: {}", values);
                        BatchExecutor.setValue(values, type, data.get(srcColumnName));
                    }
                }
            }

            if (isEmpty == true) {
                return;
            }

**Comment by rewerma** [comment]
在最新版本已解决
