### ISSUE TITLE
1.1.1版本报错 EOF encountered, 会在什么情况发生

### ISSUE THREAD

**Issue by Velsson** [alibaba/canal#1330]
at java.lang.Thread.run(Thread.java:748) [na:1.8.0_172]
2018-12-20 22:51:35.112 [destination = elastic , address =MySQL地址 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address MySQL地址 has an error, retrying. caused by 
java.io.IOException: EOF encountered.
        at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:112) ~[canal.parse.driver-1.1.1.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:174) ~[canal.parse-1.1.1.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:85) ~[canal.parse-1.1.1.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:216) ~[canal.parse-1.1.1.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:252) ~[canal.parse-1.1.1.jar:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_172]
查看了代码,packet header获取成功后 获取第一个packet时知道报错读到文件末尾,会在什么情况下发生,麻烦大神解答下.

**Comment by agapple** [comment]
链接被mysql关闭

**Comment by Velsson** [comment]
哦,好的谢谢

**Comment by waters321** [comment]
我也遇到了这个问题，重启也不好使，mysql确认可以连上

**Comment by leiwangouc** [comment]
有什么解决方式吗？我也遇到了这个问题。
