### ISSUE TITLE
canal报内存溢出问题

### ISSUE THREAD

**Issue by mengzhibule** [alibaba/canal#1332]
### environment
linux --centos 7.2
* canal version
1.0.24
* mysql version
5.7.22
### Issue Description

{"identity":{"slaveId":-1,"sourceAddress":{"address":"10.3.1.211","port":3301}},"postion":{"included":false,"journalName":"bin.000631","position":784119321,"serverId":1101,"timestamp":1545100533000}}
java.lang.OutOfMemoryError: Java heap space
Filter trigger matched.  Restarting JVM.
Dumping heap to ../logs/java_pid18582.hprof ...
Heap dump file created [7152920865 bytes in 14.304 secs]
2018-12-21 10:46:40.211 [New I/O server worker #1-32] ERROR com.alibaba.otter.canal.server.netty.NettyUtils - ErrotCode:400 , Caused by : 
something goes wrong with channel:[id: 0x2d0529b3, /10.3.1.112:45006 => /10.3.1.111:11111], exception=java.lang.OutOfMemoryError: Java heap space
Filter trigger matched.  Restart JVM (Ignoring, already restarting).

2018-12-21 10:46:40.211 [New I/O server worker #1-29] ERROR com.alibaba.otter.canal.server.netty.NettyUtils - ErrotCode:400 , Caused by : 
something goes wrong with channel:[id: 0x2a0c180f, /10.3.1.112:45000 => /10.3.1.111:11111], exception=java.lang.OutOfMemoryError: Java heap space
Filter trigger matched.  Restart JVM (Ignoring, already restarting).
	at com.google.protobuf.ByteString$CodedBuilder.<init>(ByteString.java:959)
	at com.google.protobuf.ByteString$CodedBuilder.<init>(ByteString.java:954)
	at com.google.protobuf.ByteString.newCodedBuilder(ByteString.java:950)
	at com.google.protobuf.AbstractMessageLite.toByteString(AbstractMessageLite.java:51)
	at com.alibaba.otter.canal.server.netty.handler.SessionHandler.messageReceived(SessionHandler.java:143)
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:100)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:783)
	at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:154)
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:100)
	at org.jboss.netty.handler.timeout.IdleStateAwareChannelHandler.handleUpstream(IdleStateAwareChannelHandler.java:48)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:783)
	at org.jboss.netty.handler.timeout.IdleStateHandler.messageReceived(IdleStateHandler.java:275)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:80)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:783)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:302)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.unfoldAndFireMessageReceived(ReplayingDecoder.java:525)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:506)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:443)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:80)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:274)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:261)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:349)
	at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:280)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:200)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:44)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

2018-12-21 10:46:40.211 [New I/O server worker #1-2] ERROR com.alibaba.otter.canal.server.netty.NettyUtils - ErrotCode:400 , Caused by : 
something goes wrong with channel:[id: 0x0276f2c4, /10.3.1.112:45010 => /10.3.1.111:11111], exception=java.lang.OutOfMemoryError: Java heap space
Filter trigger matched.  Restart JVM (Ignoring, already restarting).

2018-12-21 10:46:41.593 [New I/O server worker #1-24] ERROR com.alibaba.otter.canal.server.netty.NettyUtils - ErrotCode:400 , Caused by : 
something goes wrong with channel:[id: 0x35c7e017, /10.3.1.112:44990 => /10.3.1.111:11111], exception=java.lang.OutOfMemoryError: Java heap space
Filter trigger matched.  Restart JVM (Ignoring, already restarting).

2018-12-21 10:46:41.593 [New I/O server worker #1-27] ERROR com.alibaba.otter.canal.server.netty.NettyUtils - ErrotCode:400 , Caused by : 
something goes wrong with channel:[id: 0x31963b07, /10.3.1.112:44996 => /10.3.1.111:11111], exception=java.lang.OutOfMemoryError: Java heap space
Filter trigger matched.  Restart JVM (Ignoring, already restarting).

2018-12-21 10:46:41.603 [New I/O server worker #1-30] ERROR com.alibaba.otter.canal.server.netty.NettyUtils - ErrotCode:400 , Caused by : 
something goes wrong with channel:[id: 0x4be5cea6, /10.3.1.112:45002 => /10.3.1.111:11111], exception=java.lang.OutOfMemoryError: Java heap space
Filter trigger matched.  Restart JVM (Ignoring, already restarting).
	at com.google.protobuf.ByteString$CodedBuilder.<init>(ByteString.java:959)
	at com.google.protobuf.ByteString$CodedBuilder.<init>(ByteString.java:954)
	at com.google.protobuf.ByteString.newCodedBuilder(ByteString.java:950)
	at com.google.protobuf.AbstractMessageLite.toByteString(AbstractMessageLite.java:51)
	at com.alibaba.otter.canal.server.netty.handler.SessionHandler.messageReceived(SessionHandler.java:143)
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:100)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:783)
	at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:154)
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:100)
	at org.jboss.netty.handler.timeout.IdleStateAwareChannelHandler.handleUpstream(IdleStateAwareChannelHandler.java:48)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:783)
	at org.jboss.netty.handler.timeout.IdleStateHandler.messageReceived(IdleStateHandler.java:275)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:80)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:783)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:302)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.unfoldAndFireMessageReceived(ReplayingDecoder.java:525)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:506)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:443)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:80)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:274)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:261)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:349)
	at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:280)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:200)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:44)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

2018-12-21 10:46:41.604 [New I/O server worker #1-28] ERROR com.alibaba.otter.canal.server.netty.NettyUtils - ErrotCode:400 , Caused by : 
something goes wrong with channel:[id: 0x3b5bb27a, /10.3.1.112:44998 => /10.3.1.111:11111], exception=java.lang.OutOfMemoryError: Java heap space
Filter trigger matched.  Restart JVM (Ignoring, already restarting).
	at com.google.protobuf.ByteString$CodedBuilder.<init>(ByteString.java:959)
	at com.google.protobuf.ByteString$CodedBuilder.<init>(ByteString.java:954)
	at com.google.protobuf.ByteString.newCodedBuilder(ByteString.java:950)
	at com.google.protobuf.AbstractMessageLite.toByteString(AbstractMessageLite.java:51)
	at com.alibaba.otter.canal.server.netty.handler.SessionHandler.messageReceived(SessionHandler.java:143)
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:100)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:783)
	at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:154)
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:100)
	at org.jboss.netty.handler.timeout.IdleStateAwareChannelHandler.handleUpstream(IdleStateAwareChannelHandler.java:48)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:783)
	at org.jboss.netty.handler.timeout.IdleStateHandler.messageReceived(IdleStateHandler.java:275)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:80)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:783)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:302)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.unfoldAndFireMessageReceived(ReplayingDecoder.java:525)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:506)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:443)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:80)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:274)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:261)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:349)
	at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:280)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:200)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:44)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

2018-12-21 10:46:41.604 [New I/O server worker #1-4] ERROR com.alibaba.otter.canal.server.netty.NettyUtils - ErrotCode:400 , Caused by : 
something goes wrong with channel:[id: 0x11500e8f, /10.3.1.112:45014 => /10.3.1.111:11111], exception=java.lang.OutOfMemoryError: Java heap space
Filter trigger matched.  Restart JVM (Ignoring, already restarting).

2018-12-21 10:46:41.606 [New I/O server worker #1-5] ERROR com.alibaba.otter.canal.server.netty.NettyUtils - ErrotCode:400 , Caused by : 
something goes wrong with channel:[id: 0x6aabeca9, /10.3.1.112:45016 => /10.3.1.111:11111], exception=java.lang.OutOfMemoryError: Java heap space
Filter trigger matched.  Restart JVM (Ignoring, already restarting).

2018-12-21 10:46:40.211 [New I/O server worker #1-31] ERROR com.alibaba.otter.canal.server.netty.NettyUtils - ErrotCode:400 , Caused by : 
something goes wrong with channel:[id: 0x4bab9ade, /10.3.1.112:45004 => /10.3.1.111:11111], exception=java.lang.OutOfMemoryError: Java heap space
Filter trigger matched.  Restart JVM (Ignoring, already restarting).

2018-12-21 10:46:40.211 [New I/O server worker #1-23] ERROR com.alibaba.otter.canal.server.netty.NettyUtils - ErrotCode:400 , Caused by : 
something goes wrong with channel:[id: 0x253bf84e, /10.3.1.112:44988 => /10.3.1.111:11111], exception=java.lang.OutOfMemoryError: Java heap space
Filter trigger matched.  Restart JVM (Ignoring, already restarting).

2018-12-21 10:46:41.616 [New I/O server worker #1-26] ERROR c.a.otter.canal.server.netty.handler.SessionHandler - something goes wrong with channel:[id: 0x4b1553a3, /10.3.1.112:44994 => /10.3.1.111:11111], exception=java.lang.OutOfMemoryError: Java heap space
Filter trigger matched.  Restart JVM (Ignoring, already restarting).

目前项目上有82个实例在一台canal server服务器里，但是一直报内存溢出。另外，canal server我们使用了wrapper.exe启动了，会产生大量的hprof文件，使用mat工具分析，发现entry无法回收，也就是增量数据无法回收。
![Uploading image.png…]()
目前jvm内存为10G，使用G1GC方式回收，30%回收一次

**Comment by agapple** [comment]
把ringbuffer调低，这个buffer数据是常驻内存的

**Comment by mengzhibule** [comment]
## memory store RingBuffer size, should be Math.pow(2,n)
canal.instance.memory.buffer.size = 1024
## memory store RingBuffer used memory unit size , default 1kb
canal.instance.memory.buffer.memunit = 1024

ringbuffer已经设置的比较小了。

**Comment by agapple** [comment]
尝试一下1.1.3版本，内存这块有一些优化，可以看下Performance wiki

**Comment by xmt1139057136** [comment]
`Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:57)
	at java.nio.ByteBuffer.allocate(ByteBuffer.java:335)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.readNextPacket(SimpleCanalConnector.java:394)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.readNextPacket(SimpleCanalConnector.java:376)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:151)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.connect(SimpleCanalConnector.java:113)
	at com.xttblog.canal.test.CanalTest.main(CanalTest.java:34)`

最新的 1.1.2 版本都无法使用！Java heap space 参考：[https://www.xttblog.com/?p=3345](https://www.xttblog.com/?p=3345)

**Comment by flyingonthebed** [comment]
上面这个文章要微信关注，很麻烦，英文原文是如下链接
https://plumbr.io/outofmemoryerror/java-heap-space
