### ISSUE TITLE
数据库连接失败

### ISSUE THREAD

**Issue by wu-xiaolu** [alibaba/canal#1339]
### environment

* canal version1.1.3
* mysql version5.7

###2018-12-25 16:44:12.086 [destination = example , address = /60.190.243.66:56666 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: connect /XXXX failure
Caused by: java.io.IOException: connect /XXXX failure
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:77)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.connect(MysqlConnection.java:88)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.preDump(MysqlEventParser.java:86)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:175)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannelPool.open(BioSocketChannelPool.java:18)
	at com.alibaba.otter.canal.parse.driver.mysql.socket.SocketChannelPool.open(SocketChannelPool.java:18)
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:72)
	... 4 more
]

一直是报数据库连接的问题，本地是可以连接canal的服务端的，但是订阅不到日志，日志打印上面的异常信息

**Comment by DinoZhang** [comment]
canal server 连不上数据库，检查下数据库白名单吧

**Comment by fangls** [comment]
我也有这个问题，在IDEA中导入的工程，通过CanalLauncher直接run报错
 [destination = example , address = /127.0.0.1:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: connect /127.0.0.1:3306 failure
Caused by: java.io.IOException: connect /127.0.0.1:3306 failure
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:77)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.connect(MysqlConnection.java:89)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.preDump(MysqlEventParser.java:86)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:175)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketException: Socket already closed.
	at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.write(BioSocketChannel.java:39)
	at com.alibaba.otter.canal.parse.driver.mysql.utils.PacketManager.writePkg(PacketManager.java:31)
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.negotiate(MysqlConnector.java:186)
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:74)
	... 4 more
]

但通过下载的canal.deployer-1.1.3-SNAPSHOT   使用startup.sh启动则没有问题

**Comment by bai020** [comment]
我也遇到这个问题了，还没解决

**Comment by cityiron** [comment]
我最新的镜像启动也是这个情况

**Comment by nullfy** [comment]
> 我最新的镜像启动也是这个情况

![image](https://user-images.githubusercontent.com/13701882/113133397-2c1cf180-9252-11eb-9c90-a135508e5139.png)

宿主机的mysql 8.0，这样配置是可行的
