### ISSUE TITLE
从canal v1.1.1升级到1.1.2 canal.log报错

### ISSUE THREAD

**Issue by pinkedidi** [alibaba/canal#1343]
### environment

* canal version 1.1.2
* mysql version 8.0.3
* docker version 18.x
### Issue Description
2018-12-26 11:36:30.202 [destination = chess , address = mysql/10.0.0.5:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> begin to find start position, it will be long time for reset or first position
2018-12-26 11:36:30.202 [destination = chess , address = mysql/10.0.0.5:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - prepare to find start position just show master status
2018-12-26 11:36:30.204 [destination = chess , address = mysql/10.0.0.5:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address mysql/10.0.0.5:3306 has an error, retrying. caused by 
java.lang.IllegalArgumentException: Invalid charset id: 255
        at com.taobao.tddl.dbsync.binlog.CharsetConversion.getEntry(CharsetConversion.java:41) ~[canal.parse.dbsync-1.1.2.jar:na]
        at com.taobao.tddl.dbsync.binlog.CharsetConversion.getJavaCharset(CharsetConversion.java:299) ~[canal.parse.dbsync-1.1.2.jar:na]
        at com.taobao.tddl.dbsync.binlog.event.QueryLogEvent.<init>(QueryLogEvent.java:503) ~[canal.parse.dbsync-1.1.2.jar:na]
        at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:168) ~[canal.parse.dbsync-1.1.2.jar:na]
        at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:111) ~[canal.parse.dbsync-1.1.2.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.seek(MysqlConnection.java:137) ~[canal.parse-1.1.2.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findAsPerTimestampInSpecificLogFile(MysqlEventParser.java:743) ~[canal.parse-1.1.2.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findEndPositionWithMasterIdAndTimestamp(MysqlEventParser.java:392) ~[canal.parse-1.1.2.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPositionInternal(MysqlEventParser.java:447) ~[canal.parse-1.1.2.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPosition(MysqlEventParser.java:366) ~[canal.parse-1.1.2.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:186) ~[canal.parse-1.1.2.jar:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
2018-12-26 11:36:30.205 [destination = chess , address = mysql/10.0.0.5:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:chess[java.lang.IllegalArgumentException: Invalid charset id: 255
        at com.taobao.tddl.dbsync.binlog.CharsetConversion.getEntry(CharsetConversion.java:41)
        at com.taobao.tddl.dbsync.binlog.CharsetConversion.getJavaCharset(CharsetConversion.java:299)
        at com.taobao.tddl.dbsync.binlog.event.QueryLogEvent.<init>(QueryLogEvent.java:503)
        at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:168)
        at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:111)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.seek(MysqlConnection.java:137)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findAsPerTimestampInSpecificLogFile(MysqlEventParser.java:743)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findEndPositionWithMasterIdAndTimestamp(MysqlEventParser.java:392)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPositionInternal(MysqlEventParser.java:447)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPosition(MysqlEventParser.java:366)
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:186)
        at java.lang.Thread.run(Thread.java:748)
]

### Steps to reproduce
因为生产上数据库8.0.3，故从1.1.1升级到1.1.2,结果报这样的错，请问是哪里配置出问题？另外mysql在docker环境下，禁止ping

**Comment by githubkevinyou** [comment]
canal.deployer-1.1.3-SNAPSHOT.tar.gz， mysql 8.0.13 还会报java.lang.IllegalArgumentException: Invalid charset id: 255

**Comment by githubkevinyou** [comment]
canal.deployer-1.1.3-SNAPSHOT.tar.gz， mysql 8.0.13直接部署虚拟机， 还会报[destination = example , address = /10.1.137.68:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[java.lang.IllegalArgumentException: Invalid charset id: 255

**Comment by agapple** [comment]
你用master代码自己打包一个，1.1.3-alpha-1还没包含最新的代码

**Comment by waterzmh** [comment]
环境:
canal 1.1.2
mysql 8.0.12
mac 10.14.2

按照教程配置了各种需要的以后,example.log日志如下：
       2019-03-07 18:18:43.945 [destination = example , address = /127.0.0.1:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[com.alibaba.otter.canal.parse.exception.CanalParseException: java.lang.IllegalArgumentException: Invalid charset id: 255
Caused by: java.lang.IllegalArgumentException: Invalid charset id: 255
        at com.taobao.tddl.dbsync.binlog.CharsetConversion.getEntry(CharsetConversion.java:41)
        at com.taobao.tddl.dbsync.binlog.CharsetConversion.getJavaCharset(CharsetConversion.java:299)
        at com.taobao.tddl.dbsync.binlog.event.QueryLogEvent.<init>(QueryLogEvent.java:503)
        at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:168)
        at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:111)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:264)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:246)
        at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168)
        at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

请问这个255错误可以从哪些角度去定位这个问题？

**Comment by jerryzhengsz** [comment]
我也发现这个错误了,改源码强加了255的charset 还是报错.
mysql-8.0.13
canal 1.1.2

**Comment by agapple** [comment]
试用最新的1.1.3版本
