### ISSUE TITLE
something goes wrong with channel

### ISSUE THREAD

**Issue by jianghaibolxy** [alibaba/canal#1348]
### environment

* canal version
1.1.0
* mysql version
mysql5.7

### Issue Description
2018-12-27 08:08:31.866 [New I/O server worker #1-4] ERROR c.a.otter.canal.server.netty.handler.SessionHandler - something goes wrong with channel:[id: 0x01834f51, /172.25.204.37:51382 :> /10.101.93.83:11111], exception=java.nio.channels.ClosedChannelException
	at org.jboss.netty.channel.socket.nio.NioWorker.cleanUpWriteBuffer(NioWorker.java:629)
	at org.jboss.netty.channel.socket.nio.NioWorker.close(NioWorker.java:605)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:356)
	at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:281)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:201)
	at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
这个问题升级到1.1.1以后就会消失吗？

**Comment by agapple** [comment]
java.nio.channels.ClosedChannelException， 客户端断开连接
