### ISSUE TITLE
HA模式下 client 连接显示超时

### ISSUE THREAD

**Issue by bestzhao** [alibaba/canal#1373]
### environment

* canal version
* mysql version

### Issue Description
client连接HA的sever的时候抛出超时，断点打进去的时候是获取到sever地址的，单机模式的时候也是可以的，不知道是啥错误。

### Expected behaviour
`17:44:49.666 [main] ERROR c.a.o.c.c.i.r.ClientRunningMonitor - There is an error when execute initRunning method, with destination [example].
com.alibaba.otter.canal.protocol.exception.CanalClientException: java.net.ConnectException: Operation timed out
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:189) [canal.client-1.1.1.jar:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.access$000(SimpleCanalConnector.java:50) [canal.client-1.1.1.jar:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector$1.processActiveEnter(SimpleCanalConnector.java:422) ~[canal.client-1.1.1.jar:na]
	at com.alibaba.otter.canal.client.impl.running.ClientRunningMonitor.processActiveEnter(ClientRunningMonitor.java:211) [canal.client-1.1.1.jar:na]
	at com.alibaba.otter.canal.client.impl.running.ClientRunningMonitor.initRunning(ClientRunningMonitor.java:122) [canal.client-1.1.1.jar:na]
	at com.alibaba.otter.canal.client.impl.running.ClientRunningMonitor.start(ClientRunningMonitor.java:92) [canal.client-1.1.1.jar:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.connect(SimpleCanalConnector.java:106) [canal.client-1.1.1.jar:na]
	at com.alibaba.otter.canal.client.impl.ClusterCanalConnector.connect(ClusterCanalConnector.java:64) [canal.client-1.1.1.jar:na]
	at com.alibaba.otter.ClientSample.main(ClientSample.java:30) [classes/:na]
Caused by: java.net.ConnectException: Operation timed out
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_191]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_191]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_191]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_191]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:148) [canal.client-1.1.1.jar:na]
	... 8 common frames omitted`

**Comment by agapple** [comment]
java.net.ConnectException: Operation timed out at sun.nio.ch.Net.connect0

感觉是网络层面的问题，非软件本身

**Comment by gxstax** [comment]
遇到同样的问题，你这边是怎么解决的？
