### ISSUE TITLE
canal-adapter运行几分钟后开始出现报错

### ISSUE THREAD

**Issue by wurongjun** [alibaba/canal#1375]
### environment

* canal version 1.1.2
* mysql version 5.6.37

### Issue Description
canal-adapter刚启动后可正常提供服务，但过了几分钟后就自己出现报错，报错信息如下：
2019-01-03 19:50:48.612 ERROR 22225 --- [pool-9-thread-1] c.a.o.canal.client.adapter.support.Util  : connection holder is null

java.sql.SQLException: connection holder is null
	at com.alibaba.druid.pool.DruidPooledConnection.checkStateInternal(DruidPooledConnection.java:1155) ~[druid-1.1.9.jar:1.1.9]
	at com.alibaba.druid.pool.DruidPooledConnection.checkState(DruidPooledConnection.java:1148) ~[druid-1.1.9.jar:1.1.9]
	at com.alibaba.druid.pool.DruidPooledConnection.createStatement(DruidPooledConnection.java:636) ~[druid-1.1.9.jar:1.1.9]
	at com.alibaba.otter.canal.client.adapter.support.Util.sqlRS(Util.java:71) ~[client-adapter.common-1.1.3-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.getTargetColumnType(RdbSyncService.java:376) [client-adapter.rdb-1.1.3-SNAPSHOT-jar-with-dependencies.jar:na]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.update(RdbSyncService.java:287) [client-adapter.rdb-1.1.3-SNAPSHOT-jar-with-dependencies.jar:na]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.sync(RdbSyncService.java:195) [client-adapter.rdb-1.1.3-SNAPSHOT-jar-with-dependencies.jar:na]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$null$0(RdbSyncService.java:106) [client-adapter.rdb-1.1.3-SNAPSHOT-jar-with-dependencies.jar:na]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_172]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$sync$1(RdbSyncService.java:106) [client-adapter.rdb-1.1.3-SNAPSHOT-jar-with-dependencies.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_172]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_172]
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Communications link failure during commit(). Transaction resolution unknown.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_172]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_172]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_172]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_172]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.40.jar:5.1.40]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.40.jar:5.1.40]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:918) ~[mysql-connector-java-5.1.40.jar:5.1.40]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:897) ~[mysql-connector-java-5.1.40.jar:5.1.40]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:886) ~[mysql-connector-java-5.1.40.jar:5.1.40]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860) ~[mysql-connector-java-5.1.40.jar:5.1.40]
	at com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1618) ~[mysql-connector-java-5.1.40.jar:5.1.40]
	at com.alibaba.druid.pool.DruidPooledConnection.commit(DruidPooledConnection.java:749) ~[druid-1.1.9.jar:1.1.9]
	at com.alibaba.otter.canal.client.adapter.rdb.support.BatchExecutor.commit(BatchExecutor.java:71) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$sync$1(RdbSyncService.java:107) [client-adapter.rdb-1.1.3-SNAPSHOT-jar-with-dependencies.jar:na]
	... 4 common frames omitted

### Expected behaviour
查了资料，好像是和Druid的初始化有关

**Comment by agapple** [comment]
可以尝试一下1.1.3 alpha-3版本，adapter的问题有修复

**Comment by cynen** [comment]
1.1.7 好像也出这个问题. 

```

The last packet successfully received from the server was 10,010 milliseconds ago.  The last packet sent successfully to the server was 10,010 milliseconds ago.
java.lang.RuntimeException: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
```

**Comment by KuanKuanya** [comment]
@cynen 这个问题你解决了嘛？

**Comment by cynen** [comment]
太久了,我忘记了当时怎么解决的了.
不过我没有使用adapter.目前数据迁移是直接自己写consumer从rocketmq去消费完成同步的.
目前只用了 admin和canal-server.稳定运行了1年多.
