### ISSUE TITLE
canal 1.1.3-SNAPSHOT git 下载自己编译后报找不到CharsetConversion

### ISSUE THREAD

**Issue by githubkevinyou** [alibaba/canal#1377]
### environment

* canal 1.1.3-SNAPSHOT
* mysql 8.0.13

### Issue Description
2019-01-04 11:46:48.032 [destination = example , address = /xxxxxx:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> begin to find start position, it will be long time for reset or first position
2019-01-04 11:46:48.033 [destination = example , address = /xxxxxx:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - prepare to find start position just show master status
2019-01-04 11:46:48.041 [destination = example , address = /xxxxxx:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address /xxxxx:3306 has an error, retrying. caused by 
java.lang.NoClassDefFoundError: Could not initialize class com.taobao.tddl.dbsync.binlog.CharsetConversion
        at com.taobao.tddl.dbsync.binlog.event.QueryLogEvent.<init>(QueryLogEvent.java:503) ~[canal.parse.dbsync-1.1.3-SNAPSHOT.jar:na]
        at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:168) ~[canal.parse.dbsync-1.1.3-SNAPSHOT.jar:na]
        at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:111) ~[canal.parse.dbsync-1.1.3-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.seek(MysqlConnection.java:145) ~[canal.parse-1.1.3-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findAsPerTimestampInSpecificLogFile(MysqlEventParser.java:743) ~[canal.parse-1.1.3-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findEndPositionWithMasterIdAndTimestamp(MysqlEventParser.java:392) ~[canal.parse-1.1.3-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPositionInternal(MysqlEventParser.java:447) ~[canal.parse-1.1.3-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPosition(MysqlEventParser.java:366) ~[canal.parse-1.1.3-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:186) ~[canal.parse-1.1.3-SNAPSHOT.jar:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
2019-01-04 11:46:48.042 [destination = example , address = /xxxxx:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[java.lang.NoClassDefFoundError: Could not initialize class com.taobao.tddl.dbsync.binlog.CharsetConversion
        at com.taobao.tddl.dbsync.binlog.event.QueryLogEvent.<init>(QueryLogEvent.java:503)
        at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:168)
        at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:111)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.seek(MysqlConnection.java:145)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findAsPerTimestampInSpecificLogFile(MysqlEventParser.java:743)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findEndPositionWithMasterIdAndTimestamp(MysqlEventParser.java:392)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPositionInternal(MysqlEventParser.java:447)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPosition(MysqlEventParser.java:366)
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:186)
        at java.lang.Thread.run(Thread.java:748)

**Comment by agapple** [comment]
更新一下最新的代码，已修复
