### ISSUE TITLE
canal1.1.2版本不支持kafka的clientid

### ISSUE THREAD

**Issue by dingaiminGIT** [alibaba/canal#1378]
### environment

* canal version 1.1.2
* mysql version 5.6.27
* kafka version 1.0  开源版本的基础上定制化开发了

### Issue Description
    canal的1.1.2版本，使用kafka的方式。目前存在的问题是kafka的topic权限问题。我们公司的kafka在开源1.0版本的基础上进行了定制化开发，需要支持clientid进行topic的权限验证。但在canal的配置文件中没有发现填写kafka clientid的地方.

### Steps to reproduce
配置好mq的配置文件后，启动canal

主要是没有topic的权限，因为kafka需要clientid，但canal配置文件中没有提供
### Expected behaviour
预期启动canal后，canal能有权限访问kafka的topic
### Actual behaviour
 ERROR com.alibaba.otter.canal.kafka.CanalKafkaProducer - org.apache.kafka.common.errors.TopicAuthorizationException: Not authorized to access topics: [hdp_lbg
java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TopicAuthorizationException: Not authorized to access topics: [hdp_lbg_ectech_dsp_canal
	at org.apache.kafka.clients.producer.KafkaProducer$FutureFailure.<init>(KafkaProducer.java:1150) ~[kafka-clients-1.1.1.jar:na]
	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:846) ~[kafka-clients-1.1.1.jar:na]
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:784) ~[kafka-clients-1.1.1.jar:na]
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:671) ~[kafka-clients-1.1.1.jar:na]
	at com.alibaba.otter.canal.kafka.CanalKafkaProducer.send(CanalKafkaProducer.java:118) ~[canal.server-1.1.2.jar:na]
	at com.alibaba.otter.canal.server.CanalMQStarter.worker(CanalMQStarter.java:148) [canal.server-1.1.2.jar:na]
	at com.alibaba.otter.canal.server.CanalMQStarter.access$500(CanalMQStarter.java:21) [canal.server-1.1.2.jar:na]
	at com.alibaba.otter.canal.server.CanalMQStarter$CanalMQRunnable.run(CanalMQStarter.java:197) [canal.server-1.1.2.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_66]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66]
Caused by: org.apache.kafka.common.errors.TopicAuthorizationException: Not authorized to access topics: [hdp_lbg_ectech_dsp_canal_offline]

**Comment by agapple** [comment]
可以提交一个代码PR给我
