### ISSUE TITLE
Canal RDB Adpater运行一段时间报：java.sql.SQLException: connection holder is null

### ISSUE THREAD

**Issue by flackyang** [alibaba/canal#1396]
### environment

* canal version 1.2
* mysql version 5.7.20

### Issue Description
Canal RDB Apdater运行一段时间后报：
~~~
java.lang.RuntimeException: java.sql.SQLException: connection holder is null
	at com.cscs.daas.datasync.rdb.support.BatchExecutor.execute(BatchExecutor.java:66) ~[datasync-client-rdb-1.0-jar-with-dependencies.jar:na]
	at com.cscs.daas.datasync.rdb.service.RdbSyncService.insert(RdbSyncService.java:280) [datasync-client-rdb-1.0-jar-with-dependencies.jar:na]
	at com.cscs.daas.datasync.rdb.service.RdbSyncService.sync(RdbSyncService.java:213) [datasync-client-rdb-1.0-jar-with-dependencies.jar:na]
	at com.cscs.daas.datasync.rdb.service.RdbSyncService.lambda$null$5(RdbSyncService.java:108) [datasync-client-rdb-1.0-jar-with-dependencies.jar:na]
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[na:1.8.0_60]
	at com.cscs.daas.datasync.rdb.service.RdbSyncService.lambda$sync$6(RdbSyncService.java:108) [datasync-client-rdb-1.0-jar-with-dependencies.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_60]
Caused by: java.sql.SQLException: connection holder is null
	at com.alibaba.druid.pool.DruidPooledConnection.checkStateInternal(DruidPooledConnection.java:1155) ~[druid-1.1.9.jar:1.1.9]
	at com.alibaba.druid.pool.DruidPooledConnection.checkState(DruidPooledConnection.java:1148) ~[druid-1.1.9.jar:1.1.9]
	at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:336) ~[druid-1.1.9.jar:1.1.9]
	at com.cscs.daas.datasync.rdb.support.BatchExecutor.execute(BatchExecutor.java:54) ~[datasync-client-rdb-1.0-jar-with-dependencies.jar:na]
	... 9 common frames omitted
~~~

好像是RdbSyncService类batchExecutors中初始化时获取的连接(dataSource.getConnection())运行一段时间后被自动close了

**Comment by wurongjun** [comment]
我也出现了这个问题。应该和druid连接池配置有关

**Comment by chenjgtea** [comment]
大概看了一下源代码，BatchExecutor 这个用的是通过datasource的 Connection来做创建连接的，而datasource 是对Connection 是有 自动超时回收机制的，这样很容易常时间没有同步任务的话， Connection 是会被回收的。目前临时解决方案，可以通过配置 DataSource的禁止自动回收的方式来解决。

**Comment by chenjgtea** [comment]
adpater模块感觉还是有很多地方不太稳定，现在我们已经打算单独拉一个分支出来，针对性的解决适用场景解决问题，另外如果有新的功能或者bugfix，在同步更新到拉出来的分支上去。

**Comment by wurongjun** [comment]
> adpater模块感觉还是有很多地方不太稳定，现在我们已经打算单独拉一个分支出来，针对性的解决适用场景解决问题，另外如果有新的功能或者bugfix，在同步更新到拉出来的分支上去。

分支名是什么？另外是怎么解决“connection holder is null”这个问题的

**Comment by KangZhiDong** [comment]
刚解决了这问题，nice

**Comment by wurongjun** [comment]
> 刚解决了这问题，nice

怎么解决的

**Comment by daisanmu** [comment]
请问怎么解决的？

**Comment by daisanmu** [comment]
> 刚解决了这问题，nice

请问怎么解决的？

**Comment by w0nwig** [comment]
怎么解决的啊 后面没开发同步工具 就没关注canal了


散木 <notifications@github.com> 于2020年7月17日周五 上午10:39写道：
