### ISSUE TITLE
1.1.3-alpha-2 canal RdbAdapter the `truncate table` dml won't works well

### ISSUE THREAD

**Issue by TheNorthMemory** [alibaba/canal#1408]
### environment

* canal version = 1.1.3-alpha-2
* mysql version = 5.5.18

### Issue Description

```
2019-01-10 23:59:47.478  INFO 319 --- [       Thread-7] c.a.o.c.a.l.loader.CanalAdapterWorker    : =============> Subscribe destination: test succeed <=============

2019-01-11 00:00:18.138  INFO 319 --- [pool-7-thread-1] c.a.o.c.c.a.logger.LoggerAdapterExample  : DML: {"data":[{"id":1,"name":"{\"title\":12345678}"}],"database":"dbtest","destination":"test","es":1547136017000,"isDdl":null,"old":null,"pkNames":["id"],"sql":"","table":"test","ts":1547136018115,"type":"INSERT"}
2019-01-11 00:00:18.142  INFO 319 --- [pool-7-thread-1] c.a.o.c.c.a.logger.LoggerAdapterExample  : DML: {"data":[{"id":2,"name":"{\"title\":\"\\\"ok\\\"\"}"}],"database":"dbtest","destination":"test","es":1547136017000,"isDdl":null,"old":null,"pkNames":["id"],"sql":"","table":"test","ts":1547136018118,"type":"INSERT"}
2019-01-11 00:00:18.270 DEBUG 319 --- [pool-3-thread-1] c.a.o.c.c.a.rdb.service.RdbSyncService   : DML: {"data":{"id":1,"name":"{\"title\":12345678}"},"database":"dbtest","destination":"test","old":null,"table":"test","type":"INSERT"}
2019-01-11 00:00:18.288 DEBUG 319 --- [pool-3-thread-1] c.a.o.c.c.a.rdb.service.RdbSyncService   : DML: {"data":{"id":2,"name":"{\"title\":\"\\\"ok\\\"\"}"},"database":"dbtest","destination":"test","old":null,"table":"test","type":"INSERT"}
2019-01-11 00:00:18.385 DEBUG 319 --- [pool-5-thread-1] c.a.o.c.c.a.rdb.service.RdbSyncService   : DML: {"data":{"id":1,"name":"{\"title\":12345678}"},"database":"dbtest","destination":"test","old":null,"table":"test","type":"INSERT"}
2019-01-11 00:00:18.418 DEBUG 319 --- [pool-5-thread-1] c.a.o.c.c.a.rdb.service.RdbSyncService   : DML: {"data":{"id":2,"name":"{\"title\":\"\\\"ok\\\"\"}"},"database":"dbtest","destination":"test","old":null,"table":"test","type":"INSERT"}
2019-01-11 00:00:27.348  INFO 319 --- [pool-7-thread-1] c.a.o.c.c.a.logger.LoggerAdapterExample  : DML: {"data":[{"id":1,"name":"{\"title\":\"\\\"ok\\\"\"}"}],"database":"dbtest","destination":"test","es":1547136026000,"isDdl":null,"old":[{"name":"{\"title\":12345678}"}],"pkNames":["id"],"sql":"","table":"test","ts":1547136027347,"type":"UPDATE"}
2019-01-11 00:00:27.351  INFO 319 --- [pool-7-thread-1] c.a.o.c.c.a.logger.LoggerAdapterExample  : DML: {"data":[{"id":3,"name":"{\"title\":12345678}"}],"database":"dbtest","destination":"test","es":1547136026000,"isDdl":null,"old":null,"pkNames":["id"],"sql":"","table":"test","ts":1547136027348,"type":"INSERT"}
2019-01-11 00:00:27.355  INFO 319 --- [pool-7-thread-1] c.a.o.c.c.a.logger.LoggerAdapterExample  : DML: {"data":[{"id":4,"name":"{\"title\":\"\\\"ok\\\"\"}"}],"database":"dbtest","destination":"test","es":1547136026000,"isDdl":null,"old":null,"pkNames":["id"],"sql":"","table":"test","ts":1547136027348,"type":"INSERT"}
2019-01-11 00:00:27.380 DEBUG 319 --- [pool-3-thread-1] c.a.o.c.c.a.rdb.service.RdbSyncService   : DML: {"data":{"id":1,"name":"{\"title\":\"\\\"ok\\\"\"}"},"database":"dbtest","destination":"test","old":{"name":"{\"title\":12345678}"},"table":"test","type":"UPDATE"}
2019-01-11 00:00:27.405 DEBUG 319 --- [pool-3-thread-1] c.a.o.c.c.a.rdb.service.RdbSyncService   : DML: {"data":{"id":3,"name":"{\"title\":12345678}"},"database":"dbtest","destination":"test","old":null,"table":"test","type":"INSERT"}
2019-01-11 00:00:27.424 DEBUG 319 --- [pool-3-thread-1] c.a.o.c.c.a.rdb.service.RdbSyncService   : DML: {"data":{"id":4,"name":"{\"title\":\"\\\"ok\\\"\"}"},"database":"dbtest","destination":"test","old":null,"table":"test","type":"INSERT"}
2019-01-11 00:00:27.476 DEBUG 319 --- [pool-5-thread-1] c.a.o.c.c.a.rdb.service.RdbSyncService   : DML: {"data":{"id":1,"name":"{\"title\":\"\\\"ok\\\"\"}"},"database":"dbtest","destination":"test","old":{"name":"{\"title\":12345678}"},"table":"test","type":"UPDATE"}
2019-01-11 00:00:27.512 DEBUG 319 --- [pool-5-thread-1] c.a.o.c.c.a.rdb.service.RdbSyncService   : DML: {"data":{"id":3,"name":"{\"title\":12345678}"},"database":"dbtest","destination":"test","old":null,"table":"test","type":"INSERT"}
2019-01-11 00:00:27.541 DEBUG 319 --- [pool-5-thread-1] c.a.o.c.c.a.rdb.service.RdbSyncService   : DML: {"data":{"id":4,"name":"{\"title\":\"\\\"ok\\\"\"}"},"database":"dbtest","destination":"test","old":null,"table":"test","type":"INSERT"}
2019-01-11 00:01:18.028  INFO 319 --- [pool-7-thread-1] c.a.o.c.c.a.logger.LoggerAdapterExample  : DML: {"data":[{"id":1,"name":"{\"title\":\"\\\"ok\\\"\"}"},{"id":2,"name":"{\"title\":\"\\\"ok\\\"\"}"}],"database":"dbtest","destination":"test","es":1547136077000,"isDdl":null,"old":null,"pkNames":["id"],"sql":"","table":"test","ts":1547136078028,"type":"DELETE"}
2019-01-11 00:01:18.054 DEBUG 319 --- [pool-3-thread-1] c.a.o.c.c.a.rdb.service.RdbSyncService   : DML: {"data":{"id":1,"name":"{\"title\":\"\\\"ok\\\"\"}"},"database":"dbtest","destination":"test","old":null,"table":"test","type":"DELETE"}
2019-01-11 00:01:18.078 DEBUG 319 --- [pool-3-thread-1] c.a.o.c.c.a.rdb.service.RdbSyncService   : DML: {"data":{"id":2,"name":"{\"title\":\"\\\"ok\\\"\"}"},"database":"dbtest","destination":"test","old":null,"table":"test","type":"DELETE"}
2019-01-11 00:01:18.129 DEBUG 319 --- [pool-5-thread-1] c.a.o.c.c.a.rdb.service.RdbSyncService   : DML: {"data":{"id":1,"name":"{\"title\":\"\\\"ok\\\"\"}"},"database":"dbtest","destination":"test","old":null,"table":"test","type":"DELETE"}
2019-01-11 00:01:18.158 DEBUG 319 --- [pool-5-thread-1] c.a.o.c.c.a.rdb.service.RdbSyncService   : DML: {"data":{"id":2,"name":"{\"title\":\"\\\"ok\\\"\"}"},"database":"dbtest","destination":"test","old":null,"table":"test","type":"DELETE"}
2019-01-11 00:01:32.593  INFO 319 --- [pool-7-thread-1] c.a.o.c.c.a.logger.LoggerAdapterExample  : DML: {"data":null,"database":"dbtest","destination":"test","es":1547136091000,"isDdl":null,"old":null,"pkNames":null,"sql":"TRUNCATE table test","table":"test","ts":1547136092593,"type":"TRUNCATE"}
2019-01-11 00:01:32.611 ERROR 319 --- [pool-7-thread-2] c.a.o.c.a.l.loader.CanalAdapterWorker    : java.util.concurrent.ExecutionException: java.lang.NullPointerException

java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at com.alibaba.otter.canal.client.adapter.rdb.RdbAdapter.sync(RdbAdapter.java:171) ~[na:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.batchSync(AbstractCanalAdapterWorker.java:197) ~[client-adapter.launcher-1.1.3-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$1(AbstractCanalAdapterWorker.java:61) ~[client-adapter.launcher-1.1.3-SNAPSHOT.jar:na]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_181]
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$2(AbstractCanalAdapterWorker.java:57) ~[client-adapter.launcher-1.1.3-SNAPSHOT.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_181]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_181]
	at com.alibaba.otter.canal.client.adapter.rdb.RdbAdapter.sync(RdbAdapter.java:168) ~[na:na]
	... 8 common frames omitted
Caused by: java.lang.NullPointerException: null
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.pkHash(RdbSyncService.java:454) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.pkHash(RdbSyncService.java:438) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$null$3(RdbSyncService.java:160) ~[na:na]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_181]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$sync$5(RdbSyncService.java:159) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.sync(RdbSyncService.java:98) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.sync(RdbSyncService.java:139) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.rdb.RdbAdapter.lambda$sync$2(RdbAdapter.java:160) ~[na:na]
	... 4 common frames omitted

2019-01-11 00:01:32.634 ERROR 319 --- [       Thread-7] c.a.o.c.a.l.loader.CanalAdapterWorker    : Outer adapter sync failed!  Error sync and rollback, execute times: 1
2019-01-11 00:01:33.140  INFO 319 --- [pool-7-thread-3] c.a.o.c.c.a.logger.LoggerAdapterExample  : DML: {"data":null,"database":"dbtest","destination":"test","es":1547136091000,"isDdl":null,"old":null,"pkNames":null,"sql":"TRUNCATE table test","table":"test","ts":1547136093139,"type":"TRUNCATE"}
2019-01-11 00:01:33.168 ERROR 319 --- [pool-7-thread-1] c.a.o.c.a.l.loader.CanalAdapterWorker    : java.util.concurrent.ExecutionException: java.lang.NullPointerException

java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at com.alibaba.otter.canal.client.adapter.rdb.RdbAdapter.sync(RdbAdapter.java:171) ~[na:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.batchSync(AbstractCanalAdapterWorker.java:197) ~[client-adapter.launcher-1.1.3-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$1(AbstractCanalAdapterWorker.java:61) ~[client-adapter.launcher-1.1.3-SNAPSHOT.jar:na]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_181]
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$2(AbstractCanalAdapterWorker.java:57) ~[client-adapter.launcher-1.1.3-SNAPSHOT.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_181]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_181]
	at com.alibaba.otter.canal.client.adapter.rdb.RdbAdapter.sync(RdbAdapter.java:168) ~[na:na]
	... 8 common frames omitted
Caused by: java.lang.NullPointerException: null
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.pkHash(RdbSyncService.java:454) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.pkHash(RdbSyncService.java:438) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$null$3(RdbSyncService.java:160) ~[na:na]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_181]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$sync$5(RdbSyncService.java:159) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.sync(RdbSyncService.java:98) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.sync(RdbSyncService.java:139) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.rdb.RdbAdapter.lambda$sync$2(RdbAdapter.java:160) ~[na:na]
	... 4 common frames omitted

2019-01-11 00:01:33.205 ERROR 319 --- [       Thread-7] c.a.o.c.a.l.loader.CanalAdapterWorker    : Outer adapter sync failed!  Error sync and rollback, execute times: 2
2019-01-11 00:01:33.708  INFO 319 --- [pool-7-thread-2] c.a.o.c.c.a.logger.LoggerAdapterExample  : DML: {"data":null,"database":"dbtest","destination":"test","es":1547136091000,"isDdl":null,"old":null,"pkNames":null,"sql":"TRUNCATE table test","table":"test","ts":1547136093707,"type":"TRUNCATE"}
2019-01-11 00:01:33.727 ERROR 319 --- [pool-7-thread-3] c.a.o.c.a.l.loader.CanalAdapterWorker    : java.util.concurrent.ExecutionException: java.lang.NullPointerException

java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at com.alibaba.otter.canal.client.adapter.rdb.RdbAdapter.sync(RdbAdapter.java:171) ~[na:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.batchSync(AbstractCanalAdapterWorker.java:197) ~[client-adapter.launcher-1.1.3-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$1(AbstractCanalAdapterWorker.java:61) ~[client-adapter.launcher-1.1.3-SNAPSHOT.jar:na]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_181]
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$2(AbstractCanalAdapterWorker.java:57) ~[client-adapter.launcher-1.1.3-SNAPSHOT.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_181]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_181]
	at com.alibaba.otter.canal.client.adapter.rdb.RdbAdapter.sync(RdbAdapter.java:168) ~[na:na]
	... 8 common frames omitted
Caused by: java.lang.NullPointerException: null
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.pkHash(RdbSyncService.java:454) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.pkHash(RdbSyncService.java:438) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$null$3(RdbSyncService.java:160) ~[na:na]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_181]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$sync$5(RdbSyncService.java:159) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.sync(RdbSyncService.java:98) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.sync(RdbSyncService.java:139) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.rdb.RdbAdapter.lambda$sync$2(RdbAdapter.java:160) ~[na:na]
	... 4 common frames omitted

2019-01-11 00:01:33.741 ERROR 319 --- [       Thread-7] c.a.o.c.a.l.loader.CanalAdapterWorker    : Outer adapter sync failed!  Error sync and rollback, execute times: 3
2019-01-11 00:01:34.244  INFO 319 --- [pool-7-thread-1] c.a.o.c.c.a.logger.LoggerAdapterExample  : DML: {"data":null,"database":"dbtest","destination":"test","es":1547136091000,"isDdl":null,"old":null,"pkNames":null,"sql":"TRUNCATE table test","table":"test","ts":1547136094244,"type":"TRUNCATE"}
2019-01-11 00:01:34.260 ERROR 319 --- [pool-7-thread-2] c.a.o.c.a.l.loader.CanalAdapterWorker    : java.util.concurrent.ExecutionException: java.lang.NullPointerException

java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at com.alibaba.otter.canal.client.adapter.rdb.RdbAdapter.sync(RdbAdapter.java:171) ~[na:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.batchSync(AbstractCanalAdapterWorker.java:197) ~[client-adapter.launcher-1.1.3-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$1(AbstractCanalAdapterWorker.java:61) ~[client-adapter.launcher-1.1.3-SNAPSHOT.jar:na]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_181]
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$2(AbstractCanalAdapterWorker.java:57) ~[client-adapter.launcher-1.1.3-SNAPSHOT.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_181]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_181]
	at com.alibaba.otter.canal.client.adapter.rdb.RdbAdapter.sync(RdbAdapter.java:168) ~[na:na]
	... 8 common frames omitted
Caused by: java.lang.NullPointerException: null
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.pkHash(RdbSyncService.java:454) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.pkHash(RdbSyncService.java:438) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$null$3(RdbSyncService.java:160) ~[na:na]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_181]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$sync$5(RdbSyncService.java:159) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.sync(RdbSyncService.java:98) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.sync(RdbSyncService.java:139) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.rdb.RdbAdapter.lambda$sync$2(RdbAdapter.java:160) ~[na:na]
	... 4 common frames omitted

2019-01-11 00:01:34.281 ERROR 319 --- [       Thread-7] c.a.o.c.a.l.loader.CanalAdapterWorker    : Outer adapter sync failed!  Error sync and rollback, execute times: 4
2019-01-11 00:01:34.789  INFO 319 --- [pool-7-thread-3] c.a.o.c.c.a.logger.LoggerAdapterExample  : DML: {"data":null,"database":"dbtest","destination":"test","es":1547136091000,"isDdl":null,"old":null,"pkNames":null,"sql":"TRUNCATE table test","table":"test","ts":1547136094789,"type":"TRUNCATE"}
2019-01-11 00:01:34.806 ERROR 319 --- [pool-7-thread-1] c.a.o.c.a.l.loader.CanalAdapterWorker    : java.util.concurrent.ExecutionException: java.lang.NullPointerException

java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at com.alibaba.otter.canal.client.adapter.rdb.RdbAdapter.sync(RdbAdapter.java:171) ~[na:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.batchSync(AbstractCanalAdapterWorker.java:197) ~[client-adapter.launcher-1.1.3-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$1(AbstractCanalAdapterWorker.java:61) ~[client-adapter.launcher-1.1.3-SNAPSHOT.jar:na]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_181]
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$2(AbstractCanalAdapterWorker.java:57) ~[client-adapter.launcher-1.1.3-SNAPSHOT.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_181]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_181]
	at com.alibaba.otter.canal.client.adapter.rdb.RdbAdapter.sync(RdbAdapter.java:168) ~[na:na]
	... 8 common frames omitted
Caused by: java.lang.NullPointerException: null
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.pkHash(RdbSyncService.java:454) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.pkHash(RdbSyncService.java:438) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$null$3(RdbSyncService.java:160) ~[na:na]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_181]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$sync$5(RdbSyncService.java:159) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.sync(RdbSyncService.java:98) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.sync(RdbSyncService.java:139) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.rdb.RdbAdapter.lambda$sync$2(RdbAdapter.java:160) ~[na:na]
	... 4 common frames omitted

2019-01-11 00:01:34.823 ERROR 319 --- [       Thread-7] c.a.o.c.a.l.loader.CanalAdapterWorker    : Outer adapter sync failed!  Error sync but ACK!
```

### Steps to reproduce

源库内执行  `truncate table test`, RdbAdapter 抛异常无法同步，log如上。

### Expected behaviour

`truncate table test` 可同步。

### Actual behaviour

`Outer adapter sync failed!  Error sync but ACK!`

**Comment by TheNorthMemory** [comment]
可用，赞～
