### ISSUE TITLE
canal server1.1.0 通过客户端增加了要监听的表，遇到了 “fetch failed by table meta”错误及修正

### ISSUE THREAD

**Issue by ldsberry** [alibaba/canal#1410]
### environment

* 1.1.0
* 5.7.14

### Issue Description
canal 运行一段时间之后，通过客户端增加了要监听的表的数量，增加的表有数据变化时，部分表在取表的table meta时遇到了 “fetch failed by table meta”错误，这个错误不是必然出现，

2019-01-09 10:29:54.104 [destination = xxxx , address = /xxxx , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address xxx/xxxxx has an error, retrying. caused by 
com.alibaba.otter.canal.parse.exception.CanalParseException: com.alibaba.otter.canal.parse.exception.CanalParseException: com.alibaba.otter.canal.parse.exception.CanalParseException: fetch failed by table meta:`prodccsdb`.`gls_expen_reimb_v`
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: com.alibaba.otter.canal.parse.exception.CanalParseException: fetch failed by table meta:`prodccsdb`.`gls_expen_reimb_v`
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: fetch failed by table meta:`prodccsdb`.`gls_expen_reimb_v`
Caused by: java.net.SocketException: Broken pipe (Write failed)
	at java.net.SocketOutputStream.socketWrite0(Native Method) ~[na:1.8.0_141]
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111) ~[na:1.8.0_141]
	at java.net.SocketOutputStream.write(SocketOutputStream.java:143) ~[na:1.8.0_141]
	at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.write(BioSocketChannel.java:36) ~[canal.parse.driver-1.1.0.jar:na]
	at com.alibaba.otter.canal.parse.driver.mysql.utils.PacketManager.writeBody0(PacketManager.java:42) ~[canal.parse.driver-1.1.0.jar:na]
	at com.alibaba.otter.canal.parse.driver.mysql.utils.PacketManager.writeBody(PacketManager.java:35) ~[canal.parse.driver-1.1.0.jar:na]
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlQueryExecutor.query(MysqlQueryExecutor.java:55) ~[canal.parse.driver-1.1.0.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.query(MysqlConnection.java:102) ~[canal.parse-1.1.0.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.TableMetaCache.getTableMeta(TableMetaCache.java:167) ~[canal.parse-1.1.0.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.getTableMeta(LogEventConvert.java:889) ~[canal.parse-1.1.0.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseRowsEventForTableMeta(LogEventConvert.java:484) ~[canal.parse-1.1.0.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:252) ~[canal.parse-1.1.0.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:222) ~[canal.parse-1.1.0.jar:na]
	at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168) ~[disruptor-3.4.2.jar:na]
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125) ~[disruptor-3.4.2.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_141]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_141]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_141]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_141]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_141]

### 解决方案
TableMetaCache.java中对如下部分代码进行修改，查询表结构出现异常时进行一次重连然后再次进行查询

                // 因为条件变化，可能第一次的tableMeta没取到，需要从db获取一次，并记录到snapshot中
                String fullName = getFullName(schema, table);
                try {
                    ResultSetPacket packet = connection.query("show create table " + fullName);
                    String createDDL = null;
                    if (packet.getFieldValues().size() > 0) {
                        createDDL = packet.getFieldValues().get(1);
                    }
                    // 强制覆盖掉内存值
                    tableMetaTSDB.apply(position, schema, createDDL, "first");
                    tableMeta = tableMetaTSDB.find(schema, table);
                } catch (IOException e) {
                    throw new CanalParseException("fetch failed by table meta:" + fullName, e);
                }
修改为：

                // 因为条件变化，可能第一次的tableMeta没取到，需要从db获取一次，并记录到snapshot中
                String fullName = getFullName(schema, table);
                try {
                	String createDDL = null;
                	ResultSetPacket packet = null;
                	
                	try {
						packet = connection.query("show create table " + fullName);
					} catch (Exception e) {
						// Add by lds 20190110 connection可能处于Broken pipe状态，重连之后重新进行查询
						connection.reconnect();
						packet = connection.query("show create table " + fullName);
					}
                    
                    if (packet.getFieldValues().size() > 0) {
                        createDDL = packet.getFieldValues().get(1);
                    }
                    // 强制覆盖掉内存值
                    tableMetaTSDB.apply(position, schema, createDDL, "first");
                    tableMeta = tableMetaTSDB.find(schema, table);
                } catch (IOException e) {
                    throw new CanalParseException("fetch failed by table meta:" + fullName, e);
                }
### 处理依据
以下两处查询Meta信息时是做了数据库连接重做然后再次查询:
1. com.alibaba.otter.canal.parse.inbound.mysql.dbsync.TableMetaCache.java的构造方法中取TableMeta信息失败时做过一次reconnect
2. DatabaseTableMeta.java中的compareTableMetaDbAndMemory方法在从DB取TableMeta信息失败时做过一次reconnect
而"com.alibaba.otter.canal.parse.inbound.mysql.dbsync.TableMetaCache.java 的“public TableMeta getTableMeta(String schema, String table, boolean useCache, EntryPosition position) {”
中没有做相同处理，加上此相同处理之前，异常消失

**Comment by gggyd123** [comment]
该问题会导致触发该异常的那条数据丢失！！！
