### ISSUE TITLE
支持 polardb 么？

### ISSUE THREAD

**Issue by SmileTower** [alibaba/canal#1417]
### environment

* canal version 1.1.2

### Issue Description
2019-01-12 11:10:18.608 [destination = example , address = *.mysql.polardb.rds.aliyuncs.com/*.*.*.*:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> begin to find start position, it will be long time for reset or first position
2019-01-12 11:10:18.609 [destination = example , address = *.mysql.polardb.rds.aliyuncs.com/*.*.*.*:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - prepare to find start position just show master status
2019-01-12 11:10:18.619 [destination = example , address = *.mysql.polardb.rds.aliyuncs.com/*.*.*.*:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address *.mysql.polardb.rds.aliyuncs.com/*.*.*.*:3306 has an error, retrying. caused by
com.alibaba.otter.canal.parse.exception.CanalParseException: command : 'show master status' has an error! pls check. you need (at least one of) the SUPER,REPLICATION CLIENT privilege(s) for this operation
2019-01-12 11:10:18.620 [destination = example , address = *.mysql.polardb.rds.aliyuncs.com/47.102.28.7:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[com.alibaba.otter.canal.parse.exception.CanalParseException: command : 'show master status' has an error! pls check. you need (at least one of) the SUPER,REPLICATION CLIENT privilege(s) for this operation

### Steps to reproduce

show master status  is empty

**Comment by agapple** [comment]
需要porlarDb开启binlog支持

**Comment by zhouluoyang0406** [comment]
@SmileTower 老哥 你成功了么？porlarDb怎么开启binlog。是只能找运维人员么？

**Comment by agapple** [comment]
提阿里云工单申请开通binlog吧

**Comment by alansun2** [comment]
亲测支持。但是可能会遇到账号权限问题。我这边创建了一个 canal 账号就解决了。

**Comment by 497422159** [comment]
polardb监听成功了吗？我今天试了不行，我的账号是最高权限，报的是另外一个问题。


2021-03-22 14:09:14.810 [destination = mycdbPro , address = xxxxxxx:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> begin to find start position, it will be long time for reset or first position
2021-03-22 14:09:14.810 [destination = mycdbPro , address = xxxxxxx:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - prepare to find start position just show master status
2021-03-22 14:09:20.760 [destination = mycdbPro , address = xxxxxxx2:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address xxxxxxx:3306 has an error, retrying. caused by 
com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: ErrorPacket [errorNumber=1146, fieldCount=-1, message=Table 'performance_schema.events_statements_summary_by_digest_supplement' doesn't exist, sqlState=42S02, sqlStateMarker=#]
 with command: show create table `performance_schema`.`accounts`;show create table `performance_schema`.`cond_instances`;show create table `performance_schema`.`events_stages_current`;show create table `performance_schema`.`events_stages_history`;show create table `performance_schema`.`events_stages_history_long`;show create table `performance_schema`.`events_stages_summary_by_account_by_event_name`;show create table `performance_schema`.`events_stages_summary_by_host_by_event_name`;show create table `performance_schema`.`events_stages_summary_by_thread_by_event_name`;show create table `performance_schema`.`events_stages_summary_by_user_by_event_name`;show create table `performance_schema`.`events_stages_summary_global_by_event_name`;show create table `performance_schema`.`events_statements_current`;show create table `performance_schema`.`events_statements_history`;show create table `performance_schema`.`events_statements_history_long`;show create table `performance_schema`.`events_statements_summary_by_account_by_event_name`;show create table `performance_schema`.`events_statements_summary_by_digest`;show create table `performance_schema`.`events_statements_summary_by_digest_supplement`;show create table `performance_schema`.`events_statements_summary_by_host_by_event_name`;show create table `performance_schema`.`events_statements_summary_by_thread_by_event_name`;show create table `performance_schema`.`events_statements_summary_by_user_by_event_name`;show create table `performance_schema`.`events_statements_summary_global_by_event_name`;show create table `performance_schema`.`events_waits_current`;show create table `performance_schema`.`events_waits_history`;show create table `performance_schema`.`events_waits_history_long`;show create table `performance_schema`.`events_waits_summary_by_account_by_event_name`;show create table `performance_schema`.`events_waits_summary_by_host_by_event_name`;show create table `performance_schema`.`events_waits_summary_by_instance`;show create table `performance_schema`.`events_waits_summary_by_thread_by_event_name`;show create table `performance_schema`.`events_waits_summary_by_user_by_event_name`;show create table `performance_schema`.`events_waits_summary_global_by_event_name`;show create table `performance_schema`.`file_instances`;show create table `performance_schema`.`file_summary_by_event_name`;show create table `performance_schema`.`file_summary_by_instance`;show create table `performance_schema`.`host_cache`;show create table `performance_schema`.`hosts`;show create table `performance_schema`.`mutex_instances`;show create table `performance_schema`.`objects_summary_global_by_type`;show create table `performance_schema`.`performance_timers`;show create table `performance_schema`.`rwlock_instances`;show create table `performance_schema`.`session_account_connect_attrs`;show create table `performance_schema`.`session_connect_attrs`;show create table `performance_schema`.`setup_actors`;show create table `performance_schema`.`setup_consumers`;show create table `performance_schema`.`setup_instruments`;show create table `performance_schema`.`setup_objects`;show create table `performance_schema`.`setup_timers`;show create table `performance_schema`.`socket_instances`;show create table `performance_schema`.`socket_summary_by_event_name`;show create table `performance_schema`.`socket_summary_by_instance`;show create table `performance_schema`.`table_io_waits_summary_by_index_usage`;show create table `performance_schema`.`table_io_waits_summary_by_table`;show create table `performance_schema`.`table_lock_waits_summary_by_table`;show create table `performance_schema`.`threads`;show create table `performance_schema`.`users`;
Caused by: java.io.IOException: ErrorPacket [errorNumber=1146, fieldCount=-1, message=Table 'performance_schema.events_statements_summary_by_digest_supplement' doesn't exist, sqlState=42S02, sqlStateMarker=#]
 with command: show create table `performance_schema`.`accounts`;show create table `performance_schema`.`cond_instances`;show create table `performance_schema`.`events_stages_current`;show create table `performance_schema`.`events_stages_history`;show create table `performance_schema`.`events_stages_history_long`;show create table `performance_schema`.`events_stages_summary_by_account_by_event_name`;show create table `performance_schema`.`events_stages_summary_by_host_by_event_name`;show create table `performance_schema`.`events_stages_summary_by_thread_by_event_name`;show create table `performance_schema`.`events_stages_summary_by_user_by_event_name`;show create table `performance_schema`.`events_stages_summary_global_by_event_name`;show create table `performance_schema`.`events_statements_current`;show create table `performance_schema`.`events_statements_history`;show create table `performance_schema`.`events_statements_history_long`;show create table `performance_schema`.`events_statements_summary_by_account_by_event_name`;show create table `performance_schema`.`events_statements_summary_by_digest`;show create table `performance_schema`.`events_statements_summary_by_digest_supplement`;show create table `performance_schema`.`events_statements_summary_by_host_by_event_name`;show create table `performance_schema`.`events_statements_summary_by_thread_by_event_name`;show create table `performance_schema`.`events_statements_summary_by_user_by_event_name`;show create table `performance_schema`.`events_statements_summary_global_by_event_name`;show create table `performance_schema`.`events_waits_current`;show create table `performance_schema`.`events_waits_history`;show create table `performance_schema`.`events_waits_history_long`;show create table `performance_schema`.`events_waits_summary_by_account_by_event_name`;show create table `performance_schema`.`events_waits_summary_by_host_by_event_name`;show create table `performance_schema`.`events_waits_summary_by_instance`;show create table `performance_schema`.`events_waits_summary_by_thread_by_event_name`;show create table `performance_schema`.`events_waits_summary_by_user_by_event_name`;show create table `performance_schema`.`events_waits_summary_global_by_event_name`;show create table `performance_schema`.`file_instances`;show create table `performance_schema`.`file_summary_by_event_name`;show create table `performance_schema`.`file_summary_by_instance`;show create table `performance_schema`.`host_cache`;show create table `performance_schema`.`hosts`;show create table `performance_schema`.`mutex_instances`;show create table `performance_schema`.`objects_summary_global_by_type`;show create table `performance_schema`.`performance_timers`;show create table `performance_schema`.`rwlock_instances`;show create table `performance_schema`.`session_account_connect_attrs`;show create table `performance_schema`.`session_connect_attrs`;show create table `performance_schema`.`setup_actors`;show create table `performance_schema`.`setup_consumers`;show create table `performance_schema`.`setup_instruments`;show create table `performance_schema`.`setup_objects`;show create table `performance_schema`.`setup_timers`;show create table `performance_schema`.`socket_instances`;show create table `performance_schema`.`socket_summary_by_event_name`;show create table `performance_schema`.`socket_summary_by_instance`;show create table `performance_schema`.`table_io_waits_summary_by_index_usage`;show create table `performance_schema`.`table_io_waits_summary_by_table`;show create table `performance_schema`.`table_lock_waits_summary_by_table`;show create table `performance_schema`.`threads`;show create table `performance_schema`.`users`;
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlQueryExecutor.queryMulti(MysqlQueryExecutor.java:109) ~[canal.parse.driver-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.queryMulti(MysqlConnection.java:111) ~[canal.parse-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.dumpTableMeta(DatabaseTableMeta.java:232) ~[canal.parse-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:182) ~[canal.parse-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:137) ~[canal.parse-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:200) ~[canal.parse-1.1.5-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_211]
