### ISSUE TITLE
canal使用dynamicTopic不能自动创建Topic

### ISSUE THREAD

**Issue by flackyang** [alibaba/canal#1421]
### environment

* canal version 1.1.3
* mysql version 5.7.20

### Issue Description
canal 1.1.3最新代码对接RocketMQ, RocketMQ开启自动创建topic（autoCreateTopicEnable=true）
canal配置
~~~
 canal.mq.dynamicTopic=.*\\..* 
~~~
启动后一直报错
~~~
2019-01-14 15:45:50.254 [pool-4-thread-1] ERROR com.alibaba.otter.canal.rocketmq.CanalRocketMQProducer - send flat message to fixed partition error
org.apache.rocketmq.client.exception.MQClientException: No route info for this topic, cs_gs_ds_NEWS_BASICINFO_JX
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendSelectImpl(DefaultMQProducerImpl.java:1031) ~[rocketmq-client-4.3.0.jar:4.3.0]
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:997) ~[rocketmq-client-4.3.0.jar:4.3.0]
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:992) ~[rocketmq-client-4.3.0.jar:4.3.0]
	at org.apache.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:389) ~[rocketmq-client-4.3.0.jar:4.3.0]
	at com.alibaba.otter.canal.rocketmq.CanalRocketMQProducer.send(CanalRocketMQProducer.java:161) [canal.server-1.1.3-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.rocketmq.CanalRocketMQProducer.send(CanalRocketMQProducer.java:72) [canal.server-1.1.3-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.server.CanalMQStarter.worker(CanalMQStarter.java:179) [canal.server-1.1.3-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.server.CanalMQStarter.access$500(CanalMQStarter.java:22) [canal.server-1.1.3-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.server.CanalMQStarter$CanalMQRunnable.run(CanalMQStarter.java:221) [canal.server-1.1.3-SNAPSHOT.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]
~~~

从异常信息后dynamicTopic配置生效了，但是没有自动创建对应的topic

### Expected behaviour
自动创建Topic并投递消息
### Actual behaviour
没有自动创建Topic

**Comment by agapple** [comment]
自动创建是需要MQ本身支持的，canal只是会在send时指定topic的name

**Comment by 362228416** [comment]
@agapple  我也遇到这个问题，我用1.1.2 版本  rocketmq  是会自动创建topic的，升级到 1.1.3 配置动态topic 之后，并不会自动创建，需要手动创建，

rocketmq console 配置显示也是开启的

clusterTopicEnable | true
brokerTopicEnable | true
autoCreateTopicEnable | true

**Comment by 362228416** [comment]
@flackyang  我把canal中的rocketMQ client升级到4.3.2可以自动创建topic了，不过没有报你那个错
你把本地数据清空，重新同步应该ok，这个错应该是 重复 commit 了，你是不是改过代码，检查一下

**Comment by flackyang** [comment]
@362228416 本地数据清空是指清什么数据？
除了升级 rocketMQ client版本外没有改其它代码，从错误看是ack时的顺序有问题
~~~
2019-01-16 16:08:16.815 [pool-4-thread-1] ERROR com.alibaba.otter.canal.server.CanalMQStarter - batchId:236 is not the firstly:1
com.alibaba.otter.canal.meta.exception.CanalMetaManagerException: batchId:236 is not the firstly:1
2019-01-16 16:08:16.815 [pool-4-thread-1] ERROR com.alibaba.otter.canal.server.CanalMQStarter - batchId:236 is not the firstly:1
com.alibaba.otter.canal.meta.exception.CanalMetaManagerException: batchId:236 is not the firstly:1
2019-01-16 16:08:16.932 [pool-4-thread-1] ERROR com.alibaba.otter.canal.server.CanalMQStarter - batchId:237 is not the firstly:1
com.alibaba.otter.canal.meta.exception.CanalMetaManagerException: batchId:237 is not the firstly:1
2019-01-16 16:08:16.932 [pool-4-thread-1] ERROR com.alibaba.otter.canal.server.CanalMQStarter - batchId:237 is not the firstly:1
com.alibaba.otter.canal.meta.exception.CanalMetaManagerException: batchId:237 is not the firstly:1
2019-01-16 16:09:12.067 [pool-4-thread-1] ERROR com.alibaba.otter.canal.server.CanalMQStarter - batchId:238 is not the firstly:1
com.alibaba.otter.canal.meta.exception.CanalMetaManagerException: batchId:238 is not the firstly:1
2019-01-16 16:09:12.067 [pool-4-thread-1] ERROR com.alibaba.otter.canal.server.CanalMQStarter - batchId:238 is not the firstly:1
com.alibaba.otter.canal.meta.exception.CanalMetaManagerException: batchId:238 is not the firstly:1
2019-01-16 16:09:12.234 [pool-4-thread-1] ERROR com.alibaba.otter.canal.server.CanalMQStarter - batchId:239 is not the firstly:1
com.alibaba.otter.canal.meta.exception.CanalMetaManagerException: batchId:239 is not the firstly:1
2019-01-16 16:09:12.234 [pool-4-thread-1] ERROR com.alibaba.otter.canal.server.CanalMQStarter - batchId:239 is not the firstly:1
com.alibaba.otter.canal.meta.exception.CanalMetaManagerException: batchId:239 is not the firstly:1
~~~

**Comment by agapple** [comment]
可以尝试一下1.1.3 alpha-3版本，对于adapter做了蛮多的问题修复
