### ISSUE TITLE
canal异常

### ISSUE THREAD

**Issue by zhang374723384** [alibaba/canal#1428]
2019-01-15 11:24:50.535 [destination = scheduler , address = /10.96.30.66:3306 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - prepare to find start position just last position
2019-01-15 11:24:50.544 [destination = scheduler , address = /10.96.30.66:3306 , EventParser] ERROR com.taobao.tddl.dbsync.binlog.event.RowsLogBuffer - !! Don't know how to handle column type=245 meta=0 (0000)
2019-01-15 11:24:50.545 [destination = scheduler , address = /10.96.30.66:3306 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - ERROR ## parse this event has an error , last position : [EntryPosition[included=false,journalName=Master-mysql-bin.000124,position=105332465,timestamp=1547521803000]]
com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
java.lang.NullPointerException: null
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseOneRow(LogEventConvert.java:545) ~[canal.parse-1.0.19.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseRowsEvent(LogEventConvert.java:358) ~[canal.parse-1.0.19.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:106) ~[canal.parse-1.0.19.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:62) ~[canal.parse-1.0.19.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser.parseAndProfilingIfNecessary(AbstractEventParser.java:323) ~[canal.parse-1.0.19.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3$1.sink(AbstractEventParser.java:176) ~[canal.parse-1.0.19.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:124) [canal.parse-1.0.19.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209) [canal.parse-1.0.19.jar:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]

运行一段时间后canal日志有如上报错，已成功读取了一段时间binlog，是不是要升级版本

**Comment by agapple** [comment]
先升级1.1.3-alpha版本吧，版本差距有点大
