### ISSUE TITLE
远端加载canal.properties文件重新启动时出现bug

### ISSUE THREAD

**Issue by wurongjun** [alibaba/canal#1430]
### environment
最新Master分支代码
* canal version
* mysql version

### Issue Description
远端加载canal.properties文件重新启动时，先调用停止方法，此时zk连接会被回收
https://github.com/alibaba/canal/blob/7e4912cd2e703a1132a9bcc78e3437fa9a6e5276/deployer/src/main/java/com/alibaba/otter/canal/deployer/CanalController.java#L503-L505
调用start方法时，zk没有重新连接而直接使用，导致出现报错
https://github.com/alibaba/canal/blob/7e4912cd2e703a1132a9bcc78e3437fa9a6e5276/deployer/src/main/java/com/alibaba/otter/canal/deployer/CanalController.java#L134-L139
错误日志如下：
2019-01-15 14:21:23.733 [remote-canal-config-scan-0] ERROR com.alibaba.otter.canal.deployer.CanalLauncher - ZkClient already closed!
java.lang.IllegalStateException: ZkClient already closed!
	at org.I0Itec.zkclient.ZkClient.retryUntilConnected(ZkClient.java:988) ~[zkclient-0.10.jar:na]
	at org.I0Itec.zkclient.ZkClient.create(ZkClient.java:528) ~[zkclient-0.10.jar:na]
	at org.I0Itec.zkclient.ZkClient.createPersistent(ZkClient.java:294) ~[zkclient-0.10.jar:na]
	at org.I0Itec.zkclient.ZkClient.createPersistent(ZkClient.java:271) ~[zkclient-0.10.jar:na]
	at com.alibaba.otter.canal.deployer.CanalController.<init>(CanalController.java:137) ~[canal.deployer-1.1.3-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.deployer.CanalStater.start(CanalStater.java:52) ~[canal.deployer-1.1.3-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.deployer.CanalLauncher$1.onChange(CanalLauncher.java:72) [canal.deployer-1.1.3-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.deployer.CanalLauncher$1.onChange(CanalLauncher.java:65) [canal.deployer-1.1.3-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.deployer.monitor.ManagerRemoteConfigMonitor$1.run(ManagerRemoteConfigMonitor.java:286) [canal.deployer-1.1.3-SNAPSHOT.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_172]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_172]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_172]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_172]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_172]

**Comment by agapple** [comment]
可以提交一个PR给我
