### ISSUE TITLE
canal adapter-1.1.3-SNAPSHOT启动失败

### ISSUE THREAD

**Issue by githubkevinyou** [alibaba/canal#1437]
### environment
* canal adapter-1.1.3-SNAPSHOT
* mysql 5.7.24
* kafka 2.11
### Issue Description
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=96m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: UseCMSCompactAtFullCollection is deprecated and will likely be removed in a future release.
Exception in thread "main" java.lang.IllegalArgumentException: Cannot instantiate interface org.springframework.context.ApplicationContextInitializer : org.springframework.boot.autoconfigure.SharedMetadataReaderFactoryContextInitializer
        at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:448)
        at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:427)
        at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:418)
        at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:266)
        at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:247)
        at com.alibaba.otter.canal.adapter.launcher.CanalAdapterApplication.main(CanalAdapterApplication.java:17)
Caused by: java.lang.NoClassDefFoundError: org/springframework/core/KotlinDetector
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:169)
        at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:444)
        ... 5 more
Caused by: java.lang.ClassNotFoundException: org.springframework.core.KotlinDetector
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more

**Comment by agapple** [comment]
可以尝试一下1.1.3 alpha-3版本，adapter的问题有修复
