### ISSUE TITLE
CanalParseException: parse row data failed NullPointerException: null

### ISSUE THREAD

**Issue by githubkevinyou** [alibaba/canal#1451]
### environment

* canal v1.1.3-alpha-2
* mysql 5.7.27
kafka 2.11
### Issue Description
2019-01-17 16:56:45.329 [destination = example , address = /10.1.137.68:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address es-node1/10.1.137.68:3306 has an error, retrying. caused by 
com.alibaba.otter.canal.parse.exception.CanalParseException: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: java.lang.NullPointerException: null
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseOneRow(LogEventConvert.java:711) ~[canal.parse-1.1.3-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseRowsEvent(LogEventConvert.java:533) ~[canal.parse-1.1.3-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$DmlParserStage.onEvent(MysqlMultiStageCoprocessor.java:330) ~[canal.parse-1.1.3-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$DmlParserStage.onEvent(MysqlMultiStageCoprocessor.java:316) ~[canal.parse-1.1.3-SNAPSHOT.jar:na]
        at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) ~[disruptor-3.4.2.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]

### Steps to reproduce
一个实例两个库，本来正常读取binlog的，后来两个库进行多次ddl和dml操作后，一个库正常读取binlog，而另外一个库报错parse row data failed. NullPointerException之类的

**Comment by githubkevinyou** [comment]
可能因为开启tsdb，把example下的h2.mv.db删除，重启canal就能正常解析binlog了
