### ISSUE TITLE
kafka use  partitionHash messagePartition method NullPointerException

### ISSUE THREAD

**Issue by KBCode** [alibaba/canal#1453]
### environment

* canal version 1.1.2
* mysql version 6.5

### Issue Description
java.lang.NullPointerException: null
	at com.alibaba.otter.canal.protocol.FlatMessage.messagePartition(FlatMessage.java:288) ~[classes/:na]
	at com.alibaba.otter.canal.kafka.BangdaoKafkaProducer.send(BangdaoKafkaProducer.java:97) ~[classes/:na]
	at com.alibaba.otter.canal.server.CanalMQStarter.worker(CanalMQStarter.java:148) [classes/:na]
	at com.alibaba.otter.canal.server.CanalMQStarter.access$500(CanalMQStarter.java:21) [classes/:na]
	at com.alibaba.otter.canal.server.CanalMQStarter$CanalMQRunnable.run(CanalMQStarter.java:197) [classes/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_162]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_162]

### Steps to reproduce
kafka use partitionHash

**Comment by agapple** [comment]
尝试一下1.1.3版本
