### ISSUE TITLE
com.alibaba.otter.canal.protocol.exception.CanalClientException: java.net.ConnectException: Connection timed out: connect

### ISSUE THREAD

**Issue by githubkevinyou** [alibaba/canal#1457]
### environment

* canal.deployer-1.1.3-SNAPSHOT
canal.client 1.1.2
zookeeper 3.4.13

### Issue Description
 客户端连接
集群：
 CanalConnector connector = CanalConnectors.newClusterConnector("192.168.1.11:2181", destination, "canal", "canal");
直连：
 CanalConnector connector = CanalConnectors.newSingleConnector(
                new InetSocketAddress("192.168.1.11", 11111), destination, "canal", "canal");
异常：
com.alibaba.otter.canal.protocol.exception.CanalClientException: java.net.ConnectException: Connection timed out: connect
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:189)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.access$000(SimpleCanalConnector.java:50)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector$1.processActiveEnter(SimpleCanalConnector.java:422)
	at com.alibaba.otter.canal.client.impl.running.ClientRunningMonitor.processActiveEnter(ClientRunningMonitor.java:211)
	at com.alibaba.otter.canal.client.impl.running.ClientRunningMonitor.initRunning(ClientRunningMonitor.java:122)
	at com.alibaba.otter.canal.client.impl.running.ClientRunningMonitor.start(ClientRunningMonitor.java:92)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.connect(SimpleCanalConnector.java:106)
	at com.alibaba.otter.canal.client.impl.ClusterCanalConnector.connect(ClusterCanalConnector.java:64)
	at com.gta.canal.redis.AbstractCanalClient.process(AbstractCanalClient.java:112)
	at com.gta.canal.redis.AbstractCanalClient$2.run(AbstractCanalClient.java:77)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection timed out: connect
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:454)
	at sun.nio.ch.Net.connect(Net.java:446)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:148)
	... 10 common frames omitted
是不是版本冲突？

**Comment by agapple** [comment]
com.alibaba.otter.canal.protocol.exception.CanalClientException: java.net.ConnectException: Connection timed out: connect

**Comment by rewerma** [comment]
tcp和mq模式只能用一种

**Comment by chaplinthink** [comment]
@rewerma  开启两个canal实例, servermode一个配置kafka, 一个配置tcp用户client连接可以吗? 我试了下也会报连接超时的问题.
