### ISSUE TITLE
无法连接阿里云rocketmq

### ISSUE THREAD

**Issue by zhouluoyang0406** [alibaba/canal#1459]
RocketMQCanalConnector 中的nameServer填的是什么？
下面两个都不可以
nameServer：http://onsaddr.aliyun.com:8080/rocketmq/nsaddr4client-internal
或者使用 curl http://onsaddr-internal.aliyun.com:8080/rocketmq/nsaddr4client-internal返回的
nameServer：100.XXX.XX.1:8080;100.XXX.XX.2:8080;
这两个都不行

**Comment by zhouluoyang0406** [comment]
两种nameServer均报错 org.apache.rocketmq.client.exception.MQClientException: No route info for this topic, XXX
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendSelectImpl(DefaultMQProducerImpl.java:920)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:891)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:886)
	at org.apache.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:389)

**Comment by godlike110** [comment]
canal 开源版本rocketmq版本没有升级  使用阿里云的ons-client-1.7.9.final 重写rockmq发送逻辑，亲测解决问题
