### ISSUE TITLE
canal  server parse sql error

### ISSUE THREAD

**Issue by hzsbrave** [alibaba/canal#1465]
### environment

* canal version 1.1.2
* mysql version 5.7

### Issue Description
2019-01-23 10:45:52.443 [[scheduler-table-meta-snapshot]] WARN  c.a.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta - parse faield : CREATE TABLE `news` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID标识',
  `title` varchar(550) NOT NULL COMMENT '标题',
  PRIMARY KEY (`id`),
  KEY `title_index` (`title`) USING BTREE,
  FULLTEXT KEY `ft_news_title` (`title`) /*!50100 WITH PARSER `ngram` */ 
) ENGINE=InnoDB AUTO_INCREMENT=1042277 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT=''
com.alibaba.fastsql.sql.parser.ParserException: illegal name, pos 2525, line 5, column 43, token HINT
	at com.alibaba.fastsql.sql.parser.SQLExprParser.name(SQLExprParser.java:1538) ~[fastsql-2.0.0_preview_540.jar:2.0.0_preview_540]
	at com.alibaba.fastsql.sql.dialect.mysql.parser.MySqlExprParser.parseColumn(MySqlExprParser.java:495) ~[fastsql-2.0.0_preview_540.jar:2.0.0_preview_540]
	at com.alibaba.fastsql.sql.dialect.mysql.parser.MySqlCreateTableParser.parseCreateTable(MySqlCreateTableParser.java:361) ~[fastsql-2.0.0_preview_540.jar:2.0.0_preview_540]
	at com.alibaba.fastsql.sql.dialect.mysql.parser.MySqlStatementParser.parseCreate(MySqlStatementParser.java:253) ~[fastsql-2.0.0_preview_540.jar:2.0.0_preview_540]
	at com.alibaba.fastsql.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:223) ~[fastsql-2.0.0_preview_540.jar:2.0.0_preview_540]
	at com.alibaba.fastsql.sql.SQLUtils.parseStatements(SQLUtils.java:498) ~[fastsql-2.0.0_preview_540.jar:2.0.0_preview_540]
	at com.alibaba.fastsql.sql.repository.SchemaRepository.console(SchemaRepository.java:413) ~[fastsql-2.0.0_preview_540.jar:2.0.0_preview_540]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta.apply(MemoryTableMeta.java:73) ~[canal.parse-1.1.1-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.TableMetaCache.parseTableMeta(TableMetaCache.java:101) [canal.parse-1.1.1-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.compareTableMetaDbAndMemory(DatabaseTableMeta.java:311) [canal.parse-1.1.1-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.applySnapshotToDB(DatabaseTableMeta.java:253) [canal.parse-1.1.1-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.access$100(DatabaseTableMeta.java:45) [canal.parse-1.1.1-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta$2.run(DatabaseTableMeta.java:86) [canal.parse-1.1.1-SNAPSHOT.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_191]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]
2019-01-23 10:45:52.444 [[scheduler-table-meta-snapshot]] ERROR c.a.o.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta - scheudle applySnapshotToDB faield
java.lang.NullPointerException: null
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.TableMetaCache.parseTableMeta(TableMetaCache.java:103) ~[canal.parse-1.1.1-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.compareTableMetaDbAndMemory(DatabaseTableMeta.java:311) ~[canal.parse-1.1.1-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.applySnapshotToDB(DatabaseTableMeta.java:253) ~[canal.parse-1.1.1-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.access$100(DatabaseTableMeta.java:45) ~[canal.parse-1.1.1-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta$2.run(DatabaseTableMeta.java:86) ~[canal.parse-1.1.1-SNAPSHOT.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_191]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]

**Comment by hzsbrave** [comment]
使用最新版本的canal还是无法解决改问题，发现fastsql-2.0.0_preview_644.jar包无法解析FULLTEXT KEY ft_news_title (title) /*!50100 WITH PARSER ngram */后面的 ： /*!50100 WITH PARSER ngram */ 中的!50100 WITH PARSER ngram为非法token，进行反编译fastsql-2.0.0_preview_644.jar修改MySqlCreateTableParser.java文件，再编译成class文件，替换fastsql-2.0.0_preview_644.jar的MySqlCreateTableParser.class文件，解决问题

**Comment by agapple** [comment]
1.1.4 当前主干已修复
