### ISSUE TITLE
Canal是否支持azure database for mysql的binlog订阅

### ISSUE THREAD

**Issue by Robinbin** [alibaba/canal#1477]
2019-01-28 11:03:23.988 [destination = example , address = xxxxxx.mysql.database.azure.com/10.10.10.10:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: connect xxxxxx.mysql.database.azure.com/10.10.10.10:3306 failure
Caused by: java.io.IOException: connect xxxxxx.mysql.database.azure.com/10.10.10.10:3306 failure
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:77)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.connect(MysqlConnection.java:88)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.preDump(MysqlEventParser.java:86)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:175)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Error When doing Client Authentication:ErrorPacket [errorNumber=9002, fieldCount=-1, message=The connection string may not be right. Please visit portal for references. , sqlState=28000, sqlStateMarker=#]
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.negotiate(MysqlConnector.java:199)
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:74)
	... 4 more
]

**Comment by agapple** [comment]
message=The connection string may not be right. Please visit portal for references

**Comment by Robinbin** [comment]
Currently Canal can't read the binlog file of Azure database for My SQL

**Comment by zhouluoyang0406** [comment]
@Robinbin  你好 你是怎么的出 canal不能连接 Azure。联系一下我好么。luoyang.zly@alibaba-inc.com 邮箱。万分感谢。

**Comment by agapple** [comment]
最新的1.1.3，解决过azure mysql的登录问题
