### ISSUE TITLE
设置canal服务器端报错:[main] ERROR com.alibaba.druid.pool.DruidDataSource - testWhileIdle is true, validationQuery not set

### ISSUE THREAD

**Issue by LoongLiWang** [alibaba/canal#1488]
### environment

* canal version
    canal.deployer-1.1.2
* mysql version
    5.7.22-log MySQL Community Server (GPL)
### Issue Description
    启动canal服务器时候报错:信息如下
```shell
h resource [example/instance.properties]
2019-01-30 11:31:48.769 [main] ERROR com.alibaba.druid.pool.DruidDataSource - testWhileIdle is true, validationQuery not set
2019-01-30 11:31:48.884 [Druid-ConnectionPool-Create-1363560175] ERROR com.alibaba.druid.pool.DruidDataSource - create connection SQLException, url: jdbc:h2:../conf/example/h2;CACHE_SIZE=1000;MODE=MYSQL;, errorCode 90020, state 90020
org.h2.jdbc.JdbcSQLException: Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.message.DbException.get(DbException.java:168) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:188) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:168) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:100) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.engine.Database.getPageStore(Database.java:2476) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.engine.Database.open(Database.java:697) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.engine.Database.openDatabase(Database.java:276) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.engine.Database.<init>(Database.java:270) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.engine.Engine.openSession(Engine.java:64) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.engine.Engine.openSession(Engine.java:176) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.engine.Engine.createSession(Engine.java:137) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.engine.Engine.createSession(Engine.java:27) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:354) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:100) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.Driver.connect(Driver.java:69) ~[h2-1.4.196.jar:1.4.196]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1513) ~[druid-1.1.9.jar:1.1.9]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1578) ~[druid-1.1.9.jar:1.1.9]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2466) ~[druid-1.1.9.jar:1.1.9]
Caused by: java.lang.IllegalStateException: The file is locked: nio:/usr/local/canal/conf/example/h2.mv.db [1.4.196/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:765) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.mvstore.FileStore.open(FileStore.java:173) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.mvstore.MVStore.<init>(MVStore.java:347) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2930) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:155) ~[h2-1.4.196.jar:1.4.196]
	... 17 common frames omitted
```

### Steps to reproduce
```shell
mysql:
mysql binlog 已经开启，format格式也为row

canal:
conf/canal.properties  仅仅修改了canal.ip 
# head conf/canal.properties 
canal.id = 1
canal.ip = 192.168.31.139
canal.port = 11111
# 

conf/example/instance.properties 修改了position info 和 username/password 信息
# cat conf/example/instance.properties | grep -v "^#"
canal.instance.mysql.slaveId=234

canal.instance.gtidon=false

canal.instance.master.address=127.0.0.1:3306
canal.instance.master.journal.name=log-bin.000001
canal.instance.master.position=2465
canal.instance.master.timestamp=
canal.instance.master.gtid=

canal.instance.rds.accesskey=
canal.instance.rds.secretkey=
canal.instance.rds.instanceId=

canal.instance.tsdb.enable=true


canal.instance.dbUsername=canal
canal.instance.dbPassword=canal
canal.instance.connectionCharset = UTF-8
canal.instance.defaultDatabaseName =test_canal
canal.instance.enableDruid=false

canal.instance.filter.regex=.*\\..*
canal.instance.filter.black.regex=

canal.mq.topic=example
canal.mq.partition=0
# 


```

**Comment by LoongLiWang** [comment]
将这行注释掉就可以了，可是，为什么呢？
```shell
cat conf/canal.properties 
canal.instance.tsdb.spring.xml = classpath:spring/tsdb/h2-tsdb.xml
```

**Comment by agapple** [comment]
java.lang.IllegalStateException: The file is locked: nio:/usr/local/canal/conf/example/h2.mv.db 

是否有多进程启动或者上次异常crash，h2文件没有清理正常

**Comment by LoongLiWang** [comment]
这边经过检查，就是上一次进程启动后，没有关闭引起的，这边已经做了相应的动作，已经ok了,谢谢

**Comment by zhouluoyang0406** [comment]
![image](https://user-images.githubusercontent.com/42863611/53929864-3186cc80-40ca-11e9-981c-9739c5128205.png)
