### ISSUE TITLE
canal可以启动，在mysql中也可也可以通过show processlist看见slave进程，但是实际在主库insert后，canal这边没有接收任何消息

### ISSUE THREAD

**Issue by LoongLiWang** [alibaba/canal#1489]
### environment

* canal version
  canal.deployer-1.1.2
* mysql version
  5.7.22-log MySQL Community Server (GPL)

### Issue Description
```shell
2019-01-30 15:29:56.124 [main] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Loading properties file from class path resource [canal.properties]
2019-01-30 15:29:56.129 [main] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Loading properties file from class path resource [example/instance.properties]
2019-01-30 15:29:56.317 [main] WARN  o.s.beans.GenericTypeAwarePropertyDescriptor - Invalid JavaBean property 'connectionCharset' being accessed! Ambiguous write methods found next to actually used [public void com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.setConnectionCharset(java.lang.String)]: [public void com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.setConnectionCharset(java.nio.charset.Charset)]
2019-01-30 15:29:56.390 [main] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Loading properties file from class path resource [canal.properties]
2019-01-30 15:29:56.393 [main] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Loading properties file from class path resource [example/instance.properties]
2019-01-30 15:29:56.652 [main] ERROR com.alibaba.druid.pool.DruidDataSource - testWhileIdle is true, validationQuery not set
2019-01-30 15:29:56.888 [main] INFO  c.a.otter.canal.instance.spring.CanalInstanceWithSpring - start CannalInstance for 1-example 
2019-01-30 15:29:56.907 [main] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - start successful....
2019-01-30 15:29:57.008 [destination = example , address = /127.0.0.1:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> begin to find start position, it will be long time for reset or first position
2019-01-30 15:29:57.331 [destination = example , address = /127.0.0.1:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - prepare to find start position log-bin.000001:7577:1548832204000
2019-01-30 15:29:58.207 [destination = example , address = /127.0.0.1:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> find start position successfully, EntryPosition[included=false,journalName=log-bin.000001,position=7577,serverId=139,gtid=<null>,timestamp=1548832204000] cost : 1179ms , the next step is binlog dump

```

### Steps to reproduce
```shell
mysql从processlist看，可以看到canal已经连接上了
mysql> show processlist;
+-----+-------+-----------------+------+-------------+------+---------------------------------------------------------------+------------------+
| Id  | User  | Host            | db   | Command     | Time | State                                                         | Info             |
+-----+-------+-----------------+------+-------------+------+---------------------------------------------------------------+------------------+
| 720 | root  | localhost       | xykj | Query       |    0 | starting                                                      | show processlist |
| 721 | canal | localhost:36942 | NULL | Sleep       |  175 |                                                               | NULL             |
| 725 | canal | localhost:36946 | NULL | Binlog Dump |  174 | Master has sent all binlog to slave; waiting for more updates | NULL             |
+-----+-------+-----------------+------+-------------+------+---------------------------------------------------------------+------------------+
3 rows in set (0.00 sec)

mysql> 

conf/canal.properties 修改点为:
# cat canal.properties  | grep canal.ip
canal.ip = 192.168.31.139
# 

conf/example/instance.properties修改的点为:
## mysql serverId , v1.0.26+ will autoGen 
canal.instance.mysql.slaveId=234

# position info
canal.instance.master.address=127.0.0.1:3306
canal.instance.master.journal.name=log-bin.000001
canal.instance.master.position=7923
canal.instance.master.timestamp=
canal.instance.master.gtid=

# username/password
canal.instance.dbUsername=canal
canal.instance.dbPassword=canal
canal.instance.connectionCharset = UTF-8
canal.instance.defaultDatabaseName =canal

conf/canal.properties 完整conf
# cat canal.properties 
#################################################
######### 		common argument		############# 
#################################################
canal.id = 1
canal.ip = 192.168.31.139
canal.port = 11111
canal.metrics.pull.port = 11112
canal.zkServers =
# flush data to zk
canal.zookeeper.flush.period = 1000
canal.withoutNetty = false
# tcp, kafka, RocketMQ
canal.serverMode = tcp
# flush meta cursor/parse position to file
canal.file.data.dir = ${canal.conf.dir}
canal.file.flush.period = 1000
## memory store RingBuffer size, should be Math.pow(2,n)
canal.instance.memory.buffer.size = 16384
## memory store RingBuffer used memory unit size , default 1kb
canal.instance.memory.buffer.memunit = 1024 
## meory store gets mode used MEMSIZE or ITEMSIZE
canal.instance.memory.batch.mode = MEMSIZE
canal.instance.memory.rawEntry = true

## detecing config
canal.instance.detecting.enable = false
#canal.instance.detecting.sql = insert into retl.xdual values(1,now()) on duplicate key update x=now()
canal.instance.detecting.sql = select 1
canal.instance.detecting.interval.time = 3
canal.instance.detecting.retry.threshold = 3
canal.instance.detecting.heartbeatHaEnable = false

# support maximum transaction size, more than the size of the transaction will be cut into multiple transactions delivery
canal.instance.transaction.size =  1024
# mysql fallback connected to new master should fallback times
canal.instance.fallbackIntervalInSeconds = 60

# network config
canal.instance.network.receiveBufferSize = 16384
canal.instance.network.sendBufferSize = 16384
canal.instance.network.soTimeout = 30

# binlog filter config
canal.instance.filter.druid.ddl = true
canal.instance.filter.query.dcl = false
canal.instance.filter.query.dml = false
canal.instance.filter.query.ddl = false
canal.instance.filter.table.error = false
canal.instance.filter.rows = false
canal.instance.filter.transaction.entry = false

# binlog format/image check
canal.instance.binlog.format = ROW,STATEMENT,MIXED 
canal.instance.binlog.image = FULL,MINIMAL,NOBLOB

# binlog ddl isolation
canal.instance.get.ddl.isolation = false

# parallel parser config
canal.instance.parser.parallel = true
## concurrent thread number, default 60% available processors, suggest not to exceed Runtime.getRuntime().availableProcessors()
#canal.instance.parser.parallelThreadSize = 16
## disruptor ringbuffer size, must be power of 2
canal.instance.parser.parallelBufferSize = 256

# table meta tsdb info
canal.instance.tsdb.enable = true
canal.instance.tsdb.dir = ${canal.file.data.dir:../conf}/${canal.instance.destination:}
canal.instance.tsdb.url = jdbc:h2:${canal.instance.tsdb.dir}/h2;CACHE_SIZE=1000;MODE=MYSQL;
canal.instance.tsdb.dbUsername = canal
canal.instance.tsdb.dbPassword = canal
# dump snapshot interval, default 24 hour
canal.instance.tsdb.snapshot.interval = 24
# purge snapshot expire , default 360 hour(15 days)
canal.instance.tsdb.snapshot.expire = 360

# aliyun ak/sk , support rds/mq
canal.aliyun.accesskey =
canal.aliyun.secretkey =

#################################################
######### 		destinations		############# 
#################################################
canal.destinations = example
# conf root dir
canal.conf.dir = ../conf
# auto scan instance dir add/remove and start/stop instance
canal.auto.scan = true
canal.auto.scan.interval = 5

canal.instance.tsdb.spring.xml = classpath:spring/tsdb/h2-tsdb.xml
#canal.instance.tsdb.spring.xml = classpath:spring/tsdb/mysql-tsdb.xml

canal.instance.global.mode = spring
canal.instance.global.lazy = false
#canal.instance.global.manager.address = 127.0.0.1:1099
#canal.instance.global.spring.xml = classpath:spring/memory-instance.xml
canal.instance.global.spring.xml = classpath:spring/file-instance.xml
#canal.instance.global.spring.xml = classpath:spring/default-instance.xml

##################################################
######### 		     MQ 		     #############
##################################################
canal.mq.servers = 127.0.0.1:6667
canal.mq.retries = 0
canal.mq.batchSize = 16384
canal.mq.maxRequestSize = 1048576
canal.mq.lingerMs = 1
canal.mq.bufferMemory = 33554432
canal.mq.canalBatchSize = 50
canal.mq.canalGetTimeout = 100
canal.mq.flatMessage = true
canal.mq.compressionType = none
canal.mq.acks = all
# 

conf/example/instance.properties完整conf
# cat instance.properties 
#################################################
## mysql serverId , v1.0.26+ will autoGen 
canal.instance.mysql.slaveId=234

# enable gtid use true/false
canal.instance.gtidon=false

# position info
canal.instance.master.address=127.0.0.1:3306
canal.instance.master.journal.name=log-bin.000001
canal.instance.master.position=7923
canal.instance.master.timestamp=
canal.instance.master.gtid=

# rds oss binlog
canal.instance.rds.accesskey=
canal.instance.rds.secretkey=
canal.instance.rds.instanceId=

# table meta tsdb info
canal.instance.tsdb.enable=true
#canal.instance.tsdb.url=jdbc:mysql://127.0.0.1:3306/canal_tsdb
#canal.instance.tsdb.dbUsername=canal
#canal.instance.tsdb.dbPassword=canal

#canal.instance.standby.address =
#canal.instance.standby.journal.name =
#canal.instance.standby.position =
#canal.instance.standby.timestamp =
#canal.instance.standby.gtid=

# username/password
canal.instance.dbUsername=canal
canal.instance.dbPassword=canal
canal.instance.connectionCharset = UTF-8
canal.instance.defaultDatabaseName =canal
# enable druid Decrypt database password
canal.instance.enableDruid=false
#canal.instance.pwdPublicKey=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALK4BUxdDltRRE5/zXpVEVPUgunvscYFtEip3pmLlhrWpacX7y7GCMo2/JM6LeHmiiNdH1FWgGCpUfircSwlWKUCAwEAAQ==

# table regex
canal.instance.filter.regex=.*\\..*
# table black regex
canal.instance.filter.black.regex=

# mq config
canal.mq.topic=example
canal.mq.partition=0
# hash partition config
#canal.mq.partitionsNum=3
#canal.mq.partitionHash=mytest.person:id,mytest.role:id
#################################################
# 


```

**Comment by TengjieXue** [comment]
问题找到原因了吗？我也遇到同样问题了

**Comment by LoongLiWang** [comment]
没有，从mysql来看，canal已经连接到mysql了，从processlist可以看出，从canal log来看，也同样显示启动成功,但实际上我在操作我的数据库的时候(insert) , canal log 并没有任何输出，也没有报错

**Comment by TengjieXue** [comment]
你是所有dll操作都没有输出吗？
那可能是你的数据库配置的不是ROW 模式

**Comment by TengjieXue** [comment]
我遇到的问题是大部分数据都能正常的输出，但是会存在个别表的部分记录没有收到

**Comment by Zephery** [comment]
会不会是跟服务器有关系？能粘一下服务器的配置么？

**Comment by LoongLiWang** [comment]
> 会不会是跟服务器有关系？能粘一下服务器的配置么？

```bash
# uname -a
Linux MiWiFi-R3P-srv 2.6.32-642.el6.x86_64 #1 SMP Tue May 10 17:27:01 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

# cat /etc/redhat-release 
CentOS release 6.8 (Final)
```

**Comment by LoongLiWang** [comment]
> 会不会是跟服务器有关系？能粘一下服务器的配置么？

这边将版本回退到canal.deployer-1.1.0 ，mysql环境均为变动，就可以接收消息，不过这边在接收消息的时候报错了:
```bash
2019-01-31 11:05:50.662 [destination = example , address = /127.0.0.1:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address /127.0.0.1:3306 has an error, retrying. caused by 
java.lang.IllegalArgumentException: null
	at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1314) ~[na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1237) ~[na:1.8.0_191]
	at java.util.concurrent.Executors.newFixedThreadPool(Executors.java:151) ~[na:1.8.0_191]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor.start(MysqlMultiStageCoprocessor.java:84) ~[canal.parse-1.1.0.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:238) ~[canal.parse-1.1.0.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]
2019-01-31 11:05:50.663 [destination = example , address = /127.0.0.1:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[java.lang.IllegalArgumentException
	at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1314)
	at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1237)
	at java.util.concurrent.Executors.newFixedThreadPool(Executors.java:151)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor.start(MysqlMultiStageCoprocessor.java:84)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:238)
	at java.lang.Thread.run(Thread.java:748)
]
```

**Comment by mjjian0** [comment]
canal.instance.filter.query.dml = false   这个地方改为 true试下

**Comment by agapple** [comment]
测试一下1.1.3版本

**Comment by chenming666666** [comment]
canal.instance.master.address=127.0.0.1:3306 换成对应的ip:3306试一下

**Comment by agapple** [comment]
at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1314)，这个报错应该是cpu为1导致

cpu为1无法使用的问题，在1.1.3-alpha-3版本里做了修复

**Comment by lijia071421** [comment]
@pdudo 你的问题后来解决没？

**Comment by AndyWangJL** [comment]
canal是真的坑啊，一样的问题，怎么解决呢？卡了几天了

**Comment by lijia071421** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
