### ISSUE TITLE
adapter启动报错 destination:dev should start first

### ISSUE THREAD

**Issue by jianghaibolxy** [alibaba/canal#1525]
### environment

* canal version
1.1.3-SNAPSHOT
* mysql version
5.7
### Issue Description
2019-02-20 09:14:05.210 ERROR 21311 --- [       Thread-4] c.a.o.c.a.l.loader.CanalAdapterWorker    : process error!

com.alibaba.otter.canal.protocol.exception.CanalClientException: failed to subscribe with reason: something goes wrong with channel:[id: 0x0442a430, /10.101.98.159:15482 => /10.101.93.83:11111], exception=com.alibaba.otter.canal.server.exception.CanalServerException: destination:dev should start first

	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.subscribe(SimpleCanalConnector.java:240) ~[canal.client-1.1.3-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.subscribe(SimpleCanalConnector.java:217) ~[canal.client-1.1.3-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.CanalAdapterWorker.process(CanalAdapterWorker.java:84) ~[client-adapter.launcher-1.1.3-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_162]

但是我已经启动了canal instance dev。这是怎么回事呢

**Comment by jianghaibolxy** [comment]
不好意思，自己配置错了
