### ISSUE TITLE
CanalClientException: deserializer failed

### ISSUE THREAD

**Issue by lchb369** [alibaba/canal#1531]
经常出现deserializer failed的错误，canalserver,canaclient版本均为1.1.2,这是什么原因呢。

2019-02-21 15:23:05 | ERROR - main - com.alibaba.otter.CanalClient - connector.rollback batchId==5972
com.alibaba.otter.canal.protocol.exception.CanalClientException: deserializer failed
at com.alibaba.otter.canal.client.CanalMessageDeserializer.deserializer(CanalMessageDeserializer.java:54)
at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.receiveMessages(SimpleCanalConnector.java:322)
at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.getWithoutAck(SimpleCanalConnector.java:314)
at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.getWithoutAck(SimpleCanalConnector.java:286)
at com.alibaba.otter.CanalClient.main(CanalClient.java:135)
Caused by: com.alibaba.otter.canal.protocol.exception.CanalClientException: something goes wrong with reason: something goes wrong with channel:[id: 0x5c108217, /192.168.2.201:48051 => /172.20.0.2:11111], exception=com.alibaba.otter.canal.server.exception.CanalServerException: ack error , clientId:1001 batchId:5972 is not exist , please check

at com.alibaba.otter.canal.client.CanalMessageDeserializer.deserializer(CanalMessageDeserializer.java:46)
... 4 more

**Comment by agapple** [comment]
有canal-server服务端的日志么？

**Comment by agapple** [comment]
ack error , clientId:1001 batchId:5972 is not exist , please check

应该是这个问题，估计server端发生了rollback

**Comment by lchb369** [comment]
应该是有两个客户端进程同时在运行，会出现这个问题，建议多个客户端同时存在时可以给友好一点的提示。

**Comment by anankun** [comment]
有两个客户端同时运行并订阅了同一个服务端，会报这个错误。

**Comment by kitsrc** [comment]
> 有两个客户端同时运行并订阅了同一个服务端，会报这个错误。

如果canal-client只启一个怎么避免单点问题？？？

**Comment by kovow** [comment]
同样的问题，不知道怎么处理，就是多个客户端订阅了同一个服务端，不知道怎么解决，查不到解决办法

**Comment by Millet2020** [comment]
遇到同类问题，谁解决了
com.alibaba.otter.canal.protocol.exception.CanalClientException: deserializer failed

**Comment by gdbd8341** [comment]
batchId==5972  这条message已经正常提交过了，canal-server已经没有5972这条记录，再次提交报”ack error , clientId:1001 batchId:5972 is not exist 同时回滚connector.rollback batchId==5972，所报的该异常CanalClientException: deserializer failed

**Comment by lixocg** [comment]
所以最终怎么解决？

**Comment by tonyiweb** [comment]
保持单线程就可以
方法一：java代码段保证batchId的线程安全，比如用threadlocal变量，或者用同步的方法块来执行
方法二：修改canal.properties
canal.instance.parser.parallel = false
