### ISSUE TITLE
canal binlog解析报错

### ISSUE THREAD

**Issue by timqq** [alibaba/canal#154]
报错日志：
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: java.lang.IllegalArgumentException: limit excceed: 367
	at com.taobao.tddl.dbsync.binlog.LogBuffer.getFullString(LogBuffer.java:1122) ~[canal.parse.dbsync-1.0.21.jar:na]
	at com.taobao.tddl.dbsync.binlog.event.RowsLogBuffer.fetchValue(RowsLogBuffer.java:920) ~[canal.parse.dbsync-1.0.21.jar:na]
	at com.taobao.tddl.dbsync.binlog.event.RowsLogBuffer.nextValue(RowsLogBuffer.java:96) ~[canal.parse.dbsync-1.0.21.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseOneRow(LogEventConvert.java:462) ~[canal.parse-1.0.21.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseRowsEvent(LogEventConvert.java:378) ~[canal.parse-1.0.21.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:109) ~[canal.parse-1.0.21.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:62) ~[canal.parse-1.0.21.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser.parseAndProfilingIfNecessary(AbstractEventParser.java:323) ~[canal.parse-1.0.21.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3$1.sink(AbstractEventParser.java:176) ~[canal.parse-1.0.21.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:121) ~[canal.parse-1.0.21.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209) ~[canal.parse-1.0.21.jar:na]

**Comment by timqq** [comment]
mysql 5.6.27

**Comment by agapple** [comment]
1. 是否可以重现？比如什么样的sql可以造成这样的问题？
2. 是否可以提供binlog文件

**Comment by timqq** [comment]
[root@69_114 mysql]# mysqlbinlog --no-defaults --base64-output=decode-rows -v --start-position=214215706  /data2/logs/mysql/mysql-bin.000105  |more
/*!50530 SET @@SESSION.PSEUDO_SLAVE_MODE=1*/;
/*!40019 SET @@session.max_insert_delayed_threads=0*/;
/*!50003 SET @OLD_COMPLETION_TYPE=@@COMPLETION_TYPE,COMPLETION_TYPE=0*/;
DELIMITER /*!*/;
# at 214215706
# at 214216435
#160324 14:16:33 server id 6915  end_log_pos 214216533 	Table_map: `crm`.`t_product` mapped to number 78
# at 214216533
#160324 14:16:33 server id 6915  end_log_pos 214216647 	Update_rows: table id 78 flags: STMT_END_F
### UPDATE `crm`.`t_product`
### WHERE
###   @1=598342
### SET
###   @3='全车抛光'
###   @4=30000
###   @5=30000
###   @6=38800
###   @7='洗车+去污+抛光'
###   @11='1'
###   @12='9'
###   @15='5'
###   @18='2016-03-24 14:16:33'
###   @19='18699926655'
# at 214216647
# at 214217458
#160324 14:16:33 server id 6915  end_log_pos 214217547 	Table_map: `crm`.`t_sys_log` mapped to number 82
# at 214217547
#160324 14:16:33 server id 6915  end_log_pos 214218065 	Write_rows: table id 82 flags: STMT_END_F
### INSERT INTO `crm`.`t_sys_log`
### SET
###   @1=908095
###   @2='1458800193776'
###   @3='DML日志'
###   @4='1001'
###   @5='修改'
###   @6='modify'
###   @7='商品[全车抛光]'
###   @8='598342'
###   @9=''
###   @10='{"clearAmt":30000,"dataFlag":"","firstCategory":"1","marketAmt":38800,"myself":false,"pageNum":1,"pageSize":10,"product4SVo":{"carTypeName":""},"productDesc":"洗车+去污+抛光","productId":"598342","p
roductName":"全车抛光","productStatus":"5","saleAmt":30000,"secondCategory":"9","storeId":"33813","sysLogList":[],"updateUser":"18699926655"}'
###   @11='操作成功'
###   @12=18
###   @13='2016-03-24 14:16:33'
###   @14='18699926655'
###   @15='2016-03-24 14:16:33'
###   @16='18699926655'


[EntryPosition[included=false,journalName=mysql-bin.000105,position=214215706,timestamp=1458800193000]]
com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: java.lang.IllegalArgumentException: limit excceed: 3332
	at com.taobao.tddl.dbsync.binlog.LogBuffer.getFullString(LogBuffer.java:1122) ~[canal.parse.dbsync-1.0.20.jar:na]
	at com.taobao.tddl.dbsync.binlog.event.RowsLogBuffer.fetchValue(RowsLogBuffer.java:917) ~[canal.parse.dbsync-1.0.20.jar:na]
	at com.taobao.tddl.dbsync.binlog.event.RowsLogBuffer.nextValue(RowsLogBuffer.java:96) ~[canal.parse.dbsync-1.0.20.jar:na]

**Comment by timqq** [comment]
canal 1.0.20

**Comment by timqq** [comment]
my.cnf   binlog-row-image=minimal 改为full 正常了！

**Comment by agapple** [comment]
印象中canal1.0.21才支持minimal模式，提供binlog的原始二进制文件而不是解析后的文本

**Comment by timqq** [comment]
canal1.0.21 canal1.0.22-sanpshot 都不试过 不行！

**Comment by agapple** [comment]
自己做下代码debug，或者提供复现的办法，或者提供原始的binlog二进制文件，不然我也帮不了

**Comment by agapple** [comment]
自己做下代码debug，或者提供复现的办法，或者提供原始的binlog二进制文件，不然我也帮不了

**Comment by timqq** [comment]
2016-03-30 10:55:31.825 [destination = example , address = /127.0.0.1:3306 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - ERROR ## parse this event has an error , last position : [EntryPosition[included=false,journalName=mysql-bin.000052,position=35751033,timestamp=1459305662000]]


com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: java.lang.IllegalArgumentException: limit excceed: 3332
        at com.taobao.tddl.dbsync.binlog.LogBuffer.getFullString(LogBuffer.java:1122)
