### ISSUE TITLE
canal.instance.tsdb.url配置mysql链接信息出现异常

### ISSUE THREAD

**Issue by acuitong** [alibaba/canal#1547]
2019-02-27 16:52:56.067 [Druid-ConnectionPool-Create-1042307502] ERROR com.alibaba.druid.pool.DruidDataSource - create connection SQLException, url: rm-2ze94j331zgn02y07.mysql.rds.aliyuncs.com:3306/canal_tsdb, errorCode 0, state null
2019-02-27 16:20:37.825 [destination = example , address = /192.168.0.29:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - parse events has an error
com.alibaba.otter.canal.parse.exception.CanalParseException: dump address /192.168.0.29:3306 has an error, retrying. 
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: apply failed caused by : Could not get JDBC Connection; nested exception is com.alibaba.druid.pool.DataSourceDisableException
Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is com.alibaba.druid.pool.DataSourceDisableException
	at org.springframework.orm.ibatis.SqlMapClientTemplate.execute(SqlMapClientTemplate.java:198) ~[spring-orm-3.2.18.RELEASE.jar:3.2.18.RELEASE]
	at org.springframework.orm.ibatis.SqlMapClientTemplate.queryForObject(SqlMapClientTemplate.java:271) ~[spring-orm-3.2.18.RELEASE.jar:3.2.18.RELEASE]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.dao.MetaSnapshotDAO.findByTimestamp(MetaSnapshotDAO.java:29) ~[canal.parse-1.1.3-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.buildMemFromSnapshot(DatabaseTableMeta.java:401) ~[canal.parse-1.1.3-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:172) ~[canal.parse-1.1.3-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:106) ~[canal.parse-1.1.3-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:192) ~[canal.parse-1.1.3-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_65]
Caused by: com.alibaba.druid.pool.DataSourceDisableException: null
	at com.alibaba.druid.pool.DruidDataSource.pollLast(DruidDataSource.java:1952) ~[druid-1.1.9.jar:1.1.9]
	at com.alibaba.druid.pool.DruidDataSource.getConnectionInternal(DruidDataSource.java:1456) ~[druid-1.1.9.jar:1.1.9]
	at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1253) ~[druid-1.1.9.jar:1.1.9]
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1233) ~[druid-1.1.9.jar:1.1.9]
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1223) ~[druid-1.1.9.jar:1.1.9]
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:90) ~[druid-1.1.9.jar:1.1.9]
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:111) ~[spring-jdbc-3.2.18.RELEASE.jar:3.2.18.RELEASE]
	at org.springframework.orm.ibatis.SqlMapClientTemplate.execute(SqlMapClientTemplate.java:184) ~[spring-orm-3.2.18.RELEASE.jar:3.2.18.RELEASE]
	... 7 common frames omitted

**Comment by acuitong** [comment]
已解决

**Comment by warrenwx** [comment]
@acuitong  能给我看下你的canal.properties 和instance.properties文件嘛，我部署的HA，发现tsdb工作不正常。

**Comment by haoxuey** [comment]
hello,我也碰到了和您一样的错误,请问您是怎么解决的?不胜感激

**Comment by haoxuey** [comment]
> @acuitong 能给我看下你的canal.properties 和instance.properties文件嘛，我部署的HA，发现tsdb工作不正常。
你好,请问你解决这个问题了吗?我也碰到了这个问题,之前mysql成功了,后来迁到RDS开始报错

**Comment by keithyzk** [comment]
@acuitong   同样的问题，请问是怎么解决的呢？ 感谢~
