### ISSUE TITLE
求助: canal新增的destinations 启动时报错 server_id was not set

### ISSUE THREAD

**Issue by baibingzhi** [alibaba/canal#1555]
之前canal一直正常使用。为了联调新搭了一套环境，在之前的canal中增加了一个destination，zookeeper没有变动。启动时报错。
注：之前的destination仍然正常。

以下是错误信息，麻烦大神帮忙看看什么原因，非常感谢！

2019-03-01 15:08:39.965 [destination = audit_fql , address = /10.1.49.87:58195 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - prepare to find start position just show master status
2019-03-01 15:08:40.846 [destination = audit_fql , address = /10.1.49.87:58195 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - I/O error while reading from client socket
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Misconfigured master - server_id was not set
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102) ~[canal.parse-1.1.1.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.seek(MysqlConnection.java:131) [canal.parse-1.1.1.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findAsPerTimestampInSpecificLogFile(MysqlEventParser.java:731) [canal.parse-1.1.1.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findEndPositionWithMasterIdAndTimestamp(MysqlEventParser.java:386) [canal.parse-1.1.1.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPositionInternal(MysqlEventParser.java:441) [canal.parse-1.1.1.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPosition(MysqlEventParser.java:360) [canal.parse-1.1.1.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:184) [canal.parse-1.1.1.jar:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]
2019-03-01 15:08:40.846 [destination = audit_fql , address = /10.1.49.87:58195 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ERROR ## findAsPerTimestampInSpecificLogFile has an error
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Misconfigured master - server_id was not set
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102) ~[canal.parse-1.1.1.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.seek(MysqlConnection.java:131) ~[canal.parse-1.1.1.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findAsPerTimestampInSpecificLogFile(MysqlEventParser.java:731) [canal.parse-1.1.1.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findEndPositionWithMasterIdAndTimestamp(MysqlEventParser.java:386) [canal.parse-1.1.1.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPositionInternal(MysqlEventParser.java:441) [canal.parse-1.1.1.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPosition(MysqlEventParser.java:360) [canal.parse-1.1.1.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:184) [canal.parse-1.1.1.jar:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]
2019-03-01 15:08:40.847 [destination = audit_fql , address = /10.1.49.87:58195 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address /10.1.49.87:58195 has an error, retrying. caused by
com.alibaba.otter.canal.parse.exception.PositionNotFoundException: can't find start position for audit_fql
2019-03-01 15:08:40.847 [destination = audit_fql , address = /10.1.49.87:58195 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:audit_fql[com.alibaba.otter.canal.parse.exception.PositionNotFoundException: can't find start position for audit_fql

**Comment by agapple** [comment]
errno = 1236, sqlstate = HY000 errmsg = Misconfigured master - server_id was not set
