### ISSUE TITLE
运行 SimpleCanalClientTest.java 报错 ！

### ISSUE THREAD

**Issue by weiwosuoai** [alibaba/canal#1558]
### environment

* canal 1.1.2

### Issue Description

我将 SimpleCanalClientTest.java 以及 AbstractCanalClientTest.java 放在了 otter 工程中，跑了一下测试，报错如下，谁能给个思路，知道为啥报这个错吗？

```
16:04:37.658 [Thread-0] ERROR c.a.o.n.e.s.AbstractCanalClientTest - parse events has an error
java.lang.NoClassDefFoundError: com/google/protobuf/GeneratedMessageV3
	at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_191]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[na:1.8.0_191]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.8.0_191]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468) ~[na:1.8.0_191]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[na:1.8.0_191]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[na:1.8.0_191]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[na:1.8.0_191]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_191]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[na:1.8.0_191]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_191]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[na:1.8.0_191]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_191]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:151) ~[canal.client-1.1.2.jar:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.connect(SimpleCanalConnector.java:113) ~[canal.client-1.1.2.jar:na]
	at com.alibaba.otter.node.etl.selector.AbstractCanalClientTest.process(AbstractCanalClientTest.java:107) ~[test-classes/:na]
	at com.alibaba.otter.node.etl.selector.AbstractCanalClientTest$2.run(AbstractCanalClientTest.java:77) ~[test-classes/:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_191]
Caused by: java.lang.ClassNotFoundException: com.google.protobuf.GeneratedMessageV3
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_191]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_191]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[na:1.8.0_191]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_191]
	... 17 common frames omitted
16:04:37.669 [Thread-1] INFO  c.a.o.n.e.s.AbstractCanalClientTest - ## stop the canal client
16:04:37.671 [Thread-1] INFO  c.a.o.n.e.s.AbstractCanalClientTest - ## canal client is down.

Process finished with exit code 0

```

报错说 `GeneratedMessage `找不到，但是我搜了一下，确实是存在的，也添加了 `protobuf-java` 的依赖。

万分感谢！！

**Comment by weiwosuoai** [comment]
搞定了，将 otter 里面的 protobuf-java 里面的版本改成和 canal 中的 3.6.1 一样，就可以了
