### ISSUE TITLE
Could not find first log file name in binary log index file 

### ISSUE THREAD

**Issue by totmann** [alibaba/canal#156]
报错信息：
`2016-03-25 17:56:48.605 [destination = mysql_56688 , address = /127.0.0.1:56688 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - prepare to find start position /data/mysql_data/data/mysql-bin.000001:4:
2016-03-25 17:56:48.607 [destination = mysql_56688 , address = /127.0.0.1:56688 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - I/O error while reading from client socket
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:95) ~[canal.parse-1.0.21.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:113) [canal.parse-1.0.21.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209) [canal.parse-1.0.21.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
2016-03-25 17:56:48.607 [destination = mysql_56688 , address = /127.0.0.1:56688 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - dump address /127.0.0.1:56688 has an error, retrying. caused by 
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:95) ~[canal.parse-1.0.21.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:113) ~[canal.parse-1.0.21.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209) ~[canal.parse-1.0.21.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
2016-03-25 17:56:48.607 [destination = mysql_56688 , address = /127.0.0.1:56688 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:mysql_56688[java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:95)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:113)
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209)
        at java.lang.Thread.run(Thread.java:745)
`

MySQL: 
5.6.25
canal: 
1.0.21
instance.properties:
canal.instance.mysql.slaveId = 3
canal.instance.master.address = 127.0.0.1:56688
canal.instance.master.journal.name = /data/mysql_data/data/mysql-bin.000001
canal.instance.master.position = 4

首先MySQL配置和文件权限都检查过了，没啥问题，这个是因为bin log目录不在常规目录引起的吗？

**Comment by agapple** [comment]
Could not find first log file name in binary log index file at.  估计手工清理过binlog日志，没重置mysql binlog index信息，google一大把这问题解决方案

**Comment by totmann** [comment]
reset master也不行，另外，如果把不指定binlog位置，instance thread会一直卡在'show master status'

**Comment by agapple** [comment]
canal会自行做重试，清理下canal记录的历史位点信息

**Comment by nickfan** [comment]
如何清理 下canal记录的历史位点信息？ 删除什么文件还是重启zookeeper?

**Comment by agapple** [comment]
删除节点，然后重启instance

**Comment by nickfan** [comment]
otter-manager里node节点的删除链接是文字不可删除，要怎样步骤才能删除呢？

**Comment by jsrgqinbin** [comment]
在同步进度里把Position 状态删除，即可恢复

**Comment by kevinKaiF** [comment]
canal每次将解析过journalname存储到zk上面，第二次parse数据的时候会从zk去拿一次journalname，如果找不到则从master去找first index file。如果数据库管理员手动清理过日志或者磁盘过满自动清理日志都会出现这样问题，解决办法就是删除对应name的节点

**Comment by agapple** [comment]
一般是建议使用mysql命令行进行删除，就会同步修改index文件

**Comment by rovernerd** [comment]
@agapple 你好,我删除了instance的meta.dat,重启canal,还是爆这个错,请问还有别的解决办法吗

**Comment by fqybzhangji** [comment]
> @agapple 你好,我删除了instance的meta.dat,重启canal,还是爆这个错,请问还有别的解决办法吗

先关闭canal  然后再删除 meta.dat 文件  ，操作的顺序要对

**Comment by zhj12388** [comment]
> > @agapple 你好,我删除了instance的meta.dat,重启canal,还是爆这个错,请问还有别的解决办法吗
> 
> 先关闭canal 然后再删除 meta.dat 文件 ，操作的顺序要对

canal 1.1.4 为啥没有meda.dat文件？

**Comment by Lovzi** [comment]
2021-01-19 18:05:39.552 [destination = new_jindi_prism1_company_human_relation_test , address = rm-2ze99co2cx336f809.mysql.rds.aliyuncs.com/10.38.90.210:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - prepare to find start position just last position
 {"identity":{"slaveId":-1,"sourceAddress":{"address":"rm-2ze99co2cx336f809.mysql.rds.aliyuncs.com","port":3306}},"postion":{"gtid":"","included":false,"journalName":"mysql-bin.010857","position":3347,"serverId":2907274915,"timestamp":1611036012000}}
2021-01-19 18:05:39.564 [destination = new_jindi_prism1_company_human_relation_test , address = rm-2ze99co2cx336f809.mysql.rds.aliyuncs.com/10.38.90.210:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> find start position successfully, EntryPosition[included=false,journalName=mysql-bin.010857,position=3347,serverId=2907274915,gtid=,timestamp=1611036012000] cost : 50ms , the next step is binlog dump
2021-01-19 18:05:39.652 [destination = new_jindi_prism1_company_human_relation_test , address = rm-2ze99co2cx336f809.mysql.rds.aliyuncs.com/10.38.90.210:3306 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - I/O error while reading from client socket
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102) ~[canal.parse-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:235) [canal.parse-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:265) [canal.parse-1.1.4.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_271]
2021-01-19 18:05:39.653 [destination = new_jindi_prism1_company_human_relation_test , address = rm-2ze99co2cx336f809.mysql.rds.aliyuncs.com/10.38.90.210:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address rm-2ze99co2cx336f809.mysql.rds.aliyuncs.com/10.38.90.210:3306 has an error, retrying. caused by
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102) ~[canal.parse-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:235) ~[canal.parse-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:265) ~[canal.parse-1.1.4.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_271]
2021-01-19 18:05:39.655 [destination = new_jindi_prism1_company_human_relation_test , address = rm-2ze99co2cx336f809.mysql.rds.aliyuncs.com/10.38.90.210:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:new_jindi_prism1_company_human_relation_test[java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:235)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:265)
	at java.lang.Thread.run(Thread.java:748)
]
我这里好像是找到了这个binlog,但是拉取过程中出现问题，能不能看看是什么为你

**Comment by zDemon** [comment]
> 2021-01-19 18:05:39.552 [destination = new_jindi_prism1_company_human_relation_test , address = rm-2ze99co2cx336f809.mysql.rds.aliyuncs.com/10.38.90.210:3306 , EventParser] WARN c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - prepare to find start position just last position {"identity":{"slaveId":-1,"sourceAddress":{"address":"rm-2ze99co2cx336f809.mysql.rds.aliyuncs.com","port":3306}},"postion":{"gtid":"","included":false,"journalName":"mysql-bin.010857","position":3347,"serverId":2907274915,"timestamp":1611036012000}} 2021-01-19 18:05:39.564 [destination = new_jindi_prism1_company_human_relation_test , address = rm-2ze99co2cx336f809.mysql.rds.aliyuncs.com/10.38.90.210:3306 , EventParser] WARN c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> find start position successfully, EntryPosition[included=false,journalName=mysql-bin.010857,position=3347,serverId=2907274915,gtid=,timestamp=1611036012000] cost : 50ms , the next step is binlog dump 2021-01-19 18:05:39.652 [destination = new_jindi_prism1_company_human_relation_test , address = rm-2ze99co2cx336f809.mysql.rds.aliyuncs.com/10.38.90.210:3306 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - I/O error while reading from client socket java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102) ~[canal.parse-1.1.4.jar:na] at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:235) [canal.parse-1.1.4.jar:na] at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:265) [canal.parse-1.1.4.jar:na] at java.lang.Thread.run(Thread.java:748) [na:1.8.0_271] 2021-01-19 18:05:39.653 [destination = new_jindi_prism1_company_human_relation_test , address = rm-2ze99co2cx336f809.mysql.rds.aliyuncs.com/10.38.90.210:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address rm-2ze99co2cx336f809.mysql.rds.aliyuncs.com/10.38.90.210:3306 has an error, retrying. caused by java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102) ~[canal.parse-1.1.4.jar:na] at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:235) ~[canal.parse-1.1.4.jar:na] at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:265) ~[canal.parse-1.1.4.jar:na] at java.lang.Thread.run(Thread.java:748) [na:1.8.0_271] 2021-01-19 18:05:39.655 [destination = new_jindi_prism1_company_human_relation_test , address = rm-2ze99co2cx336f809.mysql.rds.aliyuncs.com/10.38.90.210:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:new_jindi_prism1_company_human_relation_test[java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102) at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:235) at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:265) at java.lang.Thread.run(Thread.java:748) ] 我这里好像是找到了这个binlog,但是拉取过程中出现问题，能不能看看是什么为你

兄弟，你这个问题解决了吗，我也遇到这个问题

**Comment by szqjige-nb** [comment]
ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - dump address mhb2h-in-pd-financial-02.mysql.rds.aliyuncs.com/10.126.68.132:3306 has an error, retrying. caused by 
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:176)
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:276)
        at java.lang.Thread.run(Thread.java:748)

同样的问题

**Comment by zDemon** [comment]
这应该是mysql里对应的binlog文件已经删除了找不到了，所以报这个错，我在测试环境打开了这个配置canal.auto.reset.latest.pos.mode=true，或者可以尝试删除位点信息重新从最新的位置开始拉

**Comment by szqjige-nb** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/canal"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月3日(星期四) 中午11:02
***@***.***&gt;;
抄送:&nbsp;"Jige@***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/canal] Could not find first log file name in binary log index file  (#156)





 
这应该是mysql里对应的binlog文件已经删除了找不到了，所以报这个错，我在测试环境打开了这个配置canal.auto.reset.latest.pos.mode=true，或者可以尝试删除位点信息重新从最新的位置开始拉

我用版本是4.2.19 使用的是 mater分支手动编译的 版本，理论上应该是没有这个配置，都是otter.properties文件。

**Comment by szqjige-nb** [comment]
> 这应该是mysql里对应的binlog文件已经删除了找不到了，所以报这个错，我在测试环境打开了这个配置canal.auto.reset.latest.pos.mode=true，或者可以尝试删除位点信息重新从最新的位置开始拉




感谢您的回复：
是的master分支编译后的应用 ，版本是otter版本是4.2.19 。配置文件是这样的：

 otter.properties 
# otter node root dir
otter.nodeHome = ${user.dir}/../

## otter node dir
otter.htdocs.dir = ${otter.nodeHome}/htdocs
otter.download.dir = ${otter.nodeHome}/download
otter.extend.dir= ${otter.nodeHome}/extend

## default zookeeper sesstion timeout = 60s
otter.zookeeper.sessionTimeout = 60000

## otter communication payload size (default = 8388608)
otter.communication.payload = 8388608

## otter communication pool size
otter.communication.pool.size = 10

## otter arbitrate & node connect manager config
otter.manager.address = 1*.1*.*.1**:1099
## 
canal.instance.filter.black.regex = mysql\..*

canal.auto.reset.latest.pos.mode=true 

即使配置好你的在otter.properties中间中canal.auto.reset.latest.pos.mode=true

**Comment by szqjige-nb** [comment]
> > @agapple 你好,我删除了instance的meta.dat,重启canal,还是爆这个错,请问还有别的解决办法吗
> 
> 先关闭canal 然后再删除 meta.dat 文件 ，操作的顺序要对

这个位置哪里？怎么没找到

**Comment by baiyinwen** [comment]
> > > @agapple 你好,我删除了instance的meta.dat,重启canal,还是爆这个错,请问还有别的解决办法吗
> > 
> > 
> > 先关闭canal 然后再删除 meta.dat 文件 ，操作的顺序要对
> 
> 这个位置哪里？怎么没找到

在conf/目录下，配置的实例目录下，比如我配置的是 ../canal/uat-example1/meta.dat

**Comment by watler-peng** [comment]
> > > @agapple 你好,我删除了instance的meta.dat,重启canal,还是爆这个错,请问还有别的解决办法吗
> > 
> > 
> > 先关闭canal 然后再删除 meta.dat 文件 ，操作的顺序要对
> 
> 这个位置哪里？怎么没找到

兄弟, 有解决吗

**Comment by baiyinwen** [comment]
> > > > @agapple 你好,我删除了instance的meta.dat,重启canal,还是爆这个错,请问还有别的解决办法吗
> > > 
> > > 
> > > 先关闭canal 然后再删除 meta.dat 文件 ，操作的顺序要对
> > 
> > 
> > 这个位置哪里？怎么没找到
> 
> 在conf/目录下，配置的实例目录下，比如我配置的是 ../canal/conf/uat-example1/meta.dat

先关闭canal，然后删除 meta.dat 文件，再启动cannl，顺序错了不行的

**Comment by watler-peng** [comment]
已解决
instance.properties 文件有指定binlog的配置,重新指定,重启就好了
