### ISSUE TITLE
canal server频繁出现parse row data failed,数据消费异常

### ISSUE THREAD

**Issue by warrenwx** [alibaba/canal#1564]
### environment
centos x86-64
* canal version
canal server 1.1.3
* mysql version
5.6
### Issue Description
```
CREATE TABLE `t_websites_9` (
        `id` bigint(20) NOT NULL AUTO_INCREMENT,
        `eid` char(36) NOT NULL,
        `seq_no` int(11) NOT NULL,
        `web_type` varchar(255) DEFAULT '',
        `web_name` varchar(255) DEFAULT '',
        `web_url` varchar(2000) NOT NULL DEFAULT '',
        `source` varchar(255) DEFAULT '',
        `date` varchar(255) DEFAULT '',
        tags int(11) NULL,
        `row_update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY (`id`),
        KEY `index_eid_on_t_websites` (`eid`),
        KEY `key_row_update_time` (`row_update_time`)
) ENGINE = InnoDB AUTO_INCREMENT = 6963245 CHARSET = utf8 ALGORITHM = INPLACE;

com.alibaba.fastsql.sql.parser.ParserException: syntax error, error in :'CHARSET = utf8 ALGORITHM = INPLACE;
CREATE T, pos 24531, line 632, column 69, token IDENTIFIER ALGORITHM
        at com.alibaba.fastsql.sql.parser.SQLParser.printError(SQLParser.java:363) ~[fastsql-2.0.0_preview_644.jar:2.0.0_preview_644]
        at com.alibaba.fastsql.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:534) ~[fastsql-2.0.0_preview_644.jar:2.0.0_preview_644]
        at com.alibaba.fastsql.sql.SQLUtils.parseStatements(SQLUtils.java:525) ~[fastsql-2.0.0_preview_644.jar:2.0.0_preview_644]
        at com.alibaba.fastsql.sql.repository.SchemaRepository.console(SchemaRepository.java:439) ~[fastsql-2.0.0_preview_644.jar:2.0.0_preview_644]
        at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta.apply(MemoryTableMeta.java:78) ~[canal.parse-1.1.3-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.buildMemFromSnapshot(DatabaseTableMeta.java:419) [canal.parse-1.1.3-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:172) [canal.parse-1.1.3-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:106) [canal.parse-1.1.3-SNAPSHOT.jar:
na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:192) [canal.parse-1.1.3-SNAPSHOT.jar:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
2019-03-05 10:53:43.865 [destination = examplec125 , address = /172.172.48.223:3312 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - --->
 find start position successfully, EntryPosition[included=false,journalName=3306179166-bin.028360,position=318970007,serverId=3306179166,gtid=,timestamp=15517005930
00] cost : 481ms , the next step is binlog dump
2019-03-05 10:53:45.369 [destination = examplec125 , address = /172.172.48.223:3312 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump
 address 172.172.48.223/172.172.48.223:3312 has an error, retrying. caused by
com.alibaba.otter.canal.parse.exception.CanalParseException: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: column size is not match for table:db_enterprise_8.t_enterprise_5,59 vs 58
2019-03-05 10:53:45.371 [destination = examplec125 , address = /172.172.48.223:3312 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - desti
nation:examplec125[com.alibaba.otter.canal.parse.exception.CanalParseException: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: column size is not match for table:db_enterprise_8.t_enterprise_5,59 vs 58
```
### Steps to reproduce
可能与数据库增加字段有关
### Expected behaviour
这种不支持报错如果不支持，是否不要报错，能否跳过；如果支持目前该如何避免
### Actual behaviour
server parse失败一致重试，导致position一直在消费但是没有取到数据。

**Comment by warrenwx** [comment]
另外，这个问题还会导致数据消费变慢
