### ISSUE TITLE
syntax error, expect IDENTIFIER, actual LITERAL_CHARS pos 249, line 1, column 231, token LITERAL_CHARS latin1_swedish_ci

### ISSUE THREAD

**Issue by 362228416** [alibaba/canal#1569]
### environment

* canal version
* mysql version

### Issue Description

2019-03-06 03:54:27.948 [MultiStageCoprocessor-other-example-0] WARN  c.a.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta - parse faield : update aaaa set fsuccessAmount =  NAME_CONST('amount1',69.34810000), fleftCount =  NAME_CONST('count1',0.00000000), fStatus =  NAME_CONST('status1',3), flastUpdatTime =  NAME_CONST('time1',_latin1'2019-03-06 11:54:28' COLLATE 'latin1_swedish_ci'), version = version + 1, fleftfees = fleftfees - @buy_fee where fId =  NAME_CONST('fid1',169103949) AND fStatus <> 4 AND fStatus <> 3
com.alibaba.fastsql.sql.parser.ParserException: syntax error, expect IDENTIFIER, actual LITERAL_CHARS pos 249, line 1, column 231, token LITERAL_CHARS latin1_swedish_ci
        at com.alibaba.fastsql.sql.parser.SQLExprParser.accept(SQLExprParser.java:3053) ~[fastsql-2.0.0_preview_644.jar:2.0.0_preview_644]
        at com.alibaba.fastsql.sql.dialect.mysql.parser.MySqlExprParser.primaryRest(MySqlExprParser.java:243) ~[fastsql-2.0.0_preview_644.jar:2.0.0_preview_644]
        at com.alibaba.fastsql.sql.parser.SQLExprParser.primary(SQLExprParser.java:866) ~[fastsql-2.0.0_preview_644.jar:2.0.0_preview_644]
        at com.alibaba.fastsql.sql.dialect.mysql.parser.MySqlExprParser.primary(MySqlExprParser.java:174) ~[fastsql-2.0.0_preview_644.jar:2.0.0_preview_644]
        at com.alibaba.fastsql.sql.parser.SQLExprParser.expr(SQLExprParser.java:87) ~[fastsql-2.0.0_preview_644.jar:2.0.0_preview_644]
        at com.alibaba.fastsql.sql.parser.SQLExprParser.exprList(SQLExprParser.java:1453) ~[fastsql-2.0.0_preview_644.jar:2.0.0_preview_644]
        at com.alibaba.fastsql.sql.parser.SQLExprParser.methodRest(SQLExprParser.java:1191) ~[fastsql-2.0.0_preview_644.jar:2.0.0_preview_644]
        at com.alibaba.fastsql.sql.parser.SQLExprParser.primaryRest(SQLExprParser.java:1030) ~[fastsql-2.0.0_preview_644.jar:2.0.0_preview_644]
        at com.alibaba.fastsql.sql.dialect.mysql.parser.MySqlExprParser.primaryRest(MySqlExprParser.java:343) ~[fastsql-2.0.0_preview_644.jar:2.0.0_preview_644]
        at com.alibaba.fastsql.sql.parser.SQLExprParser.primary(SQLExprParser.java:866) ~[fastsql-2.0.0_preview_644.jar:2.0.0_preview_644]
        at com.alibaba.fastsql.sql.dialect.mysql.parser.MySqlExprParser.primary(MySqlExprParser.java:174) ~[fastsql-2.0.0_preview_644.jar:2.0.0_preview_644]

**Comment by agapple** [comment]
最新的fastsql版本已经修复
