### ISSUE TITLE
canal adapter 同步数据时候报java.lang.NullPointerException

### ISSUE THREAD

**Issue by TiandeJohn** [alibaba/canal#1574]
### environment

* canal.deployer-1.1.1-SNAPSHOT
* canal.adapter-1.1.3-SNAPSHOT
* mysql 5.7.21

### Issue Description
2019-03-07 14:23:28.021  INFO 14266 --- [           main] c.a.o.c.a.l.loader.CanalAdapterLoader    : Start adapter for canal instance: AFSA2 succeed
2019-03-07 14:23:28.021  INFO 14266 --- [           main] c.a.o.c.a.l.loader.CanalAdapterService   : ## the canal client adapters are running now ......
2019-03-07 14:23:28.021  INFO 14266 --- [       Thread-4] c.a.o.c.a.l.loader.CanalAdapterWorker    : =============> Start to connect destination: AFSA2 <=============
2019-03-07 14:23:28.053  INFO 14266 --- [           main] c.a.o.c.a.l.CanalAdapterApplication      : Started CanalAdapterApplication in 7.31 seconds (JVM running for 7.649)
2019-03-07 14:23:28.085  INFO 14266 --- [       Thread-4] c.a.o.c.a.l.loader.CanalAdapterWorker    : =============> Start to subscribe destination: AFSA2 <=============
2019-03-07 14:23:28.124  INFO 14266 --- [       Thread-4] c.a.o.c.a.l.loader.CanalAdapterWorker    : =============> Subscribe destination: AFSA2 succeed <=============
2019-03-07 14:24:36.289 ERROR 14266 --- [pool-7-thread-1] c.a.o.c.a.l.loader.CanalAdapterWorker    : java.util.concurrent.ExecutionException: java.lang.NullPointerException

java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at com.alibaba.otter.canal.client.adapter.rdb.RdbAdapter.sync(RdbAdapter.java:171) ~[na:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.batchSync(AbstractCanalAdapterWorker.java:197) ~[client-adapter.launcher-1.1.3-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$1(AbstractCanalAdapterWorker.java:61) ~[client-adapter.launcher-1.1.3-SNAPSHOT.jar:na]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_172]
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$2(AbstractCanalAdapterWorker.java:57) ~[client-adapter.launcher-1.1.3-SNAPSHOT.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_172]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_172]
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_172]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_172]
	at com.alibaba.otter.canal.client.adapter.rdb.RdbAdapter.sync(RdbAdapter.java:168) ~[na:na]
	... 8 common frames omitted
Caused by: java.lang.NullPointerException: null
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.pkHash(RdbSyncService.java:444) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.pkHash(RdbSyncService.java:438) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$null$3(RdbSyncService.java:160) ~[na:na]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_172]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$sync$5(RdbSyncService.java:159) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.sync(RdbSyncService.java:98) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.sync(RdbSyncService.java:139) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.rdb.RdbAdapter.lambda$sync$2(RdbAdapter.java:160) ~[na:na]
	... 4 common frames omitted

2019-03-07 14:24:36.289 ERROR 14266 --- [       Thread-4] c.a.o.c.a.l.loader.CanalAdapterWorker    : Outer adapter sync failed!  Error sync but ACK!

### Steps to reproduce
canal 和canal adapter启动成功，在源数据库插入新的数据，log 报上面错误

**Comment by MrYZD** [comment]
hello ，这个问题你解决了吗？ 我遇到了同样问题？ 欢迎大家指教指教。。。谢谢

**Comment by rewerma** [comment]
1.1.1的deployer
1.1.3的adapter？

**Comment by rewerma** [comment]
请使用最新代码构建打包再试一下
