### ISSUE TITLE
docker启动有没有推荐配置(比例)

### ISSUE THREAD

**Issue by zhouluoyang0406** [alibaba/canal#1580]
### environment
* canal version
canal.1.1.0
* mysql version

### Issue Description
使用docker 容器3200M 
canal
-server -Xms2048m -Xmx3072m -Xmn1024m -XX:SurvivorRatio=2 -XX:PermSize=96m -XX:MaxPermSize=256m -Xss256k -XX:-UseAdaptiveSizePolicy -XX:MaxTenuringThreshold=15 -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC

3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address mysql-c594ae87bd6343ec992b746abff8f418-1.c594ae87bd6343ec992b746abff8f418.addon-mysql.v1.runtimes.marathon.l4lb.thisdcos.directory/11.92.194.122:3306 has an error, retrying. caused by
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method) [na:1.8.0_181]
	at java.lang.Thread.start(Thread.java:717) [na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:957) ~[na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1367) ~[na:1.8.0_181]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112) ~[na:1.8.0_181]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor.start(MysqlMultiStageCoprocessor.java:120) ~[canal.parse-1.1.0.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:238) ~[canal.parse-1.1.0.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
2019-03-07 23:21:20.594 [destination = example , address = mysql-c594ae87bd6343ec992b746abff8f418-1.c594ae87bd6343ec992b746abff8f418.addon-mysql.v1.runtimes.marathon.l4lb.thisdcos.directory/11.92.194.122:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[java.lang.OutOfMemoryError: unable to create new native thread
报错

**Comment by zhouluoyang0406** [comment]
4g太大了

**Comment by agapple** [comment]
按照你自己的业务诉求进行调整，默认是要求主机或者虚拟机4GB的内存
