### ISSUE TITLE
启动后有警告，会不会有影响？

### ISSUE THREAD

**Issue by mindops** [alibaba/canal#1595]
### environment

* canal version 1.1.2
* mysql version 5.7.16

### Issue Description
启动后有警告：
```
2019-03-13 11:28:23.391 [destination = saic_cj_test , address = /172.16.203.70:3306 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta - parse faield : REVOKE EXECUTE, SELECT, SHOW VIEW, ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, INDEX, INSERT, REFERENCES, TRIGGER, UPDATE, GRANT OPTION, LOCK TABLES  ON `el\_company`.* FROM 'xx'@'%'
com.alibaba.fastsql.sql.parser.ParserException: TODO : COMMA
	at com.alibaba.fastsql.sql.parser.SQLStatementParser.parsePrivileages(SQLStatementParser.java:1250) ~[fastsql-2.0.0_preview_644.jar:2.0.0_preview_644]
	at com.alibaba.fastsql.sql.parser.SQLStatementParser.parseRevoke(SQLStatementParser.java:1459) ~[fastsql-2.0.0_preview_644.jar:2.0.0_preview_644]
	at com.alibaba.fastsql.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:295) ~[fastsql-2.0.0_preview_644.jar:2.0.0_preview_644]
	at com.alibaba.fastsql.sql.SQLUtils.parseStatements(SQLUtils.java:525) ~[fastsql-2.0.0_preview_644.jar:2.0.0_preview_644]
	at com.alibaba.fastsql.sql.repository.SchemaRepository.console(SchemaRepository.java:439) ~[fastsql-2.0.0_preview_644.jar:2.0.0_preview_644]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta.apply(MemoryTableMeta.java:78) ~[canal.parse-1.1.2.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.applyHistoryOnMemory(DatabaseTableMeta.java:463) [canal.parse-1.1.2.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:174) [canal.parse-1.1.2.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:84) [canal.parse-1.1.2.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:192) [canal.parse-1.1.2.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
```
请问这个警告是什么原因？会不会有影响？

**Comment by agapple** [comment]
不影响，可以忽略
