### ISSUE TITLE
parse row data failed

### ISSUE THREAD

**Issue by zt3862266** [alibaba/canal#161]
按照quick start 的步骤，使用了一下，启动 startup.sh后，观察 example.log 不停地会有如下报错：
2016-04-01 15:01:37.068 [destination = example , address = /10.0.2.40:3550 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[com.alibaba.otter.canal.parse.exception.CanalParseException: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: java.lang.IllegalArgumentException: bad format, x exceed: 1887436800, 999999999
	at com.taobao.tddl.dbsync.binlog.LogBuffer.getDecimal0(LogBuffer.java:1355)
	at com.taobao.tddl.dbsync.binlog.LogBuffer.getDecimal(LogBuffer.java:1265)
	at com.taobao.tddl.dbsync.binlog.event.RowsLogBuffer.fetchValue(RowsLogBuffer.java:339)
	at com.taobao.tddl.dbsync.binlog.event.RowsLogBuffer.nextValue(RowsLogBuffer.java:96)
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseOneRow(LogEventConvert.java:462)

**Comment by agapple** [comment]
canal版本和mysql版本报告一下

**Comment by zt3862266** [comment]
mysql 版本：
/home/rong/mysql/bin/mysql  Ver 14.14 Distrib 5.6.26, for Linux (x86_64) using  EditLine wrapper
canal 就是最新的1.0.21

**Comment by agapple** [comment]
可以下载mysql binlog到本地，然后使用FileLogFetcherTest进行本地解析测试

**Comment by zt3862266** [comment]
好的，我试试看，多谢

**Comment by agapple** [comment]
估计是这个问题：https://github.com/alibaba/canal/issues/119
使用当前master分支build一个再试试

**Comment by yangyao1623** [comment]
这个问题怎么解决呀？我的MySQL版本是5.6.26,

**Comment by agapple** [comment]
类似的问题修复过一次，使用当前master分支，本地打包一个版本测试一下，如有问题请再反馈
