### ISSUE TITLE
canal对接RocketMQ消息过大时报错：org.apache.rocketmq.client.exception.MQClientException: CODE: 13  DESC: the message body size over max value, MAX: 4194304

### ISSUE THREAD

**Issue by flackyang** [alibaba/canal#1617]
### environment

* canal version 1.1.3
* mysql version 5.7.20

### Issue Description
canal上游监控数据库中新闻信息表，下游对接RocketMQ，消息过大时报错
调整 canal.mq.canalBatchSize 参数为1 还是报错
~~~
2019-03-21 11:41:34.581 [pool-8-thread-1] ERROR com.alibaba.otter.canal.rocketmq.CanalRocketMQProducer - send flat message to hashed partition error
org.apache.rocketmq.client.exception.MQClientException: CODE: 13  DESC: the message body size over max value, MAX: 4194304
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
	at org.apache.rocketmq.client.Validators.checkMessage(Validators.java:99) ~[rocketmq-client-4.3.2.jar:4.3.2]
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendSelectImpl(DefaultMQProducerImpl.java:1033) ~[rocketmq-client-4.3.2.jar:4.3.2]
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1021) ~[rocketmq-client-4.3.2.jar:4.3.2]
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1016) ~[rocketmq-client-4.3.2.jar:4.3.2]
	at org.apache.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:389) ~[rocketmq-client-4.3.2.jar:4.3.2]
	at com.alibaba.otter.canal.rocketmq.CanalRocketMQProducer.send(CanalRocketMQProducer.java:194) [canal.server-1.1.3-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.rocketmq.CanalRocketMQProducer.send(CanalRocketMQProducer.java:73) [canal.server-1.1.3-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.server.CanalMQStarter.worker(CanalMQStarter.java:179) [canal.server-1.1.3-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.server.CanalMQStarter.access$500(CanalMQStarter.java:22) [canal.server-1.1.3-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.server.CanalMQStarter$CanalMQRunnable.run(CanalMQStarter.java:221) [canal.server-1.1.3-SNAPSHOT.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]
~~~

**Comment by rewerma** [comment]
server 端 canal.instance.memory.buffer.memunit 和 canal.mq.batchSize调小
adapter 端 canal.conf.batchSize调小
试一下

**Comment by duhenglucky** [comment]
@flackyang canal.instance.memory.buffer.memunit这个参数是不是设置的超过4m？rocketmq消息最大不能超过4m

**Comment by rewerma** [comment]
是不是表里面有大字段

**Comment by rewerma** [comment]
后续可以考虑做成在mq模式下对过大的Message进行拆包

**Comment by flackyang** [comment]
@rewerma @duhenglucky 
解决是因为表中有大字段导致的，另外请问下rocketMQ消息不能超过4M是一个硬性规定吗？ 可以通过修改DefaultMQProducer中配置解决吗？
~~~
public DefaultMQProducer(String producerGroup, RPCHook rpcHook) {
        this.createTopicKey = "TBW102";
        this.defaultTopicQueueNums = 4;
        this.sendMsgTimeout = 3000;
        this.compressMsgBodyOverHowmuch = 4096;
        this.retryTimesWhenSendFailed = 2;
        this.retryTimesWhenSendAsyncFailed = 2;
        this.retryAnotherBrokerWhenNotStoreOK = false;
        this.maxMessageSize = 4194304;
        this.producerGroup = producerGroup;
        this.defaultMQProducerImpl = new DefaultMQProducerImpl(this, rpcHook);
    }
~~~

**Comment by agapple** [comment]
需要MQ服务端的支持

**Comment by ddd-person** [comment]
@flackyang 你是怎么发现是表中有大字段导致的
