### ISSUE TITLE
fastsql 2.0.0_preview_644在解析存储过程ddl报错

### ISSUE THREAD

**Issue by wurongjun** [alibaba/canal#1629]
### environment
最新master代码
* canal version
* mysql version

### Issue Description
源表创建存储过程，canal server报解析异常，猜测是最新fastsql v2.0.0_preview_644版本未做兼容
存储过程用到语句：
`DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK;SET errno = 1;select 'error'; END;`
报错信息：
`Exception in thread "main" com.alibaba.fastsql.sql.parser.ParserException: unkown handle type. pos 12, line 1, column 9, token IDENTIFIER EXIT
	at com.alibaba.fastsql.sql.dialect.mysql.parser.MySqlStatementParser.parseDeclareHandler(MySqlStatementParser.java:6791)
	at com.alibaba.fastsql.sql.dialect.mysql.parser.MySqlStatementParser.parseDeclare(MySqlStatementParser.java:6534)
	at com.alibaba.fastsql.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:319)
	at com.alibaba.fastsql.sql.SQLUtils.parseStatements(SQLUtils.java:525)
	at com.alibaba.fastsql.sql.repository.SchemaRepository.console(SchemaRepository.java:439)
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta.main(MemoryTableMeta.java:60)`

**Comment by agapple** [comment]
存储过程没在parser的支持范畴，目前tablemeta tsdb只针对DDL有效
