### ISSUE TITLE
canal-adapter v1.1.3-alpha-3 版本无法同步数据到es

### ISSUE THREAD

**Issue by wajika** [alibaba/canal#1644]
### environment

* canal version 
* mysql version

### Issue Description
```
canal-deployer 
docker 容器运行在192.168.10.235主机上
mysql在192.168.10.170主机上

启动配置
./run.sh -e canal.instance.master.address=192.168.10.170:3306 \
-e canal.destinations=test \
-e canal.instance.dbUsername=canal \
-e canal.instance.dbPassword=canal \
-e canal.instance.connectionCharset=UTF-8 \
-e canal.instance.tsdb.enable=true \
-e canal.instance.gtidon=false \
-e canal.instance.filter.regex=test

进入容器目录后可以看到test目录存在

canal-adapter配置
server:
  port: 8081
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

canal.conf:
  mode: tcp # kafka rocketMQ
  canalServerHost: 192.168.10.235:11111
#  flatMessage: true
  batchSize: 500
  syncBatchSize: 1000
  retries: 0
  timeout:
  accessKey:
  secretKey:
  srcDataSources:
    defaultDS:
      url: jdbc:mysql://192.168.10.170:3306/test?useUnicode=true
      username: canal
      password: canal
  canalAdapters:
  - instance: test # canal instance Name or mq topic name
    groups:
    - groupId: g1
      outerAdapters:
      - name: es
        hosts: 192.168.10.229:9300
        properties:
          cluster.name: elasticsearch
                                       
dataSourceKey: defaultDS
destination: test
groupId: g1
esMapping:
  _index: mytest
  _type: _doc
  _id: _id
  upsert: true
#  pk: id
  sql: "SELECT a.rowid as _id,a.fpusername,a.funitprice,a.faddressdetail FROM t_groupon_childorder a"
  etlCondition: "where a.c_time>='{0}'"
  commitBatch: 3000

启动adapter后
2019-03-28 16:54:27.319 [Thread-4] INFO  c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - =============> Start to subscribe de==
2019-03-28 16:54:27.374 [Thread-4] INFO  c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - =============> Subscribe destination=

在es中查看 没有看到索引进入

进入canal-deployer目录下修改meta.dat的binlog位置，依然没有索引同步过来
```

**Comment by wajika** [comment]
我换成使用二进制程序
adapter 日志开到debug等级，然后也看出来为什么adapter不同步数据到es中。
```
2019-03-29 11:35:03.595 [main] INFO  org.elasticsearch.plugins.PluginsService - no modules loaded
2019-03-29 11:35:03.596 [main] INFO  org.elasticsearch.plugins.PluginsService - loaded plugin [org.elasticsearch.index.reindex.ReindexPlugin]
2019-03-29 11:35:03.596 [main] INFO  org.elasticsearch.plugins.PluginsService - loaded plugin [org.elasticsearch.join.ParentJoinPlugin]
2019-03-29 11:35:03.596 [main] INFO  org.elasticsearch.plugins.PluginsService - loaded plugin [org.elasticsearch.percolator.PercolatorPlugin]
2019-03-29 11:35:03.596 [main] INFO  org.elasticsearch.plugins.PluginsService - loaded plugin [org.elasticsearch.script.mustache.MustachePlugin]
2019-03-29 11:35:03.596 [main] INFO  org.elasticsearch.plugins.PluginsService - loaded plugin [org.elasticsearch.transport.Netty4Plugin]
2019-03-29 11:35:03.636 [main] DEBUG org.elasticsearch.threadpool.ThreadPool - created thread pool: name [force_merge], size [1], queue size [unbounded]
2019-03-29 11:35:03.637 [main] DEBUG org.elasticsearch.threadpool.ThreadPool - created thread pool: name [fetch_shard_started], core [1], max [8], keep alive [5m]
2019-03-29 11:35:03.637 [main] DEBUG org.elasticsearch.threadpool.ThreadPool - created thread pool: name [listener], size [2], queue size [unbounded]
2019-03-29 11:35:03.640 [main] DEBUG org.elasticsearch.threadpool.ThreadPool - created thread pool: name [index], size [4], queue size [200]
2019-03-29 11:35:03.640 [main] DEBUG org.elasticsearch.threadpool.ThreadPool - created thread pool: name [refresh], core [1], max [2], keep alive [5m]
2019-03-29 11:35:03.640 [main] DEBUG org.elasticsearch.threadpool.ThreadPool - created thread pool: name [generic], core [4], max [128], keep alive [30s]
2019-03-29 11:35:03.640 [main] DEBUG org.elasticsearch.threadpool.ThreadPool - created thread pool: name [warmer], core [1], max [2], keep alive [5m]
2019-03-29 11:35:03.642 [main] DEBUG o.e.c.util.concurrent.QueueResizingEsThreadPoolExecutor - thread pool [_client_/search] will adjust queue by [50] when determining automatic queue size
2019-03-29 11:35:03.642 [main] DEBUG org.elasticsearch.threadpool.ThreadPool - created thread pool: name [search], size [7], queue size [1k]
2019-03-29 11:35:03.642 [main] DEBUG org.elasticsearch.threadpool.ThreadPool - created thread pool: name [flush], core [1], max [2], keep alive [5m]
2019-03-29 11:35:03.642 [main] DEBUG org.elasticsearch.threadpool.ThreadPool - created thread pool: name [fetch_shard_store], core [1], max [8], keep alive [5m]
2019-03-29 11:35:03.643 [main] DEBUG org.elasticsearch.threadpool.ThreadPool - created thread pool: name [management], core [1], max [5], keep alive [5m]
2019-03-29 11:35:03.643 [main] DEBUG org.elasticsearch.threadpool.ThreadPool - created thread pool: name [get], size [4], queue size [1k]
2019-03-29 11:35:03.643 [main] DEBUG org.elasticsearch.threadpool.ThreadPool - created thread pool: name [bulk], size [4], queue size [200]
2019-03-29 11:35:03.643 [main] DEBUG org.elasticsearch.threadpool.ThreadPool - created thread pool: name [snapshot], core [1], max [2], keep alive [5m]
2019-03-29 11:35:03.676 [main] DEBUG io.netty.util.internal.PlatformDependent0 - -Dio.netty.noUnsafe: true
2019-03-29 11:35:03.676 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe: unavailable (io.netty.noUnsafe)
2019-03-29 11:35:03.677 [main] DEBUG io.netty.util.internal.PlatformDependent0 - Java version: 8
2019-03-29 11:35:03.677 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): unavailable
2019-03-29 11:35:03.677 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
2019-03-29 11:35:03.677 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
2019-03-29 11:35:03.678 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: true
2019-03-29 11:35:03.678 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.maxDirectMemory: -1 bytes
2019-03-29 11:35:03.678 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
2019-03-29 11:35:04.392 [main] DEBUG o.e.client.transport.TransportClientNodesService - node_sampler_interval[5s]
2019-03-29 11:35:04.396 [main-SendThread(192.168.10.245:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Got ping response for sessionid: 0x1000008e1b00012 after 0ms
2019-03-29 11:35:04.412 [main] DEBUG io.netty.channel.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 8
2019-03-29 11:35:04.429 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: true
2019-03-29 11:35:04.430 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
2019-03-29 11:35:04.435 [main] DEBUG io.netty.util.internal.PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: unavailable
2019-03-29 11:35:04.476 [main] DEBUG o.e.client.transport.TransportClientNodesService - adding address [{#transport#-1}{PhQlyOjiT0i-JfUyQkcjtg}{192.168.10.229}{192.168.10.229:9300}]
2019-03-29 11:35:04.486 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.processId: 19267 (auto-detected)
2019-03-29 11:35:04.488 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv4Stack: true
2019-03-29 11:35:04.488 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv6Addresses: false
2019-03-29 11:35:04.489 [main] DEBUG io.netty.util.NetUtil - Loopback interface: lo (lo, 127.0.0.1)
2019-03-29 11:35:04.490 [main] DEBUG io.netty.util.NetUtil - /proc/sys/net/core/somaxconn: 128
2019-03-29 11:35:04.491 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.machineId: 00:0c:29:ff:fe:71:9d:8f (auto-detected)
2019-03-29 11:35:04.495 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
2019-03-29 11:35:04.495 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
2019-03-29 11:35:04.502 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.level: simple
2019-03-29 11:35:04.502 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.maxRecords: 4
2019-03-29 11:35:04.502 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.maxSampledRecords: 40
2019-03-29 11:35:04.519 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numHeapArenas: 8
2019-03-29 11:35:04.519 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numDirectArenas: 8
2019-03-29 11:35:04.519 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.pageSize: 8192
2019-03-29 11:35:04.519 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxOrder: 11
2019-03-29 11:35:04.519 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.chunkSize: 16777216
2019-03-29 11:35:04.519 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.tinyCacheSize: 512
2019-03-29 11:35:04.519 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.smallCacheSize: 256
2019-03-29 11:35:04.520 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.normalCacheSize: 64
2019-03-29 11:35:04.520 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
2019-03-29 11:35:04.520 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimInterval: 8192
2019-03-29 11:35:04.520 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.useCacheForAllThreads: true
2019-03-29 11:35:04.527 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: pooled
2019-03-29 11:35:04.527 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 65536
2019-03-29 11:35:04.527 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
2019-03-29 11:35:04.580 [main] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.bytebuf.checkAccessible: true
2019-03-29 11:35:04.581 [main] DEBUG io.netty.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@589fb74d
2019-03-29 11:35:04.586 [main] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxCapacityPerThread: disabled
2019-03-29 11:35:04.587 [main] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxSharedCapacityFactor: disabled
2019-03-29 11:35:04.587 [main] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.linkCapacity: disabled
2019-03-29 11:35:04.587 [main] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.ratio: disabled
2019-03-29 11:35:04.676 [main] DEBUG org.elasticsearch.transport.netty4.Netty4Transport - connected to node [{Zy2c00L}{Zy2c00LMTZqZSUcp8QBPJw}{MIK33XfqT5S8_KkOS-YUWg}{192.168.10.229}{192.168.10.229:9300}{ml.machine_memory=6088138752, ml.max_open_jobs=20, xpack.installed=true, ml.enabled=true}]
2019-03-29 11:35:04.686 [main] INFO  c.a.o.canal.adapter.launcher.loader.CanalAdapterLoader - Load canal adapter: es succeed
2019-03-29 11:35:04.691 [main] DEBUG o.s.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'syncSwitch'
2019-03-29 11:35:04.711 [main] INFO  c.a.o.canal.adapter.launcher.loader.CanalAdapterLoader - Start adapter for canal-client mq topic: wenzhou-g1 succeed
2019-03-29 11:35:04.711 [main] INFO  c.a.o.canal.adapter.launcher.loader.CanalAdapterService - ## the canal client adapters are running now ......
2019-03-29 11:35:04.712 [main] DEBUG o.s.beans.factory.support.DefaultListableBeanFactory - Finished creating instance of bean 'scopedTarget.canalAdapterService'
2019-03-29 11:35:04.726 [Thread-4] INFO  c.a.o.c.adapter.launcher.loader.CanalAdapterKafkaWorker - =============> Start to connect topic: wenzhou <=============
2019-03-29 11:35:04.733 [main] DEBUG o.s.b.a.logging.ConditionEvaluationReportLoggingListener - 
```

**Comment by agapple** [comment]
先使用adapter logger方式测试一下binlog是否能正常在产生和消费

**Comment by wajika** [comment]
> 先使用adapter logger方式测试一下binlog是否能正常在产生和消费

2019-04-01 09:26:26.432 [Thread-3] INFO  c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - =============> Start to connect destination: kafka <=============
2019-04-01 09:26:26.432 [Thread-3] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - process error!
com.alibaba.otter.canal.protocol.exception.CanalClientException: java.net.ConnectException: Connection refused
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:189)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.connect(SimpleCanalConnector.java:113)
	at com.alibaba.otter.canal.adapter.launcher.loader.CanalAdapterWorker.process(CanalAdapterWorker.java:88)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:454)
	at sun.nio.ch.Net.connect(Net.java:446)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:148)
	... 3 common frames omitted
这个错误代表的是什么意思？ 能够明确一点吗？

**Comment by wajika** [comment]
Logging下 adapter可以打印SQL的内容，另外一个问题为什么 canal-deployer设置为kafka模式后 11111端口就不会开放了？

```
[root@localhost deployer1.3]# cat conf/canal.properties 
#################################################
######### 		common argument		############# 
#################################################
#canal.manager.jdbc.url=jdbc:mysql://127.0.0.1:3306/canal_manager?useUnicode=true&characterEncoding=UTF-8
#canal.manager.jdbc.username=root
#canal.manager.jdbc.password=121212
canal.id = 1
canal.ip =
canal.port = 11111
canal.metrics.pull.port = 11112
#canal.zkServers = 192.168.10.245:2181
# flush data to zk
canal.zookeeper.flush.period = 1000
canal.withoutNetty = false
# tcp, kafka, RocketMQ
canal.serverMode = tcp
# flush meta cursor/parse position to file
canal.file.data.dir = ${canal.conf.dir}
canal.file.flush.period = 1000
## memory store RingBuffer size, should be Math.pow(2,n)
canal.instance.memory.buffer.size = 16384
## memory store RingBuffer used memory unit size , default 1kb
canal.instance.memory.buffer.memunit = 1024 
## meory store gets mode used MEMSIZE or ITEMSIZE
canal.instance.memory.batch.mode = MEMSIZE
canal.instance.memory.rawEntry = true

## detecing config
canal.instance.detecting.enable = false
#canal.instance.detecting.sql = insert into retl.xdual values(1,now()) on duplicate key update x=now()
canal.instance.detecting.sql = select 1
canal.instance.detecting.interval.time = 3
canal.instance.detecting.retry.threshold = 3
canal.instance.detecting.heartbeatHaEnable = false

# support maximum transaction size, more than the size of the transaction will be cut into multiple transactions delivery
canal.instance.transaction.size =  1024
# mysql fallback connected to new master should fallback times
canal.instance.fallbackIntervalInSeconds = 60

# network config
canal.instance.network.receiveBufferSize = 16384
canal.instance.network.sendBufferSize = 16384
canal.instance.network.soTimeout = 30

# binlog filter config
canal.instance.filter.druid.ddl = true
canal.instance.filter.query.dcl = false
canal.instance.filter.query.dml = false
canal.instance.filter.query.ddl = false
canal.instance.filter.table.error = false
canal.instance.filter.rows = false
canal.instance.filter.transaction.entry = false

# binlog format/image check
canal.instance.binlog.format = ROW,STATEMENT,MIXED 
canal.instance.binlog.image = FULL,MINIMAL,NOBLOB

# binlog ddl isolation
canal.instance.get.ddl.isolation = false

# parallel parser config
canal.instance.parser.parallel = true
## concurrent thread number, default 60% available processors, suggest not to exceed Runtime.getRuntime().availableProcessors()
#canal.instance.parser.parallelThreadSize = 16
## disruptor ringbuffer size, must be power of 2
canal.instance.parser.parallelBufferSize = 256

# table meta tsdb info
canal.instance.tsdb.enable = true
canal.instance.tsdb.dir = ${canal.file.data.dir:../conf}/${canal.instance.destination:}
canal.instance.tsdb.url = jdbc:h2:${canal.instance.tsdb.dir}/h2;CACHE_SIZE=1000;MODE=MYSQL;
canal.instance.tsdb.dbUsername = canal
canal.instance.tsdb.dbPassword = canal
# dump snapshot interval, default 24 hour
canal.instance.tsdb.snapshot.interval = 24
# purge snapshot expire , default 360 hour(15 days)
canal.instance.tsdb.snapshot.expire = 360

# aliyun ak/sk , support rds/mq
canal.aliyun.accessKey =
canal.aliyun.secretKey =

#################################################
######### 		destinations		############# 
#################################################
canal.destinations = kafka
# conf root dir
canal.conf.dir = ../conf
# auto scan instance dir add/remove and start/stop instance
canal.auto.scan = true
canal.auto.scan.interval = 5

canal.instance.tsdb.spring.xml = classpath:spring/tsdb/h2-tsdb.xml
#canal.instance.tsdb.spring.xml = classpath:spring/tsdb/mysql-tsdb.xml

canal.instance.global.mode = spring
canal.instance.global.lazy = false
#canal.instance.global.manager.address = 127.0.0.1:1099
#canal.instance.global.spring.xml = classpath:spring/memory-instance.xml
canal.instance.global.spring.xml = classpath:spring/file-instance.xml
#canal.instance.global.spring.xml = classpath:spring/default-instance.xml

##################################################
######### 		     MQ 		     #############
##################################################
canal.mq.servers = 192.168.10.245:9092
canal.mq.retries = 0
canal.mq.batchSize = 16384
canal.mq.maxRequestSize = 1048576
canal.mq.lingerMs = 1
canal.mq.bufferMemory = 33554432
canal.mq.canalBatchSize = 50
canal.mq.canalGetTimeout = 100
canal.mq.flatMessage = true
canal.mq.compressionType = none
canal.mq.acks = all
# use transaction for kafka flatMessage batch produce
canal.mq.transaction = false
#canal.mq.properties. =

```

```

[root@localhost deployer1.3]# cat conf/kafka/instance.properties 
#################################################
## mysql serverId , v1.0.26+ will autoGen
# canal.instance.mysql.slaveId=0

# enable gtid use true/false
canal.instance.gtidon=false

# position info
canal.instance.master.address=192.168.10.100:3306
canal.instance.master.journal.name=
canal.instance.master.position=
canal.instance.master.timestamp=
canal.instance.master.gtid=

# rds oss binlog
canal.instance.rds.accesskey=
canal.instance.rds.secretkey=
canal.instance.rds.instanceId=

# table meta tsdb info
canal.instance.tsdb.enable=true
#canal.instance.tsdb.url=jdbc:mysql://127.0.0.1:3306/canal_tsdb
#canal.instance.tsdb.dbUsername=canal
#canal.instance.tsdb.dbPassword=canal

#canal.instance.standby.address =
#canal.instance.standby.journal.name =
#canal.instance.standby.position =
#canal.instance.standby.timestamp =
#canal.instance.standby.gtid=

# username/password
canal.instance.dbUsername=canal
canal.instance.dbPassword=canal
canal.instance.connectionCharset = UTF-8
canal.instance.defaultDatabaseName =
# enable druid Decrypt database password
canal.instance.enableDruid=false
#canal.instance.pwdPublicKey=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALK4BUxdDltRRE5/zXpVEVPUgunvscYFtEip3pmLlhrWpacX7y7GCMo2/JM6LeHmiiNdH1FWgGCpUfircSwlWKUCAwEAAQ==

# table regex
canal.instance.filter.regex=
# table black regex
canal.instance.filter.black.regex=

# mq config
canal.mq.topic=wenzhou
# dynamic topic route by schema or table regex
#canal.mq.dynamicTopic=mytest1.user,mytest2\\..*,.*\\..*
canal.mq.partition=0
# hash partition config
#canal.mq.partitionsNum=4
#canal.mq.partitionHash=test.table:id^name,.*\\..*
#################################################

```

```
[root@localhost adapter1.3]# cat conf/application.yml 
server:
  port: 8081
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

canal.conf:
  mode: tcp # kafka rocketMQ
  canalServerHost: 192.168.10.238:11111
# zookeeperHosts: 192.168.10.245:2181
#  mqServers: 192.168.10.245:9092
#  flatMessage: true
  batchSize: 50
  syncBatchSize: 1000
  retries: 0
  timeout: 
  accessKey:
  secretKey:
  srcDataSources:
    defaultDS:
      url: jdbc:mysql://192.168.10.100:3306/xxx?useUnicode=true
      username: canal
      password: canal
  canalAdapters:
  - instance: kafka # canal instance Name or mq topic name
    groups:
    - groupId: g1
      outerAdapters:
#      - name: logger
      - name: es
        hosts: 192.168.10.229:9300
        properties:
          cluster.name: elasticsearch

```


```
[root@localhost adapter1.3]# cat conf/es/mytest.yml 
dataSourceKey: defaultDS
destination: kafka
groupId: g1
esMapping:
  _index: mytest
  _type: _doc
  _id: _id
  upsert: true
#  pk: id
  sql: "SELECT a.rowid as _id,a.fpusername,a.funitprice,a.faddressdetail FROM t_groupon_childorder a"
  etlCondition: "where a.c_time>='{0}'"
  commitBatch: 3000
```

**Comment by agapple** [comment]
11111端口只在tcp模式下开启

**Comment by wajika** [comment]
> 11111端口只在tcp模式下开启
@agapple 
deployer开了tcp模式
adapter也开了tcp模式，输出到es

日志开启DEBUG模式
deployer的日志内容是
```
2019-04-02 10:55:17.116 [New I/O server worker #1-1] INFO  c.a.otter.canal.server.netty.handler.SessionHandler - message receives in session handler...
2019-04-02 10:55:17.116 [New I/O server worker #1-1] INFO  c.a.otter.canal.server.netty.handler.SessionHandler - message receives in session handler...
2019-04-02 10:55:17.116 [New I/O server worker #1-1] INFO  c.a.otter.canal.server.embedded.CanalServerWithEmbedded - ack successfully, clientId:1001 batchId:2883 position:PositionRange[start=LogPosition[identity=LogIdentity[sourceAddress=192.168.23.170/192.168.23.170:25022,slaveId=-1],postion=EntryPosition[included=false,journalName=mysqld-bin.000005,position=409854792,serverId=1,gtid=,timestamp=1547178458000]],ack=LogPosition[identity=LogIdentity[sourceAddress=192.168.23.170/192.168.23.170:25022,slaveId=-1],postion=EntryPosition[included=false,journalName=mysqld-bin.000005,position=409904765,serverId=1,gtid=,timestamp=1547178465000]],end=LogPosition[identity=LogIdentity[sourceAddress=192.168.23.170/192.168.23.170:25022,slaveId=-1],postion=EntryPosition[included=false,journalName=mysqld-bin.000005,position=409904856,serverId=1,gtid=,timestamp=1547178465000]]]
2019-04-02 10:55:17.117 [New I/O server worker #1-1] INFO  c.a.otter.canal.server.netty.handler.SessionHandler - message receives in session handler...
2019-04-02 10:55:17.117 [New I/O server worker #1-1] INFO  c.a.otter.canal.server.netty.handler.SessionHandler - message receives in session handler...
2019-04-02 10:55:17.117 [New I/O server worker #1-1] INFO  c.a.otter.canal.server.embedded.CanalServerWithEmbedded - getWithoutAck successfully, clientId:1001 batchSize:50  real size is 160 and result is [batchId:2884 , position:PositionRange[start=LogPosition[identity=LogIdentity[sourceAddress=192.168.23.170/192.168.23.170:25022,slaveId=-1],postion=EntryPosition[included=false,journalName=mysqld-bin.000005,position=409905103,serverId=1,gtid=,timestamp=1547178465000]],ack=LogPosition[identity=LogIdentity[sourceAddress=192.168.23.170/192.168.23.170:25022,slaveId=-1],postion=EntryPosition[included=false,journalName=mysqld-bin.000005,position=409955502,serverId=1,gtid=,timestamp=1547178472000]],end=LogPosition[identity=LogIdentity[sourceAddress=192.168.23.170/192.168.23.170:25022,slaveId=-1],postion=EntryPosition[included=false,journalName=mysqld-bin.000005,position=409955502,serverId=1,gtid=,timestamp=1547178472000]]]]

```


adapter的日志内容是
```
2019-04-02 10:54:43.938 [Thread-4] DEBUG c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - destination: kafka batchId: 2082 elapsed time: 0 ms
2019-04-02 10:54:43.979 [Thread-4] DEBUG c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - destination: kafka batchId: 2083 batchSize: 161 
2019-04-02 10:54:43.980 [pool-2-thread-1] DEBUG c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - com.alibaba.otter.canal.client.adapter.es.ESAdapter elapsed time: 0
2019-04-02 10:54:43.980 [Thread-4] DEBUG c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - destination: kafka batchId: 2083 elapsed time: 0 ms
2019-04-02 10:54:44.022 [Thread-4] DEBUG c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - destination: kafka batchId: 2084 batchSize: 161 
2019-04-02 10:54:44.022 [pool-2-thread-1] DEBUG c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - com.alibaba.otter.canal.client.adapter.es.ESAdapter elapsed time: 0

```

但是es中还是没有收到内容，也没有看到有报错什么的。

**Comment by wajika** [comment]
我一直找不到数据同步的问题，为什么就是无法输出到es？

**Comment by wajika** [comment]
单单搞这问题都搞了好几周了，兄弟你们这个工具怎么这么麻烦啊

**Comment by cn-suibin** [comment]
V1.1.3 对应的JAVA-ES驱动是支持elasticsearch-6.2.3版本。
elasticsearch5.XXX最新版本默认不支持。
