### ISSUE TITLE
canal.mq.partitionsNum=3  最大值只能设置3 ，超过3就会报错

### ISSUE THREAD

**Issue by Bruce2jiang** [alibaba/canal#1655]
canal.mq.partitionsNum=3  最大值只能设置3 ，超过3就会报错

**Comment by agapple** [comment]
具体报错是啥？MQ层面自己的约束？

**Comment by Bruce2jiang** [comment]
2019-04-03 17:21:56.453 [pool-14-thread-4] ERROR com.alibaba.otter.canal.kafka.CanalKafkaProducer - Invalid partition given with record: 3 is not in the range [0...3).
org.apache.kafka.common.KafkaException: Invalid partition given with record: 3 is not in the range [0...3).
	at org.apache.kafka.clients.producer.KafkaProducer.waitOnMetadata(KafkaProducer.java:920) ~[kafka-clients-1.1.1.jar:na]
	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:794) ~[kafka-clients-1.1.1.jar:na]
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:784) ~[kafka-clients-1.1.1.jar:na]
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:671) ~[kafka-clients-1.1.1.jar:na]
	at com.alibaba.otter.canal.kafka.CanalKafkaProducer.produce(CanalKafkaProducer.java:208) ~[canal.server-1.1.3-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.kafka.CanalKafkaProducer.send(CanalKafkaProducer.java:181) ~[canal.server-1.1.3-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.kafka.CanalKafkaProducer.send(CanalKafkaProducer.java:121) ~[canal.server-1.1.3-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.server.CanalMQStarter.worker(CanalMQStarter.java:182) [canal.server-1.1.3-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.server.CanalMQStarter.access$500(CanalMQStarter.java:22) [canal.server-1.1.3-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.server.CanalMQStarter$CanalMQRunnable.run(CanalMQStarter.java:224) [canal.server-1.1.3-SNAPSHOT.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]

**Comment by agapple** [comment]
kafka的约束吧，你可以调低

**Comment by Bruce2jiang** [comment]
什么意思
