### ISSUE TITLE
启动服务成功，监控不到数据库的改变

### ISSUE THREAD

**Issue by yangyao1623** [alibaba/canal#166]
2016-04-15 15:45:39.563 [destination = image , address = /127.0.0.1:3306 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - prepare to find start position just show master status
2016-04-15 15:45:39.564 [destination = image , address = /127.0.0.1:3306 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - dump address /127.0.0.1:3306 has an error, retrying. caused by 
com.alibaba.otter.canal.parse.exception.CanalParseException: command : 'show master status' has an error!
Caused by: java.io.IOException: ErrorPacket [errorNumber=1227, fieldCount=-1, message=Access denied; you need (at least one of) the SUPER, REPLICATION CLIENT privilege(s) for this operation, sqlState=42000, sqlStateMarker=#]
 with command: show master status
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlQueryExecutor.query(MysqlQueryExecutor.java:60) ~[canal.parse.driver-1.0.21.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.query(MysqlConnection.java:69) ~[canal.parse-1.0.21.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findEndPosition(MysqlEventParser.java:548) ~[canal.parse-1.0.21.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPositionInternal(MysqlEventParser.java:352) ~[canal.parse-1.0.21.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPosition(MysqlEventParser.java:312) ~[canal.parse-1.0.21.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:162) ~[canal.parse-1.0.21.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]

**Comment by OpenZYK** [comment]
执行show master status的时候权限不足吧

**Comment by agapple** [comment]
低级问题，见1楼回复

**Comment by songjian0270** [comment]
查看过权限都是给的777不是这个问题

**Comment by agapple** [comment]
账号权限，不是文件权限

**Comment by songjian0270** [comment]
都给的最大权限,是zookeeper缓存节点没有清空导致的
