### ISSUE TITLE
mysql8 Client Authentication:ErrorPacket 

### ISSUE THREAD

**Issue by windyyong** [alibaba/canal#1660]
### environment

* canal version 1.1.3-snatshop
* mysql version 8.0.14 

mysql已经执行下列语句:
CREATE USER canal IDENTIFIED BY 'canal';  
GRANT SELECT, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'canal'@'%';
GRANT ALL PRIVILEGES ON *.* TO 'canal'@'%' ;
FLUSH PRIVILEGES;

授权了用户canal,mysql5.7可以链接,但是8.0.14报异常,在之前的版本也看到类似问题,但是这里没法应用

```
2019-04-03 13:25:59.063 [destination = example , address = /****:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address /47.107.227.75:3306 has an error, retrying. caused by 
com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: connect /47.107.227.75:3306 failure
Caused by: java.io.IOException: connect /****:3306 failure
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:82) ~[canal.parse.driver-1.1.3-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.connect(MysqlConnection.java:89) ~[canal.parse-1.1.3-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.preDump(MysqlEventParser.java:86) ~[canal.parse-1.1.3-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:175) ~[canal.parse-1.1.3-SNAPSHOT.jar:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
Caused by: java.io.IOException: Error When doing Client Authentication:ErrorPacket [errorNumber=1045, fieldCount=-1, message=Access denied for user 'canal'@'****' (using password: YES), sqlState=28000, sqlStateMarker=#]
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.negotiate(MysqlConnector.java:250) ~[canal.parse.driver-1.1.3-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:79) ~[canal.parse.driver-1.1.3-SNAPSHOT.jar:na]
        ... 4 common frames omitted
2019-04-03 13:25:59.063 [destination = example , address = /****:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: connect /***:3306 failure
Caused by: java.io.IOException: connect /****:3306 failure
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:82)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.connect(MysqlConnection.java:89)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.preDump(MysqlEventParser.java:86)
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:175)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Error When doing Client Authentication:ErrorPacket [errorNumber=1045, fieldCount=-1, message=Access denied for user 'canal'@'****' (using password: YES), sqlState=28000, sqlStateMarker=#]
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.negotiate(MysqlConnector.java:250)
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:79)
        ... 4 more

```

**Comment by windyyong** [comment]
解决了,是mysql8启用了新的密码认证,所以可以在mysql8创建用户时指定认证方式

https://hacpai.com/article/1529724574297

**Comment by agapple** [comment]
赞

**Comment by marchocode** [comment]
mysql 8.0 使用命令如下：

```sql
CREATE USER canal IDENTIFIED WITH mysql_native_password BY 'canal';
```
