### ISSUE TITLE
客户端同步到es时invalid internal transport message format

### ISSUE THREAD

**Issue by fzzrg** [alibaba/canal#1664]
019-04-04 11:18:05.614 [Thread-4] INFO  c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - =============> Subscribe destination: example succeed <=============
2019-04-04 11:18:38.062 [pool-2-thread-1] DEBUG c.a.otter.canal.client.adapter.es.service.ESSyncService - DML: {"data":null,"database":"test","destination":"example","es":1554347917000,"groupId":null,"isDdl":false,"old":null,"pkNames":[],"sql":"INSERT INTO `test`.`user`(`id`, `name`, `age`) VALUES (18, '2', 17)","table":"user","ts":1554347917936,"type":"INSERT"} 
Affected indexes: user 
2019-04-04 11:19:59.233 [pool-2-thread-1] DEBUG c.a.otter.canal.client.adapter.es.service.ESSyncService - DML: {"data":null,"database":"test","destination":"example","es":1554347998000,"groupId":null,"isDdl":false,"old":null,"pkNames":[],"sql":"INSERT INTO `test`.`user`(`id`, `name`, `age`) VALUES (19, 'd', 10)","table":"user","ts":1554347999232,"type":"INSERT"} 
Affected indexes: user 
2019-04-04 11:22:45.616 [elasticsearch[_client_][transport_client_boss][T#2]] WARN  org.elasticsearch.transport.netty4.Netty4Transport - exception caught on transport layer [NettyTcpChannel{localAddress=/127.0.0.1:53622, remoteAddress=/127.0.0.1:9200}], closing connection
io.netty.handler.codec.DecoderException: java.io.StreamCorruptedException: invalid internal transport message format, got (48,54,54,50)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:545)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.StreamCorruptedException: invalid internal transport message format, got (48,54,54,50)
	at org.elasticsearch.transport.TcpTransport.validateMessageHeader(TcpTransport.java:1283)
	at org.elasticsearch.transport.netty4.Netty4SizeHeaderFrameDecoder.decode(Netty4SizeHeaderFrameDecoder.java:36)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	... 19 common frames omitted

**Comment by standinhell** [comment]
@rewerma  求解，同样遇到这个问题，是es版本的问题吗

**Comment by liutaotao** [comment]
顶一下，没有人解答吗

**Comment by chenzeweishare** [comment]
这个问题解决了吗

**Comment by wgl530** [comment]
2021-11-22 17:13:44.616 [elasticsearch[_client_][transport_worker][T#2]] WARN  org.elasticsearch.transport.TcpTransport - exception caught on transport layer [Netty4TcpChannel{localAddress=/127.0.0.1:62394, remoteAddress=/127.0.0.1:9200}], closing connection
io.netty.handler.codec.DecoderException: java.io.StreamCorruptedException: invalid internal transport message format, got (48,54,54,50)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:472) ~[client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241) [client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) [client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) [client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682) [client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:582) [client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:536) [client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) [client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906) [client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_191]
Caused by: java.io.StreamCorruptedException: invalid internal transport message format, got (48,54,54,50)
        at org.elasticsearch.transport.TcpTransport.readHeaderBuffer(TcpTransport.java:745) ~[client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        at org.elasticsearch.transport.TcpTransport.readMessageLength(TcpTransport.java:731) ~[client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        at org.elasticsearch.transport.netty4.Netty4SizeHeaderFrameDecoder.decode(Netty4SizeHeaderFrameDecoder.java:40) ~[client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) ~[client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) ~[client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        ... 20 common frames omitted
2021-11-22 17:13:44.619 [elasticsearch[_client_][transport_worker][T#2]] WARN  org.elasticsearch.transport.TcpTransport - exception caught on transport layer [Netty4TcpChannel{localAddress=/127.0.0.1:62394, remoteAddress=/127.0.0.1:9200}], closing connection
io.netty.handler.codec.DecoderException: java.io.StreamCorruptedException: invalid internal transport message format, got (48,54,54,50)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:472) ~[client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:405) ~[client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:372) ~[client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:355) ~[client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:257) [client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:243) [client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:236) [client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.handler.logging.LoggingHandler.channelInactive(LoggingHandler.java:167) [client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:257) [client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:243) [client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:236) [client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1403) [client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:257) [client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:243) [client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:912) [client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:827) [client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:405) [client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906) [client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_191]
Caused by: java.io.StreamCorruptedException: invalid internal transport message format, got (48,54,54,50)
        at org.elasticsearch.transport.TcpTransport.readHeaderBuffer(TcpTransport.java:745) ~[client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        at org.elasticsearch.transport.TcpTransport.readMessageLength(TcpTransport.java:731) ~[client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        at org.elasticsearch.transport.netty4.Netty4SizeHeaderFrameDecoder.decode(Netty4SizeHeaderFrameDecoder.java:40) ~[client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) ~[client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) ~[client-adapter.es7x-1.1.6-SNAPSHOT-jar-with-dependencies.jar:na]
        ... 21 common frames omitted

**Comment by wgl530** [comment]
有人解决了吗？

**Comment by codingXcong** [comment]
遇到过这个问题，es端口错了，检查es的端口：
9200 for rest mode
9300 for transport mode
