### ISSUE TITLE
canal 1.1.3 同步ES NoNodeAvailableException

### ISSUE THREAD

**Issue by belief-Yang** [alibaba/canal#1667]
错误信息 : 

    2019-04-04 16:52:22.209 [pool-2-thread-1] INFO  c.a.o.canal.client.adapter.logger.LoggerAdapterExample - DML: {"data":[{"id":42,"name":"ddd","age":444}],"database":"datasou","destination":"example","es":1554367941000,"groupId":null,"isDdl":false,"old":null,"pkNames":["id"],"sql":"","table":"t_user","ts":1554367942150,"type":"INSERT"}
    2019-04-04 16:52:22.211 [pool-2-thread-1] ERROR c.a.otter.canal.client.adapter.es.service.ESSyncService - sync error, es index: data_sou_t_user, DML : Dml{destination='example', database='datasou', table='t_user', type='INSERT', es=1554367941000, ts=1554367942209, sql='', data=[{id=42, name=ddd, age=444}], old=null}
    2019-04-04 16:52:22.212 [pool-2-thread-1] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{gMdirtzORdaJ4Un-OZ0wmQ}{106.*.34.*}{106.*.34.*:9200}]]
    java.lang.RuntimeException: NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{gMdirtzORdaJ4Un-OZ0wmQ}{106.*.34.*}{106.*.34.*:9200}]]
        at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.sync(ESSyncService.java:113)
        at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.sync(ESSyncService.java:61)
        at com.alibaba.otter.canal.client.adapter.es.ESAdapter.sync(ESAdapter.java:176)
        at com.alibaba.otter.canal.client.adapter.es.ESAdapter.sync(ESAdapter.java:155)
        at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.batchSync(AbstractCanalAdapterWorker.java:198)
        at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$1(AbstractCanalAdapterWorker.java:62)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$2(AbstractCanalAdapterWorker.java:58)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
    Caused by: org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: [{#transport#-1}{gMdirtzORdaJ4Un-OZ0wmQ}{106.*.34.*}{106.*.34.*:9200}]
        at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:347)
        at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:245)
        at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:60)
        at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:371)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:405)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:394)
        at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.execute(AbstractClient.java:706)
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:46)
        at com.alibaba.otter.canal.client.adapter.es.support.ESTemplate.getEsType(ESTemplate.java:492)
        at com.alibaba.otter.canal.client.adapter.es.support.ESTemplate.getValFromData(ESTemplate.java:340)
        at com.alibaba.otter.canal.client.adapter.es.support.ESTemplate.getESDataFromDmlData(ESTemplate.java:371)
        at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.singleTableSimpleFiledInsert(ESSyncService.java:436)
        at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.insert(ESSyncService.java:136)
        at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.sync(ESSyncService.java:96)
        ... 11 common frames omitted
    2019-04-04 16:52:22.213 [Thread-4] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - Outer adapter sync failed!  Error sync but ACK!

app配置 : 

    canalAdapters:
    - instance: example # canal instance Name or mq topic name
        groups:
        - groupId: g1
        outerAdapters:
        - name: logger
        - name: es
            hosts: 106.*.34.*:9200
            properties:
              cluster.name: elasticsearch

es配置 : 

    # ---------------------------------- Cluster -----------------------------------
    #
    # Use a descriptive name for your cluster:
    #
    cluster.name: elasticsearch
    #
    # ------------------------------

**Comment by belief-Yang** [comment]
求帮助 , 真的搞不动了.

**Comment by agapple** [comment]
java.lang.RuntimeException: NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{gMdirtzORdaJ4Un-OZ0wmQ}{106.*.34.*}{106.*.34.*:9200}]]

是否ES服务不可用？

**Comment by belief-Yang** [comment]
在2019-04-04 17:20:00，"agapple" <notifications@github.com> 写道：


java.lang.RuntimeException: NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{gMdirtzORdaJ4Un-OZ0wmQ}{106. .34. }{106. .34. :9200}]]

是否ES服务不可用？

____

检索结束

{name=lisi, age=21}

index:data_sou_t_user type:t_user id:2

{name=zhangsan, age=20}

index:data_sou_t_user type:t_user id:1

{name=wangwu, age=22}

index:data_sou_t_user type:t_user id:3

可用

**Comment by belief-Yang** [comment]
可用

**Comment by jy4618272** [comment]
es如果有用证书的话，需要在连接代码上面进行一些调整，用es生成的证书连接才行。

**Comment by purevirtual** [comment]
@belief-Yang 发现我们碰到了同样的问题 我这边也是这样的报错

**Comment by MrYZD** [comment]
canal 1.1.3 
es：7.0.0 也有这样的问题

**Comment by purevirtual** [comment]
> canal 1.1.3
> es：7.0.0 也有这样的问题

还有种可能是加密认证方式没配对 或者 用户名密码错误 建议你从docker上下一个无加密的es试试

**Comment by jzb1006** [comment]
请问仁兄的问题解决了吗？我也遇到这和问题了，ES是6.6的，canal是最新的

**Comment by yj1851** [comment]
CANAL 1.1.3 
ES:7.0.1也遇到同样的问题

**Comment by glenn2wang** [comment]
es的话 默认端口是9200，但是java链接的话 需要是9300

**Comment by 888tyhj** [comment]
有大神搞定吗，怎么搞定的啊，我也遇到了

**Comment by cqxxxxxxxx** [comment]
我在如下环境遇到这个问题
canal 1.1.4
es: 7.9.1 

解决方案：
文档里有说明，如果需要支持其他版本的ES，需要自己下载源码重新编译。

1. 源码下载，mvn clean install 
2. 复制client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies到plugin目录下，删除老的es包
3. 修改application.yml,   name从es改成es7
4. 修改conf下面es文件夹名字，改成es7

成功启动。

**Comment by zuxianghuang** [comment]
我canal 1.1.6 ，es 7.17.3 也遇到了
