### ISSUE TITLE
CanalClientException: deserializer failed，destination:example should start first

### ISSUE THREAD

**Issue by xmt1139057136** [alibaba/canal#1679]
## Question

com.alibaba.otter.canal.protocol.exception.CanalClientException: deserializer failed
	at com.alibaba.otter.canal.client.CanalMessageDeserializer.deserializer(CanalMessageDeserializer.java:54) ~[canal.client-1.1.2.jar:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.receiveMessages(SimpleCanalConnector.java:322) ~[canal.client-1.1.2.jar:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.getWithoutAck(SimpleCanalConnector.java:314) ~[canal.client-1.1.2.jar:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.getWithoutAck(SimpleCanalConnector.java:286) ~[canal.client-1.1.2.jar:na]
	at com.jiuhuar.jmb.admin.core.CanalCoreEngine.getMessage(CanalCoreEngine.java:110) [classes/:na]
	at com.jiuhuar.jmb.admin.core.CanalCoreEngine.engine(CanalCoreEngine.java:81) [classes/:na]
	at com.jiuhuar.jmb.admin.core.CanalEntryRunner.run(CanalEntryRunner.java:28) [classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:723) [spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:713) [spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:703) [spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:304) [spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]
	at com.jiuhuar.jmb.admin.MagpieBridgeApplication.main(MagpieBridgeApplication.java:18) [classes/:na]
Caused by: com.alibaba.otter.canal.protocol.exception.CanalClientException: something goes wrong with reason: something goes wrong with channel:[id: 0x2f8dae0b, /127.0.0.1:64679 => /127.0.0.1:11111], exception=com.alibaba.otter.canal.server.exception.CanalServerException: destination:example should start first

	at com.alibaba.otter.canal.client.CanalMessageDeserializer.deserializer(CanalMessageDeserializer.java:46) ~[canal.client-1.1.2.jar:na]
	... 13 common frames omitted

哎，这个问题搞我几个小时了。已经连续加班好久了。
请问这个大概是个什么问题啊？

**Comment by wajika** [comment]
deployer 实例要先启动

**Comment by agapple** [comment]
com.alibaba.otter.canal.client.CanalMessageDeserializer.deserializer(CanalMessageDeserializer.java:54) ~[canal.client-1.1.2.jar:na]

估计客户端是protobuf模式，而服务端是flatMessage模式

**Comment by jinxiu2216** [comment]
请问这个问题您解决了吗？我也经常会遇到这个错误，很头大

**Comment by agapple** [comment]
1. 客户端和服务端的数据传输格式不对,  客户端是protobuf模式，而服务端是flatMessage模式. 
2. 中间变化过flatMessage模式, 而MQ topic里有历史老格式的数据

**Comment by wzswzjwsj** [comment]
到底怎么解决的，我重新了客户端和服务端都不行

**Comment by ilaotan** [comment]
我也遇不到了，官方代码里不能统一一下吗？？？运行example 就报这错

**Comment by debugzhao** [comment]
遇到类似的问题了，怎么解决的啊

2025-03-18 06:30:20.199 [Thread-4] INFO  c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - =============> Start to connect destination: example <=============

2025-03-18 06:30:20.200 [Thread-4] ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - process error!

com.alibaba.otter.canal.protocol.exception.CanalClientException: failed to subscribe with reason: something goes wrong with channel:[id: 0x00ebdee1, /172.17.0.2:36912 => /192.168.51.69:11111], exception=com.alibaba.otter.canal.server.exception.CanalServerException: destination:example should start first

	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.subscribe(SimpleCanalConnector.java:253)

	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.subscribe(SimpleCanalConnector.java:229)

	at com.alibaba.otter.canal.connector.tcp.consumer.CanalTCPConsumer.connect(CanalTCPConsumer.java:65)

	at com.alibaba.otter.canal.connector.core.spi.ProxyCanalMsgConsumer.connect(ProxyCanalMsgConsumer.java:41)

	at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.process(AdapterProcessor.java:187)

	at java.lang.Thread.run(Thread.java:750)
