### ISSUE TITLE
reset master后出现的binlog寻找不到的问题

### ISSUE THREAD

**Issue by ch-lgs** [alibaba/canal#168]
pid:2 nid:2 exception:canal:shanghai_canal:java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:95)
at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:113)
at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209)
at java.lang.Thread.run(Thread.java:745)

通过mysql日志发现canal依然请求原始的binlog，请问这个问题是否有处理机制？谢谢

**Comment by songjian0270** [comment]
@ch-lgs  请问下是如何处理的呢

**Comment by JichengSong** [comment]
RESET MASTER :删除所有的二进制日志，并重新创建一个新的二进制日志

原始binlog被删除了，canal也就无法消费了,所以会报错。解决办法是重设一个消费点位,  该点位之前的数据丢失。
