### ISSUE TITLE
使用logstash+canal-adapter做全量同步，canal无法发现logstash创建的mapping？

### ISSUE THREAD

**Issue by wajika** [alibaba/canal#1681]
## Question
```
2019-04-10 14:07:30.956 [pool-2-thread-1] ERROR c.a.otter.canal.client.adapter.es.service.ESSyncService - sync error, es index: sql_test, DML : Dml{destination='example', database='wenzhou', table='t_groupon_childorder', type='INSERT', es=1554876448000, ts=1554876450843, sql='', data=[{rowid=840906, forderid=, fchildorderid=, fpuserid=, fpusername=, fcusername=, fgroupgoodid=, fgroupgoodname=, funitprice=null, famountprice=null, fgroupprice=null, fsmallprice=null, fgiveintegral=null, fstatus=0, fmanufacturer=, fmarketingplanid=, fmktplanchangeid=, fordertype=0, fmateriafid=, fmaterialname=, fflutetype=, flayer=null, fboxmodel=0, fboxlength=null, fboxwidth=null, fboxheight=null, fmateriallength=0.0, fmaterialwidth=0.0, famount=0, famountpiece=0, fseries=, fhformula=null, fvformula=null, fproductarea=0.0, fstavetype=, fhline=, fvline=, fvlineplus=, fhlineformula=, fvlineformula=, fdelivery=null, fdistime=null, fsignintime=null, ftransportsheet=, fconsignee=, fcontactway=, fdispatchingtime=null, flogistics=, fcodeprovince=, flnglat=, faddressdetail=, faddressremark=, foperatetime=null, foperatorid=, foperator=, fdblflag=null, fchildpaymenttime=null, fgokeyarea=null, fexcpstatus=1, fdeletestatus=null, fcarttime=null, fmaterialwidthplus=null, fmateriallengthplus=null, furgencyorder=0, fupdatetime=2019-04-10 14:07:28.0, fcreatetime=2019-04-10 14:07:28.0, fkeyarea=0, fgroupareaid=null, fsplitorder=null, fproductionno=, fdiscountamount=null, fbasamount=null, fusercouponid=, frefundamount=0.0, frefundabnorma=null, freturndiscount=0.0, fdeductintegral=0, fprovincename=, fcodeprovinces=null, fcityname=, fcodecity=null, fareaname=, fcodearea=null, ftownname=, fcodetown=null, foutstock=null, finstock=null}], old=null}
2019-04-10 14:07:30.971 [pool-2-thread-1] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - java.lang.IllegalArgumentException: Not found the mapping info of index: sql_test
java.lang.RuntimeException: java.lang.IllegalArgumentException: Not found the mapping info of index: sql_test
	at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.sync(ESSyncService.java:113)
	at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.sync(ESSyncService.java:61)
	at com.alibaba.otter.canal.client.adapter.es.ESAdapter.sync(ESAdapter.java:176)
	at com.alibaba.otter.canal.client.adapter.es.ESAdapter.sync(ESAdapter.java:155)
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.batchSync(AbstractCanalAdapterWorker.java:198)
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$1(AbstractCanalAdapterWorker.java:62)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$2(AbstractCanalAdapterWorker.java:58)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Not found the mapping info of index: sql_test
	at com.alibaba.otter.canal.client.adapter.es.support.ESTemplate.getEsType(ESTemplate.java:504)
	at com.alibaba.otter.canal.client.adapter.es.support.ESTemplate.getValFromData(ESTemplate.java:340)
	at com.alibaba.otter.canal.client.adapter.es.support.ESTemplate.getESDataFromDmlData(ESTemplate.java:371)
	at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.singleTableSimpleFiledInsert(ESSyncService.java:436)
	at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.insert(ESSyncService.java:136)
	at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.sync(ESSyncService.java:96)
	... 11 common frames omitted
2019-04-10 14:07:30.971 [Thread-4] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - Outer adapter sync failed!  Error sync but ACK!
```
我使用logstash先做了全量同步，同步后再用canal做增量同步，但是启动canal后出现了这个错误提示，在elasticsearch中存在这个index，是因为canal不识别这个index吗？

另外ES中手动创建的mapping和logstash创建的mapping 字段有点不同，不知道canal能不能支持容错

**Comment by lza1997** [comment]
真假，会存在这种问题吗，解决了吗，那没法用啊

**Comment by wajika** [comment]
这是手工建立的mapping
```
"mappings": {
"_doc": {
"properties": {
"fpusername": {
"type": "text"
},
"faddressdetail": {
"type": "text"
},
"rowid": {
"type": "long"
}
}
}
},
```
这是logstash创建的mapping
```
"mappings": {
"doc": {
"properties": {
"fpusername": {
"type": "text",
"fields": {
"keyword": {
"ignore_above": 256,
"type": "keyword"
}
}
},
"faddressdetail": {
"type": "text",
"fields": {
"keyword": {
"ignore_above": 256,
"type": "keyword"
}
}
},
"rowid": {
"type": "long"
}
}
}
},
```

canal-deployer tcp模式，canal-adapter 除了in/out配置其他都没有动

**Comment by wajika** [comment]
@agapple 这个问题可以解答一下吗？ 确认是否可以

**Comment by bsed** [comment]
old=[{PhoneNumber=18601960764}]}
2019-09-23 14:43:50.142 [pool-2-thread-1] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - java.lang.NullPointerException
java.lang.RuntimeException: java.lang.NullPointerException
        at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.sync(ESSyncService.java:110)
        at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.sync(ESSyncService.java:58)
        at com.alibaba.otter.canal.client.adapter.es.ESAdapter.sync(ESAdapter.java:169)
        at com.alibaba.otter.canal.client.adapter.es.ESAdapter.sync(ESAdapter.java:148)
        at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.batchSync(AbstractCanalAdapterWorker.java:201)
        at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$1(AbstractCanalAdapterWorker.java:62)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$2(AbstractCanalAdapterWorker.java:58)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
        at com.alibaba.otter.canal.client.adapter.es.support.ESTemplate.append4Update(ESTemplate.java:231)
        at com.alibaba.otter.canal.client.adapter.es.support.ESTemplate.update(ESTemplate.java:115)
        at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.singleTableSimpleFiledUpdate(ESSyncService.java:802)
        at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.update(ESSyncService.java:206)
        at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.sync(ESSyncService.java:95)
        ... 11 common frames omitted
2019-09-23 14:43:50.143 [Thread-4] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - Outer adapter sync failed!  Error sync but ACK!

**Comment by ACEZOORO** [comment]
要看下你adapter适配器的es中index配置，我也是logstash切换到canal，没啥问题
