### ISSUE TITLE
canal读取历史binlog异常

### ISSUE THREAD

**Issue by windyyong** [alibaba/canal#1692]
## canal无法读取binlog
mysql8.0.14  canal1.1.3

希望读取旧数据,所以在canal中设置mysql的binlog位置信息
在canal的conf/example/instance.properties中设置binlog开始位置

> # position info
> canal.instance.master.address=192.183.3.109:3306
> canal.instance.master.journal.name=mysql-bin.000001
> canal.instance.master.position=1

mysql8中输入show master status;
返回 

>  File             | Position | Binlog_Do_DB | Binlog_Ignore_DB | Executed_Gtid_Set |
> +------------------+----------+--------------+------------------+-------------------+
> | mysql-bin.000054 |    37254 |                         |                     |                   |
> +------------------+----------+--------------+------------------+---------------

当我不设置position info的时候,是正常的,如果设置了position info,会报以下异常

```
2019-04-11 16:20:03.057 [destination = example , address = /192.183.3.109:3306 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - I/O error while reading from client socket
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102) ~[canal.parse-1.1.3.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.seek(MysqlConnection.java:144) [canal.parse-1.1.3.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findAsPerTimestampInSpecificLogFile(MysqlEventParser.java:743) [canal.parse-1.1.3.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findPositionWithMasterIdAndTimestamp(MysqlEventParser.java:407) [canal.parse-1.1.3.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPositionInternal(MysqlEventParser.java:452) [canal.parse-1.1.3.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPosition(MysqlEventParser.java:366) [canal.parse-1.1.3.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:186) [canal.parse-1.1.3.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_201]
2019-04-11 16:20:03.057 [destination = example , address = /192.183.3.109:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ERROR ## findAsPerTimestampInSpecificLogFile has an error
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102) ~[canal.parse-1.1.3.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.seek(MysqlConnection.java:144) ~[canal.parse-1.1.3.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findAsPerTimestampInSpecificLogFile(MysqlEventParser.java:743) [canal.parse-1.1.3.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findPositionWithMasterIdAndTimestamp(MysqlEventParser.java:407) [canal.parse-1.1.3.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPositionInternal(MysqlEventParser.java:452) [canal.parse-1.1.3.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPosition(MysqlEventParser.java:366) [canal.parse-1.1.3.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:186) [canal.parse-1.1.3.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_201]
2019-04-11 16:20:03.058 [destination = example , address = /192.183.3.109:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address /192.183.3.109:3306 has an error, retrying. caused by
com.alibaba.otter.canal.parse.exception.CanalParseException: [fixed timestamp] can't found begin/commit position before with fixed positionmysql-bin.000001:1
2019-04-11 16:20:03.058 [destination = example , address = /192.183.3.109:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[com.alibaba.otter.canal.parse.exception.CanalParseException: [fixed timestamp] can't found begin/commit position before with fixed positionmysql-bin.000001:1
```

**Comment by aBlackAnt** [comment]
因为拉取不到mysql-bin.000001了，mysql中的是mysql-bin.000054了

**Comment by windyyong** [comment]
> 因为拉取不到mysql-bin.000001了，mysql中的是mysql-bin.000054了

那如果我希望读取旧历史记录呢?需要手工读取吗?

**Comment by agapple** [comment]
binlog文件都不存在了，那就没办法

**Comment by xiaoyu-peng** [comment]
今天遇到类似的问题，配置最新的Binlog依然报错！！！

查看Canal官网获取信息如下：
--->>>mysql链接时的起始位置（instance.properties）
canal.instance.master.journal.name + canal.instance.master.position : 精确指定一个binlog位点，进行启动
canal.instance.master.timestamp : 指定一个时间戳，canal会自动遍历mysql binlog，找到对应时间戳的binlog位点后，进行启动
不指定任何信息：默认从当前数据库的位点，进行启动。

解决方案：
将“canal.instance.master.journal.name=”设置为空值，通过走默认值的方式解决上面问题。
