### ISSUE TITLE
Canal-adapter-1.1.3 mysql 同步数据到 elasticsearch 报错

### ISSUE THREAD

**Issue by zhuxiaokang0223** [alibaba/canal#1693]
## Question

2019-04-11 16:49:30.532 [pool-2-thread-1] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - java.lang.RuntimeException: java.lang.RuntimeException: TransportSerializationException[Failed to deserialize response from handler [org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler]]; nested: IllegalArgumentException[Unknown NamedWriteable [org.elasticsearch.cluster.metadata.MetaData$Custom][ml]];
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: TransportSerializationException[Failed to deserialize response from handler [org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler]]; nested: IllegalArgumentException[Unknown NamedWriteable [org.elasticsearch.cluster.metadata.MetaData$Custom][ml]];
	at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.sync(ESSyncService.java:113)
	at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.sync(ESSyncService.java:61)
	at com.alibaba.otter.canal.client.adapter.es.ESAdapter.sync(ESAdapter.java:176)
	at com.alibaba.otter.canal.client.adapter.es.ESAdapter.sync(ESAdapter.java:155)
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.batchSync(AbstractCanalAdapterWorker.java:198)
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$1(AbstractCanalAdapterWorker.java:62)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$2(AbstractCanalAdapterWorker.java:58)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: TransportSerializationException[Failed to deserialize response from handler [org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler]]; nested: IllegalArgumentException[Unknown NamedWriteable [org.elasticsearch.cluster.metadata.MetaData$Custom][ml]];
	at com.alibaba.otter.canal.client.adapter.support.Util.sqlRS(Util.java:47)
	at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.mainTableInsert(ESSyncService.java:468)
	at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.insert(ESSyncService.java:140)
	at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.sync(ESSyncService.java:96)
	... 11 common frames omitted
Caused by: java.lang.RuntimeException: TransportSerializationException[Failed to deserialize response from handler [org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler]]; nested: IllegalArgumentException[Unknown NamedWriteable [org.elasticsearch.cluster.metadata.MetaData$Custom][ml]];
	at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.lambda$mainTableInsert$3(ESSyncService.java:485)
	at com.alibaba.otter.canal.client.adapter.support.Util.sqlRS(Util.java:43)
	... 14 common frames omitted
Caused by: org.elasticsearch.transport.TransportSerializationException: Failed to deserialize response from handler [org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler]
	at org.elasticsearch.transport.TcpTransport.handleResponse(TcpTransport.java:1441)
	at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:1400)
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:64)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:545)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	... 1 common frames omitted
Caused by: java.lang.IllegalArgumentException: Unknown NamedWriteable [org.elasticsearch.cluster.metadata.MetaData$Custom][ml]
	at org.elasticsearch.common.io.stream.NamedWriteableRegistry.getReader(NamedWriteableRegistry.java:112)
	at org.elasticsearch.common.io.stream.NamedWriteableAwareStreamInput.readNamedWriteable(NamedWriteableAwareStreamInput.java:45)
	at org.elasticsearch.common.io.stream.NamedWriteableAwareStreamInput.readNamedWriteable(NamedWriteableAwareStreamInput.java:39)
	at org.elasticsearch.cluster.metadata.MetaData.readFrom(MetaData.java:775)
	at org.elasticsearch.cluster.ClusterState.readFrom(ClusterState.java:668)
	at org.elasticsearch.action.admin.cluster.state.ClusterStateResponse.readFrom(ClusterStateResponse.java:81)
	at org.elasticsearch.transport.TransportResponseHandler.read(TransportResponseHandler.java:47)
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.read(TransportService.java:1085)
	at org.elasticsearch.transport.TcpTransport.handleResponse(TcpTransport.java:1437)
	... 27 common frames omitted
2019-04-11 16:49:30.534 [Thread-4] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - Outer adapter sync failed!  Error sync but ACK!
2019-04-11 16:49:30.534 [elasticsearch[_client_][transport_client_boss][T#3]] WARN  org.elasticsearch.transport.netty4.Netty4Transport - exception caught on transport layer [NettyTcpChannel{localAddress=/192.168.100.207:59176, remoteAddress=/192.168.100.204:9300}], closing connection
java.lang.IllegalStateException: Message not fully read (response) for requestId [13], handler [org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler/org.elasticsearch.action.ActionListenerResponseHandler@58cac2ff], error [false]; resetting
	at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:1407)
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:64)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:545)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)

**Comment by zhuxiaokang0223** [comment]
elasticsearch server版本号是6.2.4
Canal server版本号1.1.3
Canal-adapter版本号1.1.3

mysql数据变化时，canal-adapter得到了数据， 但是向elasticsearch同步数据时，抛异常了

**Comment by wajika** [comment]
es和adapter之间的配置好像存在问题

**Comment by zhuxiaokang0223** [comment]
application.yml中es的配置：
`
server:
  port: 8081
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

canal.conf:
  mode: tcp # kafka rocketMQ
  canalServerHost: 127.0.0.1:11111
#  zookeeperHosts: slave1:2181
#  mqServers: 127.0.0.1:9092 #or rocketmq
#  flatMessage: true
  batchSize: 500
  syncBatchSize: 1000
  retries: 0
  timeout:
  accessKey:
  secretKey:
  srcDataSources:
    defaultDS:
      url: jdbc:mysql://127.0.0.1:3306/sx_test?useUnicode=true
      username: root
      password: root
  canalAdapters:
  - instance: example # canal instance Name or mq topic name
    groups:
    - groupId: g1
      outerAdapters:
      - name: logger
 - name: es
        hosts: 127.0.0.1:9300
        properties:
          cluster.name: es-cluster
`

es yml配置：
`
dataSourceKey: defaultDS
destination: example
groupId: g1
esMapping:
  _index: canal_test
  _type: _doc
  _id: _id
  upsert: true
#  pk: id
  sql: "select 
          concat(ts.task_id,'_',ts.student_id) as _id, 
          ts.task_id as task_id, 
          ts.student_id as student_id, 
          ts.student_name as student_name, 
          s.sign_time as sign_time 
        from t_task_student ts 
        left join t_sign s 
        on ts.task_id=s.task_id and ts.student_id=s.student_id"
#  objFields:
#    _labels: array:;
  etlCondition: ""
  commitBatch: 3000
`

@wajika 能帮忙看看哪里的问题吗

**Comment by purevirtual** [comment]
看起来像是写入es的时候出的问题 建议从docker上面下一个es6 然后去掉用户名和密码试试

**Comment by zhuxiaokang0223** [comment]
@purevirtual 虽然安装了X-PACK，但是并没有设置用户名和密码，而且也尝试了将ml和security设置为false，还是报同样的错。
跟踪源码，发现是获取Mapping的时候报的错：
```
mappings = transportClient.admin()
                    .cluster()
                    .prepareState()
                    .execute()
                    .actionGet()   //执行这里时，报错：Unknown NamedWriteable [org.elasticsearch.cluster.metadata.MetaData$Custom][ml]
                    .getState()
                    .getMetaData()
                    .getIndices()
                    .get(mapping.get_index())
                    .getMappings();
```

尝试修改源码，改为：
```
 GetMappingsResponse g = transportClient.admin().indices().prepareGetMappings(mapping.get_index()).get();
                mappings = g.getMappings().get(mapping.get_index());
```
成功获取Mapping， 程序执行完成。 但是数据没能插入es

**Comment by purevirtual** [comment]
那就不知道了 换个简单的mapping字段试试先？

**Comment by zhuxiaokang0223** [comment]
@purevirtual 
发现是这里的问题：
```
/**
     * 如果大于批量数则提交批次
     */
    private void commitBulk() {
        if (getBulk().numberOfActions() >= MAX_BATCH_SIZE) {
            commit();
        }
    }
```
我使用测试用例中的UserSyncSingleTest.test01方法测试的。
数据量没有达到MAX_BATCH_SIZE条，所以没有commit();

看起来，需要达到1000条才能提交一个批次， 这样的话，就不能实时同步mysql变更的数据了么？

**Comment by wajika** [comment]
确认一下你的es版本，es mapping格式

**Comment by zhuxiaokang0223** [comment]
@wajika 
elasticsearch版本号是6.2.4
Canal server版本号1.1.3
Canal-adapter版本号1.1.3

mapping格式：

"mappings": {
      "_doc": {
        "properties": {
          "_c_time": {
            "type": "date"
          },
          "_labels": {
            "type": "text"
          },
          "_name": {
            "type": "text"
          },
          "_role_id": {
            "type": "long"
          },
          "_role_name": {
            "type": "text"
          }
        }
      }
    }

**Comment by wajika** [comment]
> @wajika
> elasticsearch版本号是6.2.4
> Canal server版本号1.1.3
> Canal-adapter版本号1.1.3
> 
> mapping格式：
> 
> ```
> "mappings": {
>       "_doc": {
>         "properties": {
>           "_c_time": {
>             "type": "date"
>           },
>           "_labels": {
>             "type": "text"
>           },
>           "_name": {
>             "type": "text"
>           },
>           "_role_id": {
>             "type": "long"
>           },
>           "_role_name": {
>             "type": "text"
>           }
>         }
>       }
>     }
> ```

全量同步你是靠什么软件来做的？

**Comment by zhuxiaokang0223** [comment]
目前只考虑增量

**Comment by hektor8603** [comment]
> > @wajika
> > elasticsearch版本号是6.2.4
> > Canal server版本号1.1.3
> > Canal-adapter版本号1.1.3
> > mapping格式：
> > ```
> > "mappings": {
> >       "_doc": {
> >         "properties": {
> >           "_c_time": {
> >             "type": "date"
> >           },
> >           "_labels": {
> >             "type": "text"
> >           },
> >           "_name": {
> >             "type": "text"
> >           },
> >           "_role_id": {
> >             "type": "long"
> >           },
> >           "_role_name": {
> >             "type": "text"
> >           }
> >         }
> >       }
> >     }
> > ```
> 
> 全量同步你是靠什么软件来做的？
全量同步太多组件可以用了 阿里的datax就行啊 还有什么logstash啊 sqoop啊  好多好多

**Comment by simonlei** [comment]
应该是 es 配置里面，设置的 _id : id 造成的吧，你的sql语句里面最后select出来的实际上只有 _id字段

**Comment by rewerma** [comment]
楼上正解

**Comment by bsed** [comment]
```
_id: _id
upsert: true
sql: "select
concat(ts.task_id,'',ts.student_id) as _id,
ts.task_id as task_id,
ts.student_id as student_id,
ts.student_name as student_name,
s.sign_time as sign_time
from t_task_student ts
left join t_sign s
on ts.task_id=s.task_id and ts.student_id=s.student_id"
etlCondition: ""
commitBatch: 3000
```

**Comment by darrenchinesedba** [comment]
> es和adapter之间的配置好像存在问题

mysql 8.0.20 to es 7.8   您最后配置成功了吗

**Comment by darrenchinesedba** [comment]
elasticsearch server版本号是7.8
mysql 8.0.20
Canal server版本号1.1.5
Canal-adapter版本号1.1.5

**Comment by gaoxinshuai** [comment]
你好，能问一下怎么解决的吗，我出了同样的问题
