### ISSUE TITLE
MySQL8.0 caching_sha2_password Auth failed

### ISSUE THREAD

**Issue by masteryhx** [alibaba/canal#1700]
### environment

* canal version 1.1.3
* mysql version 8.0.11

### Issue Description
按Wiki配置用户和权限：
`CREATE USER canal IDENTIFIED BY 'canal';  
GRANT SELECT, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'canal'@'%';
-- GRANT ALL PRIVILEGES ON *.* TO 'canal'@'%' ;
FLUSH PRIVILEGES;`
instance.properties里的配置同Wiki
user canal 的plugin信息如下：
user | plugin
canal | caching_sha2_password

### Actual behaviour

```
com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: connect /127.0.0.1:3306 failure
Caused by: java.io.IOException: connect /127.0.0.1:3306 failure
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:83) ~[canal.parse.driver-1.1.3.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.connect(MysqlConnection.java:89) ~[canal.parse-1.1.3.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.preDump(MysqlEventParser.java:86) ~[canal.parse-1.1.3.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:175) ~[canal.parse-1.1.3.jar:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
Caused by: java.io.IOException: caching_sha2_password Auth failed
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.negotiate(MysqlConnector.java:257) ~[canal.parse.driver-1.1.3.jar:na]
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:80) ~[canal.parse.driver-1.1.3.jar:na]
        ... 4 common frames omitted

```

**Comment by agapple** [comment]
这个报错应该是密码不正确

**Comment by agapple** [comment]
可以跑下MysqlConnectorTest，尝试tcpdump抓一下包

**Comment by yj1851** [comment]
换到mysql 5.7版本就没有这个错误

**Comment by yj1851** [comment]
换到mysql 5.7版本就没有这个错误

**Comment by lugging** [comment]
同样发生这个错误，貌似8版本密码机制和之前不一样。MySQL 8 中，caching_sha2_password 是默认的身份验证插件，而不是以往的 mysql_native_password

**Comment by agapple** [comment]
可以跑下MysqlConnectorTest，尝试tcpdump抓一下包。

拿到网络包发我，caching_sha2_password 在canal 1.1.2+之后是支持的

**Comment by zhang530** [comment]
修改密码永不过期解决

ALTER USER 'canal'@'%' IDENTIFIED BY 'canal' PASSWORD EXPIRE NEVER;
ALTER USER 'canal'@'%' IDENTIFIED WITH mysql_native_password BY 'canal';
FLUSH PRIVILEGES;

**Comment by GLBB** [comment]
@zhang530 谢谢老哥，弄了几个小时，终于解决了

**Comment by Ljia-ncu** [comment]
@zhang530 大哥优秀，这问题搞得我都开始怀疑自己了.

**Comment by chanhan** [comment]
@zhang530  多谢大佬！

**Comment by zhuSilence** [comment]
> 修改密码永不过期解决
> 
> ALTER USER 'canal'@'%' IDENTIFIED BY 'canal' PASSWORD EXPIRE NEVER;
> ALTER USER 'canal'@'%' IDENTIFIED WITH mysql_native_password BY 'canal';
> FLUSH PRIVILEGES;

感谢老哥啊，五体投地

**Comment by photographzzz** [comment]
> 

老哥，这样的确能解决，但是想请教下是因为什么原因导致这个问题的呢？

**Comment by 12345ZMTHL** [comment]
> 修改密码永不过期解决
> 
> ALTER USER 'canal'@'%' IDENTIFIED BY 'canal' PASSWORD EXPIRE NEVER; ALTER USER 'canal'@'%' IDENTIFIED WITH mysql_native_password BY 'canal'; FLUSH PRIVILEGES;

感谢感谢

**Comment by fishjam** [comment]
看 `WITH mysql_native_password` , 似乎是改了密码验证机制. 相当于废弃了 `caching_sha2_password`. 这种算是一种规避方式. 
根据网上的介绍, MySQL 8.x 引入了新的 caching_sha2_password 身份验证插件, 但对应的, 客户端也只能是 8.x 的才能支持. 

在我自己写的使用 dev.miku:r2dbc-mysql 的客户端程序中遇到相同问题, 后来发现 r2dbc-mysql 只在 test 情况下才引入 `mysql-connector-java` 包, 于是我手动加入 spring-boot 自带的 `mysql:mysql-connector-java:8.0.29 依赖以后`, 问题解决. 

补充:
  可以通过以下命令查看服务器的验证模式(可以在执行 @zhang530 的更改密码前后执行 )
  `SELECT user,authentication_string,plugin,host FROM mysql.user;`

**Comment by bygaoyuan** [comment]
> 可以跑下MysqlConnectorTest，尝试tcpdump抓一下包。
> 
> 拿到网络包发我，caching_sha2_password 在canal 1.1.2+之后是支持的

canal1.1.2+应该如何配置caching_sha2_password呢

**Comment by LiHanGod** [comment]
canal version 1.1.6
mysql version 8.3.0

```sh
2024-03-01 23:36:26.162 [destination = example , address = mysql-local/172.19.0.10:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: connect mysql-local/172.19.0.10:3306 failure
Caused by: java.io.IOException: connect mysql-local/172.19.0.10:3306 failure
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:85)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.connect(MysqlConnection.java:89)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.preDump(MysqlEventParser.java:87)
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:176)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: caching_sha2_password Auth failed
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.negotiate(MysqlConnector.java:260)
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:82)
        ... 4 more
```
还是会有不支持的情况

**Comment by agapple** [comment]
也可以看下这个issue的修复 https://github.com/alibaba/canal/issues/5301
