### ISSUE TITLE
caching_sha2_password Auth failed 

### ISSUE THREAD

**Issue by windyyong** [alibaba/canal#1701]
### environment

* canal version 1.1.3
* mysql version 8.0.14 

[https://github.com/alibaba/canal/issues/1660](https://github.com/alibaba/canal/issues/1660)

1.1.3修复了mysql8的密码认证,但偶尔还是会报错,具体原因待探讨

```
2019-04-14 16:49:36.188 [destination = example , address = /192.183.3.109:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address /192.183.3.109:3306 has an error, retrying. caused by
com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: connect /192.183.3.109:3306 failure
Caused by: java.io.IOException: connect /192.183.3.109:3306 failure
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:83) ~[canal.parse.driver-1.1.3.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.connect(MysqlConnection.java:89) ~[canal.parse-1.1.3.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.preDump(MysqlEventParser.java:86) ~[canal.parse-1.1.3.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:175) ~[canal.parse-1.1.3.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_201]
Caused by: java.io.IOException: caching_sha2_password Auth failed
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.negotiate(MysqlConnector.java:257) ~[canal.parse.driver-1.1.3.jar:na]
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:80) ~[canal.parse.driver-1.1.3.jar:na]
	... 4 common frames omitted
2019-04-14 16:49:36.190 [destination = example , address = /192.183.3.109:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: connect /192.183.3.109:3306 failure
Caused by: java.io.IOException: connect /192.183.3.109:3306 failure
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:83)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.connect(MysqlConnection.java:89)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.preDump(MysqlEventParser.java:86)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:175)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: caching_sha2_password Auth failed
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.negotiate(MysqlConnector.java:257)
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:80)
	... 4 more
```

**Comment by agapple** [comment]
可以跑下MysqlConnectorTest，尝试tcpdump抓一下包

**Comment by windyyong** [comment]
> 可以跑下MysqlConnectorTest，尝试tcpdump抓一下包

好,我再试下

**Comment by windyyong** [comment]
> 可以跑下MysqlConnectorTest，尝试tcpdump抓一下包

https://blog.csdn.net/xiaoshunzi111/article/details/52803669
楼主,你好,找到了解决方案:
```
在mysql数据库用命令
mysql -ucanal -p 登陆一次,再重新启动就可以了,可能是域名解析问题?
```

问题重现:
1、mysql、canal正常运行
2、service mysql restart 重新启动, 期间没有关闭canal
3、mysql重启成功后,重新启动canal,报上述错误
**备注:mysql和canal都在同一台机器的局域网上,ip为192.183.3.109**

报上述异常的时候,自己尝试抓了包,

```
tcpdump tcp port 11111 and host 192.183.3.109
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 65535 bytes
```
显示如下,期间也没有显示信息

**Comment by agapple** [comment]
@windyyong 从你给的csdn链接来看，这是属于原生密码不对么？

**Comment by windyyong** [comment]
> @windyyong 从你给的csdn链接来看，这是属于原生密码不对么？

密码是对的,有可能是host映射问题,我用的IP是192.183.3.109,可能没有映射成功吧

**Comment by windyyong** [comment]
> @windyyong 从你给的csdn链接来看，这是属于原生密码不对么？

这个问题我重启mysql还是会提示,只要在本地用mysql -ucanal -p登陆一次就好了

**Comment by zhang530** [comment]
修改密码永不过期解决

ALTER USER 'canal'@'%' IDENTIFIED BY 'canal' PASSWORD EXPIRE NEVER;
ALTER USER 'canal'@'%' IDENTIFIED WITH mysql_native_password BY 'canal';
FLUSH PRIVILEGES;

**Comment by KaimingWan** [comment]
当client连接mysql，出错次数过多超过max_connection_errors配置的值时，会有caching_sha2_password Auth failed的报错。可以在mysql server执行下flush hosts来恢复特定ip的连接。

mysql> FLUSH HOSTS;

The command uses host cache tables, if maximum number of connections has been reached for a particular host, mysql server will not able to make new connections. flushing host tables resets the process and again allows the connections for particular HOST.

官方文档参考：https://dev.mysql.com/doc/refman/8.0/en/flush.html

**Comment by sixleaves** [comment]
我靠，这到底啥原因，神奇的bug。总不该到生产环境我每次出问题还得重新登入下吧

**Comment by Xuzan9396** [comment]
真的是神奇的bug，666， 真的是采坑记

**Comment by QlDoors** [comment]
我也是本地登录一下就好了

**Comment by mouday** [comment]
果然。登录下就好了，奇怪的问题

**Comment by QlDoors** [comment]
用一个很挫的办法把这个bug绕过去了，在调用 com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect() 之前用JDBC 连一下MySQL就行了
