### ISSUE TITLE
删除性质的ddl操作，解析出错

### ISSUE THREAD

**Issue by aBlackAnt** [alibaba/canal#1708]
2019-04-16 17:37:45.764 [destination = 2 , address = /:3302 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta - parse faield : ALTER TABLE `umc_enterprise_org` DROP COLUMN `TENANT_ID`, ROW_FORMAT=DEFAULT
com.alibaba.fastsql.sql.parser.ParserException: syntax error, error in :'ID`, ROW_FORMAT=DEFAULT, pos 69, line 1, column 69, token =
	at com.alibaba.fastsql.sql.parser.SQLParser.printError(SQLParser.java:363) ~[fastsql-2.0.0_preview_644.jar:2.0.0_preview_644]
	at com.alibaba.fastsql.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:534) ~[fastsql-2.0.0_preview_644.jar:2.0.0_preview_644]
	at com.alibaba.fastsql.sql.SQLUtils.parseStatements(SQLUtils.java:525) ~[fastsql-2.0.0_preview_644.jar:2.0.0_preview_644]
	at com.alibaba.fastsql.sql.repository.SchemaRepository.console(SchemaRepository.java:439) ~[fastsql-2.0.0_preview_644.jar:2.0.0_preview_644]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta.apply(MemoryTableMeta.java:78) ~[canal.parse-1.1.2.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.applyHistoryOnMemory(DatabaseTableMeta.java:463) [canal.parse-1.1.2.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:174) [canal.parse-1.1.2.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:84) [canal.parse-1.1.2.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:192) [canal.parse-1.1.2.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65]
2019-04-16 17:37:45.765 [destination = 2 , address = /39.107.158.51:3302 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> find start position successfully, EntryPosition[included=false,journalName=mysql-bin.000003,position=327051960,serverId=100,gtid=,timestamp=1555378254000] cost : 11ms , the next step is binlog dump

sql语句：ALTER TABLE `umc_enterprise_org` DROP COLUMN `TENANT_ID`, ROW_FORMAT=DEFAULT
canal版本1.1.2，请问下，这种带删除性质的ddl操作，还是只能通过业务手段去规避，或者修改消费位点重启吗？

**Comment by agapple** [comment]
1.1.4 当前主干已修复
