### ISSUE TITLE
MemoryTableMeta - parse faield : CREATE DATABASE /*!32312 IF NOT EXISTS*/ `crm_sales` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci */

### ISSUE THREAD

**Issue by Bruce2jiang** [alibaba/canal#1710]
64001000}}
2019-04-17 09:24:18.909 [destination = oms_waybill01 , address = /10.125.18.99:3306 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.tsdb. @MemoryTableMeta - parse faield : CREATE DATABASE /*!32312 IF NOT EXISTS*/ `crm_sales` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci */
com.alibaba.fastsql.sql.parser.ParserException: illegal name, pos 40, line 1, column 17, token HINT
        at com.alibaba.fastsql.sql.parser.SQLExprParser.name(SQLExprParser.java:1750) ~[fastsql-2.0.0_preview_836.jar:2.0.0_preview_836]
        at com.alibaba.fastsql.sql.dialect.mysql.parser.MySqlStatementParser.parseCreateDatabase(MySqlStatementParser.java:6501) ~[fastsql-2.0.0_preview_836.jar:2.0.0_preview_836]
        at com.alibaba.fastsql.sql.dialect.mysql.parser.MySqlStatementParser.parseCreate(MySqlStatementParser.java:292) ~[fastsql-2.0.0_preview_836.jar:2.0.0_preview_836]
        at com.alibaba.fastsql.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:228) ~[fastsql-2.0.0_preview_836.jar:2.0.0_preview_836]
        at com.alibaba.fastsql.sql.SQLUtils.parseStatements(SQLUtils.java:536) ~[fastsql-2.0.0_preview_836.jar:2.0.0_preview_836]
        at com.alibaba.fastsql.sql.repository.SchemaRepository.console(SchemaRepository.java:439) ~[fastsql-2.0.0_preview_836.jar:2.0.0_preview_836]
        at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta.apply(MemoryTableMeta.java:81) ~[canal.parse-1.1.3-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.applyHistoryOnMemory(DatabaseTableMeta.java:463) [canal.parse-1.1.3-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:174) [canal.parse-1.1.3-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:106) [canal.parse-1.1.3-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:192) [canal.parse-1.1.3-SNAPSHOT.jar:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]
2019-04-17 09:24:18.909 [destination = oms_waybill01 , address = /10.125.18.99:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> find start position successfully, EntryPosition[included=false,journalName=mysql-bin.000198,position=150450942,serverId=20403,gtid=,timestamp=1555464001000] cost : 327ms , the next step is binlog dump
2019-04-17 09:52:36.638 [Thread-27] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - stop CannalInstance for null-oms_waybill01

**Comment by ailusa** [comment]
问题你解决了吗？我也遇到这样的问题了，不知道怎么解决

**Comment by Bruce2jiang** [comment]
canal不支持创建数据库

**Comment by agapple** [comment]
1.1.4 当前主干已修复

**Comment by qinxiongzhou** [comment]
遇到同样的问题。有人可以解释下原因吗

**Comment by liutao5121** [comment]
> 

我用的1.5.1，也遇到这个问题了
![image](https://user-images.githubusercontent.com/4645306/184075736-fa86ad99-8c7c-48f1-8ad9-e9c8e844ea52.png)
