### ISSUE TITLE
com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed

### ISSUE THREAD

**Issue by pc-fuqq** [alibaba/canal#1723]
## Question

RDS作为数据源就报以下错误，其他非RDS没问题，求解，谢谢。

```
*******-web-launcher: 2019-04-19 15:22:29.695 [destination = MysqlEventParserFactoryBean.destination , address = rm-bp127us***************:3306 , EventParser] ERROR com.alibaba.otter.canal.parse.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address rm-bp127us***************:3306 has an error, retrying. caused by 
com.alibaba.otter.canal.parse.exception.CanalParseException: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: java.lang.IndexOutOfBoundsException: Index: 8, Size: 8
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseOneRow(LogEventConvert.java:640)
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseRowsEvent(LogEventConvert.java:533)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$DmlParserStage.onEvent(MysqlMultiStageCoprocessor.java:330)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$DmlParserStage.onEvent(MysqlMultiStageCoprocessor.java:316)
	at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:138)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by agapple** [comment]
对应是啥版本？RDS估计有一些隐藏主键，试一下最新的版本，印象中有修复过
