### ISSUE TITLE
canal-1.1.3数据同步异常 EOF encountered

### ISSUE THREAD

**Issue by zwh201806** [alibaba/canal#1733]
instance.properties 配置开启了gtid
# enable gtid use true/false
 canal.instance.gtidon=true

ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - I/O error while reading from client socket
java.io.IOException: EOF encountered.
	at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:113) ~[canal.parse.driver-1.1.3-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:174) ~[canal.parse-1.1.3-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:77) ~[canal.parse-1.1.3-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:261) [canal.parse-1.1.3-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:250) [canal.parse-1.1.3-SNAPSHOT.jar:na]

![02406FE1-1A5C-4FB2-B312-CA225F8956E9](https://user-images.githubusercontent.com/39817441/56493899-29240d00-6523-11e9-9eef-cfdaa25b6e6d.png)

![0AEFE730-F99C-469C-AF69-E4E74997B67E](https://user-images.githubusercontent.com/39817441/56494253-3ab9e480-6524-11e9-81e0-dbb3ace1e3d6.png)

![85A1E762-2C4C-4531-A063-AF9C2690CCCA](https://user-images.githubusercontent.com/39817441/56494274-49a09700-6524-11e9-863d-9af0cf6f7551.png)
![764DCB35-9D25-4F37-9D81-6F2647CA26F7](https://user-images.githubusercontent.com/39817441/56494277-4dccb480-6524-11e9-9994-e77a4e827d8d.png)

![5974681F-674C-47F6-AC56-BDDC1E230A23](https://user-images.githubusercontent.com/39817441/56493901-2b866700-6523-11e9-93b7-80f50a2cc081.png)

这样是不是会导致数据丢失？

**Comment by agapple** [comment]
没看懂你的问题是啥

**Comment by VincentLiSH** [comment]
应该是canal订阅binlog过程 相当于是mysql向canal写数据，
当遇到了某个特别大数据量的事务（例如“create table xxx_init as select * from xxx”），mysql写超时 断开了连接，set global show variables like '%timeout'; 发现net_write_timeout默认60秒；
set global net_write_timeout=28800 改为8小时

https://blog.csdn.net/cuizhu0832/article/details/100349359
