### ISSUE TITLE
canal无法从rds oss读取binlog

### ISSUE THREAD

**Issue by WMSen** [alibaba/canal#1749]
canal版本：1.1.1
数据库版本：rds mysql5.7

ak信息是我自己子账号生成的，账号有管理rds和oss权限，数据库实例是昨天建的，我想从开始binlog拉，启动后一直报错

2019-04-25 10:52:02.934 [destination = example , address = rm-xxxxxx.mysql.rds.aliyuncs.com/172.xx.xx.xxx:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address rm-xxxxxx.mysql.rds.aliyuncs.com/172.xx.xx.xxx:3306 has an error, retrying. caused by 
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102) ~[canal.parse-1.1.1.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:216) ~[canal.parse-1.1.1.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:252) ~[canal.parse-1.1.1.jar:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]

配置如下
canal.instance.mysql.slaveId= 14321

# enable gtid use true/false
canal.instance.gtidon=false

# position info
canal.instance.master.address=rm-xxxxxx.mysql.rds.aliyuncs.com:3306
canal.instance.master.journal.name=mysql-bin.000001
canal.instance.master.position=4
#canal.instance.master.timestamp=
#canal.instance.master.gtid=

# rds oss binlog
canal.instance.rds.accesskey=xxxxxx
canal.instance.rds.secretkey=xxxxxx
canal.instance.rds.instanceId=rm-xxxxxx

# table meta tsdb info
canal.instance.tsdb.enable=true

# username/password
canal.instance.dbUsername=xxx
canal.instance.dbPassword=xxx
canal.instance.connectionCharset = UTF-8
# enable druid Decrypt database password
canal.instance.enableDruid=false

# table regex
canal.instance.filter.regex=xxx\\..*

**Comment by WMSen** [comment]
哪位大神能解释下，到底咋配置啊

**Comment by agapple** [comment]
如果要回溯昨天的, 按照timestamp配置, 不要配置具体的位点

**Comment by nothing-do** [comment]
您好，配置timestamp解决您的问题了吗

**Comment by liguobao** [comment]
我这边配置了时间戳和OSS key ，还是不能从OSS中获取到对应的文件，看日志依旧从数据库中获取的binlog
