### ISSUE TITLE
1.1.2 tag解析mysql 5.5.35异常

### ISSUE THREAD

**Issue by wujiamail** [alibaba/canal#1783]
### environment

* canal version
1.1.2
* mysql version
5.5.35
### Issue Description
解析 table map类型的bin log,
在TableMapLogEvent类425行左右，注释为：After null_bits field, there are some new fields for extra metadata
1.1.0是可以解析的，通过和1.1.0的代码对比，optional metadata fields解析导致的问题
![image](https://user-images.githubusercontent.com/4240896/57208573-276c4600-7007-11e9-8744-f44184c389dc.png)

    default:
         throw new IllegalArgumentException("unknow type : " + type);

会进入default代码块，把throw 修改为logger.error后，

13:37:20.053 [main] ERROR c.taobao.tddl.dbsync.binlog.LogEvent - unknow type :24
13:37:23.962 [main] ERROR c.taobao.tddl.dbsync.binlog.LogEvent - unknow type :0
13:37:26.991 [main] ERROR c.taobao.tddl.dbsync.binlog.LogEvent - unknow type :35
13:37:28.730 [main] ERROR c.taobao.tddl.dbsync.binlog.LogEvent - unknow type :41
14:00:26.807 [main] ERROR c.taobao.tddl.dbsync.binlog.LogEvent - unknow type :41
14:00:33.708 [main] ERROR c.taobao.tddl.dbsync.binlog.LogEvent - unknow type :114
14:00:34.435 [main] ERROR c.taobao.tddl.dbsync.binlog.LogEvent - unknow type :95
14:00:35.139 [main] ERROR c.taobao.tddl.dbsync.binlog.LogEvent - unknow type :100
java.lang.IllegalArgumentException: limit excceed: 1199
	at com.taobao.tddl.dbsync.binlog.LogBuffer.getUint8(LogBuffer.java:235)
	at com.taobao.tddl.dbsync.binlog.LogBuffer.getPackedLong(LogBuffer.java:1024)
	at com.taobao.tddl.dbsync.binlog.event.TableMapLogEvent.parse_set_str_value(TableMapLogEvent.java:644)
	at com.taobao.tddl.dbsync.binlog.event.TableMapLogEvent.<init>(TableMapLogEvent.java:447)
	at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:182)
	at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:111)
	at com.taobao.tddl.dbsync.binlog.FileLogFetcherTest.testSimple(FileLogFetcherTest.java:44)

**Comment by agapple** [comment]
尝试一下最新的代码，代码行有点对不齐

**Comment by OursLee** [comment]
otter下遇到同样的问题
