### ISSUE TITLE
canal - 1.1.4-SNAPSHOT 连接MYSQL报NullPointerException错误，MysqlMultiStageCoprocessor

### ISSUE THREAD

**Issue by slashchenxiaojun** [alibaba/canal#1786]
canal-server正常启动，但是会隔间报NullPointerException

2019-05-07 21:50:45.941 [destination = 100018 , address = /192.168.1.10:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:100018[com.alibaba.otter.canal.parse.exception.CanalParseException: java.lang.NullPointerException
Caused by: java.lang.NullPointerException
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SinkStoreStage.onEvent(MysqlMultiStageCoprocessor.java:361)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SinkStoreStage.onEvent(MysqlMultiStageCoprocessor.java:352)
	at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

之后canal-server又会重新连接mysql-master，不断重复以下的异常

2019-05-07 21:50:45.943 [destination = 100018 , address = /192.168.1.10:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - disConnect MysqlConnection to /192.168.1.10:3306...
2019-05-07 21:50:45.944 [destination = 100018 , address = /192.168.1.10:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - disConnect MysqlConnection to /192.168.1.10:3306...
2019-05-07 21:50:45.947 [destination = 100018 , address = /192.168.1.10:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - connect MysqlConnection to /192.168.1.10:3306...
2019-05-07 21:50:45.950 [destination = 100018 , address = /192.168.1.10:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - handshake initialization packet received, prepare the client authentication packet to send
2019-05-07 21:50:45.950 [destination = 100018 , address = /192.168.1.10:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - client authentication packet is sent out.
2019-05-07 21:50:45.956 [destination = 100018 , address = /192.168.1.10:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - disConnect MysqlConnection to /192.168.1.10:3306...
2019-05-07 21:50:59.004 [destination = 100018 , address = /192.168.1.10:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - connect MysqlConnection to /192.168.1.10:3306...
2019-05-07 21:50:59.006 [destination = 100018 , address = /192.168.1.10:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - handshake initialization packet received, prepare the client authentication packet to send
2019-05-07 21:50:59.007 [destination = 100018 , address = /192.168.1.10:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - client authentication packet is sent out.
2019-05-07 21:50:59.024 [destination = 100018 , address = /192.168.1.10:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - connect MysqlConnection to /192.168.1.10:3306...
2019-05-07 21:50:59.026 [destination = 100018 , address = /192.168.1.10:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - handshake initialization packet received, prepare the client authentication packet to send
2019-05-07 21:50:59.026 [destination = 100018 , address = /192.168.1.10:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - client authentication packet is sent out.
2019-05-07 21:50:59.032 [destination = 100018 , address = /192.168.1.10:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> begin to find start position, it will be long time for reset or first position
2019-05-07 21:50:59.032 [destination = 100018 , address = /192.168.1.10:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - prepare to find start position just last position
 {"identity":{"slaveId":-1,"sourceAddress":{"address":"192.168.1.10","port":3306}},"postion":{"included":false,"journalName":"mysql-bin.000009","position":10821579,"timestamp":1557222361000}}
2019-05-07 21:50:59.071 [destination = 100018 , address = /192.168.1.10:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> find start position successfully, EntryPosition[included=false,journalName=mysql-bin.000009,position=10821579,serverId=<null>,gtid=<null>,timestamp=1557222361000] cost : 39ms , the next step is binlog dump
2019-05-07 21:50:59.073 [destination = 100018 , address = /192.168.1.10:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - disConnect MysqlConnection to /192.168.1.10:3306...
2019-05-07 21:50:59.075 [destination = 100018 , address = /192.168.1.10:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - connect MysqlConnection to /192.168.1.10:3306...
2019-05-07 21:50:59.078 [destination = 100018 , address = /192.168.1.10:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - handshake initialization packet received, prepare the client authentication packet to send
2019-05-07 21:50:59.079 [destination = 100018 , address = /192.168.1.10:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - client authentication packet is sent out.
2019-05-07 21:50:59.105 [destination = 100018 , address = /192.168.1.10:3306 , EventParser] INFO  c.a.otter.canal.parse.inbound.mysql.MysqlConnection - Register slave RegisterSlaveCommandPacket[reportHost=192.168.11.91,reportPort=52343,reportUser=dipper,reportPasswd=ide@123,serverId=100018,command=21]
2019-05-07 21:50:59.109 [destination = 100018 , address = /192.168.1.10:3306 , EventParser] INFO  c.a.otter.canal.parse.inbound.mysql.MysqlConnection - COM_BINLOG_DUMP with position:BinlogDumpCommandPacket[binlogPosition=10821579,slaveServerId=100018,binlogFileName=mysql-bin.000009,command=18]
2019-05-07 21:50:59.111 [MultiStageCoprocessor-other-100018-0] INFO  com.taobao.tddl.dbsync.binlog.LogEvent - common_header_len= 19, number_of_event_types= 35
2019-05-07 21:51:14.113 [destination = 100018 , address = /192.168.1.10:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address /192.168.1.10:3306 has an error, retrying. caused by 
com.alibaba.otter.canal.parse.exception.CanalParseException: java.lang.NullPointerException
Caused by: java.lang.NullPointerException: null
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SinkStoreStage.onEvent(MysqlMultiStageCoprocessor.java:361) ~[canal.parse-1.1.4-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SinkStoreStage.onEvent(MysqlMultiStageCoprocessor.java:352) ~[canal.parse-1.1.4-SNAPSHOT.jar:na]
	at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168) ~[disruptor-3.4.2.jar:na]
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125) ~[disruptor-3.4.2.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_201]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_201]
2019-05-07 21:51:14.118 [destination = 100018 , address = /192.168.1.10:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:100018[com.alibaba.otter.canal.parse.exception.CanalParseException: java.lang.NullPointerException
Caused by: java.lang.NullPointerException
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SinkStoreStage.onEvent(MysqlMultiStageCoprocessor.java:361)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SinkStoreStage.onEvent(MysqlMultiStageCoprocessor.java:352)
	at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by suhuaguo** [comment]
后来这个问题解决了嘛？

**Comment by suhuaguo** [comment]
这个问题，我基本查明白了，是因为 mysql 提交事务的客户端设置的字符集是 255 ，导致链接不断释放、重连。这种空指针类似抽风一样。
