### ISSUE TITLE
Can't read dir of './performance_schema/' (errno: 13 - Permission denied),

### ISSUE THREAD

**Issue by maxiaoxian** [alibaba/canal#1792]
ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:fc-sales[com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: ErrorPacket [errorNumber=1018, fieldCount=-1, message=Can't read dir of './performance_schema/' (errno: 13 - Permission denied), sqlState=HY000, sqlStateMarker=#]
 with command: show full tables from `performance_schema` where Table_type = 'BASE TABLE'
Caused by: java.io.IOException: ErrorPacket [errorNumber=1018, fieldCount=-1, message=Can't read dir of './performance_schema/' (errno: 13 - Permission denied), sqlState=HY000, sqlStateMarker=#]
 with command: show full tables from `performance_schema` where Table_type = 'BASE TABLE'
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlQueryExecutor.query(MysqlQueryExecutor.java:61)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.query(MysqlConnection.java:106)
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.dumpTableMeta(DatabaseTableMeta.java:207)
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:180)
	at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:106)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:192)
	at java.lang.Thread.run(Thread.java:722)

**Comment by maxiaoxian** [comment]
已经按文档授权了。

**Comment by Moexi2019** [comment]
但是为什么要读performance_schema这个库的权限？

**Comment by Moexi2019** [comment]
![image](https://github.com/user-attachments/assets/01560239-2b1b-4dc6-a1e0-8d5b6468ac8c)
一样的报错
