### ISSUE TITLE
ERROR com.alibaba.otter.canal.rocketmq.CanalRocketMQProducer - send flat message to fixed partition error org.apache.rocketmq.client.exception.MQClientException: The specified topic is blank

### ISSUE THREAD

**Issue by JornTang** [alibaba/canal#1799]
canal 版本1.13
RocketMQ V4.5.0
环境：windows10

当canal设置canal.mq.dynamicTopic动态主题时直接报以下错误。
检查了RocketMQ 在启动时是开启了主题可自动创建
![image](https://user-images.githubusercontent.com/30253786/57564343-f3b16780-73dc-11e9-81a8-6d31d8a5e402.png)

2019-05-11 10:45:47.339 [main] INFO  com.alibaba.otter.canal.deployer.CanalStater - ## the canal server is running now ......
2019-05-11 10:45:47.351 [canal-instance-scan-0] INFO  c.a.o.canal.deployer.monitor.SpringInstanceConfigMonitor - auto notify stop metrics successful.
2019-05-11 10:45:48.346 [pool-6-thread-1] ERROR com.alibaba.otter.canal.rocketmq.CanalRocketMQProducer - send flat message to fixed partition error
org.apache.rocketmq.client.exception.MQClientException: The specified topic is blank
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
	at org.apache.rocketmq.client.Validators.checkTopic(Validators.java:108) ~[rocketmq-client-4.3.0.jar:na]
	at org.apache.rocketmq.client.Validators.checkMessage(Validators.java:86) ~[rocketmq-client-4.3.0.jar:na]
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendSelectImpl(DefaultMQProducerImpl.java:918) ~[rocketmq-client-4.3.0.jar:na]
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:907) ~[rocketmq-client-4.3.0.jar:na]
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:902) ~[rocketmq-client-4.3.0.jar:na]
	at org.apache.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:393) ~[rocketmq-client-4.3.0.jar:na]
	at com.alibaba.otter.canal.rocketmq.CanalRocketMQProducer.send(CanalRocketMQProducer.java:197) [canal.server-1.1.3.jar:na]
	at com.alibaba.otter.canal.rocketmq.CanalRocketMQProducer.send(CanalRocketMQProducer.java:72) [canal.server-1.1.3.jar:na]
	at com.alibaba.otter.canal.server.CanalMQStarter.worker(CanalMQStarter.java:182) [canal.server-1.1.3.jar:na]
	at com.alibaba.otter.canal.server.CanalMQStarter.access$500(CanalMQStarter.java:22) [canal.server-1.1.3.jar:na]
	at com.alibaba.otter.canal.server.CanalMQStarter$CanalMQRunnable.run(CanalMQStarter.java:224) [canal.server-1.1.3.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_92]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_92]

**Comment by chenxyz707** [comment]
在原来动态topic不变的基础上，设置`canal.mq.topic`试一试呢。在使用Kafka的时候会有找不到分区的提示，设置一个默认的topic就好了。
