### ISSUE TITLE
CanalConnectors.newClusterConnector zk failover问题

### ISSUE THREAD

**Issue by BrightMi** [alibaba/canal#180]
CanalConnectors.newClusterConnector
用zk的时候报这个错误
new ClusterNodeAccessStrategy() 的时候clusterPath没有create
zkClient.getChildren这个方法报错

Exception in thread "main" org.I0Itec.zkclient.exception.ZkNoNodeException: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /otter/canal/destinations/192.168.2.2:3306/cluster
    at org.I0Itec.zkclient.exception.ZkException.create(ZkException.java:47)
    at org.I0Itec.zkclient.ZkClient.retryUntilConnected(ZkClient.java:685)
    at org.I0Itec.zkclient.ZkClient.getChildren(ZkClient.java:413)
    at org.I0Itec.zkclient.ZkClient.getChildren(ZkClient.java:409)
    at com.alibaba.otter.canal.client.impl.ClusterNodeAccessStrategy.<init>(ClusterNodeAccessStrategy.java:58)
    at com.alibaba.otter.canal.client.CanalConnectors.newClusterConnector(CanalConnectors.java:69)
    at com.alibaba.otter.canal.example.ClusterCanalClientTest.main(ClusterCanalClientTest.java:31)

**Comment by agapple** [comment]
服务端有没启动？
