### ISSUE TITLE
client是否支持多个zk节点同步到一个库

### ISSUE THREAD

**Issue by acuitong** [alibaba/canal#1809]
目前需要client多个zk节点同步到一个库，application.yml配置
![image](https://user-images.githubusercontent.com/40566190/57742678-c1617c00-76f4-11e9-906b-5c064fa81522.png)
第一次同步的时候还行，换个库同步就会出现
2019-05-14 19:12:21.086 ERROR 3420 --- [pool-9-thread-1] c.a.o.c.a.l.loader.CanalAdapterWorker    : java.lang.RuntimeException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: Target column: id not matched

java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: Target column: id not matched
	at com.alibaba.otter.canal.client.adapter.rdb.RdbAdapter.sync(RdbAdapter.java:171) ~[na:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.batchSync(AbstractCanalAdapterWorker.java:198) ~[client-adapter.launcher-1.1.3-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$1(AbstractCanalAdapterWorker.java:62) ~[client-adapter.launcher-1.1.3-SNAPSHOT.jar:na]
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[na:1.8.0_65]
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$2(AbstractCanalAdapterWorker.java:58) ~[client-adapter.launcher-1.1.3-SNAPSHOT.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_65]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_65]
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: Target column: id not matched
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.sync(RdbSyncService.java:175) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.sync(RdbSyncService.java:187) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.rdb.RdbAdapter.sync(RdbAdapter.java:166) ~[na:na]
	... 8 common frames omitted
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: Target column: id not matched
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$sync$2(RdbSyncService.java:170) ~[na:na]
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[na:1.8.0_65]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.sync(RdbSyncService.java:166) ~[na:na]
	... 10 common frames omitted
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: Target column: id not matched
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_65]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_65]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$sync$2(RdbSyncService.java:168) ~[na:na]
	... 12 common frames omitted
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Target column: id not matched
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$sync$1(RdbSyncService.java:161) ~[na:na]
	... 4 common frames omitted
Caused by: java.lang.RuntimeException: Target column: id not matched
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.appendCondition(RdbSyncService.java:558) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.appendCondition(RdbSyncService.java:539) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.delete(RdbSyncService.java:482) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.sync(RdbSyncService.java:294) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$null$0(RdbSyncService.java:153) ~[na:na]
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[na:1.8.0_65]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$sync$1(RdbSyncService.java:153) ~[na:na]
	... 4 common frames omitted
是否是applicatin.yml配置的问题

**Comment by lklkxcxc** [comment]
你的这个问题解决了吗？我也碰到了Target column: id not matched
