### ISSUE TITLE
Canal投递MQ失败后无限重试

### ISSUE THREAD

**Issue by cjk87927** [alibaba/canal#1822]
- canal version
 v1.1.3
- MQ: 
 RocketMQ 4.2
- MySQL version: 
 10.0.20-MariaDB

- MQ Config
```
canal.serverMode = RocketMQ

canal.mq.servers = xxx:9876;yyyy:9876
canal.mq.retries = 1
canal.mq.batchSize = 16384
canal.mq.maxRequestSize = 1048576
canal.mq.lingerMs = 100
canal.mq.bufferMemory = 33554432
canal.mq.producerGroup = Canal-Producer
canal.mq.canalBatchSize = 50
canal.mq.canalGetTimeout = 100
canal.mq.flatMessage = false
canal.mq.compressionType = none
canal.mq.acks = all
```

- 失败原因
表内某个字段过大,超过RocketMQ配置的消息最大值,导致投递失败

- Exception
```
2019-05-18 10:03:01.690 [pool-30-thread-4] ERROR com.alibaba.otter.canal.rocketmq.CanalRocketMQProducer - send flat message to hashed partition error
org.apache.rocketmq.client.exception.MQClientException: CODE: 13  DESC: the message body size over max value, MAX: 4194304
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
	at org.apache.rocketmq.client.Validators.checkMessage(Validators.java:98) ~[rocketmq-client-4.3.0.jar:na]
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendSelectImpl(DefaultMQProducerImpl.java:918) ~[rocketmq-client-4.3.0.jar:na]
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:907) ~[rocketmq-client-4.3.0.jar:na]
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:902) ~[rocketmq-client-4.3.0.jar:na]
	at org.apache.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:393) ~[rocketmq-client-4.3.0.jar:na]
	at com.alibaba.otter.canal.rocketmq.CanalRocketMQProducer.send(CanalRocketMQProducer.java:105) [canal.server-1.1.3.jar:na]
	at com.alibaba.otter.canal.rocketmq.CanalRocketMQProducer.send(CanalRocketMQProducer.java:72) [canal.server-1.1.3.jar:na]
	at com.alibaba.otter.canal.server.CanalMQStarter.worker(CanalMQStarter.java:182) [canal.server-1.1.3.jar:na]
	at com.alibaba.otter.canal.server.CanalMQStarter.access$500(CanalMQStarter.java:22) [canal.server-1.1.3.jar:na]
	at com.alibaba.otter.canal.server.CanalMQStarter$CanalMQRunnable.run(CanalMQStarter.java:224) [canal.server-1.1.3.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
2019-05-18 10:03:01.691 [pool-30-thread-4] ERROR com.alibaba.otter.canal.rocketmq.CanalRocketMQProducer - Send message error!
org.apache.rocketmq.client.exception.MQClientException: CODE: 13  DESC: the message body size over max value, MAX: 4194304
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
	at org.apache.rocketmq.client.Validators.checkMessage(Validators.java:98) ~[rocketmq-client-4.3.0.jar:na]
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendSelectImpl(DefaultMQProducerImpl.java:918) ~[rocketmq-client-4.3.0.jar:na]
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:907) ~[rocketmq-client-4.3.0.jar:na]
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:902) ~[rocketmq-client-4.3.0.jar:na]
	at org.apache.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:393) ~[rocketmq-client-4.3.0.jar:na]
	at com.alibaba.otter.canal.rocketmq.CanalRocketMQProducer.send(CanalRocketMQProducer.java:105) [canal.server-1.1.3.jar:na]
	at com.alibaba.otter.canal.rocketmq.CanalRocketMQProducer.send(CanalRocketMQProducer.java:72) [canal.server-1.1.3.jar:na]
	at com.alibaba.otter.canal.server.CanalMQStarter.worker(CanalMQStarter.java:182) [canal.server-1.1.3.jar:na]
	at com.alibaba.otter.canal.server.CanalMQStarter.access$500(CanalMQStarter.java:22) [canal.server-1.1.3.jar:na]
	at com.alibaba.otter.canal.server.CanalMQStarter$CanalMQRunnable.run(CanalMQStarter.java:224) [canal.server-1.1.3.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
```

- 建议增加
 1. Canal投递失败次数限制(canal.mq.retries仅限制MQ失败次数,无法限制Canal失败次数,Canal失败后还是会rollback batchId)
 2. 允许配置投递表的具体字段,剔除过大字段

**Comment by agapple** [comment]
针对过大字段问题，可以考虑提交一个PR给我

**Comment by cjk87927** [comment]
@agapple com.alibaba.fastsql:fastsql:jar:2.0.0_preview_914无法下载导致构建检查失败

**Comment by cjk87927** [comment]
#1914

**Comment by guwenxiang** [comment]
@cjk87927 你好呀,这个问题你解决了吗
