### ISSUE TITLE
OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by luqi000** [alibaba/canal#1823]
## Question

各路大神，出现如下的问题，请问有没有解决的方法，谢谢！
2019-05-20 11:12:20.067 [main] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Loading properties file from class path resource [canal.properties]
2019-05-20 11:12:20.074 [main] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Loading properties file from class path resource [example/instance.properties]
2019-05-20 11:12:20.313 [main] WARN  o.s.beans.GenericTypeAwarePropertyDescriptor - Invalid JavaBean property 'connectionCharset' being accessed! Ambiguous write methods found next to actually used [public void com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.setConnectionCharset(java.nio.charset.Charset)]: [public void com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.setConnectionCharset(java.lang.String)]
2019-05-20 11:12:20.388 [main] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Loading properties file from class path resource [canal.properties]
2019-05-20 11:12:20.388 [main] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Loading properties file from class path resource [example/instance.properties]
2019-05-20 11:12:20.644 [main] ERROR com.alibaba.druid.pool.DruidDataSource - testWhileIdle is true, validationQuery not set
2019-05-20 11:12:21.006 [main] INFO  c.a.otter.canal.instance.spring.CanalInstanceWithSpring - start CannalInstance for 1-example 
2019-05-20 11:12:21.018 [main] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table filter : 
2019-05-20 11:12:21.018 [main] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table black filter : 
2019-05-20 11:12:21.031 [main] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - start successful....
2019-05-20 11:12:21.130 [destination = example , address = /127.0.0.1:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> begin to find start position, it will be long time for reset or first position
2019-05-20 11:12:21.425 [destination = example , address = /127.0.0.1:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - prepare to find start position mysql-bin.000001:1892985:1558321853000
2019-05-20 11:12:43.150 [main] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Loading properties file from class path resource [canal.properties]
2019-05-20 11:12:43.157 [main] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Loading properties file from class path resource [example/instance.properties]
2019-05-20 11:12:43.441 [main] WARN  o.s.beans.GenericTypeAwarePropertyDescriptor - Invalid JavaBean property 'connectionCharset' being accessed! Ambiguous write methods found next to actually used [public void com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.setConnectionCharset(java.lang.String)]: [public void com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.setConnectionCharset(java.nio.charset.Charset)]
2019-05-20 11:12:43.531 [main] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Loading properties file from class path resource [canal.properties]
2019-05-20 11:12:43.532 [main] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Loading properties file from class path resource [example/instance.properties]
2019-05-20 11:12:43.834 [main] ERROR com.alibaba.druid.pool.DruidDataSource - testWhileIdle is true, validationQuery not set
2019-05-20 11:12:44.253 [main] INFO  c.a.otter.canal.instance.spring.CanalInstanceWithSpring - start CannalInstance for 1-example 
2019-05-20 11:12:44.262 [main] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table filter : 
2019-05-20 11:12:44.262 [main] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table black filter : 
2019-05-20 11:12:44.271 [main] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - start successful....
2019-05-20 11:12:44.366 [destination = example , address = /127.0.0.1:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> begin to find start position, it will be long time for reset or first position
2019-05-20 11:12:44.633 [destination = example , address = /127.0.0.1:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - prepare to find start position mysql-bin.000001:1892985:1558321853000
2019-05-20 11:13:34.559 [destination = example , address = /127.0.0.1:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address /127.0.0.1:3306 has an error, retrying. caused by 
java.lang.OutOfMemoryError: Java heap space
	at com.alibaba.fastjson.serializer.SerializeWriter.expandCapacity(SerializeWriter.java:250) ~[fastjson-1.2.28.jar:na]
	at com.alibaba.fastjson.serializer.SerializeWriter.writeStringWithDoubleQuote(SerializeWriter.java:779) ~[fastjson-1.2.28.jar:na]
	at com.alibaba.fastjson.serializer.SerializeWriter.writeString(SerializeWriter.java:1648) ~[fastjson-1.2.28.jar:na]
	at com.alibaba.fastjson.serializer.StringCodec.write(StringCodec.java:46) ~[fastjson-1.2.28.jar:na]
	at com.alibaba.fastjson.serializer.StringCodec.write(StringCodec.java:35) ~[fastjson-1.2.28.jar:na]
	at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:243) ~[fastjson-1.2.28.jar:na]
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:275) ~[fastjson-1.2.28.jar:na]
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:648) ~[fastjson-1.2.28.jar:na]
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:590) ~[fastjson-1.2.28.jar:na]
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:555) ~[fastjson-1.2.28.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.applySnapshotToDB(DatabaseTableMeta.java:333) ~[canal.parse-1.1.3.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:182) ~[canal.parse-1.1.3.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:106) ~[canal.parse-1.1.3.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:192) ~[canal.parse-1.1.3.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]
2019-05-20 11:13:34.573 [destination = example , address = /127.0.0.1:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[java.lang.OutOfMemoryError: Java heap space
	at com.alibaba.fastjson.serializer.SerializeWriter.expandCapacity(SerializeWriter.java:250)
	at com.alibaba.fastjson.serializer.SerializeWriter.writeStringWithDoubleQuote(SerializeWriter.java:779)
	at com.alibaba.fastjson.serializer.SerializeWriter.writeString(SerializeWriter.java:1648)
	at com.alibaba.fastjson.serializer.StringCodec.write(StringCodec.java:46)
	at com.alibaba.fastjson.serializer.StringCodec.write(StringCodec.java:35)
	at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:243)
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:275)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:648)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:590)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:555)
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.applySnapshotToDB(DatabaseTableMeta.java:333)
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:182)
	at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:106)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:192)
	at java.lang.Thread.run(Thread.java:748)
]

**Comment by luqi000** [comment]
不知道是不是缓存什么的原因，连接了其他的 mysql 就 ok 了

**Comment by agapple** [comment]
你这里订阅的表有多少？看着像是表数量过大导致了OOM

**Comment by wzjeff** [comment]
订阅的表数量太多导致的，求解决办法

**Comment by codeshan** [comment]
相同问题，怎么解决的？
