### ISSUE TITLE
canal.destinations NullPointerException

### ISSUE THREAD

**Issue by czy006** [alibaba/canal#1837]
## Question
启动报错，版本 canal1.1.3
配置文件：
canal.properties
##################################################
##################################################
canal.serverMode = kafka
canal.mq.servers = 10.17.172.121:9092,10.17.172.122:9092,10.17.172.123:9092
canal.mq.retries = 3
canal.mq.batchSize = 16384
canal.mq.maxRequestSize = 1048576
canal.mq.lingerMs = 1
canal.mq.bufferMemory = 33554432
canal.mq.canalBatchSize = 50
canal.mq.canalGetTimeout = 100
canal.mq.flatMessage = false
canal.mq.compressionType = none
canal.mq.acks = all
######### use transaction for kafka flatMessage batch produce
canal.mq.transaction = false

报错：

2019-05-23 11:13:32.446 [main] ERROR com.alibaba.otter.canal.deployer.CanalLauncher - ## Something goes wrong when starting up the canal Server:
java.lang.NullPointerException: null
	at com.alibaba.otter.canal.deployer.CanalController.parseInstanceConfig(CanalController.java:396) ~[canal.deployer-1.1.3.jar:na]
	at com.alibaba.otter.canal.deployer.CanalController.initInstanceConfig(CanalController.java:374) ~[canal.deployer-1.1.3.jar:na]
	at com.alibaba.otter.canal.deployer.CanalController.<init>(CanalController.java:90) ~[canal.deployer-1.1.3.jar:na]
	at com.alibaba.otter.canal.deployer.CanalStater.start(CanalStater.java:90) ~[canal.deployer-1.1.3.jar:na]
	at com.alibaba.otter.canal.deployer.CanalLauncher.main(CanalLauncher.java:57) ~[canal.deployer-1.1.3.jar:na]

CANAL_DESTINATIONS 参数为空？
|参数名字	|参数说明	|默认值|
| ------------- |:-------------😐 -----😐
|canal.destinations|	当前server上部署的instance列表|	无

然后按照案例 启动都启动不来...

**Comment by czy006** [comment]
java.lang.NullPointerException: null
	at java.util.Hashtable.put(Hashtable.java:460) ~[na:1.8.0_211]
	at java.util.Properties.setProperty(Properties.java:166) ~[na:1.8.0_211]
	at java.lang.System.setProperty(System.java:796) ~[na:1.8.0_211]
	at com.alibaba.otter.canal.deployer.CanalStater.start(CanalStater.java:85) ~[canal.deployer-1.1.3.jar:na]
	at com.alibaba.otter.canal.deployer.CanalLauncher.main(CanalLauncher.java:57) ~[canal.deployer-1.1.3.jar:na]

**Comment by agapple** [comment]
不要随意改动配置文件，按照默认自带的canal.properties
