### ISSUE TITLE
删除表的问题

### ISSUE THREAD

**Issue by BrightMi** [alibaba/canal#184]
在遇到表删除后会有这种情况
Caused by: java.io.IOException: ErrorPacket [errorNumber=1146, fieldCount=-1, message=Table 'secooOrderWriter1DB.t_increment_sequence_bak' doesn't exist, sqlState=42S02, sqlStateMarker=#]
 with command: desc `orderDB`.`t_increment_sequence_bak`
    at com.alibaba.otter.canal.parse.driver.mysql.MysqlQueryExecutor.query(MysqlQueryExecutor.java:60) ~[canal.parse.driver-1.0.21.jar:na]
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.query(MysqlConnection.java:69) ~[canal.parse-1.0.21.jar:na]
    at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.TableMetaCache.getTableMeta0(TableMetaCache.java:97) ~[canal.parse-1.0.21.jar:na]
    at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.TableMetaCache.access$000(TableMetaCache.java:26) ~[canal.parse-1.0.21.jar:na]
    at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.TableMetaCache$1.apply(TableMetaCache.java:50) ~[canal.parse-1.0.21.jar:na]
    at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.TableMetaCache$1.apply(TableMetaCache.java:41) ~[canal.parse-1.0.21.jar:na]

**Comment by agapple** [comment]
翻一下历史的issue，不建议做有删除性质的DDL操作，包括删表，删字段等

**Comment by agapple** [comment]
y
