### ISSUE TITLE
使用Canal指定Position同步，同步位置点提前，重复记录导致Canal-Adapter-RDB报错阻塞

### ISSUE THREAD

**Issue by power225** [alibaba/canal#1840]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version: 1.1.3
* canal adapter rdb: 1.1.3
* mysql version:5.7.23

### Issue Description
使用Canal指定Position同步，由于Canal会将同步位置点提前（看之前的讨论提到是提前60秒、未来得及从代码端确认），会产生重复记录，进而导致Canal-Adapter-RDB报主键唯一错，阻塞复制过程

### Steps to reproduce
1.向两张表中分别插入一条数据：
insert into busi1 values (1, 'in', 'asdf', now());
insert into busi2 values (1, 'in', 'asdf', curdate());
2.使用mysqldump全量导出至目标Oracle数据库
3.根据show master status记录位置点，在canal的instance配置文件中设置对应position，本次测试position为1057
4.向一张表中插入一条数据：
insert into busi1 values (2, 'out', 'qwer', now());
5.启动canal
6.启动canal-adapter
7.检查canal-adapter日志，发现报错：
2019-05-23 15:50:22.157 [pool-8-thread-1] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: java.sql.SQLIntegrityConstraintViolationException: ORA-00001: unique constraint (TEST.PK_BUSI2) violated

java.lang.RuntimeException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: java.sql.SQLIntegrityConstraintViolationException: ORA-00001: unique constraint (TEST.PK_BUSI2) violated

        at com.alibaba.otter.canal.client.adapter.rdb.RdbAdapter.sync(RdbAdapter.java:169)
        at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.batchSync(AbstractCanalAdapterWorker.java:198)
        at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$1(AbstractCanalAdapterWorker.java:62)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$2(AbstractCanalAdapterWorker.java:58)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
8.该主键冲突会阻塞之后的busi1的第2条记录入Oracle库
9.如果去掉Oracle数据库上busi2的主键PK_BUSI2，会发现id为1的记录重复插入了两条
10.查看Canal日志：
2019-05-23 15:49:26.689 [destination = example , address = /192.168.100.25:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> find start position successfully, EntryPosition[included=false,journalName=binlog.000009,position=961,serverId=11,gtid=,timestamp=1558596932000] cost : 2919ms , the next step is binlog dump
可见，起始点提前到961，比配置文件中的位置靠前
11.分析原因疑似Canal提前位置点，导致重复记录

### Expected behaviour
1.Canal复制的起始点按照配置文件中实际制定的position执行
2.Canal复制的起始点还采用提前的方式不变，目标数据库端通过主键限制重复记录，Canal-Adapter对主键冲突错误跳过不处理，或采用类似于数据库Merge语句的功能，如存在记录则按新记录更新

### Actual behaviour
1.Canal复制的起始点比配置文件提前，导致数据重复

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by YRWRCTB** [comment]
我在使用过程中发现，使用binlog+positon指定复制点，canal会默认找指定点前一个commit或begin，启动deployer可以通过日志查看，到如下信息：,journalName=mysql-bin.000186,position=26324,serverId=3995356455,gtid=,timestamp=1554168755000] cost : 525ms , the next step is binlog dump
，所以在配置postion时应该填写需要起始点的下一个postion。

**Comment by power225** [comment]
> 我在使用过程中发现，使用binlog+positon指定复制点，canal会默认找指定点前一个commit或begin，启动deployer可以通过日志查看，到如下信息：,journalName=mysql-bin.000186,position=26324,serverId=3995356455,gtid=,timestamp=1554168755000] cost : 525ms , the next step is binlog dump
> ，所以在配置postion时应该填写需要起始点的下一个postion。

感谢指点，实验结果是canal从当前位置点（commit点）往前的begin位置点开始执行，指定该位置点之后的commit位置点是可行的，但如果恰好没有后续事务，就没法随意指定位置点了，还是有问题的

**Comment by agapple** [comment]
可以在RDB同步时忽略一下ORA-00001约束冲突报错，最新代码已修改

**Comment by wanruoyiye** [comment]
1.1.7版本还有这个错误吗？我执行也出现了这个问题，下边是日志：
2023-08-31 09:31:04.048 [destination = example , address = /192.168.0.218:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> find start position successfully, EntryPosition[included=false,journalName=mybinlog.000002,position=2911,serverId=185,gtid=,timestamp=1693299039000] cost : 646ms , the next step is binlog dump

配置中我指定的是
# position info
canal.instance.master.address=192.168.0.218:3306
canal.instance.master.journal.name=mybinlog.000002
canal.instance.master.position=3047
