### ISSUE TITLE
Canal v1.1.3 - Mysql 5.5 - Unknown system variable 'binlog_checksum'

### ISSUE THREAD

**Issue by shengmingzhu** [alibaba/canal#1850]
## Question

Canal对接Mysql 5.5时报“Unknown system variable 'binlog_checksum'”，请问这个有谁知道怎么解决吗？

**Comment by brightsong** [comment]
我也遇到了这个问题，也是mysql5.5版本
`ERROR c.a.otter.canal.parse.inbound.mysql.MysqlConnection - 
java.io.IOException: ErrorPacket [errorNumber=1193, fieldCount=-1, message=Unknown system variable 'binlog_checksum', sqlState=HY000, sqlStateMarker=#]
 with command: select @@global.binlog_checksum
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlQueryExecutor.query(MysqlQueryExecutor.java:61) ~[canal.parse.driver-1.1.3.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.query(MysqlConnection.java:106) [canal.parse-1.1.3.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.loadBinlogChecksum(MysqlConnection.java:522) [canal.parse-1.1.3.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.seek(MysqlConnection.java:124) [canal.parse-1.1.3.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findAsPerTimestampInSpecificLogFile(MysqlEventParser.java:743) [canal.parse-1.1.3.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findEndPositionWithMasterIdAndTimestamp(MysqlEventParser.java:392) [canal.parse-1.1.3.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPositionInternal(MysqlEventParser.java:447) [canal.parse-1.1.3.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPosition(MysqlEventParser.java:366) [canal.parse-1.1.3.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:186) [canal.parse-1.1.3.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_73]
2019-06-12 15:21:10.645 [destination = example , address = /192.168.206.136:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> find start position successfully, EntryPosition[included=false,journalName=mysql-bin.000079,position=4,serverId=1,gtid=<null>,timestamp=1560375617000] cost : 1662ms , the next step is binlog dump
2019-06-12 15:21:10.666 [destination = example , address = /192.168.206.136:3306 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlConnection - 
java.io.IOException: ErrorPacket [errorNumber=1193, fieldCount=-1, message=Unknown system variable 'binlog_checksum', sqlState=HY000, sqlStateMarker=#]
 with command: select @@global.binlog_checksum
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlQueryExecutor.query(MysqlQueryExecutor.java:61) ~[canal.parse.driver-1.1.3.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.query(MysqlConnection.java:106) [canal.parse-1.1.3.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.loadBinlogChecksum(MysqlConnection.java:522) [canal.parse-1.1.3.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:161) [canal.parse-1.1.3.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:271) [canal.parse-1.1.3.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_73]`

**Comment by shengmingzhu** [comment]
@brightsong canal v1.1.3 + mysql 5.5，会报上述错误，canal会自动忽略掉。在测试环境验证了一周了，暂未发现会有什么问题。

**Comment by shengmingzhu** [comment]
canal v1.1.3 + mysql 5.5，报Unknown system variable 'binlog_checksum'的情况，canal会忽略错误正常解析binlog。
