### ISSUE TITLE
Not found the mapping info of index 明明已经存在

### ISSUE THREAD

**Issue by xiaodel** [alibaba/canal#1851]
2019-05-27 11:23:37.496 [pool-2-thread-1] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - java.lang.IllegalArgumentException: Not found the mapping info of index: lezf_house
java.lang.RuntimeException: java.lang.IllegalArgumentException: Not found the mapping info of index: lezf_house
	at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.sync(ESSyncService.java:113)
	at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.sync(ESSyncService.java:61)
	at com.alibaba.otter.canal.client.adapter.es.ESAdapter.sync(ESAdapter.java:176)
	at com.alibaba.otter.canal.client.adapter.es.ESAdapter.sync(ESAdapter.java:155)
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.batchSync(AbstractCanalAdapterWorker.java:198)
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$1(AbstractCanalAdapterWorker.java:62)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$2(AbstractCanalAdapterWorker.java:58)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Not found the mapping info of index: lezf_house
	at com.alibaba.otter.canal.client.adapter.es.support.ESTemplate.getEsType(ESTemplate.java:504)
	at com.alibaba.otter.canal.client.adapter.es.support.ESTemplate.getValFromData(ESTemplate.java:340)
	at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.wholeSqlOperation(ESSyncService.java:684)
	at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.update(ESSyncService.java:309)
	at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.sync(ESSyncService.java:98)
	... 11 common frames omitted

通过名称查看本机es index列表:
lezf@lezf:~/tools/canal-adapter$ curl 'localhost:9200/_cat/indices?v'
health status index          uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   lezf_house     iQUkRXjXRLSLprYdk6gXEA   5   1       2999           20      1.7mb          1.7mb
yellow open   lezf_cd_user   Ixmsm_3FSPiTiqUVFCORqw   5   1       1091            6    198.4kb        198.4kb
yellow open   lezf_cd_common Iq_3XFHIQvSOS4NDumGmnQ   5   1      15612            0     17.9mb         17.9mb

**Comment by taixingyiji** [comment]
因为你没有创建里面的type还有字段，可以参考一下这个文章，创建好type及字段以后就可以了[增量同步mysql 数据到elasticsearch canal adapter方式(binlog)实现（从零到一超级详细全面）](https://segmentfault.com/a/1190000019066098?utm_source=tag-newest)

**Comment by 1044730317** [comment]
你应该是用了别名的方式吧。

**Comment by lttlff** [comment]
这个问题解决了么

**Comment by taixingyiji** [comment]
> 这个问题解决了么

创建好索引的type类型和字段映射，可以看下我上面的回答

**Comment by yangmingqi218** [comment]
@taixingyiji 您好，es的索引是必须要手动创建么？

**Comment by yangmingqi218** [comment]
@taixingyiji 您好，canal-adapter的application.yml可以配置多个库么，
url: jdbc:mysql://127.0.0.1:3306/db_0?useUnicode=true
我想再加一个库，比如db_1

**Comment by zhengweixiong** [comment]
> 你应该是用了别名的方式吧。

配置里不能使用索引别名么？

**Comment by MtJolzhufeng** [comment]
> 因为你没有创建里面的type还有字段，可以参考一下这个文章，创建好type及字段以后就可以了[增量同步mysql 数据到elasticsearch canal adapter方式(binlog)实现（从零到一超级详细全面）](https://segmentfault.com/a/1190000019066098?utm_source=tag-newest)

手动创建的索引，canal就是不认 Not found the mapping info of index 怎么办

**Comment by hsgmj** [comment]
> > 因为你没有创建里面的type还有字段，可以参考一下这个文章，创建好type及字段以后就可以了[增量同步mysql 数据到elasticsearch canal adapter方式(binlog)实现（从零到一超级详细全面）](https://segmentfault.com/a/1190000019066098?utm_source=tag-newest)
> 
> 手动创建的索引，canal就是不认 Not found the mapping info of index 怎么办

请问解决了吗 麻烦告知下

**Comment by yuyoyth** [comment]
我也遇到同样的问题，已经解决，原因是初次使用es，使用默认配置在win启动，只能本地host访问，canal及adapter放置在异机linux，导致根本访问不了es。这里报错应该更友好一点，直接提示连接失败

**Comment by zhilong-12138** [comment]
同样问题，我是公司网络切换，没开通es访问权限，9200端口不通
