### ISSUE TITLE
Canal v1.1.3 读取 aliyun RDS，报SocketTimeoutException

### ISSUE THREAD

**Issue by zero47** [alibaba/canal#1853]
## Question
连接的是Aliyun RDS，能联通，但经常会出现超时。使用Canal版本1.1.3
2019-05-28 11:23:50.916 [destination = example , address = rm-XXX:3306 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - Socket timeout expired, closing connection
java.net.SocketTimeoutException: Timeout occurred, failed to read total 4 bytes in 25000 milliseconds, actual read only 0 bytes
        at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:124) ~[canal.parse.driver-1.1.3.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:174) ~[canal.parse-1.1.3.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:77) ~[canal.parse-1.1.3.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:235) [canal.parse-1.1.3.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:257) [canal.parse-1.1.3.jar:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]

**Comment by zero47** [comment]
我们项目凌晨12点会有大量的数据库操作，这个时期有可能数据库高负载而超时，但canal的超时错误会从凌晨12点过几分一直报错，就算在数据库闲时也报超时错误。

**Comment by zero47** [comment]
经过测试 Canal v1.1.2 也会有这个问题

**Comment by leiwangouc** [comment]
我也遇到了这个问题。产生这个错误以后 又以这个 binlog 文件从同开始

**Comment by zero47** [comment]
会不会是因为 binlog 太大呢？

**Comment by agapple** [comment]
Socket timeout主要是指25秒收不到mysql推送的binlog，在这种情况一般是mysql有问题或者一直没有binlog

**Comment by zero47** [comment]
但我每次删除 meta.dat 文件就能恢复正常

**Comment by zhiyuan192shine** [comment]
> 但我每次删除 meta.dat 文件就能恢复正常

除了这种方式，和开启心跳SQL，还有其他方式吗

**Comment by geeyan** [comment]
同问，在master mysql里执行 show processlist 可见 Binlog Dump 在 sending to slave，每隔25秒一次EXCEPTION日志。
只有停下channel, 修改pipeline, 删除position重新开始才能正常。
