### ISSUE TITLE
支持下mysql5.7 json类型解析

### ISSUE THREAD

**Issue by agapple** [alibaba/canal#187]
RT. 支持下mysql5.7

**Comment by agapple** [comment]
测试数据格式:
```
+-----+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| uid | data                                                                                                                                                            |
+-----+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+
|   1 | {"mail": "jiangchengyao@gmail.com", "name": "David", "address": "Shangahai"}                                                                                    |
|   2 | {"mail": "test"}                                                                                                                                                |
|   3 | {"int": 1, "bool": true, "long1": 4294967296, "long2": 1.8446744073709552e19, "double": 1.11012}                                                                |
|   4 | {"mail": [1, true, 1.11012, 4294967296, 1.8446744073709552e19]}                                                                                                 |
|   5 | {"int": 1, "bool": true, "mail": [1, true, 1.11012, 4294967296, 1.8446744073709552e19], "long1": 4294967296, "long2": 1.8446744073709552e19, "double": 1.11012} |
|   6 | {"time": "23:59:59"}                                                                                                                                            |
|   7 | {"time": "2016-06-30 15:03:32.000000"}                                                                                                                          |
|   8 | {"time": "2016-06-30 15:51:25.041000"}                                                                                                                          |
|   9 | {"time": 123.123}                                                                                                                                               |
|  10 | {"time": "23:23:23:19"}                                                                                                                                         |
|  11 | {"time": "01:00:05.000000"}                                                                                                                                     |
|  12 | {"time": "630:19:29.000000"}                                                                                                                                    |
|  13 | {"time": "2016-06-30 16:08:58.000000"}                                                                                                                          |
|  14 | {"n1": "v1", "ne1": {"n2": "v2", "ne2": {"n3": "v3", "n32": ["v32", "v33", 1]}}}                                                                                |
+-----+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

**Comment by yufeng0528** [comment]
有个bug在1.0.23下
`com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: java.lang.IllegalArgumentException: illegal json data
	at com.taobao.tddl.dbsync.binlog.JsonConversion.parse_scalar(JsonConversion.java:150)
	at com.taobao.tddl.dbsync.binlog.JsonConversion.parse_value(JsonConversion.java:67)`

数据库版本  mysql-5.7.11-winx64
数据库结构
CREATE TABLE `customer_data` (
  `id` bigint(19) unsigned NOT NULL AUTO_INCREMENT,
  `supplier_id` bigint(19) unsigned NOT NULL COMMENT '商户id',
  `customer_id` bigint(19) unsigned NOT NULL,
  `customer_data` json DEFAULT NULL COMMENT '顾客标准属性',
  `customer_ext_data` json DEFAULT NULL COMMENT '顾客扩展属性',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cust` (`customer_id`)
) ENGINE=InnoDB AUTO_INCREMENT=26036 DEFAULT CHARSET=utf8mb4;

**Comment by agapple** [comment]
给出你测试的json字符串
