### ISSUE TITLE
canal-adapter es 本地windows启动报错Config dir not found

### ISSUE THREAD

**Issue by canglang1973** [alibaba/canal#1880]
## Question

adapter中application.yml文件配置与官方一样:
------------------------------------------
server:
  port: 8081
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

canal.conf:
  canalServerHost: 127.0.0.1:11111
  batchSize: 500
  syncBatchSize: 1000
  retries: 0
  timeout:
  mode: tcp 
  srcDataSources:
    defaultDS:
      url: jdbc:mysql://127.0.0.1:3306/local_db?useUnicode=true
      username: root
      password: 123456
  canalAdapters:
  - instance: example 
    groups:
    - groupId: g1
      outerAdapters:
      - name: es
        hosts: 127.0.0.1:9300               # es 集群地址, 逗号分隔
        properties:
          cluster.name: wx-log-cluster       # es cluster name
-------------------------------------------------------
异常堆栈:

2019-06-11 11:24:12.514 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'applicationConfigMonitor': Invocation of init method failed; nested exception is java.lang.RuntimeException: Config dir not found.
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:138)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:422)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1694)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:579)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:501)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:760)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327)
	at com.alibaba.otter.canal.adapter.launcher.CanalAdapterApplication.main(CanalAdapterApplication.java:19)
Caused by: java.lang.RuntimeException: Config dir not found.
	at com.alibaba.otter.canal.client.adapter.support.Util.getConfDirPath(Util.java:87)
	at com.alibaba.otter.canal.client.adapter.support.Util.getConfDirPath(Util.java:67)
	at com.alibaba.otter.canal.adapter.launcher.monitor.ApplicationConfigMonitor.init(ApplicationConfigMonitor.java:41)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:365)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:308)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:135)
	... 16 common frames omitted

@rewerma @agapple 麻烦请解答一下呢? 我也看了源码应该是能正常读到../conf/es这个文件目录的噻

**Comment by kangsafe** [comment]
你看一下你的路径是不是有中文路径或者，我也遇到这个问题了，我放到桌面上一个叫“canal-中文”文件夹下，然后死活不行，报和你的一样的错误，然后我把他放大d:\etl\canal.adapter下就可以了，不知道什么原因

**Comment by canglang1973** [comment]
@kangsafe  好的 我试试

**Comment by BruceWhiteBai** [comment]
没中文也报这个问题，咋解决

**Comment by BruceWhiteBai** [comment]
![image](https://user-images.githubusercontent.com/10953780/62360455-60a34c00-b54b-11e9-95ac-8a020cf7066a.png)

Windows下路径有问题啊

**Comment by BruceWhiteBai** [comment]
![image](https://user-images.githubusercontent.com/10953780/62361733-27b8a680-b54e-11e9-9563-6af83abb40c5.png)
在Windows下有路径问题，算了，还是在Linux上搞吧

**Comment by songhejia** [comment]
> ![image](https://user-images.githubusercontent.com/10953780/62361733-27b8a680-b54e-11e9-9563-6af83abb40c5.png)
> 在Windows下有路径问题

遇到同样问题，怎么改的呢？？

**Comment by JingerYu** [comment]
> 你看一下你的路径是不是有中文路径或者，我也遇到这个问题了，我放到桌面上一个叫“canal-中文”文件夹下，然后死活不行，报和你的一样的错误，然后我把他放大d:\etl\canal.adapter下就可以了，不知道什么原因

感谢大佬

**Comment by AlphaKitty** [comment]
win10 路径里面没有中文也报同样的错误 我整个文件夹移动到另一个位置然后改个简单的名字就能行... 很迷

**Comment by gqyalh** [comment]
换了路径也不行
