### ISSUE TITLE
ES同步时关联查询的外键类型不支持string类型

### ISSUE THREAD

**Issue by yijiuping** [alibaba/canal#1887]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version
1.1.3

* mysql version
5.7

### Issue Description
当配置了关联查询语句时，主子表的外键类型只能是numeric类型，否则会报错。看源码发现是：
        // 查询sql批量更新
        DataSource ds = DatasourceConfig.DATA_SOURCES.get(config.getDataSourceKey());
        StringBuilder sql = new StringBuilder("SELECT * FROM (" + mapping.getSql() + ") _v WHERE ");
        paramsTmp.forEach(
            (fieldName, value) -> sql.append("_v.").append(fieldName).append("=").append(value).append(" AND "));
        int len = sql.length();

在拼接sql时，没有带单引号。

### Steps to reproduce
select r.id as _id,r.user_id,u.status,u.is_deleted, r.biz_user_id, r.biz_code, r.cellphone, r.create_time, r.update_time 
        from user_relation r
        left join user u on u.id = r.user_id

r.user_id字段为string类型

### Expected behaviour
能正常查询

### Actual behaviour
查询报错。

If there is an exception, please attach the exception trace:
java.lang.RuntimeException: java.lang.RuntimeException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column '5cff5d45b0682f4a34e62bde' in 'where clause'
        at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.sync(ESSyncService.java:113) ~[na:na]
        at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.sync(ESSyncService.java:61) ~[na:na]
        at com.alibaba.otter.canal.client.adapter.es.ESAdapter.sync(ESAdapter.java:176) ~[na:na]
        at com.alibaba.otter.canal.client.adapter.es.ESAdapter.sync(ESAdapter.java:155) ~[na:na]
        at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.batchSync(AbstractCanalAdapterWorker.java:198) ~[client-adapter.launcher-1.1.3.jar:na]
        at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$1(AbstractCanalAdapterWorker.java:62) ~[client-adapter.launcher-1.1.3.jar:na]
        at java.util.ArrayList.forEach(Unknown Source) ~[na:1.8.0_121]
        at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$2(AbstractCanalAdapterWorker.java:58) ~[client-adapter.launcher-1.1.3.jar:na]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[na:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:1.8.0_121]
        at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_121]
Caused by: java.lang.RuntimeException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column '5cff5d45b0682f4a34e62bde' in 'where clause'
        at com.alibaba.otter.canal.client.adapter.support.Util.sqlRS(Util.java:47) ~[client-adapter.common-1.1.3.jar:na]
        at com.alibaba.otter.canal.client.adapter.es.support.ESTemplate.updateByQuery(ESTemplate.java:143) ~[na:na]
        at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.joinTableSimpleFieldOperation(ESSyncService.java:572) ~[na:na]
        at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.update(ESSyncService.java:302) ~[na:na]
        at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.sync(ESSyncService.java:98) ~[na:na]
        ... 11 common frames omitted
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column '5cff5d45b0682f4a34e62bde' in 'where clause'
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_121]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.8.0_121]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.8.0_121]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[na:1.8.0_121]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.40.jar:5.1.40]
        at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.40.jar:5.1.40]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943) ~[mysql-connector-java-5.1.40.jar:5.1.40]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3970) ~[mysql-connector-java-5.1.40.jar:5.1.40]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3906) ~[mysql-connector-java-5.1.40.jar:5.1.40]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524) ~[mysql-connector-java-5.1.40.jar:5.1.40]
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2677) ~[mysql-connector-java-5.1.40.jar:5.1.40]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545) ~[mysql-connector-java-5.1.40.jar:5.1.40]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2503) ~[mysql-connector-java-5.1.40.jar:5.1.40]
        at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1369) ~[mysql-connector-java-5.1.40.jar:5.1.40]
        at com.alibaba.druid.pool.DruidPooledStatement.executeQuery(DruidPooledStatement.java:230) ~[druid-1.1.9.jar:1.1.9]
        at com.alibaba.otter.canal.client.adapter.support.Util.sqlRS(Util.java:42) ~[client-adapter.common-1.1.3.jar:na]
        ... 15 common frames omitted
```
Just put your stack trace here!
```

**Comment by rewerma** [comment]
这个在最新版本里面记得已经解决了

**Comment by yijiuping** [comment]
还没有正式release吧？
