### ISSUE TITLE
Did not write as much data as expected

### ISSUE THREAD

**Issue by leobasic** [alibaba/canal#1890]
- [x] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version  1.1.3
* mysql version 5.6.41-log

### Issue Description
能同步数据，但是报很多错误

2019-06-13 10:45:34.862 [destination = bigdata_collect , address = /192.168.8.32:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> find start position successfully, EntryPosition[included=false,journalName=mysql-bin.000010,position=176211322,serverId=1,gtid=,timestamp=1560393915000] cost : 108ms , the next step is binlog dump
2019-06-13 10:45:35.980 [destination = bigdata_collect , address = /192.168.8.32:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address 192.168.8.32/192.168.8.32:3306 has an error, retrying. caused by 
com.alibaba.otter.canal.parse.exception.CanalParseException: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: java.lang.IllegalStateException: Did not write as much data as expected.
	at com.google.protobuf.CodedOutputStream.checkNoSpaceLeft(CodedOutputStream.java:977) ~[protobuf-java-3.6.1.jar:na]
	at com.google.protobuf.ByteString$CodedBuilder.build(ByteString.java:1136) ~[protobuf-java-3.6.1.jar:na]
	at com.google.protobuf.AbstractMessageLite.toByteString(AbstractMessageLite.java:61) ~[protobuf-java-3.6.1.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseRowsEvent(LogEventConvert.java:564) ~[canal.parse-1.1.3.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$DmlParserStage.onEvent(MysqlMultiStageCoprocessor.java:330) ~[canal.parse-1.1.3.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$DmlParserStage.onEvent(MysqlMultiStageCoprocessor.java:316) ~[canal.parse-1.1.3.jar:na]
	at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) ~[disruptor-3.4.2.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@9-internal/ThreadPoolExecutor.java:1158) ~[na:na]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@9-internal/ThreadPoolExecutor.java:632) ~[na:na]
	at java.lang.Thread.run(java.base@9-internal/Thread.java:804) [na:na]

### Actual behaviour

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by leobasic** [comment]
我自己解决了这个问题，把protobuf更换成2.6.1版本
