### ISSUE TITLE
新的master分支编译有问题

### ISSUE THREAD

**Issue by wwwwwwchun** [alibaba/canal#1893]
从最新的master上下载代码，编译的时候报错，内容如下：
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[ERROR] The build could not read 1 project -> [Help 1]
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[ERROR] 'dependencies.dependency.version' for org.apache.rocketmq:rocketmq-client:jar is missing. @ line 62, column 21
[WARNING] 'dependencies.dependency.exclusions.exclusion.groupId' for com.alibaba.otter:client-adapter.logger:jar:jar-with-dependencies with value '*' does not match a valid id pattern. @ line 103, column 30
[WARNING] 'dependencies.dependency.exclusions.exclusion.artifactId' for com.alibaba.otter:client-adapter.logger:jar:jar-with-dependencies with value '*' does not match a valid id pattern. @ line 102, column 33
[WARNING] 'dependencies.dependency.exclusions.exclusion.groupId' for com.alibaba.otter:client-adapter.hbase:jar:jar-with-dependencies with value '*' does not match a valid id pattern. @ line 116, column 30
[WARNING] 'dependencies.dependency.exclusions.exclusion.artifactId' for com.alibaba.otter:client-adapter.hbase:jar:jar-with-dependencies with value '*' does not match a valid id pattern. @ line 115, column 33
[WARNING] 'dependencies.dependency.exclusions.exclusion.groupId' for com.alibaba.otter:client-adapter.elasticsearch:jar:jar-with-dependencies with value '*' does not match a valid id pattern. @ line 129, column 30
[WARNING] 'dependencies.dependency.exclusions.exclusion.artifactId' for com.alibaba.otter:client-adapter.elasticsearch:jar:jar-with-dependencies with value '*' does not match a valid id pattern. @ line 128, column 33
[WARNING] 'dependencies.dependency.exclusions.exclusion.groupId' for com.alibaba.otter:client-adapter.rdb:jar:jar-with-dependencies with value '*' does not match a valid id pattern. @ line 142, column 30
[WARNING] 'dependencies.dependency.exclusions.exclusion.artifactId' for com.alibaba.otter:client-adapter.rdb:jar:jar-with-dependencies with value '*' does not match a valid id pattern. @ line 141, column 33

        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:363)
        at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:636)
        at org.apache.maven.DefaultMaven.getProjectsForMavenReactor(DefaultMaven.java:585)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:234)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:357)
[ERROR]   
[ERROR]   The project com.alibaba.otter:client-adapter.launcher:1.1.4-SNAPSHOT (/data/canal-master/client-adapter/launcher/pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for org.apache.rocketmq:rocketmq-client:jar is missing. @ line 62, column 21
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException

编译命令为mvn clean install -e

**Comment by agapple** [comment]
已修复
