### ISSUE TITLE
synchbase 时mysql 先insert 部分字段，后更新剩下的字段，hbase报错

### ISSUE THREAD

**Issue by rongcui** [alibaba/canal#1910]
## Question

synchbase场景下，mysql先insert部分字段，此时hbase里只有部分字段，后update剩下字段时，会报错：
2019-06-20 12:50:11.182 [pool-4-thread-1] ERROR c.a.o.canal.client.adapter.hbase.support.HbaseTemplate - No columns to insert
java.lang.IllegalArgumentException: No columns to insert
        at org.apache.hadoop.hbase.client.HTable.validatePut(HTable.java:1515)
        at org.apache.hadoop.hbase.client.BufferedMutatorImpl.validatePut(BufferedMutatorImpl.java:147)
        at org.apache.hadoop.hbase.client.BufferedMutatorImpl.doMutate(BufferedMutatorImpl.java:134)
        at org.apache.hadoop.hbase.client.BufferedMutatorImpl.mutate(BufferedMutatorImpl.java:105)
        at org.apache.hadoop.hbase.client.HTable.put(HTable.java:1050)
        at com.alibaba.otter.canal.client.adapter.hbase.support.HbaseTemplate.puts(HbaseTemplate.java:149)
        at com.alibaba.otter.canal.client.adapter.hbase.service.HbaseSyncService.update(HbaseSyncService.java:257)
        at com.alibaba.otter.canal.client.adapter.hbase.service.HbaseSyncService.sync(HbaseSyncService.java:37)
        at com.alibaba.otter.canal.client.adapter.hbase.HbaseAdapter.lambda$sync$3(HbaseAdapter.java:141)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at com.alibaba.otter.canal.client.adapter.hbase.HbaseAdapter.sync(HbaseAdapter.java:141)
        at com.alibaba.otter.canal.client.adapter.hbase.HbaseAdapter.sync(HbaseAdapter.java:111)
        at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.batchSync(AbstractCanalAdapterWorker.java:198)
        at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$4(AbstractCanalAdapterWorker.java:106)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$5(AbstractCanalAdapterWorker.java:103)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019-06-20 12:50:11.183 [pool-4-thread-1] ERROR c.a.o.c.adapter.launcher.loader.CanalAdapterKafkaWorker - java.lang.IllegalArgumentException: No columns to insert
java.lang.RuntimeException: java.lang.IllegalArgumentException: No columns to insert
        at com.alibaba.otter.canal.client.adapter.hbase.support.HbaseTemplate.puts(HbaseTemplate.java:154)
        at com.alibaba.otter.canal.client.adapter.hbase.service.HbaseSyncService.update(HbaseSyncService.java:257)
        at com.alibaba.otter.canal.client.adapter.hbase.service.HbaseSyncService.sync(HbaseSyncService.java:37)
        at com.alibaba.otter.canal.client.adapter.hbase.HbaseAdapter.lambda$sync$3(HbaseAdapter.java:141)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at com.alibaba.otter.canal.client.adapter.hbase.HbaseAdapter.sync(HbaseAdapter.java:141)
        at com.alibaba.otter.canal.client.adapter.hbase.HbaseAdapter.sync(HbaseAdapter.java:111)
        at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.batchSync(AbstractCanalAdapterWorker.java:198)
        at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$4(AbstractCanalAdapterWorker.java:106)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$5(AbstractCanalAdapterWorker.java:103)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: No columns to insert
        at org.apache.hadoop.hbase.client.HTable.validatePut(HTable.java:1515)
        at org.apache.hadoop.hbase.client.BufferedMutatorImpl.validatePut(BufferedMutatorImpl.java:147)
        at org.apache.hadoop.hbase.client.BufferedMutatorImpl.doMutate(BufferedMutatorImpl.java:134)
        at org.apache.hadoop.hbase.client.BufferedMutatorImpl.mutate(BufferedMutatorImpl.java:105)
        at org.apache.hadoop.hbase.client.HTable.put(HTable.java:1050)
        at com.alibaba.otter.canal.client.adapter.hbase.support.HbaseTemplate.puts(HbaseTemplate.java:149)
        ... 14 common frames omitted

此情况该如何配置？或如何解决？

**Comment by rongcui** [comment]
。

**Comment by rongcui** [comment]
.
