### ISSUE TITLE
canal 将mq 的类型设置为 kafka, 并开启kafka 事务，应用报错

### ISSUE THREAD

**Issue by MrYueQ** [alibaba/canal#1919]
### canal 版本
- canal.deployer-1.1.3
### kafka 事务开启选项
```bash
# use transaction for kafka flatMessage batch produce
# enable kafka event grok
canal.mq.transaction = true
```
### 应用程序中错误日志输出
```bash
2019-06-21 22:56:46.407 [pool-40-thread-6] ERROR com.alibaba.otter.canal.server.CanalMQStarter - TransactionalId canal-transactional-id: Invalid transition attempted fro
m state COMMITTING_TRANSACTION to state IN_TRANSACTION
org.apache.kafka.common.KafkaException: TransactionalId canal-transactional-id: Invalid transition attempted from state COMMITTING_TRANSACTION to state IN_TRANSACTION
        at org.apache.kafka.clients.producer.internals.TransactionManager.transitionTo(TransactionManager.java:758) ~[kafka-clients-1.1.1.jar:na]
        at org.apache.kafka.clients.producer.internals.TransactionManager.transitionTo(TransactionManager.java:751) ~[kafka-clients-1.1.1.jar:na]
        at org.apache.kafka.clients.producer.internals.TransactionManager.beginTransaction(TransactionManager.java:216) ~[kafka-clients-1.1.1.jar:na]
        at org.apache.kafka.clients.producer.KafkaProducer.beginTransaction(KafkaProducer.java:587) ~[kafka-clients-1.1.1.jar:na]
        at com.alibaba.otter.canal.kafka.CanalKafkaProducer.send(CanalKafkaProducer.java:106) ~[canal.server-1.1.3.jar:na]
        at com.alibaba.otter.canal.server.CanalMQStarter.worker(CanalMQStarter.java:182) [canal.server-1.1.3.jar:na]
        at com.alibaba.otter.canal.server.CanalMQStarter.access$500(CanalMQStarter.java:22) [canal.server-1.1.3.jar:na]
        at com.alibaba.otter.canal.server.CanalMQStarter$CanalMQRunnable.run(CanalMQStarter.java:224) [canal.server-1.1.3.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_171]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
```
关于canal 实例的配置文件可以参考此[canal 实例配置] （https://github.com/alibaba/canal/issues/1918)

**Comment by MrYueQ** [comment]
这个已经是bug. 没细心看 issue 列表。早已有前辈反馈。可见此 issue (https://github.com/alibaba/canal/issues/1826)
