### ISSUE TITLE
canal KILL DUMP 

### ISSUE THREAD

**Issue by wym408** [alibaba/canal#193]
# position info

canal.instance.master.address = xx.xx.xx.xx:3306
canal.instance.master.journal.name = 
canal.instance.master.position = 
canal.instance.master.timestamp = 1471076485000

2016-08-13 16:23:09.821 [main] WARN  org.springframework.beans.TypeConverterDelegate - PropertyEditor [com.sun.beans.editors.EnumEditor] found through deprecated global PropertyEditorManager fallback - consider using a more isolated form of registration, e.g. on the BeanWrapper/BeanFactory!
2016-08-13 16:23:09.978 [main] INFO  c.a.otter.canal.instance.spring.CanalInstanceWithSpring - start CannalInstance for 1-example 
2016-08-13 16:23:10.000 [main] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - start successful....
2016-08-13 16:23:10.030 [destination = example , address = /xxxxxxxxx:3306 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - prepare to find start position ::1471076485000
2016-08-13 16:23:34.010 [destination = example , address = /xxxxxxxxxxx:3306 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - dump address /xxxxxxxxxx:3306 has an error, retrying. caused by 
java.io.IOException: KILL DUMP 459561 failure:java.io.IOException: ErrorPacket [errorNumber=1094, fieldCount=-1, message=Unknown thread id: 459561, sqlState=HY000, sqlStateMarker=#]
 with command: KILL CONNECTION 459561
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlUpdateExecutor.update(MysqlUpdateExecutor.java:49)
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.disconnect(MysqlConnector.java:104)
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.reconnect(MysqlConnector.java:82)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.reconnect(MysqlConnection.java:56)
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:169)
        at java.lang.Thread.run(Thread.java:745)

```
    at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.disconnect(MysqlConnector.java:106) ~[canal.parse.driver-1.0.22.jar:na]
    at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.reconnect(MysqlConnector.java:82) ~[canal.parse.driver-1.0.22.jar:na]
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.reconnect(MysqlConnection.java:56) ~[canal.parse-1.0.22.jar:na]
    at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:169) ~[canal.parse-1.0.22.jar:na]
    at java.lang.Thread.run(Thread.java:745) [na:1.7.0_80]
```

2016-08-13 16:23:34.010 [destination = example , address = /xxxxxxxx:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[java.io.IOException: KILL DUMP 459561 failure:java.io.IOException: ErrorPacket [errorNumber=1094, fieldCount=-1, message=Unknown thread id: 459561, sqlState=HY000, sqlStateMarker=#]
 with command: KILL CONNECTION 459561
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlUpdateExecutor.update(MysqlUpdateExecutor.java:49)
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.disconnect(MysqlConnector.java:104)
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.reconnect(MysqlConnector.java:82)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.reconnect(MysqlConnection.java:56)
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:169)
        at java.lang.Thread.run(Thread.java:745)

```
    at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.disconnect(MysqlConnector.java:106)
    at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.reconnect(MysqlConnector.java:82)
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.reconnect(MysqlConnection.java:56)
    at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:169)
    at java.lang.Thread.run(Thread.java:745)
```

]
2016-08-13 16:23:46.004 [destination = example , address = /xxxxxxxx:3306 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - prepare to find start position ::1471076485000

**Comment by wym408** [comment]
1.0.22 版本
 配置起始时间信息，client启动后，/logs/example/example.log  中记录 kill dump
配置起始位置，也报相同的错误
谢谢 大神们 帮忙

**Comment by whlgh** [comment]
我也遇到这样的问题，后来把conf/example/meta.dat删掉，再重启就好了。

**Comment by wym408** [comment]
@whlgh   这个方法我试了，没用

**Comment by wym408** [comment]
@whlgh   这个方法我试了，没用，不知道我是不是还有其他地方没设置对？ 我用windows 跑，配置了canal.instance.master.timestamp 没问题，配置 canal.instance.master.journal.name 和 canal.instance.master.position  就报上面的错，  Linux下跑 2中配置方式 都报错

**Comment by whlgh** [comment]
#################################################
## mysql serverId
canal.instance.mysql.slaveId = 1234

# position info
canal.instance.master.address = 127.0.0.1:3306
canal.instance.master.journal.name =
canal.instance.master.position =
canal.instance.master.timestamp =

#canal.instance.standby.address = 
#canal.instance.standby.journal.name =
#canal.instance.standby.position = 
#canal.instance.standby.timestamp = 

# username/password
canal.instance.dbUsername =root
canal.instance.dbPassword =root
canal.instance.defaultDatabaseName =test
canal.instance.connectionCharset = UTF-8

# table regex
canal.instance.filter.regex = .*\\..*
# table black regex
canal.instance.filter.black.regex =

#################################################

这是我配置文件， canal.instance.master.journal.name、canal.instance.master.position、canal.instance.master.timestamp三个参数都为空也没问题。配上前两个也没问题，我是在Linux下跑的。

**Comment by wym408** [comment]
@whlgh   你用的什么版本？我用的1.0.22

**Comment by whlgh** [comment]
也是1.0.22
1、你用root用户执行
2、show variables like '%log_bin%';
看看mysql的binlog有没有开启

**Comment by wym408** [comment]
@whlgh   方便的话，加我QQ  793024465  私聊  效率个高点

**Comment by agapple** [comment]
KILL CONNECTION异常已经处理

**Comment by smallez** [comment]
请问下，这个问题是怎么解决的，我怎么没有找到meta.dat文件

**Comment by smallez** [comment]
这个是我的异常日志信息
2016-11-29 11:17:23.465 [destination = inventory , address = /172.172.230.55:3307 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - prepare to find start position ::1480262400000
2016-11-29 11:17:57.401 [destination = inventory , address = /172.172.230.55:3307 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - dump address /172.172.230.55:3307 has an error, retrying. caused by 
java.io.IOException: KILL DUMP 6155706 failure:java.io.IOException: ErrorPacket [errorNumber=1094, fieldCount=-1, message=Unknown thread id: 6155706, sqlState=HY000, sqlStateMarker=#]
 with command: KILL CONNECTION 6155706
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlUpdateExecutor.update(MysqlUpdateExecutor.java:49)
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.disconnect(MysqlConnector.java:104)
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.reconnect(MysqlConnector.java:82)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.reconnect(MysqlConnection.java:56)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:169)
	at java.lang.Thread.run(Thread.java:745)

	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.disconnect(MysqlConnector.java:106) ~[canal.parse.driver-1.0.22.jar:na]
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.reconnect(MysqlConnector.java:82) ~[canal.parse.driver-1.0.22.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.reconnect(MysqlConnection.java:56) ~[canal.parse-1.0.22.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:169) ~[canal.parse-1.0.22.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]

**Comment by jkudu** [comment]
你的问题怎么解决的？能分享下么？

**Comment by wym408** [comment]
我好像用时间了，不和位置较劲了

**Comment by xiaoshikun801** [comment]
能分析解决的过程吗
