### ISSUE TITLE
同步父子文档时，没有parent信息，导致同步失败。

### ISSUE THREAD

**Issue by hqch0708** [alibaba/canal#1931]
在修改了mysql数据时，通过canal同步父子文档中的子文档到es时，发生异常：
`2019-06-26 23:45:38.441 [pool-4-thread-1] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - ES sync commit errorMapperParsingException[failed to parse]; nested: IllegalArgumentException[[parent] is missing for join field [xxxxxx]];
java.lang.RuntimeException: ES sync commit errorMapperParsingException[failed to parse]; nested: IllegalArgumentException[[parent] is missing for join field [xxxxx]];
        at com.alibaba.otter.canal.client.adapter.es.support.ESTemplate.commit(ESTemplate.java:203)
        at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.commit(ESSyncService.java:843)
        at com.alibaba.otter.canal.client.adapter.es.ESAdapter.sync(ESAdapter.java:158)
        at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.batchSync(AbstractCanalAdapterWorker.java:198)
        at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$1(AbstractCanalAdapterWorker.java:62)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$2(AbstractCanalAdapterWorker.java:58)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)`

查看源码发现，在
`public Object getESDataFromDmlData(ESMapping mapping, Map<String, Object> dmlData, Map<String, Object> dmlOld,Map<String, Object> esFieldData) {
        SchemaItem schemaItem = mapping.getSchemaItem();
        String idFieldName = mapping.get_id() == null ? mapping.getPk() : mapping.get_id();
        Object resultIdVal = null;
        for (FieldItem fieldItem : schemaItem.getSelectFields().values()) {
            String columnName = fieldItem.getColumnItems().iterator().next().getColumnName();
            if (fieldItem.getFieldName().equals(idFieldName)) {
                resultIdVal = getValFromData(mapping, dmlData, fieldItem.getFieldName(), columnName);
            }
            if (dmlOld.containsKey(columnName) && !mapping.getSkips().contains(fieldItem.getFieldName())) {
                esFieldData.put(Util.cleanColumn(fieldItem.getFieldName()),
                    getValFromData(mapping, dmlData, fieldItem.getFieldName(), columnName));
            }
        }
        // 添加父子文档关联信息
        putRelationData(mapping, schemaItem, dmlOld, esFieldData);
        return resultIdVal;`
传递的是dmlOld，导致根据配置的parent字段获取值为null，从而在提交给es的数据中没有
parent和$parent_routing，导致同步失败。

**Comment by rewerma** [comment]
修改的是父子关联外键信息？

**Comment by hqch0708** [comment]
不是外键，是子表中的其他信息

**Comment by hqch0708** [comment]
因为dml中data放的是当前记录行最新信息，olddata放的是修改字段的原始值，在这里传过去的是olddata，导致获取不到parent配置字段

**Comment by niejian** [comment]
> 因为dml中data放的是当前记录行最新信息，olddata放的是修改字段的原始值，在这里传过去的是olddata，导致获取不到parent配置字段

解决了吗？

**Comment by chaiyanliang** [comment]
添加了这段代码不行啊，有解决方案吗?
