### ISSUE TITLE
表结构解析失败，syntax error, error in :'SPATIAL KEY `position` (`geo`)

### ISSUE THREAD

**Issue by zhaoyuanping** [alibaba/canal#1943]
2019-06-29 11:17:35.153 [destination = example , address = /172.17.0.10:3306 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta - parse faield : CREATE TABLE `tag_topic` (
  `id` bigint(11) NOT NULL,
  `geo` point NOT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  SPATIAL KEY `position` (`geo`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='话题表'
com.alibaba.fastsql.sql.parser.ParserException: syntax error, error in :'SPATIAL KEY `position` (`geo`)
) ENGINE=In', expect ), actual null, pos 1190, line 23, column 16, token IDENTIFIER `position`
        at com.alibaba.fastsql.sql.parser.SQLParser.printError(SQLParser.java:363) ~[fastsql-2.0.0_preview_644.jar:2.0.0_preview_644]
        at com.alibaba.fastsql.sql.parser.SQLParser.accept(SQLParser.java:371) ~[fastsql-2.0.0_preview_644.jar:2.0.0_preview_644]
        at com.alibaba.fastsql.sql.dialect.mysql.parser.MySqlCreateTableParser.parseCreateTable(MySqlCreateTableParser.java:418) ~[fastsql-2.0.0_preview_644.jar:2.0.0_preview_644]
        at com.alibaba.fastsql.sql.dialect.mysql.parser.MySqlStatementParser.parseCreate(MySqlStatementParser.java:265) ~[fastsql-2.0.0_preview_644.jar:2.0.0_preview_644]
        at com.alibaba.fastsql.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:224) ~[fastsql-2.0.0_preview_644.jar:2.0.0_preview_644]
        at com.alibaba.fastsql.sql.SQLUtils.parseStatements(SQLUtils.java:525) ~[fastsql-2.0.0_preview_644.jar:2.0.0_preview_644]
        at com.alibaba.fastsql.sql.repository.SchemaRepository.console(SchemaRepository.java:439) ~[fastsql-2.0.0_preview_644.jar:2.0.0_preview_644]
        at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta.apply(MemoryTableMeta.java:83) ~[canal.parse-1.1.3-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.applyHistoryOnMemory(DatabaseTableMeta.java:463) [canal.parse-1.1.3-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:174) [canal.parse-1.1.3-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:106) [canal.parse-1.1.3-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:192) [canal.parse-1.1.3-SNAPSHOT.jar:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_201]

**Comment by bucketli** [comment]
hi，你好，请按照标准模板填写，这样方便我们准确定位和解决问题，如果你有能力 fix 问题， 欢迎提交代码。感谢。

**Comment by agapple** [comment]
最新主干已经修复
