### ISSUE TITLE
canal不能使用阿里云提供的RocketMq

### ISSUE THREAD

**Issue by ljz0721cx** [alibaba/canal#1944]
### environment

* canal version
1.1.3
* mysql version
5.7

### Issue Description
1.阿里云购买的rocket不能再canal中使用，自己搭建的rocketmq可以收到消息，在canel.deployer时候出现以下异常
```
2019-06-29 14:58:36.507 [pool-4-thread-1] ERROR com.alibaba.otter.canal.rocketmq.CanalRocketMQProducer - send flat message to fixed partition error
org.apache.rocketmq.client.exception.MQClientException: No route info for this topic, DEV_CANAL_TRANS_BILL
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendSelectImpl(DefaultMQProducerImpl.java:1031) ~[rocketmq-client-4.3.0.jar:4.3.0]
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:997) ~[rocketmq-client-4.3.0.jar:4.3.0]
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:992) ~[rocketmq-client-4.3.0.jar:4.3.0]
	at org.apache.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:389) ~[rocketmq-client-4.3.0.jar:4.3.0]
	at com.alibaba.otter.canal.rocketmq.CanalRocketMQProducer.send(CanalRocketMQProducer.java:197) [classes/:na]
	at com.alibaba.otter.canal.rocketmq.CanalRocketMQProducer.send(CanalRocketMQProducer.java:75) [classes/:na]
	at com.alibaba.otter.canal.server.CanalMQStarter.worker(CanalMQStarter.java:182) [classes/:na]
	at com.alibaba.otter.canal.server.CanalMQStarter.access$500(CanalMQStarter.java:22) [classes/:na]
	at com.alibaba.otter.canal.server.CanalMQStarter$CanalMQRunnable.run(CanalMQStarter.java:224) [classes/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_202]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_202]
2019-06-29 14:58:41.908 [pool-4-thread-1] ERROR com.alibaba.otter.canal.rocketmq.CanalRocketMQProducer - send flat message to fixed partition error
org.apache.rocketmq.client.exception.MQClientException: No route info for this topic, DEV_CANAL_TRANS_BILL
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendSelectImpl(DefaultMQProducerImpl.java:1031) ~[rocketmq-client-4.3.0.jar:4.3.0]
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:997) ~[rocketmq-client-4.3.0.jar:4.3.0]
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:992) ~[rocketmq-client-4.3.0.jar:4.3.0]
	at org.apache.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:389) ~[rocketmq-client-4.3.0.jar:4.3.0]
	at com.alibaba.otter.canal.rocketmq.CanalRocketMQProducer.send(CanalRocketMQProducer.java:197) [classes/:na]
	at com.alibaba.otter.canal.rocketmq.CanalRocketMQProducer.send(CanalRocketMQProducer.java:75) [classes/:na]
	at com.alibaba.otter.canal.server.CanalMQStarter.worker(CanalMQStarter.java:182) [classes/:na]
	at com.alibaba.otter.canal.server.CanalMQStarter.access$500(CanalMQStarter.java:22) [classes/:na]
	at com.alibaba.otter.canal.server.CanalMQStarter$CanalMQRunnable.run(CanalMQStarter.java:224) [classes/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_202]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_202]
2019-06-29 14:58:45.429 [pool-4-thread-1] ERROR com.alibaba.otter.canal.rocketmq.CanalRocketMQProducer - send flat message to fixed partition error
org.apache.rocketmq.client.exception.MQClientException: No route info for this topic, DEV_CANAL_TRANS_BILL
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendSelectImpl(DefaultMQProducerImpl.java:1031) ~[rocketmq-client-4.3.0.jar:4.3.0]
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:997) ~[rocketmq-client-4.3.0.jar:4.3.0]
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:992) ~[rocketmq-client-4.3.0.jar:4.3.0]
	at org.apache.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:389) ~[rocketmq-client-4.3.0.jar:4.3.0]
	at com.alibaba.otter.canal.rocketmq.CanalRocketMQProducer.send(CanalRocketMQProducer.java:197) [classes/:na]
	at com.alibaba.otter.canal.rocketmq.CanalRocketMQProducer.send(CanalRocketMQProducer.java:75) [classes/:na]
	at com.alibaba.otter.canal.server.CanalMQStarter.worker(CanalMQStarter.java:182) [classes/:na]
	at com.alibaba.otter.canal.server.CanalMQStarter.access$500(CanalMQStarter.java:22) [classes/:na]
	at com.alibaba.otter.canal.server.CanalMQStarter$CanalMQRunnable.run(CanalMQStarter.java:224) [classes/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_202]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_202]

```

2.阿里云上这个匹配地址和阿里云上的地址不一致,代码在
```
org.apache.rocketmq.remoting.common.RemotingHelper#string2SocketAddress
//eg. http://1592051318398515.mqrest.cn-qingdao-public.aliyuncs.com:80
//不能创建InetSocketAddress
public static SocketAddress string2SocketAddress(final String addr) {
        String[] s = addr.split(":");
        InetSocketAddress isa = new InetSocketAddress(s[0], Integer.parseInt(s[1]));
        return isa;
    }
```

**Comment by EayonChen** [comment]
i have meet the same question.

**Comment by santiagogogo** [comment]
我也遇到的上述问题

**Comment by wzcJava** [comment]
需要修改 server项目下的源码，将生产消息那段代码用ons-client改写 com.alibaba.otter.canal.rocketmq.CanalRocketMQProducer

**Comment by agapple** [comment]
https://github.com/alibaba/canal/commit/d0a83aad2758c28e84b5581fbf740ed5a4ffee55

升级1.1.4最新版，已经支持
