### ISSUE TITLE
Unexpected End Stream Exception

### ISSUE THREAD

**Issue by owenludong** [alibaba/canal#197]
数据库用的阿里云rds， canal版本1.0.22

最近隔几天就会报下面的错误，导致接收不到binlog。 能看出是啥问题吗？

2016-08-30 11:00:27.364 [destination = prodb2 , address = x/y:3306 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - I/O error while reading from client socket
java.io.IOException: Unexpected End Stream
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:156) ~[canal.parse-1.0.22.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:70) ~[canal.parse-1.0.22.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:113) [canal.parse-1.0.22.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:210) [canal.parse-1.0.22.jar:na]
        at java.lang.Thread.run(Thread.java:744) [na:1.7.0_45]
2016-08-30 11:00:27.370 [destination = prodb2 , address = x/y:3306 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - dump address x/y:3306 has an error, retrying. caused by
java.io.IOException: Unexpected End Stream
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:156) ~[canal.parse-1.0.22.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:70) ~[canal.parse-1.0.22.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:113) ~[canal.parse-1.0.22.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:210) ~[canal.parse-1.0.22.jar:na]
        at java.lang.Thread.run(Thread.java:744) [na:1.7.0_45]
2016-08-30 11:00:27.371 [destination = prodb2 , address = x/y:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:prodb2[java.io.IOException: Unexpected End Stream
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:156)
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:70)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:113)
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:210)
        at java.lang.Thread.run(Thread.java:744)
]
2016-08-30 11:00:28.554 [destination = prodb2 , address = x/y:3306 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - disconnect address x/y:3306 has an error, retrying., caused by
java.io.IOException: KILL DUMP 369615002 failure:java.io.IOException: ErrorPacket [errorNumber=1094, fieldCount=-1, message=Unknown thread id: 369615002, sqlState=HY000, sqlStateMarker=#]
 with command: KILL CONNECTION 369615002
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlUpdateExecutor.update(MysqlUpdateExecutor.java:49)
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.disconnect(MysqlConnector.java:104)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.disconnect(MysqlConnection.java:60)
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:242)
        at java.lang.Thread.run(Thread.java:744)

**Comment by agapple** [comment]
KILL CONNECTION 建议使用主干打包试试

**Comment by tutulvlv** [comment]
@agapple 您好，我最近也发现了这个问题，您说得主干打包是什么意思，没明白，这个问题您在另一个相同issue里提出的解决方案是打开心跳sql，有具体可行的方案吗，刚接触不久，谢谢啦

**Comment by agapple** [comment]
@tutulvlv 使用1.0.24新版试试

**Comment by shijiebei2009** [comment]
用的1.0.24也是偶尔报这个错误。

`2017-09-15 16:33:17.786 [destination = action_log , address = /127.0.0.2:2020 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - dump address 127.0.0.2/127.0.0.2:2020 has an error, retry
ing. caused by 
java.io.IOException: Unexpected End Stream
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:156) ~[canal.parse-1.0.24.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:70) ~[canal.parse-1.0.24.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:122) ~[canal.parse-1.0.24.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209) ~[canal.parse-1.0.24.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_80]
2017-09-15 16:33:17.786 [destination = action_log , address = /127.0.0.2:2020 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:action_log[java.io.IOException: Unexpected En
d Stream
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:156)
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:70)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:122)
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209)
        at java.lang.Thread.run(Thread.java:745)
]
2017-09-15 16:33:34.137 [destination = action_log , address = /127.0.0.2:2020 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - prepare to find start position just last position
 {"identity":{"slaveId":-1,"sourceAddress":{"address":"127.0.0.2","port":2020}},"postion":{"included":false,"journalName":"mysql-bin.000876","position":1064558972,"serverId":1037,"timestamp":1505464397000}}`

**Comment by shijiebei2009** [comment]
大概几个小时就会重现，不知道是不是客户端引起的？客户端是拉一次->消费->确认，再循环，如果数据在master堆积会有问题吗？

**Comment by pc-fuqq** [comment]
`taojin-warehouse-web-launcher: 2019-05-08 01:30:12.241 [destination = MysqlEventParserFactoryBean.destination , address = 192.168.xxx.xxx/192.168.xxx.xxx:3306 , EventParser] INFO  com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - KILL DUMP 106452 failure
java.io.IOException: ErrorPacket [errorNumber=1094, fieldCount=-1, message=Unknown thread id: 106452, sqlState=HY000, sqlStateMarker=#]
 with command: KILL CONNECTION 106452
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlUpdateExecutor.update(MysqlUpdateExecutor.java:49)
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.disconnect(MysqlConnector.java:113)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.disconnect(MysqlConnection.java:97)
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:307)
        at java.lang.Thread.run(Thread.java:748)`

我也遇到了，最新版1.1.3

**Comment by pc-fuqq** [comment]
> taojin-warehouse-web-launcher: 2019-05-08 01:30:12.241 [destination = MysqlEventParserFactoryBean.destination , address = 192.168.xxx.xxx/192.168.xxx.xxx:3306 , EventParser] INFO com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - KILL DUMP 106452 failure java.io.IOException: ErrorPacket [errorNumber=1094, fieldCount=-1, message=Unknown thread id: 106452, sqlState=HY000, sqlStateMarker=#] with command: KILL CONNECTION 106452 at com.alibaba.otter.canal.parse.driver.mysql.MysqlUpdateExecutor.update(MysqlUpdateExecutor.java:49) at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.disconnect(MysqlConnector.java:113) at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.disconnect(MysqlConnection.java:97) at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:307) at java.lang.Thread.run(Thread.java:748)

我也遇到了，最新版本1.1.3
