### ISSUE TITLE
删除索引的时候为什么会报错？

### ISSUE THREAD

**Issue by ZSH9053** [alibaba/canal#1970]
2019-07-08 18:24:08.021 [MultiStageCoprocessor-other-hub_test-0] WARN  c.a.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta - parse faield : DROP INDEX `order_id_card_info_id_idx` ON `PDD_ORDER_CARD_INFO`
java.lang.NullPointerException: null
        at com.alibaba.fastsql.sql.ast.statement.SQLCreateTableStatement.apply(SQLCreateTableStatement.java:767) ~[fastsql-2.0.0_preview_644.jar:2.0.0_preview_644]
        at com.alibaba.fastsql.sql.repository.SchemaRepository.acceptDropIndex(SchemaRepository.java:959) ~[fastsql-2.0.0_preview_644.jar:2.0.0_preview_644]
        at com.alibaba.fastsql.sql.repository.SchemaRepository$MySqlConsoleSchemaVisitor.visit(SchemaRepository.java:675) ~[fastsql-2.0.0_preview_644.jar:2.0.0_preview_644]
        at com.alibaba.fastsql.sql.ast.statement.SQLDropIndexStatement.accept0(SQLDropIndexStatement.java:86) ~[fastsql-2.0.0_preview_644.jar:2.0.0_preview_644]
        at com.alibaba.fastsql.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:51) ~[fastsql-2.0.0_preview_644.jar:2.0.0_preview_644]
        at com.alibaba.fastsql.sql.repository.SchemaRepository.console(SchemaRepository.java:497) ~[fastsql-2.0.0_preview_644.jar:2.0.0_preview_644]
        at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta.apply(MemoryTableMeta.java:83) ~[canal.parse-1.1.3-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.apply(DatabaseTableMeta.java:154) [canal.parse-1.1.3-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.TableMetaCache.apply(TableMetaCache.java:231) [canal.parse-1.1.3-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseQueryEvent(LogEventConvert.java:269) [canal.parse-1.1.3-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:114) [canal.parse-1.1.3-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:292) [canal.parse-1.1.3-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:246) [canal.parse-1.1.3-SNAPSHOT.jar:na]
        at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168) [disruptor-3.4.2.jar:na]
        at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125) [disruptor-3.4.2.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_80]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_80]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_80]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_80]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_80]

**Comment by agapple** [comment]
1.1.4 主干已经修复

**Comment by helei810304** [comment]
我用1.1.5 了，还是报错
