### ISSUE TITLE
ClientAdapter(Sync RDB)同步至Postgres，如果canalAdapters参数设置多个，会报异常ConcurrentModificationException

### ISSUE THREAD

**Issue by dingqianlong** [alibaba/canal#1974]
## Question

软件清单：
canal.deployer-1.1.1
canal.adapter-1.1.3

问题描述：
使用ClientAdapter(Sync RDB)同步至Postgres数据库，如果canal.adapter/conf/application.yml中canalAdapters参数设置多个instance和groups，RdbSyncService会报异常ConcurrentModificationException，而如果只保留一个就没问题，请问有可能是什么原因，谢谢。

配置明细：
![image](https://user-images.githubusercontent.com/29193829/60939977-75a20c00-a30c-11e9-88aa-579e9445f5e2.png)

异常信息：
2019-07-10 10:50:24.794 [pool-10-thread-1] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.Ru
ntimeException: java.util.ConcurrentModificationException
java.lang.RuntimeException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.util.ConcurrentModificationException
        at com.alibaba.otter.canal.client.adapter.rdb.RdbAdapter.sync(RdbAdapter.java:169)
        at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.batchSync(AbstractCanalAdapterWorker.java:198)
        at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$1(AbstractCanalAdapterWorker.java:62)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$2(AbstractCanalAdapterWorker.java:58)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.util.ConcurrentModificationException
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$sync$2(RdbSyncService.java:127)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.sync(RdbSyncService.java:123)
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.sync(RdbSyncService.java:147)
        at com.alibaba.otter.canal.client.adapter.rdb.RdbAdapter.sync(RdbAdapter.java:166)
        ... 8 common frames omitted
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.util.ConcurrentModificationException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$sync$2(RdbSyncService.java:125)
        ... 12 common frames omitted
Caused by: java.lang.RuntimeException: java.util.ConcurrentModificationException
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$sync$1(RdbSyncService.java:118)
        ... 4 common frames omitted
Caused by: java.util.ConcurrentModificationException: null
        at java.util.ArrayList.forEach(ArrayList.java:1260)
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$sync$1(RdbSyncService.java:110)
        ... 4 common frames omitted
2019-07-10 10:50:24.794 [Thread-8] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - Outer adapter sync failed!  Error sync but ACK!

**Comment by dingqianlong** [comment]
canalAdapters中outerAdapters.key命名保证唯一即可
