### ISSUE TITLE
canal1.1.3同步到hbase（mode:kafka）报错java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by brightsong** [alibaba/canal#1977]
使用canal.adapter-1.1.3将mysql数据同步到hbase上，application.yml配置内容如下：

> canal.conf:
  mode: kafka
  zookeeperHosts: 192.168.206.128:2181
  flatMessage: true
  batchSize: 500
  syncBatchSize: 1000
  retries: 0
  timeout:
  accessKey:
  secretKey:
  srcDataSources:
    defaultDS:
      url: jdbc:mysql://192.168.206.136:3306/can_db?useUnicode=true
      username: canal
      password: canal
  canalAdapters:
   - instance: canal113topic1 # canal instance Name or mq topic name
    groups:
 >    - groupId: g1
      outerAdapters:
>       - name: hbase
        properties:
          hbase.zookeeper.quorum: 192.168.206.128
          hbase.zookeeper.property.clientPort: 2181
          zookeeper.znode.parent: /hbase

 hbase/mytest_person2.yml配置内容为：

> dataSourceKey: defaultDS
> destination: canal113topic1
> groupId: g1
> hbaseMapping:
>   mode: STRING  #NATIVE   #PHOENIX
  destination: canal113topic1
  database: can_db  # 数据库名
  table: user_test     # 数据库表名
  hbaseTable: CAN_DB.USER_TEST2   # HBase表名
  family: CF  # 默认统一Family名称
  uppercaseQualifier: true  # 字段名转大写, 默认为true
  commitBatch: 3000 # 批量提交的大小
  #rowKey: id,type  # 复合字段rowKey不能和columns中的rowKey重复
  columns:
    # 数据库字段:HBase对应字段
    id: ROWKEY LEN:15
    name: NAME
    age: AGE

新建了hbase表 CAN_DB.USER_TEST2，
启动canal、kafka后报错：
`2019-07-10 16:22:14.041 [main] INFO  c.a.o.canal.adapter.launcher.loader.CanalAdapterLoader - Load canal adapter: hbase succeed
2019-07-10 16:22:14.121 [main] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterService - ## something goes wrong when starting up the canal client adapters:
java.lang.NullPointerException: null
        at java.util.Hashtable.put(Hashtable.java:459)
        at com.alibaba.otter.canal.client.kafka.KafkaCanalConnector.<init>(KafkaCanalConnector.java:52)
        at com.alibaba.otter.canal.adapter.launcher.loader.CanalAdapterKafkaWorker.<init>(CanalAdapterKafkaWorker.java:38)
        at com.alibaba.otter.canal.adapter.launcher.loader.CanalAdapterLoader.init(CanalAdapterLoader.java:109)
        at com.alibaba.otter.canal.adapter.launcher.loader.CanalAdapterService.init(CanalAdapterService.java:58)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:365)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:308)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:135)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:422)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1694)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:579)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:501)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$1(AbstractBeanFactory.java:353)
        at org.springframework.cloud.context.scope.GenericScope$BeanLifecycleWrapper.getBean(GenericScope.java:390)
        at org.springframework.cloud.context.scope.GenericScope.get(GenericScope.java:184)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:350)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1089)
        at org.springframework.cloud.context.scope.refresh.RefreshScope.eagerlyInitialize(RefreshScope.java:126)
        at org.springframework.cloud.context.scope.refresh.RefreshScope.start(RefreshScope.java:117)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
      `

**Comment by brightsong** [comment]
canal113topic1 是kafka的topic名

**Comment by yby271621060** [comment]
您好，您这个问题解决了吗

**Comment by brightsong** [comment]
没有解决。你所用的canal版本也是这个吗？github上解决问题不及时了。

在 2019-10-10 19:29:49，"杨小昱" <notifications@github.com> 写道：


您好，您这个问题解决了吗

**Comment by yby271621060** [comment]
我是1.1.4版本，我又重新改了遍配置文件，重启了下服务，莫名奇妙的好了，也不知道改了点啥，莫名其妙的不好，又莫名其妙的好了，下午再看看，看看能不能复现一下问题，现在一脸懵

**Comment by haoxuey** [comment]
你好,您的问题解决了吗?和你一样的错误

**Comment by yby271621060** [comment]
shell的配置，对空格要求比较严格，别用tab键，我的是空格和tab键的原因

**Comment by brightsong** [comment]
没有解决，后来一直没有看

在 2019-11-15 15:43:22，"haoxuey" <notifications@github.com> 写道：


你好,您的问题解决了吗?和你一样的错误

**Comment by haoxuey** [comment]
谢谢,我想把业务库数据实时更新到hbase,您后来采用的sparkstreaming消费kafka的方案还是其他更有效的方案呢?求助###

**Comment by yby271621060** [comment]
你看下canal-adapter，不用streaming，它支持server直接到hbase，配置一下就好了，不用代码开发

**Comment by haoxuey** [comment]
> shell的配置，对空格要求比较严格，别用tab键，我的是空格和tab键的原因

请问您用的1.1.4版本吗?此外,您说的shell配置指的是两个配置文件(.ylm)的配置吗?

**Comment by haoxuey** [comment]
> 你看下canal-adapter，不用streaming，它支持server直接到hbase，配置一下就好了，不用代码开发
直接mysql到Hbase,不通过kafka了吗?

**Comment by yby271621060** [comment]
对的，1.1.4的版本，instance.properties

**Comment by haoxuey** [comment]
非常感谢!!我去升级一下版本~~

**Comment by yby271621060** [comment]
没事没事

**Comment by brightsong** [comment]
问一下，你升级成1.1.4版本可以了吗，需要adpter和developer都配置吗。中间通过kafka了吗

在 2019-11-15 16:03:40，"haoxuey" <notifications@github.com> 写道：


非常感谢!!我去升级一下版本~~

**Comment by brightsong** [comment]
> 你看下canal-adapter，不用streaming，它支持server直接到hbase，配置一下就好了，不用代码开发

升级成了1.1.4版本，我是在canal-adapter配置- name: hbase，然后启动canal-developer和canal-adapter，还是报NullPointerException错误；
- instance: 配置的是kakfa的topic名。
