### ISSUE TITLE
canal同步报错

### ISSUE THREAD

**Issue by kamactor** [alibaba/canal#1985]
你好，canal启动后，使用canal-go消费数据，canal端报以下错误，测试过1.1.3 和1.1.4都出现相同情况，请问这是什么原因？

2019-07-12 09:19:55.078 [destination = example , address = rdsxxxxxxxxxxxx:3306 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - I/O error while reading from client socket
java.io.IOException: EOF encountered.
	at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:113) ~[canal.parse.driver-1.1.4-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:174) ~[canal.parse-1.1.4-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:77) ~[canal.parse-1.1.4-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:235) [canal.parse-1.1.4-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:257) [canal.parse-1.1.4-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_74]
2019-07-12 09:19:55.079 [destination = example , address = rdsxxxxxxxxxxxx:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address rdsxxxxxxxxxxxx:3306 has an error, retrying. caused by 
java.io.IOException: EOF encountered.
	at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:113) ~[canal.parse.driver-1.1.4-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:174) ~[canal.parse-1.1.4-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:77) ~[canal.parse-1.1.4-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:235) ~[canal.parse-1.1.4-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:257) ~[canal.parse-1.1.4-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_74]
2019-07-12 09:19:55.080 [destination = example , address = rdsxxxxxxxxxxxx:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[java.io.IOException: EOF encountered.
	at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:113)
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:174)
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:77)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:235)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:257)
	at java.lang.Thread.run(Thread.java:745)
]

**Comment by zgl1011** [comment]
解决了吗？

**Comment by agapple** [comment]
destination:example[java.io.IOException: EOF encountered.

MySQL主动断链，会自动重连恢复

**Comment by VincentLiSH** [comment]
应该是canal订阅binlog过程 相当于是mysql向canal写数据，
当遇到了某个特别大数据量的事务（例如“create table xxx_init as select * from xxx”），mysql写超时 断开了连接，set global show variables like '%timeout'; 发现net_write_timeout默认60秒；
set global net_write_timeout=28800 改为8小时

https://blog.csdn.net/cuizhu0832/article/details/100349359

**Comment by gangade** [comment]
也可能是 max_allowed_packet 太低的原因。1.1.5碰到过，MySQL5.7侧报错：Aborted connection 2012476 to db: 'unconnected' user: 'app_xxxx_xxxx' host: '10.xxx.xxx.xxx' (Got an error reading co
mmunication packets)
