### ISSUE TITLE
同步到es 出错，错误信息能给详细点吗？

### ISSUE THREAD

**Issue by bells** [alibaba/canal#1989]
2019-07-12 12:39:05.492 [pool-2-thread-1] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - java.lang.NullPointerException
java.lang.RuntimeException: java.lang.NullPointerException
	at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.sync(ESSyncService.java:113)
	at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.sync(ESSyncService.java:61)
	at com.alibaba.otter.canal.client.adapter.es.ESAdapter.sync(ESAdapter.java:176)
	at com.alibaba.otter.canal.client.adapter.es.ESAdapter.sync(ESAdapter.java:155)
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.batchSync(AbstractCanalAdapterWorker.java:198)
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$1(AbstractCanalAdapterWorker.java:62)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$2(AbstractCanalAdapterWorker.java:58)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
	at com.alibaba.otter.canal.client.adapter.es.support.ESTemplate.insert(ESTemplate.java:75)
	at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.singleTableSimpleFiledInsert(ESSyncService.java:445)
	at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.insert(ESSyncService.java:136)
	at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.sync(ESSyncService.java:96)
	... 11 common frames omitted
2019-07-12 12:39:05.492 [Thread-4] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - Outer adapter sync failed!  Error sync but ACK!

这错误信息我真看不出哪里有问题！

**Comment by Ecli2h** [comment]
请问是如何解决的，我也遇到了同样的错误

**Comment by bells** [comment]
> 请问是如何解决的，我也遇到了同样的错误

记得是配置问题，再检查下相应的配置吧

**Comment by Ecli2h** [comment]
> > 请问是如何解决的，我也遇到了同样的错误
> 
> 记得是配置问题，再检查下相应的配置吧

好的，谢谢

**Comment by shuhong123** [comment]
@bells 这个怎么解决的，我刚开始运行好好地，运行一段时间会出现这个问题

**Comment by LuckyManGit** [comment]
@shuhong123  兄弟解决了吗。我也是运行一段时间就出这个问题。重启就好了

**Comment by sweetspot00** [comment]
同问是怎么解决的
