### ISSUE TITLE
MysqlConnection的seek方法和dump方法会报NullPointerException

### ISSUE THREAD

**Issue by kevinKaiF** [alibaba/canal#201]
seek方法和dump方法都有初始化LogContext
``` java
LogContext context = new LogContext();
```
但是在decode的时候会报NullPointerException
建议分别添加
``` java
context.setLogPosition(new LogPosition(binlogfilename));
```

**Comment by agapple** [comment]
能给更详细的异常堆栈不？

**Comment by kevinKaiF** [comment]
我运行的是MysqlEventParserTest的test_timestamp方法
``` java
16:06:16.145 [destination = null , address = /10.4.0.20:3306 , EventParser] INFO  c.a.o.c.p.i.mysql.MysqlConnection - COM_BINLOG_DUMP with position:BinlogDumpCommandPacket[binlogPosition=4,slaveServerId=3344,binlogFileName=mysql-bin.000047,command=18]
16:06:16.146 [destination = null , address = /10.4.0.20:3306 , EventParser] WARN  c.a.o.c.p.i.mysql.MysqlEventParser - the binlogfile:mysql-bin.000047 doesn't exist, to continue to search the next binlogfile , caused by java.lang.NullPointerException
	at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:162)
	at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:106)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.seek(MysqlConnection.java:96)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findAsPerTimestampInSpecificLogFile(MysqlEventParser.java:1101)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findByStartTimeStamp(MysqlEventParser.java:539)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPositionInternal(MysqlEventParser.java:375)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPosition(MysqlEventParser.java:310)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:162)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by agapple** [comment]
https://github.com/alibaba/canal/pull/203
