### ISSUE TITLE
docker下canal运行一段时间报错

### ISSUE THREAD

**Issue by kervin521** [alibaba/canal#2018]
## Question

2019-07-19 10:31:44.126 [destination = example , address = mysql/172.19.0.2:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> find start position successfully, EntryPosition[included=false,journalName=mysql-bin.000032,position=93461075,serverId=1,gtid=,timestamp=1563359494000] cost : 6ms , the next step is binlog dump
2019-07-19 10:31:44.170 [destination = example , address = mysql/172.19.0.2:3306 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - I/O error while reading from client socket
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = binlog truncated in the middle of event; consider out of disk space on master; the first event 'mysql-bin.000032' at 93461075, the last event read from './mysql-bin.000032' at 123, the last byte read from './mysql-bin.000032' at 93461094.
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102) ~[canal.parse-1.1.3.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:235) [canal.parse-1.1.3.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:257) [canal.parse-1.1.3.jar:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
2019-07-19 10:31:44.170 [destination = example , address = mysql/172.19.0.2:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address mysql/172.19.0.2:3306 has an error, retrying. caused by
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = binlog truncated in the middle of event; consider out of disk space on master; the first event 'mysql-bin.000032' at 93461075, the last event read from './mysql-bin.000032' at 123, the last byte read from './mysql-bin.000032' at 93461094.
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102) ~[canal.parse-1.1.3.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:235) ~[canal.parse-1.1.3.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:257) ~[canal.parse-1.1.3.jar:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
2019-07-19 10:31:44.171 [destination = example , address = mysql/172.19.0.2:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = binlog truncated in the middle of event; consider out of disk space on master; the first event 'mysql-bin.000032' at 93461075, the last event readfrom './mysql-bin.000032' at 123, the last byte read from './mysql-bin.000032' at 93461094.
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:235)
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:257)
        at java.lang.Thread.run(Thread.java:748)
]

**Comment by kervin521** [comment]
![image](https://user-images.githubusercontent.com/9798724/61521809-a3413080-aa43-11e9-8653-03de957197c8.png)

**Comment by agapple** [comment]
errmsg = binlog truncated in the middle of event; consider out of disk space on master; the first event 'mysql-bin.000032' at 93461075, the last event read from './mysql-bin.000032' at 123, the last byte read from './mysql-bin.000032' at 93461094.

位点错误，重置一下binlog
