### ISSUE TITLE
canal连接mysql5.5报错

### ISSUE THREAD

**Issue by jorchen** [alibaba/canal#2061]
canal.1.1.4 启动时报错（数据库为mysql5.5) 。错误信息如下： 

2019-08-12 15:21:28.610 [destination = example , address = /127.0.0.1:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address /127.0.0.1:3306 has an error, retrying. caused by
com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: connect /127.0.0.1:3306 failure
Caused by: java.io.IOException: connect /127.0.0.1:3306 failure
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:83) ~[canal.parse.driver-1.1.4-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.connect(MysqlConnection.java:89) ~[canal.parse-1.1.4-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.preDump(MysqlEventParser.java:86) ~[canal.parse-1.1.4-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:175) ~[canal.parse-1.1.4-SNAPSHOT.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66]
Caused by: java.lang.NullPointerException: null
        at java.io.OutputStream.write(OutputStream.java:75) ~[na:1.8.0_66]
        at com.alibaba.otter.canal.parse.driver.mysql.packets.client.AuthSwitchResponsePacket.toBytes(AuthSwitchResponsePacket.java:17) ~[canal.parse.driver-1.1.4-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.negotiate(MysqlConnector.java:241) ~[canal.parse.driver-1.1.4-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:80) ~[canal.parse.driver-1.1.4-SNAPSHOT.jar:na]
        ... 4 common frames omitted

**Comment by jorchen** [comment]
补充一下： instance.properties 文件中的mysql用户名和密码， 在mysql client 实测可正常连接数据库。

**Comment by yetHandsome** [comment]
你是配置的投递到 kafka 了吗？

**Comment by jorchen** [comment]
> 你是配置的投递到 kafka 了吗？
没有呢。
# tcp, kafka, RocketMQ
canal.serverMode = tcp

**Comment by yetHandsome** [comment]
我也出现了，我出现的原因是没有删除默认配置，你看看是不是跟我一个情况，看https://github.com/alibaba/canal/issues/2063

**Comment by jorchen** [comment]
@yetHandsome ，删除的是数据库实例。 删除example是可以运行的，但你没有去读取指定数据库binlog，只是启动了cannal的服务，没有实际业务价值。

**Comment by yetHandsome** [comment]
那我们可能不是一个问题，我是 复制了4份 example 分别为 s1,s2,s3,s4
 conf/canal.properties 里面的 canal.destinations = s1,s2,s3,s4
然后就报错链接不上
[destination = example , address = /127.0.0.1:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address /127.0.0.1:3306 has an error, retrying. caused by

我将 example文件夹删除 问题就消失了

**Comment by jorchen** [comment]
有专家来解答一下么？

**Comment by agapple** [comment]
估计是配置问题，按照QuickStart来吧

**Comment by jorchen** [comment]
就是按照quickstart来的啊

**Comment by jorchen** [comment]
> 估计是配置问题，按照QuickStart来吧

能帮忙看一下是什么配置的问题么？ @agapple
