### ISSUE TITLE
貌似conf/canal.properties 里面的 canal.destinations = s1,s2,s3,s4  不是实际决定读那些配置

### ISSUE THREAD

**Issue by yetHandsome** [alibaba/canal#2063]
## Question
貌似conf/canal.properties 里面的 canal.destinations = s1,s2,s3,s4 
不是实际决定读那些配置，我配置的时候那个默认的 example  配置没有删除，然后就报下面错误
/127.0.0.1:3306 has an error, retrying. caused by
百思不解，我始终找不到哪里在链接127.0.0.1:3306，最后怀疑是 读了 example 文件，于是删除了 example 之后就正常了，之前报错如下

2019-08-12 23:41:00.902 [main] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table black filter : ^mysql..*$
2019-08-12 23:41:00.923 [destination = s2 , address = /192.168.8.38:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> begin to find start position, it will be long time for reset or first position
2019-08-12 23:41:00.923 [destination = s2 , address = /192.168.8.38:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - prepare to find start position just show master status
2019-08-12 23:41:00.929 [main] INFO  com.alibaba.otter.canal.deployer.CanalStater - ## the canal server is running now ......
2019-08-12 23:41:01.405 [destination = s3 , address = /192.168.8.39:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> find start position successfully, EntryPosition[included=false,journalName=mysql-bin.000038,position=4,serverId=39,gtid=<null>,timestamp=1565581862000] cost : 772ms , the next step is binlog dump
2019-08-12 23:41:01.405 [destination = s2 , address = /192.168.8.38:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> find start position successfully, EntryPosition[included=false,journalName=mysql-bin.000016,position=4,serverId=38,gtid=<null>,timestamp=1565582007000] cost : 464ms , the next step is binlog dump
2019-08-12 23:41:01.406 [destination = s4 , address = /192.168.8.40:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> find start position successfully, EntryPosition[included=false,journalName=mysql-bin.000012,position=42301,serverId=23,gtid=,timestamp=1565621498000] cost : 754ms , the next step is binlog dump
2019-08-12 23:41:01.516 [destination = s1 , address = /192.168.8.37:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> find start position successfully, EntryPosition[included=false,journalName=mysql-bin.000047,position=18308279,serverId=37,gtid=,timestamp=1565624448000] cost : 676ms , the next step is binlog dump
2019-08-12 23:41:17.353 [destination = example , address = /127.0.0.1:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address /127.0.0.1:3306 has an error, retrying. caused by
com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: connect /127.0.0.1:3306 failure
Caused by: java.io.IOException: connect /127.0.0.1:3306 failure
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:83) ~[canal.parse.driver-1.1.4-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.connect(MysqlConnection.java:89) ~[canal.parse-1.1.4-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.preDump(MysqlEventParser.java:86) ~[canal.parse-1.1.4-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:175) ~[canal.parse-1.1.4-SNAPSHOT.jar:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_222]

**Comment by jorchen** [comment]
把example 删除， 是可以正常运行了。 但是canal没有数据库实例监控了啊，怎么读取指定数据库的binlog ？

**Comment by yetHandsome** [comment]
那我们可能不是一个问题，我是 复制了4份 example 分别为 s1,s2,s3,s4
conf/canal.properties 里面的 canal.destinations = s1,s2,s3,s4
然后就报错链接不上
[destination = example , address = /127.0.0.1:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address /127.0.0.1:3306 has an error, retrying. caused by

我将 example文件夹删除 问题就消失了
