### ISSUE TITLE
canal连接数据库IO异常:EOF encountered

### ISSUE THREAD

**Issue by karlie93** [alibaba/canal#2065]
![image](https://user-images.githubusercontent.com/54050952/62912267-02336480-bdba-11e9-9f79-eefe01e87478.png)

pid:33 nid:3 exception:canal::java.io.IOException: EOF encountered.
    at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:56)
    at com.alibaba.otter.canal.parse.driver.mysql.utils.PacketManager.readHeader(PacketManager.java:12)
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.sendRegisterSlave(MysqlConnection.java:280)
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:148)
    at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:266)
    at java.lang.Thread.run(Thread.java:748)

**Comment by karlie93** [comment]
otter同步数据时，canal连接报错，错误信息如上，直接连接数据库是没有问题的，

**Comment by agapple** [comment]
EOF encountered，MySQL主动断链，canal会自动重连来恢复

**Comment by VincentLiSH** [comment]
应该是canal订阅binlog过程 相当于是mysql向canal写数据，
当遇到了某个特别大数据量的事务（例如“create table xxx_init as select * from xxx”），mysql写超时 断开了连接，set global show variables like '%timeout'; 发现net_write_timeout默认60秒；
set global net_write_timeout=28800 改为8小时

https://blog.csdn.net/cuizhu0832/article/details/100349359
