### ISSUE TITLE
一个日志疑问

### ISSUE THREAD

**Issue by lulu2panpan** [alibaba/canal#207]
首先看日志：
`2016-09-27 11:01:06:com.alibaba.otter.canal.client.impl.ClusterCanalConnector.subscribe(ClusterCanalConnector.java:110) - something goes wrong when subscribing from server:null
com.alibaba.otter.canal.protocol.exception.CanalClientException: failed to subscribe with reason: something goes wrong with channel:[id: 0x111fe04e, /10.204.12.79:47450 => /10.204.246.102:11111], exceptio
n=com.alibaba.otter.canal.server.exception.CanalServerException: destination:ucarobd should start first

```
    at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.subscribe(SimpleCanalConnector.java:203)
    at com.alibaba.otter.canal.client.impl.ClusterCanalConnector.subscribe(ClusterCanalConnector.java:106)
    at com.alibaba.otter.canal.client.impl.ClusterCanalConnector.subscribe(ClusterCanalConnector.java:99)
    at com.ucar.dep.exchange.binlog.AbstractCanalClient$ProcessThread.process(AbstractCanalClient.java:142)
    at com.ucar.dep.exchange.binlog.AbstractCanalClient$ProcessThread.run(AbstractCanalClient.java:134)`
```

通过分析代码，“should start first”这样的异常信息在subscribing的时候是不会触发的，可是我的日志文件里出现了这样的日志，分析了一天代码了，让我百思不得其解，请问作者能提供点儿什么思路吗？

**Comment by agapple** [comment]
这异常一般是server端出现了重启导致，比如开启了scan=true，扫描到了文件变化，自动重载，客户端增加重试机制就好了

**Comment by lulu2panpan** [comment]
这个异常产生的原因我清楚
我感到奇怪的是：通过查看堆栈信息，是在subscribe方法中触发的这个异常，我查看了客户端和server端的代码，在subscribe的时候没有checkStart的判断，也就是说这个“should start first”异常不应该在此出现

**Comment by agapple** [comment]
客户端的第一次subscribe会触发服务端进行start操作
