### ISSUE TITLE
uncategorized SQLException for SQL []; SQL state [HY000]; error code [50000];

### ISSUE THREAD

**Issue by yomosir** [alibaba/canal#2080]
### environment

* canal version  v1.1.1
* mysql version 5.5.18.1

### Issue Description
canal-server 突然报错，已经正常运行了很长时间了，然后突然报错了

If there is an exception, please attach the exception trace:

 retrying. caused by
com.alibaba.otter.canal.parse.exception.CanalParseException: apply failed caused by : SqlMapClient operation; uncategorized SQLException for SQL []; SQL state [HY000]; error code [50000];
--- The error occurred in spring/tsdb/sql-map/sqlmap_snapshot.xml.
--- The error occurred while applying a parameter map.
--- Check the meta_snapshot.findByTimestamp-InlineParameterMap.
--- Check the statement (query failed).
--- Cause: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: This map is closed [1.4.196/4]" [50000-196]; nested exception is com.ibatis.common.jdbc.exception.NestedSQLException:
--- The error occurred in spring/tsdb/sql-map/sqlmap_snapshot.xml.
--- The error occurred while applying a parameter map.
--- Check the meta_snapshot.findByTimestamp-InlineParameterMap.
--- Check the statement (query failed).
--- Cause: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: This map is closed [1.4.196/4]" [50000-196]
Caused by: org.springframework.jdbc.UncategorizedSQLException: SqlMapClient operation; uncategorized SQLException for SQL []; SQL state [HY000]; error code [50000];
--- The error occurred in spring/tsdb/sql-map/sqlmap_snapshot.xml.
--- The error occurred while applying a parameter map.
--- Check the meta_snapshot.findByTimestamp-InlineParameterMap.
--- Check the statement (query failed).
--- Cause: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: This map is closed [1.4.196/4]" [50000-196]; nested exception is com.ibatis.common.jdbc.exception.NestedSQLException:
--- The error occurred in spring/tsdb/sql-map/sqlmap_snapshot.xml.
--- The error occurred while applying a parameter map.
--- Check the meta_snapshot.findByTimestamp-InlineParameterMap.
--- Check the statement (query failed).
--- Cause: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: This map is closed [1.4.196/4]" [50000-196]
Caused by: org.springframework.jdbc.UncategorizedSQLException: SqlMapClient operation; uncategorized SQLException for SQL []; SQL state [HY000]; error code [50000];
--- The error occurred in spring/tsdb/sql-map/sqlmap_snapshot.xml.
--- The error occurred while applying a parameter map.
--- Check the meta_snapshot.findByTimestamp-InlineParameterMap.
--- Check the statement (query failed).
--- Cause: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: This map is closed [1.4.196/4]" [50000-196]; nested exception is com.ibatis.common.jdbc.exception.NestedSQLException:
--- The error occurred in spring/tsdb/sql-map/sqlmap_snapshot.xml.
--- The error occurred while applying a parameter map.
--- Check the meta_snapshot.findByTimestamp-InlineParameterMap.
--- Check the statement (query failed).
--- Cause: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: This map is closed [1.4.196/4]" [50000-196]
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:83) ~[spring-jdbc-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80) ~[spring-jdbc-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80) ~[spring-jdbc-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.orm.ibatis.SqlMapClientTemplate.execute(SqlMapClientTemplate.java:206) ~[spring-orm-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.orm.ibatis.SqlMapClientTemplate.queryForObject(SqlMapClientTemplate.java:271) ~[spring-orm-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.dao.MetaSnapshotDAO.findByTimestamp(MetaSnapshotDAO.java:29) ~[canal.parse-1.1.1.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.buildMemFromSnapshot(DatabaseTableMeta.java:347) ~[canal.parse-1.1.1.jar:na]
at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:135) ~[canal.parse-1.1.1.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:87) ~[canal.parse-1.1.1.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:190) ~[canal.parse-1.1.1.jar:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_222]
Caused by: com.ibatis.common.jdbc.exception.NestedSQLException:
--- The error occurred in spring/tsdb/sql-map/sqlmap_snapshot.xml.
--- The error occurred while applying a parameter map.
--- Check the meta_snapshot.findByTimestamp-InlineParameterMap.
--- Check the statement (query failed).
--- Cause: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: This map is closed [1.4.196/4]" [50000-196]
at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryWithCallback(MappedStatement.java:201) ~[ibatis-sqlmap-2.3.4.726.jar:na]
        at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryForObject(MappedStatement.java:120) ~[ibatis-sqlmap-2.3.4.726.jar:na]
        at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForObject(SqlMapExecutorDelegate.java:518) ~[ibatis-sqlmap-2.3.4.726.jar:na]
        at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForObject(SqlMapExecutorDelegate.java:493) ~[ibatis-sqlmap-2.3.4.726.jar:na]
        at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.queryForObject(SqlMapSessionImpl.java:106) ~[ibatis-sqlmap-2.3.4.726.jar:na]
        at org.springframework.orm.ibatis.SqlMapClientTemplate$1.doInSqlMapClient(SqlMapClientTemplate.java:273) ~[spring-orm-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        at org.springframework.orm.ibatis.SqlMapClientTemplate.execute(SqlMapClientTemplate.java:203) ~[spring-orm-3.2.18.RELEASE.jar:3.2.18.RELEASE]
        ... 7 common frames omitted
Caused by: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: This map is closed [1.4.196/4]" [50000-196]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:345) ~[h2-1.4.196.jar:1.4.196]
        at org.h2.message.DbException.get(DbException.java:168) ~[h2-1.4.196.jar:1.4.196]
        at org.h2.message.DbException.convert(DbException.java:295) ~[h2-1.4.196.jar:1.4.196]
        at org.h2.message.DbException.toSQLException(DbException.java:268) ~[h2-1.4.196.jar:1.4.196]
        at org.h2.message.TraceObject.logAndConvert(TraceObject.java:352) ~[h2-1.4.196.jar:1.4.196]
        at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:220) ~[h2-1.4.196.jar:1.4.196]
        at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:498) ~[druid-1.1.9.jar:1.1.9]
        at com.ibatis.sqlmap.engine.execution.SqlExecutor.executeQuery(SqlExecutor.java:185) ~[ibatis-sqlmap-2.3.4.726.jar:na]
at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.sqlExecuteQuery(MappedStatement.java:221) ~[ibatis-sqlmap-2.3.4.726.jar:na]
        at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryWithCallback(MappedStatement.java:189) ~[ibatis-sqlmap-2.3.4.726.jar:na]
        ... 13 common frames omitted
Caused by: java.lang.IllegalStateException: This map is closed [1.4.196/4]
        at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:765) ~[h2-1.4.196.jar:1.4.196]
        at org.h2.mvstore.MVMap.beforeWrite(MVMap.java:1044) ~[h2-1.4.196.jar:1.4.196]
        at org.h2.mvstore.MVMap.remove(MVMap.java:542) ~[h2-1.4.196.jar:1.4.196]
        at org.h2.store.LobStorageMap.removeLob(LobStorageMap.java:342) ~[h2-1.4.196.jar:1.4.196]
        at org.h2.store.LobStorageMap.removeLob(LobStorageMap.java:335) ~[h2-1.4.196.jar:1.4.196]
        at org.h2.value.ValueLobDb.remove(ValueLobDb.java:233) ~[h2-1.4.196.jar:1.4.196]
        at org.h2.engine.Session.removeTemporaryLobs(Session.java:702) ~[h2-1.4.196.jar:1.4.196]
        at org.h2.engine.Session.commit(Session.java:637) ~[h2-1.4.196.jar:1.4.196]
        at org.h2.command.Command.stop(Command.java:156) ~[h2-1.4.196.jar:1.4.196]
        at org.h2.command.Command.executeQuery(Command.java:231) ~[h2-1.4.196.jar:1.4.196]
        at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:200) ~[h2-1.4.196.jar:1.4.196]
        ... 17 common frames omitted

**Comment by yomosir** [comment]
然后重启之后，服务就正常了
