### ISSUE TITLE
 Load canal adapter: es failed

### ISSUE THREAD

**Issue by 2gamayibuxulong** [alibaba/canal#2084]
## Question
错误描述：
Load canal adapter: es failed
java.lang.RuntimeException: java.lang.NullPointerException

Caused by: java.lang.NullPointerException: null
        at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
        at com.alibaba.otter.canal.client.adapter.es.ESAdapter.init(ESAdapter.java:96)

1、我做的是通过canal同步mysql数据至ES
2、在能够正常同步基础上 我关停了ES
3、重启ES 发现无法进行正常同步
4、重启ES、Kibana、canal-server均正常，canal-adapter 出现上述日志

**Comment by Arthurker** [comment]
我也有同样的问题，请问你是怎么解决的？

**Comment by nothing-do** [comment]
楼上解决问题了吗  我已经反复检查了配置 还是没找到原因。
