### ISSUE TITLE
canal突然出现这个错误不停的刷日志

### ISSUE THREAD

**Issue by YearnForFreedom** [alibaba/canal#2112]
2019-08-28 14:28:21.127 [destination = example , address = /172.16.10.50:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address /172.16.10.50:3306 has an error, retrying. caused by 
com.alibaba.fastsql.sql.parser.ParserException: illegal sql expr : cncertcc_db_1.2, pos 15, line 1, column 14, token LITERAL_FLOAT
	at com.alibaba.fastsql.sql.SQLUtils.toSQLExpr(SQLUtils.java:258) ~[fastsql-2.0.0_preview_855.jar:2.0.0_preview_855]
	at com.alibaba.fastsql.sql.repository.Schema.setName(Schema.java:77) ~[fastsql-2.0.0_preview_855.jar:2.0.0_preview_855]
	at com.alibaba.fastsql.sql.repository.SchemaRepository.setDefaultSchema(SchemaRepository.java:130) ~[fastsql-2.0.0_preview_855.jar:2.0.0_preview_855]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta.apply(MemoryTableMeta.java:72) ~[canal.parse-1.1.3.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.dumpTableMeta(DatabaseTableMeta.java:234) ~[canal.parse-1.1.3.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:180) ~[canal.parse-1.1.3.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:106) ~[canal.parse-1.1.3.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:192) ~[canal.parse-1.1.3.jar:na]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_211]

**Comment by agapple** [comment]
cncertcc_db_1.2，你这个库名里还带有特殊的点号？

**Comment by YearnForFreedom** [comment]
> cncertcc_db_1.2，你这个库名里还带有特殊的点号？

公司测试环境的镜像库标识版本的，不过这个错误跟库名没有关系吧？

**Comment by zackzhangzz** [comment]
是库名带小数点的问题么？我也碰到问题了

**Comment by YearnForFreedom** [comment]
> 是库名带小数点的问题么？我也碰到问题了

#canal.instance.tsdb.spring.xml = classpath:spring/tsdb/h2-tsdb.xml
#canal.instance.tsdb.spring.xml = classpath:spring/tsdb/mysql-tsdb.xml
canal.properties里把这两行注掉了

**Comment by lxf-NewBanker** [comment]
是的，我把数据库中所有包含小数点的库都删掉，就好了。
