### ISSUE TITLE
Adapter同步到ES出现数据丢失

### ISSUE THREAD

**Issue by 1071746754** [alibaba/canal#2126]
现象：
       1.1.3版本，用es-adapter将rdb数据同步到ES。
       binlog已解析成功，但是数据未同步到ES，数据丢失，同步ES这一块在更新数据量变大的时候同步是否有存在问题

**Comment by 1071746754** [comment]
java.lang.RuntimeException: java.lang.RuntimeException: java.util.ConcurrentModificationException
        at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.sync(ESSyncService.java:112) ~[na:na]
        at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.sync(ESSyncService.java:60) ~[na:na]
        at com.alibaba.otter.canal.client.adapter.es.ESAdapter.sync(ESAdapter.java:168) ~[na:na]
        at com.alibaba.otter.canal.client.adapter.es.ESAdapter.sync(ESAdapter.java:148) ~[na:na]
        at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.batchSync(AbstractCanalAdapterWorker.java:198) ~[client-adapter.launcher-1.1.3-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$1(AbstractCanalAdapterWorker.java:62) ~[client-adapter.launcher-1.1.3-SNAPSHOT.jar:na]
        at java.util.ArrayList.forEach(ArrayList.java:1249) ~[na:1.8.0_144]
        at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$2(AbstractCanalAdapterWorker.java:58) ~[client-adapter.launcher-1.1.3-SNAPSHOT.jar:na]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_144]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_144]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_144]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_144]
Caused by: java.lang.RuntimeException: java.util.ConcurrentModificationException
        at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.lambda$mainTableInsert$3(ESSyncService.java:484) ~[na:na]
        at com.alibaba.otter.canal.client.adapter.es.support.ESSyncUtil.sqlRS(ESSyncUtil.java:314) ~[na:na]
        at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.mainTableInsert(ESSyncService.java:467) ~[na:na]
        at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.insert(ESSyncService.java:139) ~[na:na]
        at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.sync(ESSyncService.java:95) ~[na:na]
        ... 11 common frames omitted
Caused by: java.util.ConcurrentModificationException: null
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[na:1.8.0_144]
        at java.util.ArrayList$Itr.next(ArrayList.java:851) ~[na:1.8.0_144]
        at org.elasticsearch.action.bulk.BulkRequest.writeTo(BulkRequest.java:599) ~[na:na]
        at org.elasticsearch.transport.TcpTransport.buildMessage(TcpTransport.java:1236) ~[na:na]
        at org.elasticsearch.transport.TcpTransport.sendRequestToChannel(TcpTransport.java:1108) ~[na:na]
        at org.elasticsearch.transport.TcpTransport.access$1700(TcpTransport.java:122) ~[na:na]
        at org.elasticsearch.transport.TcpTransport$NodeChannels.sendRequest(TcpTransport.java:482) ~[na:na]
        at org.elasticsearch.transport.TransportService.sendRequestInternal(TransportService.java:598) ~[na:na]
        at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:518) ~[na:na]
        at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:506) ~[na:na]
        at org.elasticsearch.action.TransportActionNodeProxy.execute(TransportActionNodeProxy.java:51) ~[na:na]
        at org.elasticsearch.client.transport.TransportProxyClient.lambda$execute$0(TransportProxyClient.java:60) ~[na:na]
        at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:250) ~[na:na]
        at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:60) ~[na:na]

**Comment by okamiv** [comment]
同样遇到了这个问题，求解

**Comment by yangyiweigege** [comment]
你这个问题我遇到过类似的。你贴一下你的 adapter-client application.yml的配置 我帮你看看
canal.conf:
  canalServerHost: 127.0.0.1:11111
  batchSize: 500
  syncBatchSize: 1000
  retries: 0
  timeout:
  mode: tcp 
  srcDataSources:
    defaultDS:
      url: jdbc:mysql://127.0.0.1:3306/mytest?useUnicode=true
      username: root
      password: 121212
  canalAdapters:
  - instance: example 
    groups:
    - groupId: g1
      outerAdapters:
      - name: es
        hosts: 127.0.0.1:9300               # es 集群地址, 逗号分隔
        properties:
          cluster.name: elasticsearch       # es cluster namecanal.conf:
  canalServerHost: 127.0.0.1:11111
  batchSize: 500
  syncBatchSize: 1000
  retries: 0
  timeout:
  mode: tcp 
  srcDataSources:
    defaultDS:
      url: jdbc:mysql://127.0.0.1:3306/mytest?useUnicode=true
      username: root
      password: 121212
  canalAdapters:
  - instance: example 
    groups:
    - groupId: g1
      outerAdapters:
      - name: es
        hosts: 127.0.0.1:9300               # es 集群地址, 逗号分隔
        properties:
          cluster.name: elasticsearch       # es cluster name

就是贴出如上代码 就行。我确定一下 是不是那个问题。

**Comment by okamiv** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        拜托帮忙看看server:  port: 8081spring:  jackson:    date-format: yyyy-MM-dd HH:mm:ss    time-zone: GMT+8    default-property-inclusion: non_nullcanal.conf:  mode: tcp  zookeeperHosts: 192.168.1.173:2181  batchSize: 500  syncBatchSize: 1000  retries: 3  timeout:  accessKey:  secretKey:  srcDataSources:    defaultDS:      url: jdbc:mysql://192.168.1.199:38383/test?useUnicode=true      username: canal      password: canal    defaultDS2:      url: jdbc:mysql://192.168.1.199:38383/newtest?useUnicode=true      username: canal      password: canal  canalAdapters:  - instance: example_01    groups:    - groupId: g1      outerAdapters:      - name: logger      - name: es        hosts: 192.168.1.209:9200,192.168.1.210:9200,192.168.1.211:9200        properties:          mode: rest          cluster.name: test-application  - instance: example_02    groups:    - groupId: g2      outerAdapters:      - name: logger      - name: es        hosts: 192.168.1209:9200,192.168.1.210:9200,192.168.1.211:9200        properties:          mode: rest          cluster.name: test-application
            
        
    
    
        
            
        
    
    
      
    
        
            
    
        
            
                
                    
                        
                    
                    
                        
                            Okami
                            
                            
                                
                                    732726554@qq.com
                                
                        
                    
                
            
        
    

        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2019年09月5日 11:41，yangyiweigege<notifications@github.com> 写道： 


你这个问题我遇到过类似的。你贴一下你的 adapter-client application.yml的配置 我帮你看看

canal.conf:

canalServerHost: 127.0.0.1:11111

batchSize: 500

syncBatchSize: 1000

retries: 0

timeout:

mode: tcp

srcDataSources:

defaultDS:

url: jdbc:mysql://127.0.0.1:3306/mytest?useUnicode=true

username: root

password: 121212

canalAdapters:



instance: example

groups:



groupId: g1

outerAdapters:



name: es

hosts: 127.0.0.1:9300               # es 集群地址, 逗号分隔

properties:

cluster.name: elasticsearch       # es cluster namecanal.conf:

canalServerHost: 127.0.0.1:11111

batchSize: 500

syncBatchSize: 1000

retries: 0

timeout:

mode: tcp

srcDataSources:

defaultDS:

url: jdbc:mysql://127.0.0.1:3306/mytest?useUnicode=true

username: root

password: 121212

canalAdapters:









instance: example

groups:



groupId: g1

outerAdapters:



name: es

hosts: 127.0.0.1:9300               # es 集群地址, 逗号分隔

properties:

cluster.name: elasticsearch       # es cluster name











就是贴出如上代码 就行。我确定一下 是不是那个问题。



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by yangyiweigege** [comment]
加我微信吧 13150583605 我能确定你的问题了 但是几句话说不清楚 这个跟源码 以及 官方给的ES 同步例子 有关系。

**Comment by 1071746754** [comment]
> font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } 拜托帮忙看看server:  port: 8081spring:  jackson:    date-format: yyyy-MM-dd HH:mm:ss    time-zone: GMT+8    default-property-inclusion: non_nullcanal.conf:  mode: tcp  zookeeperHosts: 192.168.1.173:2181  batchSize: 500  syncBatchSize: 1000  retries: 3  timeout:  accessKey:  secretKey:  srcDataSources:    defaultDS:      url: jdbc:mysql://192.168.1.199:38383/test?useUnicode=true      username: canal      password: canal    defaultDS2:      url: jdbc:mysql://192.168.1.199:38383/newtest?useUnicode=true      username: canal      password: canal  canalAdapters:  - instance: example_01    groups:    - groupId: g1      outerAdapters:      - name: logger      - name: es        hosts: 192.168.1.209:9200,192.168.1.210:9200,192.168.1.211:9200        properties:          mode: rest          cluster.name: test-application  - instance: example_02    groups:    - groupId: g2      outerAdapters:      - name: logger      - name: es        hosts: 192.168.1209:9200,192.168.1.210:9200,192.168.1.211:9200        properties:          mode: rest          cluster.name: test-application Okami 732726554@qq.com 签名由 网易邮箱大师 定制 在2019年09月5日 11:41，yangyiweigege<notifications@github.com> 写道： 你这个问题我遇到过类似的。你贴一下你的 adapter-client application.yml的配置 我帮你看看 canal.conf: canalServerHost: 127.0.0.1:11111 batchSize: 500 syncBatchSize: 1000 retries: 0 timeout: mode: tcp srcDataSources: defaultDS: url: jdbc:mysql://127.0.0.1:3306/mytest?useUnicode=true username: root password: 121212 canalAdapters: instance: example groups: groupId: g1 outerAdapters: name: es hosts: 127.0.0.1:9300 # es 集群地址, 逗号分隔 properties: cluster.name: elasticsearch # es cluster namecanal.conf: canalServerHost: 127.0.0.1:11111 batchSize: 500 syncBatchSize: 1000 retries: 0 timeout: mode: tcp srcDataSources: defaultDS: url: jdbc:mysql://127.0.0.1:3306/mytest?useUnicode=true username: root password: 121212 canalAdapters: instance: example groups: groupId: g1 outerAdapters: name: es hosts: 127.0.0.1:9300 # es 集群地址, 逗号分隔 properties: cluster.name: elasticsearch # es cluster name 就是贴出如上代码 就行。我确定一下 是不是那个问题。 —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

这个是因为adapter同步到ES失败了，可以把重试打开，问题也可以解决

**Comment by yangyiweigege** [comment]
你这个问题 和这个 帖子的作者 是同一个原因 明天 我....发个issue 统一解答.顺便告知作者......





------------------ 原始邮件 ------------------
发件人: 我是小小菜包 <notifications@github.com&gt;
发送时间: 2019年9月5日 13:38
收件人: alibaba/canal <canal@noreply.github.com&gt;
抄送: yangyiweigege <2873824885@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[alibaba/canal] Adapter同步到ES出现数据丢失 (#2126)



 
font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } 拜托帮忙看看server:&nbsp; port: 8081spring:&nbsp; jackson:&nbsp; &nbsp; date-format: yyyy-MM-dd HH:mm:ss&nbsp; &nbsp; time-zone: GMT+8&nbsp; &nbsp; default-property-inclusion: non_nullcanal.conf:&nbsp; mode: tcp&nbsp; zookeeperHosts: 192.168.1.173:2181&nbsp; batchSize: 500&nbsp; syncBatchSize: 1000&nbsp; retries: 3&nbsp; timeout:&nbsp; accessKey:&nbsp; secretKey:&nbsp; srcDataSources:&nbsp; &nbsp; defaultDS:&nbsp; &nbsp; &nbsp; url: jdbc:mysql://192.168.1.199:38383/test?useUnicode=true&nbsp; &nbsp; &nbsp; username: canal&nbsp; &nbsp; &nbsp; password: canal&nbsp; &nbsp; defaultDS2:&nbsp; &nbsp; &nbsp; url: jdbc:mysql://192.168.1.199:38383/newtest?useUnicode=true&nbsp; &nbsp; &nbsp; username: canal&nbsp; &nbsp; &nbsp; password: canal&nbsp; canalAdapters:&nbsp; - instance: example_01&nbsp; &nbsp; groups:&nbsp; &nbsp; - groupId: g1&nbsp; &nbsp; &nbsp; outerAdapters:&nbsp; &nbsp; &nbsp; - name: logger&nbsp; &nbsp; &nbsp; - name: es&nbsp; &nbsp; &nbsp; &nbsp; hosts: 192.168.1.209:9200,192.168.1.210:9200,192.168.1.211:9200&nbsp; &nbsp; &nbsp; &nbsp; properties:&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; mode: rest&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; cluster.name: test-application&nbsp; - instance: example_02&nbsp; &nbsp; groups:&nbsp; &nbsp; - groupId: g2&nbsp; &nbsp; &nbsp; outerAdapters:&nbsp; &nbsp; &nbsp; - name: logger&nbsp; &nbsp; &nbsp; - name: es&nbsp; &nbsp; &nbsp; &nbsp; hosts:&nbsp;192.168.1209:9200,192.168.1.210:9200,192.168.1.211:9200&nbsp; &nbsp; &nbsp; &nbsp; properties:&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; mode: rest&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; cluster.name: test-application Okami 732726554@qq.com 签名由 网易邮箱大师 定制 在2019年09月5日 11:41，yangyiweigegenotifications@github.com 写道： 你这个问题我遇到过类似的。你贴一下你的 adapter-client application.yml的配置 我帮你看看 canal.conf: canalServerHost: 127.0.0.1:11111 batchSize: 500 syncBatchSize: 1000 retries: 0 timeout: mode: tcp srcDataSources: defaultDS: url: jdbc:mysql://127.0.0.1:3306/mytest?useUnicode=true username: root password: 121212 canalAdapters: instance: example groups: groupId: g1 outerAdapters: name: es hosts: 127.0.0.1:9300 # es 集群地址, 逗号分隔 properties: cluster.name: elasticsearch # es cluster namecanal.conf: canalServerHost: 127.0.0.1:11111 batchSize: 500 syncBatchSize: 1000 retries: 0 timeout: mode: tcp srcDataSources: defaultDS: url: jdbc:mysql://127.0.0.1:3306/mytest?useUnicode=true username: root password: 121212 canalAdapters: instance: example groups: groupId: g1 outerAdapters: name: es hosts: 127.0.0.1:9300 # es 集群地址, 逗号分隔 properties: cluster.name: elasticsearch # es cluster name 就是贴出如上代码 就行。我确定一下 是不是那个问题。 —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
  
这个是因为adapter同步到ES失败了，可以把重试打开，问题也可以解决

**Comment by rewerma** [comment]
已经修复

**Comment by jackznq** [comment]
> 已经修复

请问是怎么解决的  我这边是多表join mysql同步到ES，
mysql 5.6
ES 6.7
canal 1.1.4
canal-adapter 1.1.4 
单表同步的时候没发现异常，多表join  并且有group 的情况会出现数据丢失的情况，并且基本没有插入数据，一天订单量是几万的  这边基本没有插入，我在线上观察的一天就插入了几十条数据。

**Comment by JacksonCda** [comment]
我今天也是，只是同步了_id字段，其他字段都没有同步，而且就同步了几十条就没也同步了

**Comment by ddddddddddddddddddf** [comment]
我这时不时也会
