### ISSUE TITLE
canal v1.1.4 启动报错，是jdk版本的问题吗

### ISSUE THREAD

**Issue by practisedaybyday** [alibaba/canal#2145]
## Question

process error!com.alibaba.otter.canal.protocol.exception.CanalClientException: unsupported version at this client.
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:155) ~[classes/:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.connect(SimpleCanalConnector.java:115) ~[classes/:na]
	at com.alibaba.otter.canal.example.AbstractCanalClientTest.process(AbstractCanalClientTest.java:61) ~[classes/:na]
	at com.alibaba.otter.canal.example.AbstractCanalClientTest$1.run(AbstractCanalClientTest.java:31) [classes/:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_211]

**Comment by agapple** [comment]
用心的client在读旧版本server的数据？

**Comment by leohou0430** [comment]
有解决嘛？

**Comment by KDcx35** [comment]
请问解决了吗，我也遇到类似问题

**Comment by xq443** [comment]
我也有这个问题，该怎么解决
