### ISSUE TITLE
canal重启后异常

### ISSUE THREAD

**Issue by enclairfarron** [alibaba/canal#2147]
查询issue没有查询到相关内容

2019-09-04 18:24:47.876 [Druid-ConnectionPool-Create-12255153] ERROR com.alibaba.druid.pool.DruidDataSource - create connection SQLException, url: jdbc:h2:../conf/example2/h2;CACHE_SIZE=1000;MODE=MYSQL;, errorCode 90030, state 90030
org.h2.jdbc.JdbcSQLException: File corrupted while reading record: null. Possible solution: use the recovery tool [90030-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.message.DbException.get(DbException.java:168) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:196) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:168) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:100) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.engine.Database.getPageStore(Database.java:2476) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.engine.Database.open(Database.java:697) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.engine.Database.openDatabase(Database.java:276) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.engine.Database.<init>(Database.java:270) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.engine.Engine.openSession(Engine.java:64) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.engine.Engine.openSession(Engine.java:176) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.engine.Engine.createSession(Engine.java:137) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.engine.Engine.createSession(Engine.java:27) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:354) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:100) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.Driver.connect(Driver.java:69) ~[h2-1.4.196.jar:1.4.196]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1513) ~[druid-1.1.9.jar:1.1.9]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1578) ~[druid-1.1.9.jar:1.1.9]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2466) ~[druid-1.1.9.jar:1.1.9]
Caused by: java.lang.IllegalStateException: File corrupted in chunk 8618, expected page length 4..192, got 0 [1.4.196/6]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:765) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.mvstore.Page.read(Page.java:649) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.mvstore.Page.read(Page.java:195) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.mvstore.MVStore.readPage(MVStore.java:1952) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.mvstore.MVMap.readPage(MVMap.java:741) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.mvstore.Page.getChildPage(Page.java:217) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.mvstore.Cursor.min(Cursor.java:129) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.mvstore.Cursor.hasNext(Cursor.java:36) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.mvstore.MVStore.loadChunkMeta(MVStore.java:694) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.mvstore.MVStore.readStoreHeader(MVStore.java:675) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.mvstore.MVStore.<init>(MVStore.java:358) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2930) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:155) ~[h2-1.4.196.jar:1.4.196]
	... 17 common frames omitted

**Comment by enclairfarron** [comment]
自问自答一下 删除conf/对应的xx.mv.db xx.trace.db 相关：https://github.com/alibaba/canal/issues/512
