### ISSUE TITLE
1.1.4 windows启动报错

### ISSUE THREAD

**Issue by shizhengchao** [alibaba/canal#2152]
ch.qos.logback.core.LogbackException: Unexpected filename extension of file [file:/D:/canal-1.1.4/conf/]. Should be either .groovy or .xml
        at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:79)
        at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:152)
        at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:85)
        at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
        at org.slf4j.LoggerFactory.bind(LoggerFactory.java:141)
        at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:120)
        at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:331)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:283)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:304)
        at com.alibaba.otter.canal.deployer.CanalLauncher.<clinit>(CanalLauncher.java:29)

**Comment by shizhengchao** [comment]
可以了,不知道为啥要把windows启动脚本的这句给去掉
`set logback_configurationFile=%conf_dir%\logback.xml`

**Comment by R1310328554** [comment]
真的是坑爹啊！ startup.bat 的这行 不能注释， 否则就没有了日志。

当然， 其实关系也不大， 就是启动时候报了这个错，也不影响 canal 运行。

**Comment by hyq965672903** [comment]
有解决办法了吗？

**Comment by xyzhuzhou** [comment]
@rem set logback_configurationFile=%conf_dir%\logback.xml
上面那行是注释 把@rem删掉改成下面启动就行
set logback_configurationFile=%conf_dir%\logback.xml
