### ISSUE TITLE
es同步空指针异常

### ISSUE THREAD

**Issue by ruixiong-kong** [alibaba/canal#2159]
![image](https://user-images.githubusercontent.com/31500350/64397287-5d900400-d093-11e9-9dcc-368ca57321d0.png)
2019-09-06 10:32:30.210 [pool-5-thread-1] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - null
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at org.elasticsearch.client.RequestConverters.bulk(RequestConverters.java:154)
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1589)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1563)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1546)
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1512)
	at org.elasticsearch.client.RestHighLevelClient.bulk(RestHighLevelClient.java:427)
	at com.alibaba.otter.canal.client.adapter.es.support.ESConnection$ESBulkRequest.bulk(ESConnection.java:420)
	at com.alibaba.otter.canal.client.adapter.es.support.ESTemplate.commit(ESTemplate.java:198)
	at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.commit(ESSyncService.java:852)
	at com.alibaba.otter.canal.client.adapter.es.ESAdapter.sync(ESAdapter.java:151)
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.batchSync(AbstractCanalAdapterWorker.java:201)
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$1(AbstractCanalAdapterWorker.java:63)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$2(AbstractCanalAdapterWorker.java:59)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-09-06 10:32:30.210 [pool-3-thread-1] DEBUG c.a.otter.canal.client.adapter.es.service.ESSyncService - DML: {"data":[{"id":100102,"module":"ECC","condition_type":"YBP0","condition_table":"A648","sales_org":"HK61","sales_office":"PL10","distribution_channel":"81","customer":null,"customer_price_group":null,"country":null,"incoterm":null,"shipping_condition":null,"material":"4ZK0M44650","price":1310.0,"currency":"EUR","valid_from":"2017-04-01","valid_to":"9999-12-31","create_by":"admin","create_time":1553616000000,"is_effective":"1","is_expand":"1"}],"database":"price_dev","destination":"price-server","es":1567737034000,"groupId":null,"isDdl":false,"old":null,"pkNames":["id"],"sql":"","table":"channelprice_copy2","ts":1567737150042,"type":"INSERT"} 
Affected indexes: channelprice_c_t 
2019-09-06 10:32:30.211 [Thread-6] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - Outer adapter sync failed!  Error sync but ACK!

**Comment by yangyiweigege** [comment]
ES数据同步 配置一下key就好了。具体内容 看我 发的ISSUE ---建议官方修正Wiki

**Comment by rewerma** [comment]
已经修复
