### ISSUE TITLE
docker  canal_1.1.4 不能连接到canal.register.ip地址

### ISSUE THREAD

**Issue by yuyetingqin** [alibaba/canal#2179]
## Question
我将canal_1.1.4 制作成docker 镜像，其中IP地址配置如下：
canal.ip =  
canal.register.ip = 10.1.1.134 (docker容器所在物理机IP地址)

问题：
    发现canal注册到zk上的IP地址为 10.1.1.134:11111 , 但是canal服务日志中显示，客户端连接到canal IP地址是 docker 容器的IP地址，而不是 10.1.1.134:11111 地址。  canal日志错误信息如下：
2019-09-11 07:00:47.824 [New I/O server worker #1-6] ERROR c.a.otter.canal.server.netty.handler.SessionHandler - something goes wrong with channel:[id: 0x670c8388, /10.1.1.101:45606(客户端地址) => /10.42.4.44:11111(canal容器地址)], exception=java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:322)
        at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:281)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:201)
        at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
请问canal 如果做成docker，如何配置？ 这个错误如何处理?

**Comment by agapple** [comment]
Connection reset by peer，这是TCP已经在工作之后出的reset，肯定是已经正常连接了
