### ISSUE TITLE
canal_1.1.1 Docker 下遇到的连接问题

### ISSUE THREAD

**Issue by yuyetingqin** [alibaba/canal#2198]
## Question
docker pull  canal/canal-server:v1.1.1
映射 11111  11112 端口到本地宿主机(10.1.1.134)对应端口上。容器启动以后，canal 日志提示宿主机连接容器端口的错误：

2019-09-16 09:29:24.758 [New I/O server worker #1-2] ERROR c.a.otter.canal.server.netty.handler.SessionHandler - something goes wrong with channel:[id: 0x4b89c735, /10.1.1.134:50124 => /10.42.4.51:11111], exception=java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:322)
        at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:281)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:201)
        at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by agapple** [comment]
Connection reset by peer，肯定是已经连上了，客户端一直没响应就断开
