### ISSUE TITLE
MySQL 同步数据到 Phoenix 报错 java.lang.NullPointerException

### ISSUE THREAD

**Issue by ruicky** [alibaba/canal#2203]
## 环境:
    MySQL: 5.6.21
    HBase: 1.2
    Canal: 1.1.3 
    phoenix: phoenix-4.14.0-HBase-1.2-server 

## adapter/conf/application.yml 配置文件:

```
...
      - name: rdb
        key: phoenix1
        properties:
          jdbc.driverClassName: org.apache.phoenix.jdbc.PhoenixDriver
          jdbc.url: jdbc:phoenix:10.255.72.237:2181
          jdbc.username: 
          jdbc.password: 
          threads: 1
          commitSize: 3000
...
```

## 日志：

```
ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
java.lang.RuntimeException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at com.alibaba.otter.canal.client.adapter.rdb.RdbAdapter.sync(RdbAdapter.java:169)
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.batchSync(AbstractCanalAdapterWorker.java:198)
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$1(AbstractCanalAdapterWorker.java:62)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$2(AbstractCanalAdapterWorker.java:58)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$sync$2(RdbSyncService.java:127)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.sync(RdbSyncService.java:123)
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.sync(RdbSyncService.java:147)
	at com.alibaba.otter.canal.client.adapter.rdb.RdbAdapter.sync(RdbAdapter.java:166)
	... 8 common frames omitted
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$sync$2(RdbSyncService.java:125)
	... 12 common frames omitted
Caused by: java.lang.NullPointerException: null
	at com.alibaba.druid.pool.DruidDataSource.getConnectionInternal(DruidDataSource.java:1492)
	at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1253)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1233)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1223)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:90)
	at com.alibaba.otter.canal.client.adapter.rdb.support.BatchExecutor.getConn(BatchExecutor.java:38)
	at com.alibaba.otter.canal.client.adapter.rdb.support.BatchExecutor.rollback(BatchExecutor.java:77)
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$sync$1(RdbSyncService.java:117)
	... 4 common frames omitted
2019-09-17 13:07:45.433 [Thread-21] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - Outer adapter sync failed!  Error sync but ACK!
```

请问：我的思路是 想备份mysql的数据 到  phoenix ，他俩同事rdb 数据，理论上应该配置即可，现在报错， `java.lang.NullPointerException` 有什么处理办法吗？
或者说是我的配置文件有问题？希望能够解答一下疑惑，感谢！

**Comment by ruicky** [comment]
@rewerma  @agapple  2位大神能否抽空 看下这个问题，感谢！

**Comment by ruicky** [comment]
补充 放在 lib 文件夹下的的 drivers 是 phoenix-4.14.0-HBase-1.2-client.jar
