### ISSUE TITLE
java.lang.IllegalArgumentException: cannot write xcontent for unknown value of type class java.math.BigDecimal

### ISSUE THREAD

**Issue by sy973961684** [alibaba/canal#2213]
### environment
* canal 1.1.4
* mysql 5.7.27
* es 6.8.3
### Issue Description
mysql5.7.27一个表中的字段类型为decimal,es对应的mapping为float,然后启动canal-adapter同步数据时报 java.lang.IllegalArgumentException: cannot write xcontent for unknown value of type class java.math.BigDecimal,这个问题如何解决呢? 如果把mysql和es里的这个字段删除,canal-adapter同步是没有问题.

If there is an exception, please attach the exception trace:

```
2019-09-18 16:36:10.844 [http-nio-8081-exec-2] ERROR com.alibaba.otter.canal.client.adapter.support.Util - sqlRs has error, sql:  SELECT hsp.id , hsp.last_modified_time AS lastModifiedTime, hsp.valid, hsp.fk_first_category_id AS f
irstCategoryId, hsp.fk_second_category_id AS secondCategoryId, hsp.fk_third_category_id AS thirdCategoryId, hsp.fk_brand_info AS brandInfoId, hsp.fk_carriage_id AS carriageId, hsp.fk_product_type_id AS productTypeId, hsp.name as p
roductName, hsp.code as productCode, hsp.sort, hsp.sub_title AS subTitle, hsp.introduction, hsp.product_no AS productNo, hsp.price, hsp.market_price AS marketPrice, hsp.stock, hsp.min_stock AS minStock, hsp.stock_unit AS stockUnit
, hsp.min_purchase_num AS minPurchaseNum, hsp.weight, hsp.weight_unit AS weightUnit, hsp.key_words AS keyWords, hsp.publish_status AS publishStatus, hsp.detail_title AS detailTitle, hsp.online_status AS onlineStatus, hsp.product_s
tatus AS productStatus, hsp.sale_nums AS saleNums, hc1.name AS firstCategoryName, hc2.name AS secondCategoryName, hc3.name AS thirdCategoryName, hbi.name AS brandName, hpp2.productPics FROM hs_product hsp LEFT JOIN hs_category hc1
 ON hsp.fk_first_category_id = hc1.id LEFT JOIN hs_category hc2 ON hsp.fk_second_category_id = hc2.id LEFT JOIN hs_category hc3 ON hsp.fk_third_category_id = hc3.id LEFT JOIN hs_brand_info hbi ON hsp.fk_brand_info = hbi.id LEFT JO
IN ( SELECT fk_product_code, group_concat( hpp.picture ORDER BY id DESC SEPARATOR ',' ) AS productPics FROM hs_product_pic hpp GROUP BY fk_product_code ) hpp2 ON hsp.id = hpp2.fk_product_code
2019-09-18 16:36:10.844 [http-nio-8081-exec-2] ERROR c.a.otter.canal.client.adapter.es.service.ESEtlService - java.lang.RuntimeException: java.lang.IllegalArgumentException: cannot write xcontent for unknown value of type class ja
va.sql.Timestamp
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalArgumentException: cannot write xcontent for unknown value of type class java.sql.Timestamp
    at com.alibaba.otter.canal.client.adapter.support.Util.sqlRS(Util.java:65)
    at com.alibaba.otter.canal.client.adapter.es.service.ESEtlService.executeSqlImport(ESEtlService.java:80)
    at com.alibaba.otter.canal.client.adapter.support.AbstractEtlService.importData(AbstractEtlService.java:105)
    at com.alibaba.otter.canal.client.adapter.es.service.ESEtlService.importData(ESEtlService.java:57)
    at com.alibaba.otter.canal.client.adapter.es.ESAdapter.etl(ESAdapter.java:181)
    at com.alibaba.otter.canal.adapter.launcher.rest.CommonRest.etl(CommonRest.java:100)
    at com.alibaba.otter.canal.adapter.launcher.rest.CommonRest.etl(CommonRest.java:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
    at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
    at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:877)
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:783)
    at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)
    at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:877)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
    at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
    at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
    at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
    at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
    at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: cannot write xcontent for unknown value of type class java.sql.Timestamp
    at com.alibaba.otter.canal.client.adapter.es.service.ESEtlService.lambda$executeSqlImport$1(ESEtlService.java:206)
    at com.alibaba.otter.canal.client.adapter.support.Util.sqlRS(Util.java:60)
    ... 60 common frames omitted
Caused by: java.lang.IllegalArgumentException: cannot write xcontent for unknown value of type class java.sql.Timestamp
    at org.elasticsearch.common.xcontent.XContentBuilder.unknownValue(XContentBuilder.java:755)
    at org.elasticsearch.common.xcontent.XContentBuilder.map(XContentBuilder.java:810)
    at org.elasticsearch.common.xcontent.XContentBuilder.map(XContentBuilder.java:792)
    at org.elasticsearch.action.index.IndexRequest.source(IndexRequest.java:312)
    at org.elasticsearch.action.index.IndexRequest.source(IndexRequest.java:301)
    at org.elasticsearch.action.update.UpdateRequest.doc(UpdateRequest.java:555)
    at org.elasticsearch.action.update.UpdateRequestBuilder.setDoc(UpdateRequestBuilder.java:212)
    at com.alibaba.otter.canal.client.adapter.es.support.ESConnection$ESUpdateRequest.setDoc(ESConnection.java:220)
    at com.alibaba.otter.canal.client.adapter.es.service.ESEtlService.lambda$executeSqlImport$1(ESEtlService.java:139)
    ... 61 common frames omitted
2019-09-18 16:36:10.844 [http-nio-8081-exec-2] INFO  c.a.otter.canal.client.adapter.es.service.ESEtlService - 数据全量导入完成, 一共导入 0 条数据, 耗时: 9
```

**Comment by dalaoyang** [comment]
这个问题解决了吗？我也遇到了这个问题

**Comment by kamzhuyuqing** [comment]
这个解决了吗，我也遇到这个问题

**Comment by 15656080075** [comment]
配置application.yml中的目标为es7
