### ISSUE TITLE
canal 服务端运行一段时间会报如下错。不知道如何解决。

### ISSUE THREAD

**Issue by JoeyFan** [alibaba/canal#225]
我程序启动连接canal 报错：
something goes wrong with reason: something goes wrong with channel 
com.alibaba.otter.canal.server.exception.CanalServerException: ack error , clientId:1001 batchId:47 is not exist , please check

怎么解决？canal服务端我也重启了。运行了一下，过一阵程序启动还是继续会报错

下面是我的代码
```
while (true) {
                Message message = connector.getWithoutAck(1000); // 获取指定数量的数据
                long batchId = message.getId();
                int size = message.getEntries().size();
                if (batchId == -1 || size == 0) {
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException e) {}
                } else {
                    long beginTime = DateUtils.nowDateToTimestamp();
                    //逻辑:1先判断插入与更新2如果是状态已完成4，则获取数据。进行保存，存mongdb
                    try {
                        switchHandle(message.getEntries());
                        connector.ack(batchId); // 提交确认
                    } catch (Exception e) {
                        //System.out.println("同步错误，需要回滚" + e.getMessage());
                        logger.error("同步错误，需要回滚", e);
                        connector.rollback(batchId);
                        continue;
                    }
                    long endTime = DateUtils.nowDateToTimestamp();
                    logger.info("此次同步时间是:" + (endTime - beginTime) + " ms");
                }
}
```

**Comment by agapple** [comment]
出现这个问题，怀疑是server端发生了instance重启，导致内存里的batchId丢失.  检查一下服务端的日志

**Comment by JoeyFan** [comment]
agapple 服务端没有发送重启，还有别的原因么？我的代码没有问题吧？

**Comment by agapple** [comment]
server端开启了scan=true扫描？

**Comment by SHUlibee** [comment]
我也遇到这个问题，请问是怎么解决的啊？

**Comment by agapple** [comment]
客户端增加重试，或者服务端关闭scan=false

**Comment by JoeyFan** [comment]
@SHUlibee 两种思路。一个是确认一下是否是canal server进行了重启，再就是确认mysql的binlog是否进行了清理，canal的meta.data是否进行了清理。。
同时如果进行优化的话，可以跟agepple说的那样client端增加重试机制，并且关闭把canal Server的scan设置成false

**Comment by weirui** [comment]
一样的错，求解

**Comment by rovernerd** [comment]
我这边是切换了kakfa的版本,修改了kafka和zookeeper的地址,之后就一直报这个错误,请教下怎么处理?
```
2018-05-29 11:00:08.799 [Thread-4] WARN  c.alibaba.otter.canal.client.impl.ClusterCanalConnector - something goes wrong when rollbacking data from server:null
com.alibaba.otter.canal.protocol.exception.CanalClientException: java.io.IOException: Broken pipe
        at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.rollback(SimpleCanalConnector.java:342)
        at com.alibaba.otter.canal.client.impl.ClusterCanalConnector.rollback(ClusterCanalConnector.java:216)
        at com.xiaomatech.dbevent.canal.dbkafka.AbstractCanalClient.process(AbstractCanalClient.java:203)
        at com.xiaomatech.dbevent.canal.dbkafka.AbstractCanalClient$2.run(AbstractCanalClient.java:99)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Broken pipe
        at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
        at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
        at sun.nio.ch.IOUtil.write(IOUtil.java:65)
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:470)
        at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.writeWithHeader(SimpleCanalConnector.java:359)
        at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.rollback(SimpleCanalConnector.java:336)
        ... 4 more

2018-05-29 11:00:13.869 [Thread-4] INFO  c.alibaba.otter.canal.client.impl.ClusterCanalConnector - restart the connector for next round retry.
2018-05-29 11:00:13.902 [Thread-4] WARN  c.alibaba.otter.canal.client.impl.ClusterCanalConnector - something goes wrong when getWithoutAck data from server:null
com.alibaba.otter.canal.protocol.exception.CanalClientException: something goes wrong with reason: something goes wrong with channel:[id: 0x513ca1d3, /10.20.105.201:39029 => /10.20.105.201:11112], exception=com.alibaba.otter.canal.server.exception.CanalServerException: rollback error, clientId:1001 batchId:3 is not exist , please check

        at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.receiveMessages(SimpleCanalConnector.java:302)
        at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.getWithoutAck(SimpleCanalConnector.java:279)
        at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.getWithoutAck(SimpleCanalConnector.java:252)
        at com.alibaba.otter.canal.client.impl.ClusterCanalConnector.getWithoutAck(ClusterCanalConnector.java:180)
        at com.xiaomatech.dbevent.canal.dbkafka.AbstractCanalClient.process(AbstractCanalClient.java:186)
        at com.xiaomatech.dbevent.canal.dbkafka.AbstractCanalClient$2.run(AbstractCanalClient.java:99)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by mjjian0** [comment]
@agapple  一样的错，关闭scan=false也不行。

**Comment by Fanduzi** [comment]
把canal.id换一个就好了

**Comment by dragon-Mac** [comment]
我程序启动连接canal 报错：
something goes wrong with reason: something goes wrong with channel
com.alibaba.otter.canal.server.exception.CanalServerException: ack error , clientId:1001 batchId:47 is not exist , please check
这个问题还是没有解决，关闭scan=false也不行，不定时的报这个错误，问题出在哪里呢 @agapple ， @fanqinghui 你的问题解决了吗？
两种思路。一个是确认一下是否是canal server进行了重启，再就是确认mysql的binlog是否进行了清理，canal的meta.data是否进行了清理。。
同时如果进行优化的话，可以跟agepple说的那样client端增加重试机制，并且关闭把canal Server的scan设置成false   该确认的都确认了，canal.auto.scan=false也设置了，难道是我设置的有问题吗？

**Comment by hxy91819** [comment]
怎样重试呢？直接目前使用的1.1.4最新的demo里的代码，应该是自带了重试吧，但是还是出现了丢数据的问题。代码如下：
```
        int batchSize = 5 * 1024;
        while (running) {
            try {
                MDC.put("destination", destination);
                connector.connect();
                connector.subscribe();
                while (running) {
                    Message message = connector.getWithoutAck(batchSize); // 获取指定数量的数据
                    long batchId = message.getId();
                    int size = message.getEntries().size();
                    if (batchId == -1 || size == 0) {
                        // 无效信息，可以考虑休眠
                    } else {
//                        printSummary(message, batchId, size);
//                        printEntry(message.getEntries());
                        if (handleEntry != null) {
                            handleEntry.invoke(message.getEntries());
                        }
                    }

                    if (batchId != -1) {
                        connector.ack(batchId); // 提交确认
                        // connector.rollback(batchId); // 处理失败, 回滚数据
                    }
                }
            } catch (Exception e) {
                log.error("process error!", e);
                try {
                    Thread.sleep(1000L);
                } catch (InterruptedException e1) {
                    Thread.currentThread().interrupt();
                }
            } finally {
                connector.disconnect();
                MDC.remove("destination");
            }
        }
```

**Comment by wanyy15083** [comment]
这个错误有解决办法不？会一直采集错误指标占用内存增长较快
