### ISSUE TITLE
清理了一下 主mysql主的binlog日志，然后重启了canal，canal 服务端启动报错

### ISSUE THREAD

**Issue by JoeyFan** [alibaba/canal#226]
我清理了一下 主mysql主的binlog日志，然后重启了canal 
canal 服务端启动报错。
```
2016-11-22 15:41:55.513 [destination = tj-172.18.100.97 , address = /172.18.100.97:3306 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - disconnect address /172.18.100.97:3306 has an error, retrying., caused by 
java.io.IOException: KILL DUMP 1299 failure:java.io.IOException: ErrorPacket [errorNumber=1094, fieldCount=-1, message=Unknown thread id: 1299, sqlState=HY000, sqlStateMarker=#]
 with command: KILL CONNECTION 1299
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlUpdateExecutor.update(MysqlUpdateExecutor.java:49)
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.disconnect(MysqlConnector.java:104)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.disconnect(MysqlConnection.java:60)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:242)
	at java.lang.Thread.run(Thread.java:745)

	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.disconnect(MysqlConnector.java:106) ~[canal.parse.driver-1.0.22.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.disconnect(MysqlConnection.java:60) ~[canal.parse-1.0.22.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:242) ~[canal.parse-1.0.22.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]

```

这大概是什么原因导致的呢？

**Comment by JoeyFan** [comment]
我主要是把主mysql的binlog日志清理了，binlog从头开始了。但meta.dat里面记录的却不是。所以启动canal报错了，清理了一下 instance的meta.dat 文件，就可以了
