### ISSUE TITLE
canal正常启动，本地的mysql可正常订阅binlog，远程提示连不上mysql，但用mysql命令行是能连上mysql的

### ISSUE THREAD

**Issue by gaohanghbut** [alibaba/canal#2265]
## 异常如下：
```
java.io.IOException: ErrorPacket [errorNumber=2003, fieldCount=-1, message=Can't connect to MySQL server on '$ip' (107), sqlState=HY000, sqlStateMarker=#]
 with command: set @master_binlog_checksum= @@global.binlog_checksum
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlUpdateExecutor.update(MysqlUpdateExecutor.java:49) ~[canal.parse.driver-1.1.5-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.update(MysqlConnection.java:116) [canal.parse-1.1.5-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.updateSettings(MysqlConnection.java:420) [canal.parse-1.1.5-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.seek(MysqlConnection.java:123) [canal.parse-1.1.5-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findAsPerTimestampInSpecificLogFile(MysqlEventParser.java:746) [canal.parse-1.1.5-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findEndPositionWithMasterIdAndTimestamp(MysqlEventParser.java:395) [canal.parse-1.1.5-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPositionInternal(MysqlEventParser.java:450) [canal.parse-1.1.5-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPosition(MysqlEventParser.java:369) [canal.parse-1.1.5-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:194) [canal.parse-1.1.5-SNAPSHOT.jar:na]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_161]
```

使用mysql命令行和其它数据库工具都能正常连接上数据库，只有canal显示连不上

mysql是5.7版本

canal.properties中的destinations配置：

canal.destinations = example3,example4

instance.properties配置中只有数据连的地址，用户名及密码不同，其它均相同：

求助

**Comment by agapple** [comment]
升级到最新的1.1.4版本，已经解决
