### ISSUE TITLE
canal-adapter 启动报错 

### ISSUE THREAD

**Issue by zeminli** [alibaba/canal#2278]
## Question

2019-10-04 15:36:11.355 [Thread-4] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - process error!
com.alibaba.otter.canal.protocol.exception.CanalClientException: java.net.ConnectException: Connection refused
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:198)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.connect(SimpleCanalConnector.java:115)
	at com.alibaba.otter.canal.adapter.launcher.loader.CanalAdapterWorker.process(CanalAdapterWorker.java:88)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:454)
	at sun.nio.ch.Net.connect(Net.java:446)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:150)
	... 3 common frames omitted
2019-10-04 15:36:11.355 [Thread-4] INFO  c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - =============> Disconnect destination: example <=============

**Comment by zeminli** [comment]
已解决，谢谢- -|

**Comment by yeyuguang1** [comment]
请问怎么解决的，我现在adapter连接不上server

**Comment by ChenZhaobin** [comment]
@zeminli  请问怎么解决的，我也遇到了
