### ISSUE TITLE
windows 

### ISSUE THREAD

**Issue by CXW0504** [alibaba/canal#2279]
start cmd :  java   -Xms128m -Xmx512m -XX:PermSize=128m  -Djava.awt.headless=true -Djava.net.preferIPv4Stack=true -Dapplication.codeset=UTF-8 -Dfile.encoding=UTF-8  -server -Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,address=9099,server=y,suspend=n  -DappName=otter-canal -Dlogback.configurationFile="" -Dcanal.conf="C:\Users\Administrator\Desktop\canal.deployer-1.1.4\bin\\..\conf\canal.properties" -classpath "C:\Users\Administrator\Desktop\canal.deployer-1.1.4\bin\\..\conf\..\lib\*;C:\Users\Administrator\Desktop\canal.deployer-1.1.4\bin\\..\conf" java   -Xms128m -Xmx512m -XX:PermSize=128m  -Djava.awt.headless=true -Djava.net.preferIPv4Stack=true -Dapplication.codeset=UTF-8 -Dfile.encoding=UTF-8  -server -Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,address=9099,server=y,suspend=n  -DappName=otter-canal -Dlogback.configurationFile="" -Dcanal.conf="C:\Users\Administrator\Desktop\canal.deployer-1.1.4\bin\\..\conf\canal.properties" -classpath "C:\Users\Administrator\Desktop\canal.deployer-1.1.4\bin\\..\conf\..\lib\*;C:\Users\Administrator\Desktop\canal.deployer-1.1.4\bin\\..\conf" com.alibaba.otter.canal.deployer.CanalLauncher
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
Listening for transport dt_socket at address: 9099
Failed to instantiate [ch.qos.logback.classic.LoggerContext]
Reported exception:
ch.qos.logback.core.LogbackException: Unexpected filename extension of file [file:/C:/Users/Administrator/Desktop/canal.deployer-1.1.4/conf/]. Should be either .groovy or .xml
        at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:79)
        at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:152)
        at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:85)
        at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
        at org.slf4j.LoggerFactory.bind(LoggerFactory.java:141)
        at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:120)
        at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:331)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:283)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:304)
        at com.alibaba.otter.canal.deployer.CanalLauncher.<clinit>(CanalLauncher.java:29)

**Comment by CXW0504** [comment]
canal.deployer-1.1.4-SNAPSHOT is ok。。。。

**Comment by agapple** [comment]
主干代码已经修复
