### ISSUE TITLE
Canal推送到RocketMQ,出现null数据以及ArithmeticException

### ISSUE THREAD

**Issue by offSwitch** [alibaba/canal#2286]
Canal日志 
2019-10-10 13:47:57.484 [pool-4-thread-1] ERROR com.alibaba.otter.canal.rocketmq.CanalRocketMQProducer - java.util.concurrent.ExecutionException: java.lang.ArithmeticException: / by zero
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.ArithmeticException: / by zero
        at com.alibaba.otter.canal.common.utils.ExecutorTemplate.waitForResult(ExecutorTemplate.java:74) ~[canal.common-1.1.5-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.rocketmq.CanalRocketMQProducer.send(CanalRocketMQProducer.java:199) ~[canal.server-1.1.5-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.rocketmq.CanalRocketMQProducer.send(CanalRocketMQProducer.java:106) ~[canal.server-1.1.5-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.server.CanalMQStarter.worker(CanalMQStarter.java:183) [canal.server-1.1.5-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.server.CanalMQStarter.access$500(CanalMQStarter.java:23) [canal.server-1.1.5-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.server.CanalMQStarter$CanalMQRunnable.run(CanalMQStarter.java:225) [canal.server-1.1.5-SNAPSHOT.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_202]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_202]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_202]
Caused by: java.util.concurrent.ExecutionException: java.lang.ArithmeticException: / by zero
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_202]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_202]
        at com.alibaba.otter.canal.common.utils.ExecutorTemplate.waitForResult(ExecutorTemplate.java:72) ~[canal.common-1.1.5-SNAPSHOT.jar:na]
        ... 8 common frames omitted
Caused by: java.lang.ArithmeticException: / by zero
        at com.alibaba.otter.canal.rocketmq.CanalRocketMQProducer.sendMessage(CanalRocketMQProducer.java:254) ~[canal.server-1.1.5-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.rocketmq.CanalRocketMQProducer.access$200(CanalRocketMQProducer.java:36) ~[canal.server-1.1.5-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.rocketmq.CanalRocketMQProducer$3.run(CanalRocketMQProducer.java:192) ~[canal.server-1.1.5-SNAPSHOT.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_202]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_202]
        ... 3 common frames omitted
2019-10-10 13:54:14.967 [canal-instance-scan-0] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - stop CannalInstance for null-example
2019-10-10 13:54:15.083 [pool-4-thread-1] ERROR com.alibaba.otter.canal.server.CanalMQStarter - process error!
com.alibaba.otter.canal.server.exception.CanalServerException: destination:example should start first
2019-10-10 13:54:15.198 [canal-instance-scan-0] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - stop successful....
2019-10-10 13:54:15.222 [canal-instance-scan-0] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Loading properties file from class path resource [canal.properties]
2019-10-10 13:54:15.223 [canal-instance-scan-0] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Loading properties file from class path resource [example/instance.properties]
2019-10-10 13:54:15.239 [canal-instance-scan-0] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Loading properties file from class path resource [canal.properties]
2019-10-10 13:54:15.239 [canal-instance-scan-0] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Loading properties file from class path resource [example/instance.properties]
2019-10-10 13:54:15.266 [canal-instance-scan-0] INFO  c.a.otter.canal.instance.spring.CanalInstanceWithSpring - start CannalInstance for 1-example
2019-10-10 13:54:15.266 [canal-instance-scan-0] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table filter : ^.*\..*$
2019-10-10 13:54:15.267 [canal-instance-scan-0] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table black filter :
2019-10-10 13:54:15.268 [canal-instance-scan-0] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - start successful....
2019-10-10 13:54:15.285 [destination = example , address = /127.0.0.1:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> begin to find start position, it will be long time for reset or first position
2019-10-10 13:54:15.286 [destination = example , address = /127.0.0.1:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - prepare to find start position just last position
 {"identity":{"slaveId":-1,"sourceAddress":{"address":"localhost.localdomain","port":3306}},"postion":{"gtid":"","included":false,"journalName":"mysql-bin.000001","position":11085,"serverId":1,"timestamp":1570686516000}}
2019-10-10 13:54:15.304 [destination = example , address = /127.0.0.1:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> find start position successfully, EntryPosition[included=false,journalName=mysql-bin.000001,position=11085,serverId=1,gtid=,timestamp=1570686516000] cost : 19ms , the next step is binlog dump
2019-10-10 13:54:20.458 [Thread-6] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - stop CannalInstance for null-example
2019-10-10 13:54:21.345 [Thread-6] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - stop successful....
2019-10-10 13:54:31.652 [main] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Loading properties file from class path resource [canal.properties]
2019-10-10 13:54:31.654 [main] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Loading properties file from class path resource [example/instance.properties]
2019-10-10 13:54:31.754 [main] WARN  o.s.beans.GenericTypeAwarePropertyDescriptor - Invalid JavaBean property 'connectionCharset' being accessed! Ambiguous write methods found next to actually used [public void com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.setConnectionCharset(java.nio.charset.Charset)]: [public void com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.setConnectionCharset(java.lang.String)]
2019-10-10 13:54:31.777 [main] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Loading properties file from class path resource [canal.properties]
2019-10-10 13:54:31.777 [main] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Loading properties file from class path resource [example/instance.properties]
2019-10-10 13:54:32.031 [main] INFO  c.a.otter.canal.instance.spring.CanalInstanceWithSpring - start CannalInstance for 1-example
2019-10-10 13:54:32.036 [main] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table filter : ^.*\..*$
2019-10-10 13:54:32.036 [main] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table black filter :
2019-10-10 13:54:32.090 [destination = example , address = /127.0.0.1:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> begin to find start position, it will be long time for reset or first position
2019-10-10 13:54:32.107 [main] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - start successful....
2019-10-10 13:54:32.120 [destination = example , address = /127.0.0.1:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - prepare to find start position just last position
 {"identity":{"slaveId":-1,"sourceAddress":{"address":"localhost.localdomain","port":3306}},"postion":{"gtid":"","included":false,"journalName":"mysql-bin.000001","position":11085,"serverId":1,"timestamp":1570686516000}}
2019-10-10 13:54:32.405 [destination = example , address = /127.0.0.1:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> find start position successfully, EntryPosition[included=false,journalName=mysql-bin.000001,position=11085,serverId=1,gtid=,timestamp=1570686516000] cost : 297ms , the next step is binlog dump

RocketMQ

root@dockerone:/opt/rocketmq/bin# ./mqadmin  topicStatus -n 127.0.0.1:9876 -t example
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
#Broker Name                      #QID  #Min Offset           #Max Offset             #Last Updated
dockerone                         0     0                     18                      2019-10-10 13:48:36,303
dockerone                         1     0                     4                       2019-10-10 13:48:36,303
dockerone                         2     0                     4                       2019-10-10 13:48:36,305
dockerone                         3     0                     3                       2019-10-10 13:48:36,305
root@dockerone:/opt/rocketmq/bin# ./mqadmin  topicStatus -n 127.0.0.1:9876 -t example
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
#Broker Name                      #QID  #Min Offset           #Max Offset             #Last Updated
dockerone                         0     0                     18                      2019-10-10 13:48:36,303
dockerone                         1     0                     4                       2019-10-10 13:48:36,303
dockerone                         2     0                     4                       2019-10-10 13:48:36,305
dockerone                         3     0                     3                       2019-10-10 13:48:36,305
root@dockerone:/opt/rocketmq/bin# ./mqadmin  topicStatus -n 127.0.0.1:9876 -t example
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
#Broker Name                      #QID  #Min Offset           #Max Offset             #Last Updated
dockerone                         0     0                     19                      2019-10-10 13:54:59,893
dockerone                         1     0                     5                       2019-10-10 13:54:59,897
dockerone                         2     0                     5                       2019-10-10 13:54:59,893
dockerone                         3     0                     4                       2019-10-10 13:54:59,894
root@dockerone:/opt/rocketmq/bin# ./mqadmin  topicStatus -n 127.0.0.1:9876 -t example
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
#Broker Name                      #QID  #Min Offset           #Max Offset             #Last Updated
dockerone                         0     0                     19                      2019-10-10 13:54:59,893
dockerone                         1     0                     5                       2019-10-10 13:54:59,897
dockerone                         2     0                     5                       2019-10-10 13:54:59,893
dockerone                         3     0                     4                       2019-10-10 13:54:59,894
root@dockerone:/opt/rocketmq/bin# ./mqadmin  topicStatus -n 127.0.0.1:9876 -t example
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
#Broker Name                      #QID  #Min Offset           #Max Offset             #Last Updated
dockerone                         0     0                     20                      2019-10-10 13:58:00,982
dockerone                         1     0                     6                       2019-10-10 13:58:00,983
dockerone                         2     0                     6                       2019-10-10 13:58:00,981
dockerone                         3     0                     5                       2019-10-10 13:58:00,982
root@dockerone:/opt/rocketmq/bin# ./mqadmin  topicStatus -n 127.0.0.1:9876 -t example
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
#Broker Name                      #QID  #Min Offset           #Max Offset             #Last Updated
dockerone                         0     0                     21                      2019-10-10 14:00:41,310
dockerone                         1     0                     7                       2019-10-10 14:00:41,309
dockerone                         2     0                     7                       2019-10-10 14:00:41,310
dockerone                         3     0                     6                       2019-10-10 14:00:41,311

**Comment by offSwitch** [comment]
修改一条数据，4个queue都增加了一条，实际上只有一条有数据，其它得都是null. canal单topic多分区.
![image](https://user-images.githubusercontent.com/11695496/66543095-fae4c900-eb66-11e9-83bb-a567ce764713.png)

canal 配置

#################################################
## mysql serverId , v1.0.26+ will autoGen
# canal.instance.mysql.slaveId=0

# enable gtid use true/false
canal.instance.gtidon=false

# position info
canal.instance.master.address=127.0.0.1:3306
canal.instance.master.journal.name=
canal.instance.master.position=
canal.instance.master.timestamp=
canal.instance.master.gtid=

# rds oss binlog
canal.instance.rds.accesskey=
canal.instance.rds.secretkey=
canal.instance.rds.instanceId=

# table meta tsdb info
canal.instance.tsdb.enable=true
#canal.instance.tsdb.url=jdbc:mysql://127.0.0.1:3306/canal_tsdb
#canal.instance.tsdb.dbUsername=canal
#canal.instance.tsdb.dbPassword=canal

#canal.instance.standby.address =
#canal.instance.standby.journal.name =
#canal.instance.standby.position =
#canal.instance.standby.timestamp =
#canal.instance.standby.gtid=

# username/password
canal.instance.dbUsername=canal
canal.instance.dbPassword=canal
canal.instance.connectionCharset = UTF-8
# enable druid Decrypt database password
canal.instance.enableDruid=false
#canal.instance.pwdPublicKey=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALK4BUxdDltRRE5/zXpVEVPUgunvscYFtEip3pmLlhrWpacX7y7GCMo2/JM6LeHmiiNdH1FWgGCpUfircSwlWKUCAwEAAQ==

# table regex
canal.instance.filter.regex=.*\\..*
# table black regex
canal.instance.filter.black.regex=
# table field filter(format: schema1.tableName1:field1/field2,schema2.tableName2:field1/field2)
#canal.instance.filter.field=test1.t_product:id/subject/keywords,test2.t_company:id/name/contact/ch
# table field black filter(format: schema1.tableName1:field1/field2,schema2.tableName2:field1/field2)
#canal.instance.filter.black.field=test1.t_product:subject/product_image,test2.t_company:id/name/contact/ch

# mq config
canal.mq.topic=example
# dynamic topic route by schema or table regex
#canal.mq.dynamicTopic=mytest1.user,mytest2\\..*,.*\\..*
#canal.mq.partition=0
# hash partition config
canal.mq.partitionsNum=4
canal.mq.partitionHash=.*\\..*:$pk$
#################################################

**Comment by offSwitch** [comment]
canal版本是v1.1.5-alpha-1

**Comment by offSwitch** [comment]
![image](https://user-images.githubusercontent.com/11695496/66544065-a858dc00-eb69-11e9-866e-cc54e590bfc2.png)

![image](https://user-images.githubusercontent.com/11695496/66544035-90815800-eb69-11e9-83a0-e355c2386eed.png)
![image](https://user-images.githubusercontent.com/11695496/66544053-a000a100-eb69-11e9-84da-eaccd756dec6.png)

**Comment by agapple** [comment]
重新基于主干打包试试
