### ISSUE TITLE
java.io.IOException: Unexpected End Stream异常

### ISSUE THREAD

**Issue by lilykyung** [alibaba/canal#229]
canal版本 1.0.16
偶发性的报如下异常：
2016-11-30 12:56:17.588 [destination = example , address = /xxx:3306 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - I/O error while reading from client socket
java.io.IOException: Unexpected End Stream
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:156) ~[canal.parse-1.0.16.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:78) ~[canal.parse-1.0.16.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:116) [canal.parse-1.0.16.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:208) [canal.parse-1.0.16.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_67]
2016-11-30 12:56:17.588 [destination = example , address = /xxx:3306 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - dump address /172.16.81.97:23306 has an error, retrying. caused by 
java.io.IOException: Unexpected End Stream
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:156) ~[canal.parse-1.0.16.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:78) ~[canal.parse-1.0.16.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:116) ~[canal.parse-1.0.16.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:208) ~[canal.parse-1.0.16.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_67]
2016-11-30 12:56:17.588 [destination = example , address = /xxx:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[java.io.IOException: Unexpected End Stream
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:156)
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:78)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:116)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:208)
	at java.lang.Thread.run(Thread.java:745)
]

且伴随着丢失binlog，偶发的时间没有规律性，有没有遇到过这个问题？

**Comment by agapple** [comment]
几个建议：
1. 升级下canal版本到最新版
2. 开启心跳SQL,定时产生心跳事件,保证TCP链接一致有包传递

**Comment by tomjamescn** [comment]
我也遇到了这个问题，具体场景是，一张60多万的表，有批量更新操作（update语句没有where条件），这样基于row模式的binlog就特别多，每次执行到30w数据时，就报这个错误了。我现在加上了心跳sql，还在观察数据。

**Comment by tomjamescn** [comment]
测试了一下，貌似是客户端处理时间过长导致的，如果客户端处理很快，就没有这个问题。所以我目前的解决方案是在客户端中将接收message和处理通过文件队列异步处理。但这样带来一个麻烦，就是失败的逻辑，得在客户端在实现一次。

**Comment by tutulvlv** [comment]
各位前辈，这个问题我也是时不时的出现，有实用的解决方案吗，谢谢啦

**Comment by shijiebei2009** [comment]
不知道你解决了吗？我一样的问题，数据堆积在master就报错 @tutulvlv

**Comment by shijiebei2009** [comment]
@agapple 
请问如何开启心跳SQL？
