### ISSUE TITLE
Lucene50 错误

### ISSUE THREAD

**Issue by 18678224309** [alibaba/canal#2290]
往ES同步数据时报错：An SPI class of type org.apache.lucene.codecs.PostingsFormat with name 'Lucene50' does not exist.   这个怎么解决啊？

**Comment by gs80140** [comment]
遇到相同的错误了, 正在想办法解决中...
Caused by: java.lang.IllegalArgumentException: An SPI class of type org.apache.lucene.codecs.PostingsFormat with name 'Lucene50' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: [completion]
	at org.apache.lucene.util.NamedSPILoader.lookup(NamedSPILoader.java:116) ~[client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.apache.lucene.codecs.PostingsFormat.forName(PostingsFormat.java:112) ~[client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.elasticsearch.common.lucene.Lucene.<clinit>(Lucene.java:113) ~[client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]

**Comment by gs80140** [comment]
设置成 rest 模式不报这个错了

 mode: rest

**Comment by xuej2s** [comment]
我是想适配2.x版本，然后遇到了这个问题，然后pom文件添加这个之后，我这边问题解决了
`<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
						<configuration>
							<transformers>
								<transformer
									implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
									<resource>META-INF/services/org.apache.lucene.codecs.Codec</resource>
								</transformer>
								<transformer
									implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
									<resource>META-INF/services/org.apache.lucene.codecs.DocValuesFormat</resource>
								</transformer>
								<transformer
									implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
									<resource>META-INF/services/org.apache.lucene.codecs.PostingsFormat</resource>
								</transformer>
								<transformer
									implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer">
								</transformer>

								                           
							</transformers>
							<shadedArtifactAttached>true</shadedArtifactAttached>
							<shadedClassifierName>fat</shadedClassifierName>
						</configuration>
					</execution>
				</executions>

			</plugin>`
