### ISSUE TITLE
Load canal adapter: es failed

### ISSUE THREAD

**Issue by zxlxgd** [alibaba/canal#2299]
2019-10-15 17:34:12.669 [main] INFO  c.a.o.canal.adapter.launcher.loader.CanalAdapterService - ## syncSwitch refreshed.
2019-10-15 17:34:12.669 [main] INFO  c.a.o.canal.adapter.launcher.loader.CanalAdapterService - ## start the canal client adapters.
2019-10-15 17:34:12.673 [main] INFO  c.a.otter.canal.client.adapter.support.ExtensionLoader - extension classpath dir: /opt/app/canal
-1.1.5/canal.adapter-1.1.5/plugin
2019-10-15 17:34:12.695 [main] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterLoader - Load canal adapter: es failed
java.lang.IllegalStateException: Extension instance(name: es, class: interface com.alibaba.otter.canal.client.adapter.OuterAdapter)
could not be instantiated: class could not be found
        at com.alibaba.otter.canal.client.adapter.support.ExtensionLoader.createExtension(ExtensionLoader.java:186) ~[client-adapter.
common-1.1.5-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.client.adapter.support.ExtensionLoader.getExtension(ExtensionLoader.java:142) ~[client-adapter.com
mon-1.1.5-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.adapter.launcher.loader.CanalAdapterLoader.loadAdapter(CanalAdapterLoader.java:175) [client-adapte
r.launcher-1.1.5-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.adapter.launcher.loader.CanalAdapterLoader.init(CanalAdapterLoader.java:72) [client-adapter.launch
er-1.1.5-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.adapter.launcher.loader.CanalAdapterService.init(CanalAdapterService.java:60) [client-adapter.laun
cher-1.1.5-SNAPSHOT.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_191]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_191]

**Comment by danvid** [comment]
我也遇到同样的问题

**Comment by wanglittlehandsome** [comment]
解决了吗

**Comment by wanyzCh** [comment]
本地启动可尝试打开以下代码com.alibaba.otter.canal.client.adapter.support.ExtensionLoader：
// 只加载外部spi, 不加载classpath
        // 2. load inner extension class with default classLoader
         ClassLoader classLoader = findClassLoader();
         loadFile(extensionClasses, CANAL_DIRECTORY, classLoader);
         loadFile(extensionClasses, SERVICES_DIRECTORY, classLoader);

**Comment by wanyzCh** [comment]
> 本地启动可尝试打开以下代码com.alibaba.otter.canal.client.adapter.support.ExtensionLoader：
> // 只加载外部spi, 不加载classpath
> // 2. load inner extension class with default classLoader
> ClassLoader classLoader = findClassLoader();
> loadFile(extensionClasses, CANAL_DIRECTORY, classLoader);
> loadFile(extensionClasses, SERVICES_DIRECTORY, classLoader);

同时在idea跑的话需要mvn install一下，每个adapter有修改都需要install

**Comment by maybeyj** [comment]
有用

> > 本地启动可尝试打开以下代码com.alibaba.otter.canal.client.adapter.support.ExtensionLoader：
> > // 只加载外部spi, 不加载classpath
> > // 2. load inner extension class with default classLoader
> > ClassLoader classLoader = findClassLoader();
> > loadFile(extensionClasses, CANAL_DIRECTORY, classLoader);
> > loadFile(extensionClasses, SERVICES_DIRECTORY, classLoader);
> 
> 同时在idea跑的话需要mvn install一下，每个adapter有修改都需要install
