### ISSUE TITLE
全量数据 etl 异常: ElasticsearchException[Elasticsearch exception [type=mapper_parsing_exception, reason=failed to parse [cardtime_date]]]

### ISSUE THREAD

**Issue by mgqonline** [alibaba/canal#2314]
```
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: 全量数据 etl 异常: ElasticsearchException[Elasticsearch exception [type=mapper_parsing_exception, reason=failed to parse [cardtime_date]]]; nested: ElasticsearchException[Elasticsearch exception [type=illegal_argument_exception, reason=Invalid format: "2019-10-21T08:44:31-05:00" is malformed at "T08:44:31-05:00"]];
        at com.alibaba.otter.canal.client.adapter.support.Util.sqlRS(Util.java:65)
        at com.alibaba.otter.canal.client.adapter.es.service.ESEtlService.executeSqlImport(ESEtlService.java:80)
        at com.alibaba.otter.canal.client.adapter.support.AbstractEtlService.lambda$importData$1(AbstractEtlService.java:91)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by rewerma** [comment]
报错已经很明显了： failed to parse  [cardtime_date]，查看一下你配置中的sql是否正确符合wiki上的格式要求

**Comment by crl1036** [comment]
请问楼主解决了吗？我也碰到相同的问题了

**Comment by mgqonline** [comment]
@crl1036 谢谢，已解决

**Comment by mgqonline** [comment]
@crl1036 是解析问题，已解决，时间格式设置问题

**Comment by steamedBreadKiller** [comment]
@mgqonline 怎么解决的，是修改es中字段的format吗，还是修改sql语句，也碰到了这个问题。
