### ISSUE TITLE
ErrorPacket [errorNumber=1094, fieldCount=-1, message=Unknown thread id: 335944433, sqlState=HY000, sqlStateMarker=#]

### ISSUE THREAD

**Issue by dongfangshangren** [alibaba/canal#232]
canal版本:1.0.22
mysql版本：阿里云rds mysql5.6.16-log
报如下异常:
2016-12-05 10:05:19.828 [destination = example , address = xxx.mysql.rds.aliyuncs.com/xxx:3306 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - I/O error while reading from client socket
java.io.IOException: Unexpected End Stream
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:156) ~[canal.parse-1.0.22.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:70) ~[canal.parse-1.0.22.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:113) [canal.parse-1.0.22.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:210) [canal.parse-1.0.22.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
2016-12-05 10:05:19.837 [destination = example , address = xxx.mysql.rds.aliyuncs.com/xxx:3306 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - dump address xxx.mysql.rds.aliyuncs.com/xxx:3306 has an error, retrying. caused by 
java.io.IOException: Unexpected End Stream
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:156) ~[canal.parse-1.0.22.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:70) ~[canal.parse-1.0.22.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:113) ~[canal.parse-1.0.22.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:210) ~[canal.parse-1.0.22.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
2016-12-05 10:05:19.841 [destination = example , address = xxx.mysql.rds.aliyuncs.com/xxx:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[java.io.IOException: Unexpected End Stream
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:156)
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:70)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:113)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:210)
	at java.lang.Thread.run(Thread.java:745)
]
2016-12-05 10:05:19.858 [destination = example , address = xxx.mysql.rds.aliyuncs.com/xxx:3306 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - disconnect address xxx.mysql.rds.aliyuncs.com/xxx:3306 has an error, retrying., caused by 
java.io.IOException: KILL DUMP 335944433 failure:java.io.IOException: 
 with command: KILL CONNECTION 335944433
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlUpdateExecutor.update(MysqlUpdateExecutor.java:49)ErrorPacket [errorNumber=1094, fieldCount=-1, message=Unknown thread id: 335944433, sqlState=HY000, sqlStateMarker=#]
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.disconnect(MysqlConnector.java:104)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.disconnect(MysqlConnection.java:60)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:242)
	at java.lang.Thread.run(Thread.java:745)

	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.disconnect(MysqlConnector.java:106) ~[canal.parse.driver-1.0.22.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.disconnect(MysqlConnection.java:60) ~[canal.parse-1.0.22.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:242) ~[canal.parse-1.0.22.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
2016-12-05 10:05:33.210 [destination = example , address = xxx.mysql.rds.aliyuncs.com/xxx:3306 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - prepare to find start position just last position
2016-12-05 10:05:33.249 [destination = example , address = xxx.mysql.rds.aliyuncs.com/xxx:3306 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - I/O error while reading from client socket
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:95) ~[canal.parse-1.0.22.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:113) [canal.parse-1.0.22.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:210) [canal.parse-1.0.22.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
2016-12-05 10:05:33.250 [destination = example , address = xxx.mysql.rds.aliyuncs.com/xxx:3306 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - dump address xxx.mysql.rds.aliyuncs.com/xxx:3306 has an error, retrying. caused by 
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:95) ~[canal.parse-1.0.22.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:113) ~[canal.parse-1.0.22.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:210) ~[canal.parse-1.0.22.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
2016-12-05 10:05:33.250 [destination = example , address = xxx.mysql.rds.aliyuncs.com/xxx:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:95)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:113)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:210)
	at java.lang.Thread.run(Thread.java:745)
]

**Comment by dongfangshangren** [comment]
MySQL主从同步中会出现从库执行某些sql语句失败而导致从库备份失败，但是可以通过slave_skip_errors来跳过一些错误，此处应该是这种错误造成canal同步失败，上面1094是mysql从库执行线程相关错误，请问一些canal这边这种情况怎么解决

**Comment by agapple** [comment]
destination:example[java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file

**Comment by dongfangshangren** [comment]
是出现java.io.IOException: Unexpected End Stream之后发送KILL DUMP 335944433 之后 ，然后接收到了 [errorNumber=1094, fieldCount=-1, message=Unknown thread id: 335944433, sqlState=HY000, sqlStateMarker=#]，再重连就出现Could not find first log file name in binary log index file了，想问一下是不是那个java.io.IOException: Unexpected End Stream造成的

**Comment by agapple** [comment]
Could not find first log file name in binary log index file，这个是主因
