### ISSUE TITLE
[v1.1.4]CanalServerException: destination:target should start first

### ISSUE THREAD

**Issue by kervin521** [alibaba/canal#2324]
## Question

com.alibaba.otter.canal.protocol.exception.CanalClientException: com.alibaba.otter.canal.protocol.exception.CanalClientException: something goes wrong in initRunning method. 

	at com.alibaba.otter.canal.client.impl.ClusterCanalConnector.connect(ClusterCanalConnector.java:74) ~[canal.client-1.1.4.jar!/:?]

	at com.alibaba.otter.canal.client.impl.ClusterCanalConnector.restart(ClusterCanalConnector.java:273) ~[canal.client-1.1.4.jar!/:?]

	at com.alibaba.otter.canal.client.impl.ClusterCanalConnector.getWithoutAck(ClusterCanalConnector.java:189) ~[canal.client-1.1.4.jar!/:?]

	at com.hollysys.smartfactory.target.calculate.canal.CanalListener.doService(CanalListener.java:155) ~[classes!/:?]

	at com.hollysys.smartfactory.target.calculate.canal.CanalListener.lambda$start$0(CanalListener.java:127) ~[classes!/:?]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]

	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

Caused by: com.alibaba.otter.canal.protocol.exception.CanalClientException: something goes wrong in initRunning method. 

	at com.alibaba.otter.canal.client.impl.running.ClientRunningMonitor.initRunning(ClientRunningMonitor.java:156) ~[canal.client-1.1.4.jar!/:?]

	at com.alibaba.otter.canal.client.impl.running.ClientRunningMonitor.start(ClientRunningMonitor.java:93) ~[canal.client-1.1.4.jar!/:?]

	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.connect(SimpleCanalConnector.java:108) ~[canal.client-1.1.4.jar!/:?]

	at com.alibaba.otter.canal.client.impl.ClusterCanalConnector.connect(ClusterCanalConnector.java:64) ~[canal.client-1.1.4.jar!/:?]

	... 7 more

Caused by: com.alibaba.otter.canal.protocol.exception.CanalClientException: failed to subscribe with reason: something goes wrong with channel:[id: 0x1254c16e, /10.255.0.177:34426 => /10.255.2.111:11111], exception=com.alibaba.otter.canal.server.exception.CanalServerException: destination:target should start first

	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.subscribe(SimpleCanalConnector.java:249) ~[canal.client-1.1.4.jar!/:?]

	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector$1.processActiveEnter(SimpleCanalConnector.java:434) ~[canal.client-1.1.4.jar!/:?]

	at com.alibaba.otter.canal.client.impl.running.ClientRunningMonitor.processActiveEnter(ClientRunningMonitor.java:221) ~[canal.client-1.1.4.jar!/:?]

	at com.alibaba.otter.canal.client.impl.running.ClientRunningMonitor.initRunning(ClientRunningMonitor.java:123) ~[canal.client-1.1.4.jar!/:?]

	at com.alibaba.otter.canal.client.impl.running.ClientRunningMonitor.start(ClientRunningMonitor.java:93) ~[canal.client-1.1.4.jar!/:?]

	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.connect(SimpleCanalConnector.java:108) ~[canal.client-1.1.4.jar!/:?]

	at com.alibaba.otter.canal.client.impl.ClusterCanalConnector.connect(ClusterCanalConnector.java:64) ~[canal.client-1.1.4.jar!/:?]

	... 7 more

**Comment by kervin521** [comment]
![image](https://user-images.githubusercontent.com/9798724/67359436-cd9c1000-f595-11e9-89cd-9e510d6d77aa.png)
![image](https://user-images.githubusercontent.com/9798724/67359481-d7257800-f595-11e9-85bc-a6bf98cbb240.png)

**Comment by kervin521** [comment]
这是在Docker的swarm下做主备模式有问题

**Comment by kervin521** [comment]
![image](https://user-images.githubusercontent.com/9798724/67360458-98dd8800-f598-11e9-8fea-fa75903ba588.png)

**Comment by everior** [comment]
请问解决了吗，我也遇到了一样的问题。

**Comment by kamzhuyuqing** [comment]
请问解决了吗

**Comment by AI1186780944** [comment]
请问怎么解决的呢？

**Comment by 827551331** [comment]
我也在等，怎么解决的
