### ISSUE TITLE
aliyun rds，canal无法正常同步，报kill dump

### ISSUE THREAD

**Issue by jimhj** [alibaba/canal#2327]
由于之前一直用rds的暴露外网地址访问，添加到canal里面就自动被解析成ip地址，昨晚大概凌晨，这个外网对应的ip地址突然变更了，导致服务挂起，有大量的未同步数据，且有如下错误，我应该怎么做，才会恢复服务，并同步之前的数据，急求！

pid:3 nid:2 exception:canal:canv5sh:java.io.IOException: KILL DUMP 4049924 failure:java.io.IOException: ErrorPacket [errorNumber=1094, fieldCount=-1, message=Unknown thread id: 4049924, sqlState=HY000, sqlStateMarker=#]
with command: KILL CONNECTION 4049924
at com.alibaba.otter.canal.parse.driver.mysql.MysqlUpdateExecutor.update(MysqlUpdateExecutor.java:49)
at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.disconnect(MysqlConnector.java:104)
at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.reconnect(MysqlConnector.java:82)
at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.reconnect(MysqlConnection.java:56)
at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:169)
at java.lang.Thread.run(Thread.java:745)

**Comment by liuqunqi** [comment]
同样的问题

**Comment by wuyimei** [comment]
+1 目前还没有找到解决方法

**Comment by liuqunqi** [comment]
已解决，把h2.mv.db 干掉，重启canal-server

**Comment by lubo212** [comment]
同样的问题

**Comment by renxinlin** [comment]
遇到同样的问题
