### ISSUE TITLE
canal基于timestamp位点回抽报错

### ISSUE THREAD

**Issue by smallez** [alibaba/canal#233]
canal版本：1.0.22
测试时基于timestamp位点信息配置数据重抽，发现日志里不断报错，请问是什么原因，该如何解决？报错信息如下：
2016-12-05 19:24:29.049 [destination = oms_orders , address = /172.172.230.36:3307 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - prepare to find start position ::1480780800000
2016-12-05 19:24:49.062 [destination = oms_orders , address = /172.172.230.36:3307 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - ERROR ## findAsPerTimestampInSpecificLogFile has an error
java.io.IOException: KILL DUMP 19915370 failure:java.io.IOException: ErrorPacket [errorNumber=1094, fieldCount=-1, message=Unknown thread id: 19915370, sqlState=HY000, sqlStateMarker=#]
 with command: KILL CONNECTION 19915370
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlUpdateExecutor.update(MysqlUpdateExecutor.java:49)
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.disconnect(MysqlConnector.java:104)
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.reconnect(MysqlConnector.java:82)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.reconnect(MysqlConnection.java:56)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findAsPerTimestampInSpecificLogFile(MysqlEventParser.java:674)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findByStartTimeStamp(MysqlEventParser.java:519)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPositionInternal(MysqlEventParser.java:356)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPosition(MysqlEventParser.java:313)
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:162)
        at java.lang.Thread.run(Thread.java:745)

        at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.disconnect(MysqlConnector.java:106) ~[canal.parse.driver-1.0.22.jar:na]
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.reconnect(MysqlConnector.java:82) ~[canal.parse.driver-1.0.22.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.reconnect(MysqlConnection.java:56) ~[canal.parse-1.0.22.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findAsPerTimestampInSpecificLogFile(MysqlEventParser.java:674) [canal.parse-1.0.22.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findByStartTimeStamp(MysqlEventParser.java:519) [canal.parse-1.0.22.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPositionInternal(MysqlEventParser.java:356) [canal.parse-1.0.22.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPosition(MysqlEventParser.java:313) [canal.parse-1.0.22.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:162) [canal.parse-1.0.22.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]

**Comment by smallez** [comment]
![image](https://cloud.githubusercontent.com/assets/7370509/20909493/1b10a274-bb97-11e6-8098-6fa85a4ab56e.png)
我用的1.0.22版本里的代码，发现异常不是记录日志

**Comment by agapple** [comment]
已修改，使用当前master打个包试试

**Comment by smallez** [comment]
重新基于master做了编译，替换了driver下的mysqlconnector类，不影响抽取流程了
