### ISSUE TITLE
为什么运行好好的，突然报错Could not find first log file name in binary log index file

### ISSUE THREAD

**Issue by aiaix** [alibaba/canal#236]
双向同步中，出现的。而且还影响了单向同步。 指定了位点，同步看起来正常，但是始终处于定位中，数据不同步。

**Comment by aiaix** [comment]
但是我这个机器中，OTTER其他SCHEME同步正常。有什么方法处理。

**Comment by owenludong** [comment]
我这边也是，运行着 突然报这个  canal 1.0.22,   rds

ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - I/O error while reading from client socket
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:95) ~[canal.parse-1.0.22.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:113) [canal.parse-1.0.22.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:210) [canal.parse-1.0.22.jar:na]
        at java.lang.Thread.run(Thread.java:744) [na:1.7.0_45]

**Comment by agapple** [comment]
rds会有删除binlog的操作，如果消费有延迟就容易出现位点不在的情况

**Comment by agapple** [comment]
rds会有删除binlog的操作，如果消费有延迟就容易出现位点不在的情况

**Comment by geckhan** [comment]
请问这个要怎么处理
