### ISSUE TITLE
 canal-server对接了dts的实例时，报CanalParseException: fetch failed by table meta

### ISSUE THREAD

**Issue by NoNException** [alibaba/canal#2377]
cannal-server在监听接了阿里dts的实例时，会报这个错，然后connal-server就不在往client推数据变更了
![image](https://user-images.githubusercontent.com/23208566/68459682-fcc2aa80-0240-11ea-93f1-d3d3e2b02341.png)

2019-11-08 07:56:36.314 [destination = weps , address = rm-bpyo.mysql.rds.aliyuncs.com/xxx.xxx:3306 EventtParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:weps[com.alibaba.otter.canal.parse.exception.CanalParseException: com.alibaba.otter.canal.parse.exception.CanalParseException: com.alibaba.otter.canal.parse.exception.CanalParseException: fetch failed by table meta:`dts`.`dts_trx4unit_mark_17`
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: com.alibaba.otter.canal.parse.exception.CanalParseException: fetch failed by table meta:`dts`.`dts_trx4unit_mark_17`
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: fetch failed by table meta:`dts`.`dts_trx4unit_mark_17`
Caused by: java.io.IOException: ErrorPacket [errorNumber=1142, fieldCount=-1, message=SHOW command denied to user 'xxx' for table 'dts_trx4unit_mark_17', sqlState=42000, sqlStateMarker=#]
 with command: show create table `dts`.`dts_trx4unit_mark_17`
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlQueryExecutor.query(MysqlQueryExecutor.java:61)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.query(MysqlConnection.java:106)
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.TableMetaCache.getTableMeta(TableMetaCache.java:177)
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.getTableMeta(LogEventConvert.java:950)
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseRowsEventForTableMeta(LogEventConvert.java:479)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:280)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:246)
        at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168)
        at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
]

**Comment by acuitong** [comment]
server端使用的什么版本??

**Comment by itmyhome** [comment]
我们也出现这个错误，node managea 4.2.18

**Comment by Mokaful** [comment]
@acuitong 同样的错，canal1.1.3 and mysql5.7
` com.alibaba.otter.canal.parse.exception.CanalParseException: fetch failed by table meta:`tag_meta`.`tag_market_copy1`
`
之后无论是ddl还是dml语句，client端都接收不到
