### ISSUE TITLE
java.io.IOException: end of stream when reading header 异常

### ISSUE THREAD

**Issue by AnakinSkyW** [alibaba/canal#238]
前两天还正常，今天突然报了这个异常
18:08:13.923 [im_message-****] ERROR  ***.mysql.binlog.CanalClient - process error!
com.alibaba.otter.canal.protocol.exception.CanalClientException: java.io.IOException: end of stream when reading header
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.getWithoutAck(SimpleCanalConnector.java:281) ~[canal.client.jar:na]
	at cn.ishow.db.mysql.binlog.CanalClient.process(CanalClient.java:160) [Subscriber.jar:na]
	at cn.ishow.db.mysql.binlog.CanalClient.access$100(CanalClient.java:27) [Subscriber.jar:na]
	at cn.ishow.db.mysql.binlog.CanalClient$2.run(CanalClient.java:101) [Subscriber.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_74]
Caused by: java.io.IOException: end of stream when reading header
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.read(SimpleCanalConnector.java:378) ~[canal.client.jar:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.readNextPacket(SimpleCanalConnector.java:369) ~[canal.client.jar:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.receiveMessages(SimpleCanalConnector.java:286) ~[canal.client.jar:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.getWithoutAck(SimpleCanalConnector.java:279) ~[canal.client.jar:na]
	... 4 common frames omitted
18:08:13.923 [im_message-****] INFO  ***.mysql.binlog.CanalClient - disconnect

随后canal就连不上了，一直报错
com.alibaba.otter.canal.protocol.exception.CanalClientException: java.net.ConnectException: Connection refused: connect
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:171) ~[canal.client.jar:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.connect(SimpleCanalConnector.java:97) ~[canal.client.jar:na]
	at cn.ishow.db.mysql.binlog.CanalClient.process(CanalClient.java:151) [Subscriber.jar:na]
	at cn.ishow.db.mysql.binlog.CanalClient.access$100(CanalClient.java:27) [Subscriber.jar:na]
	at cn.ishow.db.mysql.binlog.CanalClient$2.run(CanalClient.java:101) [Subscriber.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_74]
Caused by: java.net.ConnectException: Connection refused: connect
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_74]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_74]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_74]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_74]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:132) ~[canal.client.jar:na]
	... 5 common frames omitted

**Comment by AnakinSkyW** [comment]
sorry,自己的问题

**Comment by yujinsong** [comment]
什么原因，我也遇到了

**Comment by haiboyang** [comment]
什么问题，我也遇到了，突然就有这个问题 @AnakinSkyW

**Comment by dingaiminGIT** [comment]
我运行官网提供的 SimpleCanalClientExample  类报了这个错误，不知道什么原因

**Comment by yiyin888** [comment]
哥，能贴下解决办法吗？我也遇到了这个问题，@AnakinSkyW

**Comment by AI1186780944** [comment]
这是什么问题到底？

**Comment by beibeiaishuijiao** [comment]
> 这是什么问题到底？

请问这个问题现在，你知道怎么解决了吗

**Comment by yilongchuan** [comment]
什么问题，怎么解决啊？

**Comment by jiangxiaoqiang** [comment]
同问
