### ISSUE TITLE
end of stream when reading header

### ISSUE THREAD

**Issue by 784134748** [alibaba/canal#2383]
请问，一直在报这个错误是怎么回事？
Caused by: java.io.IOException: end of stream when reading header
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.read(SimpleCanalConnector.java:413) ~[canal.client-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.readNextPacket(SimpleCanalConnector.java:401) ~[canal.client-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.readNextPacket(SimpleCanalConnector.java:385) ~[canal.client-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.receiveMessages(SimpleCanalConnector.java:330) ~[canal.client-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.getWithoutAck(SimpleCanalConnector.java:323) ~[canal.client-1.1.5-SNAPSHOT.jar:na]

**Comment by 784134748** [comment]
分析了下源码，不太明白这里的处理：
此处抛出异常的，为什么要用error级别的日志来捕获呢？导致日志全是这些报错
 if (r == -1) {
     throw new IOException("end of stream when reading header");
}

} catch (Exception e) {
    if (i != retry - 1) {
        connector.rollback(batchId); // 处理失败, 回滚数据
        logger.error(e.getMessage() + " Error sync and rollback, execute times: " + (i + 1));
    } else {
        connector.ack(batchId);
        logger.error(e.getMessage() + " Error sync but ACK!");
    }
    Thread.sleep(500);
}

**Comment by dingyufei615** [comment]
我也遇到了这个问题 跑着跑着就
SimpleAdminConnectors - java.io.IOException: end of stream when reading header

admin就挂了 但是server中的实例正常
