### ISSUE TITLE
使用CanalConnectors.newClusterConnector报错。

### ISSUE THREAD

**Issue by JoeyFan** [alibaba/canal#239]
使用zk获取canal连接报错
语句：
 CanalConnector simpleCanalConnector= CanalConnectors.newClusterConnector("10.100.103.19:2181","example","","");
报错信息
Exception in thread "main" java.lang.IllegalAccessError: tried to access method com.google.common.collect.MapMaker.makeComputingMap(Lcom/google/common/base/Function;)Ljava/util/concurrent/ConcurrentMap; from class com.alibaba.otter.canal.common.zookeeper.ZkClientx
	at com.alibaba.otter.canal.common.zookeeper.ZkClientx.<clinit>(ZkClientx.java:26)
	at com.alibaba.otter.canal.client.CanalConnectors.newClusterConnector(CanalConnectors.java:60)
	at com.foundation.test.canal.ClientCluster.main(ClientCluster.java:25)

**Comment by JoeyFan** [comment]
解决了。依赖更新到最新的1.0.22就ok了。老版本的参数不一致！
<dependency>
  <groupId>com.alibaba.otter</groupId>
  <artifactId>canal.client</artifactId>
  <version>1.0.22</version>
</dependency>
