### ISSUE TITLE
切换成group-instance.xml 时，消费不到数据

### ISSUE THREAD

**Issue by rongyousu** [alibaba/canal#240]
2016-12-19 17:28:58.734 [main] INFO  com.alibaba.otter.canal.deployer.CanalLauncher - ## start the canal server.
log4j:WARN No appenders could be found for logger (org.I0Itec.zkclient.ZkEventThread).
log4j:WARN Please initialize the log4j system properly.
2016-12-19 17:28:58.991 [main] INFO  com.alibaba.otter.canal.deployer.CanalController - ## start the canal server[10.97.14.145:11111]
2016-12-19 17:28:59.527 [main] ERROR c.a.o.c.common.zookeeper.running.ServerRunningMonitor - processActiveEnter failed
java.lang.NullPointerException: null
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser.start(AbstractEventParser.java:274) ~[canal.parse-1.0.22.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.start(MysqlEventParser.java:145) ~[canal.parse-1.0.22.jar:na]
	at com.alibaba.otter.canal.parse.inbound.group.GroupEventParser.start(GroupEventParser.java:24) ~[canal.parse-1.0.22.jar:na]
	at com.alibaba.otter.canal.instance.core.AbstractCanalInstance.start(AbstractCanalInstance.java:91) ~[canal.instance.core-1.0.22.jar:na]
	at com.alibaba.otter.canal.instance.spring.CanalInstanceWithSpring.start(CanalInstanceWithSpring.java:30) ~[canal.instance.spring-1.0.22.jar:na]
	at com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded.start(CanalServerWithEmbedded.java:102) ~[canal.server-1.0.22.jar:na]
	at com.alibaba.otter.canal.deployer.CanalController$2$1.processActiveEnter(CanalController.java:121) ~[canal.deployer-1.0.22.jar:na]
	at com.alibaba.otter.canal.common.zookeeper.running.ServerRunningMonitor.processActiveEnter(ServerRunningMonitor.java:234) [canal.common-1.0.22.jar:na]
	at com.alibaba.otter.canal.common.zookeeper.running.ServerRunningMonitor.initRunning(ServerRunningMonitor.java:138) [canal.common-1.0.22.jar:na]
	at com.alibaba.otter.canal.common.zookeeper.running.ServerRunningMonitor.start(ServerRunningMonitor.java:98) [canal.common-1.0.22.jar:na]
	at com.alibaba.otter.canal.deployer.CanalController.start(CanalController.java:396) [canal.deployer-1.0.22.jar:na]
	at com.alibaba.otter.canal.deployer.CanalLauncher.main(CanalLauncher.java:35) [canal.deployer-1.0.22.jar:na]

**Comment by agapple** [comment]
java.lang.NullPointerException: null
at com.alibaba.otter.canal.parse.inbound.AbstractEventParser.start(AbstractEventParser.java:274) ~

要学会看日志

**Comment by agapple** [comment]
关注下最新版1.0.23

**Comment by agapple** [comment]
关注下最新版1.0.23
