### ISSUE TITLE
Timeout occurred, failed to read total 8150 bytes in 25000 milliseconds, actual read only 928 bytes

### ISSUE THREAD

**Issue by wuyimei** [alibaba/canal#2400]
canal-server：1.1.3

ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - Socket timeout expired, closing connection
java.net.SocketTimeoutException: Timeout occurred, failed to read total 8150 bytes in 25000 milliseconds, actual read only 928 bytes
	at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:124) ~[canal.parse.driver-1.1.3.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:174) ~[canal.parse-1.1.3.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:85) ~[canal.parse-1.1.3.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:235) [canal.parse-1.1.3.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:257) [canal.parse-1.1.3.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]

会重试，但之后还会出现这个异常，请问现在有解决方案吗？

**Comment by zhiyuan192shine** [comment]
请问这个问题怎么解决？ 你是开启了心跳SQL吗 ？

**Comment by sshitaime** [comment]
1.1.4 我部署也出现这个问题，请问问题怎么解决？

**Comment by KinYu668** [comment]
问题解决了么
