### ISSUE TITLE
Client requested master to start replication from impossible position

### ISSUE THREAD

**Issue by slowooo** [alibaba/canal#242]
完整的报错信息：
2016-12-22 00:00:54.195 [destination = ixtrade , address = /172.30.10.109:3306 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - prepare to find start position just last position
2016-12-22 00:00:54.199 [destination = ixtrade , address = /172.30.10.109:3306 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - I/O error while reading from client socket
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Client requested master to start replication from impossible position; the first event 'mysql-bin.000024' at 533920026, the last event read from 'mysql-bin.000024' at 4, the last byte read from 'mysql-bin.000024' at 4.
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:95) ~[canal.parse-1.0.22.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:113) [canal.parse-1.0.22.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:210) [canal.parse-1.0.22.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]
2016-12-22 00:00:54.199 [destination = ixtrade , address = /172.30.10.109:3306 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - dump address /172.30.10.109:3306 has an error, retrying. caused by 
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Client requested master to start replication from impossible position; the first event 'mysql-bin.000024' at 533920026, the last event read from 'mysql-bin.000024' at 4, the last byte read from 'mysql-bin.000024' at 4.
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:95) ~[canal.parse-1.0.22.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:113) ~[canal.parse-1.0.22.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:210) ~[canal.parse-1.0.22.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]
2016-12-22 00:00:54.200 [destination = ixtrade , address = /172.30.10.109:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:ixtrade[java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Client requested master to start replication from impossible position; the first event 'mysql-bin.000024' at 533920026, the last event read from 'mysql-bin.000024' at 4, the last byte read from 'mysql-bin.000024' at 4.
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:95)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:113)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:210)
	at java.lang.Thread.run(Thread.java:745)
]
2016-12-22 00:00:54.202 [destination = ixtrade , address = /172.30.10.109:3306 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - disconnect address /172.30.10.109:3306 has an error, retrying., caused by 
java.io.IOException: KILL DUMP 7726 failure:java.io.IOException: ErrorPacket [errorNumber=1094, fieldCount=-1, message=Unknown thread id: 7726, sqlState=HY000, sqlStateMarker=#]
 with command: KILL CONNECTION 7726
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlUpdateExecutor.update(MysqlUpdateExecutor.java:49)
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.disconnect(MysqlConnector.java:104)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.disconnect(MysqlConnection.java:60)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:242)
	at java.lang.Thread.run(Thread.java:745)

	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.disconnect(MysqlConnector.java:106) ~[canal.parse.driver-1.0.22.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.disconnect(MysqlConnection.java:60) ~[canal.parse-1.0.22.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:242) ~[canal.parse-1.0.22.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]

这个异常应该是mysql非正常关闭后产生的，请问该怎么处理？

**Comment by agapple** [comment]
sqlstate = HY000 errmsg = Client requested master to start replication from impossible position; the first event 'mysql-bin.000024' at 533920026, the last event read from 'mysql-bin.000024' at 4, the last byte read from 'mysql-bin.000024' at 4.

估计位点错误

**Comment by chenglinjava68** [comment]
清除meta.dat中内容 或者清楚zk 中报错的postion 信息 重启server 端就可以了
