### ISSUE TITLE
CanalAdapter 同步至Es时 使用Es别名抛出异常

### ISSUE THREAD

**Issue by mirocolo** [alibaba/canal#2437]
- [x] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment
* canal version
1.1.4
* mysql version
5.7.28
### Issue Description
canal配置文件如下：
![image](https://user-images.githubusercontent.com/24607277/69806122-19894700-121d-11ea-8067-b448f4f4c4af.png)
es别名配置
![image](https://user-images.githubusercontent.com/24607277/69806138-227a1880-121d-11ea-97e0-9a35f5bc63ea.png)

### Expected behaviour
使用别名market_sku同步至索引market_sku_v0成功
### Actual behaviour
抛出找不到索引异常，

If there is an exception, please attach the exception trace:

```
`2019-11-28 19:29:56.181 [pool-2-thread-1] ERROR c.a.otter.canal.client.adapter.es.service.ESSyncService - sync error, es index: market_sku, DML : Dml{destination='chaosale', database='chaosale_setting', table='goods_sku', type='INSERT', es=15749405
95000, ts=1574940596115, sql='', data=[{id=1111113, product_id=111}], old=null}
2019-11-28 19:29:56.183 [pool-2-thread-1] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalArgumentException: Not found the mapping info of index: market_sku
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalArgumentException: Not found the mapping info of index: market_sku
        at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.sync(ESSyncService.java:110)
        at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.sync(ESSyncService.java:58)
        at com.alibaba.otter.canal.client.adapter.es.ESAdapter.sync(ESAdapter.java:169)
        at com.alibaba.otter.canal.client.adapter.es.ESAdapter.sync(ESAdapter.java:148)
        at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.batchSync(AbstractCanalAdapterWorker.java:201)
        at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$1(AbstractCanalAdapterWorker.java:62)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$2(AbstractCanalAdapterWorker.java:58)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)`
```

**Comment by mirocolo** [comment]
es 版本 6.7.2

**Comment by 565407548** [comment]
不支持别名．我自己有去做别名支持，但是一个别名可能对应多个实际index，所以我也没有提相关pr 或者 issure

**Comment by 565407548** [comment]
```
    public MappingMetaData getMapping(String indexOrAlias, String type) {
        MappingMetaData mappingMetaData = getMappingByIndex(indexOrAlias, type);
        if (mappingMetaData == null) {
            mappingMetaData = getMappingByAlias(indexOrAlias, type);
        }
        return mappingMetaData;
    }


private MappingMetaData getMappingByIndex(String index, String type) {
        MappingMetaData mappingMetaData = null;
        if (mode == ESClientMode.TRANSPORT) {
            ImmutableOpenMap<String, MappingMetaData> mappings;
            try {
                mappings = transportClient.admin()
                        .cluster()
                        .prepareState()
                        .execute()
                        .actionGet()
                        .getState()
                        .getMetaData()
                        .getIndices()
                        .get(index)
                        .getMappings();
            } catch (NullPointerException e) {
                throw new IllegalArgumentException("Not found the mapping info of index: " + index);
            }
            mappingMetaData = mappings.get(type);

        } else {
            ImmutableOpenMap<String, ImmutableOpenMap<String, MappingMetaData>> mappings;
            try {
                GetMappingsRequest request = new GetMappingsRequest();
                request.indices(index);
                GetMappingsResponse response;
                try {
                    // 6.4以下版本直接使用该接口会报错
                    response = restHighLevelClient
                            .indices()
                            .getMapping(request, RequestOptions.DEFAULT);

                } catch (Exception e) {
                    logger.warn("Low ElasticSearch version for getMapping");
                    response = RestHighLevelClientExt.getMapping(restHighLevelClient, request, RequestOptions.DEFAULT);
                }

                mappingMetaData = response.mappings().get(index).get(type);
            } catch (NullPointerException e) {
                logger.warn("Not found the mapping info of index: " + index);
            } catch (IOException e) {
                logger.error(e.getMessage(), e);
            }
        }
        return mappingMetaData;
    }


    private MappingMetaData getMappingByAlias(String alias, String type) {
        MappingMetaData mappingMetaData = null;

        GetAliasesRequest getAliasesRequest = new GetAliasesRequest();
        getAliasesRequest.aliases(alias);

        try {
            GetAliasesResponse getAliasesResponse = restHighLevelClient.indices().getAlias(getAliasesRequest, RequestOptions.DEFAULT);
            if (getAliasesResponse != null
                    && getAliasesResponse.getAliases() != null
                    && getAliasesResponse.getAliases().size() == 1) {
                for (String index : getAliasesResponse.getAliases().keySet()) {
                    mappingMetaData = getMappingByIndex(index, type);
                }
            }
        } catch (ConnectException e) {
            notifyError(e);
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }

        return mappingMetaData;
    }
```

**Comment by mirocolo** [comment]
感谢 这个写法在rest模式下 只有一个物流索引对应一个别名可用 但是TRANSPORT模式 就不行了 还得稍微改改 算是临时解决

**Comment by jiaowc** [comment]
这个问题在那个版本中解决了？ 我也遇到这个问题。

**Comment by mirocolo** [comment]
> 这个问题在那个版本中解决了？ 我也遇到这个问题。

没解决 当初自己fork下来 我拿上方这个哥们提供的部分代码在自己调试改动后解决的，各自的ES版本不一样就没提交，时间久远也翻不回来了，你可以解决上方这位大佬提供的写法基于自己的版本调试解决

**Comment by jiaowc** [comment]
我下载下来源码看了，他们目前的版本只对es6支持，es7 8都没支持，我自己改了源码用的，感觉提的issus他们也不改

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2025年12月31日 15:15 |
| 收件人 | alibaba/canal ***@***.***> |
| 抄送人 | jiaowc ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [alibaba/canal] CanalAdapter 同步至Es时 使用Es别名抛出异常 (#2437) |
mirocolo left a comment (alibaba/canal#2437)

这个问题在那个版本中解决了？ 我也遇到这个问题。

没解决 当初自己fork下来 我拿上方这个哥们提供的部分代码在自己调试改动后解决的，各自的ES版本不一样就没提交，时间久远也翻不回来了，你可以解决上方这位大佬提供的写法基于自己的版本调试解决

**Comment by mirocolo** [comment]
> 我下载下来源码看了，他们目前的版本只对es6支持，es7 8都没支持，我自己改了源码用的，感觉提的issus他们也不改
> […](#)

嗯，开源么，有能力改咱们可以自己改，提request，不苛责，也可能正好咱们改了没出问题。当年还是个菜逼，不会提就没提了这么多年了也找不回来拉。
