### ISSUE TITLE
Could not find a 'KafkaClient' entry in the JAAS configuration. System property 'java.security.auth.login.config' is/canal-1.1.4/bin/../conf/kerberos/jaas.conf

### ISSUE THREAD

**Issue by BigData-YC** [alibaba/canal#2464]
关于canal同步数据到kafka的kerberos认证，操作过程：
1、修改canal.properties
canal.mq.kafka.kerberos.enable = true
canal.mq.kafka.kerberos.krb5FilePath = ../conf/kerberos/krb5.conf
canal.mq.kafka.kerberos.jaasFilePath = ../conf/kerberos/jaas.conf

2、在conf目录下创建kerberos文件夹
添加krb5.conf文件
添加jaas.conf文件
添加kafka.keytab文件
-----------在kerberos下有三个文件

3、krb5.conf文件和jaas.conf文件
连接：https://blog.csdn.net/weixin_40126236/article/details/103492815

问题：当开启zookeeper保存元数据的时候就会报这个错误，不使用zookeeper的时候就没有问题？？？？？？？？？？？？？

**Comment by BigData-YC** [comment]
配置zookeeper同时使用classpath:spring/default-instance.xml 就会报错
不配置zookeeper使用classpath:spring/file-instance.xml 就不会报错

**Comment by BigData-YC** [comment]
自己问题，自己解决，
在启动脚本/bin/start.sh里面添加一句
JAVA_OPTS=" $JAVA_OPTS -Djava.security.auth.login.config=$base/conf/kerberos/jaas.conf"
就可以了，，，前提是按照以上步骤操作了！！！！！！！！！！！！！

**Comment by zhiyuan192shine** [comment]
> 自己问题，自己解决，
> 在启动脚本/bin/start.sh里面添加一句
> JAVA_OPTS=" $JAVA_OPTS -Djava.security.auth.login.config=$base/conf/kerberos/jaas.conf"
> 就可以了，，，前提是按照以上步骤操作了！！！！！！！！！！！！！

我目前的情况跟你一样，按照你的操作，我依然也不行，还是出现一样的错误

**Comment by zhiyuan192shine** [comment]
> 自己问题，自己解决，
> 在启动脚本/bin/start.sh里面添加一句
> JAVA_OPTS=" $JAVA_OPTS -Djava.security.auth.login.config=$base/conf/kerberos/jaas.conf"
> 就可以了，，，前提是按照以上步骤操作了！！！！！！！！！！！！！

按照你的方式，我直接出现这个异常： com.google.common.collect.ComputationException: org.I0Itec.zkclient.exception.ZkAuthFailedException: Authentication failure

**Comment by BigData-YC** [comment]
你的zookeeper是不是也需要认证，，zookeeper还没做到kerberos认证，，，目前官网只有kafka的认证

**Comment by BigData-YC** [comment]
你的zookeeper是不是也需要认证，，zookeeper还没做到kerberos认证，，，目前官网只有kafka的认证

**Comment by BigData-YC** [comment]
你的zookeeper是不是也需要认证，，zookeeper还没做到kerberos认证，，，目前官网只有kafka的认证

**Comment by zhiyuan192shine** [comment]
> 你的zookeeper是不是也需要认证，，zookeeper还没做到kerberos认证，，，目前官网只有kafka的认证

我在 startup.sh 里面加了 -Djava.security.krb5.conf  和 -Djava.security.auth.login.config， 启动没有出错，但是发送数据到 kafka 又出现：WARN  org.apache.kafka.clients.NetworkClient - [Producer clientId=producer-1] Error while fetching metadata with correlation id 2552 : {=INVALID_TOPIC_EXCEPTION}

**Comment by zhiyuan192shine** [comment]
> > 自己问题，自己解决，
> > 在启动脚本/bin/start.sh里面添加一句
> > JAVA_OPTS=" $JAVA_OPTS -Djava.security.auth.login.config=$base/conf/kerberos/jaas.conf"
> > 就可以了，，，前提是按照以上步骤操作了！！！！！！！！！！！！！
> 
> 我目前的情况跟你一样，按照你的操作，我依然也不行，还是出现一样的错误

我在 startup.sh JAVA_OPTS 里加了 -Djava.security.krb5.conf 和 -Djava.security.auth.login.config，现在没有出问题了，完美结合了 kerberos， 谢谢你的这个 issue 解决

**Comment by zhiyuan192shine** [comment]
> > > 自己问题，自己解决，
> > > 在启动脚本/bin/start.sh里面添加一句
> > > JAVA_OPTS=" $JAVA_OPTS -Djava.security.auth.login.config=$base/conf/kerberos/jaas.conf"
> > > 就可以了，，，前提是按照以上步骤操作了！！！！！！！！！！！！！
> > 
> > 
> > 我目前的情况跟你一样，按照你的操作，我依然也不行，还是出现一样的错误
> 
> 我在 startup.sh JAVA_OPTS 里加了 -Djava.security.krb5.conf 和 -Djava.security.auth.login.config，现在没有出问题了，完美结合了 kerberos， 谢谢你的这个 issue 解决

我现在运行一段时间后又出现了： [Producer clientId=producer-1] Error while fetching metadata with correlation id 3098 : {=INVALID_TOPIC_EXCEPTION}， 你的 canal 与 kafka kerberos 运行正常不 ？

**Comment by BigData-YC** [comment]
这个应该不是问题，是canal自己创建topic导致的。





---Original---

**Comment by BigData-YC** [comment]
你应该设置的是动态topic吧！canal自己创建topic时会出现这个error，但是不影响。这个需要你在kafka的配置里面设置允许创建,设置auto.create.topics.enable = true

**Comment by zhiyuan192shine** [comment]
> 你应该设置的是动态topic吧！canal自己创建topic时会出现这个error，但是不影响。这个需要你在kafka的配置里面设置允许创建,设置auto.create.topics.enable = true

auto.create.topics.enable  这个配置，我是开启了的，而且我的是拉取固定的表，topic 也是提前创建好了的。正常运行一段时间就会出现异常

**Comment by BigData-YC** [comment]
Error while fetching metadata with correlation id 3098 : {=INVALID_TOPIC_EXCEPTION}

这个问题可能是上游数据库的问题，可能是数据库或者binlog日志有问题。我最近也遇到了。摸索了一天，最终只能删除zookeeper上的元数据，重新启动，会丢失一部分数据。为了最小的丢失数据，只能在instance.properties里面配置canal.instance.master.timestamp= 毫秒。稍微大于报错的时间。。。。好的办法还没有找到。。。

**Comment by zhiyuan192shine** [comment]
> Error while fetching metadata with correlation id 3098 : {=INVALID_TOPIC_EXCEPTION}
> 
> 这个问题可能是上游数据库的问题，可能是数据库或者binlog日志有问题。我最近也遇到了。摸索了一天，最终只能删除zookeeper上的元数据，重新启动，会丢失一部分数据。为了最小的丢失数据，只能在instance.properties里面配置canal.instance.master.timestamp= 毫秒。稍微大于报错的时间。。。。好的办法还没有找到。。。

我发现了导致这个的原因，你看看日志是不是有出现：
```
2020-01-15 01:30:27.536 [destination = yms_prod , address = /*.*.*.*:10018 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - Socket timeout expired, closing connection
java.net.SocketTimeoutException: Timeout occurred, failed to read total 114 bytes in 25000 milliseconds, actual read only 100 bytes
	at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:124) ~[canal.parse.driver-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:174) ~[canal.parse-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:85) ~[canal.parse-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:235) [canal.parse-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:265) [canal.parse-1.1.4.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_141]
```

**Comment by BigData-YC** [comment]
Caused by: org.apache.kafka.common.errors.InvalidTopicException: 
2020-01-14 17:18:22.734 [pool-72-thread-2] ERROR com.alibaba.otter.canal.kafka.CanalKafkaProducer - java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.InvalidTopicException: 
java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.InvalidTopicException: 
        at com.alibaba.otter.canal.kafka.CanalKafkaProducer.produce(CanalKafkaProducer.java:215) ~[canal.server-1.1.4.jar:na]
        at com.alibaba.otter.canal.kafka.CanalKafkaProducer.send(CanalKafkaProducer.java:149) ~[canal.server-1.1.4.jar:na]
        at com.alibaba.otter.canal.kafka.CanalKafkaProducer.send(CanalKafkaProducer.java:117) ~[canal.server-1.1.4.jar:na]
        at com.alibaba.otter.canal.server.CanalMQStarter.worker(CanalMQStarter.java:183) [canal.server-1.1.4.jar:na]
        at com.alibaba.otter.canal.server.CanalMQStarter.access$500(CanalMQStarter.java:23) [canal.server-1.1.4.jar:na]
        at com.alibaba.otter.canal.server.CanalMQStarter$CanalMQRunnable.run(CanalMQStarter.java:225) [canal.server-1.1.4.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.InvalidTopicException: 
        at org.apache.kafka.clients.producer.KafkaProducer$FutureFailure.<init>(KafkaProducer.java:1255) ~[kafka-clients-2.1.1.jar_b:na]
        at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:916) ~[kafka-clients-2.1.1.jar_b:na]
        at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:839) ~[kafka-clients-2.1.1.jar_b:na]
        at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:726) ~[kafka-clients-2.1.1.jar_b:na]
        at com.alibaba.otter.canal.kafka.CanalKafkaProducer.produce(CanalKafkaProducer.java:199) ~[canal.server-1.1.4.jar:na]
        ... 8 common frames omitted

**Comment by zhiyuan192shine** [comment]
出现 25 秒超时，会导致后面错误，你看其他日志呢，可以用心跳SQL，产生binlog
