### ISSUE TITLE
example无法链接到mysql，报java.lang.NullPointerException

### ISSUE THREAD

**Issue by z070204z** [alibaba/canal#247]
2017-01-03 16:58:21.099 [destination = example , address = /127.0.0.1:3306 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - dump address /127.0.0.1:3306 has an error, retrying. caused by 
java.lang.NullPointerException: null
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.loadBinlogChecksum(MysqlConnection.java:284) ~[canal.parse-1.0.23.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:113) ~[canal.parse-1.0.23.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209) ~[canal.parse-1.0.23.jar:na]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_111]
2017-01-03 16:58:21.100 [destination = example , address = /127.0.0.1:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[java.lang.NullPointerException
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.loadBinlogChecksum(MysqlConnection.java:284)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:113)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209)
	at java.lang.Thread.run(Unknown Source)
]

定位到MysqlConnection.java:284代码为
if (columnValues != null && columnValues.size() >= 1 && columnValues.get(0).toUpperCase().equals("CRC32"))
MySQL版本5.5.14 ，前面查询 select @master_binlog_checksum 为null

**Comment by boboChina** [comment]
升级到最新版本

**Comment by agapple** [comment]
当前主干已经有人提了PR修复了

**Comment by CONANLMN** [comment]
你好，你解决了吗，我也碰到了同样的问题，用了1.0.23，不是已经是最新版本了吗？

**Comment by z070204z** [comment]
@CONANLMN 这个问题我已经修复提交了，Release里面应该是没有重新打包，你去把最新的源码下下来编译了，替换掉MysqlConnection.class就行

**Comment by gaoqiang-0327** [comment]
为啥我1.1.4还有这问题

**Comment by jiayuxiaochaoren** [comment]
为啥我1.1.5还有这个问题
