### ISSUE TITLE
kafka动态topic发送有问题bug

### ISSUE THREAD

**Issue by Arthurker** [alibaba/canal#2471]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment
测试环境
centos7.5
canal版本1.1.4
kafka2.11
mysql5.7.26

* canal version
* mysql version

### Issue Description
canal推到kafka的数据使用动态主题，从
canal.mq.dynamicTopic=databasename\\..*
变成
canal.mq.dynamicTopic=.\*\\..*
后
报错
更改需求，从某个库的同步变成整个数据库实例的同步，主题名称变成数据库名+表名

### Steps to reproduce

从原先正常的canal动态推送kafka固定主题改成全动态生成主题
canal.mq.dynamicTopic=databasename\\..*
变成
canal.mq.dynamicTopic=. *\\..*

### Expected behaviour

2019-12-14 21:19:13.374 [pool-53-thread-3] ERROR com.alibaba.otter.canal.kafka.CanalKafkaProducer - java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.
java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.
	at com.alibaba.otter.canal.kafka.CanalKafkaProducer.produce(CanalKafkaProducer.java:215) ~[canal.server-1.1.4.jar:na]
	at com.alibaba.otter.canal.kafka.CanalKafkaProducer.send(CanalKafkaProducer.java:179) ~[canal.server-1.1.4.jar:na]
	at com.alibaba.otter.canal.kafka.CanalKafkaProducer.send(CanalKafkaProducer.java:117) ~[canal.server-1.1.4.jar:na]
	at com.alibaba.otter.canal.server.CanalMQStarter.worker(CanalMQStarter.java:183) [canal.server-1.1.4.jar:na]
	at com.alibaba.otter.canal.server.CanalMQStarter.access$500(CanalMQStarter.java:23) [canal.server-1.1.4.jar:na]
	at com.alibaba.otter.canal.server.CanalMQStarter$CanalMQRunnable.run(CanalMQStarter.java:225) [canal.server-1.1.4.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_231]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_231]
Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.
	at org.apache.kafka.clients.producer.KafkaProducer$FutureFailure.<init>(KafkaProducer.java:1150) ~[kafka-clients-1.1.1.jar:na]
	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:846) ~[kafka-clients-1.1.1.jar:na]
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:784) ~[kafka-clients-1.1.1.jar:na]
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:671) ~[kafka-clients-1.1.1.jar:na]
	at com.alibaba.otter.canal.kafka.CanalKafkaProducer.produce(CanalKafkaProducer.java:199) ~[canal.server-1.1.4.jar:na]
	... 8 common frames omitted

### Actual behaviour

If there is an exception, please attach the exception trace:
没有使用ide试调
```
Just put your stack trace here!
```

**Comment by xyz327** [comment]
我们也遇到这个问题，看代码发现1.1.4 kafkaProducer 发送的时候 把 .替换成_ 的逻辑被注释了,然后最新代码改回来了
https://github.com/alibaba/canal/blob/canal-1.1.4/server/src/main/java/com/alibaba/otter/canal/kafka/CanalKafkaProducer.java#L112

这应该是1.1.4的bug
