### ISSUE TITLE
canal1.1.4版本启动错误哦

### ISSUE THREAD

**Issue by 1120025919** [alibaba/canal#2483]
lassic.LoggerContext]
Reported exception:
ch.qos.logback.core.LogbackException: Unexpected filename extension of file [file:/C:/defineserver/canal_server/canal.deployer-1.1.4/conf/]. Should be either .groovy or .xml
        at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:79)
        at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:152)
        at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:85)
        at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
        at org.slf4j.LoggerFactory.bind(LoggerFactory.java:141)
        at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:120)
        at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:331)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:283)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:304)
        at com.alibaba.otter.canal.deployer.CanalLauncher.<clinit>(CanalLauncher.java:29)

window环境下启动报这个错误

**Comment by chongchongzi** [comment]
我也出现这个问题

**Comment by xuebinwang** [comment]
startup.cmd文件中
set logback_configurationFile=%conf_dir%\logback.xml
这一句被注释掉了，放开就好了。

**Comment by 1120025919** [comment]
嗯呢谢谢了
