### ISSUE TITLE
主备切换的问题

### ISSUE THREAD

**Issue by ch-lgs** [alibaba/canal#249]
主备切换的过程中出现错误，log如下（注意mysql-bin.000029=7¾以及Could not find first log file name in binary log index）
2017-01-03 22:09:16.930 [destination = xiaopang3 , address = /192.168.6.123:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - client authentication packet is sent out.
2017-01-03 22:09:16.934 [destination = xiaopang3 , address = /192.168.6.123:3306 , EventParser] INFO  c.a.otter.canal.parse.inbound.mysql.MysqlConnection - COM_BINLOG_DUMP with position:BinlogDumpCommandPacket[binlogPosition=21725485,slaveServerId=1237,binlogFileName=mysql-bin.000029=7¾,command=18]
2017-01-03 22:09:16.935 [destination = xiaopang3 , address = /192.168.6.123:3306 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - I/O error while reading from client socket
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:95) ~[canal.parse-1.0.23.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:121) [canal.parse-1.0.23.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209) [canal.parse-1.0.23.jar:na]
	at java.lang.Thread.run(Thread.java:744) [na:1.7.0_45]
2017-01-03 22:09:16.935 [destination = xiaopang3 , address = /192.168.6.123:3306 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - dump address /192.168.6.123:3306 has an error, retrying. caused by 
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:95) ~[canal.parse-1.0.23.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:121) ~[canal.parse-1.0.23.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209) ~[canal.parse-1.0.23.jar:na]
	at java.lang.Thread.run(Thread.java:744) [na:1.7.0_45]
2017-01-03 22:09:16.935 [destination = xiaopang3 , address = /192.168.6.123:3306 , EventParser] ERROR com.alibaba.otter.canal.common.

**Comment by agapple** [comment]
感觉是binlog名字出现了乱码，试试当前主干

**Comment by brandom-iava** [comment]
@agapple 这个问题在1.0.26版本上还是存在，知道什么原因吗？

**Comment by lijie1992066** [comment]
我也遇到同样的问题，canal  版本 v1.0.26 alpha 1， mariadb 版本用的 10.2.11，切换的时候 发现binlog文件名字乱码。

**Comment by agapple** [comment]
@lijie1992066 提供一下对应的binlog文件给我

**Comment by ZhiXingHeYiApple** [comment]
我也遇到了同样的问题，主备切换时老是报binlog找不到，断点调试如下：
![image](https://user-images.githubusercontent.com/20380664/38121113-d6675676-33ff-11e8-9341-6703fa332bd6.png)
感觉后缀上有乱码

**Comment by agapple** [comment]
能debug看看，这个乱码的位点是从哪里获取到的？@ZhiXingHeYiApple
