### ISSUE TITLE
1.1.4，instance启用，日志循环create hive表的意义

### ISSUE THREAD

**Issue by xuebinwang** [alibaba/canal#2499]
Caused by: java.io.IOException: ErrorPacket [errorNumber=1146, fieldCount=-1, message=Table 'hive.aux_table' doesn't exist, sqlState=42S02, sqlStateMarker=#]
 with command: show create table `hive`.`AUX_TABLE`;show create table `hive`.`BUCKETING_COLS`;show create table `hive`.`CDS`;
 show create table `hive`.`COLUMNS_V2`;show create table `hive`.`COMPACTION_QUEUE`;
 show create table `hive`.`COMPLETED_COMPACTIONS`;show create table `hive`.`COMPLETED_TXN_COMPONENTS`;
 show create table `hive`.`DATABASE_PARAMS`;show create table `hive`.`DBS`;
 show create table `hive`.`DB_PRIVS`;show create table `hive`.`DELEGATION_TOKENS`;
 show create table `hive`.`FUNCS`;show create table `hive`.`FUNC_RU`;
 show create table `hive`.`GLOBAL_PRIVS`;show create table `hive`.`HIVE_LOCKS`;
 show create table `hive`.`IDXS`;show create table `hive`.`INDEX_PARAMS`;
 show create table `hive`.`KEY_CONSTRAINTS`;show create table `hive`.`MASTER_KEYS`;
 show create table `hive`.`NEXT_COMPACTION_QUEUE_ID`;show create table `hive`.`NEXT_LOCK_ID`;
 show create table `hive`.`NEXT_TXN_ID`;show create table `hive`.`NOTIFICATION_LOG`;
 show create table `hive`.`NOTIFICATION_SEQUENCE`;show create table `hive`.`NUCLEUS_TABLES`;
 show create table `hive`.`PARTITIONS`;show create table `hive`.`PARTITION_EVENTS`;
 show create table `hive`.`PARTITION_KEYS`;show create table `hive`.`PARTITION_KEY_VALS`;
 show create table `hive`.`PARTITION_PARAMS`;show create table `hive`.`PART_COL_PRIVS`;
 show create table `hive`.`PART_COL_STATS`;show create table `hive`.`PART_PRIVS`;
 show create table `hive`.`ROLES`;show create table `hive`.`ROLE_MAP`;show create table `hive`.`SDS`;
 show create table `hive`.`SD_PARAMS`;show create table `hive`.`SEQUENCE_TABLE`;
 show create table `hive`.`SERDES`;show create table `hive`.`SERDE_PARAMS`;
 show create table `hive`.`SKEWED_COL_NAMES`;show create table `hive`.`SKEWED_COL_VALUE_LOC_MAP`;
 show create table `hive`.`SKEWED_STRING_LIST`;show create table `hive`.`SKEWED_STRING_LIST_VALUES`;
 show create table `hive`.`SKEWED_VALUES`;show create table `hive`.`SORT_COLS`;
 show create table `hive`.`TABLE_PARAMS`;show create table `hive`.`TAB_COL_STATS`;
 show create table `hive`.`TBLS`;show create table `hive`.`TBL_COL_PRIVS`;
 show create table `hive`.`TBL_PRIVS`;show create table `hive`.`TXNS`;
 show create table `hive`.`TXN_COMPONENTS`;
 show create table `hive`.`TYPES`;show create table `hive`.`TYPE_FIELDS`;
 show create table `hive`.`VERSION`;
 show create table `hive`.`WRITE_SET`;
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlQueryExecutor.queryMulti(MysqlQueryExecutor.java:109) ~[classes/:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.queryMulti(MysqlConnection.java:111) ~[classes/:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.dumpTableMeta(DatabaseTableMeta.java:232) ~[classes/:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:182) ~[classes/:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:137) ~[classes/:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:200) ~[classes/:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]

**Comment by agapple** [comment]
Table 'hive.aux_table' doesn't exist，清空一下tsdb
