### ISSUE TITLE
 CanalConnectors.newClusterConnector使用zookeeper 异常

### ISSUE THREAD

**Issue by xuebinwang** [alibaba/canal#2509]
使用OK：
// 基于固定canal server的地址，建立链接，其中一台server发生crash，可以支持failover
         CanalConnector connector = CanalConnectors.newClusterConnector(
         Arrays.asList(
                 new InetSocketAddress("server1", 11111),
                 new InetSocketAddress("server2", 11111)),
                 destination, "canal", "E3619321C1A937C46A0D8BD1DAC39F93B27D4458");

使用no OK：
 // 基于zookeeper动态获取canal server的地址，建立链接，其中一台server发生crash，可以支持failover
        CanalConnector connector = CanalConnectors.newClusterConnector(
                "server1:2181", destination,
                "canal",
                "E3619321C1A937C46A0D8BD1DAC39F93B27D4458");

异常： initClusters(this.zkClient.getChildren(clusterPath));

2019-12-27 11:35:45.426 [main-EventThread] INFO  org.I0Itec.zkclient.ZkClient - zookeeper state changed (SyncConnected)
Exception in thread "main" org.I0Itec.zkclient.exception.ZkNoNodeException: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /otter/canal/destinations/server1-canal-manager/cluster
	at org.I0Itec.zkclient.exception.ZkException.create(ZkException.java:47)
	at org.I0Itec.zkclient.ZkClient.retryUntilConnected(ZkClient.java:1001)
	at org.I0Itec.zkclient.ZkClient.getChildren(ZkClient.java:677)
	at org.I0Itec.zkclient.ZkClient.getChildren(ZkClient.java:673)

**Comment by xuebinwang** [comment]
自问自答，调试好了，是因为集群主配置的canal.zkServers未配置
canal.zkServers =server1：2181
