### ISSUE TITLE
使用1.1.4-admin manager模式instance显示及连接问题

### ISSUE THREAD

**Issue by user-GitHub-user** [alibaba/canal#2538]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version
1.1.4
* mysql version
5.7.28
### Issue Description
1.
当使用admin web ui管理模式时，instance若没有客户端消费，启动时提示启动成功，且日志显示：auto notify start example successful，但web ui上一直显示不出运行状况，如下：
![image](https://user-images.githubusercontent.com/18843801/71872392-39ceee80-3157-11ea-853a-abc2d175563d.png)
开启adapter logger客户端后,客户端先抛出异常，然后自动恢复连接上了instance实例，开启客户端后，web ui上instance显示为已启动

2.在server1详情里停止instance时，每次都会隔几秒在相同的server1上启动，并不会切换到HA的另一台机器server2上，而停止整个server1，server1上的instance会切换到server2上（然而同问题1所述，如果此时没有客户端在消费，instance的状态在web上是不可知的）

### Steps to reproduce
使用 admin manager模式开启instance
### Expected behaviour
无客户端连接时，instance实例状态正常显示，第一次客户端连接不报错
### Actual behaviour
无客户端连接时，instance实例状态显示异常，第一次客户端连接报错

If there is an exception, please attach the exception trace:

```
2020-01-07 13:58:58.206 [main] INFO  c.a.o.canal.adapter.launcher.loader.CanalAdapterService - ## start the canal client adapters.
2020-01-07 13:58:58.223 [main] INFO  c.a.otter.canal.client.adapter.support.ExtensionLoader - extension classpath dir: /usr/local/canal-adapter/plugin
2020-01-07 13:58:58.241 [main] INFO  c.a.o.canal.adapter.launcher.loader.CanalAdapterLoader - Load canal adapter: logger succeed
2020-01-07 13:58:58.252 [main] INFO  c.a.o.canal.adapter.launcher.loader.CanalAdapterLoader - Start adapter for canal instance: example succeed
2020-01-07 13:58:58.292 [main] INFO  c.a.o.canal.adapter.launcher.loader.CanalAdapterService - ## the canal client adapters are running now ......
2020-01-07 13:58:58.290 [Thread-3] INFO  c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - =============> Start to connect destination: example <=============
2020-01-07 13:58:58.309 [main] INFO  org.apache.coyote.http11.Http11NioProtocol - Starting ProtocolHandler ["http-nio-8081"]
2020-01-07 13:58:58.320 [main] INFO  org.apache.tomcat.util.net.NioSelectorPool - Using a shared selector for servlet write/read
2020-01-07 13:58:58.335 [main] INFO  o.s.boot.web.embedded.tomcat.TomcatWebServer - Tomcat started on port(s): 8081 (http) with context path ''
2020-01-07 13:58:58.338 [main] INFO  c.a.otter.canal.adapter.launcher.CanalAdapterApplication - Started CanalAdapterApplication in 2.883 seconds (JVM running for 3.417)
2020-01-07 13:58:58.373 [Thread-3] INFO  c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - =============> Start to subscribe destination: example <=============
2020-01-07 13:58:58.430 [Thread-3] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - process error!
com.alibaba.otter.canal.protocol.exception.CanalClientException: failed to subscribe with reason: something goes wrong with channel:[id: 0x1aa68d30, /192.168.11.102:50357 => /192.168.11.102:11111], exception=com.alibaba.otter.canal.serve
r.exception.CanalServerException: destination:example should start first

	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.subscribe(SimpleCanalConnector.java:249)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.subscribe(SimpleCanalConnector.java:226)
	at com.alibaba.otter.canal.adapter.launcher.loader.CanalAdapterWorker.process(CanalAdapterWorker.java:90)
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker$$Lambda$333/1299661385.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
2020-01-07 13:58:58.431 [Thread-3] INFO  c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - =============> Disconnect destination: example <=============
2020-01-07 13:58:59.431 [Thread-3] INFO  c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - =============> Start to connect destination: example <=============
2020-01-07 13:58:59.433 [Thread-3] INFO  c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - =============> Start to subscribe destination: example <=============
2020-01-07 13:58:59.478 [Thread-3] INFO  c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - =============> Subscribe destination: example succeed <=============
```

**Comment by Brainhu** [comment]
这个1.1.4的admin 压根就不能用啊,local.properties覆盖canal.properties 配置文件，server 压根启动不了。报 config empty？

**Comment by user-GitHub-user** [comment]
不影响使用

**Comment by user-GitHub-user** [comment]
不影响使用
