### ISSUE TITLE
canal 1.1.4  kafka with kerberos's  exception

### ISSUE THREAD

**Issue by zhiyuan192shine** [alibaba/canal#2540]
### environment

* canal version
canal 1.1.4
* mysql version
5.6

### Issue Description
借助 zookeeper 使用 canal 1.1.4 集群模式，将 binlog 数据到开启kerberos后的kafka模式，启动会直接出现异常。（canal.mq.kafka.kerberos.krb5FilePath、canal.mq.kafka.kerberos.jaasFilePath这两配置我在canal admin 里已经配置好）
```
org.apache.kafka.common.KafkaException: Failed to construct kafka producer
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:456) ~[kafka-clients-1.1.1.jar:na]
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:303) ~[kafka-clients-1.1.1.jar:na]
	at com.alibaba.otter.canal.kafka.CanalKafkaProducer.init(CanalKafkaProducer.java:81) ~[canal.server-1.1.4.jar:na]
	at com.alibaba.otter.canal.server.CanalMQStarter.start(CanalMQStarter.java:51) ~[canal.server-1.1.4.jar:na]
	at com.alibaba.otter.canal.deployer.CanalStarter.start(CanalStarter.java:101) [canal.deployer-1.1.4.jar:na]
	at com.alibaba.otter.canal.deployer.CanalLauncher.main(CanalLauncher.java:115) [canal.deployer-1.1.4.jar:na]
Caused by: java.lang.IllegalArgumentException: Could not find a 'KafkaClient' entry in the JAAS configuration. System property 'java.security.auth.login.config' is /opt/apps/canal/deployer/kerberos/glp_test/jaas.conf
	at org.apache.kafka.common.security.JaasContext.defaultContext(JaasContext.java:133) ~[kafka-clients-1.1.1.jar:na]
	at org.apache.kafka.common.security.JaasContext.load(JaasContext.java:98) ~[kafka-clients-1.1.1.jar:na]
	at org.apache.kafka.common.security.JaasContext.loadClientContext(JaasContext.java:84) ~[kafka-clients-1.1.1.jar:na]
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:119) ~[kafka-clients-1.1.1.jar:na]
	at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:65) ~[kafka-clients-1.1.1.jar:na]
	at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:88) ~[kafka-clients-1.1.1.jar:na]
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:413) ~[kafka-clients-1.1.1.jar:na]
	... 5 common frames omitted

```

出现以上问题后，我又在 startup.sh 里的 JAVA_OPTS 中加入 `-Djava.security.krb5.conf=/etc/krb5.conf -Djava.security.auth.login.config=/etc/krb5.conf.d/jaas.conf` ，然后启动正常，但是正常运行一段时间后，会出现以下问题：

```
2020-01-08 15:38:52.446 [kafka-producer-network-thread | producer-1] WARN  org.apache.kafka.clients.NetworkClient - [Producer clientId=producer-1] Error while fetching metadata with correlation id 464608 : {=INVALID_TOPIC_EXCEPTION}
2020-01-08 15:38:52.548 [kafka-producer-network-thread | producer-1] WARN  org.apache.kafka.clients.NetworkClient - [Producer clientId=producer-1] Error while fetching metadata with correlation id 464609 : {=INVALID_TOPIC_EXCEPTION}
2020-01-08 15:38:52.650 [kafka-producer-network-thread | producer-1] WARN  org.apache.kafka.clients.NetworkClient - [Producer clientId=producer-1] Error while fetching metadata with correlation id 464610 : {=INVALID_TOPIC_EXCEPTION}
```

**Comment by BillowX** [comment]
方便将你的jaas.conf贴出来么？
有没有试过用命令行的方式去消费带kerberos认证的KAFKA？

**Comment by zhiyuan192shine** [comment]
> 方便将你的jaas.conf贴出来么？
> 有没有试过用命令行的方式去消费带kerberos认证的KAFKA？
KafkaClient {
  com.sun.security.auth.module.Krb5LoginModule required
  useKeyTab=true
  storeKey=true
  serviceName="kafka"
  keyTab="/etc/security/keytab/bigdata.keytab"
  principal="bigdata@GLPROP.COM";
};

Client {
  com.sun.security.auth.module.Krb5LoginModule required
  useKeyTab=true
  storeKey=true
  keyTab="/etc/security/keytab/bigdata.keytab"
  principal="bigdata@GLPROP.COM";
};

命令行是没有任何问题的，正常运行几天就会出异常：WARN  org.apache.kafka.clients.NetworkClient - [Producer clientId=producer-1] Error while fetching metadata with correlation id 464608 : {=INVALID_TOPIC_EXCEPTION}

**Comment by hyperglory** [comment]
> > 方便将你的jaas.conf贴出来么？
> > 有没有试过用命令行的方式去消费带kerberos认证的KAFKA？
> 
> ```
> KafkaClient {
>   com.sun.security.auth.module.Krb5LoginModule required
>   useKeyTab=true
>   storeKey=true
>   serviceName="kafka"
>   keyTab="/etc/security/keytab/bigdata.keytab"
>   principal="bigdata@GLPROP.COM";
> };
> 
> Client {
>   com.sun.security.auth.module.Krb5LoginModule required
>   useKeyTab=true
>   storeKey=true
>   keyTab="/etc/security/keytab/bigdata.keytab"
>   principal="bigdata@GLPROP.COM";
> };
> ```
> 
> 命令行是没有任何问题的，正常运行几天就会出异常：WARN org.apache.kafka.clients.NetworkClient - [Producer clientId=producer-1] Error while fetching metadata with correlation id 464608 : {=INVALID_TOPIC_EXCEPTION}

请问你的这个问题解决了么？我也是运行一段时间后出现异常：
[kafka-producer-network-thread | producer-1] WARN  org.apache.kafka.clients.NetworkClient - [Producer clientId=producer-1] Error while fetching metadata with correlation id 260825 : {=UNKNOWN_SERVER_ERROR}

**Comment by zhiyuan192shine** [comment]
> > > 方便将你的jaas.conf贴出来么？
> > > 有没有试过用命令行的方式去消费带kerberos认证的KAFKA？
> > 
> > 
> > ```
> > KafkaClient {
> >   com.sun.security.auth.module.Krb5LoginModule required
> >   useKeyTab=true
> >   storeKey=true
> >   serviceName="kafka"
> >   keyTab="/etc/security/keytab/bigdata.keytab"
> >   principal="bigdata@GLPROP.COM";
> > };
> > 
> > Client {
> >   com.sun.security.auth.module.Krb5LoginModule required
> >   useKeyTab=true
> >   storeKey=true
> >   keyTab="/etc/security/keytab/bigdata.keytab"
> >   principal="bigdata@GLPROP.COM";
> > };
> > ```
> > 
> > 
> > 命令行是没有任何问题的，正常运行几天就会出异常：WARN org.apache.kafka.clients.NetworkClient - [Producer clientId=producer-1] Error while fetching metadata with correlation id 464608 : {=INVALID_TOPIC_EXCEPTION}
> 
> 请问你的这个问题解决了么？我也是运行一段时间后出现异常：
> [kafka-producer-network-thread | producer-1] WARN org.apache.kafka.clients.NetworkClient - [Producer clientId=producer-1] Error while fetching metadata with correlation id 260825 : {=UNKNOWN_SERVER_ERROR}

这个问题很诡异，我加了以下两个配置可以运行很长一段时间
canal.instance.detecting.enable = true
canal.instance.detecting.sql = select 1
