### ISSUE TITLE
Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not open log file

### ISSUE THREAD

**Issue by linqh1** [alibaba/canal#2546]
canal版本：1.1.2
mysql版本：5.6.41-log

otter同步报错：
`pid:327 nid:20 exception:canal:la-qcc-portal-prod:java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not open log file
at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102)
at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:159)
at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:271)
at java.lang.Thread.run(Thread.java:748)
`

查看了一下出错时候的binlog和position,没发现有异常的地方:

`SHOW BINLOG EVENTS IN 'mysql-bin.000355' FROM 1073809958`

![image](https://user-images.githubusercontent.com/42435177/72229730-d0822c00-35eb-11ea-9651-7bde00fce9d8.png)

然后我把位点信息改成下一个(如上图mysql-bin.000356;pos=4)就可以了.

感觉是canal解析binlog的时候没有考虑到这种case吗?

**Comment by linqh1** [comment]
#705 这里也有人提到相同的问题，但是我觉得并没有找出问题的本质

**Comment by agapple** [comment]
这是mysql binlog协议的约束，不能随意指定位点

**Comment by linqh1** [comment]
> 这是mysql binlog协议的约束，不能随意指定位点

没有随意指定位点啊，出问题的位点1073809958是otter自己走到那里的，走到那里otter就走不下去了。需要人为挪到下一个位点
