### ISSUE TITLE
BUG，在Mysql 5.5.28版本下报错

### ISSUE THREAD

**Issue by xut2447** [alibaba/canal#255]
日志：
2017-01-12 12:06:16.107 [destination = example , address = /127.0.0.1:3306 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - dump address /127.0.0.1:3306 has an error, retrying. caused by 
java.lang.NullPointerException: null
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.loadBinlogChecksum(MysqlConnection.java:309) ~[canal.parse-1.0.24-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:120) ~[canal.parse-1.0.24-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209) ~[canal.parse-1.0.24-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Unknown Source) [na:1.7.0_80]

原因：程序BUG，缺少null判断
if (columnValues != null && columnValues.size() >= 1
				&& columnValues.get(0).toUpperCase().equals("CRC32"))
改为：
if (columnValues != null && columnValues.size() >= 1
				&& columnValues.get(0) != null   //缺少的判断
				&& columnValues.get(0).toUpperCase().equals("CRC32"))

症状消除！

**Comment by agapple** [comment]
请更新当前master版本

**Comment by keyganker** [comment]
感觉这个问题比较严重啊，建议发一个release比较好，对于低版本mysql，canal直接无法正常启动了
