### ISSUE TITLE
canal-admin未读取到instance中的配置文件

### ISSUE THREAD

**Issue by liujiansgit** [alibaba/canal#2568]
##版本
1.1.4
##同时使用canal-server及canal-admin未读取到example中的配置文件，是哪里的问题呢，异常信息如下：
2020-02-04 15:02:46.924 [main] INFO  com.alibaba.otter.canal.deployer.CanalStarter - ## start the canal server.
2020-02-04 15:02:46.954 [main] INFO  com.alibaba.otter.canal.deployer.CanalController - ## start the canal server[172.17.0.1(172.17.0.1):11111]
2020-02-04 15:02:47.057 [main] ERROR c.a.o.c.common.zookeeper.running.ServerRunningMonitor - start failed
com.google.common.collect.ComputationException: com.alibaba.otter.canal.common.CanalException: com.alibaba.otter.canal.common.CanalException: instance : example config is not found
	at com.google.common.collect.MapMaker$ComputingMapAdapter.get(MapMaker.java:889) ~[guava-18.0.jar:na]
	at com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded.start(CanalServerWithEmbedded.java:137) ~[canal.server-1.1.4.jar:na]
	at com.alibaba.otter.canal.deployer.CanalController$2$1.processActiveEnter(CanalController.java:160) ~[canal.deployer-1.1.4.jar:na]
	at com.alibaba.otter.canal.common.zookeeper.running.ServerRunningMonitor.processActiveEnter(ServerRunningMonitor.java:247) ~[canal.common-1.1.4.jar:na]
	at com.alibaba.otter.canal.common.zookeeper.running.ServerRunningMonitor.start(ServerRunningMonitor.java:104) ~[canal.common-1.1.4.jar:na]
	at com.alibaba.otter.canal.deployer.CanalController.start(CanalController.java:513) [canal.deployer-1.1.4.jar:na]
	at com.alibaba.otter.canal.deployer.CanalStarter.start(CanalStarter.java:78) [canal.deployer-1.1.4.jar:na]
	at com.alibaba.otter.canal.deployer.CanalLauncher.main(CanalLauncher.java:115) [canal.deployer-1.1.4.jar:na]
Caused by: com.alibaba.otter.canal.common.CanalException: com.alibaba.otter.canal.common.CanalException: instance : example config is not found
Caused by: com.alibaba.otter.canal.common.CanalException: instance : example config is not found
2020-02-04 15:02:47.067 [main] INFO  com.alibaba.otter.canal.deployer.CanalStarter - ## the canal server is running now ......

**Comment by medlying** [comment]
怎么解决的呢

**Comment by zhuwenxiang2** [comment]
有解决办法吗？
