### ISSUE TITLE
MysqlEventParser里发现一个bug

### ISSUE THREAD

**Issue by scyehan** [alibaba/canal#257]
1.0.23版里MysqlEventParser的stopHeartBeat方法里没有判断heartBeatTimerTask的类型就直接做强制转换，导致下面

java.lang.ClassCastException: com.alibaba.otter.canal.parse.inbound.AbstractEventParser$4 cannot be cast to com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser$MysqlDetectingTimeTask
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.stopHeartBeat(MysqlEventParser.java:186)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser.stop(AbstractEventParser.java:282)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.stop(MysqlEventParser.java:165)
	at com.alibaba.otter.canal.instance.core.AbstractCanalInstance.stop(AbstractCanalInstance.java:104)
	at com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded.stop(CanalServerWithEmbedded.java:85)

**Comment by jixingxing** [comment]
@agapple  大神，这个bug会导致eventparser线程释放不了，是不是意味着 canalserver stop 其实好多stop的事情都没能做到，啥时候能上 1.0.24版本到mvn仓库呢，坐等谢谢大神
