### ISSUE TITLE
1.1.4消费cannal传输到kafka中的数据的时候一直报错

### ISSUE THREAD

**Issue by xinweishao** [alibaba/canal#2588]
2020-02-24 14:31:08.775 [Thread-1] ERROR c.a.otter.canal.example.kafka.CanalKafkaClientExample - Error deserializing key/value for partition example-0 at offset 5. If needed, please seek past the record to continue consumption.
org.apache.kafka.common.errors.SerializationException: Error deserializing key/value for partition example-0 at offset 5. If needed, please seek past the record to continue consumption.
Caused by: com.alibaba.otter.canal.protocol.exception.CanalClientException: deserializer failed
	at com.alibaba.otter.canal.client.CanalMessageDeserializer.deserializer(CanalMessageDeserializer.java:54) ~[classes/:na]
	at com.alibaba.otter.canal.client.CanalMessageDeserializer.deserializer(CanalMessageDeserializer.java:14) ~[classes/:na]
	at com.alibaba.otter.canal.client.kafka.MessageDeserializer.deserialize(MessageDeserializer.java:24) ~[classes/:na]
	at com.alibaba.otter.canal.client.kafka.MessageDeserializer.deserialize(MessageDeserializer.java:16) ~[classes/:na]
	at org.apache.kafka.common.serialization.Deserializer.deserialize(Deserializer.java:60) ~[kafka-clients-2.3.0.jar:na]
	at org.apache.kafka.clients.consumer.internals.Fetcher.parseRecord(Fetcher.java:1264) ~[kafka-clients-2.3.0.jar:na]
	at org.apache.kafka.clients.consumer.internals.Fetcher.access$3600(Fetcher.java:124) ~[kafka-clients-2.3.0.jar:na]
	at org.apache.kafka.clients.consumer.internals.Fetcher$PartitionRecords.fetchRecords(Fetcher.java:1488) ~[kafka-clients-2.3.0.jar:na]
	at org.apache.kafka.clients.consumer.internals.Fetcher$PartitionRecords.access$1600(Fetcher.java:1328) ~[kafka-clients-2.3.0.jar:na]
	at org.apache.kafka.clients.consumer.internals.Fetcher.fetchRecords(Fetcher.java:641) ~[kafka-clients-2.3.0.jar:na]
	at org.apache.kafka.clients.consumer.internals.Fetcher.fetchedRecords(Fetcher.java:602) ~[kafka-clients-2.3.0.jar:na]
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1263) ~[kafka-clients-2.3.0.jar:na]
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1225) ~[kafka-clients-2.3.0.jar:na]
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1159) ~[kafka-clients-2.3.0.jar:na]
	at com.alibaba.otter.canal.client.kafka.KafkaCanalConnector.getListWithoutAck(KafkaCanalConnector.java:184) ~[classes/:na]
	at com.alibaba.otter.canal.example.kafka.CanalKafkaClientExample.process(CanalKafkaClientExample.java:114) [classes/:na]
	at com.alibaba.otter.canal.example.kafka.CanalKafkaClientExample.access$000(CanalKafkaClientExample.java:19) [classes/:na]
	at com.alibaba.otter.canal.example.kafka.CanalKafkaClientExample$3.run(CanalKafkaClientExample.java:78) [classes/:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
Caused by: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
	at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:86) ~[protobuf-java-3.6.1.jar:na]
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readRawBytes(CodedInputStream.java:1293) ~[protobuf-java-3.6.1.jar:na]
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readBytes(CodedInputStream.java:947) ~[protobuf-java-3.6.1.jar:na]
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:537) ~[protobuf-java-3.6.1.jar:na]
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:514) ~[protobuf-java-3.6.1.jar:na]
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:633) ~[protobuf-java-3.6.1.jar:na]
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:295) ~[protobuf-java-3.6.1.jar:na]
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readGroup(CodedInputStream.java:868) ~[protobuf-java-3.6.1.jar:na]
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:541) ~[protobuf-java-3.6.1.jar:na]
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:514) ~[protobuf-java-3.6.1.jar:na]
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:633) ~[protobuf-java-3.6.1.jar:na]
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:295) ~[protobuf-java-3.6.1.jar:na]
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readGroup(CodedInputStream.java:868) ~[protobuf-java-3.6.1.jar:na]
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:541) ~[protobuf-java-3.6.1.jar:na]
	at com.google.protobuf.GeneratedMessageV3.parseUnknownFieldProto3(GeneratedMessageV3.java:305) ~[protobuf-java-3.6.1.jar:na]
	at com.alibaba.otter.canal.protocol.CanalPacket$Packet.<init>(CanalPacket.java:475) ~[classes/:na]
	at com.alibaba.otter.canal.protocol.CanalPacket$Packet.<init>(CanalPacket.java:409) ~[classes/:na]
	at com.alibaba.otter.canal.protocol.CanalPacket$Packet$1.parsePartialFrom(CanalPacket.java:1396) ~[classes/:na]
	at com.alibaba.otter.canal.protocol.CanalPacket$Packet$1.parsePartialFrom(CanalPacket.java:1390) ~[classes/:na]
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:163) ~[protobuf-java-3.6.1.jar:na]
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:197) ~[protobuf-java-3.6.1.jar:na]
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:209) ~[protobuf-java-3.6.1.jar:na]
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:214) ~[protobuf-java-3.6.1.jar:na]
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49) ~[protobuf-java-3.6.1.jar:na]
	at com.alibaba.otter.canal.protocol.CanalPacket$Packet.parseFrom(CanalPacket.java:867) ~[classes/:na]
	at com.alibaba.otter.canal.client.CanalMessageDeserializer.deserializer(CanalMessageDeserializer.java:22) ~[classes/:na]
	... 18 common frames omitted

**Comment by xinweishao** [comment]
自行解决

**Comment by XuYijing2018** [comment]
请问怎么解决的呀？

**Comment by qiaojian0907** [comment]
> 自行解决

怎么解决的 ？
