### ISSUE TITLE
unknow type : 48

### ISSUE THREAD

**Issue by luispater** [alibaba/canal#2629]
- [x] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal 1.1.4
* mysql 8.0.18

### Issue Description
com.alibaba.otter.canal.parse.exception.CanalParseException: java.lang.IllegalArgumentException: unknow type : 48
Caused by: java.lang.IllegalArgumentException: unknow type : 48
        at com.taobao.tddl.dbsync.binlog.event.TableMapLogEvent.<init>(TableMapLogEvent.java:487) ~[canal.parse.dbsync-1.1.4.jar:na]
        at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:182) ~[canal.parse.dbsync-1.1.4.jar:na]
        at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:111) ~[canal.parse.dbsync-1.1.4.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:264) ~[canal.parse-1.1.4.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:246) ~[canal.parse-1.1.4.jar:na]
        at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168) ~[disruptor-3.4.2.jar:na]
        at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125) ~[disruptor-3.4.2.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_231]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_231]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_231]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_231]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_231]

**Comment by wlyu** [comment]
me too

mysql==8.0.18

============================================
Caused by: java.lang.IllegalArgumentException: unknow type : 227
	at com.taobao.tddl.dbsync.binlog.event.TableMapLogEvent.<init>(TableMapLogEvent.java:504)
	at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:152)
	at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:80)
============================================
           int numberOfColumns = inputStream.readPackedInteger();

          numberOfColumns ==101 ,but  count is 99  

SELECT * FROM information_schema.COLUMNS WHERE 
TABLE_SCHEMA='aaaa' and 
TABLE_NAME = 'bbbb'
========================================================
=========================[mysql-binlog-connector-java]=======
eventData.setColumnMetadata(readMetadata(inputStream, eventData.getColumnTypes()));
array[99]=20
array[100]=20

**Comment by wlyu** [comment]
@luispater 
happened in mysql8.0.18.
upgrade to 8.0.27 (test OK)

**Comment by zhuchao941** [comment]
是不是有表使用到了多值索引？

**Comment by zhuchao941** [comment]
是不是用到多值索引或者是stored generated column了？
