### ISSUE TITLE
es adapter create zookeeper node throw exception

### ISSUE THREAD

**Issue by KerryJava** [alibaba/canal#2649]
- [x] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment
windows， centos
* canal version
 master 分支 0e3d719a 
* mysql version
5.7
### Issue Description

使用zookeeper 配置es adapter就会报错，单机使用没有问题。

### Steps to reproduce
es adapter application.yml 配置了

canal.conf:
  mode: tcp #tcp kafka rocketMQ rabbitMQ
  #flatMessage: true
  syncBatchSize: 1000
  retries: 2
  timeout: 100000
  accessKey:
  secretKey:
  consumerProperties:
    # canal tcp consumer
    canal.tcp.zookeeper.hosts: 127.0.0.1:12181
    canal.tcp.batch.size: 500
### Expected behaviour
   能够成功订阅
### Actual behaviour
  实际上报异常

If there is an exception, please attach the exception trace:

```
log 日志：
2020-03-26 15:12:19.247 [Thread-5] ERROR c.a.otter.canal.client.impl.running.ClientRunningMonitor - There is an error when execute initRunning method, with destination [xxxx].
java.lang.LinkageError: loader constraint violation: loader (instance of sun/misc/Launcher$AppClassLoader) previously initiated loading for a different type with name "org/apache/zookeeper/CreateMode"
	at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_211]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[na:1.8.0_211]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.8.0_211]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468) ~[na:1.8.0_211]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[na:1.8.0_211]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[na:1.8.0_211]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[na:1.8.0_211]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_211]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[na:1.8.0_211]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_211]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[na:1.8.0_211]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_211]
	at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:766) ~[connector.tcp-1.1.5-SNAPSHOT-jar-with-dependencies.jar:3.4.5-1392090]
	at org.I0Itec.zkclient.ZkConnection.create(ZkConnection.java:100) ~[connector.tcp-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.I0Itec.zkclient.ZkClient$3.call(ZkClient.java:531) ~[connector.tcp-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.I0Itec.zkclient.ZkClient$3.call(ZkClient.java:528) ~[connector.tcp-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.I0Itec.zkclient.ZkClient.retryUntilConnected(ZkClient.java:991) ~[connector.tcp-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.I0Itec.zkclient.ZkClient.create(ZkClient.java:528) ~[connector.tcp-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.I0Itec.zkclient.ZkClient.create(ZkClient.java:499) ~[connector.tcp-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
	at com.alibaba.otter.canal.client.impl.running.ClientRunningMonitor.initRunning(ClientRunningMonitor.java:122) [connector.tcp-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
	at com.alibaba.otter.canal.client.impl.running.ClientRunningMonitor.start(ClientRunningMonitor.java:93) [connector.tcp-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.connect(SimpleCanalConnector.java:108) [connector.tcp-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
	at com.alibaba.otter.canal.client.impl.ClusterCanalConnector.connect(ClusterCanalConnector.java:64) [connector.tcp-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
	at com.alibaba.otter.canal.connector.tcp.consumer.CanalTCPConsumer.connect(CanalTCPConsumer.java:59) [connector.tcp-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.process(AdapterProcessor.java:184) [classes/:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_211]```

**Comment by agapple** [comment]
classloader问题还是第一次见

**Comment by XuDaojie** [comment]
我也遇到这个问题了，v1.1.5只要配置了`canal.tcp.zookeeper.hosts`就会抛出异常
