### ISSUE TITLE
adapter1.1.5写到es7时报空指针

### ISSUE THREAD

**Issue by nicygan** [alibaba/canal#2653]
## Question
服务端的binlog数据能正常读到，但当向es7写时，就会报nullpointException
`2020-03-31 15:31:01.606 [pool-2-thread-1] ERROR c.a.o.canal.client.adapter.es.core.service.ESSyncService - sync error, es index: test, DML : Dml{destination='test', database='test', table='test_2', type='INSERT', es=1585639863000, ts=1585639861606, sql='', data=[{name=fgd}], old=null}
2020-03-31 15:31:01.608 [pool-2-thread-1] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - java.lang.NullPointerException
java.lang.RuntimeException: java.lang.NullPointerException
        at com.alibaba.otter.canal.client.adapter.es.core.service.ESSyncService.sync(ESSyncService.java:112) ~[na:na]
        at com.alibaba.otter.canal.client.adapter.es.core.service.ESSyncService.sync(ESSyncService.java:60) ~[na:na]
        at com.alibaba.otter.canal.client.adapter.es.core.ESAdapter.sync(ESAdapter.java:116) ~[na:na]
        at com.alibaba.otter.canal.client.adapter.es.core.ESAdapter.sync(ESAdapter.java:95) ~[na:na]
        at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.batchSync(AbstractCanalAdapterWorker.java:201) ~[client-adapter.launcher-1.1.5-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$1(AbstractCanalAdapterWorker.java:62) ~[client-adapter.launcher-1.1.5-SNAPSHOT.jar:na]
        at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891) ~[na:1.8.0_171]
        at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$2(AbstractCanalAdapterWorker.java:58) ~[client-adapter.launcher-1.1.5-SNAPSHOT.jar:na]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_171]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_171]
Caused by: java.lang.NullPointerException: null
        at com.alibaba.otter.canal.client.adapter.es7x.support.ES7xTemplate.insert(ES7xTemplate.java:75) ~[na:na]
        at com.alibaba.otter.canal.client.adapter.es.core.service.ESSyncService.singleTableSimpleFiledInsert(ESSyncService.java:444) ~[na:na]
        at com.alibaba.otter.canal.client.adapter.es.core.service.ESSyncService.insert(ESSyncService.java:135) ~[na:na]
        at com.alibaba.otter.canal.client.adapter.es.core.service.ESSyncService.sync(ESSyncService.java:95) ~[na:na]
        ... 11 common frames omitted`

按照文档中进行配置的：
dataSourceKey: defaultDS
destination: test
groupId: g1
esMapping:
  _index: test
  _id: _id
  sql: "SELECT a.name FROM test_2 a"
  commitBatch: 3000

**Comment by lilujiong** [comment]
需要一个主键 as _id，如 sql: "SELECT a.id as _id, a.name FROM test_2 a"

**Comment by qing9527** [comment]
请问这个问题解决了吗？我遇到了同样的问题：同步mysql数据到es7中，报空指针

**Comment by lilujiong** [comment]
会不会sql里没有主键



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月24日(星期二) 上午10:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/canal] adapter1.1.5写到es7时报空指针 (#2653)





 
请问这个问题解决了吗？我遇到了同样的问题：同步mysql数据到es7中，报空指针
