### ISSUE TITLE
canal报错， Read Q_FLAGS2_CODE error: limit excceed: 75

### ISSUE THREAD

**Issue by daijunjian** [alibaba/canal#2658]
canal是1.1.3，Mysql是8.0.16

java.io.IOException: Read Q_FLAGS2_CODE error: limit excceed: 75
	at com.taobao.tddl.dbsync.binlog.event.QueryLogEvent.unpackVariables(QueryLogEvent.java:717)
	at com.taobao.tddl.dbsync.binlog.event.QueryLogEvent.<init>(QueryLogEvent.java:495)
	at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:168)
	at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:111)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:172)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:271)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: limit excceed: 75
	at com.taobao.tddl.dbsync.binlog.LogBuffer.getUint32(LogBuffer.java:562)
	at com.taobao.tddl.dbsync.binlog.event.QueryLogEvent.unpackVariables(QueryLogEvent.java:612)
	... 6 more

**Comment by agapple** [comment]
先升级canal版本到最新，印象中修复过类似的问题

**Comment by felowchu** [comment]
canal：1.1.5，mariadb: 10.6.4-MariaDB-log
报相同的错
java.io.IOException: Read Q_FLAGS2_CODE error: limit excceed: 82
	at com.taobao.tddl.dbsync.binlog.event.QueryLogEvent.unpackVariables(QueryLogEvent.java:715) ~[classes/:na]
	at com.taobao.tddl.dbsync.binlog.event.QueryLogEvent.<init>(QueryLogEvent.java:495) ~[classes/:na]
	at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:168) ~[classes/:na]
	at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:111) ~[classes/:na]

**Comment by SwimmingTiger** [comment]
* canal-1.1.6-hotfix-1
* 10.7.3-MariaDB

```
2022-08-15 11:34:11.873 [destination = hu60 , address = /127.0.0.1:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:hu60[com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: Read Q_FLAGS2_CODE error: limit excceed: 67
Caused by: java.io.IOException: Read Q_FLAGS2_CODE error: limit excceed: 67
        at com.taobao.tddl.dbsync.binlog.event.QueryLogEvent.unpackVariables(QueryLogEvent.java:715)
        at com.taobao.tddl.dbsync.binlog.event.QueryLogEvent.<init>(QueryLogEvent.java:495)
        at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:137)
        at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:80)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:269)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:251)
        at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168)
        at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: limit excceed: 67
        at com.taobao.tddl.dbsync.binlog.LogBuffer.getUint32(LogBuffer.java:562)
        at com.taobao.tddl.dbsync.binlog.event.QueryLogEvent.unpackVariables(QueryLogEvent.java:612)
```
