### ISSUE TITLE
canal_deloyer启动报错：org.apache.zookeeper.ClientCnxn - Session 0x0 for server null

### ISSUE THREAD

**Issue by mfc6b** [alibaba/canal#2666]
canal_deloyer启动报错：

2020-04-08 10:58:45.270 [main-SendThread(10.233.99.44:2181)] WARN  org.apache.zookeeper.ClientCnxn - Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_161]
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350) ~[zookeeper-3.4.5.jar:3.4.5-1392090]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1068) ~[zookeeper-3.4.5.jar:3.4.5-1392090]

备注：之前一直正常运行，莫名其妙就挂了，重启就报这个错误。蒙蔽了。

**Comment by tanhao-github** [comment]
1.1.4这个版本我也遇到了这个问题，zk用的是集群

**Comment by agapple** [comment]
Connection refused
