### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: org.apache.kafka.common.serialization.StringDeserializer

### ISSUE THREAD

**Issue by waynecookie** [alibaba/canal#2667]
Connected to the target VM, address: '127.0.0.1:60875', transport: 'socket'
2020-04-08 14:31:47.904 [main] ERROR c.a.otter.canal.example.kafka.CanalKafkaClientExample - ## Something goes wrong when starting up the kafka consumer:
java.lang.NoClassDefFoundError: org/apache/kafka/common/serialization/StringDeserializer
	at com.alibaba.otter.canal.client.kafka.KafkaCanalConnector.<init>(KafkaCanalConnector.java:64) ~[classes/:na]
	at com.alibaba.otter.canal.example.kafka.CanalKafkaClientExample.<init>(CanalKafkaClientExample.java:37) ~[classes/:na]
	at com.alibaba.otter.canal.example.kafka.CanalKafkaClientExample.main(CanalKafkaClientExample.java:42) ~[classes/:na]
Caused by: java.lang.ClassNotFoundException: org.apache.kafka.common.serialization.StringDeserializer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_181]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[na:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_181]
	... 3 common frames omitted

**Comment by liuyongfei1** [comment]
I have the same problem, for help!

**Comment by liuyongfei1** [comment]
hello,I've solved it. The solution：
1. cd zookeeper 运行zkCli.sh
2. ls /brokers/topics
3. rmr /brokers/topics/consumer_offsets
4. restart kafka cluster

**Comment by liuyongfei1** [comment]
hello,I've solved it. The solution：
idea => The Maven sidebar => Select the module => Right click  => Reimport
