### ISSUE TITLE
Could not find first log file name in binary log index file

### ISSUE THREAD

**Issue by codedart2018** [alibaba/canal#2673]
## Question

canal版本: 1.1.4
client: go
mysql: 8.0.19
环境：docker

日志
```
2020-04-12 22:14:50.958 [New I/O server worker #1-2] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - subscribe filter change to .*\..*
2020-04-12 22:14:50.959 [New I/O server worker #1-2] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table filter : ^.*\..*$
2020-04-12 22:14:51.785 [destination = example , address = mysql/172.100.0.20:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> begin to find start position, it will be long time for reset or first position
2020-04-12 22:14:51.786 [destination = example , address = mysql/172.100.0.20:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - prepare to find start position mysql-bin.000111 # è·åå°ååªæ¹æ°å­:4060:null
2020-04-12 22:14:51.786 [destination = example , address = mysql/172.100.0.20:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> find start position successfully, EntryPosition[included=false,journalName=mysql-bin.000111 # è·åå°ååªæ¹æ°å­,position=4060,serverId=<null>,gtid=,timestamp=<null>] cost : 1ms , the next step is binlog dump
2020-04-12 22:14:51.791 [destination = example , address = mysql/172.100.0.20:3306 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - I/O error while reading from client socket
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102) ~[canal.parse-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:235) [canal.parse-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:265) [canal.parse-1.1.4.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
2020-04-12 22:14:51.792 [destination = example , address = mysql/172.100.0.20:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address mysql/172.100.0.20:3306 has an error, retrying. caused by 
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102) ~[canal.parse-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:235) ~[canal.parse-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:265) ~[canal.parse-1.1.4.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
2020-04-12 22:14:51.793 [destination = example , address = mysql/172.100.0.20:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:235)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:265)
	at java.lang.Thread.run(Thread.java:748)
]
```
通查sql语句
```
show master status;
```
拿到 file position后修改 instance.properties 文件
```
canal.instance.master.journal.name=mysql-bin.000113
canal.instance.master.position=155
```
保存后重启canal server,运行客户端，写入数据库客户端无任何反应，看日志文件又是上面的错误，请问这种情况应该如何解决呢？

**Comment by wedog** [comment]
你的postion配置应该没有生效。源码里是这样的：GTID模式下，CanalLogPositionManager里取最后的gtid，没有则取instanc配置中的。所以必须启用GTID模式你的配置才生效。

**Comment by wedog** [comment]
而且日志也能看的出，EntryPosition[included=false,journalName=mysql-bin.000111 的确起始位置不是你配置的，而是canal实现的自动查找binlog位置。具体可以看看MysqlEventParser的
findStartPositionInternal

**Comment by hnrainll** [comment]
只有在通过logPositionManager 获取不到相关的LogPosition时，才会去配置文件中的数据。你可以查查是不是zk里面还存放在该destination相关的LogPosition，可以删除试试。

不知道还有没有更好的方式？

**Comment by kangning1** [comment]
您好，这个问题有解决吗？我也遇到了同样的问题，配置文件定义了mysql的binlog信息，但是日志中还是去读原来的binlog地址，但是mysql主机上已经清掉了。怎样才能让配置文件的配置生效呢？

**Comment by codedart2018** [comment]
@kangning1 解决了。properties里配置好正确的journal.name 及 position 和帐号密码其它都不用管了。至于 regex 我看服务端会重写它。在这里怎么写都会没用的。

**Comment by lawbar** [comment]
> 多谢解答。我刚查看了zookeeper里的信息，将zookeeper里的记录删除了，canal就自动获取新的binlog地址了。

请问怎么删除zk里面的canal记录呢
