### ISSUE TITLE
Sync with ES using canal adapter

### ISSUE THREAD

**Issue by kishorebambi** [alibaba/canal#2691]
## Question

I'm using Canal adapter with deployer to sync MySQL data to elastic search. I have used join operation to have parent-child relationship to index in elastic search. When inserting record to MySQL same gets inserted to ES. But when I try updating data in my MySQL table it updates the record to table, but not to ES. Rather I get an error as in the log added. So, Can someone here help me what's the cause of the error? Thanks in advance.

> 2020-04-22 16:52:56.752 [pool-3-thread-1] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - ES sync commit errorElasticsearchException[Elasticsearch exception [type=mapper_parsing_exception, reason=failed to parse]]; nested: ElasticsearchException[Elasticsearch exception [type=illegal_argument_exception, reason=[parent] is missing for join field [data_item]]];
java.lang.RuntimeException: ES sync commit errorElasticsearchException[Elasticsearch exception [type=mapper_parsing_exception, reason=failed to parse]]; nested: ElasticsearchException[Elasticsearch exception [type=illegal_argument_exception, reason=[parent] is missing for join field [data_item]]];
	at com.alibaba.otter.canal.client.adapter.es.support.ESTemplate.commit(ESTemplate.java:208)
	at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.commit(ESSyncService.java:852)
	at com.alibaba.otter.canal.client.adapter.es.ESAdapter.sync(ESAdapter.java:178)
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.batchSync(AbstractCanalAdapterWorker.java:201)
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$writeOut$1(AbstractCanalAdapterWorker.java:62)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$writeOut$2(AbstractCanalAdapterWorker.java:58)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-04-22 16:52:56.753 [Thread-4] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - Outer adapter sync failed!  Error sync but ACK!

**Comment by MistRay** [comment]
what version of the elasticsearch you use?

**Comment by kishorebambi** [comment]
I'm using 6.8.8

> {
  "name" : "node-1",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "ekclln3TSK20_KinZbGhjQ",
  "version" : {
    "number" : "6.8.8",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "2f4c224",
    "build_date" : "2020-03-18T23:22:18.622755Z",
    "build_snapshot" : false,
    "lucene_version" : "7.7.2",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}

**Comment by MistRay** [comment]
sorry,I did not encounter the same problem. 
but I guess it's a mapping problem,you can check configure file in es folder.
sql supports free combination of multi-table associations, but there are limitations.
you can search `sql映射说明:` in [wiki](https://github.com/alibaba/canal/wiki/Sync-ES)

**Comment by niejian** [comment]
```java
// 如果是父子文档关系的话给esFieldData添加parent信息
        if (!mapping.getRelations().isEmpty()) {
            mapping.getRelations().forEach((relationField, relationMapping) -> {
                logger.info("relationField: {}", relationField);
                logger.info("relationName: {}", relationMapping.getName());
                // 获取关联的字段信息
                String relationParent = relationMapping.getParent();
                logger.info("relationParent: {}", relationParent);
                if (dmlData.containsKey(relationParent)) {
                    esFieldData.put(relationParent, dmlData.get(relationParent).toString());
                    dmlOld.put(relationParent, dmlData.get(relationParent).toString());
                    return;
                }

            });
        }
```
