### ISSUE TITLE
canal v1.1.4使用RokcetMQ提示No route info for this topic，无法动态创建TOPIC。

### ISSUE THREAD

**Issue by capricornxl** [alibaba/canal#2712]
### 环境
- 系统： Centos7
- Rokcetmq版本：4.5.2
- Canal-Server：1.1.4

通过canal-admin部署好canal server集群之后，在TCP模式下测试能同步生产和消费MYSQL BINLOG中的数据。
随后将canal.serverMode转成RokcetMQ。
【RocketMQ集群通过MQ客户端和命令行测试是可以自动创建TOPIC，并能正常生产和消费，在这里排除掉了RokcetMQ自身的问题。】

修改模式为RocketMQ之后，重启instance，启动adapter。
在日志中出现：ERROR com.alibaba.otter.canal.rocketmq.CanalRocketMQProducer - send flat message to fixed partition error
org.apache.rocketmq.client.exception.MQClientException: No route info for this topic, test_canal_topic
```
2020-04-29 19:14:20.343 [pool-11-thread-4] ERROR com.alibaba.otter.canal.rocketmq.CanalRocketMQProducer - send flat message to fixed partition error
org.apache.rocketmq.client.exception.MQClientException: No route info for this topic, test_canal_topic
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendSelectImpl(DefaultMQProducerImpl.java:1108) ~[rocketmq-client-4.5.2.jar:4.5.2]
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1068) ~[rocketmq-client-4.5.2.jar:4.5.2]
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1063) ~[rocketmq-client-4.5.2.jar:4.5.2]
	at org.apache.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:524) ~[rocketmq-client-4.5.2.jar:4.5.2]
	at com.alibaba.otter.canal.rocketmq.CanalRocketMQProducer.sendMessage(CanalRocketMQProducer.java:195) [canal.server-1.1.4.jar:na]
	at com.alibaba.otter.canal.rocketmq.CanalRocketMQProducer.send(CanalRocketMQProducer.java:179) [canal.server-1.1.4.jar:na]
	at com.alibaba.otter.canal.rocketmq.CanalRocketMQProducer.send(CanalRocketMQProducer.java:84) [canal.server-1.1.4.jar:na]
	at com.alibaba.otter.canal.server.CanalMQStarter.worker(CanalMQStarter.java:183) [canal.server-1.1.4.jar:na]
	at com.alibaba.otter.canal.server.CanalMQStarter.access$500(CanalMQStarter.java:23) [canal.server-1.1.4.jar:na]
	at com.alibaba.otter.canal.server.CanalMQStarter$CanalMQRunnable.run(CanalMQStarter.java:225) [canal.server-1.1.4.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]
```

![image](https://user-images.githubusercontent.com/40738379/80590033-d04c5600-8a4d-11ea-8ac8-eafb91ef5576.png)

### 然后我在RocketMQ中手工创建了test_canal_topic，依旧无效！一直是报这个错。

**Comment by capricornxl** [comment]
## 找到问题了，有个地方有点坑，要注意
这里神坑，多个rocketmq节点要用;号隔开~~
canal.mq.servers=

over了，解决了！！！

**Comment by zhegexiaohuozi** [comment]
文档需要调整下，容易误导
![image](https://user-images.githubusercontent.com/2982325/91153085-558d0200-e6f2-11ea-9c0e-d1c7d22d763e.png)
