### ISSUE TITLE
报错，转换异常

### ISSUE THREAD

**Issue by shang7053** [alibaba/canal#273]
java.lang.ClassCastException: com.alibaba.otter.canal.parse.inbound.AbstractEventParser$4 cannot be cast to com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser$MysqlDetectingTimeTask
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.stopHeartBeat(MysqlEventParser.java:186) ~[canal.parse-1.0.23.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser.stop(AbstractEventParser.java:282) ~[canal.parse-1.0.23.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.stop(MysqlEventParser.java:165) ~[canal.parse-1.0.23.jar:na]
	at com.alibaba.otter.canal.instance.core.AbstractCanalInstance.stop(AbstractCanalInstance.java:104) ~[canal.instance.core-1.0.23.jar:na]
	at com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded.stop(CanalServerWithEmbedded.java:85) ~[canal.server-1.0.23.jar:na]
	at com.alibaba.otter.canal.server.netty.CanalServerWithNetty.stop(CanalServerWithNetty.java:95) [canal.server-1.0.23.jar:na]
	at com.alibaba.otter.canal.deployer.CanalController.stop(CanalController.java:422) [canal.deployer-1.0.23.jar:na]
	at com.alibaba.otter.canal.deployer.CanalLauncher$1.run(CanalLauncher.java:42) [canal.deployer-1.0.23.jar:na]

**Comment by agapple** [comment]
新的master代码已经修复
