### ISSUE TITLE
CanalRabbitMQConsumer  disconnect() 方法报错

### ISSUE THREAD

**Issue by cxntsh** [alibaba/canal#2735]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version 1.1.5-alpha-1
* mysql version 5,7

### Issue Description

CanalRabbitMQConsumer  disconnect() 方法内 channel.close(); 和 connect.close(); 执行先后顺序要互换。不然会导致 启动 或者 关闭服务的时候报错。

### 修复如下：
```
    public void disconnect() {

        if (channel != null) {     // 要先关闭 channel
            try {
                channel.close();
            } catch (IOException | TimeoutException e) {
                throw new CanalClientException("stop channel error", e);
            }
        }

        if (connect != null) {
            try {
                connect.close();
            } catch (IOException e) {
                throw new CanalClientException("stop connect error", e);
            }
        }
    }
```

### Actual behaviour

If there is an exception, please attach the exception trace:

```
2020-05-12 21:29:58.779 [Thread-2] ERROR c.z.a.datastash.launcher.client.loader.AdapterProcessor - process error!
com.rabbitmq.client.AlreadyClosedException: connection is already closed due to clean connection shutdown; protocol method: #method<connection.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
	at com.rabbitmq.client.impl.AMQChannel.processShutdownSignal(AMQChannel.java:401) ~[amqp-client-5.9.0.jar:5.9.0]
	at com.rabbitmq.client.impl.ChannelN.startProcessShutdownSignal(ChannelN.java:287) ~[amqp-client-5.9.0.jar:5.9.0]
	at com.rabbitmq.client.impl.ChannelN.close(ChannelN.java:608) ~[amqp-client-5.9.0.jar:5.9.0]
	at com.rabbitmq.client.impl.ChannelN.close(ChannelN.java:542) ~[amqp-client-5.9.0.jar:5.9.0]
	at com.rabbitmq.client.impl.ChannelN.close(ChannelN.java:535) ~[amqp-client-5.9.0.jar:5.9.0]
	at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.close(AutorecoveringChannel.java:73) ~[amqp-client-5.9.0.jar:5.9.0]
	at com.zmops.argus.datastash.connector.consumer.CanalRabbitMQConsumer.disconnect(CanalRabbitMQConsumer.java:194) ~[argus-datastash-0.0.1-SNAPSHOT.jar:na]
	at com.zmops.argus.datastash.launcher.client.loader.AdapterProcessor.process(AdapterProcessor.java:221) ~[argus-datastash-0.0.1-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_242]
```

**Comment by agapple** [comment]
可以考虑提交一个PR给我
