### ISSUE TITLE
新建一个表同时插入9万行记录进行初始化，canal超时重试导致客户端重复消费

### ISSUE THREAD

**Issue by VincentLiSH** [alibaba/canal#2750]
初始化sql类似下面这样：

> drop table if exists fi_task_etl_init;
create table fi_task_etl_init as select * from fi_task where state not in('invalid','creater_closed','close_co_rejected','close_co_cancelled');

canal日志如下。能否通过设置更长的超时时间 避免Connection reset？
> 2020-05-18 11:29:41.313 [New I/O server worker #1-1] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - subscribe filter change to qcdbv2\..*
2020-05-18 11:29:41.313 [New I/O server worker #1-1] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table filter : ^qcdbv2\..*$
2020-05-18 12:57:50.548 [destination = qcdbv2 , address = /172.19.109.177:3306 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - I/O error while reading from client socket
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210) ~[na:1.8.0_181]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:1.8.0_181]
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[na:1.8.0_181]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286) ~[na:1.8.0_181]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345) ~[na:1.8.0_181]
	at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:109) ~[canal.parse.driver-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:174) ~[canal.parse-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:85) ~[canal.parse-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:235) [canal.parse-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:265) [canal.parse-1.1.4.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]

**Comment by VincentLiSH** [comment]
花了4天时间终于解决了——加大canal缓存设置,
> canal.instance.memory.buffer.size = 1048576
> canal.instance.memory.batch.mode = ITEMSIZE

### 原因分析：

- 由于我在数据库执行了21个建表并插入数据的脚本（create table xxx as select * ），
- 并且其中有2个表数据很多——超过三十万条记录，
- 同时我的canal客户端消费和处理数据的逻辑比较复杂、耗时，因此造成canal中堆积数据等待etl来消费，
- 这里就涉及到canal的ring buffer的机制和原理了（这里不展开，参考https://blog.csdn.net/XiaoHanZuoFengZhou/article/details/103088868）；
- canal的ring buffer默认缓存16m，一旦堆满就会等待消费，等待期间canal应该是（我猜测）不跟mysql通信的；
- 因此当消费的速度很慢导致canal长时间等待，于是canal与mysql之间的connection就被reset了；
- 而且我也没有找到mysql的或canal的哪个设置可以避免reset
- 于是只好尝试加大ring buffer，我当时的想法是加大这个缓存 让初始化脚本导致的binlog数据一次性灌进canal，即便客户端消费的缓慢，但是也不会导致canal装满 等待；
- 如上设置，由于我的初始化数据不到一百万条，于是把buffer.size指定为1048576，我的库里数据单条1k大小，因此总计占用内存1G左右，毫无压力；
- 运行结果也确实如我希望的，一开始cpu飙到90% 内存逐渐增加，应该是canal在忙着解析binlog；
- 几分钟后cpu降下来了，这时就是客户端在消费了，内存占用持续下降；
- 最终顺利完成 没有再出现报错；

**Comment by agapple** [comment]
你这下游消费速度是有多慢？ canal默认设置set net_write_timeout=1800，超过半小时mysql会断开链接

**Comment by agapple** [comment]
MysqlConnection.updateSettings()方法
