### ISSUE TITLE
canal 服务端显示某个配置成功，但client端异常

### ISSUE THREAD

**Issue by rocky-peng** [alibaba/canal#276]
```
2017-03-06 15:19:16.800 [canal-instance-scan-0] INFO  c.a.o.canal.deployer.monitor.SpringInstanceConfigMonitor - auto notify reload local successful.
```
日志显示 local 这个instance成功，但client报异常：

```
com.alibaba.otter.canal.protocol.exception.CanalClientException: something goes wrong with reason: something goes wrong with channel:[id: 0x3f655fa5, /127.0.0.1:65443 => /127.0.0.1:11111], exception=com.alibaba.otter.canal.server.exception.CanalServerException: destination:local should start first

	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.receiveMessages(SimpleCanalConnector.java:302)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.getWithoutAck(SimpleCanalConnector.java:279)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.getWithoutAck(SimpleCanalConnector.java:252)
	at com.alibaba.otter.canal.example.RockyDemo.main(RockyDemo.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by agapple** [comment]
服务端可能发生了重启，client多重试

**Comment by lx5210** [comment]
你解决没？我也遇到这个问题了怎么解决？

**Comment by xiongwj13** [comment]
同问怎么解决的

**Comment by 3CB3EC** [comment]
> 同问怎么解决的

client里面example和server里面instance名字不一致
