### ISSUE TITLE
运行客户端  batchId偶尔出现冲突问题

### ISSUE THREAD

**Issue by youngJavabird** [alibaba/canal#279]
batchId:2176966 is not the firstly:2176965
        at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.receiveMessages(SimpleCanalConnector.java:302)     at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.getWithoutAck(SimpleCanalConnector.java:279)
        at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.getWithoutAck(SimpleCanalConnector.java:252)
        at com.yagou.yggx.provider.datasync.start.AbstractCanalStart.process(AbstractCanalStart.java:115)

下面是代码：
int batchSize = 5 * 1024;
		while (running) {
			try {
				MDC.put("destination", destination);
				connector.connect();
				connector.subscribe();
				while (running) {				
					// 获取指定数量的数据
					Message message = connector.getWithoutAck(batchSize);
					long batchId = message.getId();
					int size = message.getEntries().size();
					List<Entry> entrys = message.getEntries();
					if (batchId == -1 || size == 0) {
						// try {Thread.sleep(1000);
						// } catch (InterruptedException e) { }
					} else {
						DataSourceListenerInformation.comeOutEntry(entrys);
					}
					connector.ack(batchId); // 提交确认

**Comment by hui1hui2hui3** [comment]
同样碰到这个问题，请问你这个最后是怎么解决的

**Comment by youngJavabird** [comment]
一个destination,对应一个消费端。多个消费端同时消费同一个destination，就会报batchId不存在或不是位点
