### ISSUE TITLE
com.alibaba.otter.canal.common.CanalException: instance : example config is not found

### ISSUE THREAD

**Issue by mameng1992** [alibaba/canal#2795]
2020-06-05 16:50:20.042 [main] INFO  com.alibaba.otter.canal.deployer.CanalStarter - ## start the canal server.
2020-06-05 16:50:20.077 [main] INFO  com.alibaba.otter.canal.deployer.CanalController - ## start the canal server[192.168.200.14(192.168.200.14):11111]
2020-06-05 16:50:20.192 [main] ERROR c.a.o.c.common.zookeeper.running.ServerRunningMonitor - start failed
com.google.common.collect.ComputationException: com.alibaba.otter.canal.common.CanalException: com.alibaba.otter.canal.common.CanalException: instance : example config is not found
        at com.google.common.collect.MapMaker$ComputingMapAdapter.get(MapMaker.java:889) ~[guava-18.0.jar:na]
        at com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded.start(CanalServerWithEmbedded.java:137) ~[canal.server-1.1.4.jar:na]
        at com.alibaba.otter.canal.deployer.CanalController$2$1.processActiveEnter(CanalController.java:160) ~[canal.deployer-1.1.4.jar:na]
        at com.alibaba.otter.canal.common.zookeeper.running.ServerRunningMonitor.processActiveEnter(ServerRunningMonitor.java:247) ~[canal.common-1.1.4.jar:na]
        at com.alibaba.otter.canal.common.zookeeper.running.ServerRunningMonitor.start(ServerRunningMonitor.java:104) ~[canal.common-1.1.4.jar:na]
        at com.alibaba.otter.canal.deployer.CanalController.start(CanalController.java:513) [canal.deployer-1.1.4.jar:na]
        at com.alibaba.otter.canal.deployer.CanalStarter.start(CanalStarter.java:78) [canal.deployer-1.1.4.jar:na]
        at com.alibaba.otter.canal.deployer.CanalLauncher.main(CanalLauncher.java:115) [canal.deployer-1.1.4.jar:na]
Caused by: com.alibaba.otter.canal.common.CanalException: com.alibaba.otter.canal.common.CanalException: instance : example config is not found
Caused by: com.alibaba.otter.canal.common.CanalException: instance : example config is not found
2020-06-05 16:50:20.269 [main] INFO  com.alibaba.otter.canal.deployer.CanalStarter - ## the canal server is running now ......

**Comment by jonn-yan** [comment]
解决了吗，我也遇到这个问题，canal.deployer-1.1.4

**Comment by agapple** [comment]
example config is not found，配置问题

**Comment by 1261762904** [comment]
canal.properties有配置canal-admin吧，如果配置了需要手动在admin里配置instance，他不会自动读取conf/example的instance
<img width="1571" alt="image" src="https://github.com/user-attachments/assets/60a72c66-6bc4-4889-ba86-357afedcb6e5">
