### ISSUE TITLE
使用1.1.5版本写入es时，group里面配置name: es报错

### ISSUE THREAD

**Issue by Gongruixiao** [alibaba/canal#2796]
使用canal.adapter-1.1.5-SNAPSHOT.tar.gz 配置如下，报错。但是同样的配置在1.1.4没有问题
```
  canalAdapters:
  - instance: comment # canal instance Name or mq topic name
    groups:
    - groupId: comment_es
      outerAdapters:
      - name: logger
      - name: es
        hosts: ip:9200 # 127.0.0.1:9200 for rest mode
        properties:
          mode: rest # or rest
          # security.auth: test:123456 #  only used for rest mode
          cluster.name: test
```
```
2020-06-05 18:00:11.845 [main] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterLoader - Load canal adapter: es failed
java.lang.IllegalStateException: Extension instance(name: es, class: interface com.alibaba.otter.canal.client.adapter.OuterAdapter)  could not be instantiated: class could not be found
        at com.alibaba.otter.canal.client.adapter.support.ExtensionLoader.createExtension(ExtensionLoader.java:186) ~[client-adapter.common-1.1.5-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.client.adapter.support.ExtensionLoader.getExtension(ExtensionLoader.java:142) ~[client-adapter.common-1.1.5-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.adapter.launcher.loader.CanalAdapterLoader.loadAdapter(CanalAdapterLoader.java:175) [client-adapter.launcher-1.1.5-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.adapter.launcher.loader.CanalAdapterLoader.init(CanalAdapterLoader.java:72) [client-adapter.launcher-1.1.5-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.adapter.launcher.loader.CanalAdapterService.init(CanalAdapterService.java:60) [client-adapter.launcher-1.1.5-SNAPSHOT.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_252]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_252]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_252]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_252]
```

**Comment by xuzhipeng1028** [comment]
es6或者es7,对应es的版本是6.x或7.x,https://github.com/alibaba/canal/wiki/Sync-ES

**Comment by Gongruixiao** [comment]
是我疏忽了  非常感谢您的帮助

**Comment by yangmingqi218** [comment]
@Gongruixiao  您好，请问您是怎么解决的？我本地启动的es是6.3.2版本，我填写es6还是报您的那个错误
![image](https://user-images.githubusercontent.com/38835550/90723988-4ff97b80-e2f0-11ea-8b58-f744f347343f.png)
![image](https://user-images.githubusercontent.com/38835550/90724034-6c95b380-e2f0-11ea-96eb-1fbc6b5864be.png)

**Comment by yangmingqi218** [comment]
@xuzhipeng1028 您好，您知道这个问题怎么解决么？

**Comment by jiejie2018** [comment]
一样的问题啊，哪位大佬解答一下括弧笑
