### ISSUE TITLE
大家都是怎么做etl的初始化的？

### ISSUE THREAD

**Issue by VincentLiSH** [alibaba/canal#2807]
## Question

我用canal对业务系统的mysql做增量订阅实现etl，
但是在系统部署之后 需要首先对存量数据做一个完整的同步，
我的做法是用“create table xxx_init as select * from xxx” 来实现初始化。
但是现在遇到一个麻烦的问题——遇到比较大的表（30万记录）时，canal会经常出现以下错误信息：
`2020-06-08 15:39:24.584 [New I/O server worker #1-1] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - subscribe filter change to qcdbv2\..*
2020-06-08 15:39:24.584 [New I/O server worker #1-1] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table filter : ^qcdbv2\..*$
2020-06-08 16:53:42.632 [destination = qcdbv2 , address = /172.19.109.177:3306 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - I/O error while reading from client socket
java.io.IOException: EOF encountered.
	at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:113) ~[canal.parse.driver-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:174) ~[canal.parse-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:85) ~[canal.parse-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:169) [canal.parse-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:279) [canal.parse-1.1.4.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
2020-06-08 16:53:42.633 [destination = qcdbv2 , address = /172.19.109.177:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address 172.19.109.177/172.19.109.177:3306 has an error, retrying. caused by 
java.io.IOException: EOF encountered.
	at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:113) ~[canal.parse.driver-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:174) ~[canal.parse-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:85) ~[canal.parse-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:169) ~[canal.parse-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:279) ~[canal.parse-1.1.4.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
2020-06-08 16:53:42.638 [destination = qcdbv2 , address = /172.19.109.177:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:qcdbv2[java.io.IOException: EOF encountered.
	at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:113)
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:174)
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:85)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:169)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:279)
	at java.lang.Thread.run(Thread.java:748)
]`

**Comment by VincentLiSH** [comment]
上述日志表明：
15:39:24 canal客户端启动 开始订阅qcdbv2\..*
然后我在数据库执行一批“create table xxx_init as select * from xxx” 初始化脚本
16:53:42 canal报错 I/O error while reading from client socket java.io.IOException: EOF encountered.
此时canal客户端还是正常的，因为还没消费到

**Comment by foolgry** [comment]
如果是单表的话，直接用etl就可以了啊

**Comment by KylinShinlyLin** [comment]
我们公司的表都有update_time ，使用 DATE_ADD(update_time, INTERVAL 1 SECOND)，然后使用脚本根据当前表的数据量生成一堆SQL（避免UPDATE执行的时候锁表），但是在这张方式下同步的时候需要时刻注意Mysql的磁盘空间

**Comment by VincentLiSH** [comment]
应该是mysql超时断开了canal的dump连接，set global net_write_timeout=28800
