### ISSUE TITLE
canal HA模式下监控RDS的数据库，为什么没有conf/example/meta.dat文件，而且启动服务时一直报这个错误，求救如何配置canal.instance.master.journal.name= canal.instance.master.position= canal.instance.master.timestamp=0  非常急！

### ISSUE THREAD

**Issue by 13301891422** [alibaba/canal#2808]
2020-06-09 10:03:38.091 [destination = example , address = XXX:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ERROR ## findAsPerTimestampInSpecificLogFile has an error
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102) ~[canal.parse-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.seek(MysqlConnection.java:144) ~[canal.parse-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findAsPerTimestampInSpecificLogFile(MysqlEventParser.java:746) [canal.parse-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findByStartTimeStamp(MysqlEventParser.java:584) [canal.parse-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPositionInternal(MysqlEventParser.java:521) [canal.parse-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPosition(MysqlEventParser.java:369) [canal.parse-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:194) [canal.parse-1.1.4.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]
2020-06-09 10:03:38.091 [destination = example , address = XXX:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - Didn't find the corresponding binlog files from mysql-bin.0003 to mysql-bin.0009
2020-06-09 10:03:38.091 [destination = example , address = XXX:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address XXX:3306 has an error, retrying. caused by 
com.alibaba.otter.canal.parse.exception.PositionNotFoundException: can't find start position for example
2020-06-09 10:03:38.091 [destination = example , address = XXX：3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[com.alibaba.otter.canal.parse.exception.PositionNotFoundException: can't find start position for example

**Comment by 13301891422** [comment]
在Instance.properties已经配置了# position info
canal.instance.master.address=XXXX:3306
canal.instance.master.journal.name=mysql-bin.000809
canal.instance.master.position=489534
canal.instance.master.timestamp=0
canal.instance.master.gtid=
但是仍然报上面的错误 不知道是不是没有生效

**Comment by agapple** [comment]
Didn't find the corresponding binlog files from mysql-bin.0003 to mysql-bin.0009

找不到符合条件的位点
