### ISSUE TITLE
指定binlog文件和偏移，find start position successfully,可是为什么下一步 binlog dump就报 I/O error while reading from client socket错误呢

### ISSUE THREAD

**Issue by 13301891422** [alibaba/canal#2810]
2020-06-09 11:21:32.724 [main] INFO  c.a.otter.canal.instance.spring.CanalInstanceWithSpring - start CannalInstance for 1-example 
2020-06-09 11:21:32.731 [main] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table filter : ^tms$
2020-06-09 11:21:32.731 [main] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table black filter : 
2020-06-09 11:21:32.760 [main] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - start successful....
2020-06-09 11:21:32.790 [destination = example , address = xxxx:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> begin to find start position, it will be long time for reset or first position
2020-06-09 11:21:32.802 [destination = example , address = xxxx:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - prepare to find start position just last position
 {"identity":{"slaveId":104,"sourceAddress":{"address":"rm-bp1j1e16rl110616hrw.mysql.rds.aliyuncs.com","port":3306}},"postion":{"included":false,"journalName":"mysql-bin.000810","position":3687508,"timestamp":1591669491}}
2020-06-09 11:21:32.820 [destination = example , address = xxxx:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> find start position successfully, EntryPosition[included=false,journalName=mysql-bin.000810,position=3687508,serverId=<null>,gtid=<null>,timestamp=1591669491] cost : 13ms , the next step is binlog dump
2020-06-09 11:21:32.870 [destination = example , address = xxxx:3306 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - I/O error while reading from client socket
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102) ~[canal.parse-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:235) [canal.parse-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:265) [canal.parse-1.1.4.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]
2020-06-09 11:21:32.870 [destination = example , address = xxxx:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address xxxx:3306 has an error, retrying. caused by 
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102) ~[canal.parse-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:235) ~[canal.parse-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:265) ~[canal.parse-1.1.4.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]
2020-06-09 11:21:32.873 [destination = example , address = xxxx:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:235)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:265)
	at java.lang.Thread.run(Thread.java:748)

**Comment by huanxu767** [comment]
我也遇到这个问题了

> ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:235)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:265)
	at java.lang.Thread.run(Thread.java:748)

**Comment by ruyin-zh** [comment]
Indicates an error, for example trying to fetch from wrong binlog position.  可以检查下数据库的字符集设置是否有问题

**Comment by agapple** [comment]
Could not find first log file name in binary log index file  ， binlog文件已经被删除，重置下位点

**Comment by xuanYangZi** [comment]
请问楼主有解决吗? 怎么解决的呢 ?

**Comment by 13301891422** [comment]
> 请问楼主有解决吗? 怎么解决的呢 ?

兄得 刚解决 删除zk里面跟canal偏移量相关的位置信息 canal就能自动找到最新的偏移量了

**Comment by xuanYangZi** [comment]
> > 请问楼主有解决吗？怎么解决的呢？
> 
> 兄得刚解决方案删除zk里面跟运河改变量相关的位置信息canal可以自动找到最新的替换量了

我的并没有配置zookeeper,我的问题删除example目录下的meta.dat 也可找到最新的, 但是新生成文件meta.dat不更新, 造成的IOException

**Comment by misstt123** [comment]
> > > 请问楼主有解决吗？怎么解决的呢？
> > 
> > 
> > 兄得刚解决方案删除zk里面跟运河改变量相关的位置信息canal可以自动找到最新的替换量了
> 
> 我的并没有配置zookeeper,我的问题删除example目录下的meta.dat 也可找到最新的, 但是新生成文件meta.dat不更新, 造成的IOException

请问楼主解决了吗？？？

**Comment by jinfeng202111** [comment]
我是直接删除zookeeper里的/otter/canal/destinations/xxx/1001/cursor，重启后就没有问题，但是刚才出现错误的数据就没有再重新发送过来了。

**Comment by 13301891422** [comment]
已经收到，谢谢!
