### ISSUE TITLE
请问阿里大牛，deploy怎么打整包，把所有依赖打包到项目中？

### ISSUE THREAD

**Issue by laosan-it** [alibaba/canal#2823]

**Comment by laosan-it** [comment]
已经找到方法了
<plugin>  
	<artifactId>maven-assembly-plugin</artifactId>  
	<configuration>  
		<descriptorRefs>  
			<descriptorRef>jar-with-dependencies</descriptorRef>  
		</descriptorRefs>  
		<archive>  
			<manifest>  
				<mainClass>com.alibaba.otter.canal.deployer.CanalLauncher</mainClass>  
			</manifest>  
		</archive>  
	</configuration>  
	<executions>  
		<execution>  
			<id>make-assembly</id>  
			<phase>package</phase>  
			<goals>  
				<goal>single</goal>  
			</goals>  
		</execution>  
	</executions>  
</plugin>

**Comment by jurimengs** [comment]
能交流下吗， 我跑源码正常。但是打包后放在 centos 7.2 ， sh start.sh 启动报：
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: java.net.SocketException: Socket closed
Caused by: java.net.SocketException: Socket closed
        at java.net.SocketInputStream.read(SocketInputStream.java:204) ~[na:1.8.0_191]
        at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:1.8.0_191]
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[na:1.8.0_191]
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286) ~[na:1.8.0_191]
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345) ~[na:1.8.0_191]
        at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:52) ~[canal.parse.driver-1.1.4.jar:na]
        at com.alibaba.otter.canal.parse.driver.mysql.utils.PacketManager.readHeader(PacketManager.java:13) ~[canal.parse.driver-1.1.4.jar:na]
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlQueryExecutor.readNextPacket(MysqlQueryExecutor.java:159) ~[canal.parse.driver-1.1.4.jar:na]
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlQueryExecutor.query(MysqlQueryExecutor.java:56) ~[canal.parse.driver-1.1.4.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.query(MysqlConnection.java:106) ~[canal.parse-1.1.4.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.loadBinlogImage(MysqlConnection.java:492) ~[canal.parse-1.1.4.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.getBinlogImage(MysqlConnection.java:654) ~[canal.parse-1.1.4.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.preDump(MysqlEventParser.java:108) ~[canal.parse-1.1.4.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:196) ~[canal.parse-1.1.4.jar:na]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_191]
2020-11-05 18:31:47.067 [main] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - stop successful....

**Comment by jurimengs** [comment]
谢谢
