### ISSUE TITLE
k8s部署的cannal不定时出现无法连接kafka和rabbitmq

### ISSUE THREAD

**Issue by busyboy-ws** [alibaba/canal#2870]
## Question

在k8s上运行cannal时我们不定时的遇到cannal无法连接kafka,mq的问题，经历看mq重启一定会出现这种问题.
以kafka为列,报错如下：
```
2020-07-08 10:56:44.351 [pool-4-thread-1] ERROR com.alibaba.otter.canal.kafka.CanalKafkaProducer - java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.
java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.
	at com.alibaba.otter.canal.kafka.CanalKafkaProducer.send(CanalKafkaProducer.java:150) ~[canal.server-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.server.CanalMQStarter.worker(CanalMQStarter.java:183) [canal.server-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.server.CanalMQStarter.access$500(CanalMQStarter.java:23) [canal.server-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.server.CanalMQStarter$CanalMQRunnable.run(CanalMQStarter.java:225) [canal.server-1.1.5-SNAPSHOT.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.
	at org.apache.kafka.clients.producer.KafkaProducer$FutureFailure.<init>(KafkaProducer.java:1150) ~[kafka-clients-1.1.1.jar:na]
	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:846) ~[kafka-clients-1.1.1.jar:na]
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:784) ~[kafka-clients-1.1.1.jar:na]
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:671) ~[kafka-clients-1.1.1.jar:na]
	at com.alibaba.otter.canal.kafka.CanalKafkaProducer.produce(CanalKafkaProducer.java:234) ~[canal.server-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.kafka.CanalKafkaProducer.send(CanalKafkaProducer.java:227) ~[canal.server-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.kafka.CanalKafkaProducer.access$000(CanalKafkaProducer.java:38) ~[canal.server-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.kafka.CanalKafkaProducer$1.call(CanalKafkaProducer.java:124) ~[canal.server-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.kafka.CanalKafkaProducer$1.call(CanalKafkaProducer.java:119) ~[canal.server-1.1.5-SNAPSHOT.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_181]
	... 3 common frames omitted
Caused by: org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.

```
出现这种问题时，我们登陆对应pod 查看kafka的端口是通的. 
```
[root@canal-server-kafka-8548fb77bd-vbpp4 test]# telnet kafka-test 9092
Trying 172.19.10.18...
Connected to kafka-test.
Escape character is '^]'.
^CConnection closed by foreign host.
```

**Comment by agapple** [comment]
咨询下MQ社区？

**Comment by privatesql** [comment]
楼主 这个问题解决了吗
