### ISSUE TITLE
与guava 20有兼容问题，guava 18 MapMaker.makeComputingMap方法已过时

### ISSUE THREAD

**Issue by Luckywb** [alibaba/canal#288]
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.collect.MapMaker.makeComputingMap(Lcom/google/common/base/Function;)Ljava/util/concurrent/ConcurrentMap;
	at com.google.common.collect.MigrateMap.makeComputingMap(MigrateMap.java:17)
	at com.alibaba.otter.canal.common.zookeeper.ZkClientx.<clinit>(ZkClientx.java:26)
	at com.alibaba.otter.canal.client.CanalConnectors.newClusterConnector(CanalConnectors.java:66)

**Comment by agapple** [comment]
考虑提交一个PR给我把，guava 20目前内部还没人用上

**Comment by Luckywb** [comment]
自己实现了CanalNodeAccessStrategy解决了

**Comment by klaus-pd** [comment]
@Luckywb 怎么实现的？

**Comment by hektor8603** [comment]
> 自己实现了CanalNodeAccessStrategy解决了

怎么实现的 我也遇到这个问题了
