### ISSUE TITLE
canal1.1.5  es7.7.0 debug提示的错误，请问是什么原因

### ISSUE THREAD

**Issue by liuchenbaidu** [alibaba/canal#2882]
## Question

2020-07-20 11:25:33.719 [Thread-3] ERROR c.a.o.c.client.adapter.es.core.monitor.ESConfigMonitor - esMapping._type
java.lang.NullPointerException: esMapping._type
        at com.alibaba.otter.canal.client.adapter.es.core.config.ESSyncConfig.validate(ESSyncConfig.java:35) ~[client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
        at com.alibaba.otter.canal.client.adapter.es.core.monitor.ESConfigMonitor$FileListener.onFileCreate(ESConfigMonitor.java:76) ~[client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
        at org.apache.commons.io.monitor.FileAlterationObserver.doCreate(FileAlterationObserver.java:379) [commons-io-2.4.jar:2.4]
        at org.apache.commons.io.monitor.FileAlterationObserver.checkAndNotify(FileAlterationObserver.java:330) [commons-io-2.4.jar:2.4]
        at org.apache.commons.io.monitor.FileAlterationObserver.checkAndNotify(FileAlterationObserver.java:304) [commons-io-2.4.jar:2.4]
        at org.apache.commons.io.monitor.FileAlterationMonitor.run(FileAlterationMonitor.java:182) [commons-io-2.4.jar:2.4]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]
2020-07-20 11:25:33.719 [Thread-3] DEBUG c.a.o.c.c.a.c.common.YamlPropertySourceLoader$Processor - Loading from YAML: Byte array resource [resource loaded from byte array]
2020-07-20 11:25:33.721 [Thread-3] DEBUG c.a.o.c.c.adapter.config.common.MutablePropertySources - Adding PropertySource 'profiles' with highest search precedence
2020-07-20 11:25:33.721 [Thread-3] DEBUG c.a.o.c.c.a.c.common.YamlPropertySourceLoader$Processor - Matched document with default matcher: {dataSourceKey=defaultDS, destination=example, groupId=g1, esMapping={_index=customer, _id=id, relations={customer_order={name=customer}}, sql=select t.id, t.name, t.email from customer t, etlCondition=where t.c_time>={}, commitBatch=3000}}
2020-07-20 11:25:33.721 [Thread-3] DEBUG c.a.o.c.c.a.c.common.YamlPropertySourceLoader$Processor - Loaded 1 document from YAML resource: Byte array resource [resource loaded from byte array]
2020-07-20 11:25:33.721 [Thread-3] DEBUG c.a.o.c.c.adapter.config.common.MutablePropertySources - Adding PropertySource 'manualBindConfig' with highest search precedence
2020-07-20 11:25:33.721 [Thread-3] DEBUG c.a.o.c.c.a.config.bind.PropertySourcesPropertyResolver - Found key 'dataSourceKey' in PropertySource 'manualBindConfig' with value of type String
2020-07-20 11:25:33.721 [Thread-3] DEBUG c.a.o.c.c.a.config.bind.PropertySourcesPropertyResolver - Found key 'destination' in PropertySource 'manualBindConfig' with value of type String
2020-07-20 11:25:33.722 [Thread-3] DEBUG c.a.o.c.c.a.config.bind.PropertySourcesPropertyResolver - Found key 'groupId' in PropertySource 'manualBindConfig' with value of type String
2020-07-20 11:25:33.722 [Thread-3] DEBUG c.a.o.c.c.a.config.bind.PropertySourcesPropertyResolver - Found key 'esMapping._index' in PropertySource 'manualBindConfig' with value of type String
2020-07-20 11:25:33.722 [Thread-3] DEBUG c.a.o.c.c.a.config.bind.PropertySourcesPropertyResolver - Found key 'esMapping._id' in PropertySource 'manualBindConfig' with value of type String
2020-07-20 11:25:33.722 [Thread-3] DEBUG c.a.o.c.c.a.config.bind.PropertySourcesPropertyResolver - Found key 'esMapping.relations.customer_order.name' in PropertySource 'manualBindConfig' with value of type String
2020-07-20 11:25:33.722 [Thread-3] DEBUG c.a.o.c.c.a.config.bind.PropertySourcesPropertyResolver - Found key 'esMapping.sql' in PropertySource 'manualBindConfig' with value of type String
2020-07-20 11:25:33.722 [Thread-3] DEBUG c.a.o.c.c.a.config.bind.PropertySourcesPropertyResolver - Found key 'esMapping.etlCondition' in PropertySource 'manualBindConfig' with value of type String
2020-07-20 11:25:33.722 [Thread-3] DEBUG c.a.o.c.c.a.config.bind.PropertySourcesPropertyResolver - Found key 'esMapping.commitBatch' in PropertySource 'manualBindConfig' with value of type Integer

**Comment by EstellaHuang** [comment]
_type 这个配置项没配值吧

**Comment by gangade** [comment]
一般是修改了es7下的yml文件，每次我都需要重启一下canal.adapter

**Comment by mugbya** [comment]
> 一般是修改了es7下的yml文件，每次我都需要重启一下canal.adapter

good

**Comment by wubaohua** [comment]
请问,怎么解决的?我这重启也不管用啊
