### ISSUE TITLE
数据库绑定域名， canal 通过域名启动MySQL, 如果 域名更换ip 了， 我这边是否可以不重启操作！

### ISSUE THREAD

**Issue by Xuzan9396** [alibaba/canal#2884]
#### 现在运维更换mysql ip 我这边就报错
```
ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - I/O error while reading from client socket
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Client requested master to start replication from position > file size
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102) ~[canal.parse-1.1.4-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:235) [canal.parse-1.1.4-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:265) [canal.parse-1.1.4-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
```
请问大家怎么解决的

**Comment by agapple** [comment]
Client requested master to start replication from position > file size

更换域名之后新主机位点和之前不一致，确保一下新旧mysql之间的server_id不同，1.1.5版本是有对域名情况做了兼容处理
