### ISSUE TITLE
1.1.5同步不了，发现有几个人都一样的问题，能检查到binlog，但是没有etlservice同步，这基本的功能都这样，麻烦作者解决一下吧

### ISSUE THREAD

**Issue by liuchenbaidu** [alibaba/canal#2886]
## Question

1.1.5版本同步不了，发现有几个人都一样的问题，能检查到binlog，但是没有etlservice同步，这基本的功能都这样，麻烦作者解决一下吧
2020-07-20 17:08:57.155 [pool-5-thread-1] INFO  c.a.o.canal.client.adapter.logger.LoggerAdapterExample - DML: {"data":[{"id":2137,"org_id":1,"product_id":null,"username":"chen.liu@welab-inc.com","support_username":null,"action":"DELETE","module":"INTENT","source_id":"57","path":"/intents/57/content/245","remark":"删除意图示例，意图：活动，id：245","ip":"10.0.0.252","create_time":1595236137000}],"database":"call_bot","destination":"example","es":1595236136000,"groupId":null,"isDdl":false,"old":null,"pkNames":["id"],"sql":"","table":"audit_log","ts":1595236137153,"type":"INSERT"}

**Comment by sunyaer66** [comment]
同样的问题

**Comment by xianxin27** [comment]
canal-adapter-1.1.5同步ES启动时连接instance报错，提示授权失败，不知道怎么配置授权
2020-08-14 18:12:26.222 [Thread-4] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - process error!
com.alibaba.otter.canal.protocol.exception.CanalClientException: something goes wrong when doing authentication: auth failed for user:
        at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:192) ~[canal.client-1.1.5-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.connect(SimpleCanalConnector.java:115) ~[canal.client-1.1.5-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.adapter.launcher.loader.CanalAdapterWorker.process(CanalAdapterWorker.java:88) ~[client-adapter.launcher-1.1.5-SNAPSHOT.jar:na]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_161]

**Comment by xianxin27** [comment]
> ## Question
> 1.1.5版本同步不了，发现有几个人都一样的问题，能检查到binlog，但是没有etlservice同步，这基本的功能都这样，麻烦作者解决一下吧
> 2020-07-20 17:08:57.155 [pool-5-thread-1] INFO c.a.o.canal.client.adapter.logger.LoggerAdapterExample - DML: {"data":[{"id":2137,"org_id":1,"product_id":null,"username":"[chen.liu@welab-inc.com](mailto:chen.liu@welab-inc.com)","support_username":null,"action":"DELETE","module":"INTENT","source_id":"57","path":"/intents/57/content/245","remark":"删除意图示例，意图：活动，id：245","ip":"10.0.0.252","create_time":1595236137000}],"database":"call_bot","destination":"example","es":1595236136000,"groupId":null,"isDdl":false,"old":null,"pkNames":["id"],"sql":"","table":"audit_log","ts":1595236137153,"type":"INSERT"}

canal-adapter同步ES怎么配置授权

**Comment by DearZh** [comment]
> ## Question
> 1.1.5版本同步不了，发现有几个人都一样的问题，能检查到binlog，但是没有etlservice同步，这基本的功能都这样，麻烦作者解决一下吧
> 2020-07-20 17:08:57.155 [pool-5-thread-1] INFO c.a.o.canal.client.adapter.logger.LoggerAdapterExample - DML: {"data":[{"id":2137,"org_id":1,"product_id":null,"username":"[chen.liu@welab-inc.com](mailto:chen.liu@welab-inc.com)","support_username":null,"action":"DELETE","module":"INTENT","source_id":"57","path":"/intents/57/content/245","remark":"删除意图示例，意图：活动，id：245","ip":"10.0.0.252","create_time":1595236137000}],"database":"call_bot","destination":"example","es":1595236136000,"groupId":null,"isDdl":false,"old":null,"pkNames":["id"],"sql":"","table":"audit_log","ts":1595236137153,"type":"INSERT"}

朋友，你这个根本不是ETL的同步功能，你这个配置adapter适配器的时候，是只配置了logger吧，看你的日志是只有输出LoggerAdapterExample 的日志信息，所以，建议再看下canal的文档吧，是你的使用方式有点问题

**Comment by DearZh** [comment]
> > ## Question
> > 1.1.5版本同步不了，发现有几个人都一样的问题，能检查到binlog，但是没有etlservice同步，这基本的功能都这样，麻烦作者解决一下吧
> > 2020-07-20 17:08:57.155 [pool-5-thread-1] INFO c.a.o.canal.client.adapter.logger.LoggerAdapterExample - DML: {"data":[{"id":2137,"org_id":1,"product_id":null,"username":"[chen.liu@welab-inc.com](mailto:chen.liu@welab-inc.com)","support_username":null,"action":"DELETE","module":"INTENT","source_id":"57","path":"/intents/57/content/245","remark":"删除意图示例，意图：活动，id：245","ip":"10.0.0.252","create_time":1595236137000}],"database":"call_bot","destination":"example","es":1595236136000,"groupId":null,"isDdl":false,"old":null,"pkNames":["id"],"sql":"","table":"audit_log","ts":1595236137153,"type":"INSERT"}
> 
> canal-adapter同步ES怎么配置授权，麻烦告知下，谢谢

配置授权具体是什么意思？这个问题或许可能是你的ES服务端配置了授权相关的东西导致的，不过canal-client-adapter在创建
ESConnection的时候的确会有进行授权相关的操作，代码如下所示：

```
if (mode == ESClientMode.TRANSPORT) {
            Settings.Builder settingBuilder = Settings.builder();
            settingBuilder.put("cluster.name", properties.get("cluster.name"));
            Settings settings = settingBuilder.build();
            transportClient = new PreBuiltTransportClient(settings);
            for (String host : hosts) {
                int i = host.indexOf(":");
                transportClient.addTransportAddress(new TransportAddress(InetAddress.getByName(host.substring(0, i)),
                        Integer.parseInt(host.substring(i + 1))));
            }
        } else {
            HttpHost[] httpHosts = new HttpHost[hosts.length];
            for (int i = 0; i < hosts.length; i++) {
                String host = hosts[i];
                int j = host.indexOf(":");
                HttpHost httpHost = new HttpHost(InetAddress.getByName(host.substring(0, j)),
                        Integer.parseInt(host.substring(j + 1)));
                httpHosts[i] = httpHost;
            }
            RestClientBuilder restClientBuilder = RestClient.builder(httpHosts);
            String nameAndPwd = properties.get("security.auth");
            if (StringUtils.isNotEmpty(nameAndPwd) && nameAndPwd.contains(":")) {
                String[] nameAndPwdArr = nameAndPwd.split(":");
                final CredentialsProvider credentialsProvider = new BasicCredentialsProvider();
                credentialsProvider.setCredentials(AuthScope.ANY, new UsernamePasswordCredentials(nameAndPwdArr[0],
                        nameAndPwdArr[1]));
                restClientBuilder.setHttpClientConfigCallback(httpClientBuilder -> httpClientBuilder.setDefaultCredentialsProvider(credentialsProvider));
            }
            restHighLevelClient = new RestHighLevelClient(restClientBuilder);
        }
```
分别是区分了REST和TRANSPORT的两种创建方式，
所以，你可以自己尝试写一个ES Client的客户端，尝试一下，如果的确需要授权，那么你可以在application.yml中配置canalAdapters时，指定下相关的授权相关的配置，

**Comment by Reyoo** [comment]
这个问题前辈们怎么解决的。遇到了同样的问题

**Comment by ZhangShunXinGitHub** [comment]
我也是1.1.5 es7 同步不了。哎

**Comment by chengchaoyin** [comment]
同问，最终解决了吗？
