### ISSUE TITLE
adapter 1.1.5版本启动空指针，有大佬遇到过吗

### ISSUE THREAD

**Issue by jiuqinyan** [alibaba/canal#2905]
## Question

```
2020-07-28 18:41:28.142 [main] INFO  c.a.o.c.client.adapter.es.core.config.ESSyncConfigLoader - ## Start loading es mapping config ... 
2020-07-28 18:41:28.208 [main] INFO  c.a.o.c.client.adapter.es.core.config.ESSyncConfigLoader - ## ES mapping config loaded
2020-07-28 18:41:28.532 [main] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterLoader - Load canal adapter: es7 failed
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
        at com.alibaba.otter.canal.client.adapter.es7x.ES7xAdapter.init(ES7xAdapter.java:54) ~[client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
        at com.alibaba.otter.canal.adapter.launcher.loader.CanalAdapterLoader.loadAdapter(CanalAdapterLoader.java:196) [client-adapter.launcher-1.1.5-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.adapter.launcher.loader.CanalAdapterLoader.init(CanalAdapterLoader.java:72) [client-adapter.launcher-1.1.5-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.adapter.launcher.loader.CanalAdapterService.init(CanalAdapterService.java:60) [client-adapter.launcher-1.1.5-SNAPSHOT.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_252]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_252]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_252]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_252]
```

```
application.yml
      - name: es7
        hosts: 127.0.0.1:9200 # 127.0.0.1:9200 for rest mode
        properties:
          mode: rest 
#          # security.auth: test:123456 #  only used for rest mode
          cluster.name: elasticsearch
```

user.yml
```
SourceKey: defaultDS
destination: example
groupId: g1
esMapping:
  _index: user
  _type: _doc
  _id: _id
  upsert: true
  sql: "select u.id as _id,u.name,u.conf_id from user u"
  commitBatch: 1000
```

mappings
```
"mappings": {
  
      "properties": {
        "name": {
         "type": "text",
          "analyzer": "ik_smart"
        },
         "conf_id": {
          "type": "long"
        }
      }
  }
```

**Comment by EstellaHuang** [comment]
你这个是启动的本地的源码包的应用吗？还是就是用shell脚本启动的解压的包。我启动用源码里面的launcher的时候遇到过，程序启动时没有读到es下的配置文件，在根目录下build一下就好了。

**Comment by jiuqinyan** [comment]
> 你这个是启动的本地的二进制包的应用吗？还是就是用shell脚本启动的解压的包。我启动用源码里面的launcher的时候遇到过，程序启动时没有读到es下的配置文件，在根目录下build一下就好了。

下载的压缩包
