### ISSUE TITLE
两个客户端同时运行并订阅了同一个canal服务端，客户端就无法消费且报错，并且binlog日志会丢失

### ISSUE THREAD

**Issue by MoRongQin** [alibaba/canal#2926]
`com.alibaba.otter.canal.protocol.exception.CanalClientException: deserializer failed
at com.alibaba.otter.canal.client.CanalMessageDeserializer.deserializer(CanalMessageDeserializer.java:54)
at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.receiveMessages(SimpleCanalConnector.java:322)
at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.getWithoutAck(SimpleCanalConnector.java:314)
at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.getWithoutAck(SimpleCanalConnector.java:286)
at com.alibaba.otter.CanalClient.main(CanalClient.java:135)`

**Comment by agapple** [comment]
为了保序，只能单客户端消费
