### ISSUE TITLE
adapter 同步到目标库 报错Target column: id not matched

### ISSUE THREAD

**Issue by lklkxcxc** [alibaba/canal#2941]
## Question

源数据库mysq 5.7
目的数据库mariadb 版本：10.3.17-MariaDB-0+deb10u1 Debian 10

同步报错表结构：
```
+------------+-------------+------+-----+---------+----------------+
| Field      | Type        | Null | Key | Default | Extra          |
+------------+-------------+------+-----+---------+----------------+
| id         | int(10)     | NO   | PRI | NULL    | auto_increment |
| right_code | varchar(10) | NO   |     | NULL    |                |
| address_ip | varchar(20) | NO   |     | NULL    |                |
| date       | datetime    | YES  |     | NULL    |                |
+------------+-------------+------+-----+---------+----------------+
```
adapter日志：
```
2020-08-11 10:30:54.502 [pool-8-thread-1] INFO  c.a.o.canal.client.adapter.logger.LoggerAdapterExample - DML: {"data":[{"id":1,"right_code":"test","address_ip":"test","date":null}],"database":"manage","destination":"example","es":1597113148000,"groupId":null,"isDdl":false,"old":null,"pkNames":["id"],"sql":"","table":"account_code","ts":1597113054502,"type":"DELETE"}
2020-08-11 10:30:54.504 [pool-7-thread-1] ERROR com.alibaba.otter.canal.client.adapter.support.Util - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'manage.account_code WHERE 1=2' at line 1
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'manage.account_code WHERE 1=2' at line 1
        at sun.reflect.GeneratedConstructorAccessor34.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
        at com.mysql.jdbc.Util.getInstance(Util.java:408)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3970)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3906)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2677)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2503)
        at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1369)
        at com.alibaba.druid.pool.DruidPooledStatement.executeQuery(DruidPooledStatement.java:230)
        at com.alibaba.otter.canal.client.adapter.support.Util.sqlRS(Util.java:77)
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.getTargetColumnType(RdbSyncService.java:415)
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.delete(RdbSyncService.java:368)
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.sync(RdbSyncService.java:216)
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$null$0(RdbSyncService.java:115)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$sync$1(RdbSyncService.java:115)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-08-11 10:30:54.505 [pool-6-thread-1] ERROR com.alibaba.otter.canal.client.adapter.support.Util - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'manage.account_code WHERE 1=2' at line 1
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'manage.account_code WHERE 1=2' at line 1
        at sun.reflect.GeneratedConstructorAccessor34.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
        at com.mysql.jdbc.Util.getInstance(Util.java:408)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3970)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3906)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2677)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2503)
        at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1369)
        at com.alibaba.druid.pool.DruidPooledStatement.executeQuery(DruidPooledStatement.java:230)
        at com.alibaba.otter.canal.client.adapter.support.Util.sqlRS(Util.java:77)
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.getTargetColumnType(RdbSyncService.java:415)
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.insert(RdbSyncService.java:258)
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.sync(RdbSyncService.java:212)
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$null$0(RdbSyncService.java:115)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$sync$1(RdbSyncService.java:115)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-08-11 10:30:54.507 [pool-5-thread-1] ERROR com.alibaba.otter.canal.client.adapter.support.Util - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'manage.account_code WHERE 1=2' at line 1
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'manage.account_code WHERE 1=2' at line 1
        at sun.reflect.GeneratedConstructorAccessor34.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
        at com.mysql.jdbc.Util.getInstance(Util.java:408)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3970)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3906)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2677)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2503)
        at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1369)
        at com.alibaba.druid.pool.DruidPooledStatement.executeQuery(DruidPooledStatement.java:230)
        at com.alibaba.otter.canal.client.adapter.support.Util.sqlRS(Util.java:77)
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.getTargetColumnType(RdbSyncService.java:415)
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.insert(RdbSyncService.java:258)
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.sync(RdbSyncService.java:212)
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$null$0(RdbSyncService.java:115)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$sync$1(RdbSyncService.java:115)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-08-11 10:30:54.509 [pool-8-thread-1] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: Target column: id not matched
java.lang.RuntimeException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: Target column: id not matched
        at com.alibaba.otter.canal.client.adapter.rdb.RdbAdapter.sync(RdbAdapter.java:171)
        at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.batchSync(AbstractCanalAdapterWorker.java:201)
        at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$1(AbstractCanalAdapterWorker.java:62)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$2(AbstractCanalAdapterWorker.java:58)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: Target column: id not matched
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$sync$2(RdbSyncService.java:132)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.sync(RdbSyncService.java:128)
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbMirrorDbSyncService.sync(RdbMirrorDbSyncService.java:83)
        at com.alibaba.otter.canal.client.adapter.rdb.RdbAdapter.sync(RdbAdapter.java:169)
        ... 8 common frames omitted
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: Target column: id not matched
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$sync$2(RdbSyncService.java:130)
        ... 12 common frames omitted
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Target column: id not matched
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$sync$1(RdbSyncService.java:123)
        ... 4 common frames omitted
Caused by: java.lang.RuntimeException: Target column: id not matched
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.insert(RdbSyncService.java:270)
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.sync(RdbSyncService.java:212)
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$null$0(RdbSyncService.java:115)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$sync$1(RdbSyncService.java:115)
        ... 4 common frames omitted
2020-08-11 10:30:54.510 [Thread-4] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - Outer adapter sync failed!  Error sync but ACK!
```

**Comment by lklkxcxc** [comment]
后面测试导入到源数据库一样版本的mysql5.7 也是报上面错误

**Comment by 306094061** [comment]
解决了吗

**Comment by renxing5** [comment]
解决了么？我也遇到了这个问题

**Comment by renxing5** [comment]
数据库名称  必须是下划线   如果不是  就会报这个错

**Comment by dingziyang** [comment]
> canal 版本 1.1.5
我将mysql  --> postgress. 也碰到这个问题，猜测是源码有bug; 源码tag-1.1.5中的com.alibaba.otter.canal.client.adapter.rdb.support.SyncUtil.class中最后面有个方法如下：
```
public static String getDbTableName(MappingConfig.DbMapping dbMapping) {
        String result = "";
        if (StringUtils.isNotEmpty(dbMapping.getTargetDb())) {
            result += ("`" + dbMapping.getTargetDb() + "`.");
        }
        result += ("`" + dbMapping.getTargetTable() + "`");
        return result;
       // 上述代码执行后，不管你写不写targetDb参数， 最终的效果都是`库.表` 或者 `表`；但是这种语法并不是所有数据库都能用，刚好我这次的目标库postgress就不行，真是坑啊。
    }
```
-------
在postgress客户端执行到单斜引号报错如下： 刚好应证了上面的强制加了单斜引号
```
select * from `area_copy`
> ERROR:  syntax error at or near "`"
LINE 1: select * from `area_copy`
                      ^

> 时间: 0.002s
```
-------
> 下面是报错信息， 总是某字段 not matched，怎么写都不行
```
dbMapping:
  # 源数据库 
  database: dyh_bm
  # 源表
  table: area_copy
  # 目的数据库.表
  targetTable: area_copy
  targetPk:
    id: id
  # 开启则表示两边的表需要一模一样
  mapAll: true
```
使用navicat数据传输过去的， 我确定两边的表一模一样
```
2021-11-09 02:43:12.223 [pool-7-thread-1] ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: Target column: id not matched
java.lang.RuntimeException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: Target column: id not matched
	at com.alibaba.otter.canal.client.adapter.rdb.RdbAdapter.sync(RdbAdapter.java:171) ~[na:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.batchSync(AdapterProcessor.java:139) ~[client-adapter.launcher-1.1.5.jar:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.lambda$null$1(AdapterProcessor.java:97) ~[client-adapter.launcher-1.1.5.jar:na]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:895) ~[na:1.8.0_301]
	at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.lambda$null$2(AdapterProcessor.java:94) ~[client-adapter.launcher-1.1.5.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_301]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_301]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_301]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_301]
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: Target column: id not matched
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$sync$2(RdbSyncService.java:133) ~[na:na]
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[na:1.8.0_301]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.sync(RdbSyncService.java:129) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.sync(RdbSyncService.java:153) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.rdb.RdbAdapter.sync(RdbAdapter.java:168) ~[na:na]
	... 8 common frames omitted
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: Target column: id not matched
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_301]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_301]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$sync$2(RdbSyncService.java:131) ~[na:na]
	... 12 common frames omitted
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Target column: id not matched
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$sync$1(RdbSyncService.java:124) ~[na:na]
	... 4 common frames omitted
Caused by: java.lang.RuntimeException: Target column: id not matched
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.insert(RdbSyncService.java:275) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.sync(RdbSyncService.java:214) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$null$0(RdbSyncService.java:115) ~[na:na]
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[na:1.8.0_301]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$sync$1(RdbSyncService.java:115) ~[na:na]
	... 4 common frames omitted
2021-11-09 02:43:12.224 [Thread-5] ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - Outer adapter sync failed!  Error sync but ACK!
```

**Comment by dingziyang** [comment]
我准备在本地下载tag-1.1.5的源码，改动一点，多打写config方面的日志出来，然后替换掉adapter的lib
1. cd canal-adapter/lib # 每个人adapter安装文件夹名可能不一样
2. mv client-adapter.launcher-1.1.5.jar client-adapter.launcher-1.1.5.jar.copy # 先备份下原始包
3. 在本地下载好源码，先在最外层install一下：```mvn clean install -am -Dmaven.test.skip=true ``` # 如果需要自己指定--settings
4. 修改com.alibaba.otter.canal.client.adapter.rdb.support.SyncUtil.class的getDbTableName方法，以及在RdbSyncService和RdbMirrorDbSyncService多打点日志，方便看问题。

**Comment by dingziyang** [comment]
我放弃改源码管理私有版本了，直接用1.1.4 ，至少SyncUtil.class这里是好的
> 感觉1.1.5的这里是实习生写的吧
```
public static String getDbTableName(MappingConfig.DbMapping dbMapping) {
        String result = "";
        if (StringUtils.isNotEmpty(dbMapping.getTargetDb())) {
            result += dbMapping.getTargetDb() + ".";
        }
        result += dbMapping.getTargetTable();
        return result;
    }
```

**Comment by dingziyang** [comment]
我已经成功打通了

**Comment by 306094061** [comment]
通过日志发现问题  表和表一样 但是这个工具同步数据的时候因为某一个数据太长不能同步 把目标库对应的表字段修改类型 成功同步了数据 但是这不合理 所以放弃使用这个了

**Comment by cleanwk** [comment]
> public static String getDbTableName(MappingConfig.DbMapping dbMapping) {
>         String result = "";
>         if (StringUtils.isNotEmpty(dbMapping.getTargetDb())) {
>             result += dbMapping.getTargetDb() + ".";
>         }
>         result += dbMapping.getTargetTable();
>         return result;
>     }

麻麻的。今个看了好久 就是这个问题

**Comment by BrantZheng** [comment]
#3228  引入的问题，明显没考虑到 postgres 数据库

**Comment by Bella-Liang** [comment]
> 数据库名称 必须是下划线 如果不是 就会报这下划线也报错

**Comment by Bella-Liang** [comment]
有完善的解决方案吗？各位

**Comment by cleanwk** [comment]
> 有完善的解决方案吗？各位
<img width="488" alt="image" src="https://user-images.githubusercontent.com/53394058/160402305-bfb7933b-8b89-41fc-be41-073830fcedb8.png">

这项目没人维护了，要么直接用1.14版本的。要么老哥直接改源码然后重新打包一下，新的jar包替换掉release中/plugin目录中对应的jar包就行了。

**Comment by chadwangqq** [comment]
1.6版本解决了吗

**Comment by FrankAblert** [comment]
> 1.6版本解决了吗

解决了
