### ISSUE TITLE
阿里云启动成功，但是本地客户端链接不上是为什么呢？

### ISSUE THREAD

**Issue by 747857485** [alibaba/canal#2946]
`Exception in thread "main" com.alibaba.otter.canal.protocol.exception.CanalClientException: java.net.ConnectException: Connection refused
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:190)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.connect(SimpleCanalConnector.java:114)
	at onlinewawa.ossign.signature.Test.main(Test.java:29)
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:454)
	at sun.nio.ch.Net.connect(Net.java:446)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:149)`

客户端代码是在官方复制的
`        // 创建链接
        CanalConnector connector = CanalConnectors.newSingleConnector(new InetSocketAddress("118.190.1.182",
                11111), "example", "", "");`
服务端启动日志

`2020-08-11 15:23:37.519 [main] INFO  com.alibaba.otter.canal.deployer.CanalLauncher - ## set default uncaught exception handler
2020-08-11 15:23:37.569 [main] INFO  com.alibaba.otter.canal.deployer.CanalLauncher - ## load canal configurations
2020-08-11 15:23:37.583 [main] INFO  com.alibaba.otter.canal.deployer.CanalStarter - ## start the canal server.
2020-08-11 15:23:37.624 [main] INFO  com.alibaba.otter.canal.deployer.CanalController - ## start the canal server[172.31.94.125(172.31.94.125):11111]
2020-08-11 15:23:38.450 [main] INFO  com.alibaba.otter.canal.deployer.CanalStarter - ## the canal server is running now ......
`

**Comment by agapple** [comment]
指定一下具体IP把

**Comment by VirgilLone** [comment]
求教我指定的内网ip咋还是连接拒绝呢

**Comment by VirgilLone** [comment]
> 指定一下具体IP把

求教我指定了内网ip咋还是连接拒绝呢
