### ISSUE TITLE
发生网络抖动后，canalserver会卡住，不能自动恢复

### ISSUE THREAD

**Issue by lan1994** [alibaba/canal#297]
问题描述：
当发生网络抖动时，canalserver会被卡住，网络恢复正常后canalserver不能自动恢复正常，需要手动重启instance才能恢复。
心跳检查是开启的，异常栈如下：
2017-04-21 00:29:16.425 [destination = xxxx, address = xxxx , HeartBeatTimeTask] WARN  c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - connect failed by java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:197)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379)
        at com.alibaba.otter.canal.parse.driver.mysql.utils.PacketManager.readBytesAsBuffer(PacketManager.java:20)
        at com.alibaba.otter.canal.parse.driver.mysql.utils.PacketManager.readHeader(PacketManager.java:13)
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlQueryExecutor.readNextPacket(MysqlQueryExecutor.java:104)
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlQueryExecutor.query(MysqlQueryExecutor.java:55)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.query(MysqlConnection.java:68)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser$MysqlDetectingTimeTask.run(MysqlEventParser.java:191)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)

除此之外没有其它的异常信息，有人遇到这种情况么

**Comment by lan1994** [comment]
@agapple

**Comment by agapple** [comment]
要么是mysql binlogdump的tcp链接被异常断开了，canal没有感知到

**Comment by lan1994** [comment]
代码中，有异常应该是能捕捉到的，捕捉到异常会重连重试的，但是我这里没有重试。你说canal没有感知到是指异常没有捕捉到吗

**Comment by agapple** [comment]
应该是socket一直阻塞在读操作上，没有感知到异常

**Comment by alexandnpu** [comment]
@lan1994 , 今天也遇到了这种情况，而且sotimeout默认是30秒，当网络不稳定的情况下，更拖慢了binlog的消费。 

@agapple ，不知道这里的30秒有什么讲究

**Comment by alexandnpu** [comment]
我的栈好像不太一样

```
2017-06-27 19:50:47.285 [destination = xxxxx , address = xxxxx , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - I/O error while reading from client socket
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_131]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_131]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_131]
        at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[na:1.8.0_131]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_131]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:154) ~[canal.parse-1.0.24.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:70) ~[canal.parse-1.0.24.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:122) [canal.parse-1.0.24.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209) [canal.parse-1.0.24.jar:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
```

**Comment by lan1994** [comment]
你的这个栈我也遇到过，那个sotimeout 30s没什么用，因为这个设置对于nio没有作用，产生这个问题应该是网络出现故障后，canal 的解析线程一直在read，没有感知到故障    我们可能需要一个类似sotimeout 超时重连的功能 @alexandnpu

**Comment by agapple** [comment]
当前master版本已经提供，可以关注

**Comment by alexandnpu** [comment]
@agapple ， 有相关的PR吗？

**Comment by agapple** [comment]
别人提交的一个MR，主要是基于netty改造了，增加了超时读取，可以关注一下代码里的SocketChannel

**Comment by alexandnpu** [comment]
好的，回头找找，只是觉得，你能提供一个pr号，或者一个commit id，会更容易一些

**Comment by agapple** [comment]
https://github.com/alibaba/canal/pull/334

**Comment by alexandnpu** [comment]
Thanks
