### ISSUE TITLE
日志异常dataType=DB_BATCH，求解决办法

### ISSUE THREAD

**Issue by angelmm126** [alibaba/canal#299]
日志错误信息：
pid:5 nid:1 exception:setl:load miss data with keys:[MemoryPipeKey[identity=Identity[channelId=2,pipelineId=5,processId=702747],time=1493745579135,dataType=DB_BATCH]]

pid:5 nid:1 exception:canal:canal_题库:java.io.IOException: Connection reset by peer
    at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
    at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
    at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
    at sun.nio.ch.IOUtil.read(IOUtil.java:197)
    at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379)
    at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:154)
    at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:70)
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:121)
    at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209)
    at java.lang.Thread.run(Thread.java:744)

**Comment by agapple** [comment]
Connection reset by peer，网络被mysql给断开了吧，重试一下就好
