### ISSUE TITLE
ClientAdapter在压测中出现单事务sql条数超限的报错

### ISSUE THREAD

**Issue by roamerway** [alibaba/canal#2999]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version 1.1.5
* mysql version tidb

### Issue Description
在对ClientAdapter进行压测时，会不断报出下面的异常：
`
2020-09-02 11:21:51.124 [pool-7-thread-1] ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: java.sql.SQLException: statement count 5001 exceeds the transaction limitation, autocommit = false
java.lang.RuntimeException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: java.sql.SQLException: statement count 5001 exceeds the transaction limitation, autocommit = false
        at com.alibaba.otter.canal.client.adapter.rdb.RdbAdapter.sync(RdbAdapter.java:171) ~[na:na]
        at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.batchSync(AdapterProcessor.java:139) ~[client-adapter.launcher-1.1.5.1c.jar:na]
`
测试环境为：CanalSever + Kafka + ClientAdapter + TiDB，一次性同步2万条记录。
TiDB设置了事务最大sql条数为5000

### Actual behaviour

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by roamerway** [comment]
问题偶发，无法重现。
从代码分析，的确存在超出事务最大限制的可能性
