### ISSUE TITLE
binlog 解析出现问题

### ISSUE THREAD

**Issue by wang87612** [alibaba/canal#300]
com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: java.lang.IllegalArgumentException: limit excceed: 191
	at com.taobao.tddl.dbsync.binlog.LogBuffer.getFullString(LogBuffer.java:1140) ~[canal.parse.dbsync-1.0.25-SNAPSHOT.jar:na]
	at com.taobao.tddl.dbsync.binlog.event.RowsLogBuffer.fetchValue(RowsLogBuffer.java:923) ~[canal.parse.dbsync-1.0.25-SNAPSHOT.jar:na]
	at com.taobao.tddl.dbsync.binlog.event.RowsLogBuffer.nextValue(RowsLogBuffer.java:99) ~[canal.parse.dbsync-1.0.25-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseOneRow(LogEventConvert.java:495) ~[canal.parse-1.0.25-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseRowsEvent(LogEventConvert.java:388) ~[canal.parse-1.0.25-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:111) ~[canal.parse-1.0.25-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:62) ~[canal.parse-1.0.25-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser.parseAndProfilingIfNecessary(AbstractEventParser.java:326) ~[canal.parse-1.0.25-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3$1.sink(AbstractEventParser.java:176) ~[canal.parse-1.0.25-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:130) [canal.parse-1.0.25-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209) [canal.parse-1.0.25-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]

[mysql-bin.000954.zip](https://github.com/alibaba/canal/files/972734/mysql-bin.000954.zip)

提供了出错的binlog 文件 canal版本为 1.0.24 mysql 版本为 10.0.26-MariaDB-enterprise

**Comment by wang87612** [comment]
同样版本的 另一个mysql  binlog 解析就没有问题
[mysql-bin.005283.zip](https://github.com/alibaba/canal/files/972748/mysql-bin.005283.zip)

**Comment by wang87612** [comment]
加大了  canal.instance.memory.buffer.size 不在报错 但是 也不解析 
## memory store RingBuffer size, should be Math.pow(2,n)
canal.instance.memory.buffer.size = 268435456

**Comment by wang87612** [comment]
用FileLogFetcherTest本地解析binlog 也同样报错 但是 加大
 FileLogFetcher fetcher = new FileLogFetcher(1024 * 1024 * 1024);
参数后 测试通过

**Comment by wang87612** [comment]
很奇怪 我换了个几个mysql 版本 生成的binlog  用这个本地解析类FileLogFetcherTest 都不能正常解析
都必须调整 new FileLogFetcher(1024 * 1024 * 1024); 这里的参数 往大了调才测试通过

**Comment by wang87612** [comment]
貌似和 varchar 长度有关系  超过255 就会出现这个问题

**Comment by wang87612** [comment]
出错的几个表 varchar长度均超过了255 有的1024 有的2048

**Comment by wang87612** [comment]
最新发现 貌似和 下面的表结构有关系
 `create_time` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `update_time` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最近操作时间',
  `submit_time` timestamp NULL DEFAULT NULL COMMENT '第一次提交借进件的时间',

 只要建表里 有这些列 就直接解析出错 建表不加这些列 就解析没问题

**Comment by wang87612** [comment]
### INSERT INTO `a1`.`apply_info_222`
### SET
###   @1=***Corrupted replication event was detected. Not printing the value***

每次我插入一条数据  在binlog里 都会出来这个玩意 感觉是这个的问题

**Comment by agapple** [comment]
我先关注一下你的测试binlog文件

**Comment by dadarom** [comment]
应该和mariadb的timestamp精度有关，参考下：
[MDEV-9567](https://jira.mariadb.org/browse/MDEV-9567)
[MDEV-5377](https://jira.mariadb.org/browse/MDEV-5377)

**Comment by agapple** [comment]
感觉是mariadb在binlog协议里没有记录足够的meta信息，导致解析失败. 试过10.1系列的mariadb ？我是参考10.1的进行协议解析对比

**Comment by Xiangakun** [comment]
@agapple 你好~，请问这个问题能修复吗？我也遇到了同样的问题，我试了10.0.21-MariaDB，5.5.49-MariaDB版本，都是有问题的，（而10.2.18-MariaDB 这个版本则没有问题，应该是这个版本的binlog修复好了），对于 datetime,timestamp,time 类型的只要是毫秒级别的数据解析都有问题，正如你说的，应该就是没有足够的meta信息，对于timestamp类型的，我在 LogEventConvert.parseOneRow 方法中根据 tableMeta 的columnType，重设了ColumnInfo 信息，对于timestamp长度不为0的，将 info.type 设为 LogEvent.MYSQL_TYPE_TIMESTAMP2，并将长度设给 info.meta， 这样就能正常解析了 (备注：由于时间比较紧急，临时打的补丁)。而对于datetime跟time 类型，则不能如法炮制，应该是时间解析的时候规则可能略有不同，时间原因没有细究。
如果可以的话，希望你们能帮忙修复这个bug, 非常感谢~

**Comment by Xiangakun** [comment]
@agapple

**Comment by ruochen** [comment]
支持MariaDB的哪些版本？
