### ISSUE TITLE
es adapter 运行一段时间后同步数据到es 会报错

### ISSUE THREAD

**Issue by code4j-chen** [alibaba/canal#3016]
```
2020-09-07 15:49:29.106 [pool-7-thread-1] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - ES sync commit errorElasticsearchException[Elasticsearch exception [type=mapper_parsing_exception, reason=Field [_id] is a metadata field and cannot be added inside a document. Use the index API request parameters.]]
java.lang.RuntimeException: ES sync commit errorElasticsearchException[Elasticsearch exception [type=mapper_parsing_exception, reason=Field [_id] is a metadata field and cannot be added inside a document. Use the index API request parameters.]]
        at com.alibaba.otter.canal.client.adapter.es.support.ESTemplate.commit(ESTemplate.java:208)
        at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.commit(ESSyncService.java:852)
        at com.alibaba.otter.canal.client.adapter.es.ESAdapter.sync(ESAdapter.java:151)
        at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.batchSync(AbstractCanalAdapterWorker.java:201)
        at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$1(AbstractCanalAdapterWorker.java:62)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$2(AbstractCanalAdapterWorker.java:58)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2020-09-07 15:49:29.106 [Thread-8] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - Outer adapter sync failed!  Error sync but ACK!
```

**Comment by shifufu** [comment]
我也遇到这个问题了，求解决。

**Comment by wkwk0** [comment]
这个问题困扰了我好久了，看源码看的头疼

**Comment by zhangjingwei-gwi** [comment]
> 这个问题困扰了我好久了，看源码看的头疼

兄弟，你的工程项目能编译通过么？
我上来就报个 “[ERROR] import: Entry[import  from realm ClassRealm[project>com.alibaba.otter:canal:1.1.4, parent: ClassRealm[maven.api, parent: null]]]”

**Comment by wangyu1916** [comment]
_id是不是用了几张表的联合主键？

**Comment by eactt** [comment]
> _id是不是用了几张表的联合主键？

我就是，也遇到这个问题了，你们解决了吗

**Comment by MengyanGuo** [comment]
同问！好像数据同步没问题，就是一直报这个错

**Comment by LQresier** [comment]
同样出现这个问题！不知道怎么解决

**Comment by Bundanpipi** [comment]
_id的值被修改了吗
例如 _id = CONCAT(a, "_", b)
a和b旧的值分别为v1,v2
将b的值修改为v3, 则canal去mysql中查找 a = v1， b = v2的数据，查找不到导致同步失败报错

**Comment by wxk1221** [comment]
有人解决了?求解决啊

**Comment by yilongchuan** [comment]
应该是因为某次操作监听到了_id字段的变更，导致更新语句中有了_id字段；
elasticsearch发现没有_id字段，触发了新增字段的操作，但是_id又是一个metadata 字段，不能新增。
修改方式：1.同步配置文件中（yml文件）添加 skips:  - _id，将 _id 字段作忽略掉可以了
2.修改源码，将_id默认加到skips中。——1358395292@qq.com
