### ISSUE TITLE
getWithoutAck中timeout设置为0,导致subscribe方法时SocketTimeoutException

### ISSUE THREAD

**Issue by maowei0427** [alibaba/canal#3018]
### environment

* canal version
1.1.4

### Issue Description
![image](https://user-images.githubusercontent.com/34717256/92434754-3c488300-f1d3-11ea-9f6b-f5b8e8a5be87.png)

![image](https://user-images.githubusercontent.com/34717256/92435061-035cde00-f1d4-11ea-9296-ef2cde8eb134.png)

当我参考源码方法注释,设置timeout参数为0的时候,我的canal程序一直处于阻塞状态, 过了好一会后会报SocketTimeoutException,
并且当我设置timeout参数为0的时候,我发现原来使用正常的client也受到了影响,线程会在connector.subscribe方法上一直阻塞,一直到超时错误.
我尝试重启服务端的时候可以解决这个问题,但是下次设置timeout参数为0时又有同样的问题

### Exception Info:

Exception in thread "main" com.alibaba.otter.canal.protocol.exception.CanalClientException: java.net.SocketTimeoutException
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.subscribe(SimpleCanalConnector.java:254)
	at com.vlinklink.sync.test.SimpleCanalClientExample.main(SimpleCanalClientExample.java:24)
Caused by: java.net.SocketTimeoutException
	at sun.nio.ch.SocketAdaptor$SocketInputStream.read(SocketAdaptor.java:211)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
	at java.nio.channels.Channels$ReadableByteChannelImpl.read(Channels.java:385)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.read(SimpleCanalConnector.java:411)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.readNextPacket(SimpleCanalConnector.java:401)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.readNextPacket(SimpleCanalConnector.java:385)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.subscribe(SimpleCanalConnector.java:246)
	... 1 more

**Comment by maowei0427** [comment]
申明 : 设置timeout参数为0的时候,有binlog产生(我自己模拟了数据的修改删除等操作),即满足了batchSize=1的条件, 按理来说不应该会超时了

**Comment by wangyu1916** [comment]
是不是没有binlog产生

**Comment by sunqb** [comment]
遇到同样的问题，canal1.1.7

**Comment by sunqb** [comment]
> 

现象一样，但是原因不一样：我的原因是canal服务上面的数据库权限有问题，定位问题的方法是查看canal的日志

**Comment by wangxin-200** [comment]
也遇到了相同的问题，
![image](https://user-images.githubusercontent.com/69952057/191158180-883a4366-9aea-4e8c-b4b1-7b3f90b5c432.png)
![image](https://user-images.githubusercontent.com/69952057/191158231-b86007bd-eae1-4c6a-9966-85149556c15e.png)

**Comment by sunqb** [comment]
> 也遇到了相同的问题， ![image](https://user-images.githubusercontent.com/69952057/191158180-883a4366-9aea-4e8c-b4b1-7b3f90b5c432.png) ![image](https://user-images.githubusercontent.com/69952057/191158231-b86007bd-eae1-4c6a-9966-85149556c15e.png)

建议先看日志吧，看下canal服务上面的日志

**Comment by wangxin-200** [comment]
这个异常跟了好几天，已经确定是这个问题了。subscribe(）出现了超时异常，导致线程中断，但是加了捕获和循环去连接canal-server, 一直链接不上。不知道是不是canal-server的配置有关系。
