### ISSUE TITLE
一段时间没有去拉binlog，直至报错的疑问

### ISSUE THREAD

**Issue by owenludong** [alibaba/canal#303]
18:23:55.605收到最后一个binlog请求，下一个日志就是2017-05-18 20:35:27.539的日志，
两个疑问：
1、中间两个小时的binlog为什么没有去拉
2、2017-05-18 20:35:27.539  的报错不像是找不到binlog文件，这个错误有什么经验能分享下吗？

下面的是昨晚的日志：

2017-05-18 18:23:55.605 [New I/O server worker #1-6] INFO  c.a.otter.canal.server.embedded.CanalServerWithEmbedded - ack successfully, clientId:1001 batchId:7193361 position:PositionRange[start=LogPosition[identity=LogIdentity[sourceAddress=x/y:3306,slaveId=-1],postion=EntryPosition[included=false,journalName=mysql-bin.006011,position=409700943,serverId=262651658,timestamp=1495103035000]],ack=LogPosition[identity=LogIdentity[sourceAddress=x:3306,slaveId=-1],postion=EntryPosition[included=false,journalName=mysql-bin.006011,position=409702008,serverId=262651658,timestamp=1495103035000]],end=LogPosition[identity=LogIdentity[sourceAddress=x/10.157.81.57:3306,slaveId=-1],postion=EntryPosition[included=false,journalName=mysql-bin.006011,position=409702008,serverId=262651658,timestamp=1495103035000]]]

2017-05-18 20:35:27.539 [destination = db50-59 , address = x/y:3306 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - I/O error while reading from client socket
java.io.IOException: Connection timed out
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.7.0_45]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.7.0_45]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.7.0_45]
        at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[na:1.7.0_45]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379) ~[na:1.7.0_45]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:154) ~[canal.parse-1.0.22.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:70) ~[canal.parse-1.0.22.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:113) [canal.parse-1.0.22.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:210) [canal.parse-1.0.22.jar:na]
        at java.lang.Thread.run(Thread.java:744) [na:1.7.0_45]
2017-05-18 20:35:27.599 [destination = db50-59 , address = x/y:3306 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - dump address x/y:3306 has an error, retrying. caused by
java.io.IOException: Connection timed out
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.7.0_45]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.7.0_45]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.7.0_45]
        at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[na:1.7.0_45]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379) ~[na:1.7.0_45]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:154) ~[canal.parse-1.0.22.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:70) ~[canal.parse-1.0.22.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:113) ~[canal.parse-1.0.22.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:210) ~[canal.parse-1.0.22.jar:na]

**Comment by Sunkiss007** [comment]
2017-05-18 20:35:27.599 [destination = db50-59 , address = mangoerpdb1.mysql.rds.aliyuncs.com/10.157.81.57:3306 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - dump address mangoerpdb1.mysql.rds.aliyuncs.com/10.157.81.57:3306 has an error, retrying. caused by
java.io.IOException: Connection timed out
会不会是这段时间数据库连接异常？

**Comment by agapple** [comment]
中间没有日志不是代表没有拉取binlog啊
