### ISSUE TITLE
pos 15, line 1, column 14, token LITERAL_FLOAT

### ISSUE THREAD

**Issue by 514826395** [alibaba/canal#3031]
020-09-11 15:15:55.308 [destination = example , address = / , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address / has an error, retrying. caused by 
com.alibaba.fastsql.sql.parser.ParserException: illegal sql expr :  pos 15, line 1, column 14, token LITERAL_FLOAT
	at com.alibaba.fastsql.sql.SQLUtils.toSQLExpr(SQLUtils.java:258) ~[fastsql-2.0.0_preview_973.jar:2.0.0_preview_973]
	at com.alibaba.fastsql.sql.repository.Schema.setName(Schema.java:77) ~[fastsql-2.0.0_preview_973.jar:2.0.0_preview_973]
	at com.alibaba.fastsql.sql.repository.SchemaRepository.setDefaultSchema(SchemaRepository.java:130) ~[fastsql-2.0.0_preview_973.jar:2.0.0_preview_973]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta.apply(MemoryTableMeta.java:72) ~[canal.parse-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.dumpTableMeta(DatabaseTableMeta.java:236) ~[canal.parse-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:182) ~[canal.parse-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:137) ~[canal.parse-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:200) ~[canal.parse-1.1.4.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_201]
2020-09-11 15:15:55.309 [destination = example , address = / , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[com.alibaba.fastsql.sql.parser.ParserException: illegal sql expr : ynsj_course_2.0, pos 15, line 1, column 14, token LITERAL_FLOAT
	at com.alibaba.fastsql.sql.SQLUtils.toSQLExpr(SQLUtils.java:258)
	at com.alibaba.fastsql.sql.repository.Schema.setName(Schema.java:77)
	at com.alibaba.fastsql.sql.repository.SchemaRepository.setDefaultSchema(SchemaRepository.java:130)
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta.apply(MemoryTableMeta.java:72)
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.dumpTableMeta(DatabaseTableMeta.java:236)
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:182)
	at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:137)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:200)
	at java.lang.Thread.run(Thread.java:748)

**Comment by lijianghu** [comment]
碰到了同样的问题，有人解答一下吗？

**Comment by lijianghu** [comment]
看着像是数据库名有小数点导致。

**Comment by agapple** [comment]
最新代码已修复
