### ISSUE TITLE
CanalConnectors.newSingleConnector(SocketAddress address, String destination, String username, String password) 请问一下，第3、第4个参数用户名与密码，这里传的是什么的用户名与密码，是mysql的用户名与密码吗？

### ISSUE THREAD

**Issue by yin2na** [alibaba/canal#3034]
CanalConnectors.newSingleConnector(SocketAddress address, String destination, String username, String password)

请问一下，第3、第4个参数用户名与密码，这里传的是什么的用户名与密码，是mysql的用户名与密码吗？

**Comment by linshimingyi** [comment]
空着就行

**Comment by yin2na** [comment]
> 空着就行

com.alibaba.otter.canal.protocol.exception.CanalClientException: something goes wrong when doing authentication: auth failed for user:
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:192)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.connect(SimpleCanalConnector.java:115)
	at com.ztesoft.isa.canal.SimpleCanalClientTest2.main(SimpleCanalClientTest2.java:25)

第3、4个参数用户名与密码空着，会报错啊，有谁知道这里是填什么密码吗？
