### ISSUE TITLE
使用cannal同步数据运行半个月突然异常,报的这个错

### ISSUE THREAD

**Issue by yanguojian** [alibaba/canal#3043]
## Question

java.lang.RuntimeException: ES sync commit error [index/aKno3nyrQFGmVK6rQnDXoA][[index][0]] ElasticsearchException[Elasticsearch exception [type=version_conflict_engine_exception, reason=[67ae549e-f7c2-11ea-9935-5254007efafc]: version conflict, document already exists (current version [1])]]
	at com.alibaba.otter.canal.client.adapter.es7x.support.ESConnection$ES7xBulkResponse.processFailBulkResponse(ESConnection.java:474) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.es7x.support.ES7xTemplate.commit(ES7xTemplate.java:171) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.es.core.service.ESSyncService.commit(ESSyncService.java:984) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.es.core.ESAdapter.sync(ESAdapter.java:98) ~[na:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.batchSync(AbstractCanalAdapterWorker.java:201) ~[client-adapter.launcher-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$writeOut$1(AbstractCanalAdapterWorker.java:62) ~[client-adapter.launcher-1.1.5-SNAPSHOT.jar:na]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891) ~[na:1.8.0_241]
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$writeOut$2(AbstractCanalAdapterWorker.java:58) ~[client-adapter.launcher-1.1.5-SNAPSHOT.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_241]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_241]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_241]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_241]

**Comment by yanguojian** [comment]
有木有碰到类似原因的老哥呀

**Comment by 784134748** [comment]
version conflict, document already exists (current version [1])]]

**Comment by sixPulseExcalibur** [comment]
把canal adapter es的retry调大一点,发生版本冲突后重试即可插入,最终数据是正确的.
