### ISSUE TITLE
v1.1.5 连接阿里云RocketMQ失败

### ISSUE THREAD

**Issue by tang1987426** [alibaba/canal#3064]
canal deployer版本：v1.1.5
1、canal配置MQ部分
# Set this value to "cloud", if you want open message trace feature in aliyun.
canal.mq.accessChannel = cloud
canal.mq.servers = http://1570761615070884.mqrest.cn-hangzhou-internal.aliyuncs.com
#canal.mq.servers = http://MQ_INST_1570761615070884_BbMlJuiA.cn-hangzhou.mq-internal.aliyuncs.com:8080
canal.mq.producerGroup = GID_PPYM_SCM_ITEM_CANAL_DAILY
#canal.mq.namespace = MQ_INST_1570761615070884_BbMlJuiA
canal.mq.topic = TIC_PPYM_SCM_ITEM_CANAL_DAILY

2、已事先在对应MQ中添加相应的toppic和group

3、日志报错部分：
2020-09-25 17:52:16.248 [pool-4-thread-1] ERROR c.a.o.c.c.rocketmq.producer.CanalRocketMQProducer - org.apache.rocketmq.client.exception.MQClientException: No route info for this topic, TIC_PPYM_SCM_ITEM_CANAL_DAILY
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
java.lang.RuntimeException: org.apache.rocketmq.client.exception.MQClientException: No route info for this topic, TIC_PPYM_SCM_ITEM_CANAL_DAILY
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
	at com.alibaba.otter.canal.connector.rocketmq.producer.CanalRocketMQProducer.sendMessage(CanalRocketMQProducer.java:268) ~[na:na]
	at com.alibaba.otter.canal.connector.rocketmq.producer.CanalRocketMQProducer.sendMessage(CanalRocketMQProducer.java:292) ~[na:na]
	at com.alibaba.otter.canal.connector.rocketmq.producer.CanalRocketMQProducer.send(CanalRocketMQProducer.java:249) ~[na:na]
	at com.alibaba.otter.canal.connector.rocketmq.producer.CanalRocketMQProducer.send(CanalRocketMQProducer.java:151) ~[na:na]
	at com.alibaba.otter.canal.server.CanalMQStarter.worker(CanalMQStarter.java:185) [canal.server-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.server.CanalMQStarter.access$500(CanalMQStarter.java:25) [canal.server-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.server.CanalMQStarter$CanalMQRunnable.run(CanalMQStarter.java:227) [canal.server-1.1.5-SNAPSHOT.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_241]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_241]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_241]
Caused by: org.apache.rocketmq.client.exception.MQClientException: No route info for this topic, TIC_PPYM_SCM_ITEM_CANAL_DAILY
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendSelectImpl(DefaultMQProducerImpl.java:1108) ~[na:na]
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1068) ~[na:na]
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1063) ~[na:na]
	at org.apache.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:524) ~[na:na]
	at com.alibaba.otter.canal.connector.rocketmq.producer.CanalRocketMQProducer.sendMessage(CanalRocketMQProducer.java:256) ~[na:na]
	... 9 common frames omitted

**Comment by ReidStack** [comment]
你们后面是怎么解决的呀

**Comment by cnhnnyzhy** [comment]
解决了吗？我也是这个问题。

**Comment by jiang-yunlong** [comment]
我也是这个问题，找阿里云的售后，折腾了一天，他们也没找到问题，让我来社区看看。。。

**Comment by agapple** [comment]
估计是ak/sk的配置不生效问题，最新代码已经解决

**Comment by yudidi** [comment]
之前没理解ak/sk的意思，原来是accessKey和secretKey的意思，配了就行了。
```
# aliyun ak/sk , support rds/mq
canal.aliyun.accessKey =
canal.aliyun.secretKey =
```
