### ISSUE TITLE
Read timed out

### ISSUE THREAD

**Issue by LiuFuyuan** [alibaba/canal#3069]
启动 canal-server 的时候报 read timed out 异常，虚拟机里面跑的，使用的是 NAT 模式，防火墙关闭了，主机里面可以访问到虚拟机里面的 admin 管理页面，能帮忙排查下是什么原因导致的吗

`2020-09-28 14:52:50.627 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "[read] I/O error: Read timed out"
2020-09-28 14:52:50.627 [main] DEBUG o.a.http.impl.conn.DefaultManagedHttpClientConnection - http-outgoing-0: Close connection
2020-09-28 14:52:50.628 [main] DEBUG o.a.http.impl.conn.DefaultManagedHttpClientConnection - http-outgoing-0: Shutdown connection
2020-09-28 14:52:50.628 [main] DEBUG org.apache.http.impl.execchain.MainClientExec - Connection discarded
2020-09-28 14:52:50.628 [main] DEBUG o.a.http.impl.conn.PoolingHttpClientConnectionManager - Connection released: [id: 0][route: {}->http://127.0.0.1:8089][total kept alive: 0; route allocated: 0 of 2; total allocated: 0 of 20]
2020-09-28 14:52:50.628 [main] DEBUG org.apache.http.impl.execchain.MainClientExec - Cancelling request execution
2020-09-28 14:52:50.636 [main] ERROR com.alibaba.otter.canal.deployer.CanalLauncher - ## Something goes wrong when starting up the canal Server:
com.alibaba.otter.canal.common.CanalException: load manager config failed.
Caused by: java.lang.RuntimeException: requestGet remote error, request : http://127.0.0.1:8089/api/v1/config/server_polling?ip=192.168.170.130&port=11110&md5=&register=1&cluster=
	at com.alibaba.otter.canal.instance.manager.plain.HttpHelper.get(HttpHelper.java:109) ~[canal.instance.manager-1.1.4.jar:na]
	at com.alibaba.otter.canal.instance.manager.plain.PlainCanalConfigClient.doQuery(PlainCanalConfigClient.java:119) ~[canal.instance.manager-1.1.4.jar:na]
	at com.alibaba.otter.canal.instance.manager.plain.PlainCanalConfigClient.queryConfig(PlainCanalConfigClient.java:108) ~[canal.instance.manager-1.1.4.jar:na]
	at com.alibaba.otter.canal.instance.manager.plain.PlainCanalConfigClient.findServer(PlainCanalConfigClient.java:75) ~[canal.instance.manager-1.1.4.jar:na]
	at com.alibaba.otter.canal.deployer.CanalLauncher.main(CanalLauncher.java:69) ~[canal.deployer-1.1.4.jar:na]
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method) ~[na:1.8.0_261]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[na:1.8.0_261]
	at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[na:1.8.0_261]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:1.8.0_261]
	at org.apache.http.impl.conn.LoggingInputStream.read(LoggingInputStream.java:87) ~[httpclient-4.5.1.jar:4.5.1]
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:139) ~[httpcore-4.4.3.jar:4.4.3]
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:155) ~[httpcore-4.4.3.jar:4.4.3]
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:284) ~[httpcore-4.4.3.jar:4.4.3]
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140) ~[httpclient-4.5.1.jar:4.5.1]
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57) ~[httpclient-4.5.1.jar:4.5.1]
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261) ~[httpcore-4.4.3.jar:4.4.3]
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165) ~[httpcore-4.4.3.jar:4.4.3]
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167) ~[httpclient-4.5.1.jar:4.5.1]
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272) ~[httpcore-4.4.3.jar:4.4.3]
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124) ~[httpcore-4.4.3.jar:4.4.3]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271) ~[httpclient-4.5.1.jar:4.5.1]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[httpclient-4.5.1.jar:4.5.1]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) ~[httpclient-4.5.1.jar:4.5.1]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.1.jar:4.5.1]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[httpclient-4.5.1.jar:4.5.1]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[httpclient-4.5.1.jar:4.5.1]
	at com.alibaba.otter.canal.instance.manager.plain.HttpHelper.get(HttpHelper.java:99) ~[canal.instance.manager-1.1.4.jar:na]
	... 4 common frames omitted
2020-09-28 15:33:39.742 [main] INFO  com.alibaba.otter.canal.deployer.CanalLauncher - ## set default uncaught exception handler
2020-09-28 15:33:40.331 [main] INFO  com.alibaba.otter.canal.deployer.CanalLauncher - ## load canal configurations
`

**Comment by YaErHub** [comment]
这个问题解决了吗

**Comment by dba7788** [comment]
请问这个问题解决了吗

**Comment by JNSimba** [comment]
请问这个问题解决了吗
