### ISSUE TITLE
org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.

### ISSUE THREAD

**Issue by Level1Accelerator** [alibaba/canal#3083]
## Question

2020-10-10 18:12:40.176 [destination = doris_test , address = /192.168.5.24:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> find start position successfully, EntryPosition[included=false,journalName=mysql-bin.000002,position=1108,serverId=1,gtid=,timestamp=1602321177000] cost : 120ms , the next step is binlog dump
2020-10-10 18:12:40.235 [MultiStageCoprocessor-other-doris_test-0] WARN  c.a.o.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta - dup apply for sql : /* ApplicationName=DBeaver 7.1.5 - Main */ CREATE SCHEMA `doris_test`
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci
2020-10-10 18:12:44.563 [pool-3-thread-2] ERROR com.alibaba.otter.canal.kafka.CanalKafkaProducer - java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.
java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.
	at com.alibaba.otter.canal.kafka.CanalKafkaProducer.produce(CanalKafkaProducer.java:215) ~[canal.server-1.1.4.jar:na]
	at com.alibaba.otter.canal.kafka.CanalKafkaProducer.send(CanalKafkaProducer.java:179) ~[canal.server-1.1.4.jar:na]
	at com.alibaba.otter.canal.kafka.CanalKafkaProducer.send(CanalKafkaProducer.java:117) ~[canal.server-1.1.4.jar:na]
	at com.alibaba.otter.canal.server.CanalMQStarter.worker(CanalMQStarter.java:183) [canal.server-1.1.4.jar:na]
	at com.alibaba.otter.canal.server.CanalMQStarter.access$500(CanalMQStarter.java:23) [canal.server-1.1.4.jar:na]
	at com.alibaba.otter.canal.server.CanalMQStarter$CanalMQRunnable.run(CanalMQStarter.java:225) [canal.server-1.1.4.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_211]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_211]
Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.
	at org.apache.kafka.clients.producer.KafkaProducer$FutureFailure.<init>(KafkaProducer.java:1150) ~[kafka-clients-1.1.1.jar:na]
	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:846) ~[kafka-clients-1.1.1.jar:na]
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:784) ~[kafka-clients-1.1.1.jar:na]
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:671) ~[kafka-clients-1.1.1.jar:na]
	at com.alibaba.otter.canal.kafka.CanalKafkaProducer.produce(CanalKafkaProducer.java:199) ~[canal.server-1.1.4.jar:na]
	... 8 common frames omitted
Caused by: org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.
2020-10-10 18:12:44.565 [pool-3-thread-2] ERROR com.alibaba.otter.canal.server.CanalMQStarter - rollback error, clientId:1001 batchId:11 is not exist , please check
com.alibaba.otter.canal.server.exception.CanalServerException: rollback error, clientId:1001 batchId:11 is not exist , please check

**Comment by dingyufei615** [comment]
# mq config 未匹配到dynamicTopic的落入默认topic
canal.mq.topic=***

**Comment by dingyufei615** [comment]
#mq config 未匹配到dynamicTopic的落入默认topic
canal.mq.topic=unmatch-binlog-topic

**Comment by Level1Accelerator** [comment]
> #mq config 未匹配到dynamicTopic的落入默认topic
> canal.mq.topic=unmatch-binlog-topic

开启了动态topic不会创建还是到canal.mq.topic这个里了

**Comment by agapple** [comment]
检查kafka问题
