### ISSUE TITLE
canal 1.1.4解析binlog日志异常，无法同步数据

### ISSUE THREAD

**Issue by ParanoidHarry** [alibaba/canal#3090]
canal  1.1.4
mysql 5.7.4-m14-log
在mysql修改数据，无法同步。
报错如下：
2020-10-14 16:32:52.689 [MultiStageCoprocessor-other-example-0] ERROR com.taobao.tddl.dbsync.binlog.LogEvent - Query_log_event has unknown status vars (first has code: 14), skipping the rest of them
2020-10-14 16:32:52.692 [MultiStageCoprocessor-other-example-0] WARN  com.taobao.tddl.dbsync.binlog.LogDecoder - Decoding Query failed from: mysql-bin.000001:120
java.io.IOException: Read Q_SQL_MODE_CODE error: limit excceed: 67
	at com.taobao.tddl.dbsync.binlog.event.QueryLogEvent.unpackVariables(QueryLogEvent.java:715) ~[canal.parse.dbsync-1.1.4.jar:na]
	at com.taobao.tddl.dbsync.binlog.event.QueryLogEvent.<init>(QueryLogEvent.java:495) ~[canal.parse.dbsync-1.1.4.jar:na]
	at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:168) ~[canal.parse.dbsync-1.1.4.jar:na]
	at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:111) ~[canal.parse.dbsync-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:264) [canal.parse-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:246) [canal.parse-1.1.4.jar:na]
	at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168) [disruptor-3.4.2.jar:na]
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125) [disruptor-3.4.2.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_211]
	at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_211]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_211]
Caused by: java.lang.IllegalArgumentException: limit excceed: 67
	at com.taobao.tddl.dbsync.binlog.LogBuffer.getLong64(LogBuffer.java:874) ~[canal.parse.dbsync-1.1.4.jar:na]
	at com.taobao.tddl.dbsync.binlog.event.QueryLogEvent.unpackVariables(QueryLogEvent.java:615) ~[canal.parse.dbsync-1.1.4.jar:na]
	... 12 common frames omitted

**Comment by agapple** [comment]
最新代码已修复
