### ISSUE TITLE
关于客户端authentication: auth failed for user:canal问题

### ISSUE THREAD

**Issue by yangzhiwen911** [alibaba/canal#3107]
### environment

* canal version 1.1.4
* mysql version 5.6 
* windows 10

### Issue Description

关于canaladapter客户端启动一种报错的问题，为什么还没修复：
Connected to the target VM, address: '127.0.0.1:52171', transport: 'socket'
process error!com.alibaba.otter.canal.protocol.exception.CanalClientException: something goes wrong when doing authentication: auth failed for user:canal
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:191) ~[classes/:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.connect(SimpleCanalConnector.java:115) ~[classes/:na]
	at com.alibaba.otter.canal.example.AbstractCanalClientTest.process(AbstractCanalClientTest.java:56) ~[classes/:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_202]
process error!com.alibaba.otter.canal.protocol.exception.CanalClientException: something goes wrong when doing authentication: auth failed for user:canal
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:191) ~[classes/:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.connect(SimpleCanalConnector.java:115) ~[classes/:na]
	at com.alibaba.otter.canal.example.AbstractCanalClientTest.process(AbstractCanalClientTest.java:56) ~[classes/:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_202]
  
![image](https://user-images.githubusercontent.com/37975654/96962908-54355580-153a-11eb-9168-8b5efc668c5f.png)

### Steps to reproduce
1、直接执行canal.adapter-1.1.4.bat 报错
2、执行客户端类： SimpleCanalClientTest 报错
 都是授权失败，就一个测试demo你授权什么？

### Actual behaviour

If there is an exception, please attach the exception trace:

```
 Ack ackBody = Ack.parseFrom(ack.getBody());
            if (ackBody.getErrorCode() > 0) {
                throw new CanalClientException("something goes wrong when doing authentication: "
                                               + ackBody.getErrorMessage());
            }
```

**Comment by 812406210** [comment]
+1,咋回事呢,我这边是搭建集群碰到的问题

**Comment by agapple** [comment]
服务端开启了auth认证，账号密码不对
