### ISSUE TITLE
canal.servermode = kafka 后客户端运行就报错,这是为啥?

### ISSUE THREAD

**Issue by niunan2019** [alibaba/canal#3111]
## Question
用IDEA执行客户端代码后,报错啊,配置改回TCP就正常了
Exception in thread "main" com.alibaba.otter.canal.protocol.exception.CanalClientException: java.net.ConnectException: Connection refused: connect
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:198)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.connect(SimpleCanalConnector.java:115)

**Comment by agapple** [comment]
报错很明显，连不上
