### ISSUE TITLE
一直连不上数据库

### ISSUE THREAD

**Issue by money461** [alibaba/canal#3128]
2020-10-29 20:01:20.557 [destination = instance_two , address = /192.168.137.1:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> begin to find start position, it will be long time for reset or first position
2020-10-29 20:01:20.557 [destination = instance_two , address = /192.168.137.1:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - prepare to find start position just show master status
2020-10-29 20:01:20.687 [destination = instance_two , address = /192.168.137.1:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address /192.168.137.1:3306 has an error, retrying. caused by 
com.alibaba.fastsql.sql.parser.ParserException: illegal sql expr : easyweb-security-oauth2.0, pos 25, line 1, column 24, token LITERAL_FLOAT
	at com.alibaba.fastsql.sql.SQLUtils.toSQLExpr(SQLUtils.java:258) ~[fastsql-2.0.0_preview_973.jar:2.0.0_preview_973]
	at com.alibaba.fastsql.sql.repository.Schema.setName(Schema.java:77) ~[fastsql-2.0.0_preview_973.jar:2.0.0_preview_973]
	at com.alibaba.fastsql.sql.repository.SchemaRepository.setDefaultSchema(SchemaRepository.java:130) ~[fastsql-2.0.0_preview_973.jar:2.0.0_preview_973]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta.apply(MemoryTableMeta.java:72) ~[canal.parse-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.dumpTableMeta(DatabaseTableMeta.java:236) ~[canal.parse-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:182) ~[canal.parse-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:137) ~[canal.parse-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:200) ~[canal.parse-1.1.5-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
2020-10-29 20:01:20.688 [destination = instance_two , address = /192.168.137.1:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:instance_two[com.alibaba.fastsql.sql.parser.ParserException: illegal sql expr : easyweb-security-oauth2.0, pos 25, line 1, column 24, token LITERAL_FLOAT
	at com.alibaba.fastsql.sql.SQLUtils.toSQLExpr(SQLUtils.java:258)
	at com.alibaba.fastsql.sql.repository.Schema.setName(Schema.java:77)
	at com.alibaba.fastsql.sql.repository.SchemaRepository.setDefaultSchema(SchemaRepository.java:130)
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta.apply(MemoryTableMeta.java:72)
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.dumpTableMeta(DatabaseTableMeta.java:236)
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:182)
	at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:137)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:200)
	at java.lang.Thread.run(Thread.java:748)
]
2020-10-29 20:01:32.008 [destination = instance_two , address = /192.168.137.1:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> begin to find start position, it will be long time for reset or first position
2020-10-29 20:01:32.008 [destination = instance_two , address = /192.168.137.1:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - prepare to find start position just show master status
2020-10-29 20:01:32.209 [destination = instance_two , address = /192.168.137.1:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address /192.168.137.1:3306 has an error, retrying. caused by 
com.alibaba.fastsql.sql.parser.ParserException: illegal sql expr : easyweb-security-oauth2.0, pos 25, line 1, column 24, token LITERAL_FLOAT
	at com.alibaba.fastsql.sql.SQLUtils.toSQLExpr(SQLUtils.java:258) ~[fastsql-2.0.0_preview_973.jar:2.0.0_preview_973]
	at com.alibaba.fastsql.sql.repository.Schema.setName(Schema.java:77) ~[fastsql-2.0.0_preview_973.jar:2.0.0_preview_973]
	at com.alibaba.fastsql.sql.repository.SchemaRepository.setDefaultSchema(SchemaRepository.java:130) ~[fastsql-2.0.0_preview_973.jar:2.0.0_preview_973]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta.apply(MemoryTableMeta.java:72) ~[canal.parse-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.dumpTableMeta(DatabaseTableMeta.java:236) ~[canal.parse-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:182) ~[canal.parse-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:137) ~[canal.parse-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:200) ~[canal.parse-1.1.5-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
2020-10-29 20:01:32.209 [destination = instance_two , address = /192.168.137.1:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:instance_two[com.alibaba.fastsql.sql.parser.ParserException: illegal sql expr : easyweb-security-oauth2.0, pos 25, line 1, column 24, token LITERAL_FLOAT
	at com.alibaba.fastsql.sql.SQLUtils.toSQLExpr(SQLUtils.java:258)
	at com.alibaba.fastsql.sql.repository.Schema.setName(Schema.java:77)
	at com.alibaba.fastsql.sql.repository.SchemaRepository.setDefaultSchema(SchemaRepository.java:130)
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta.apply(MemoryTableMeta.java:72)
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.dumpTableMeta(DatabaseTableMeta.java:236)
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:182)
	at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:137)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:200)
	at java.lang.Thread.run(Thread.java:748)
]

**Comment by money461** [comment]
数据库名称不能带小数点
