### ISSUE TITLE
ClientRunningMonitor    ConnectException

### ISSUE THREAD

**Issue by chenyurong** [alibaba/canal#314]
在CentOS7.2的服务器上，运行着运行着就发现抛出了ConnectException，提示连接异常。请问这个是哪部分出了问题？

```
[2017-06-02 17:01:03.295] [ERROR] [ZkClient-EventThread-20-10.10.10.81:2181,10.10.10.82:2181,10.10.10.33:2181] [c.a.o.c.client.impl.running.ClientRunningMonitor] >>> There is an error when execute initRunning method, with destination [db10101067002].
com.alibaba.otter.canal.protocol.exception.CanalClientException: java.net.ConnectException: Connection timed out
        at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:171) ~[canal.client-1.0.23.jar:na]
        at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.access$000(SimpleCanalConnector.java:48) ~[canal.client-1.0.23.jar:na]
        at com.alibaba.otter.canal.client.impl.SimpleCanalConnector$1.processActiveEnter(SimpleCanalConnector.java:396) ~[canal.client-1.0.23.jar:na]
        at com.alibaba.otter.canal.client.impl.running.ClientRunningMonitor.processActiveEnter(ClientRunningMonitor.java:207) ~[canal.client-1.0.23.jar:na]
        at com.alibaba.otter.canal.client.impl.running.ClientRunningMonitor.initRunning(ClientRunningMonitor.java:118) ~[canal.client-1.0.23.jar:na]
```

**Comment by agapple** [comment]
环境问题，自行排查
