### ISSUE TITLE
[type=mapper_parsing_exception, reason=failed to parse field [updateTime] of type [date]

### ISSUE THREAD

**Issue by jackznq** [alibaba/canal#3143]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal 1.1.4
* mysql 6.5
* es 6.7
### Issue Description
[type=mapper_parsing_exception, reason=failed to parse field [updateTime] of type [date]
### Steps to reproduce
插入数据
删除数据
更新数据

### Actual behaviour

If there is an exception, please attach the exception trace:

```
2020-11-03 17:12:45.940 [pool-5-thread-1] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - ES sync commit errorElasticsearchException[Elasticsearch exception [type=mapper_parsing_exception, reason=failed to parse field [updateTime] of type [date] in document with id '2020043011371113174']]; nested: ElasticsearchException[Elasticsearch exception [type=illegal_argument_exception, reason=Invalid format: "2020-11-03T17:10:32+08:00" is malformed at "+08:00"]];
java.lang.RuntimeException: ES sync commit errorElasticsearchException[Elasticsearch exception [type=mapper_parsing_exception, reason=failed to parse field [updateTime] of type [date] in document with id '2020043011371113174']]; nested: ElasticsearchException[Elasticsearch exception [type=illegal_argument_exception, reason=Invalid format: "2020-11-03T17:10:32+08:00" is malformed at "+08:00"]];
	at com.alibaba.otter.canal.client.adapter.es.support.ESTemplate.commit(ESTemplate.java:208)
	at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.commit(ESSyncService.java:852)
	at com.alibaba.otter.canal.client.adapter.es.ESAdapter.sync(ESAdapter.java:151)
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.batchSync(AbstractCanalAdapterWorker.java:201)
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$1(AbstractCanalAdapterWorker.java:62)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$2(AbstractCanalAdapterWorker.java:58)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-11-03 17:12:45.940 [Thread-5] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - Outer adapter sync```

**Comment by steamedBreadKiller** [comment]
you can change your elasticMapping，example：

before:
```
"sync_dt" : {
            "type" : "date",
            "format" : "yyyy-MM-dd HH:mm:ss || yyyy-MM-dd || yyyy/MM/dd HH:mm:ss|| yyyy/MM/dd|| epoch_millis"
}
```
after:
```
"sync_dt1" : {
            "type" : "date",
            "format" : "yyyy-MM-dd HH:mm:ss || yyyy-MM-dd || yyyy/MM/dd HH:mm:ss|| yyyy/MM/dd|| strict_date_optional_time|| epoch_millis"
}
```
add: || strict_date_optional_time

it is a bug.

**Comment by jackznq** [comment]
> you can change your elasticSearch mapping，example：
> 
> before:
> 
> ```
> "sync_dt" : {
>             "type" : "date",
>             "format" : "yyyy-MM-dd HH:mm:ss || yyyy-MM-dd || yyyy/MM/dd HH:mm:ss|| yyyy/MM/dd|| epoch_millis"
> }
> ```
> 
> after:
> 
> ```
> "sync_dt1" : {
>             "type" : "date",
>             "format" : "yyyy-MM-dd HH:mm:ss || yyyy-MM-dd || yyyy/MM/dd HH:mm:ss|| yyyy/MM/dd|| strict_date_optional_time|| epoch_millis"
> }
> ```
> 
> add: || strict_date_optional_time
> 
> it is a bug.

已经处理了  修改了canal的部分源码
