### ISSUE TITLE
org.h2.jdbc.JdbcSQLException: The database has been closed [90098-196]

### ISSUE THREAD

**Issue by cxy19891109** [alibaba/canal#3148]
org.h2.jdbc.JdbcSQLException: The database has been closed [90098-196]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
        at org.h2.message.DbException.get(DbException.java:179)
        at org.h2.message.DbException.get(DbException.java:155)
        at org.h2.message.DbException.get(DbException.java:144)
        at org.h2.engine.Database.checkPowerOff(Database.java:524)
        at org.h2.command.Command.executeQuery(Command.java:227)
        at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:200)
        at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:498)
        at com.ibatis.sqlmap.engine.execution.SqlExecutor.executeQuery(SqlExecutor.java:185)
        at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.sqlExecuteQuery(MappedStatement.java:221)
        at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryWithCallback(MappedStatement.java:189)
        at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryForObject(MappedStatement.java:120)
        at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForObject(SqlMapExecutorDelegate.java:518)
        at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForObject(SqlMapExecutorDelegate.java:493)
        at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.queryForObject(SqlMapSessionImpl.java:106)
        at org.springframework.orm.ibatis.SqlMapClientTemplate$1.doInSqlMapClient(SqlMapClientTemplate.java:273)
        at org.springframework.orm.ibatis.SqlMapClientTemplate.execute(SqlMapClientTemplate.java:203)
        at org.springframework.orm.ibatis.SqlMapClientTemplate.queryForObject(SqlMapClientTemplate.java:271)
        at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.dao.MetaSnapshotDAO.findByTimestamp(MetaSnapshotDAO.java:29)
        at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.buildMemFromSnapshot(DatabaseTableMeta.java:401)
        at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:172)
        at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:106)
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:192)
        at java.lang.Thread.run(Thread.java:748)

经常发生这个问题，请问是什么原因，而且项目中h2数据库是存在哪里的。

**Comment by nielizixiu** [comment]
我遇到过的异常就是日志把磁盘写满了  然后出现了各种奇怪的问题   不知道是不是这个原因

**Comment by cxy19891109** [comment]
您好，目前我们生产使用canal性能tps只能到达1000笔/s，始终提升不了，怀疑是配置哪里有问题，想请教怎么改配置，能提升到官方所测试的性能。谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/canal"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月22日(星期一) 下午5:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/canal] org.h2.jdbc.JdbcSQLException: The database has been closed [90098-196] (#3148)





 
我遇到过的异常就是日志把磁盘写满了  然后出现了各种奇怪的问题   不知道是不是这个原因
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cxy19891109** [comment]
canal.instance.filter.regex配置后导致tps大幅下滑，帮忙问问这个是什么原因




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "陈晓阳"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月26日(星期三) 上午10:58
***@***.***&gt;;

主题:&nbsp;回复： [alibaba/canal] org.h2.jdbc.JdbcSQLException: The database has been closed [90098-196] (#3148)



您好，目前我们生产使用canal性能tps只能到达1000笔/s，始终提升不了，怀疑是配置哪里有问题，想请教怎么改配置，能提升到官方所测试的性能。谢谢




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "alibaba/canal"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月22日(星期一) 下午5:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/canal] org.h2.jdbc.JdbcSQLException: The database has been closed [90098-196] (#3148)





 
我遇到过的异常就是日志把磁盘写满了  然后出现了各种奇怪的问题   不知道是不是这个原因
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lc1993929** [comment]
> org.h2.jdbc.JdbcSQLException: The database has been closed [90098-196] at org.h2.message.DbException.getJdbcSQLException(DbException.java:345) at org.h2.message.DbException.get(DbException.java:179) at org.h2.message.DbException.get(DbException.java:155) at org.h2.message.DbException.get(DbException.java:144) at org.h2.engine.Database.checkPowerOff(Database.java:524) at org.h2.command.Command.executeQuery(Command.java:227) at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:200) at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:498) at com.ibatis.sqlmap.engine.execution.SqlExecutor.executeQuery(SqlExecutor.java:185) at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.sqlExecuteQuery(MappedStatement.java:221) at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryWithCallback(MappedStatement.java:189) at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryForObject(MappedStatement.java:120) at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForObject(SqlMapExecutorDelegate.java:518) at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForObject(SqlMapExecutorDelegate.java:493) at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.queryForObject(SqlMapSessionImpl.java:106) at org.springframework.orm.ibatis.SqlMapClientTemplate$1.doInSqlMapClient(SqlMapClientTemplate.java:273) at org.springframework.orm.ibatis.SqlMapClientTemplate.execute(SqlMapClientTemplate.java:203) at org.springframework.orm.ibatis.SqlMapClientTemplate.queryForObject(SqlMapClientTemplate.java:271) at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.dao.MetaSnapshotDAO.findByTimestamp(MetaSnapshotDAO.java:29) at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.buildMemFromSnapshot(DatabaseTableMeta.java:401) at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:172) at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:106) at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:192) at java.lang.Thread.run(Thread.java:748)
> 
> 经常发生这个问题，请问是什么原因，而且项目中h2数据库是存在哪里的。

同样遇到这样的问题，同问
