### ISSUE TITLE
canal 添加自定义拦截器报类型转换异常

### ISSUE THREAD

**Issue by yansheng105** [alibaba/canal#3157]
canal 版本 1.1.5-alpha-2

错误描述：在kafka connector中添加了自定义消费者拦截器，启动适配器报错：
```
ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - process error!org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
```
经过debug 发现具体错误如下：

错误日志：
```
org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:793)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:644)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:624)
	at com.alibaba.otter.canal.connector.kafka.consumer.CanalKafkaConsumer.connect(CanalKafkaConsumer.java:67)
	at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.process(AdapterProcessor.java:190)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: class com.alibaba.otter.canal.connector.kafka.consumer.CustomConsumerInterceptor
	at java.lang.Class.asSubclass(Class.java:3404)
	at org.apache.kafka.common.utils.Utils.loadClass(Utils.java:322)
	at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:311)
	at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstances(AbstractConfig.java:355)
	at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstances(AbstractConfig.java:332)
	at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstances(AbstractConfig.java:319)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:684)
	... 5 more
```

错误发生位置：
org.apache.kafka.common.utils.Utils
```
    public static <T> Class<? extends T> loadClass(String klass, Class<T> base) throws ClassNotFoundException {
        return Class.forName(klass, true, getContextOrKafkaClassLoader()).asSubclass(base);
    }
```

相关源码：
CanalKafkaConsumer.java
```
    @Override
    public void connect() {
        if (this.flatMessage) {
            kafkaProperties.put("value.deserializer", StringDeserializer.class);
            // 添加自定义拦截器
            List<String> interceptors = new ArrayList<>();
            interceptors.add("com.alibaba.otter.canal.connector.kafka.consumer.CustomConsumerInterceptor");
            kafkaProperties.put(ConsumerConfig.INTERCEPTOR_CLASSES_CONFIG, interceptors);
            this.kafkaConsumer = new KafkaConsumer<String, String>(kafkaProperties);
        } else {
            kafkaProperties.put("value.deserializer", KafkaMessageDeserializer.class);
            this.kafkaConsumer = new KafkaConsumer<String, Message>(kafkaProperties);
        }
        kafkaConsumer.subscribe(Collections.singletonList(topic));
    }
```
CustomConsumerInterceptor.java
```
public class CustomConsumerInterceptor implements org.apache.kafka.clients.consumer.ConsumerInterceptor {

    private static final SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    private static final SimpleDateFormat sdf2 = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss");

    @Override
    public ConsumerRecords onConsume(ConsumerRecords records) {
        List<ConsumerRecord<String, String>> filterRecords = new ArrayList<>();
        Map<TopicPartition, List<ConsumerRecord<String, String>>> newRecords = new HashMap<>();
        Set<TopicPartition> partitions = records.partitions();
        for (TopicPartition tp : partitions) {
            List<ConsumerRecord<String, String>> consumerRecords = records.records(tp);
            for (ConsumerRecord<String, String> record : consumerRecords) {
                filterRecords.add(convertMessage(record));
            }
            if (filterRecords.size() > 0) {
                newRecords.put(tp, filterRecords);
            }
        }
        return new ConsumerRecords<>(newRecords);
    }
```

**Comment by yansheng105** [comment]
@zhuzhaoyuan @zhmz1326 @frew @JacksonTian 各位大佬求解
