### ISSUE TITLE
listener timeout after waiting for [30000] ms

### ISSUE THREAD

**Issue by swordhgh** [alibaba/canal#3162]
同步es
隔段时间会报ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - java.io.IOException: listener timeout after waiting for [30000] ms。

canal-adapter的application.yml 中的timeout已经改为60000 了，但好像无效？

大家有没有遇到过？

**Comment by swordhgh** [comment]
补充一下错误信息：


2020-11-07 16:43:29.357 [pool-13-thread-1] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - java.io.IOException: listener timeout after waiting for [30000] ms
java.lang.RuntimeException: java.io.IOException: listener timeout after waiting for [30000] ms
	at com.alibaba.otter.canal.client.adapter.es.support.ESConnection$ESBulkRequest.bulk(ESConnection.java:422)
	at com.alibaba.otter.canal.client.adapter.es.support.ESTemplate.commit(ESTemplate.java:198)
	at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.commit(ESSyncService.java:852)
	at com.alibaba.otter.canal.client.adapter.es.ESAdapter.sync(ESAdapter.java:151)
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.batchSync(AbstractCanalAdapterWorker.java:201)
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$1(AbstractCanalAdapterWorker.java:62)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$2(AbstractCanalAdapterWorker.java:58)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: listener timeout after waiting for [30000] ms
	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:899)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:227)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1256)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1240)
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1223)
	at org.elasticsearch.client.RestHighLevelClient.bulk(RestHighLevelClient.java:340)
	at com.alibaba.otter.canal.client.adapter.es.support.ESConnection$ESBulkRequest.bulk(ESConnection.java:420)
	... 11 common frames omitted
2020-11-07 16:43:29.358 [Thread-14] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - Outer adapter sync failed!  Error sync and rollback, execute times: 1

**Comment by swordhgh** [comment]
修改源码，没有效果
是哪里还没修改到吗？
![image](https://user-images.githubusercontent.com/25214688/98618665-a1883400-233c-11eb-8c9a-3829ddfb505e.png)

**Comment by swordhgh** [comment]
确认了，是es客户端版本问题，升级到6.8.2就好了
