### ISSUE TITLE
canal example报错：something goes wrong when getWithoutAck data from server:null

### ISSUE THREAD

**Issue by xuliangyong** [alibaba/canal#318]
canal example 启动了两台,相当于主从把 一台挂了会自动切换到另一台 运行中出现如下异常
2017-06-08 02:39:42.964 [Thread-3] WARN  c.alibaba.otter.canal.client.impl.ClusterCanalConnector - something goes wrong when getWithoutAck data from server:null
com.alibaba.otter.canal.protocol.exception.CanalClientException: java.nio.channels.AsynchronousCloseException
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.getWithoutAck(SimpleCanalConnector.java:281)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.getWithoutAck(SimpleCanalConnector.java:252)
	at com.alibaba.otter.canal.client.impl.ClusterCanalConnector.getWithoutAck(ClusterCanalConnector.java:180)
	at com.alibaba.otter.canal.example.AbstractCanalClientTest.process(AbstractCanalClientTest.java:131)
	at com.alibaba.otter.canal.example.AbstractCanalClientTest$2.run(AbstractCanalClientTest.java:98)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.channels.AsynchronousCloseException
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:205)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:407)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.read(SimpleCanalConnector.java:376)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.readNextPacket(SimpleCanalConnector.java:366)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.receiveMessages(SimpleCanalConnector.java:286)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.getWithoutAck(SimpleCanalConnector.java:279)
	... 5 more

2017-06-08 02:39:43.088 [ZkClient-EventThread-17-10.1.102.181:3001] ERROR c.a.otter.canal.client.impl.running.ClientRunningMonitor - There is an error when execute initRunning method, with destination [example].
com.alibaba.otter.canal.protocol.exception.CanalClientException: java.nio.channels.ClosedChannelException
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:171) ~[canal.client-1.0.24.jar:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.access$000(SimpleCanalConnector.java:48) ~[canal.client-1.0.24.jar:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector$1.processActiveEnter(SimpleCanalConnector.java:396) ~[canal.client-1.0.24.jar:na]
	at com.alibaba.otter.canal.client.impl.running.ClientRunningMonitor.processActiveEnter(ClientRunningMonitor.java:207) ~[canal.client-1.0.24.jar:na]
	at com.alibaba.otter.canal.client.impl.running.ClientRunningMonitor.initRunning(ClientRunningMonitor.java:118) ~[canal.client-1.0.24.jar:na]
	at com.alibaba.otter.canal.client.impl.running.ClientRunningMonitor$1.handleDataDeleted(ClientRunningMonitor.java:71) [canal.client-1.0.24.jar:na]
	at org.I0Itec.zkclient.ZkClient$6.run(ZkClient.java:549) [zkclient-0.1.jar:na]
	at org.I0Itec.zkclient.ZkEventThread.run(ZkEventThread.java:71) [zkclient-0.1.jar:na]
Caused by: java.nio.channels.ClosedChannelException: null
	at sun.nio.ch.SocketChannelImpl.ensureReadOpen(SocketChannelImpl.java:257) ~[na:1.8.0_131]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:300) ~[na:1.8.0_131]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.read(SimpleCanalConnector.java:376) ~[canal.client-1.0.24.jar:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.readNextPacket(SimpleCanalConnector.java:369) ~[canal.client-1.0.24.jar:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:133) ~[canal.client-1.0.24.jar:na]
	... 7 common frames omitted
2017-06-08 02:39:43.114 [ZkClient-EventThread-17-10.1.102.181:3001] WARN  c.a.otter.canal.client.impl.running.ClientRunningMonitor - canal is not run any in node
2017-06-08 02:39:48.103 [Thread-3] INFO  c.alibaba.otter.canal.client.impl.ClusterCanalConnector - restart the connector for next round retry.
2017-06-08 11:34:56.529 [main-SendThread(10.1.102.181:3001)] INFO  org.apache.zookeeper.ClientCnxn - Unable to read additional data from server sessionid 0x15c83dad6dc0000, likely server has closed socket, closing socket connection and attempting reconnect
2017-06-08 11:34:59.029 [main-SendThread(10.1.102.181:3001)] INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server 10.1.102.181/10.1.102.181:3001. Will not attempt to authenticate using SASL (unknown error)
2017-06-08 11:34:59.310 [main-SendThread(10.1.102.181:3001)] INFO  org.apache.zookeeper.ClientCnxn - Socket connection established to 10.1.102.181/10.1.102.181:3001, initiating session
2017-06-08 11:35:00.488 [main-SendThread(10.1.102.181:3001)] WARN  org.apache.zookeeper.ClientCnxn - Session 0x15c83dad6dc0000 for server 10.1.102.181/10.1.102.181:3001, unexpected error, closing socket connection and attempting reconnect
java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[na:1.8.0_131]
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47) ~[na:1.8.0_131]
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93) ~[na:1.8.0_131]
	at sun.nio.ch.IOUtil.write(IOUtil.java:65) ~[na:1.8.0_131]
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471) ~[na:1.8.0_131]
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:117) ~[zookeeper-3.4.5.jar:3.4.5-1392090]
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:355) ~[zookeeper-3.4.5.jar:3.4.5-1392090]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1068) ~[zookeeper-3.4.5.jar:3.4.5-1392090]

**Comment by alexandnpu** [comment]
这个我也在1.0.24中发现了。在执行过程中，把canal server停掉，然后canal client就一直会有这个问题，把canal server重启启动，canal client还是在那里一直报错，不会选择新的server重连，具体的问题我也还在调试中。

@agapple

**Comment by alexandnpu** [comment]
调试了一下，是因为自己的用法导致的，我把我创建的cluster client放到了一个pool里面，注意下面的code

```       
            CanalConnector connector = CanalConnectors.newClusterConnector(connectionPath, destination, "", "");
            connector.connect();
            connector.subscribe();
```

这里会抛出CanalClientException， 这是个runtime exception
所以当`connect`抛出异常的时候，记得要捕获一下，然后`disconnect`掉。

```
        try {
            connector.connect();
            connector.subscribe();
        } catch (Throwable t) {
            logger.error("failed to connect to canal server", t);
            connector.disconnect();
            throw t;
        }
```

@xuliangyong ， 不知道你的是不是跟我一样的问题，希望对你有帮助。

**Comment by stone-cheng** [comment]
@alexandnpu, 我也碰到过这种情况，而且检查TCP连接时，发现很多事CLOSE_WAIT状态的。
最后也是通过catch异常然后disconnect解决的。
