### ISSUE TITLE
1.15版本启动admin 启动 instance 不成功  后台报错没有对应的日志文件

### ISSUE THREAD

**Issue by JavaTop2** [alibaba/canal#3202]

**Comment by Mrshengjie** [comment]
1.1.4也一样报这个错误：
java.io.FileNotFoundException: ../logs/instance1/instance1.log (No such file or directory)
	at java.io.RandomAccessFile.open0(Native Method) ~[na:1.8.0_252]
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316) ~[na:1.8.0_252]
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243) ~[na:1.8.0_252]
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:124) ~[na:1.8.0_252]
	at com.alibaba.otter.canal.common.utils.FileUtils.readFileFromOffset(FileUtils.java:22) [canal.common-1.1.4.jar:na]
	at com.alibaba.otter.canal.common.utils.FileUtils.readFileFromOffset(FileUtils.java:15) [canal.common-1.1.4.jar:na]
	at com.alibaba.otter.canal.deployer.admin.CanalAdminController.instanceLog(CanalAdminController.java:218) [canal.deployer-1.1.4.jar:na]
	at com.alibaba.otter.canal.admin.handler.SessionHandler.messageReceived(SessionHandler.java:116) [canal.server-1.1.4.jar:na]
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:100) [netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:545) [netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:754) [netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:154) [netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:100) [netty-3.2.2.Final.jar:na]
	at org.jboss.netty.handler.timeout.IdleStateAwareChannelHandler.handleUpstream(IdleStateAwareChannelHandler.java:48) [netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:545) [netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:754) [netty-3.2.2.Final.jar:na]
	at org.jboss.netty.handler.timeout.IdleStateHandler.messageReceived(IdleStateHandler.java:276) [netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:80) [netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:545) [netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:754) [netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:302) [netty-3.2.2.Final.jar:na]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.unfoldAndfireMessageReceived(ReplayingDecoder.java:526) [netty-3.2.2.Final.jar:na]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:507) [netty-3.2.2.Final.jar:na]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:444) [netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:80) [netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:545) [netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:540) [netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:274) [netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:261) [netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:350) [netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:281) [netty-3.2.2.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:201) [netty-3.2.2.Final.jar:na]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.2.2.Final.jar:na]
	at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46) [netty-3.2.2.Final.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_252]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_252]

**Comment by agapple** [comment]
看报错应该是instance还未启动，没有产生日志文件

**Comment by nielizixiu** [comment]
尝试启动instance  提示启动成功，但是instance无日志，刷新页面状态仍然为停止

**Comment by happyi** [comment]
1.1.5 同样的错误

**Comment by happyi** [comment]
解决方案   sh startup.sh local   一定要带上这个 local

**Comment by cnn007** [comment]
使用docker 也是这个问题，怎样解决。
sh run.sh -e canal.admin.manager=ecsip:8089 \
         -e canal.admin.port=11110 \
         -e canal.port=11121 \
         -e canal.admin.user=admin \
         -e canal.admin.passwd=4ACFE3202A5FF5CF467898FC58AAB1D615029441

**Comment by ColinChenX** [comment]
1.1.5版本也有这个问题。老子在logs目录下面自己手动创建文件结果还是启动不了，真是蛋疼
