### ISSUE TITLE
How to use SSL mode connect to MySQL

### ISSUE THREAD

**Issue by yekangming** [alibaba/canal#3226]
## Question

I lookup the document, but I didn't follow the relevant SSL settings. 
Anyone can help me, Thanks.

in instance.properties
canal.instance.master.address=[databaseAddress:Port] // No other configuration was found to set SSL mode

`2020-12-05 03:30:47.469 [destination = xxx, address = xxx/1.1.1.1:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address xxx/1.1.1.1:3306 has an error, retrying. caused by 
com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: connect xxx/1.1.1.1:3306 failure
Caused by: java.io.IOException: connect xxx/1.1.1.1:3306 failure
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:83) ~[canal.parse.driver-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.connect(MysqlConnection.java:89) ~[canal.parse-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.preDump(MysqlEventParser.java:86) ~[canal.parse-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:183) ~[canal.parse-1.1.5-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_271]
Caused by: java.io.IOException: Error When doing Client Authentication:ErrorPacket [errorNumber=9002, fieldCount=-1, message=SSL connection is required. Please specify SSL options and retry., sqlState=28000, sqlStateMarker=#]
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.negotiate(MysqlConnector.java:271) ~[canal.parse.driver-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:80) ~[canal.parse.driver-1.1.5-SNAPSHOT.jar:na]
	... 4 common frames omitted
`

**Comment by yekangming** [comment]
@agapple

**Comment by zuyanlong** [comment]
I met the same problem, could you please give a reply? @yekangming @frew @zhuzhaoyuan @zhmz1326 @JacksonTian
