### ISSUE TITLE
PositionNotFoundException: can't find start position for example

### ISSUE THREAD

**Issue by seqwait** [alibaba/canal#3243]
1. 按照wiki运行canal 但是报错
2. 环境(按照网上方法移除meta.dat 重启无效)
```
mysql>  show master status;
+------------------+----------+--------------+------------------+-------------------+
| File             | Position | Binlog_Do_DB | Binlog_Ignore_DB | Executed_Gtid_Set |
+------------------+----------+--------------+------------------+-------------------+
| mysql-bin.000001 |      427 |              |                  |                   |
+------------------+----------+--------------+------------------+-------------------+
1 row in set (0.30 sec)
```
> /example/instance.properties
 ```
# username/password
canal.instance.master.address=127.0.0.1:3306
canal.instance.dbUsername=canal
canal.instance.dbPassword=123456
canal.instance.connectionCharset = UTF-8
# enable druid Decrypt database password
canal.instance.enableDruid=false
```
> /example/example.log
```
2020-12-12 22:24:19.294 [destination = example , address = /127.0.0.1:3306 , EventParser] INFO  c.a.otter.canal.parse.inbound.mysql.MysqlConnection - COM_BINLOG_DUMP with position:BinlogDumpCommandPacket[binlogPosition=4,slaveServerId=1791873550,binlogFileName=mysql-bin.000001,command=18]
2020-12-12 22:24:19.297 [destination = example , address = /127.0.0.1:3306 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - I/O error while reading from client socket
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Misconfigured master - master server_id is 0
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102) ~[canal.parse-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.seek(MysqlConnection.java:144) [canal.parse-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findAsPerTimestampInSpecificLogFile(MysqlEventParser.java:760) [canal.parse-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findEndPositionWithMasterIdAndTimestamp(MysqlEventParser.java:395) [canal.parse-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPositionInternal(MysqlEventParser.java:450) [canal.parse-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPosition(MysqlEventParser.java:369) [canal.parse-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:194) [canal.parse-1.1.5-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_272]
2020-12-12 22:24:19.297 [destination = example , address = /127.0.0.1:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ERROR ## findAsPerTimestampInSpecificLogFile has an error
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Misconfigured master - master server_id is 0
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102) ~[canal.parse-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.seek(MysqlConnection.java:144) ~[canal.parse-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findAsPerTimestampInSpecificLogFile(MysqlEventParser.java:760) [canal.parse-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findEndPositionWithMasterIdAndTimestamp(MysqlEventParser.java:395) [canal.parse-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPositionInternal(MysqlEventParser.java:450) [canal.parse-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPosition(MysqlEventParser.java:369) [canal.parse-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:194) [canal.parse-1.1.5-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_272]
2020-12-12 22:24:19.298 [destination = example , address = /127.0.0.1:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address /127.0.0.1:3306 has an error, retrying. caused by

```

**Comment by qingtianbuyu** [comment]
啥问题啊？我也是这样

**Comment by IceFoxs** [comment]
在my.cnf设置
[mysqld]
#server_id设置为数字
server_id=1
然后删除canal实例下meta.dat 重新启动canal

**Comment by yiuwacheng** [comment]
> 在my.cnf设置
> [mysqld]
> #server_id设置为数字
> server_id=1
> 然后删除canal实例下meta.dat 重新启动canal

🐂🍺，改成1解决了，我一开始设置0老报这个错，不知道为什么得是1。

**Comment by IceFoxs** [comment]
> > 在my.cnf设置
> > [mysqld]
> > #server_id设置为数字
> > server_id=1
> > 然后删除canal实例下meta.dat 重新启动canal
> 
> 🐂🍺，改成1解决了，我一开始设置0老报这个错，不知道为什么得是1。
可以看一下这个网址
[mysql server_id](https://dev.mysql.com/doc/refman/8.0/en/replication-options.html#sysvar_server_id)


![image](https://user-images.githubusercontent.com/26451038/119294855-00cde600-bc88-11eb-8788-fd2e5a8ba901.png)

**Comment by douya0808** [comment]
今晚同样踩了 server_id 不能设置为 0 的雷，配置 MySQL 集群时设置 server_id = 0 能跑起来，换 Canal 会有问题，具体原因见楼上

**Comment by ahululu** [comment]
如果是云数据呢，怎么改。。比如阿里云的RDS，aws的RDS，或者google的CloudSQL，今天就碰到CloudSQL报这个错。
