### ISSUE TITLE
canal-adapter 无法找到索引（Not found the mapping info of index）索引已经存在，无子文档

### ISSUE THREAD

**Issue by JacksonCda** [alibaba/canal#3259]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues)＃1851 of this repository and believe that this is not a useful.

### environment

* canal version 1.1.4
* canal-adapter version 1.1.4
* mysql version 5.6

### Issue Description
The Mapping is exists!!
![image](https://user-images.githubusercontent.com/42628796/102563622-a77bec80-4114-11eb-912b-9e3b82630a46.png)
![image](https://user-images.githubusercontent.com/42628796/102563675-c7abab80-4114-11eb-8ec7-c42636cf238b.png)

config of canal-adapter es/test_keyword_db.yml
![image](https://user-images.githubusercontent.com/42628796/102563890-4acd0180-4115-11eb-905a-7a5412de4f95.png)

### Steps to reproduce
MYSQL Binlog file successfully read
### Expected behaviour
successful SyncES
### Actual behaviour
![image](https://user-images.githubusercontent.com/42628796/102563832-26712500-4115-11eb-9c3b-fd235399c3d9.png)

If there is an exception, please attach the exception trace:

```

**Comment by JacksonCda** [comment]
ERROR c.a.otter.canal.client.adapter.es.service.ESSyncService - sync error, es index: test_keyword_db, DML : Dml{destination='test', database='canal_manager', table='test', type='UPDATE', es=1608236866000, ts=1608236866208, sql='', data=[{id=8, title=54841289qqqasdasd, product_description=}], old=[{title=54841289qqq}]}
2020-12-18 04:27:46.233 [pool-3-thread-1] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - java.lang.IllegalArgumentException: Not found the mapping info of index: test_keyword_db
java.lang.RuntimeException: java.lang.IllegalArgumentException: Not found the mapping info of index: test_keyword_db
	at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.sync(ESSyncService.java:110)
	at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.sync(ESSyncService.java:58)
	at com.alibaba.otter.canal.client.adapter.es.ESAdapter.sync(ESAdapter.java:169)
	at com.alibaba.otter.canal.client.adapter.es.ESAdapter.sync(ESAdapter.java:148)
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.batchSync(AbstractCanalAdapterWorker.java:201)
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$1(AbstractCanalAdapterWorker.java:62)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at com.alibaba.otter.canal.adapter.launcher.loader.AbstractCanalAdapterWorker.lambda$null$2(AbstractCanalAdapterWorker.java:58)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Not found the mapping info of index: test_keyword_db
	at com.alibaba.otter.canal.client.adapter.es.support.ESTemplate.getEsType(ESTemplate.java:497)
	at com.alibaba.otter.canal.client.adapter.es.support.ESTemplate.getValFromData(ESTemplate.java:345)
	at com.alibaba.otter.canal.client.adapter.es.support.ESTemplate.getESDataFromDmlData(ESTemplate.java:410)
	at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.singleTableSimpleFiledUpdate(ESSyncService.java:793)
	at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.update(ESSyncService.java:206)
	at com.alibaba.otter.canal.client.adapter.es.service.ESSyncService.sync(ESSyncService.java:95)
	... 11 common frames omitted

**Comment by itfeiyue** [comment]
这个问题解决了吗？

**Comment by clannad2000** [comment]
使用索引别名时会出现这个问题。
例如:
PUT tyredb-s_garage_v1
{
  "aliases": {
    "tyredb-s_garage": {
      "is_write_index": true
    }
  }
...

**Comment by JacksonCda** [comment]
还没解决，我并没有使用别名

**Comment by JacksonCda** [comment]
> 这个问题解决了吗？

还没有解决

**Comment by JacksonCda** [comment]
> 使用索引别名时会出现这个问题。
> 例如:
> PUT tyredb-s_garage_v1
> {
> "aliases": {
> "tyredb-s_garage": {
> "is_write_index": true
> }
> }
> ...

我并没有使用别名

**Comment by JacksonCda** [comment]
![image](https://user-images.githubusercontent.com/42628796/103768866-3ae27680-505e-11eb-92db-c2fd23d33960.png)
现在没报错了，但是也没更新数据

**Comment by JacksonCda** [comment]
之前看到1.1.4支持ES 6.X.X版本以上，以为也支持ES 7，昨天看到一篇文章说只有1.1.5才支持，想着会不会是版本问题，于是昨天又换了canal-deployer为1.1.5版本，但是依然不行，没报错，但是也没更新ES数据

**Comment by GumpDing** [comment]
碰到和你一样的问题,显先是报索引不存在,后来把字段改成大写,不报错了,日志也展示能读到新增数据,但是es中没数据

**Comment by lcb1208** [comment]
感觉upsert没起作用吧

**Comment by Jenfong** [comment]
1.1.5 adapter 配置es7报错找不到适配器，换成1.1.4的adapter配置为出现一样的现象。
elasticsearch-7.13.3-1.x86_64
java version "1.8.0_211

> 之前看到1.1.4支持ES 6.X.X版本以上，以为也支持ES 7，昨天看到一篇文章说只有1.1.5才支持，想着会不会是版本问题，于是昨天又换了canal-deployer为1.1.5版本，但是依然不行，没报错，但是也没更新ES数据

**Comment by pruidong** [comment]
问题解决了吗?我也遇到了这个问题,调了一天了一直提示这个错误...

**Comment by zsdxhwzn** [comment]
我这是遇到了Not found the mapping info of index: XXX这个问题
canal版本：1.1.4 
es版本：7.15.2

把ESConnection类的第137行注释调的代码放开
源代码
// try {
// response = restHighLevelClient
// .indices()
// .getMapping(request, RequestOptions.DEFAULT);
// // 6.4以下版本直接使用该接口会报错
// } catch (Exception e) {
// logger.warn("Low ElasticSearch version for getMapping");
response = RestHighLevelClientExt.getMapping(restHighLevelClient, request, RequestOptions.DEFAULT);
更改后
try {
 response = restHighLevelClient
 .indices()
 .getMapping(request, RequestOptions.DEFAULT);
 // 6.4以下版本直接使用该接口会报错
 } catch (Exception e) {
 logger.warn("Low ElasticSearch version for getMapping");
// response = RestHighLevelClientExt.getMapping(restHighLevelClient, request, RequestOptions.DEFAULT);

同时下面147行IOException改为Exception

以上操作完后再次install，重新运行，问题得以解决

**Comment by zsdxhwzn** [comment]
> 问题解决了吗？我也遇到了这个问题，调了一天一直提示这个错误...

可以试一下我的解决方案

**Comment by pruidong** [comment]
> > 问题解决了吗？我也遇到了这个问题，调了一天一直提示这个错误...
> 
> 可以试一下我的解决方案

解决了，我遇到的是连接ES失败，所以一直提示索引不存在.处理了连接问题之后就可以了.

**Comment by Pupupuuuu** [comment]
> > > 问题解决了吗？我也遇到了这个问题，调了一天一直提示这个错误...
> > 
> > 
> > 可以试一下我的解决方案
> 
> 解决了，我遇到的是连接ES失败，所以一直提示索引不存在.处理了连接问题之后就可以了.

怎么解决的连接问题?
