### ISSUE TITLE
Socket连接一直报这个Timeout occurred, failed to read total 4 bytes in 25000 milliseconds, actual read only 0 bytes

### ISSUE THREAD

**Issue by wuhan-chenke** [alibaba/canal#3261]
有办法解决吗
2020-12-18 15:29:13.107 [destination = td240 , address = /10.50.30.240:3306 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - Socket timeout expired, closing connection
java.net.SocketTimeoutException: Timeout occurred, failed to read total 4 bytes in 25000 milliseconds, actual read only 0 bytes
	at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:127) ~[canal.parse.driver-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:174) ~[canal.parse-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:77) ~[canal.parse-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:235) [canal.parse-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:265) [canal.parse-1.1.5-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
2020-12-18 15:29:13.108 [destination = td240 , address = /10.50.30.240:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address 10.50.30.240/10.50.30.240:3306 has an error, retrying. caused by 
java.net.SocketTimeoutException: Timeout occurred, failed to read total 4 bytes in 25000 milliseconds, actual read only 0 bytes
	at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:127) ~[canal.parse.driver-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:174) ~[canal.parse-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:77) ~[canal.parse-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:235) ~[canal.parse-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:265) ~[canal.parse-1.1.5-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
2020-12-18 15:29:13.108 [destination = td240 , address = /10.50.30.240:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:td240[java.net.SocketTimeoutException: Timeout occurred, failed to read total 4 bytes in 25000 milliseconds, actual read only 0 bytes
	at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:127)
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:174)
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:77)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:235)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:265)
	at java.lang.Thread.run(Thread.java:745)

**Comment by wuhan-chenke** [comment]
最新版本canal.deployer-1.1.5-SNAPSHOT

**Comment by wuhan-chenke** [comment]
有点坑，找到原因了，因为没有产生binlog日志导致。解决办法只能开启心跳检测
canal.instance.detecting.enable = true
canal.instance.detecting.sql = insert into xdual values(1,now()) on duplicate key update x=now()

**Comment by 710961349** [comment]
还是不行。。。

**Comment by wuhan-chenke** [comment]
> 还是不行。。。

有可能是连接超时了，把域名解析去掉
在my.cnf文件的mysqld下加入
skip-name-resolve

**Comment by yonger1516** [comment]
有更新吗 ？ 不知道这个错误是否会导致消息丢失

**Comment by 710961349** [comment]
我这边是配置问题。重新把mysql重启一下就连接到了

**Comment by r13ljj** [comment]
> 我这边是配置问题。重新把mysql重启一下就连接到了

我连接RDS5.7也碰到这个问题，能详细说下是什么配置原因吗

**Comment by 710961349** [comment]
> > 我这边是配置问题。重新把mysql重启一下就连接到了
> 
> 我连接RDS5.7也碰到这个问题，能详细说下是什么配置原因吗

我是把数据库的配置字符集和排序规则改了下就可以了utf8    utf8_general_ci

**Comment by r13ljj** [comment]
> > > 我这边是配置问题。重新把mysql重启一下就连接到了
> > 
> > 
> > 我连接RDS5.7也碰到这个问题，能详细说下是什么配置原因吗
> 
> 我是把数据库的配置字符集和排序规则改了下就可以了utf8 utf8_general_ci

我的问题也找到了，是ECS到RDS的网络问题

**Comment by shyandsy** [comment]
链接腾讯云rds，一样的问题

**Comment by CLX4399** [comment]
请问下~这个超时的配置是在哪里配置的呢，没有找到~
