### ISSUE TITLE
canal client-adapter 1.1.4 启动 初始化数据库报错

### ISSUE THREAD

**Issue by ccubec** [alibaba/canal#3265]
## Question

`com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)`

**Comment by ccubec** [comment]
1.1.4 不支持mysql8 建议使用1.1.5
