### ISSUE TITLE
canal1.10偶尔发生一次java.net.SocketException: Connection reset后持续两个多小时没有拉新数据，直到自动恢复，但是跳过了中间没有拉数的时间段的记录，从最新的地方开始拉

### ISSUE THREAD

**Issue by xiaotaitai** [alibaba/canal#3273]
## Question

当时几个小时确实发生过几次java.net.SocketException: Connection reset的情况，但是其他情况都自动很快恢复拉数，没有丢数，但是一次就发生异常后就卡在那里，没有拉新数据，网络抖动但是那个库其他canal都正常拉数，直到恢复后从最新的位置开始拉，而不是之前卡住的地方开始拉，请问为什么会卡住，又为什么会跳过中间的记录。异常是下面这个
:java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:209)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:108)
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:174)
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:85)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:213)
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:249)
        at java.lang.Thread.run(Thread.java:745)

**Comment by parashorea** [comment]
也遇到了
