### ISSUE TITLE
kafka 连接超时

### ISSUE THREAD

**Issue by lixiongjie** [alibaba/canal#3286]
## Question

大大好，
    我们公司的kafka版本是0.9.0（kafka_2.11-0.9.0-kafka-2.0.2-sources.jar），我用canal连接的时候报超时。但是换了高版本的kafka发现是可以连的，canal对kafka有版本限制吗？如果有限制我0.9.0的该用哪种版本的canal呢？

2020-12-31 09:18:39.388 [pool-6-thread-1] ERROR c.a.o.canal.connector.kafka.producer.CanalKafkaProducer - java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.
java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.
	at com.alibaba.otter.canal.connector.kafka.producer.CanalKafkaProducer.send(CanalKafkaProducer.java:183) ~[na:na]
	at com.alibaba.otter.canal.server.CanalMQStarter.worker(CanalMQStarter.java:185) [canal.server-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.server.CanalMQStarter.access$500(CanalMQStarter.java:25) [canal.server-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.server.CanalMQStarter$CanalMQRunnable.run(CanalMQStarter.java:227) [canal.server-1.1.5-SNAPSHOT.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_221]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_221]
Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.
	at org.apache.kafka.clients.producer.KafkaProducer$FutureFailure.<init>(KafkaProducer.java:1150) ~[kafka-clients-0.9.0.1.jar:na]
	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:846) ~[kafka-clients-0.9.0.1.jar:na]
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:784) ~[kafka-clients-0.9.0.1.jar:na]
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:671) ~[kafka-clients-0.9.0.1.jar:na]
	at com.alibaba.otter.canal.connector.kafka.producer.CanalKafkaProducer.produce(CanalKafkaProducer.java:267) ~[na:na]
	at com.alibaba.otter.canal.connector.kafka.producer.CanalKafkaProducer.send(CanalKafkaProducer.java:260) ~[na:na]
	at com.alibaba.otter.canal.connector.kafka.producer.CanalKafkaProducer.lambda$send$0(CanalKafkaProducer.java:155) ~[na:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_221]
	... 3 common frames omitted
Caused by: org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.

**Comment by wingerx** [comment]
从问题上猜测是Canal 依赖的kafka client 端对Kafka Server 的版本有要求

**Comment by lixiongjie** [comment]
> 从问题上猜测是Canal 依赖的kafka client 端对Kafka Server 的版本有要求

是的，我更换了0.9.0对应的client包也没用，感觉需要换老一点的canal

**Comment by wingerx** [comment]
kafka 0.8/0.9/10/11版本差异都比较大，Canal mq adaptor 在这块应该是没有考虑兼容多个kafka 版本的.可以基于mq模块做一下适配吧

**Comment by lixiongjie** [comment]
> kafka 0.8/0.9/10/11版本差异都比较大，Canal mq adaptor 在这块应该是没有考虑兼容多个kafka 版本的.可以基于mq模块做一下适配吧

谢谢大大，我准备用他TCP模式的ClientAPI生产数据到低版本的kafka里。
