### ISSUE TITLE
canal_adapter无法导入es

### ISSUE THREAD

**Issue by yidazhi** [alibaba/canal#3291]
es版本：7.10
canal版本：1.1.4
es的索引信息
![image](https://user-images.githubusercontent.com/35521643/103620401-5ff7bc00-4f6e-11eb-9a59-469e8d6d13bb.png)

canal adapter application.yml配置文件如下：

server:
  port: 8081
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

canal.conf:
  canalServerHost: 192.168.11.169:11111
  flatMessage: true
  batchSize: 500
  syncBatchSize: 1000
  retries: 0
  timeout:
  accessKey:
  secretKey:
  username:
  password:
  vhost:
  srcDataSources:
    defaultDS:
      url: jdbc:mysql://192.168.11.169:3306/sbtest?useUnicode=true
      username: zhao
      password: 111111
  canalAdapters:
    groups:
    - groupId: test-consumer-group
      outerAdapters:
      - name: logger
      - name: es7
        properties:
          cluster.name: my-application

canal adapter es7目录下mytest_user.yml配置如下：

dataSourceKey: defaultDS
destination: example
groupId: test-consumer-group
esMapping:
  _index: st
  pk: id
  upsert: true
  sql: "select id,gid,c from c_0"
  commitBatch: 3000

报错信息如下：
2021-01-05 15:38:09.156 [pool-1-thread-1] INFO  c.a.o.canal.client.adapter.logger.LoggerAdapterExample - DML: {"data":[{"gid":"ee","c":4,"id":4}],"database":"sbtest","des
tination":"example","es":1609831930000,"groupId":"test-consumer-group","isDdl":false,"old":null,"pkNames":["id"],"sql":"","table":"c_0","ts":1609831930133,"type":"INSERT"
}
2021-01-05 15:38:09.304 [elasticsearch[_client_][transport_worker][T#4]] ERROR org.elasticsearch.ExceptionsHelper - fatal error
        at org.elasticsearch.ExceptionsHelper.lambda$maybeDieOnAnotherThread$4(ExceptionsHelper.java:300)
        at java.util.Optional.ifPresent(Optional.java:159)
        at org.elasticsearch.ExceptionsHelper.maybeDieOnAnotherThread(ExceptionsHelper.java:290)
        at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.exceptionCaught(Netty4MessageChannelHandler.java:70)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:297)
        at io.netty.channel.AbstractChannelHandlerContext.notifyHandlerException(AbstractChannelHandlerContext.java:831)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:376)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:582)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:536)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.lang.Thread.run(Thread.java:748)
2021-01-05 15:38:09.320 [elasticsearch[_client_][transport_worker][T#4]] WARN  org.elasticsearch.transport.TcpTransport - exception caught on transport layer [Netty4TcpChannel{localAddress=/192.168.11.169:59452, remoteAddress=/192.168.11.178:9300}], closing connection
java.lang.Exception: java.lang.ExceptionInInitializerError
        at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.exceptionCaught(Netty4MessageChannelHandler.java:75) [client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:297) [client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.notifyHandlerException(AbstractChannelHandlerContext.java:831) [client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:376) [client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) [client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) [client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241) [client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241) [client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) [client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) [client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682) [client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:582) [client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:536) [client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) [client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906) [client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_222-ea]
Caused by: java.lang.ExceptionInInitializerError: null
        at org.elasticsearch.search.SearchHits.<init>(SearchHits.java:83) ~[client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
        at org.elasticsearch.search.internal.InternalSearchResponse.<init>(InternalSearchResponse.java:53) ~[client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
        at org.elasticsearch.action.search.SearchResponse.<init>(SearchResponse.java:81) ~[client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
        at org.elasticsearch.action.ActionListenerResponseHandler.read(ActionListenerResponseHandler.java:69) ~[client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
        at org.elasticsearch.action.ActionListenerResponseHandler.read(ActionListenerResponseHandler.java:36) ~[client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
        at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.read(TransportService.java:1092) ~[client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
        at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.read(TransportService.java:1079) ~[client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
        at org.elasticsearch.transport.InboundHandler.handleResponse(InboundHandler.java:209) ~[client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
        at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:141) ~[client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
        at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:105) ~[client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
        at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:660) ~[client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
        at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:62) [client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
        ... 23 common frames omitted
Caused by: java.lang.IllegalArgumentException: An SPI class of type org.apache.lucene.codecs.PostingsFormat with name 'Lucene50' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: [completion]
        at org.apache.lucene.util.NamedSPILoader.lookup(NamedSPILoader.java:116) ~[client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
        at org.apache.lucene.codecs.PostingsFormat.forName(PostingsFormat.java:112) ~[client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
        at org.elasticsearch.common.lucene.Lucene.<clinit>(Lucene.java:113) ~[client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
        ... 36 common frames omitted
2021-01-05 15:38:39.130 [Thread-4] ERROR c.a.o.c.adapter.launcher.loader.CanalAdapterKafkaWorker - null Error sync but ACK!

请问这个报错如何处理

**Comment by williamyuan86** [comment]
canalAdapters:

instance: example # canal instance Name or mq topic name
groups:
groupId: g1
outerAdapters:
name: logger
name: es
hosts: ${IP}:${PORT}
properties:
mode: rest
security.auth: ${elastic_user}:${elastic_password}
cluster.name: ${elastic_cluster_name}
