### ISSUE TITLE
canal1.1.0启动后日志报错，并且不再同步binlog，错误日志如下

### ISSUE THREAD

**Issue by zhaolinyu** [alibaba/canal#3295]
## Question

2021-01-05 18:50:33.399 [destination = example , address = rm-2zes8ofxqv99x.mysql.rds.aliyuncs.com/172.xx.xx.129:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - KILL DUMP 1544547458 failure
java.io.IOException: ErrorPacket [errorNumber=1094, fieldCount=-1, message=Unknown thread id: 1544547458, sqlState=HY000, sqlStateMarker=#]
 with command: KILL CONNECTION 1544547458
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlUpdateExecutor.update(MysqlUpdateExecutor.java:49) ~[canal.parse.driver-1.1.0.jar:na]
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.disconnect(MysqlConnector.java:107) ~[canal.parse.driver-1.1.0.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.disconnect(MysqlConnection.java:93) [canal.parse-1.1.0.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:298) [canal.parse-1.1.0.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

**Comment by zhaolinyu** [comment]
stop服务，删除了h2.mv.db，然后重启，问题没有解决。之前数据库应该存在过闪断的情况
