### ISSUE TITLE
MySQL5.7 JSON解析问题

### ISSUE THREAD

**Issue by toruneko** [alibaba/canal#330]
canal 版本1.0.24
写入MySQL的JSON数据，Canal解析失败

2017-06-22 11:39:25.104 [destination = example , address = /127.0.0.1:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[com.alibaba.otter.canal.parse.exception.CanalParseException: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: java.lang.IllegalArgumentException: illegal json data
        at com.taobao.tddl.dbsync.binlog.JsonConversion.parse_array_or_object(JsonConversion.java:81)
        at com.taobao.tddl.dbsync.binlog.JsonConversion.parse_value(JsonConversion.java:61)
        at com.taobao.tddl.dbsync.binlog.event.RowsLogBuffer.fetchValue(RowsLogBuffer.java:955)
        at com.taobao.tddl.dbsync.binlog.event.RowsLogBuffer.nextValue(RowsLogBuffer.java:99)
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseOneRow(LogEventConvert.java:495)
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseRowsEvent(LogEventConvert.java:376)
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:108)
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:62)
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser.parseAndProfilingIfNecessary(AbstractEventParser.java:326)
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3$1.sink(AbstractEventParser.java:176)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:130)
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209)
        at java.lang.Thread.run(Thread.java:745)

另外如果json中包含双引号，canal解析之后丢失了转义符号。
![image](https://user-images.githubusercontent.com/5357638/27416733-e8f73ba8-5741-11e7-96c0-2a0de5ddc8af.png)

**Comment by agapple** [comment]
提供一下测试SQL

**Comment by toruneko** [comment]
两个问题，第一个问题还没找到出问题的SQL，
第二个是canal已经解析了，并且canal client可以拿到数据。

+-------+-------------+------+-----+-------------------+-------+
| Field | Type        | Null | Key | Default           | Extra |
+-------+-------------+------+-----+-------------------+-------+
| id    | int(11)     | NO   | PRI | NULL              |       |
| dt    | timestamp   | NO   |     | CURRENT_TIMESTAMP |       |
| json1 | json        | YES  |     | NULL              |       |
| aa    | varchar(50) | YES  |     | NULL              |       |
+-------+-------------+------+-----+-------------------+-------+
insert into t1(id, json1, aa) values(3,"{\"test\":\"aa\\\"aa\"}", "a");
`insert into t1(id, json1, aa) values(3,"{\"test\":\"aa\\\"aa\"}", "a");`

**Comment by toruneko** [comment]
找到导致illegal json data 的SQL了。
json大概有25000个字节，就补贴出来了。

**Comment by lan1994** [comment]
找到导致illegal json data 的SQL了。
json大概有25000个字节，就补贴出来了。

会不会是因为json太大，导致bytes和len长度计算错误。
----------------------------------------------------------------
@toruneko   你这个问题怎么解决的？

**Comment by toruneko** [comment]
@lan1994 最后我们没有用json了。改了方案。。

**Comment by caojiaqing** [comment]
遇到同样问题，求解。

**Comment by agapple** [comment]
我尽快修复一下，应该不难

**Comment by littlemice** [comment]
最近我们postgresql切换到mysql用到了json类型的字段，mysql版本升级到5.7才能支持，想问一下canal升级到v1.1.0，是否支持json类型的字段？

**Comment by littlemice** [comment]
@agapple , 技术专家，您好，有个问题请教一下：
最近我们项目改造，数据库postgresql切换到mysql用到了json类型的字段，mysql版本升级到5.7才能支持，想问一下canal升级到v1.1.0，是否支持json类型的字段？

**Comment by agapple** [comment]
canal是向前兼容的，支持json解析

**Comment by littlemice** [comment]
@agapple ,没想到这么快就回复了，谢谢大咖！
