### ISSUE TITLE
对接阿里云rocketmq 提示topic is batch send , not support.

### ISSUE THREAD

**Issue by ivancxj** [alibaba/canal#3304]
## Question

版本1.1.15
使用阿里云rocketmq，设置ak/sk后，启动后提示错误
Caused by: org.apache.rocketmq.client.exception.MQBrokerException: CODE: 1  DESC: the topic[binlog_prod_yaomaitong] is batch send , not support.
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.processSendResponse(MQClientAPIImpl.java:671) ~[na:na]
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessageSync(MQClientAPIImpl.java:467) ~[na:na]
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:449) ~[na:na]
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:403) ~[na:na]
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendKernelImpl(DefaultMQProducerImpl.java:831) ~[na:na]
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:981) ~[na:na]
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:963) ~[na:na]
	at org.apache.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:800) ~[na:na]
	at com.alibaba.otter.canal.connector.rocketmq.producer.CanalRocketMQProducer.sendMessage(CanalRocketMQProducer.java:303) ~[na:na]

了解后原因就是阿里云rocketmq不支持批量发送，请问这个如何解决？

**Comment by c2ch** [comment]
请问你解决了吗

**Comment by ivancxj** [comment]
> 请问你解决了吗

改了源码，改成单个发送

**Comment by MrJXL** [comment]
> > 请问你解决了吗
> 
> 改了源码，改成单个发送

源码要改哪里能告知下吗

**Comment by ivancxj** [comment]
CanalRocketMQProducer类

**Comment by ivancxj** [comment]
> > > 请问你解决了吗
> > 
> > 
> > 改了源码，改成单个发送
> 
> 源码要改哪里能告知下吗

CanalRocketMQProducer类，334行
```java
SendResult sendResult = this.defaultMQProducer.send(messages, queue);
```
改成
```java
for (Message message : messages) {
   sendMessage(message, partition);
}
```

**Comment by MrJXL** [comment]
> > > > 请问你解决了吗
> > > 
> > > 
> > > 改了源码，改成单个发送
> > 
> > 
> > 源码要改哪里能告知下吗
> 
> CanalRocketMQProducer类，334行
> 
> ```java
> SendResult sendResult = this.defaultMQProducer.send(messages, queue);
> ```
> 
> 改成
> 
> ```java
> for (Message message : messages) {
>    sendMessage(message, partition);
> }
> ```

嗯，已经找到了，感谢。
