### ISSUE TITLE
运行example下面的CanalKafkaClientExample 报错java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by zcc19910524** [alibaba/canal#3324]
canal.deployer-1.1.4;

09:50:39.119 [Thread-0] ERROR CanalKafkaClientExample - null
java.lang.NullPointerException: null
	at com.alibaba.otter.canal.client.kafka.KafkaCanalConnector.getListWithoutAck(KafkaCanalConnector.java:184) ~[canal.client-1.1.4.jar:na]
	at CanalKafkaClientExample.process(CanalKafkaClientExample.java:99) ~[classes/:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_231]

终端 kafka命令行模式 已经可以消费到canal的消息 运行这个client时在getListWithoutAck这一行就报错

**Comment by zcc19910524** [comment]
因为设置了canal.mq.flatMessage = true 所以需要用 getFlatListWithoutAck
