### ISSUE TITLE
异步ack的时候，ack线程出现空指针异常，get线程阻塞在BooleanMutex，是否与设置ring buffer size有关？

### ISSUE THREAD

**Issue by Jdoing** [alibaba/canal#336]
client端ack线程出现空指针异常，get线程阻塞在BooleanMutex

`"SyncThread5" #27 prio=5 os_prio=0 tid=0x00007fc880f62800 nid=0x549 waiting on condition [0x00007fc854302000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x0000000735ee1df0> (a com.alibaba.otter.canal.common.utils.BooleanMutex$Sync)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
        at com.alibaba.otter.canal.common.utils.BooleanMutex$Sync.innerGet(BooleanMutex.java:123)
        at com.alibaba.otter.canal.common.utils.BooleanMutex.get(BooleanMutex.java:53)
        at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.waitClientRunning(SimpleCanalConnector.java:425)
        at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.getWithoutAck(SimpleCanalConnector.java:256)
        at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.getWithoutAck(SimpleCanalConnector.java:252)
        at com.alibaba.otter.canal.client.impl.ClusterCanalConnector.getWithoutAck(ClusterCanalConnector.java:180)
        at com.dfire.obd.core.Launcher$SyncThread.run(Launcher.java:105)`

server端出现：2017-07-04 14:28:15.068 ERROR com.alibaba.otter.canal.server.netty.NettyUtils [New I/O server worker #1-4]；ErrotCode:400 , Caused by : 
something goes wrong with channel:[id: 0x2ce9c057, /10.26.0.247:41053 :> /10.26.0.9:11111], exception=com.alibaba.otter.canal.server.exception.CanalServerException: ack error , clientId:1001 batchId:14800952 is not exist , please check

**Comment by agapple** [comment]
尝试一下canal新版本
