### ISSUE TITLE
canal监听阿里的polarDB异常

### ISSUE THREAD

**Issue by 497422159** [alibaba/canal#3416]
- [√ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ √] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version 
 1.1.5-SNAPSHOT
* mysql version
polarDB
### Issue Description
 使用canal监听自建的mysql可以正常监听，重新创建了一个canal.destinations，监听对象是阿里的polarDB，则启动canal报异常，说是performance_schema中有些表找不到，但是我查看了自建的mysql，一样没有这些表，但是canal能正常启动和监听。

### Expected behaviour
canal能像监听自建mysql一样可以监听polarDB
### Actual behaviour
canal配置polarDB后启动报错，监听失败

If there is an exception, please attach the exception trace:

```
2021-03-22 14:09:14.810 [destination = mycdbPro , address = xxxxxxx:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> begin to find start position, it will be long time for reset or first position
2021-03-22 14:09:14.810 [destination = mycdbPro , address = xxxxxxx:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - prepare to find start position just show master status
2021-03-22 14:09:20.760 [destination = mycdbPro , address = xxxxxxx2:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address xxxxxxx:3306 has an error, retrying. caused by 
com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: ErrorPacket [errorNumber=1146, fieldCount=-1, message=Table 'performance_schema.events_statements_summary_by_digest_supplement' doesn't exist, sqlState=42S02, sqlStateMarker=#]
 with command: show create table `performance_schema`.`accounts`;show create table `performance_schema`.`cond_instances`;show create table `performance_schema`.`events_stages_current`;show create table `performance_schema`.`events_stages_history`;show create table `performance_schema`.`events_stages_history_long`;show create table `performance_schema`.`events_stages_summary_by_account_by_event_name`;show create table `performance_schema`.`events_stages_summary_by_host_by_event_name`;show create table `performance_schema`.`events_stages_summary_by_thread_by_event_name`;show create table `performance_schema`.`events_stages_summary_by_user_by_event_name`;show create table `performance_schema`.`events_stages_summary_global_by_event_name`;show create table `performance_schema`.`events_statements_current`;show create table `performance_schema`.`events_statements_history`;show create table `performance_schema`.`events_statements_history_long`;show create table `performance_schema`.`events_statements_summary_by_account_by_event_name`;show create table `performance_schema`.`events_statements_summary_by_digest`;show create table `performance_schema`.`events_statements_summary_by_digest_supplement`;show create table `performance_schema`.`events_statements_summary_by_host_by_event_name`;show create table `performance_schema`.`events_statements_summary_by_thread_by_event_name`;show create table `performance_schema`.`events_statements_summary_by_user_by_event_name`;show create table `performance_schema`.`events_statements_summary_global_by_event_name`;show create table `performance_schema`.`events_waits_current`;show create table `performance_schema`.`events_waits_history`;show create table `performance_schema`.`events_waits_history_long`;show create table `performance_schema`.`events_waits_summary_by_account_by_event_name`;show create table `performance_schema`.`events_waits_summary_by_host_by_event_name`;show create table `performance_schema`.`events_waits_summary_by_instance`;show create table `performance_schema`.`events_waits_summary_by_thread_by_event_name`;show create table `performance_schema`.`events_waits_summary_by_user_by_event_name`;show create table `performance_schema`.`events_waits_summary_global_by_event_name`;show create table `performance_schema`.`file_instances`;show create table `performance_schema`.`file_summary_by_event_name`;show create table `performance_schema`.`file_summary_by_instance`;show create table `performance_schema`.`host_cache`;show create table `performance_schema`.`hosts`;show create table `performance_schema`.`mutex_instances`;show create table `performance_schema`.`objects_summary_global_by_type`;show create table `performance_schema`.`performance_timers`;show create table `performance_schema`.`rwlock_instances`;show create table `performance_schema`.`session_account_connect_attrs`;show create table `performance_schema`.`session_connect_attrs`;show create table `performance_schema`.`setup_actors`;show create table `performance_schema`.`setup_consumers`;show create table `performance_schema`.`setup_instruments`;show create table `performance_schema`.`setup_objects`;show create table `performance_schema`.`setup_timers`;show create table `performance_schema`.`socket_instances`;show create table `performance_schema`.`socket_summary_by_event_name`;show create table `performance_schema`.`socket_summary_by_instance`;show create table `performance_schema`.`table_io_waits_summary_by_index_usage`;show create table `performance_schema`.`table_io_waits_summary_by_table`;show create table `performance_schema`.`table_lock_waits_summary_by_table`;show create table `performance_schema`.`threads`;show create table `performance_schema`.`users`;
Caused by: java.io.IOException: ErrorPacket [errorNumber=1146, fieldCount=-1, message=Table 'performance_schema.events_statements_summary_by_digest_supplement' doesn't exist, sqlState=42S02, sqlStateMarker=#]
 with command: show create table `performance_schema`.`accounts`;show create table `performance_schema`.`cond_instances`;show create table `performance_schema`.`events_stages_current`;show create table `performance_schema`.`events_stages_history`;show create table `performance_schema`.`events_stages_history_long`;show create table `performance_schema`.`events_stages_summary_by_account_by_event_name`;show create table `performance_schema`.`events_stages_summary_by_host_by_event_name`;show create table `performance_schema`.`events_stages_summary_by_thread_by_event_name`;show create table `performance_schema`.`events_stages_summary_by_user_by_event_name`;show create table `performance_schema`.`events_stages_summary_global_by_event_name`;show create table `performance_schema`.`events_statements_current`;show create table `performance_schema`.`events_statements_history`;show create table `performance_schema`.`events_statements_history_long`;show create table `performance_schema`.`events_statements_summary_by_account_by_event_name`;show create table `performance_schema`.`events_statements_summary_by_digest`;show create table `performance_schema`.`events_statements_summary_by_digest_supplement`;show create table `performance_schema`.`events_statements_summary_by_host_by_event_name`;show create table `performance_schema`.`events_statements_summary_by_thread_by_event_name`;show create table `performance_schema`.`events_statements_summary_by_user_by_event_name`;show create table `performance_schema`.`events_statements_summary_global_by_event_name`;show create table `performance_schema`.`events_waits_current`;show create table `performance_schema`.`events_waits_history`;show create table `performance_schema`.`events_waits_history_long`;show create table `performance_schema`.`events_waits_summary_by_account_by_event_name`;show create table `performance_schema`.`events_waits_summary_by_host_by_event_name`;show create table `performance_schema`.`events_waits_summary_by_instance`;show create table `performance_schema`.`events_waits_summary_by_thread_by_event_name`;show create table `performance_schema`.`events_waits_summary_by_user_by_event_name`;show create table `performance_schema`.`events_waits_summary_global_by_event_name`;show create table `performance_schema`.`file_instances`;show create table `performance_schema`.`file_summary_by_event_name`;show create table `performance_schema`.`file_summary_by_instance`;show create table `performance_schema`.`host_cache`;show create table `performance_schema`.`hosts`;show create table `performance_schema`.`mutex_instances`;show create table `performance_schema`.`objects_summary_global_by_type`;show create table `performance_schema`.`performance_timers`;show create table `performance_schema`.`rwlock_instances`;show create table `performance_schema`.`session_account_connect_attrs`;show create table `performance_schema`.`session_connect_attrs`;show create table `performance_schema`.`setup_actors`;show create table `performance_schema`.`setup_consumers`;show create table `performance_schema`.`setup_instruments`;show create table `performance_schema`.`setup_objects`;show create table `performance_schema`.`setup_timers`;show create table `performance_schema`.`socket_instances`;show create table `performance_schema`.`socket_summary_by_event_name`;show create table `performance_schema`.`socket_summary_by_instance`;show create table `performance_schema`.`table_io_waits_summary_by_index_usage`;show create table `performance_schema`.`table_io_waits_summary_by_table`;show create table `performance_schema`.`table_lock_waits_summary_by_table`;show create table `performance_schema`.`threads`;show create table `performance_schema`.`users`;
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlQueryExecutor.queryMulti(MysqlQueryExecutor.java:109) ~[canal.parse.driver-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.queryMulti(MysqlConnection.java:111) ~[canal.parse-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.dumpTableMeta(DatabaseTableMeta.java:232) ~[canal.parse-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:182) ~[canal.parse-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:137) ~[canal.parse-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:200) ~[canal.parse-1.1.5-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_211]
```

**Comment by agapple** [comment]
过滤下performance_schema的订阅
