### ISSUE TITLE
canal 1.1.5 rocketmq CODE: 1  DESC: UNKNOWN_ERROR

### ISSUE THREAD

**Issue by zhanghongwang** [alibaba/canal#3417]
增加配置后 出现 canal.mq.partitionsNum=1
出现如下错误
`

2021-03-21 19:07:32.723 [pool-75-thread-1] ERROR c.a.o.c.c.rocketmq.producer.CanalRocketMQProducer - java.util.concurrent.ExecutionException: java.lang.RuntimeException: org.apache.rocketmq.client.exception.MQBrokerException: CODE: 1  DESC: UNKNOWN_ERROR
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: org.apache.rocketmq.client.exception.MQBrokerException: CODE: 1  DESC: UNKNOWN_ERROR
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
        at com.alibaba.otter.canal.common.utils.ExecutorTemplate.waitForResult(ExecutorTemplate.java:74) ~[canal.common-1.1.5-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.connector.rocketmq.producer.CanalRocketMQProducer.send(CanalRocketMQProducer.java:241) ~[na:na]
        at com.alibaba.otter.canal.connector.rocketmq.producer.CanalRocketMQProducer.send(CanalRocketMQProducer.java:151) ~[na:na]
        at com.alibaba.otter.canal.server.CanalMQStarter.worker(CanalMQStarter.java:181) [canal.server-1.1.5-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.server.CanalMQStarter.access$100(CanalMQStarter.java:25) [canal.server-1.1.5-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.server.CanalMQStarter$CanalMQRunnable.run(CanalMQStarter.java:223) [canal.server-1.1.5-SNAPSHOT.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: org.apache.rocketmq.client.exception.MQBrokerException: CODE: 1  DESC: UNKNOWN_ERROR
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_181]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_181]
        at com.alibaba.otter.canal.common.utils.ExecutorTemplate.waitForResult(ExecutorTemplate.java:72) ~[canal.common-1.1.5-SNAPSHOT.jar:na]
        ... 8 common frames omitted
Caused by: java.lang.RuntimeException: org.apache.rocketmq.client.exception.MQBrokerException: CODE: 1  DESC: UNKNOWN_ERROR
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
        at com.alibaba.otter.canal.connector.rocketmq.producer.CanalRocketMQProducer.sendMessage(CanalRocketMQProducer.java:308) ~[na:na]
        at com.alibaba.otter.canal.connector.rocketmq.producer.CanalRocketMQProducer.lambda$send$3(CanalRocketMQProducer.java:235) ~[na:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_181]
        ... 3 common frames omitted
Caused by: org.apache.rocketmq.client.exception.MQBrokerException: CODE: 1  DESC: UNKNOWN_ERROR
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
        at org.apache.rocketmq.client.impl.MQClientAPIImpl.processSendResponse(MQClientAPIImpl.java:671) ~[na:na]
        at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessageSync(MQClientAPIImpl.java:467) ~[na:na]
        at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:449) ~[na:na]
        at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:403) ~[na:na]
        at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendKernelImpl(DefaultMQProducerImpl.java:831) ~[na:na]
        at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:981) ~[na:na]
        at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:963) ~[na:na]
        at org.apache.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:800) ~[na:na]
        at com.alibaba.otter.canal.connector.rocketmq.producer.CanalRocketMQProducer.sendMessage(CanalRocketMQProducer.java:303) ~[na:na]
        ... 6 common frames omitted
[root@canal-server-1 pre]# `

**Comment by zhanghongwang** [comment]
注释  `#canal.mq.partitionsNum = 3` 出现这个如下错误

`2021-03-22 16:44:36.285 [pool-93-thread-1] ERROR c.a.o.c.c.rocketmq.producer.CanalRocketMQProducer - null
java.lang.NullPointerException: null`
