### ISSUE TITLE
canal server停用一个月后，重新启用报错

### ISSUE THREAD

**Issue by jayws** [alibaba/canal#348]
canal server停用一个月后，重新启用报错，找不到之前解析文件位置，请问canal当找不到原来已解析过的文件位置时，不能从最新位置开始解析吗？谢谢！
[destination = xxx , address = /1.1.1.1:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:xxx [java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:95)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:122)
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209)
        at java.lang.Thread.run(Thread.java:745)

**Comment by luyee** [comment]
配置了位点不能吧，要从最新开始消费，直接删除位点试试

**Comment by jayws** [comment]
没有指定位点，请问如何删除位点，谢谢！

**Comment by jayws** [comment]
我那个问题应该是binlog清理掉之前的文件，然后导致找不到从位点解析binlog的问题吧

**Comment by luyee** [comment]
是的 指定位点了就会，不指定应该是从最新开始消费的

**Comment by jayws** [comment]
嗯嗯，谢谢！修改位点是不是只能修改zookeeper里存放offset的数据呀！
