### ISSUE TITLE
账号拒绝错误

### ISSUE THREAD

**Issue by enjoy4913** [alibaba/canal#3516]
## Question

数据库版本5.7.25-28   权限我都测试过  全部可以连接  不清楚为什么老是报账号拒绝错误
java.io.IOException: Error When doing Register slave:ErrorPacket [errorNumber=1045, fieldCount=-1, message=Access denied for user 'retl'@'%' (using password: YES), sqlState=28000, sqlStateMarker=#]
at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.sendRegisterSlave(MysqlConnection.java:287)
at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:148)
at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:266)
at java.lang.Thread.run(Thread.java:748)

**Comment by yonggandeliuguang** [comment]
可以看看https://blog.csdn.net/xiaoshunzi111/article/details/52803669，可能密码错了，或者像这个说的，改为%，localhost访问不了

**Comment by bf236** [comment]
这个问题解决了吗

**Comment by bf236** [comment]
> 这个问题解决了吗

也遇到这个问题
