### ISSUE TITLE
canal  报错：  Read Q_FLAGS2_CODE error: limit excceed: 63

### ISSUE THREAD

**Issue by yangshike** [alibaba/canal#352]
大数据量的批量插入 类似select into 的sql （10w条记录），canal 报错：
pid:1 nid:2 exception:canal:canal_master:java.io.IOException: Read Q_FLAGS2_CODE error: limit excceed: 63
at com.taobao.tddl.dbsync.binlog.event.QueryLogEvent.unpackVariables(QueryLogEvent.java:650)
at com.taobao.tddl.dbsync.binlog.event.QueryLogEvent.(QueryLogEvent.java:477)
at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:154)
at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:106)
at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:123)
at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: limit excceed: 63
at com.taobao.tddl.dbsync.binlog.LogBuffer.getUint32(LogBuffer.java:561)
at com.taobao.tddl.dbsync.binlog.event.QueryLogEvent.unpackVariables(QueryLogEvent.java:563)
... 6 more

**Comment by agapple** [comment]
报告一下mysql和canal版本

**Comment by jwcjlu** [comment]
我这边也有这个问题 canal是1.0.22，Mysql是5.7.12-5-log

**Comment by agapple** [comment]
@jwcjlu 先测试一下1.0.26版本试试

**Comment by jwcjlu** [comment]
测试过了1.0.25就没有问题了

**Comment by sumrainli** [comment]
1.1.4还是有问题

**Comment by sumrainli** [comment]
com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:elabnote[com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: Read Q_FLAGS2_CODE error: limit excceed: 70
Caused by: java.io.IOException: Read Q_FLAGS2_CODE error: limit excceed: 70
	at com.taobao.tddl.dbsync.binlog.event.QueryLogEvent.unpackVariables(QueryLogEvent.java:715)
	at com.taobao.tddl.dbsync.binlog.event.QueryLogEvent.<init>(QueryLogEvent.java:495)
	at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:168)
	at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:111)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:269)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:251)
	at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: limit excceed: 70
	at com.taobao.tddl.dbsync.binlog.LogBuffer.getUint32(LogBuffer.java:562)
	at com.taobao.tddl.dbsync.binlog.event.QueryLogEvent.unpackVariables(QueryLogEvent.java:612)
	... 12 more

**Comment by HJC15388696859** [comment]
搞了一下午一直是这个错误，最后发现docker部署的canal版本是v1.1.1，好几年前的版本了。然后拉取了最近的版本v1.1.7，直接就好了。我的mysql版本是8.2.0，部署在windows本地。希望能帮到你！
