### ISSUE TITLE
启动cancl，连接数据库连接不上

### ISSUE THREAD

**Issue by yjianwei** [alibaba/canal#354]
2017-08-01 09:27:36.766 [main] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Loading properties file from class path resource [canal.properties]
2017-08-01 09:27:36.770 [main] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Loading properties file from class path resource [example/instance.properties]
2017-08-01 09:27:36.850 [main] WARN  org.springframework.beans.TypeConverterDelegate - PropertyEditor [com.sun.beans.editors.EnumEditor] found through deprecated global PropertyEditorManager fallback - consider using a more isolated form of registration, e.g. on the BeanWrapper/BeanFactory!
2017-08-01 09:27:36.971 [main] INFO  c.a.otter.canal.instance.spring.CanalInstanceWithSpring - start CannalInstance for 1-example 
2017-08-01 09:27:36.987 [main] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - start successful....
2017-08-01 09:27:44.004 [destination = example , address = /192.168.**.**:**** , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - dump address /192.168.30.46:3306 has an error, retrying. caused by 
com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: connect /192.168.**.**:**** failure:java.net.ConnectException: Connection timed out
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:364)
	at sun.nio.ch.Net.connect(Net.java:356)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:623)
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:70)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.connect(MysqlConnection.java:56)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.preDump(MysqlEventParser.java:86)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:157)
	at java.lang.Thread.run(Thread.java:722)
报错信息如上，我不知道是不是这个/的问题，但是我在配置文件并没有/的，看了源码也没有，不知道是什么原因，求助！！！！万分感谢

**Comment by yjianwei** [comment]
canal版本是1.0.24

**Comment by luyee** [comment]
这个肯定是自己连接有问题，另外，1.0.24 还是别用的好。。。
