### ISSUE TITLE
[release/v1.1.5] mysql binlog ddl sql parser error

### ISSUE THREAD

**Issue by yuexiwei** [alibaba/canal#3543]
**升级至canal release/v1.1.5，(/canal/lib/druid-1.2.6.jar)后mysql binlog 的ddl解析还是出错：**

mysql  Ver 14.14 Distrib 5.7.31

```
2021-05-20 15:41:35.859 [destination = example , address = mysql/172.19.0.5:3306 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta - parse faield : CREATE TABLE `CJ_CMP_F5_DEVICE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'F5 device表ID',
  `MEMBER_ID` bigint(20) NOT NULL COMMENT '会员ID',
  `INSTANCE_ID` varchar(64) DEFAULT NULL,
  `NAME` varchar(255) NOT NULL COMMENT '中文名称',
  `ENTITY_ID` varchar(255) DEFAULT NULL COMMENT '实体ID',
  `SERVICE_ACCOUNT_ID` bigint(20) DEFAULT NULL COMMENT '云平台ID',
  `ADDRESS` varchar(255) DEFAULT NULL COMMENT '地址',
  `BUILD` varchar(64) DEFAULT NULL COMMENT '构建版本',
  `DEVICE_URI` varchar(255) DEFAULT NULL COMMENT '设备URI',
  `GENERATION` int(11) DEFAULT NULL COMMENT '代',
  `GROUP_NAME` varchar(255) DEFAULT NULL COMMENT '组名称',
  `HTTPS_PORT` int(11) DEFAULT NULL COMMENT 'http端口',
  `CLUSTERED` tinyint(1) DEFAULT NULL COMMENT '是否集群化',
  `LICENSE_EXPIRED` tinyint(1) DEFAULT NULL COMMENT 'license是否过期',
  `IS_VIRTUAL` tinyint(1) DEFAULT NULL COMMENT '是否虚拟化',
  `KIND` varchar(255) DEFAULT NULL COMMENT '种类',
  `MACHINEID` varchar(255) DEFAULT NULL COMMENT '机器id',
  `MANAGEMENT_ADDRESS` varchar(255) DEFAULT NULL COMMENT '管理地址',
  `MCP_DEVICE_NAME` varchar(255) DEFAULT NULL COMMENT 'mcp设备名称',
  `PRODUCT` varchar(255) DEFAULT NULL COMMENT '产品',
  `CLUSTER_NAME` varchar(255) DEFAULT NULL COMMENT '集群名称',
  `REST_FRAMEWORK_VERSION` varchar(64) DEFAULT NULL COMMENT 'rest框架版本',
  `VERSION` varchar(64) DEFAULT NULL COMMENT '版本号',
  `STATUS` varchar(64) DEFAULT NULL COMMENT '状态',
  `DISCOVERY_SOURCE` varchar(64) DEFAULT NULL COMMENT '发现来源',
  `FIRST_DISCOVERED` datetime DEFAULT NULL COMMENT '首次发现时间',
  `LAST_DISCOVERED` datetime DEFAULT NULL COMMENT '最后发现时间',
  `FAULT_COUNT` int(11) DEFAULT NULL COMMENT '失败次数',
  `SKIP_SYNC` tinyint(1) DEFAULT NULL COMMENT '是否跳过同步',
  `CREATE_BY` varchar(64) DEFAULT NULL COMMENT '创建人',
  `CREATE_DATE` datetime DEFAULT NULL COMMENT '创建时间',
  `LAST_MODIFIED_BY` varchar(64) DEFAULT NULL COMMENT '修改人',
  `LAST_MODIFIED_DATE` datetime DEFAULT NULL COMMENT '修改时间',
  `IS_DELETED` tinyint(4) DEFAULT '0' COMMENT '逻辑删除标识',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='F5 device表'
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'`CLUSTERED` tinyint(1) DEFAULT NULL COMMEN', expect ), actual null, pos 700, line 14, column 16, token IDENTIFIER tinyint
        at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:576) ~[druid-1.2.6.jar:1.2.6]
        at com.alibaba.druid.sql.parser.SQLParser.accept(SQLParser.java:584) ~[druid-1.2.6.jar:1.2.6]
        at com.alibaba.druid.sql.dialect.mysql.parser.MySqlCreateTableParser.parseCreateTable(MySqlCreateTableParser.java:366) ~[druid-1.2.6.jar:1.2.6]
        at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseCreate(MySqlStatementParser.java:309) ~[druid-1.2.6.jar:1.2.6]
        at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:249) ~[druid-1.2.6.jar:1.2.6]
        at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:565) ~[druid-1.2.6.jar:1.2.6]
        at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:587) ~[druid-1.2.6.jar:1.2.6]
        at com.alibaba.druid.sql.repository.SchemaRepository.console(SchemaRepository.java:445) ~[druid-1.2.6.jar:1.2.6]
        at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta.apply(MemoryTableMeta.java:84) ~[canal.parse-1.1.5.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.dumpTableMeta(DatabaseTableMeta.java:225) [canal.parse-1.1.5.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:173) [canal.parse-1.1.5.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:142) [canal.parse-1.1.5.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:197) [canal.parse-1.1.5.jar:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_202]
2021-05-20 15:41:36.171 [destination = example , address = mysql/172.19.0.5:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> find start position successfully, EntryPosition[included=false,journalName=067adac2b988-bin.000013,position=437546862,serverId=1,gtid=,timestamp=1621496493000] cost : 2565ms , the next step is binlog dump
```

**Comment by agapple** [comment]
CLUSTERED识别为关键字了

**Comment by yongzheJIN** [comment]
> CLUSTERED识别为关键字了

这个问题不解决吗，数据库里有关键名称的表字段 还是挺常见的。 flink都可以支持这个
