### ISSUE TITLE
com.alibaba.otter.canal.server.exception.CanalServerException: destination:example should start first

### ISSUE THREAD

**Issue by jiangxiaoqiang** [alibaba/canal#3565]
## Question

启动canal-adapter后，日志打印错误：

```
2021-05-27 16:25:07.653 [Thread-4] ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - process error!
com.alibaba.otter.canal.protocol.exception.CanalClientException: failed to subscribe with reason: something goes wrong with channel:[id: 0x2db2bd91, /10.244.2.253:39276 => /10.244.5.18:11111], exception=com.alibaba.otter.canal.server.exception.CanalServerException: destination:example should start first
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.subscribe(SimpleCanalConnector.java:249) ~[na:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.subscribe(SimpleCanalConnector.java:226) ~[na:na]
	at com.alibaba.otter.canal.connector.tcp.consumer.CanalTCPConsumer.connect(CanalTCPConsumer.java:60) ~[na:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.process(AdapterProcessor.java:184) ~[client-adapter.launcher-1.1.5-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_282]
2021-05-27 16:25:08.653 [Thread-4] INFO  c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - =============> Start to connect destination: example <=============
2021-05-27 16:25:08.654 [Thread-4] ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - process error!
com.alibaba.otter.canal.protocol.exception.CanalClientException: failed to subscribe with reason: something goes wrong with channel:[id: 0x2db2bd91, /10.244.2.253:39276 => /10.244.5.18:11111], exception=com.alibaba.otter.canal.server.exception.CanalServerException: destination:example should start first
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.subscribe(SimpleCanalConnector.java:249) ~[na:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.subscribe(SimpleCanalConnector.java:226) ~[na:na]
	at com.alibaba.otter.canal.connector.tcp.consumer.CanalTCPConsumer.connect(CanalTCPConsumer.java:60) ~[na:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.process(AdapterProcessor.java:184) ~[client-adapter.launcher-1.1.5-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_282]
2021-05-27 16:25:09.655 [Thread-4] INFO  c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - =============> Start to connect destination: example <=============


```

这种是什么问题？

**Comment by jiangxiaoqiang** [comment]
instance名字配置错误，已解决

**Comment by zuoxianglei** [comment]
我也出现了这个问题

**Comment by wscjwacs** [comment]
大佬们解决了吗
