### ISSUE TITLE
canal解析错误fetch failed by table meta:`test`.`test`

### ISSUE THREAD

**Issue by jayws** [alibaba/canal#358]
请问这种错误有什么办法可以解决呢？谢谢！

com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: com.google.common.collect.ComputationException: com.alibaba.otter.canal.parse.exception.CanalParseException: fetch failed by table meta:`test`.`test`
Caused by: com.google.common.collect.ComputationException: com.alibaba.otter.canal.parse.exception.CanalParseException: fetch failed by table meta:`test`.`test`
	at com.google.common.collect.MapMaker$ComputingMapAdapter.get(MapMaker.java:889) ~[guava-18.0.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.TableMetaCache.getTableMeta(TableMetaCache.java:78) ~[canal.parse-1.0.24.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.getTableMeta(LogEventConvert.java:677) ~[canal.parse-1.0.24.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseRowsEvent(LogEventConvert.java:362) ~[canal.parse-1.0.24.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:108) ~[canal.parse-1.0.24.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:62) ~[canal.parse-1.0.24.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser.parseAndProfilingIfNecessary(AbstractEventParser.java:326) ~[canal.parse-1.0.24.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3$1.sink(AbstractEventParser.java:176) ~[canal.parse-1.0.24.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:130) [canal.parse-1.0.24.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209) [canal.parse-1.0.24.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]

**Comment by whyliyu** [comment]
我也碰到这个错误了

我找到了原因，这是因为在解析某条binlog记录时，该记录对应的表被删掉了，而在binlog解析过程中canal会发送一条desc `schemeName`.`tableName`的sql语:
    private TableMeta getTableMeta0(String fullname) throws IOException {
        ResultSetPacket packet = connection.query("desc " + fullname);
        return new TableMeta(fullname, parserTableMeta(packet));
    }
而对应的表已经被删掉，这时候就会抛出这个异常

但是没找到如何解决这个方法，不知道这是不是个bug？有没有阿里的大佬出来解答一下？

**Comment by hellogh2014** [comment]
试试 canal/conf 下的 canal.instance.filter.black.regex = test.*

**Comment by agapple** [comment]
尝试一下最新版的，启用TSDB可以解决这个问题

**Comment by fansie1** [comment]
> 试试 canal/conf 下的 canal.instance.filter.black.regex = test.*

成功了，感谢
