### ISSUE TITLE
ERROR c.a.otter.canal.server.netty.handler.SessionHandler - something goes wrong with channel:[id: 0x085a90b2, /127.0.0.1:42008 => /127.0.0.1:11111], exception=java.lang.NegativeArraySizeException

### ISSUE THREAD

**Issue by jiangxiaoqiang** [alibaba/canal#3585]
## Question

运行过程中出现错误：

```
[root@canal-server-stable-0 bin]# tail -f ../logs/canal/canal.log -n 200
2021-06-01 03:08:30.395 [main] INFO  com.alibaba.otter.canal.deployer.CanalLauncher - ## set default uncaught exception handler
2021-06-01 03:08:30.428 [main] INFO  com.alibaba.otter.canal.deployer.CanalLauncher - ## load canal configurations
2021-06-01 03:08:30.839 [main] INFO  com.alibaba.otter.canal.deployer.CanalStarter - ## start the canal server.
2021-06-01 03:08:30.957 [main] INFO  com.alibaba.otter.canal.deployer.CanalController - ## start the canal server[10.244.2.18(10.244.5.5):11111]
2021-06-01 03:08:31.022 [main] INFO  com.alibaba.otter.canal.deployer.CanalStarter - ## the canal server is running now ......
2021-06-01 03:08:32.024 [canal-instance-scan-0] INFO  com.alibaba.otter.canal.deployer.CanalController - auto notify start instance01 successful.
2021-06-01 03:14:18.466 [New I/O server worker #1-3] ERROR c.a.otter.canal.server.netty.handler.SessionHandler - something goes wrong with channel:[id: 0x085a90b2, /127.0.0.1:42008 => /127.0.0.1:11111], exception=java.lang.NegativeArraySizeException
        at org.jboss.netty.buffer.HeapChannelBuffer.<init>(HeapChannelBuffer.java:47)
        at org.jboss.netty.buffer.BigEndianHeapChannelBuffer.<init>(BigEndianHeapChannelBuffer.java:39)
        at org.jboss.netty.buffer.ChannelBuffers.buffer(ChannelBuffers.java:139)
        at org.jboss.netty.buffer.HeapChannelBufferFactory.getBuffer(HeapChannelBufferFactory.java:73)
        at org.jboss.netty.buffer.AbstractChannelBuffer.readBytes(AbstractChannelBuffer.java:306)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoderBuffer.readBytes(ReplayingDecoderBuffer.java:362)
        at com.alibaba.otter.canal.server.netty.handler.FixedHeaderFrameDecoder.decode(FixedHeaderFrameDecoder.java:19)
        at com.alibaba.otter.canal.server.netty.handler.FixedHeaderFrameDecoder.decode(FixedHeaderFrameDecoder.java:15)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:471)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:444)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:274)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:261)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:350)
        at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:281)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:201)
        at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)


```

**Comment by KyrieY** [comment]
这个问题怎么解决的兄弟
