### ISSUE TITLE
canal  阿里云rds 日志文件丢失

### ISSUE THREAD

**Issue by mail6562** [alibaba/canal#3590]
## Question

阿里云rds 8.0+ 版本，
Canal 版本最新版1.1.5 .
监听日志的时候： 当阿里云的 binglog文件变化的时候，就获取不到文件报错了。
错误信息： java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102) ~[canal.parse-1.1.5.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:238) ~[canal.parse-1.1.5.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:262) ~[canal.parse-1.1.5.jar:na]

**Comment by mail6562** [comment]
也配置了 获取rds日志切换后上传到oss上面 key。通过脚本执行是可以的。
