### ISSUE TITLE
canal  1.1.3     是否还使用nio收集bin  log  日志        ？java.nio.channels.ClosedChannelException

### ISSUE THREAD

**Issue by wjlzk1** [alibaba/canal#3613]
## Question

021-06-17 18:40:52.540 [New I/O server worker #1-4] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - subscribe filter change to leiniao_car.*\..*
2021-06-17 18:40:52.566 [New I/O server worker #1-4] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table filter : ^leiniao_car.*\..*$
2021-06-17 18:42:40.258 [New I/O server worker #1-2] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - subscribe filter change to leiniao_car.*\..*
2021-06-17 18:42:40.258 [New I/O server worker #1-2] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table filter : ^leiniao_car.*\..*$
2021-06-17 19:58:39.615 [New I/O server worker #1-4] ERROR c.a.otter.canal.server.netty.handler.SessionHandler - something goes wrong with channel:[id: 0x3774e7b1, /172.18.0.101:54824 :> /172.18.0.63:11111], exception=java.nio.channels.ClosedChannelException
        at org.jboss.netty.channel.socket.nio.NioWorker.cleanUpWriteBuffer(NioWorker.java:649)
        at org.jboss.netty.channel.socket.nio.NioWorker.writeFromUserCode(NioWorker.java:370)
        at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleAcceptedSocket(NioServerSocketPipelineSink.java:137)
        at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:76)
        at org.jboss.netty.channel.Channels.write(Channels.java:611)
        at org.jboss.netty.channel.Channels.write(Channels.java:578)
        at com.alibaba.otter.canal.server.netty.NettyUtils.write(NettyUtils.java:48)
        at com.alibaba.otter.canal.server.netty.handler.SessionHandler.messageReceived(SessionHandler.java:261)
        at org.jboss.netty.handler.timeout.IdleStateAwareChannelHandler.handleUpstream(IdleStateAwareChannelHandler.java:48)
        at org.jboss.netty.handler.timeout.IdleStateHandler.messageReceived(IdleStateHandler.java:276)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:302)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.unfoldAndfireMessageReceived(ReplayingDecoder.java:526)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:507)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:444)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:274)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:261)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:350)
        at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:281)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:201)
        at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

**Comment by wjlzk1** [comment]
2021-06-17 19:58:39.716 [Thread-14] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - stop CannalInstance for null-leiniao_car
2021-06-17 19:58:40.092 [Thread-14] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - stop successful....
2021-06-17 19:58:44.327 [New I/O server worker #1-4] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Loading properties file from class path resource [canal.properties]
2021-06-17 19:58:44.353 [New I/O server worker #1-4] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Loading properties file from class path resource [leiniao_car/instance.properties]
2021-06-17 19:58:44.437 [New I/O server worker #1-4] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Loading properties file from class path resource [canal.properties]
2021-06-17 19:58:44.438 [New I/O server worker #1-4] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Loading properties file from class path resource [leiniao_car/instance.properties]
2021-06-17 19:58:44.481 [New I/O server worker #1-4] ERROR com.alibaba.druid.pool.DruidDataSource - testWhileIdle is true, validationQuery not set
2021-06-17 19:58:44.630 [New I/O server worker #1-4] INFO  c.a.otter.canal.instance.spring.CanalInstanceWithSpring - start CannalInstance for 1-leiniao_car
2021-06-17 19:58:44.646 [New I/O server worker #1-4] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table filter : ^leiniao_car.*\..*$
2021-06-17 19:58:44.646 [New I/O server worker #1-4] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table black filter :
2021-06-17 19:58:44.649 [New I/O server worker #1-4] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - subscribe filter change to leiniao_car.*\..*
2021-06-17 19:58:44.649 [New I/O server worker #1-4] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table filter : ^leiniao_car.*\..*$
2021-06-17 19:58:44.649 [New I/O server worker #1-4] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - start successful....
2021-06-17 19:58:44.674 [New I/O server worker #1-3] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - subscribe filter change to leiniao_car.*\..*
2021-06-17 19:58:44.674 [New I/O server worker #1-3] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table filter : ^leiniao_car.*\..*$
2021-06-17 19:58:44.680 [destination = leiniao_car , address = rm-2zeitfy0v0132435633150.mysql.rds.aliyuncs.com/172.19.0.152:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> begin to find start position, it will be long time for reset or first position
2021-06-17 19:58:44.680 [destination = leiniao_car , address = rm-2zeitfy0v0132435633150.mysql.rds.aliyuncs.com/172.19.0.152:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - prepare to find start position just last position
 {"identity":{"slaveId":-1,"sourceAddress":{"address":"rm-***************.mysql.rds.aliyuncs.com","port":3306}},"postion":{"gtid":"","included":false,"journalName":"mysql-bin.003256","position":26322182,"serverId":2575659630,"timestamp":1623931113000}}
2021-06-17 19:58:45.407 [destination = leiniao_car , address = rm-**************0.mysql.rds.aliyuncs.com/172.19.0.152:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> find start position successfully, EntryPosition[included=false,journalName=mysql-bin.003256,position=26322182,serverId=2575659630,gtid=,timestamp=1623931113000] cost : 652ms , the next step is binlog dump
