### ISSUE TITLE
求助！！deployer-1.1.5 mysql5.7启动 报 Could not find first log file name in binary log index file，example文件夹下只留instance.properties 问题没有解决 

### ISSUE THREAD

**Issue by jikehuiyin** [alibaba/canal#3649]
## Question
mysql 5.7 版本：
 my.cnf 文件配置：
[mysql]
default-character-set = utf8mb4
[mysqld]
basedir = /usr/local/mysql
datadir = /usr/local/mysql/data
port = 3306
log_bin = /usr/local/mysql/data/mysql-bin
binlog_format = Row
server_id = 1
sync_binlog = 1
#expire_logs_days = 2    #5.7版本 binlog删除时间
#binlog_expire_logs_seconds   #8.0版本binlog删除时间
socket = /tmp/mysql.sock
max_connections = 64726
max_connect_errors = 100
#binlog-do-db = hotel_shop
#binlog-do-db = iworks10
max_allowed_packet = 16M
skip-name-resolve
innodb_buffer_pool_size = 3221225472 #设置大小3G
table_open_cache = 400
#slow_query_log=0  #开启慢查询
#long_query_time=10 #慢查询时间
log_queries_not_using_indexes
character-set-client-handshake = FALSE 
character-set-server = utf8mb4 
collation-server = utf8mb4_unicode_ci 
init_connect='SET NAMES utf8mb4'

启动报以下错误：
2021-07-09 21:17:08.351 [destination = example , address = /10.0.20.209:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address /10.0.20.209:3306 has an error, retrying. caused by 
com.alibaba.otter.canal.parse.exception.PositionNotFoundException: can't find start position for example
2021-07-09 21:17:08.352 [destination = example , address = /10.0.20.209:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[com.alibaba.otter.canal.parse.exception.PositionNotFoundException: can't find start position for example
]
2021-07-09 21:17:22.771 [destination = example , address = /10.0.20.209:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> begin to find start position, it will be long time for reset or first position
2021-07-09 21:17:22.771 [destination = example , address = /10.0.20.209:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - prepare to find start position just show master status
2021-07-09 21:17:22.776 [destination = example , address = /10.0.20.209:3306 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - I/O error while reading from client socket
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102) ~[canal.parse-1.1.5.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.seek(MysqlConnection.java:151) [canal.parse-1.1.5.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findAsPerTimestampInSpecificLogFile(MysqlEventParser.java:761) [canal.parse-1.1.5.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findEndPositionWithMasterIdAndTimestamp(MysqlEventParser.java:383) [canal.parse-1.1.5.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPositionInternal(MysqlEventParser.java:438) [canal.parse-1.1.5.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPosition(MysqlEventParser.java:357) [canal.parse-1.1.5.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:191) [canal.parse-1.1.5.jar:na]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_151]
2021-07-09 21:17:22.777 [destination = example , address = /10.0.20.209:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ERROR ## findAsPerTimestampInSpecificLogFile has an error
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102) ~[canal.parse-1.1.5.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.seek(MysqlConnection.java:151) ~[canal.parse-1.1.5.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findAsPerTimestampInSpecificLogFile(MysqlEventParser.java:761) [canal.parse-1.1.5.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findEndPositionWithMasterIdAndTimestamp(MysqlEventParser.java:383) [canal.parse-1.1.5.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPositionInternal(MysqlEventParser.java:438) [canal.parse-1.1.5.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPosition(MysqlEventParser.java:357) [canal.parse-1.1.5.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:191) [canal.parse-1.1.5.jar:na]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_151]
2021-07-09 21:17:22.777 [destination = example , address = /10.0.20.209:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address /10.0.20.209:3306 has an error, retrying. caused by 
com.alibaba.otter.canal.parse.exception.PositionNotFoundException: can't find start position for example
2021-07-09 21:17:22.777 [destination = example , address = /10.0.20.209:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[com.alibaba.otter.canal.parse.exception.PositionNotFoundException: can't find start position for example

**Comment by berace** [comment]
开启binlog了么

**Comment by jikehuiyin** [comment]
> 开启binlog了么
有开启 binlog的 以下是 5.7 my.cnf配置
mysql 5.7 版本：
my.cnf 文件配置：
[mysql]
default-character-set = utf8mb4
[mysqld]
basedir = /usr/local/mysql
datadir = /usr/local/mysql/data
port = 3306
log_bin = /usr/local/mysql/data/mysql-bin
binlog_format = Row
server_id = 1
sync_binlog = 1
#expire_logs_days = 2 #5.7版本 binlog删除时间
#binlog_expire_logs_seconds #8.0版本binlog删除时间
socket = /tmp/mysql.sock
max_connections = 64726
max_connect_errors = 100
#binlog-do-db = hotel_shop
#binlog-do-db = iworks10
max_allowed_packet = 16M
skip-name-resolve
innodb_buffer_pool_size = 3221225472 #设置大小3G
table_open_cache = 400
#slow_query_log=0 #开启慢查询
#long_query_time=10 #慢查询时间
log_queries_not_using_indexes
character-set-client-handshake = FALSE
character-set-server = utf8mb4
collation-server = utf8mb4_unicode_ci
init_connect='SET NAMES utf8mb4'

**Comment by berace** [comment]
binlog是不是被删掉了

**Comment by zhoujiale** [comment]
请问这个最后是怎么解决的

**Comment by berace** [comment]
> 请问这个最后是怎么解决的

binlog不存在了
