### ISSUE TITLE
canal-adapter启动一会后同步es数据失败

### ISSUE THREAD

**Issue by zhanghongzheng6** [alibaba/canal#3654]
* canal version 1.1.5
* mysql version 

### Issue Description
canal-adapter启动一会后同步es数据失败，使用的es6

开始后偶尔报错
2021-07-12 20:38:09.773 [pool-6-thread-1] ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - ES sync commit error [product/ULqPJgFHSLq9txAHTHJOPA][[product][0]] ElasticsearchException[Elasticsearch exception [type=version_conflict_engine_exception, reason=[productDoc][196589523311145017]: version conflict, required seqNo [5200], primary term [1]. current document has seqNo [5210] and primary term [1]]]
java.lang.RuntimeException: ES sync commit error [product/ULqPJgFHSLq9txAHTHJOPA][[product][0]] ElasticsearchException[Elasticsearch exception [type=version_conflict_engine_exception, reason=[productDoc][196589523311145017]: version conflict, required seqNo [5200], primary term [1]. current document has seqNo [5210] and primary term [1]]]
	at com.alibaba.otter.canal.client.adapter.es6x.support.ESConnection$ES6xBulkResponse.processFailBulkResponse(ESConnection.java:476) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.es6x.support.ES6xTemplate.commit(ES6xTemplate.java:178) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.es.core.service.ESSyncService.commit(ESSyncService.java:877) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.es.core.ESAdapter.sync(ESAdapter.java:97) ~[na:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.batchSync(AdapterProcessor.java:139) ~[client-adapter.launcher-1.1.5.jar:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.lambda$null$1(AdapterProcessor.java:97) ~[client-adapter.launcher-1.1.5.jar:na]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891) ~[na:1.8.0_181]
	at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.lambda$null$2(AdapterProcessor.java:94) ~[client-adapter.launcher-1.1.5.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]

1个小时后一直报这个错误，每次重启adapter后会好一段时间
2021-07-12 21:56:32.961 [pool-6-thread-1] ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - null
java.lang.NullPointerException: null
	at org.elasticsearch.action.bulk.BulkRequest.validate(BulkRequest.java:571) ~[na:na]
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1248) ~[na:na]
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1240) ~[na:na]
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1223) ~[na:na]
	at org.elasticsearch.client.RestHighLevelClient.bulk(RestHighLevelClient.java:340) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.es6x.support.ESConnection$ES6xBulkRequest.bulk(ESConnection.java:428) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.es6x.support.ES6xTemplate.commit(ES6xTemplate.java:176) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.es.core.service.ESSyncService.commit(ESSyncService.java:877) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.es.core.ESAdapter.sync(ESAdapter.java:97) ~[na:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.batchSync(AdapterProcessor.java:139) ~[client-adapter.launcher-1.1.5.jar:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.lambda$null$1(AdapterProcessor.java:97) ~[client-adapter.launcher-1.1.5.jar:na]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891) ~[na:1.8.0_181]
	at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.lambda$null$2(AdapterProcessor.java:94) ~[client-adapter.launcher-1.1.5.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]

**Comment by zhanghongzheng6** [comment]
我把es存储方式由rest改为了transport正在观察是否会报错

**Comment by ipoyang7** [comment]
解决了吗？我使用rest 和transport都有这个错误

**Comment by zhanghongzheng6** [comment]
我用的1.1.5未定版本改成transport 解决了 @ipoyang7

**Comment by alvaj** [comment]
解决了吗？

我也碰到这种问题了。。在mq堆积大量数据的时候会出现，重启之后解决。
