### ISSUE TITLE
Canal1.1.4订阅Mysql8.0库，出现以下异常，大佬求帮助

### ISSUE THREAD

**Issue by xiaoyu-peng** [alibaba/canal#3659]
2021-07-14 18:12:00.665 [destination = canal-staging-sg-2 , address = /120.25.225.226:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - connect MysqlConnection to /120.25.225.226:3306...
2021-07-14 18:12:00.713 [destination = canal-staging-sg-2 , address = /120.25.225.226:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - handshake initialization packet received, prepare the client authentication packet to send
2021-07-14 18:12:00.713 [destination = canal-staging-sg-2 , address = /120.25.225.226:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - client authentication packet is sent out.
2021-07-14 18:12:00.761 [destination = canal-staging-sg-2 , address = /120.25.225.226:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - auth switch response packet is sent out.
2021-07-14 18:12:00.994 [destination = canal-staging-sg-2 , address = /120.25.225.226:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - connect MysqlConnection to /120.25.225.226:3306...
2021-07-14 18:12:01.032 [destination = canal-staging-sg-2 , address = /120.25.225.226:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - handshake initialization packet received, prepare the client authentication packet to send
2021-07-14 18:12:01.032 [destination = canal-staging-sg-2 , address = /120.25.225.226:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - client authentication packet is sent out.
2021-07-14 18:12:01.070 [destination = canal-staging-sg-2 , address = /120.25.225.226:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - auth switch response packet is sent out.
2021-07-14 18:12:01.147 [destination = canal-staging-sg-2 , address = /120.25.225.226:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> begin to find start position, it will be long time for reset or first position
2021-07-14 18:12:01.147 [destination = canal-staging-sg-2 , address = /120.25.225.226:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - prepare to find start position just last position
 {"identity":{"slaveId":-1,"sourceAddress":{"address":"120.25.225.226","port":3306}},"postion":{"gtid":"","included":false,"journalName":"binlog.000022","position":71942,"serverId":1,"timestamp":1626068950000}}
2021-07-14 18:12:01.158 [destination = canal-staging-sg-2 , address = /120.25.225.226:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> find start position successfully, EntryPosition[included=false,journalName=binlog.000022,position=71942,serverId=1,gtid=,timestamp=1626068950000] cost : 10ms , the next step is binlog dump
2021-07-14 18:12:01.158 [destination = canal-staging-sg-2 , address = /120.25.225.226:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - disConnect MysqlConnection to /120.25.225.226:3306...
2021-07-14 18:12:01.195 [destination = canal-staging-sg-2 , address = /120.25.225.226:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - connect MysqlConnection to /120.25.225.226:3306...
2021-07-14 18:12:01.246 [destination = canal-staging-sg-2 , address = /120.25.225.226:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - handshake initialization packet received, prepare the client authentication packet to send
2021-07-14 18:12:01.246 [destination = canal-staging-sg-2 , address = /120.25.225.226:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - client authentication packet is sent out.
2021-07-14 18:12:01.283 [destination = canal-staging-sg-2 , address = /120.25.225.226:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - auth switch response packet is sent out.
2021-07-14 18:12:01.661 [destination = canal-staging-sg-2 , address = /120.25.225.226:3306 , EventParser] INFO  c.a.otter.canal.parse.inbound.mysql.MysqlConnection - Register slave RegisterSlaveCommandPacket[reportHost=192.168.1.80,reportPort=34236,reportUser=case,reportPasswd=password,serverId=1560281089,command=21]
2021-07-14 18:12:01.698 [destination = canal-staging-sg-2 , address = /120.25.225.226:3306 , EventParser] INFO  c.a.otter.canal.parse.inbound.mysql.MysqlConnection - COM_BINLOG_DUMP with position:BinlogDumpCommandPacket[binlogPosition=71942,slaveServerId=1560281089,binlogFileName=binlog.000022,command=18]
2021-07-14 18:12:01.736 [MultiStageCoprocessor-other-canal-staging-sg-2-0] INFO  com.taobao.tddl.dbsync.binlog.LogEvent - common_header_len= 19, number_of_event_types= 44
2021-07-14 18:12:01.774 [destination = canal-staging-sg-2 , address = /120.25.225.226:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address 120.25.225.226/120.25.225.226:3306 has an error, retrying. caused by 
com.alibaba.otter.canal.parse.exception.CanalParseException: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: java.lang.IllegalArgumentException: limit excceed: 369
	at com.taobao.tddl.dbsync.binlog.LogBuffer.getUint8(LogBuffer.java:235) ~[canal.parse.dbsync-1.1.4.jar:na]
	at com.taobao.tddl.dbsync.binlog.LogBuffer.getPackedLong(LogBuffer.java:1024) ~[canal.parse.dbsync-1.1.4.jar:na]
	at com.taobao.tddl.dbsync.binlog.JsonDiffConversion.print_json_diff(JsonDiffConversion.java:48) ~[canal.parse.dbsync-1.1.4.jar:na]
	at com.taobao.tddl.dbsync.binlog.event.RowsLogBuffer.fetchValue(RowsLogBuffer.java:1073) ~[canal.parse.dbsync-1.1.4.jar:na]
	at com.taobao.tddl.dbsync.binlog.event.RowsLogBuffer.nextValue(RowsLogBuffer.java:125) ~[canal.parse.dbsync-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseOneRow(LogEventConvert.java:726) ~[canal.parse-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseRowsEvent(LogEventConvert.java:549) ~[canal.parse-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$DmlParserStage.onEvent(MysqlMultiStageCoprocessor.java:330) ~[canal.parse-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$DmlParserStage.onEvent(MysqlMultiStageCoprocessor.java:316) ~[canal.parse-1.1.4.jar:na]
	at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) ~[disruptor-3.4.2.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
2021-07-14 18:12:01.775 [destination = canal-staging-sg-2 , address = /120.25.225.226:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - disConnect MysqlConnection to /120.25.225.226:3306...
2021-07-14 18:12:01.775 [destination = canal-staging-sg-2 , address = /120.25.225.226:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - disConnect MysqlConnection to /120.25.225.226:3306...
2021-07-14 18:12:01.815 [destination = canal-staging-sg-2 , address = /120.25.225.226:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - connect MysqlConnection to /120.25.225.226:3306...
2021-07-14 18:12:01.848 [destination = canal-staging-sg-2 , address = /120.25.225.226:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - handshake initialization packet received, prepare the client authentication packet to send
2021-07-14 18:12:01.849 [destination = canal-staging-sg-2 , address = /120.25.225.226:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - client authentication packet is sent out.
2021-07-14 18:12:01.885 [destination = canal-staging-sg-2 , address = /120.25.225.226:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - auth switch response packet is sent out.
2021-07-14 18:12:01.959 [destination = canal-staging-sg-2 , address = /120.25.225.226:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - KILL DUMP 362269 failure
java.io.IOException: ErrorPacket [errorNumber=1094, fieldCount=-1, message=Unknown thread id: 362269, sqlState=HY000, sqlStateMarker=#]
 with command: KILL CONNECTION 362269
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlUpdateExecutor.update(MysqlUpdateExecutor.java:49) ~[canal.parse.driver-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.disconnect(MysqlConnector.java:113) ~[canal.parse.driver-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.disconnect(MysqlConnection.java:97) [canal.parse-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:315) [canal.parse-1.1.4.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
2021-07-14 18:12:01.959 [destination = canal-staging-sg-2 , address = /120.25.225.226:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - disConnect MysqlConnection to /120.25.225.226:3306...

**Comment by xiaoyu-peng** [comment]
目前定位到问题：MySQL8库中存在字段类型为json格式导致此异常，后续定位中

**Comment by xiaoyu-peng** [comment]
后续定位，Canal支持订阅Json类型字段，问题原因是由于字段设置的异常默认值导致

**Comment by duguwo** [comment]
楼主怎么解决的呢
