### ISSUE TITLE
这是BUG吗：canal解析错误fetch failed by table meta:`schemeName`.`tableName`

### ISSUE THREAD

**Issue by whyliyu** [alibaba/canal#366]
这个问题和#358类似
如果canal从一个数据库binglog的第一条记录开始读取，那么canal在解析过程中，可能会因为在解析到某条binlog记录时，该记录对应的表被删掉了，而在binlog解析过程中canal会发送一条desc "schemeName.tableName"的sql：
private TableMeta getTableMeta0(String fullname) throws IOException {
    ResultSetPacket packet = connection.query("desc " + fullname);
    return new TableMeta(fullname, parserTableMeta(packet));
}
而对应的表已经被删掉，这时候就会抛出这个异常，导致binlog读取无法继续下去

不知道这是不是个bug？或者是通过配置的方法解决？有没有阿里的大佬出来解答一下？

**Comment by whyliyu** [comment]
具体日志是这样的：
2017-08-10 14:26:56.593 [destination = 10.160.246.137-1379 , address = /10.160.246.137:1379 , EventParser]369 WARN  c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - ERROR ## parse this event has an error , last position : [EntryPosition[included=false,journalName=
mysql-bin.000003,position=46788142,serverId=1092,timestamp=1493132987000]]
com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: com.google.common.collect.ComputationException: com.alibaba.otter.canal.parse.exception.CanalParseException: fetch failed by table meta:`yx_expert`.`bak_TB_YX_ZXJ_ADVICE_COLLECT_ACTIVITY`
Caused by: com.google.common.collect.ComputationException: com.alibaba.otter.canal.parse.exception.CanalParseException: fetch failed by table meta:`yx_expert`.`bak_TB_YX_ZXJ_ADVICE_COLLECT_ACTIVITY`
        at com.google.common.collect.MapMaker$ComputingMapAdapter.get(MapMaker.java:889)
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.TableMetaCache.getTableMeta(TableMetaCache.java:78)
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.getTableMeta(LogEventConvert.java:677)
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseRowsEvent(LogEventConvert.java:362)
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:108)
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:62)
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser.parseAndProfilingIfNecessary(AbstractEventParser.java:326)
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3$1.sink(AbstractEventParser.java:176)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:130)
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: fetch failed by table meta:`yx_expert`.`bak_TB_YX_ZXJ_ADVICE_COLLECT_ACTIVITY`
Caused by: java.io.IOException: ErrorPacket [errorNumber=1146, fieldCount=-1, message=Table 'yx_expert.bak_TB_YX_ZXJ_ADVICE_COLLECT_ACTIVITY' doesn't exist, sqlState=42S02, sqlStateMarker=#]
 with command: desc `yx_expert`.`bak_TB_YX_ZXJ_ADVICE_COLLECT_ACTIVITY`
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlQueryExecutor.query(MysqlQueryExecutor.java:60)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.query(MysqlConnection.java:73)
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.TableMetaCache.getTableMeta0(TableMetaCache.java:105)
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.TableMetaCache.access$000(TableMetaCache.java:26)
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.TableMetaCache$1.apply(TableMetaCache.java:51)
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.TableMetaCache$1.apply(TableMetaCache.java:42)
        at com.google.common.collect.ComputingConcurrentHashMap$ComputingValueReference.compute(ComputingConcurrentHashMap.java:356)
        at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.compute(ComputingConcurrentHashMap.java:182)
        at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.getOrCompute(ComputingConcurrentHashMap.java:151)
        at com.google.common.collect.ComputingConcurrentHashMap.getOrCompute(ComputingConcurrentHashMap.java:67)
        at com.google.common.collect.MapMaker$ComputingMapAdapter.get(MapMaker.java:885)
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.TableMetaCache.getTableMeta(TableMetaCache.java:78)
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.getTableMeta(LogEventConvert.java:677)
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseRowsEvent(LogEventConvert.java:362)
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:108)
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:62)
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser.parseAndProfilingIfNecessary(AbstractEventParser.java:326)
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3$1.sink(AbstractEventParser.java:176)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:130)
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209)
        at java.lang.Thread.run(Thread.java:745)

**Comment by leslie-chu** [comment]
什么问题 这是 解决了吗？

**Comment by whyliyu** [comment]
现在解决了，可以通过配置filterTableError=true来忽略掉这个异常，这样instance的线程就可以继续运行下去

**Comment by liutizhong** [comment]
我也遇到这个问题了,请问这个filterTableError=true 在哪个地方加的,直接添加filterTableError=true?

**Comment by whyliyu** [comment]
@liutizhong 我使用的是CanalInstanceWithManager，只要在它的配置CanalParameter中设置就行了,代码大体上是这样：
CanalParameter parameter = new CanalParameter;
parameter.setFilterTableError(true);
Canal canal = new Canal();
canal.setCanalParameter(parameter);
最后在new CanalInstance时：
new CanalInstanceWithManager(canal, filter);

**Comment by yuxie** [comment]
@liutizhong 可以直接在配置文件配置
canal.instance.filter.table.error =true

**Comment by leslie-chu** [comment]
6666666666😁

2017-11-22 11:41 GMT+08:00 yuxie <notifications@github.com>:

**Comment by chenwj1103** [comment]
牛逼

**Comment by onepiece-yang** [comment]
我也遇到这个问题了，otter配置文件里面该加在哪？
canal.instance.filter.table.error =true去忽略表错误

**Comment by stulzq** [comment]
谢谢分享，直接修改配置文件canal.instance.filter.table.error =true 忽略了异常

**Comment by qinlz-1** [comment]
> @liutizhong 可以直接在配置文件配置 canal.instance.filter.table.error =true

忽略异常，会不会导致一些其他异常也被被隐藏，从而导致问题没有被发现出现数据丢失

**Comment by fangchieh** [comment]
> 

提的好，我也遇到了

**Comment by GabbyMrH** [comment]
提得好，我也遇到了，解决了。
