### ISSUE TITLE
启动canal-adapter这个错误，如何解决？

### ISSUE THREAD

**Issue by Robert613** [alibaba/canal#3680]
Caused by: java.lang.ClassCastException: com.alibaba.druid.pool.DruidDataSource cannot be cast to com.alibaba.druid.pool.DruidDataSource
	at com.alibaba.otter.canal.client.adapter.es.core.ESAdapter.addSyncConfigToCache(ESAdapter.java:146) ~[client-adapter.es6x-1.1.5-jar-with-dependencies.jar:na]
	at com.alibaba.otter.canal.client.adapter.es.core.ESAdapter.init(ESAdapter.java:75) ~[client-adapter.es6x-1.1.5-jar-with-dependencies.jar:na]
	... 43 common frames omitted
2021-07-22 17:33:41.923 [main] INFO  c.alibaba.otter.canal.connector.core.spi.ExtensionLoader - extension classpath dir: E:\canal\canal-adapter\plugin
2021-07-22 17:33:41.942 [main] INFO  c.a.o.canal.adapter.launcher.loader.CanalAdapterLoader - Start adapter for canal-client mq topic: product-g1 succeed
2021-07-22 17:33:41.942 [Thread-5] INFO  c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - =============> Start to connect destination: product <=============
2021-07-22 17:33:41.942 [main] INFO  c.a.o.canal.adapter.launcher.loader.CanalAdapterService - ## the canal client adapters are running now ......
2021-07-22 17:33:41.946 [main] INFO  org.apache.coyote.http11.Http11NioProtocol - Starting ProtocolHandler ["http-nio-8081"]
2021-07-22 17:33:41.947 [main] INFO  org.apache.tomcat.util.net.NioSelectorPool - Using a shared selector for servlet write/read
2021-07-22 17:33:41.957 [main] INFO  o.s.boot.web.embedded.tomcat.TomcatWebServer - Tomcat started on port(s): 8081 (http) with context path ''
2021-07-22 17:33:41.959 [main] INFO  c.a.otter.canal.adapter.launcher.CanalAdapterApplication - Started CanalAdapterApplication in 2.723 seconds (JVM running for 3.125)
2021-07-22 17:33:41.982 [Thread-5] ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - process error!
com.alibaba.otter.canal.protocol.exception.CanalClientException: failed to subscribe with reason: something goes wrong with channel:[id: 0x11a708cc, /127.0.0.1:50781 => /127.0.0.1:11111], exception=com.alibaba.otter.canal.server.exception.CanalServerException: destination:product should start first

	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.subscribe(SimpleCanalConnector.java:249) ~[na:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.subscribe(SimpleCanalConnector.java:226) ~[na:na]
	at com.alibaba.otter.canal.connector.tcp.consumer.CanalTCPConsumer.connect(CanalTCPConsumer.java:64) ~[na:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.process(AdapterProcessor.java:184) ~[client-adapter.launcher-1.1.5.jar:na]
	at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_151]
2021-07-22 17:33:42.992 [Thread-5] INFO  c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - =============> Start to connect destination: product <=============
2021-07-22 17:33:42.993 [Thread-5] ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - process error!
com.alibaba.otter.canal.protocol.exception.CanalClientException: failed to subscribe with reason: something goes wrong with channel:[id: 0x11a708cc, /127.0.0.1:50781 => /127.0.0.1:11111], exception=com.alibaba.otter.canal.server.exception.CanalServerException: destination:product should start first

	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.subscribe(SimpleCanalConnector.java:249) ~[na:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.subscribe(SimpleCanalConnector.java:226) ~[na:na]
	at com.alibaba.otter.canal.connector.tcp.consumer.CanalTCPConsumer.connect(CanalTCPConsumer.java:64) ~[na:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.process(AdapterProcessor.java:184) ~[client-adapter.launcher-1.1.5.jar:na]
	at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_151]
2021-07-22 17:33:44.002 [Thread-5] INFO  c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - =============> Start to connect destination: product <=============
2021-07-22 17:33:44.007 [Thread-5] ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - process error!
com.alibaba.otter.canal.protocol.exception.CanalClientException: failed to subscribe with reason: something goes wrong with channel:[id: 0x11a708cc, /127.0.0.1:50781 => /127.0.0.1:11111], exception=com.alibaba.otter.canal.server.exception.CanalServerException: destination:product should start first

	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.subscribe(SimpleCanalConnector.java:249) ~[na:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.subscribe(SimpleCanalConnector.java:226) ~[na:na]
	at com.alibaba.otter.canal.connector.tcp.consumer.CanalTCPConsumer.connect(CanalTCPConsumer.java:64) ~[na:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.process(AdapterProcessor.java:184) ~[client-adapter.launcher-1.1.5.jar:na]
	at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_151]

**Comment by arthasking123** [comment]
hosts怎么写的?

**Comment by Robert613** [comment]
> hosts怎么写的?

**Comment by Robert613** [comment]
> > hosts怎么写的?

![image](https://user-images.githubusercontent.com/49790339/126623000-79a44886-d354-4a2d-b505-da8e36e54fcb.png)

**Comment by Robert613** [comment]
还没有解决

**Comment by arthasking123** [comment]
DruidDataSource classLoader in put:sun.misc.Launcher$AppClassLoader@18b4aac2
DruidDataSource classLoader in get:com.alibaba.otter.canal.client.adapter.support.URLClassExtensionLoader@2ba1209b

put和get时的classloader不同导致

**Comment by axapi-shichuan** [comment]
![image](https://user-images.githubusercontent.com/10141595/127149855-1c9b03c9-746e-4ff2-8fbc-8144505f1df1.png)
