### ISSUE TITLE
client断开连接后再也连不上canal

### ISSUE THREAD

**Issue by G-shp** [alibaba/canal#3697]
canal使用docker部署的1.1.4版本
当使用getWithoutAck(var1, 0, var3)阻塞获取数据时，如果长时间（大概40s）没有数据变化，
就会抛出异常socket断开连接，过后无论如何都连不上canal了，除非再重启canal

**Comment by G-shp** [comment]
但是使用循环去不断的getWithoutAck就不会出现这种情况

**Comment by G-shp** [comment]
Exception in thread "main" com.alibaba.otter.canal.protocol.exception.CanalClientException: java.net.SocketTimeoutException
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.getWithoutAck(SimpleCanalConnector.java:325)
	at com.gsp.test.base.canal.SimpleCanalClientExample.main(SimpleCanalClientExample.java:34)
Caused by: java.net.SocketTimeoutException
	at sun.nio.ch.SocketAdaptor$SocketInputStream.read(SocketAdaptor.java:211)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
	at java.nio.channels.Channels$ReadableByteChannelImpl.read(Channels.java:385)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.read(SimpleCanalConnector.java:411)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.readNextPacket(SimpleCanalConnector.java:401)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.readNextPacket(SimpleCanalConnector.java:385)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.receiveMessages(SimpleCanalConnector.java:330)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.getWithoutAck(SimpleCanalConnector.java:323)

**Comment by wangxin-200** [comment]
有解决的办法吗？

**Comment by sunxien** [comment]
问题描述：发生 SocketTimeoutException: null  的原因之一是：Canal Instance 没有找到位点，可以在 {instance}_stdout.log 查找错误内容：can't find position, retrying. 通过 `tail -f` 可以看到程序一直在重试并打印该日志。  
关键逻辑：在 `AbstractEventParser.java` 程序不断重试查找binlog位点，Adapter调用 getWithoutAck 会出现等待超时。
解决办法：Adapter 判断 SocketTimeoutException: null 则挂起同步任务，用户重置正确的binlog位点后，再重新启动任务。
