### ISSUE TITLE
canal 启动后报空指针异常

### ISSUE THREAD

**Issue by MINGHUE** [alibaba/canal#3710]
## 环境
canal：v1.1.4
mysql：8.0.22
jdk：1.8.0
## 配置信息
```properties
canal.instance.gtidon=false
# position info
canal.instance.master.address=192.168.37.129:3306
canal.instance.master.journal.name= mysql-bin.000001
canal.instance.master.position= 156
canal.instance.master.timestamp=
canal.instance.master.gtid=
# username/password
canal.instance.dbUsername=canal
canal.instance.dbPassword=canal
canal.instance.connectionCharset = UTF-8
canal.instance.enableDruid=false
canal.instance.filter.regex=.*\\..*
```

## 错误代码
```
2021-08-05 23:54:13.186 [destination = example , address = /192.168.37.129:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsB
2021-08-05 23:54:13.245 [destination = example , address = /192.168.37.129:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsB
2021-08-05 23:54:13.819 [destination = example , address = /192.168.37.129:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsB
java.lang.NullPointerException: null
	at com.alibaba.fastsql.sql.visitor.SQLASTOutputVisitor.visit(SQLASTOutputVisitor.java:5117) ~[fastsql-2.0.0_preview_973.jar:2
	at com.alibaba.fastsql.sql.ast.statement.SQLCheck.accept0(SQLCheck.java:48) ~[fastsql-2.0.0_preview_973.jar:2.0.0_preview_973
	at com.alibaba.fastsql.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:48) ~[fastsql-2.0.0_preview_973.jar:2.0.0_preview_973]
	at com.alibaba.fastsql.sql.visitor.SQLASTOutputVisitor.printTableElements(SQLASTOutputVisitor.java:3409) ~[fastsql-2.0.0_prev
	at com.alibaba.fastsql.sql.visitor.SQLASTOutputVisitor.visit(SQLASTOutputVisitor.java:8873) ~[fastsql-2.0.0_preview_973.jar:2
	at com.alibaba.fastsql.sql.dialect.mysql.ast.statement.MySqlCreateTableStatement.accept0(MySqlCreateTableStatement.java:125) 
	at com.alibaba.fastsql.sql.dialect.mysql.ast.statement.MySqlCreateTableStatement.accept0(MySqlCreateTableStatement.java:85) ~
	at com.alibaba.fastsql.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:48) ~[fastsql-2.0.0_preview_973.jar:2.0.0_preview_973]
	at com.alibaba.fastsql.sql.ast.SQLObjectImpl.output(SQLObjectImpl.java:89) ~[fastsql-2.0.0_preview_973.jar:2.0.0_preview_973]
	at com.alibaba.fastsql.sql.ast.SQLObjectImpl.output(SQLObjectImpl.java:74) ~[fastsql-2.0.0_preview_973.jar:2.0.0_preview_973]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta.snapshot(MemoryTableMeta.java:150) ~[canal.parse-1.1.4.ja
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.applySnapshotToDB(DatabaseTableMeta.java:301) ~[canal.p
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:184) ~[canal.parse-1.1.
	at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:137) ~
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:200) ~[canal.parse-1.1.4.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_292]
2021-08-05 23:54:13.820 [destination = example , address = /192.168.37.129:3306 , EventParser] ERROR com.alibaba.otter.canal.common.a
	at com.alibaba.fastsql.sql.visitor.SQLASTOutputVisitor.visit(SQLASTOutputVisitor.java:5117)
	at com.alibaba.fastsql.sql.ast.statement.SQLCheck.accept0(SQLCheck.java:48)
	at com.alibaba.fastsql.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:48)
	at com.alibaba.fastsql.sql.visitor.SQLASTOutputVisitor.printTableElements(SQLASTOutputVisitor.java:3409)
	at com.alibaba.fastsql.sql.visitor.SQLASTOutputVisitor.visit(SQLASTOutputVisitor.java:8873)
	at com.alibaba.fastsql.sql.dialect.mysql.ast.statement.MySqlCreateTableStatement.accept0(MySqlCreateTableStatement.java:125)
	at com.alibaba.fastsql.sql.dialect.mysql.ast.statement.MySqlCreateTableStatement.accept0(MySqlCreateTableStatement.java:85)
	at com.alibaba.fastsql.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:48)
	at com.alibaba.fastsql.sql.ast.SQLObjectImpl.output(SQLObjectImpl.java:89)
	at com.alibaba.fastsql.sql.ast.SQLObjectImpl.output(SQLObjectImpl.java:74)
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta.snapshot(MemoryTableMeta.java:150)
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.applySnapshotToDB(DatabaseTableMeta.java:301)
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:184)
	at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:137)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:200)
	at java.lang.Thread.run(Thread.java:748)
]

```

**Comment by code19971001** [comment]
最终是如何解决的？？

**Comment by code19971001** [comment]
同样的错，尝试了mysql5.6是可以的。准备升级canal试一下。
