### ISSUE TITLE
NegativeArraySizeException错误是什么原因导致

### ISSUE THREAD

**Issue by killerddd3** [alibaba/canal#3721]
## Question

2021-07-19 19:22:29.336 [New I/O server worker #1-15] ERROR c.a.otter.canal.server.netty.handler.SessionHandler - something goes wrong with channel:[id: 0x71a47f31, /123.160.221.8:34816 => /10.60.79.68:9877], exception=java.lang.NegativeArraySizeException
        at org.jboss.netty.buffer.HeapChannelBuffer.<init>(HeapChannelBuffer.java:47)
        at org.jboss.netty.buffer.BigEndianHeapChannelBuffer.<init>(BigEndianHeapChannelBuffer.java:39)
        at org.jboss.netty.buffer.ChannelBuffers.buffer(ChannelBuffers.java:139)
        at org.jboss.netty.buffer.HeapChannelBufferFactory.getBuffer(HeapChannelBufferFactory.java:73)
        at org.jboss.netty.buffer.AbstractChannelBuffer.readBytes(AbstractChannelBuffer.java:306)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoderBuffer.readBytes(ReplayingDecoderBuffer.java:362)
        at com.alibaba.otter.canal.server.netty.handler.FixedHeaderFrameDecoder.decode(FixedHeaderFrameDecoder.java:19)
        at com.alibaba.otter.canal.server.netty.handler.FixedHeaderFrameDecoder.decode(FixedHeaderFrameDecoder.java:15)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:471)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:444)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:274)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:261)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:350)
        at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:281)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:201)
        at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by alexyangxiaoniu** [comment]
请问解决了吗，我今天也遇到这个问题了

**Comment by lancedang** [comment]
me too
