### ISSUE TITLE
canal-adapter 全量同步失败

### ISSUE THREAD

**Issue by dmanbu** [alibaba/canal#3725]
### environment

* canal version: 1.1.4
* mysql version: 5.7.34

### Issue Description
通过命令 `curl http://127.0.0.1:38081/etl/rdb/mysql_01/mysql_01.yml -X POST` 执行全量同步失败
报错：
```
2021-08-16 14:00:24.320 [http-nio-38081-exec-1] DEBUG c.a.otter.canal.client.adapter.rdb.service.RdbEtlService - etl sql : SELECT * FROM mytest.null
2021-08-16 14:00:24.347 [http-nio-38081-exec-1] ERROR com.alibaba.otter.canal.client.adapter.support.Util - sqlRs has error, sql: SELECT COUNT(1) FROM ( SELECT * FROM mytest.null) _CNT  
2021-08-16 14:00:24.349 [http-nio-38081-exec-1] ERROR c.a.otter.canal.client.adapter.rdb.service.RdbEtlService - com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'mytest.null' doesn't exist
java.lang.RuntimeException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'mytest.null' doesn't exist
	at com.alibaba.otter.canal.client.adapter.support.Util.sqlRS(Util.java:65)
	at com.alibaba.otter.canal.client.adapter.support.AbstractEtlService.importData(AbstractEtlService.java:62)
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbEtlService.importData(RdbEtlService.java:43)
	at com.alibaba.otter.canal.client.adapter.rdb.RdbAdapter.etl(RdbAdapter.java:188)
	at com.alibaba.otter.canal.adapter.launcher.rest.CommonRest.etl(CommonRest.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:877)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:783)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:877)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'mytest.null' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3970)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3906)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2677)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2549)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1962)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:228)
	at com.alibaba.otter.canal.client.adapter.support.Util.sqlRS(Util.java:59)
	... 58 common frames omitted
```

不知道为啥，表名为 null
增量同步是没问题的

**Comment by MiLeskylimit** [comment]
mysql_01.yml 文件方便贴下不

**Comment by dmanbu** [comment]
> mysql_01.yml 文件方便贴下不

application.yml 配置
```
server:
  port: 38081
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

canal.conf:
  mode: tcp
  zookeeperHosts: 192.168.0.200:2181,192.168.0.201:2181,192.168.0.202:2181
  batchSize: 500
  syncBatchSize: 1000
  retries: -1
  timeout: 3000
  consumerProperties:
    canal.tcp.zookeeper.hosts: 192.168.0.200:2181,192.168.0.201:2181,192.168.0.202:2181
    canal.tcp.batch.size: 500
  srcDataSources:
    defaultDS:
      url: jdbc:mysql://192.168.0.202:3306/mytest?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
      username: canal
      password: canal
  canalAdapters:
  - instance: db-01
    groups:
    - groupId: g1
      outerAdapters:
      - name: rdb
        key: mysql_01
        properties:
          jdbc.driverClassName: com.mysql.jdbc.Driver
          jdbc.url: jdbc:mysql://192.168.0.203:3306/mytest?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
          jdbc.username: canal
          jdbc.password: canal
```

mysql_01.yml 配置
```
dataSourceKey: defaultDS
destination: db-01
groupId: g1
outerAdapterKey: mysql_01
concurrent: true
dbMapping:
  mirrorDb: true
  database: mytest
```

**Comment by dmanbu** [comment]
> > mysql_01.yml 文件方便贴下不
> 
> application.yml 配置
> 
> ```
> server:
>   port: 38081
> spring:
>   jackson:
>     date-format: yyyy-MM-dd HH:mm:ss
>     time-zone: GMT+8
>     default-property-inclusion: non_null
> 
> canal.conf:
>   mode: tcp
>   zookeeperHosts: 192.168.0.200:2181,192.168.0.201:2181,192.168.0.202:2181
>   batchSize: 500
>   syncBatchSize: 1000
>   retries: -1
>   timeout: 3000
>   consumerProperties:
>     canal.tcp.zookeeper.hosts: 192.168.0.200:2181,192.168.0.201:2181,192.168.0.202:2181
>     canal.tcp.batch.size: 500
>   srcDataSources:
>     defaultDS:
>       url: jdbc:mysql://192.168.0.202:3306/mytest?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
>       username: canal
>       password: canal
>   canalAdapters:
>   - instance: db-01
>     groups:
>     - groupId: g1
>       outerAdapters:
>       - name: rdb
>         key: mysql_01
>         properties:
>           jdbc.driverClassName: com.mysql.jdbc.Driver
>           jdbc.url: jdbc:mysql://192.168.0.203:3306/mytest?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
>           jdbc.username: canal
>           jdbc.password: canal
> ```
> 
> mysql_01.yml 配置
> 
> ```
> dataSourceKey: defaultDS
> destination: db-01
> groupId: g1
> outerAdapterKey: mysql_01
> concurrent: true
> dbMapping:
>   mirrorDb: true
>   database: mytest
> ```

@MiLeskylimit

**Comment by MiLeskylimit** [comment]
看下rdb关于yml的配置   https://github.com/alibaba/canal/tree/master/client-adapter  
看你的 yml文件应该是没指定目标表

dataSourceKey: defaultDS        # 源数据源的key, 对应上面配置的srcDataSources中的值
destination: example            # cannal的instance或者MQ的topic
outerAdapterKey: oracle1        # adapter key, 对应上面配置outAdapters中的key
concurrent: true                # 是否按主键hase并行同步, 并行同步的表必须保证主键不会更改及主键不能为其他同步表的外键!!
dbMapping:
  database: mytest              # 源数据源的database/shcema
  table: user                   # 源数据源表名
  targetTable: mytest.tb_user   # 目标数据源的库名.表名
  targetPk:                     # 主键映射
    id: id                      # 如果是复合主键可以换行映射多个
#  mapAll: true                 # 是否整表映射, 要求源表和目标表字段名一模一样 (如果targetColumns也配置了映射,则以targetColumns配置为准)
  targetColumns:                # 字段映射, 格式: 目标表字段: 源表字段, 如果字段名一样源表字段名可不填
    id:
    name:
    role_id:
    c_time:
    test1:

**Comment by dmanbu** [comment]
> 求源表和目标表字段名一模一样 (如果targetColumns也配置了映射,则以targe

mirrorDb 模式不可用么？如果配置单个 targetTable ，那如果我有上百张表，是不是需要配置的太多了？

**Comment by flowell** [comment]
1.1.5看源码，mirrorDb模式确实是不支持ETL的，ETL是针对单表，mirror模式下yml文件里没有表信息。
```
    /**
     * 导入数据
     */
    public EtlResult importData(List<String> params) {
        DbMapping dbMapping = config.getDbMapping();
        String sql = "SELECT * FROM " + dbMapping.getDatabase() + "." + dbMapping.getTable();
        return importData(sql, params);
    }
```

**Comment by mifashion** [comment]
> > 求源表和目标表字段名一模一样 (如果targetColumns也配置了映射,则以targe
> 
> mirrorDb 模式不可用么？如果配置单个 targetTable ，那如果我有上百张表，是不是需要配置的太多了？

我也觉得太不人性化了
