### ISSUE TITLE
dump address /a.b.c.d:XX has an error, retrying. caused by 

### ISSUE THREAD

**Issue by jimgreat** [alibaba/canal#3748]
一直运行正常，突然出现下面异常，重启canal后正常

java.lang.NullPointerException: null
	at java.net.InetSocketAddress.equals(InetSocketAddress.java:407) ~[na:1.8.0_202]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPositionInternal(MysqlEventParser.java:487) ~[canal.parse-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPosition(MysqlEventParser.java:369) ~[canal.parse-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:194) ~[canal.parse-1.1.5-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_202]

**Comment by w237100760** [comment]
解决了吗 mysql8 一直这个报错
