### ISSUE TITLE
canal 1.1.5版本运行一段时间报错

### ISSUE THREAD

**Issue by ljy-super** [alibaba/canal#3759]
### environment

* canal 1.1.5-SNAPSHOT or 1.1.5 
* mysql version 5.7.30-log

### Issue Description
用的是ES7同步，用的1.1.5版本  1.1.5-SNAPSHOT也试过
运行一段时间后canal-adapter报错
2021-09-01 10:42:17.918 [Thread-4] ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - process error!
com.alibaba.otter.canal.protocol.exception.CanalClientException: java.io.IOException: Broken pipe
        at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.subscribe(SimpleCanalConnector.java:254) ~[na:na]
        at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.subscribe(SimpleCanalConnector.java:226) ~[na:na]
        at com.alibaba.otter.canal.connector.tcp.consumer.CanalTCPConsumer.connect(CanalTCPConsumer.java:60) ~[na:na]
        at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.process(AdapterProcessor.java:184) ~[client-adapter.launcher-1.1.5-SNAPSHOT.jar:na] 
<img width="741" alt="87e1eca18befa5f6484ec5a918acd57" src="https://user-images.githubusercontent.com/30432333/131630666-81006e17-fd43-4672-a91f-748427237172.png">

server端是
<img width="701" alt="c54e38836bb5a1b075a21026298e9af" src="https://user-images.githubusercontent.com/30432333/131630941-8c682205-ce3f-4175-9d75-0096340a12f2.png">

因为canal报错的时间点 不确定。也不好排查 是因为 server端 链接重置了 还是 因为canal-adapter 报错了，导致 这个一直没有ack 所以 同步滞后
### Steps to reproduce
正常启动server和client  运行一段时间后，报错
### Actual behaviour

If there is an exception, please attach the exception trace:

```
adapter端

2021-09-01 10:42:17.918 [Thread-4] ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - process error!
com.alibaba.otter.canal.protocol.exception.CanalClientException: java.io.IOException: Broken pipe
        at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.subscribe(SimpleCanalConnector.java:254) ~[na:na]
        at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.subscribe(SimpleCanalConnector.java:226) ~[na:na]
        at com.alibaba.otter.canal.connector.tcp.consumer.CanalTCPConsumer.connect(CanalTCPConsumer.java:60) ~[na:na]
        at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.process(AdapterProcessor.java:184) ~[client-adapter.launcher-1.1.5-SNAPSHOT.jar:na] 


server端 

2021-08-31 12:43:45.861 [destination = shop , address =xxxx:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address xxxx:3306 has an error, retrying. caused by
java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:210) ~[na:1.8.0_262]
        at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:1.8.0_262]
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[na:1.8.0_262]
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286) ~[na:1.8.0_262]
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345) ~[na:1.8.0_262]
        at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:109) ~[canal.parse.driver-1.1.5-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:174) ~[canal.parse-1.1.5-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:85) ~[canal.parse-1.1.5-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:235) ~[canal.parse-1.1.5-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:265) ~[canal.parse-1.1.5-SNAPSHOT.jar:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_262]
```

**Comment by geekerstar** [comment]
同样遇到了

**Comment by ljy-super** [comment]
> 同样遇到了

有解决方案吗？

**Comment by agapple** [comment]
java.net.SocketException: Connection reset

被mysql主动关闭了链接，要么是mysql长时间没变更，要么是啥其他网络问题
