### ISSUE TITLE
canal.adapter 1.1.5版本，MySQL数据变化同步时，提示 Failed to deserialize response from handler 异常

### ISSUE THREAD

**Issue by obatis** [alibaba/canal#3768]
org.elasticsearch.transport.TransportSerializationException: Failed to deserialize response from handler [org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler/org.elasticsearch.action.ActionListenerResponseHandler@1cd49c5a/org.elasticsearch.client.transport.TransportClientNodesService$RetryListener@50031277]
	at org.elasticsearch.transport.InboundHandler.handleResponse(InboundHandler.java:263) [client-adapter.es7x-1.1.5-jar-with-dependencies.jar:na]
	at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:126) [client-adapter.es7x-1.1.5-jar-with-dependencies.jar:na]
	at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:82) [client-adapter.es7x-1.1.5-jar-with-dependencies.jar:na]
	at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:710) [client-adapter.es7x-1.1.5-jar-with-dependencies.jar:na]
	at org.elasticsearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:129) ~[client-adapter.es7x-1.1.5-jar-with-dependencies.jar:na]
	at org.elasticsearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:104) ~[client-adapter.es7x-1.1.5-jar-with-dependencies.jar:na]
	at org.elasticsearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:69) ~[client-adapter.es7x-1.1.5-jar-with-dependencies.jar:na]
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:63) ~[client-adapter.es7x-1.1.5-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[client-adapter.es7x-1.1.5-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[client-adapter.es7x-1.1.5-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[client-adapter.es7x-1.1.5-jar-with-dependencies.jar:na]
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:271) ~[client-adapter.es7x-1.1.5-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[client-adapter.es7x-1.1.5-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[client-adapter.es7x-1.1.5-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[client-adapter.es7x-1.1.5-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[client-adapter.es7x-1.1.5-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[client-adapter.es7x-1.1.5-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[client-adapter.es7x-1.1.5-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[client-adapter.es7x-1.1.5-jar-with-dependencies.jar:na]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[client-adapter.es7x-1.1.5-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[client-adapter.es7x-1.1.5-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[client-adapter.es7x-1.1.5-jar-with-dependencies.jar:na]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[client-adapter.es7x-1.1.5-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[client-adapter.es7x-1.1.5-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) ~[client-adapter.es7x-1.1.5-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:615) ~[client-adapter.es7x-1.1.5-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:578) ~[client-adapter.es7x-1.1.5-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[client-adapter.es7x-1.1.5-jar-with-dependencies.jar:na]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[client-adapter.es7x-1.1.5-jar-with-dependencies.jar:na]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[client-adapter.es7x-1.1.5-jar-with-dependencies.jar:na]

**Comment by obatis** [comment]
也会报如下的错误：
Caused by: java.lang.IllegalArgumentException: Unknown NamedWriteable category [org.elasticsearch.persistent.PersistentTaskParams]
	at org.elasticsearch.common.io.stream.NamedWriteableRegistry.getReader(NamedWriteableRegistry.java:96) ~[na:na]
	at org.elasticsearch.common.io.stream.NamedWriteableAwareStreamInput.readNamedWriteable(NamedWriteableAwareStreamInput.java:34) ~[na:na]
	at org.elasticsearch.common.io.stream.NamedWriteableAwareStreamInput.readNamedWriteable(NamedWriteableAwareStreamInput.java:28) ~[na:na]
	at org.elasticsearch.persistent.PersistentTasksCustomMetadata$PersistentTask.<init>(PersistentTasksCustomMetadata.java:340) ~[na:na]
	at org.elasticsearch.common.io.stream.StreamInput.readMap(StreamInput.java:656) ~[na:na]
	at org.elasticsearch.common.io.stream.StreamInput.readMap(StreamInput.java:640) ~[na:na]
	at org.elasticsearch.persistent.PersistentTasksCustomMetadata.<init>(PersistentTasksCustomMetadata.java:525) ~[na:na]
	at org.elasticsearch.common.io.stream.NamedWriteableAwareStreamInput.readNamedWriteable(NamedWriteableAwareStreamInput.java:35) ~[na:na]
	at org.elasticsearch.common.io.stream.NamedWriteableAwareStreamInput.readNamedWriteable(NamedWriteableAwareStreamInput.java:28) ~[na:na]
	at org.elasticsearch.cluster.metadata.Metadata.readFrom(Metadata.java:1059) ~[na:na]
	at org.elasticsearch.cluster.ClusterState.readFrom(ClusterState.java:694) ~[na:na]
	at org.elasticsearch.action.admin.cluster.state.ClusterStateResponse.lambda$new$0(ClusterStateResponse.java:37) ~[na:na]
	at org.elasticsearch.common.io.stream.StreamInput.readOptionalWriteable(StreamInput.java:1037) ~[na:na]
	at org.elasticsearch.action.admin.cluster.state.ClusterStateResponse.<init>(ClusterStateResponse.java:37) ~[na:na]
	at org.elasticsearch.action.ActionListenerResponseHandler.read(ActionListenerResponseHandler.java:58) ~[na:na]
	at org.elasticsearch.action.ActionListenerResponseHandler.read(ActionListenerResponseHandler.java:25) ~[na:na]
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.read(TransportService.java:1269) ~[na:na]
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.read(TransportService.java:1256) ~[na:na]
	at org.elasticsearch.transport.InboundHandler.handleResponse(InboundHandler.java:260) ~[na:na]
	... 30 common frames omitted
