### ISSUE TITLE
CanalParseException: java.lang.IndexOutOfBoundsException: Index: 8, Size: 8

### ISSUE THREAD

**Issue by OliverYu949** [alibaba/canal#3776]
2021-09-08T21:13:26.173+0800|ERROR|destination = test , address = /127.0.0.1:18080 , EventParser|||||c.alibaba.otter.canal.parse.inbound.AbstractEventParser|- dump address 127.0.0.1:18080 has an error, retrying. caused by 
com.alibaba.otter.canal.parse.exception.CanalParseException: java.lang.IndexOutOfBoundsException: Index: 8, Size: 8
Caused by: java.lang.IndexOutOfBoundsException: Index: 8, Size: 8
        at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[na:1.8.0_192]
        at java.util.ArrayList.get(ArrayList.java:433) ~[na:1.8.0_192]
        at com.taobao.tddl.dbsync.binlog.event.TableMapLogEvent.parse_signedness(TableMapLogEvent.java:618) ~[canal.parse.dbsync-1.1.5-SNAPSHOT.jar:na]
        at com.taobao.tddl.dbsync.binlog.event.TableMapLogEvent.<init>(TableMapLogEvent.java:458) ~[canal.parse.dbsync-1.1.5-SNAPSHOT.jar:na]
        at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:182) ~[canal.parse.dbsync-1.1.5-SNAPSHOT.jar:na]
        at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:111) ~[canal.parse.dbsync-1.1.5-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:264) ~[canal.parse-1.1.5-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:246) ~[canal.parse-1.1.5-SNAPSHOT.jar:na]
        at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168) ~[disruptor-3.4.2.jar:na]
        at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125) ~[disruptor-3.4.2.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_192]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_192]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_192]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_192]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_192]

**Comment by OliverYu949** [comment]
canal 1.1.5
RDS 启动时报错，ip和端口是更改后的

**Comment by agapple** [comment]
估计和近期修复mysql 8.0版本的特性有关
https://github.com/alibaba/canal/pull/3976
a574b91fdf19e28e4860f604bca350d24e4bbb28
