### ISSUE TITLE
请问是多表映射后没有设置父子关系，单独修改子表，不会更新文档问题吗

### ISSUE THREAD

**Issue by xiaomabenpao** [alibaba/canal#3781]
大佬可以加你好友吗，最近公司让用es还是多对多的。不会弄啊，查了好多还是没有找到解决办法

**Comment by totoro52** [comment]
借助官方的思路，掰成一对多关系，按照官方的例子，一个用户有多个标签，把标签摆成字符串，换种思路去解决
```
SELECT
	a.id AS _id,
	a.NAME,
	a.role_id,
	c.labels,
	a.c_time 
FROM
	USER a
	LEFT JOIN ( SELECT user_id, group_concat( label ORDER BY id DESC SEPARATOR ';' ) AS labels FROM label GROUP BY user_id ) c ON c.user_id = a.id
```

**Comment by xiaomabenpao** [comment]
谢谢，我试一试

**Comment by xiaomabenpao** [comment]
2021-09-11 18:36:15.682 [main] INFO  c.a.o.c.client.adapter.es.core.config.ESSyncConfigLoader - ## ES mapping config loaded
2021-09-11 18:36:15.938 [main] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterLoader - Load canal adapter: es7 failed
java.lang.RuntimeException: java.lang.RuntimeException: com.alibaba.fastsql.sql.parser.ParserException
	at com.alibaba.otter.canal.client.adapter.es7x.ES7xAdapter.init(ES7xAdapter.java:54) ~[client-adapter.es7x-1.1.5-SNAPSHOT-jar-with-dependencies.jar:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.CanalAdapterLoader.loadAdapter(CanalAdapterLoader.java:225) [client-adapter.launcher-1.1.5.jar:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.CanalAdapterLoader.init(CanalAdapterLoader.java:56) [client-adapter.launcher-1.1.5.jar:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.CanalAdapterService.init(CanalAdapterService.java:60) [client-adapter.launcher-1.1.5.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_31]

**Comment by xiaomabenpao** [comment]
好像不支持

**Comment by xiaomabenpao** [comment]
sql: "SELECT
        a.role_typeid as _id,
        o.organization_id as organizationId
        FROM
        mem_organization o
        LEFT JOIN ( SELECT account_id, group_concat(DISTINCT  role_typeid ORDER BY role_typeid DESC SEPARATOR ';' ) AS role_typeid FROM mem_account_role GROUP BY account_id )a ON o.account_id = a.account_id "        # sql映射
  etlCondition: "where a.c_time>={}"   #etl的条件参数

**Comment by Jackheart** [comment]
> 借助官方的思路，掰成一对多关系，按照官方的例子，一个用户有多个标签，把标签摆成字符串，换种思路去解决
> 
> ```
> SELECT
> 	a.id AS _id,
> 	a.NAME,
> 	a.role_id,
> 	c.labels,
> 	a.c_time 
> FROM
> 	USER a
> 	LEFT JOIN ( SELECT user_id, group_concat( label ORDER BY id DESC SEPARATOR ';' ) AS labels FROM label GROUP BY user_id ) c ON c.user_id = a.id
> ```

改成子查询后，子查询的原数据物理删除后不会同步到主表，adapter会收到mq消息，但是没有触发主表的查询子查询的属性表更

**Comment by 1512033796** [comment]
> > 借助官方的思路，掰成一对多关系，按照官方的例子，一个用户有多个标签，把标签摆成字符串，换种思路去解决
> > ```
> > SELECT
> > 	a.id AS _id,
> > 	a.NAME,
> > 	a.role_id,
> > 	c.labels,
> > 	a.c_time 
> > FROM
> > 	USER a
> > 	LEFT JOIN ( SELECT user_id, group_concat( label ORDER BY id DESC SEPARATOR ';' ) AS labels FROM label GROUP BY user_id ) c ON c.user_id = a.id
> > ```
> 
> 改成子查询后，子查询的原数据物理删除后不会同步到主表，adapter会收到mq消息，但是没有触发主表的查询子查询的属性表更

大佬，这个问题解决没

**Comment by totoro52** [comment]
> > > 借助官方的思路，掰成一对多关系，按照官方的例子，一个用户有多个标签，把标签摆成字符串，换种思路去解决
> > > ```
> > > SELECT
> > > 	a.id AS _id,
> > > 	a.NAME,
> > > 	a.role_id,
> > > 	c.labels,
> > > 	a.c_time 
> > > FROM
> > > 	USER a
> > > 	LEFT JOIN ( SELECT user_id, group_concat( label ORDER BY id DESC SEPARATOR ';' ) AS labels FROM label GROUP BY user_id ) c ON c.user_id = a.id
> > > ```
> > 
> > 
> > 改成子查询后，子查询的原数据物理删除后不会同步到主表，adapter会收到mq消息，但是没有触发主表的查询子查询的属性表更
> 
> 大佬，这个问题解决没

我放弃了adapter 自写了client，效果比直接用adapter还好一些。

**Comment by 1512033796** [comment]
> 我放弃了adapter 自写了client，效果比直接用adapter还好一些。

大佬牛啊！可否分享下自写client如何写的呢！

**Comment by totoro52** [comment]
> > 我放弃了adapter 自写了client，效果比直接用adapter还好一些。
> 
> 大佬牛啊！可否分享下自写client如何写的呢！

菜鸟一枚，这个canal本身提供了client，但比较难用，我是参考了别人开源的库仿写的
地址：https://github.com/NormanGyllenhaal/canal-client
但该库已停止维护很久了，食用时须注意，可以借鉴思路。

**Comment by 1512033796** [comment]
> 地址：https://github.com/NormanGyllenhaal/canal-client
> 但该库已停止维护很久了，食用时须注意，可以借鉴思路。
感谢大佬！
