### ISSUE TITLE
启动某个channel就一直报错

### ISSUE THREAD

**Issue by heshangdaben** [alibaba/canal#381]
pid:9 nid:1 exception:canal:tdesk_test_canal:java.lang.NoClassDefFoundError: Could not initialize class com.alibaba.otter.canal.common.utils.JsonUtils 
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPositionInternal(MysqlEventParser.java:415) 
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPosition(MysqlEventParser.java:315) 
    at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:161) 
    at java.lang.Thread.run(Thread.java:748) 

请问是什么原因啊？是没有位点的原因的吗？

**Comment by heshangdaben** [comment]
启动了多一段时间也可能有这个错。

**Comment by agapple** [comment]
请使用最新版测试
