### ISSUE TITLE
1.1.5版本adapter报错表不存在

### ISSUE THREAD

**Issue by gaoqiang-0327** [alibaba/canal#3834]
## Question
cat application.yml 
  srcDataSources:
    defaultDS:
      url: jdbc:mysql://192.168.1.5:3306/sbtest?useUnicode=true
      username: root
      password: Lepu123.com
  canalAdapters:
  - instance: example # canal instance Name or mq topic name
    groups:
    - groupId: g1
      outerAdapters:
      - name: logger
      - name: rdb
        key: mysql1
        properties:
          jdbc.driverClassName: com.mysql.jdbc.Driver
          jdbc.url: jdbc:mysql://192.168.1.5:3350/dba?useUnicode=true
          jdbc.username: canal_user
          jdbc.password: 123456

[root@localhost]# cat liaison_summary.yml
dataSourceKey: defaultDS
destination: example
groupId: g1
outerAdapterKey: mysql1
concurrent: true
dbMapping:
  database: test_db
  table: liaison_summary
  targetTable: canal_activity_test_count.iaison_summary
  targetPk:
    id: id
  mapAll: true

不知道为什么会把url里面的dba库给带进去，导致在往目的端插入数据的时候表格式为：db.db.table。正常情况应该是db.table
错误日志：
2021-09-22 21:29:51.106 [pool-3-thread-1] ERROR com.alibaba.otter.canal.client.adapter.support.Util - Table 'dba.canal_activity_test_count.iaison_summary' doesn't exist
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'dba.canal_activity_test_count.iaison_summary' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_221]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_221]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_221]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_221]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.48.jar:5.1.48]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.48.jar:5.1.48]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944) ~[mysql-connector-java-5.1.48.jar:5.1.48]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933) ~[mysql-connector-java-5.1.48.jar:5.1.48]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869) ~[mysql-connector-java-5.1.48.jar:5.1.48]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524) ~[mysql-connector-java-5.1.48.jar:5.1.48]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675) ~[mysql-connector-java-5.1.48.jar:5.1.48]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465) ~[mysql-connector-java-5.1.48.jar:5.1.48]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2439) ~[mysql-connector-java-5.1.48.jar:5.1.48]
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1365) ~[mysql-connector-java-5.1.48.jar:5.1.48]
	at com.alibaba.druid.pool.DruidPooledStatement.executeQuery(DruidPooledStatement.java:296) ~[druid-1.2.6.jar:1.2.6]
	at com.alibaba.otter.canal.client.adapter.support.Util.sqlRS(Util.java:77) ~[client-adapter.common-1.1.5.jar:na]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.getTargetColumnType(RdbSyncService.java:420) [client-adapter.rdb-1.1.5-jar-with-dependencies.jar:na]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.insert(RdbSyncService.java:263) [client-adapter.rdb-1.1.5-jar-with-dependencies.jar:na]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.sync(RdbSyncService.java:214) [client-adapter.rdb-1.1.5-jar-with-dependencies.jar:na]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$null$0(RdbSyncService.java:115) [client-adapter.rdb-1.1.5-jar-with-dependencies.jar:na]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_221]
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$sync$1(RdbSyncService.java:115) [client-adapter.rdb-1.1.5-jar-with-dependencies.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_221]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_221]

**Comment by flowell** [comment]
这是因为adapter的jdbc.url里指定了使用的数据库。
在我的测试下，如果在指定了默认DB的情况下使用反引号包裹的表名，mysql会在反引号表名的基础上添加默认DB名
```
use db
select * FROM `db.table` where 1=2;        // MYSQL ERROR:  Table 'db.db.table' doesn't exist
```
将adapter的jdbc.url修改成不带database的格式即可，但是会报no database use的错误。看起来不带反引号会是一个正确的选择？
