### ISSUE TITLE
canal  client 获取message 报错 Protocol message had invalid UTF-8. 

### ISSUE THREAD

**Issue by hotspring-zwb** [alibaba/canal#3848]
canal  1.1.5 版本

## canal client 拉取消息报错

执行到这里报错
// 获取指定数量的数据
Message message = connector.getWithoutAck(BATCH_SIZE);   

对应着下方 CanalTaskThread.java:133 报错行的代码

```
com.alibaba.otter.canal.protocol.exception.CanalClientException: com.google.protobuf.InvalidProtocolBufferException: Protocol message had invalid UTF-8.
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.subscribe(SimpleCanalConnector.java:254)
	at com.linewell.form.server.datacenter.canal.CanalTaskThread.run(CanalTaskThread.java:133)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Protocol message had invalid UTF-8.
	at com.google.protobuf.InvalidProtocolBufferException.invalidUtf8(InvalidProtocolBufferException.java:148)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readStringRequireUtf8(CodedInputStream.java:841)
	at com.alibaba.otter.canal.protocol.CanalPacket$Ack.<init>(CanalPacket.java:4292)
	at com.alibaba.otter.canal.protocol.CanalPacket$Ack.<init>(CanalPacket.java:4249)
	at com.alibaba.otter.canal.protocol.CanalPacket$Ack$1.parsePartialFrom(CanalPacket.java:4930)
	at com.alibaba.otter.canal.protocol.CanalPacket$Ack$1.parsePartialFrom(CanalPacket.java:4924)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:105)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:125)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:130)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at com.alibaba.otter.canal.protocol.CanalPacket$Ack.parseFrom(CanalPacket.java:4525)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.subscribe(SimpleCanalConnector.java:247)
	... 1 common frames omitted
```
 
重启 canal-1.1.5 deploy 后正常一段时间后，又会报错，这个是插入到mysql 里面的数据格式要特殊要求，不能是特殊格式么?
观察 canal server 端expamle没有报错日志

## 问题求助
-- 1. 是否是配置问题导致
-- 2.如何修改server 端配置，或者 client 需要添加什么配置
-- 3.客户端如何查看具体是那一条 binlog 转 message 处理有问题

**Comment by agapple** [comment]
检查下client和server的版本是否对齐，感觉是protocol协议版本对不上
