### ISSUE TITLE
canal解析mysql json_object函数产生的binlog报错

### ISSUE THREAD

**Issue by daijunjian** [alibaba/canal#3853]
### environment
* canal version ：1.1.3
* mysql version：5.7

### Issue Description
canal解析mysql json_object函数产生的binlog报错

### 引发报错的sql
update table
set remark = JSON_OBJECT('0-1000', length_gt_0,'1000-2000', length_gt_1000,'2000-3000', length_gt_2000,'3000', length_gt_3000);
字段remark是json类型

### exception
com.alibaba.otter.canal.parse.exception.CanalParseException: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: java.lang.IllegalArgumentException: limit excceed: 6
	at com.taobao.tddl.dbsync.binlog.LogBuffer.fillBytes(LogBuffer.java:1557)
	at com.taobao.tddl.dbsync.binlog.LogBuffer.getData(LogBuffer.java:1578)
	at com.taobao.tddl.dbsync.binlog.JsonConversion.parse_scalar(JsonConversion.java:174)
	at com.taobao.tddl.dbsync.binlog.JsonConversion.parse_value(JsonConversion.java:71)
	at com.taobao.tddl.dbsync.binlog.JsonConversion$Json_Value.element(JsonConversion.java:277)
	at com.taobao.tddl.dbsync.binlog.JsonConversion$Json_Value.toJsonString(JsonConversion.java:290)
	at com.taobao.tddl.dbsync.binlog.event.RowsLogBuffer.fetchValue(RowsLogBuffer.java:1093)
	at com.taobao.tddl.dbsync.binlog.event.RowsLogBuffer.nextValue(RowsLogBuffer.java:125)
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseOneRow(LogEventConvert.java:711)
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseRowsEvent(LogEventConvert.java:545)
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseRowsEvent(LogEventConvert.java:487)
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:125)
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:67)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser.parseAndProfilingIfNecessary(AbstractEventParser.java:409)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3$1.sink(AbstractEventParser.java:209)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:178)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:271)
	at java.lang.Thread.run(Thread.java:745)

**Comment by nielizixiu** [comment]
作者回答过，这个可以忽略 不用管的      你可以翻翻以前的issue

**Comment by agapple** [comment]
先升级下canal版本到最新，印象中有解决过json的解析问题
