### ISSUE TITLE
ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:xxx[java.io.IOException: Unexpected End Stream

### ISSUE THREAD

**Issue by zhumt** [alibaba/canal#390]
在canal实例日志中偶尔会报这个错误，请问怎么解决

**Comment by agapple** [comment]
mysql断链问题，目前是一些已知问题，主干版本有人提交了修复

**Comment by shijiebei2009** [comment]
@agapple 
```
2017-11-06 15:00:03.937 [destination = action_log , address = /127.0.0.2:2020 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - dump address 127.0.0.2/127.0.0.2:2020 has an error, retrying. caused by 
java.io.IOException: Unexpected End Stream
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:156) ~[canal.parse-1.0.24.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:70) ~[canal.parse-1.0.24.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:122) ~[canal.parse-1.0.24.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209) ~[canal.parse-1.0.24.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_80]
2017-11-06 15:00:03.938 [destination = action_log , address = /127.0.0.2:2020 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:action_log[java.io.IOException: Unexpected End Stream
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:156)
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:70)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:122)
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209)
        at java.lang.Thread.run(Thread.java:745)
]
2017-11-06 15:00:22.587 [destination = action_log , address = /127.0.0.2:2020 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - prepare to find start position just last position
 {"identity":{"slaveId":-1,"sourceAddress":{"address":"127.0.0.2","port":2020}},"postion":{"included":false,"journalName":"mysql-bin.001213","position":638501339,"serverId":1037,"timestamp":1509951603000}}
2017-11-06 17:00:22.588 [destination = action_log , address = /127.0.0.2:2020 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - I/O error while reading from client socket
java.io.IOException: Unexpected End Stream
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:156) ~[canal.parse-1.0.24.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:70) ~[canal.parse-1.0.24.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:122) [canal.parse-1.0.24.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209) [canal.parse-1.0.24.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_80]
2017-11-06 17:00:22.588 [destination = action_log , address = /127.0.0.2:2020 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - dump address 127.0.0.2/127.0.0.2:2020 has an error, retrying. caused by 
java.io.IOException: Unexpected End Stream
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:156) ~[canal.parse-1.0.24.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:70) ~[canal.parse-1.0.24.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:122) ~[canal.parse-1.0.24.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209) ~[canal.parse-1.0.24.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_80]
2017-11-06 17:00:22.588 [destination = action_log , address = /127.0.0.2:2020 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:action_log[java.io.IOException: Unexpected End Stream
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:156)
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:70)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:122)
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209)
        at java.lang.Thread.run(Thread.java:745)
]
2017-11-06 17:00:34.936 [destination = action_log , address = /127.0.0.2:2020 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - prepare to find start position just last position
 {"identity":{"slaveId":-1,"sourceAddress":{"address":"127.0.0.2","port":2020}},"postion":{"included":false,"journalName":"mysql-bin.001214","position":269841413,"serverId":1037,"timestamp":1509958822000}}
(END) 
```
大约每两小时就报一次，但是貌似并没有丢数据，请问对线上业务有影响吗？新版canal修复该问题了吗？

**Comment by tdytaylor** [comment]
亲，这个问题你们解决了嘛？

**Comment by shijiebei2009** [comment]
@tdytaylor 
至今没有解决，如果你解决了，吼一吼

**Comment by agapple** [comment]
mysql server服务端主动断链接，尝试用最新版本试试

**Comment by zhangbuding** [comment]
这个问题会造成丢失数据吗...重启了后遇到的, 
升级版本有什么简便方法吗
