### ISSUE TITLE
canal deployed successfully,but can't be started in java client

### ISSUE THREAD

**Issue by 123ovo321** [alibaba/canal#3940]
The canal is running with docker ,and i can also ping the port successfully,but can't  be started in java client.
Exception in thread "main" java.lang.NoClassDefFoundError: com/alibaba/otter/canal/protocol/exception/CanalClientException
	at com.alibaba.otter.canal.client.CanalConnectors.newSingleConnector(CanalConnectors.java:31)
	at org.example.CanalTest.main(CanalTest.java:10)
Caused by: java.lang.ClassNotFoundException: com.alibaba.otter.canal.protocol.exception.CanalClientException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 2 more
![image](https://user-images.githubusercontent.com/87159627/143620047-d3e78b5f-eccf-4a05-add9-e33c4b3db501.png)

**Comment by 123ovo321** [comment]
![image](https://user-images.githubusercontent.com/87159627/143672542-12f25a5a-afc0-4c2b-a590-424d68a6739e.png)
I found the reason ,it's caused by the version ...
but why there is so much classes decrease in version 1.1.5?
The mirror I choosed is aliyunmirror.

**Comment by agapple** [comment]
Caused by: java.lang.ClassNotFoundException: com.alibaba.otter.canal.protocol.exception.CanalClientException
