### ISSUE TITLE
运行一段时间后，发生com.rabbitmq.client.impl.ForgivingExceptionHandler错误，就停止解析了

### ISSUE THREAD

**Issue by wangbinq** [alibaba/canal#3973]
2021-12-20 02:10:28.503 [pool-8-thread-333] WARN  com.rabbitmq.client.impl.ForgivingExceptionHandler - Consumer com.alibaba.otter.canal.connector.rabbitmq.consumer.CanalRabbitMQConsumer$1@65d949bb (amq.ctag-hKkcM9bh4a-Hreo5p0-L6A) method handleDelivery for channel AMQChannel(amqp://admin@x.x.x.x:5672/canal,1) threw an exception for channel AMQChannel(amqp://admin@x.x.x.x:5672/canal,1) (Exception message: Connection reset)
2021-12-20 02:10:28.518 [pool-8-thread-333] ERROR com.rabbitmq.client.impl.ForgivingExceptionHandler - Failure during close of channel AMQChannel(amqp://admin@x.x.x.x:5672/canal,1) after java.net.SocketException: Connection reset
java.net.SocketException: Broken pipe (Write failed)
        at java.net.SocketOutputStream.socketWrite0(Native Method) ~[na:1.8.0_121]
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111) ~[na:1.8.0_121]
        at java.net.SocketOutputStream.write(SocketOutputStream.java:155) ~[na:1.8.0_121]
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82) ~[na:1.8.0_121]
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140) ~[na:1.8.0_121]
        at java.io.DataOutputStream.flush(DataOutputStream.java:123) ~[na:1.8.0_121]
        at com.rabbitmq.client.impl.SocketFrameHandler.flush(SocketFrameHandler.java:177) ~[connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at com.rabbitmq.client.impl.AMQConnection.flush(AMQConnection.java:573) ~[connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at com.rabbitmq.client.impl.AMQCommand.transmit(AMQCommand.java:134) ~[connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at com.rabbitmq.client.impl.AMQChannel.quiescingTransmit(AMQChannel.java:452) ~[connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at com.rabbitmq.client.impl.AMQChannel.quiescingTransmit(AMQChannel.java:433) ~[connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at com.rabbitmq.client.impl.AMQChannel.quiescingRpc(AMQChannel.java:350) ~[connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at com.rabbitmq.client.impl.ChannelN.close(ChannelN.java:608) ~[connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at com.rabbitmq.client.impl.ChannelN.close(ChannelN.java:541) ~[connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at com.rabbitmq.client.impl.StrictExceptionHandler.handleChannelKiller(StrictExceptionHandler.java:72) [connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at com.rabbitmq.client.impl.StrictExceptionHandler.handleConsumerException(StrictExceptionHandler.java:61) [connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:154) [connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:104) [connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
2021-12-20 02:10:28.643 [RabbitMQ Error On Write Thread] WARN  com.rabbitmq.client.impl.ForgivingExceptionHandler - An unexpected connection driver error occured (Exception message: Connection reset)
2021-12-20 02:10:28.647 [RabbitMQ Error On Write Thread] ERROR com.rabbitmq.client.impl.ForgivingExceptionHandler - An unexpected connection driver error occured
java.net.SocketException: Broken pipe (Write failed)
        at java.net.SocketOutputStream.socketWrite0(Native Method) ~[na:1.8.0_121]
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111) ~[na:1.8.0_121]
        at java.net.SocketOutputStream.write(SocketOutputStream.java:155) ~[na:1.8.0_121]
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82) ~[na:1.8.0_121]
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140) ~[na:1.8.0_121]
        at java.io.DataOutputStream.flush(DataOutputStream.java:123) ~[na:1.8.0_121]
        at com.rabbitmq.client.impl.SocketFrameHandler.flush(SocketFrameHandler.java:177) ~[na:na]
        at com.rabbitmq.client.impl.AMQConnection.flush(AMQConnection.java:573) ~[na:na]
        at com.rabbitmq.client.impl.AMQCommand.transmit(AMQCommand.java:134) ~[na:na]
        at com.rabbitmq.client.impl.AMQChannel.quiescingTransmit(AMQChannel.java:452) ~[na:na]
        at com.rabbitmq.client.impl.AMQChannel.quiescingTransmit(AMQChannel.java:433) ~[na:na]
        at com.rabbitmq.client.impl.AMQChannel.quiescingRpc(AMQChannel.java:350) ~[na:na]
        at com.rabbitmq.client.impl.ChannelN.close(ChannelN.java:608) ~[na:na]
        at com.rabbitmq.client.impl.ChannelN.close(ChannelN.java:541) ~[na:na]
        at com.rabbitmq.client.impl.StrictExceptionHandler.handleChannelKiller(StrictExceptionHandler.java:72) ~[na:na]
        at com.rabbitmq.client.impl.StrictExceptionHandler.handleConsumerException(StrictExceptionHandler.java:61) ~[na:na]
        at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:154) ~[na:na]
        at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:104) ~[na:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_121]

**Comment by wangbinq** [comment]
2021-12-20 02:10:28.648 [AMQP Connection x.x.x.x:5672] ERROR com.rabbitmq.client.impl.ForgivingExceptionHandler - An unexpected connection driver error occured
java.io.IOException: Stream closed.
        at java.net.AbstractPlainSocketImpl.available(AbstractPlainSocketImpl.java:470) ~[na:1.8.0_121]
        at java.net.SocketInputStream.available(SocketInputStream.java:259) ~[na:1.8.0_121]
        at java.io.BufferedInputStream.read(BufferedInputStream.java:353) ~[na:1.8.0_121]
        at java.io.DataInputStream.readFully(DataInputStream.java:195) ~[na:1.8.0_121]
        at java.io.DataInputStream.readFully(DataInputStream.java:169) ~[na:1.8.0_121]
        at com.rabbitmq.client.impl.Frame.readFrom(Frame.java:113) ~[na:na]
        at com.rabbitmq.client.impl.SocketFrameHandler.readFrame(SocketFrameHandler.java:164) ~[na:na]
        at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:598) ~[na:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
2021-12-20 02:10:28.653 [RabbitMQ Error On Write Thread] ERROR com.rabbitmq.client.impl.ForgivingExceptionHandler - An unexpected connection driver error occured
java.net.SocketException: Broken pipe (Write failed)
        at java.net.SocketOutputStream.socketWrite0(Native Method) ~[na:1.8.0_121]
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111) ~[na:1.8.0_121]
        at java.net.SocketOutputStream.write(SocketOutputStream.java:155) ~[na:1.8.0_121]
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82) ~[na:1.8.0_121]
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140) ~[na:1.8.0_121]
        at java.io.DataOutputStream.flush(DataOutputStream.java:123) ~[na:1.8.0_121]
        at com.rabbitmq.client.impl.SocketFrameHandler.flush(SocketFrameHandler.java:177) ~[na:na]
        at com.rabbitmq.client.impl.AMQConnection.flush(AMQConnection.java:573) ~[na:na]
        at com.rabbitmq.client.impl.AMQCommand.transmit(AMQCommand.java:134) ~[na:na]
        at com.rabbitmq.client.impl.AMQChannel.quiescingTransmit(AMQChannel.java:452) ~[na:na]
        at com.rabbitmq.client.impl.AMQChannel.quiescingTransmit(AMQChannel.java:433) ~[na:na]
        at com.rabbitmq.client.impl.AMQChannel.quiescingRpc(AMQChannel.java:350) ~[na:na]
        at com.rabbitmq.client.impl.AMQConnection.close(AMQConnection.java:1047) ~[na:na]
        at com.rabbitmq.client.impl.AMQConnection.abort(AMQConnection.java:996) ~[na:na]
        at com.rabbitmq.client.impl.AMQConnection.abort(AMQConnection.java:981) ~[na:na]
        at com.rabbitmq.client.impl.StrictExceptionHandler.handleChannelKiller(StrictExceptionHandler.java:79) ~[na:na]
        at com.rabbitmq.client.impl.StrictExceptionHandler.handleConsumerException(StrictExceptionHandler.java:61) ~[na:na]
        at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:154) ~[na:na]
        at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:104) ~[na:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_121]
2021-12-20 02:10:28.654 [pool-8-thread-333] ERROR com.rabbitmq.client.impl.ForgivingExceptionHandler - Consumer com.alibaba.otter.canal.connector.rabbitmq.consumer.CanalRabbitMQConsumer$1@65d949bb (amq.ctag-hKkcM9bh4a-Hreo5p0-L6A) method handleDelivery for channel AMQChannel(amqp://admin@x.x.x.x:5672/canal,1) threw an exception for channel AMQChannel(amqp://admin@x.x.x.x:5672/canal,1)
com.rabbitmq.client.AlreadyClosedException: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=Closed due to exception from Consumer (amq.ctag-hKkcM9bh4a-Hreo5p0-L6A) method handleDelivery for channel AMQChannel(amqp://admin@x.x.x.x:5672/canal,1), class-id=0, method-id=0)
        at com.rabbitmq.client.impl.AMQChannel.ensureIsOpen(AMQChannel.java:257) ~[connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at com.rabbitmq.client.impl.AMQChannel.transmit(AMQChannel.java:426) ~[connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at com.rabbitmq.client.impl.AMQChannel.transmit(AMQChannel.java:420) ~[connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at com.rabbitmq.client.impl.recovery.RecoveryAwareChannelN.basicAck(RecoveryAwareChannelN.java:93) ~[connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.basicAck(AutorecoveringChannel.java:436) ~[connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at com.alibaba.otter.canal.connector.rabbitmq.consumer.CanalRabbitMQConsumer$1.handleDelivery(CanalRabbitMQConsumer.java:125) ~[connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149) ~[connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:104) [connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
2021-12-20 02:10:28.680 [pool-6-thread-1] DEBUG c.a.o.canal.client.adapter.rdb.service.RdbSyncService - DML: {"data":{"uid":"135063","cat":"lastChargeTime","tag":"2019-08-03 14:18:44.0","enabled":"1","lastUpdateTime":"1639924249008"},"database":"hoodb","destination":"hoo.q.canal.r.hoodb","old":null,"table":"t_user_tag","type":"INSERT"}
2021-12-20 02:10:28.686 [pool-8-thread-333] ERROR com.rabbitmq.client.impl.ForgivingExceptionHandler - Consumer com.alibaba.otter.canal.connector.rabbitmq.consumer.CanalRabbitMQConsumer$1@65d949bb (amq.ctag-hKkcM9bh4a-Hreo5p0-L6A) method handleDelivery for channel AMQChannel(amqp://admin@x.x.x.x:5672/canal,1) threw an exception for channel AMQChannel(amqp://admin@x.x.x.x:5672/canal,1)
com.rabbitmq.client.AlreadyClosedException: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=Closed due to exception from Consumer (amq.ctag-hKkcM9bh4a-Hreo5p0-L6A) method handleDelivery for channel AMQChannel(amqp://admin@x.x.x.x:5672/canal,1), class-id=0, method-id=0)
        at com.rabbitmq.client.impl.AMQChannel.ensureIsOpen(AMQChannel.java:257) ~[connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at com.rabbitmq.client.impl.AMQChannel.transmit(AMQChannel.java:426) ~[connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at com.rabbitmq.client.impl.AMQChannel.transmit(AMQChannel.java:420) ~[connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at com.rabbitmq.client.impl.recovery.RecoveryAwareChannelN.basicAck(RecoveryAwareChannelN.java:93) ~[connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.basicAck(AutorecoveringChannel.java:436) ~[connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at com.alibaba.otter.canal.connector.rabbitmq.consumer.CanalRabbitMQConsumer$1.handleDelivery(CanalRabbitMQConsumer.java:125) ~[connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149) ~[connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:104) [connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
2021-12-20 02:10:28.686 [pool-8-thread-333] ERROR com.rabbitmq.client.impl.ForgivingExceptionHandler - Consumer com.alibaba.otter.canal.connector.rabbitmq.consumer.CanalRabbitMQConsumer$1@65d949bb (amq.ctag-hKkcM9bh4a-Hreo5p0-L6A) method handleDelivery for channel AMQChannel(amqp://admin@x.x.x.x:5672/canal,1) threw an exception for channel AMQChannel(amqp://admin@x.x.x.x:5672/canal,1)
com.rabbitmq.client.AlreadyClosedException: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=Closed due to exception from Consumer (amq.ctag-hKkcM9bh4a-Hreo5p0-L6A) method handleDelivery for channel AMQChannel(amqp://admin@x.x.x.x:5672/canal,1), class-id=0, method-id=0)
        at com.rabbitmq.client.impl.AMQChannel.ensureIsOpen(AMQChannel.java:257) ~[connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at com.rabbitmq.client.impl.AMQChannel.transmit(AMQChannel.java:426) ~[connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at com.rabbitmq.client.impl.AMQChannel.transmit(AMQChannel.java:420) ~[connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at com.rabbitmq.client.impl.recovery.RecoveryAwareChannelN.basicAck(RecoveryAwareChannelN.java:93) ~[connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.basicAck(AutorecoveringChannel.java:436) ~[connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at com.alibaba.otter.canal.connector.rabbitmq.consumer.CanalRabbitMQConsumer$1.handleDelivery(CanalRabbitMQConsumer.java:125) ~[connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149) ~[connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:104) [connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
2021-12-20 02:10:28.693 [pool-5-thread-1] DEBUG c.a.o.canal.client.adapter.rdb.service.RdbSyncService - DML: {"data":{"uid":"135190","cat":"lastChargeTime","tag":"2019-08-04 10:37:40.0","enabled":"1","lastUpdateTime":"1639924249008"},"database":"hoodb","destination":"hoo.q.canal.r.hoodb","old":null,"table":"t_user_tag","type":"INSERT"}
2021-12-20 02:10:28.698 [pool-8-thread-333] ERROR com.rabbitmq.client.impl.ForgivingExceptionHandler - Consumer com.alibaba.otter.canal.connector.rabbitmq.consumer.CanalRabbitMQConsumer$1@65d949bb (amq.ctag-hKkcM9bh4a-Hreo5p0-L6A) method handleDelivery for channel AMQChannel(amqp://admin@x.x.x.x:5672/canal,1) threw an exception for channel AMQChannel(amqp://admin@x.x.x.x:5672/canal,1)
com.rabbitmq.client.AlreadyClosedException: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=Closed due to exception from Consumer (amq.ctag-hKkcM9bh4a-Hreo5p0-L6A) method handleDelivery for channel AMQChannel(amqp://admin@x.x.x.x:5672/canal,1), class-id=0, method-id=0)
        at com.rabbitmq.client.impl.AMQChannel.ensureIsOpen(AMQChannel.java:257) ~[connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at com.rabbitmq.client.impl.AMQChannel.transmit(AMQChannel.java:426) ~[connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at com.rabbitmq.client.impl.AMQChannel.transmit(AMQChannel.java:420) ~[connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at com.rabbitmq.client.impl.recovery.RecoveryAwareChannelN.basicAck(RecoveryAwareChannelN.java:93) ~[connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.basicAck(AutorecoveringChannel.java:436) ~[connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at com.alibaba.otter.canal.connector.rabbitmq.consumer.CanalRabbitMQConsumer$1.handleDelivery(CanalRabbitMQConsumer.java:125) ~[connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149) ~[connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:104) [connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
2021-12-20 02:10:28.699 [pool-8-thread-333] ERROR com.rabbitmq.client.impl.ForgivingExceptionHandler - Consumer com.alibaba.otter.canal.connector.rabbitmq.consumer.CanalRabbitMQConsumer$1@65d949bb (amq.ctag-hKkcM9bh4a-Hreo5p0-L6A) method handleDelivery for channel AMQChannel(amqp://admin@x.x.x.x:5672/canal,1) threw an exception for channel AMQChannel(amqp://admin@x.x.x.x:5672/canal,1)
com.rabbitmq.client.AlreadyClosedException: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=Closed due to exception from Consumer (amq.ctag-hKkcM9bh4a-Hreo5p0-L6A) method handleDelivery for channel AMQChannel(amqp://admin@x.x.x.x:5672/canal,1), class-id=0, method-id=0)
        at com.rabbitmq.client.impl.AMQChannel.ensureIsOpen(AMQChannel.java:257) ~[connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at com.rabbitmq.client.impl.AMQChannel.transmit(AMQChannel.java:426) ~[connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at com.rabbitmq.client.impl.AMQChannel.transmit(AMQChannel.java:420) ~[connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at com.rabbitmq.client.impl.recovery.RecoveryAwareChannelN.basicAck(RecoveryAwareChannelN.java:93) ~[connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.basicAck(AutorecoveringChannel.java:436) ~[connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at com.alibaba.otter.canal.connector.rabbitmq.consumer.CanalRabbitMQConsumer$1.handleDelivery(CanalRabbitMQConsumer.java:125) ~[connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149) ~[connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:104) [connector.rabbitmq-1.1.5-jar-with-dependencies.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]

**Comment by wangbinq** [comment]
主要是出错以后就卡住了，如果能够进程奔溃，我还能用脚本监控来重启，这个就没办法处理了。

**Comment by believezhang** [comment]
我遇到了相同的问题，你这个解决了吗？ @wangbinq
