### ISSUE TITLE
安装了canal-admin客户端，canal-server日志报错com.alibaba.otter.canal.common.CanalException: load manager config failed.Caused by: java.lang.RuntimeException 但不影响正常消费

### ISSUE THREAD

**Issue by richard-fu-1007** [alibaba/canal#3974]
## Question

```java
2021-12-20 10:41:45.779 [canal-instance-scan-0] INFO  com.alibaba.otter.canal.deployer.CanalController - auto notify start mes_test successful.
2021-12-20 10:42:46.937 [canal-instance-scan-0] WARN  c.a.o.c.common.zookeeper.running.ServerRunningMonitor - canal is not run any in node
2021-12-20 10:42:46.940 [canal-instance-scan-0] INFO  com.alibaba.otter.canal.deployer.CanalController - auto notify stop mes_test successful.
2021-12-20 10:44:48.381 [canal-instance-scan-0] INFO  com.alibaba.otter.canal.deployer.CanalController - auto notify start mes_test successful.
2021-12-20 10:53:28.127 [canal-instance-scan-0] WARN  c.a.o.c.common.zookeeper.running.ServerRunningMonitor - canal is running in node[master02-cdpdev-ic:11111] , but not in node[master01-cdpdev-ic:11111]
2021-12-20 10:53:28.129 [canal-instance-scan-0] INFO  com.alibaba.otter.canal.deployer.CanalController - auto notify stop mes_test successful.
2021-12-20 11:40:24.274 [canal-instance-scan-0] INFO  com.alibaba.otter.canal.deployer.CanalController - auto notify start mes_test successful.
2021-12-20 11:49:35.638 [canal-instance-scan-0] WARN  c.a.o.c.common.zookeeper.running.ServerRunningMonitor - canal is running in node[master02-cdpdev-ic:11111] , but not in node[master01-cdpdev-ic:11111]
2021-12-20 11:49:35.640 [canal-instance-scan-0] INFO  com.alibaba.otter.canal.deployer.CanalController - auto notify stop mes_test successful.
2021-12-20 12:33:39.023 [canal-server-scan-0] ERROR com.alibaba.otter.canal.deployer.CanalLauncher - scan failed
com.alibaba.otter.canal.common.CanalException: load manager config failed.
Caused by: java.lang.RuntimeException: requestGet remote error, request : http://master01-cdpdev-ic:8089/api/v1/config/server_polling?ip=master01-cdpdev-ic&port=11110&md5=6e3f42d9bbc7655106e80a6b7e7eabbb&register=1&cluster=&name=
	at com.alibaba.otter.canal.instance.manager.plain.HttpHelper.get(HttpHelper.java:100) ~[canal.instance.manager-1.1.5.jar:na]
	at com.alibaba.otter.canal.instance.manager.plain.PlainCanalConfigClient.doQuery(PlainCanalConfigClient.java:121) ~[canal.instance.manager-1.1.5.jar:na]
	at com.alibaba.otter.canal.instance.manager.plain.PlainCanalConfigClient.queryConfig(PlainCanalConfigClient.java:110) ~[canal.instance.manager-1.1.5.jar:na]
	at com.alibaba.otter.canal.instance.manager.plain.PlainCanalConfigClient.findServer(PlainCanalConfigClient.java:77) ~[canal.instance.manager-1.1.5.jar:na]
	at com.alibaba.otter.canal.deployer.CanalLauncher$1.run(CanalLauncher.java:92) ~[canal.deployer-1.1.5.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_232]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_232]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_232]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_232]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_232]
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method) ~[na:1.8.0_232]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[na:1.8.0_232]
	at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[na:1.8.0_232]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:1.8.0_232]
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:139) ~[httpcore-4.4.3.jar:4.4.3]
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:155) ~[httpcore-4.4.3.jar:4.4.3]
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:284) ~[httpcore-4.4.3.jar:4.4.3]
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140) ~[httpclient-4.5.1.jar:4.5.1]
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57) ~[httpclient-4.5.1.jar:4.5.1]
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261) ~[httpcore-4.4.3.jar:4.4.3]
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165) ~[httpcore-4.4.3.jar:4.4.3]
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167) ~[httpclient-4.5.1.jar:4.5.1]
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272) ~[httpcore-4.4.3.jar:4.4.3]
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124) ~[httpcore-4.4.3.jar:4.4.3]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271) ~[httpclient-4.5.1.jar:4.5.1]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[httpclient-4.5.1.jar:4.5.1]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) ~[httpclient-4.5.1.jar:4.5.1]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.1.jar:4.5.1]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[httpclient-4.5.1.jar:4.5.1]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[httpclient-4.5.1.jar:4.5.1]
	at com.alibaba.otter.canal.instance.manager.plain.HttpHelper.get(HttpHelper.java:90) ~[canal.instance.manager-1.1.5.jar:na]
	... 11 common frames omitted

**Comment by agapple** [comment]
Caused by: java.net.SocketTimeoutException: Read timed out

**Comment by wangpengshao** [comment]
请问该问题已经解决了吗

**Comment by sbwfnhn** [comment]
最新的1.1.8中也有这个问题，时不时会来下，不影响业务，这个timeout时长是多少。
测试机上根本没什么业务，不存在服务器压力的问题，而且admin与deployer同一台机器
也不存在网络的事情，admin的8080与deployer的11110是同一台机器
