### ISSUE TITLE
canal 1.1.5 adapter出现空指针报错

### ISSUE THREAD

**Issue by xltxb** [alibaba/canal#3994]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal 1.1.5
* mysql 8.0.23

### Issue Description
通过canal deployer 读取MySQL binlog 使用canal adapter 同步到elasticsearch(7.12)中
之前一直好好的，今天突然adapter出现故障.

### Actual behaviour
重启adapter服务之后恢复正常。：：

If there is an exception, please attach the exception trace:

```
报错如下：
2021-12-31 20:23:55.573 [pool-2-thread-1] ERROR c.a.o.canal.client.adapter.es.core.service.ESSyncService - sync error, es index: tbl_member_promo_transaction, DML : Dml{destination='mysql-2-es', database='ym', table='tbl_member_promo_transaction', type='INSERT', es=1640957035000, ts=1640957035572, sql='', data=[{id=68020387923807053, bill_no=7593482959694152325, uid=158155819286111441, platform_id=362857114342923387, username=thienanpr, cash_type=173, amount=60.0, before_amount=138.0200, after_amount=78.0200, created_at=1640957035391, remark=4260000_34194}], old=null}2021-12-31 20:23:55.574 [pool-2-thread-1] ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - java.lang.NullPointerExceptionjava.lang.RuntimeException: java.lang.NullPointerException
        at com.alibaba.otter.canal.client.adapter.es.core.service.ESSyncService.sync(ESSyncService.java:116) ~[na:na]        at com.alibaba.otter.canal.client.adapter.es.core.service.ESSyncService.sync(ESSyncService.java:64) ~[na:na]        at com.alibaba.otter.canal.client.adapter.es.core.ESAdapter.sync(ESAdapter.java:115) ~[na:na]
        at com.alibaba.otter.canal.client.adapter.es.core.ESAdapter.sync(ESAdapter.java:94) ~[na:na]
        at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.batchSync(AdapterProcessor.java:139) ~[client-adapter.launcher-1.1.5.jar:na]
        at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.lambda$null$1(AdapterProcessor.java:97) ~[client-adapter.launcher-1.1.5.jar:na]
        at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891) ~[na:1.8.0_241]
        at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.lambda$null$2(AdapterProcessor.java:94) ~[client-adapter.launcher-1.1.5.jar:na]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_241]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_241]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_241]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_241]
Caused by: java.lang.NullPointerException: null
2021-12-31 20:23:55.574 [Thread-4] ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - Outer adapter sync failed!  Error sync but ACK!
```

**Comment by zhuchao941** [comment]
@xltxb
