### ISSUE TITLE
Load canal adapter: es7 failed

### ISSUE THREAD

**Issue by caipeishen** [alibaba/canal#4005]
### environment
* canal 1.1.5
* mysql 8.0.19
* elasticsearch 7.16.2

### exception
mysql数据同步到es7，出现Load canal adapter: es7 failed，修改数据，控制台可以打印出来增量数据(-name: logger生效)

> application.yml
![image](https://user-images.githubusercontent.com/47104943/148498827-0d814063-877b-49ea-994a-2b89c9e31f83.png)

> es7配置文件
![image](https://user-images.githubusercontent.com/47104943/148498884-5fa908e6-4734-4bee-855f-96e535fda554.png)

```
2022-01-07 05:01:40.051 [main] INFO  c.a.o.c.client.adapter.es.core.config.ESSyncConfigLoader - ## Start loading es mapping config ... 
2022-01-07 05:01:40.168 [main] INFO  c.a.o.c.client.adapter.es.core.config.ESSyncConfigLoader - ## ES mapping config loaded
2022-01-07 05:01:40.528 [main] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterLoader - Load canal adapter: es7 failed
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.ClassCastException: com.alibaba.druid.pool.DruidDataSource cannot be cast to com.alibaba.druid.pool.DruidDataSource
	at com.alibaba.otter.canal.client.adapter.es7x.ES7xAdapter.init(ES7xAdapter.java:54) ~[client-adapter.es7x-1.1.5-jar-with-dependencies.jar:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.CanalAdapterLoader.loadAdapter(CanalAdapterLoader.java:225) [client-adapter.launcher-1.1.5.jar:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.CanalAdapterLoader.init(CanalAdapterLoader.java:56) [client-adapter.launcher-1.1.5.jar:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.CanalAdapterService.init(CanalAdapterService.java:60) [client-adapter.launcher-1.1.5.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_251]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_251]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:365) [spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:308) [spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:135) [spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:422) [spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1694) [spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:579) [spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:501) [spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$1(AbstractBeanFactory.java:353) [spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.cloud.context.scope.GenericScope$BeanLifecycleWrapper.getBean(GenericScope.java:390) ~[spring-cloud-context-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.cloud.context.scope.GenericScope.get(GenericScope.java:184) ~[spring-cloud-context-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:350) [spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) [spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1089) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.cloud.context.scope.refresh.RefreshScope.eagerlyInitialize(RefreshScope.java:126) ~[spring-cloud-context-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.cloud.context.scope.refresh.RefreshScope.start(RefreshScope.java:117) ~[spring-cloud-context-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_251]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_251]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:264) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:182) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:144) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:400) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:354) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:888) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:161) ~[spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) ~[spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395) ~[spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) ~[spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at com.alibaba.otter.canal.adapter.launcher.CanalAdapterApplication.main(CanalAdapterApplication.java:19) ~[client-adapter.launcher-1.1.5.jar:na]
Caused by: java.lang.RuntimeException: java.lang.ClassCastException: com.alibaba.druid.pool.DruidDataSource cannot be cast to com.alibaba.druid.pool.DruidDataSource
	at com.alibaba.otter.canal.client.adapter.es.core.ESAdapter.init(ESAdapter.java:83) ~[client-adapter.es7x-1.1.5-jar-with-dependencies.jar:na]
	at com.alibaba.otter.canal.client.adapter.es7x.ES7xAdapter.init(ES7xAdapter.java:52) ~[client-adapter.es7x-1.1.5-jar-with-dependencies.jar:na]
	... 42 common frames omitted
Caused by: java.lang.ClassCastException: com.alibaba.druid.pool.DruidDataSource cannot be cast to com.alibaba.druid.pool.DruidDataSource
	at com.alibaba.otter.canal.client.adapter.es.core.ESAdapter.addSyncConfigToCache(ESAdapter.java:146) ~[client-adapter.es7x-1.1.5-jar-with-dependencies.jar:na]
	at com.alibaba.otter.canal.client.adapter.es.core.ESAdapter.init(ESAdapter.java:75) ~[client-adapter.es7x-1.1.5-jar-with-dependencies.jar:na]
	... 43 common frames omitted

```

**Comment by caipeishen** [comment]
注意结构不一样
![image](https://user-images.githubusercontent.com/47104943/148496095-b6802fc1-8c8e-420e-bd34-2447a5af70f2.png)

**Comment by caipeishen** [comment]
把代码拉下来，自己编译一下把client-adapter.es7x-1.1.5-jar-with-dependencies.jar替换

**Comment by ice-llz** [comment]
你好，我把代码拉下来编译无法通过。请问能将你编译好的jar包发一份到我邮箱吗？
867253045@qq.com
感激不尽，谢谢

**Comment by caipeishen** [comment]
> 你好，我把代码拉下来编译无法通过。请问能将你编译好的jar包发一份到我邮箱吗？ [867253045@qq.com](mailto:867253045@qq.com) 感激不尽，谢谢

代码稍后我发一下，参考我写的文章，https://github.com/caipeishen/Learning-Note/blob/master/Canal/Canal%E5%90%8C%E6%AD%A5MySQL%E5%88%B0ES7.md

**Comment by ice-llz** [comment]
已经收到你的回复，感谢，这一part顺利解决。但是在我的使用过程中关于数据增量同步仍有一小部分未解决。
在adapter/config/es7/xx.yml文件里的sql语句，由于我需要同步至es的数据之一在数据库中需要关联5张表。而像这样的数据我有5个，也就是总共有25张表，但事实上没这么多，因为在left join 从表时，5张表里的3张表是公用的。也就是一共有2X5+3=13张表。
在搜索服务里他们可以被抽取的字段几乎一样，所以我想把他们放在一个索引里。于是我的sql语句采用的是一个数据里我使用了4个left join, 然后将5个数据的sql使用union all联合起来。这样复杂的sql导致语句并不能被canal解析。于是我在数据库里创建了一个视图，然后让sql查询这个视图的所有字段。事实上在执行全量同步时它顺利的将数据同步至了es，但是增量的数据，更新的数据，删除的数据虽然在控制台打印了出来但是没有发送index，在es中也查不到。经查我猜测的原因为，因为sql监控的是视图，而增量的数据里的sql table不是视图，而是视图的源表，虽然原理是一样的，但是canal并未能正确监控到视图数据的改动，或者说视图本身就没有binlog，所以它并没有将源表的改动同步过去，除非再次执行全量同步。
我取消了视图的做法，但是union all又行不通。于是我将5个数据拆分成了5个xxx.yml文件，他们指向同一个es索引，但是数据库查询的表不都一样，如上所述，有3张从表是一样的。这次，全量和增量的数据全部同步成功了，但是这出现了一个新的致命的问题，那就是如果在从表中直接update某个字段，canal是可以正确update的。但是如果在从表中新增了一行数据，然后将关联关系表里的某行数据改成关联这条新增的数据。则这个原本的旧数据会被insert。而且最为致命的是，本来我es里有10个属性，而被重新insert后，这个文档只会有2条属性，其余的属性全部不见了。而且经过查看发现这2条属性刚好就是从表新增的那一行的数据里的被索引的2个字段。

**Comment by ice-llz** [comment]
1. 已经收到你的回复，感谢，这一part顺利解决。但是在我的使用过程中关于数据增量同步仍有一小部分未解决。

2. 在adapter/config/es7/xx.yml文件里的sql语句，由于我需要同步至es的数据之一在数据库中需要关联5张表。而像这样的数据我有5个，也就是总共有25张表，但事实上没这么多，因为在left join 从表时，5张表里的3张表是公用的。也就是一共有2X5+3=13张表。

3. 在搜索服务里他们可以被抽取的字段几乎一样，所以我想把他们放在一个索引里。于是我的sql语句采用的是一个数据里我使用了4个left join, 然后将5个数据的sql使用union all联合起来。这样复杂的sql导致语句并不能被canal解析。于是我在数据库里创建了一个视图，然后让sql查询这个视图的所有字段。事实上在执行全量同步时它顺利的将数据同步至了es，但是增量的数据，更新的数据，删除的数据虽然在控制台打印了出来但是没有发送index，在es中也查不到。经查我猜测的原因为，因为sql监控的是视图，而增量的数据里的sql table不是视图，而是视图的源表，虽然原理是一样的，但是canal并未能正确监控到视图数据的改动，或者说视图本身就没有binlog，所以它并没有将源表的改动同步过去，除非再次执行全量同步。

4. 我取消了视图的做法，但是union all又行不通。于是我将5个数据拆分成了5个xxx.yml文件，他们指向同一个es索引，但是数据库查询的表不都一样，如上所述，有3张从表是一样的。这次，全量和增量的数据全部同步成功了，但是这出现了一个新的致命的问题，那就是如果在从表中直接update某个字段，canal是可以正确update的。但是如果在从表中新增了一行数据，然后将关联关系表里的某行数据改成关联这条新增的数据。则这个原本的旧数据会被insert。而且最为致命的是，本来我es里有10个属性，而被重新insert后，这个文档只会有2条属性，其余的属性全部不见了。而且经过查看发现这2条属性刚好就是从表新增的那一行的数据里的被索引的2个字段。

**Comment by agapple** [comment]
com.alibaba.druid.pool.DruidDataSource cannot be cast to com.alibaba.druid.pool.DruidDataSource，代码问题已经合并
