### ISSUE TITLE
adapter1.1.5同步es7.3.2，出现NoNodeAvailableException，求求了，太难搞了 ........

### ISSUE THREAD

**Issue by caipeishen** [alibaba/canal#4024]
## Question

logger打印正常更变的数据，无法同步到es中，
```
2022-01-17 05:51:44.984 [pool-1-thread-1] INFO  c.a.o.canal.client.adapter.logger.LoggerAdapterExample - DML: {"data":[{"id":13,"user_id":2,"ana_type_id":1,"ana_title":"甘蔗男2222111","ana_content":"现在的男生真的太惨了\r\n不会撩人吧，被说成直男\r\n会撩人吧，又被说成渣男\r\n对女孩子好吧，就成了中央空调\r\n对女孩子不好吧，就被人骂成狗\r\n有呼吸=渣男  没呼吸=死渣男","comment_num":0,"prize_num":0,"create_date":1563148800000,"update_date":1589038197000}],"database":"cloud_wall","destination":"example","es":1642398704000,"groupId":"g1","isDdl":false,"old":[{"ana_title":"甘蔗男2222"}],"pkNames":["id"],"sql":"","table":"ana","ts":1642398704740,"type":"UPDATE"}
2022-01-17 05:51:44.993 [pool-1-thread-1] ERROR c.a.o.canal.client.adapter.es.core.service.ESSyncService - sync error, es index: ana, DML : Dml{destination='example', database='cloud_wall', table='ana', type='UPDATE', es=1642398704000, ts=1642398704740, sql='', data=[{id=13, user_id=2, ana_type_id=1, ana_title=甘蔗男2222111, ana_content=现在的男生真的太惨了
不会撩人吧，被说成直男
会撩人吧，又被说成渣男
对女孩子好吧，就成了中央空调
对女孩子不好吧，就被人骂成狗
有呼吸=渣男  没呼吸=死渣男, comment_num=0, prize_num=0, create_date=2019-07-15 00:00:00.0, update_date=2020-05-09 15:29:57.0}], old=[{ana_title=甘蔗男2222}]}

java.lang.RuntimeException: NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{pPHaJwc_Rpaz6XSEviY_WA}{192.168.56.117}{192.168.56.117:9300}]]
	at com.alibaba.otter.canal.client.adapter.es.core.service.ESSyncService.sync(ESSyncService.java:116) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.es.core.service.ESSyncService.sync(ESSyncService.java:64) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.es.core.ESAdapter.sync(ESAdapter.java:115) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.es.core.ESAdapter.sync(ESAdapter.java:94) ~[na:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.batchSync(AdapterProcessor.java:139) ~[client-adapter.launcher-1.1.5.jar:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.lambda$null$1(AdapterProcessor.java:97) ~[client-adapter.launcher-1.1.5.jar:na]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891) ~[na:1.8.0_251]
	at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.lambda$null$2(AdapterProcessor.java:94) ~[client-adapter.launcher-1.1.5.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_251]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_251]
Caused by: org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: [{#transport#-1}{pPHaJwc_Rpaz6XSEviY_WA}{192.168.56.117}{192.168.56.117:9300}]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:352) ~[na:na]
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:248) ~[na:na]
	at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:57) ~[na:na]
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:394) ~[na:na]
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:392) ~[na:na]
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:381) ~[na:na]
	at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.execute(AbstractClient.java:675) ~[na:na]
```

### application.yml

```yml
server:
  port: 8081
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

canal.conf:
  mode: tcp #tcp kafka rocketMQ rabbitMQ
  flatMessage: true
  zookeeperHosts:
  syncBatchSize: 1000
  retries: 0
  timeout:
  accessKey:
  secretKey:
  consumerProperties:
    # canal tcp consumer
    canal.tcp.server.host: 192.168.56.117:11111
    #canal.tcp.zookeeper.hosts:
    canal.tcp.batch.size: 500
    #canal.tcp.username:
    #canal.tcp.password:
    # kafka consumer
    kafka.bootstrap.servers: 127.0.0.1:9092
    kafka.enable.auto.commit: false
    kafka.auto.commit.interval.ms: 1000
    kafka.auto.offset.reset: latest
    kafka.request.timeout.ms: 40000
    kafka.session.timeout.ms: 30000
    kafka.isolation.level: read_committed
    kafka.max.poll.records: 1000
    # rocketMQ consumer
    rocketmq.namespace:
    rocketmq.namesrv.addr: 127.0.0.1:9876
    rocketmq.batch.size: 1000
    rocketmq.enable.message.trace: false
    rocketmq.customized.trace.topic:
    rocketmq.access.channel:
    rocketmq.subscribe.filter:
    # rabbitMQ consumer
    rabbitmq.host:
    rabbitmq.virtual.host:
    rabbitmq.username:
    rabbitmq.password:
    rabbitmq.resource.ownerId:

  srcDataSources:
    defaultDS:
      url: jdbc:mysql://127.0.0.1:3306/cloud_wall?useUnicode=true
      username: root
      password: a9530.A.
  canalAdapters:
  - instance: example
    groups:
    - groupId: g1
      outerAdapters:
      - name: logger
      - name: es7
        key: exampleKey
        hosts: 127.0.0.1:9300               # es 集群地址, 逗号分隔
        properties:
          mode: rest#可指定transport模式或者rest模式
          # security.auth: test:123456      # only used for rest mode
          cluster.name: elasticsearch      # es cluster name
```

### es7.yml
```yml
dataSourceKey: defaultDS
outerAdapterKey: exampleKey
destination: example
groupId: g1
esMapping:
  _index: ana
  _id: _id
  upsert: true
#  pk: id
  sql: "SELECT a.id as _id, a.user_id, u.user_nick_name, a.ana_type_id, t.ana_type_name, a.ana_title, a.ana_content, a.comment_num, a.prize_num, a.create_date, a.update_date
        FROM ana a
        LEFT JOIN ana_type t ON a.ana_type_id = t.id
        LEFT JOIN `user` u ON a.user_id = u.id"
#  objFields:
#    _labels: array:;
  etlCondition: "where a.create_date>={'0'}"
  commitBatch: 3000
```

**Comment by maclinuxp** [comment]
1.5有问题。没成功，1.6可以
