### ISSUE TITLE
docker 1.1.5版本address = mysql-test/172.19.0.2:3300 , EventParser] ERROR 

### ISSUE THREAD

**Issue by tioncico** [alibaba/canal#4025]
## Question

我使用docker容器进行通信,mysql-test正常ping通,在配置mysql-test:3300之后,自动变成mysql-test/172.19.0.2:3300
配置172.19.0.2:3300  自动变成/172.19.0.2:3300  导致一直连接失败

```
2022-01-17 09:37:37.750 [destination = example , address = mysql-test/172.19.0.2:3300 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: connect mysql-test/172.19.0.2:3300 failure
Caused by: java.io.IOException: connect mysql-test/172.19.0.2:3300 failure
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:85)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.connect(MysqlConnection.java:90)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.preDump(MysqlEventParser.java:86)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:176)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannelPool.open(BioSocketChannelPool.java:18)
	at com.alibaba.otter.canal.parse.driver.mysql.socket.SocketChannelPool.open(SocketChannelPool.java:18)
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:80)
	... 4 more
```

**Comment by tioncico** [comment]
```
# position info
canal.instance.master.address=mysql-test:3300
canal.instance.master.journal.name=mysql-bin.000002
canal.instance.master.position=25993272
canal.instance.master.timestamp=
canal.instance.master.gtid=


```

**Comment by tioncico** [comment]
![image](https://user-images.githubusercontent.com/31308307/149745463-2c84dcd2-8146-4896-a28c-e6f6a0fea31b.png)

**Comment by tioncico** [comment]
我是sb,弄错端口了

**Comment by tioncico** [comment]
开头有/是正常的
