### ISSUE TITLE
求解答：message=Proxy ERROR: Proxy does not support such usage yet: Do not support global set, sqlState=HY000, sqlStateMarker=#]

### ISSUE THREAD

**Issue by LiangliangW** [alibaba/canal#4038]
连接MySQL成功，且 find start position successfully。但是报这个错误，求问这是什么问题。

WARN  c.a.otter.canal.parse.inbound.mysql.MysqlConnection - update master_binlog_checksum failed
java.io.IOException: ErrorPacket [errorNumber=650, fieldCount=-1, message=Proxy ERROR: Proxy does not support such usage yet: Do not support global set, sqlState=HY000, sqlStateMarker=#]
 with command: set @master_binlog_checksum= @@global.binlog_checksum
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlUpdateExecutor.update(MysqlUpdateExecutor.java:49) ~[canal.parse.driver-1.1.5.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.update(MysqlConnection.java:117) [canal.parse-1.1.5.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.updateSettings(MysqlConnection.java:435) [canal.parse-1.1.5.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:230) [canal.parse-1.1.5.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:262) [canal.parse-1.1.5.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_241]
2022-01-23 15:34:30.231 [destination = example , address = /XXX:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address /10.23.106.46:3306 has an error, retrying. caused by
java.io.IOException: Error When doing Register slave:ErrorPacket [errorNumber=602, fieldCount=-1, message=Proxy ERROR: This type of SQL is not supported by group shard, sqlState=HY000, sqlStateMarker=#]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.sendRegisterSlave(MysqlConnection.java:305) ~[canal.parse-1.1.5.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:232) ~[canal.parse-1.1.5.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:262) ~[canal.parse-1.1.5.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_241]
2022-01-23 15:34:30.232 [destination = example , address = /XXX:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[java.io.IOException: Error When doing Register slave:ErrorPacket [errorNumber=602, fieldCount=-1, message=Proxy ERROR: This type of SQL is not supported by group shard, sqlState=HY000, sqlStateMarker=#]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.sendRegisterSlave(MysqlConnection.java:305)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:232)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:262)
	at java.lang.Thread.run(Thread.java:748)
]

**Comment by agapple** [comment]
Proxy ERROR: Proxy does not support such usage yet: Do not support global set, sqlState=HY000, sqlStateMarker=#]

这不是原生mysql吧？

**Comment by liprais** [comment]
腾讯的td sql不支持binlog dump command.

**Comment by randyho** [comment]
新版的TDSQL可以通过`/*proxy*/set binlog_dump_sticky_backend="set_name"`，将该会话的dump请求全部绑定路由到指定的分片上，有大佬试试吗
