### ISSUE TITLE
1.1.6x写入pulsar空指针

### ISSUE THREAD

**Issue by walkhan** [alibaba/canal#4049]
2022-01-29 15:27:31.623 [pool-4-thread-1] ERROR c.a.o.c.c.pulsarmq.producer.CanalPulsarMQProducer - java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.NullPointerException
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.NullPointerException
        at com.alibaba.otter.canal.common.utils.ExecutorTemplate.waitForResult(ExecutorTemplate.java:74) ~[canal.common-1.1.6-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.connector.pulsarmq.producer.CanalPulsarMQProducer.send(CanalPulsarMQProducer.java:152) ~[na:na]
        at com.alibaba.otter.canal.server.CanalMQStarter.worker(CanalMQStarter.java:181) [canal.server-1.1.6-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.server.CanalMQStarter.access$100(CanalMQStarter.java:24) [canal.server-1.1.6-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.server.CanalMQStarter$CanalMQRunnable.run(CanalMQStarter.java:223) [canal.server-1.1.6-SNAPSHOT.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_211]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_211]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_211]
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_211]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_211]
        at com.alibaba.otter.canal.common.utils.ExecutorTemplate.waitForResult(ExecutorTemplate.java:72) ~[canal.common-1.1.6-SNAPSHOT.jar:na]
        ... 7 common frames omitted
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
        at com.alibaba.otter.canal.connector.pulsarmq.producer.CanalPulsarMQProducer.lambda$send$0(CanalPulsarMQProducer.java:147) ~[na:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_211]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_211]
        ... 3 common frames omitted
Caused by: java.lang.NullPointerException: null

配置 canal.properties如下:
![image](https://user-images.githubusercontent.com/16821730/151652023-eb4aee56-ab74-4bb3-b07b-1b1b812250ed.png)
pulsar配置已经添加如下：
![image](https://user-images.githubusercontent.com/16821730/151652105-bb1d544b-d45f-44e8-a89e-485bd710f13e.png)

请教是哪里的问题吗？

**Comment by agapple** [comment]
日志不太全，看不到NPE具体的代码栈
