### ISSUE TITLE
canal-adapter RDB方式同步的时候，schema带横杠(横线)的时候有问题

### ISSUE THREAD

**Issue by jimmy384** [alibaba/canal#4071]
- [x] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version: 1.1.5
* mysql version: 5.7.30

### Issue Description
rdb adapter同步的时候配置了
```yml
...
dbMapping:
  database: 'my-schema'
  table: table1
...
```
etl的时候会报sql语法错误，最后拼接执行的sql schema缺失了一部分
```sql
select * from -schema.table1
```
此时
增量同步：OK
ETL全量同步：报错

报错的日志:
```
2022-02-19 20:35:39.711 [http-nio-8081-exec-4] ERROR c.a.otter.canal.client.adapter.rdb.service.RdbEtlService - com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in you     r SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-schema.table1 where credate>='2022-01-01 00:00:00') _CNT' at line 1
java.lang.RuntimeException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the      right syntax to use near '-schema.table1 where credate>='2022-01-01 00:00:00') _CNT' at line 1
    at com.alibaba.otter.canal.client.adapter.support.Util.sqlRS(Util.java:65) ~[client-adapter.common-1.1.5.jar:na]
    at com.alibaba.otter.canal.client.adapter.support.AbstractEtlService.importData(AbstractEtlService.java:62) ~[client-adapter.common-1.1.5.jar:na]
    at com.alibaba.otter.canal.client.adapter.rdb.service.RdbEtlService.importData(RdbEtlService.java:47) [client-adapter.rdb-1.1.5-jar-with-dependencies.jar:na]
    at com.alibaba.otter.canal.client.adapter.rdb.RdbAdapter.etl(RdbAdapter.java:188) [client-adapter.rdb-1.1.5-jar-with-dependencies.jar:na]
```

---

把database加上"`"
```yml
...
dbMapping:
  database: '`my-schema`'
  table: table1
...
```
此时
增量同步：失效了（应该时对比schema的时候多了个"`"对不上）
ETL全量同步：OK

其他adapter没试过

**Comment by agapple** [comment]
可以考虑提交下PR给我

**Comment by yegaofei** [comment]
我也遇到了这个问题， 一开始把全量同步的问题修复好了，结果增量同步怎么弄都不行。。。
