### ISSUE TITLE
Canal任务建立时候报错会导致该任务始终无法启动

### ISSUE THREAD

**Issue by simake2017** [alibaba/canal#4084]
canal 114 version

bug复现: 通过admin 添加一个 任务后，这个任务在创建的时候报错，那么这个任务将不会在创建成功，异常截图
<img width="1378" alt="image" src="https://user-images.githubusercontent.com/31234273/156304440-31fec843-998a-431e-9180-9c9f61af77a0.png">

bug 分析:
任务添加之后，会调用scan() 方法，在调用下图方法之后，会创建任务，并且将这个任务放到canalInstances里面，如果
创建的时候发生异常，如上图，在调用admin 的时候发生报错，就会导致创建失败
<img width="898" alt="image" src="https://user-images.githubusercontent.com/31234273/156304897-00f0655d-8075-434a-b649-de979257bad3.png">

而在下图中，scan的时候，会将这个instance放入到 configs里面去，导致了每次scan的时候，导致了这个任务被认为已经创建成功(在configs)里面，而不能被重启，只能重启整个canal server 才行。
<img width="1174" alt="image" src="https://user-images.githubusercontent.com/31234273/156305069-f0a2436e-68ee-494c-a2ba-ab701af87355.png">

bug修复：
修改scan逻辑：修复如下图，除了判断 content的md5，还要判断canalEmbedServer的 instances里面是否包含这个 instance
<img width="1209" alt="image" src="https://user-images.githubusercontent.com/31234273/156305579-72c0930d-c085-4c26-9ffe-0c6fca912e23.png">

**Comment by dingyufei615** [comment]
遇到和你一样的问题 server日志里看到
2022-04-19 19:41:45.743 [canal-instance-scan-0] ERROR c.a.o.c.deployer.monitor.ManagerInstanceConfigMonitor - scan failed
com.alibaba.otter.canal.common.CanalException: load manager config failed.
Caused by: java.lang.RuntimeException: requestGet remote error, request : http://****:***/api/v1/config/instance_polling/**** ?md5=
	at com.alibaba.otter.canal.instance.manager.plain.HttpHelper.get(HttpHelper.java:100) ~[canal.instance.manager-1.1.5.jar:na]
	at com.alibaba.otter.canal.instance.manager.plain.PlainCanalConfigClient.doQuery(PlainCanalConfigClient.java:121) ~[canal.instance.manager-1.1.5.jar:na]
	at com.alibaba.otter.canal.instance.manager.plain.PlainCanalConfigClient.queryConfig(PlainCanalConfigClient.java:110) ~[canal.instance.manager-1.1.5.jar:na]

**Comment by simake2017** [comment]
> 

不活跃了

**Comment by agapple** [comment]
可以考虑提交一个PR给我
