### ISSUE TITLE
canal全量同步失败

### ISSUE THREAD

**Issue by Amaiyeye** [alibaba/canal#4085]
canal 全量同步 mysql 某些表的数据到 rocketmq，有的表可以同步进 rocketmq，有的表不行，而且不管行或者不行都会报下面的报错：

Caused by: org.apache.rocketmq.client.exception.MQClientException: The specified topic is blank
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
	at org.apache.rocketmq.client.Validators.checkTopic(Validators.java:107) ~[na:na]
	at org.apache.rocketmq.client.Validators.checkMessage(Validators.java:87) ~[na:na]
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendSelectImpl(DefaultMQProducerImpl.java:1104) ~[na:na]
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1092) ~[na:na]
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1087) ~[na:na]
	at org.apache.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:508) ~[na:na]
	at com.alibaba.otter.canal.connector.rocketmq.producer.CanalRocketMQProducer.sendMessage(CanalRocketMQProducer.java:287) ~[na:na]
	... 8 common frames omitted

其他一点报错没有，各位大神有遇到跟我一样情况的么

**Comment by bai020** [comment]
有的，也碰到了，说是canal.mq.topic不能为空，配一个默认值

**Comment by liuwenzhi0318** [comment]
配置了canal.mq.topic 默认值后，动态 topic 就不生效了。怎么解决
