### ISSUE TITLE
1.14版本的adapter连接canalserver时报错：something goes wrong when doing authentication: auth failed for user:

### ISSUE THREAD

**Issue by liteng2430** [alibaba/canal#4090]
## Question

2022-03-05 14:21:39.190 [Thread-4] INFO  c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - =============> Start to connect destination: shsc_wms_wnc <=============
2022-03-05 14:21:39.192 [Thread-4] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterWorker - process error!
com.alibaba.otter.canal.protocol.exception.CanalClientException: something goes wrong when doing authentication: auth failed for user:
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:192)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.connect(SimpleCanalConnector.java:115)
	at com.alibaba.otter.canal.adapter.launcher.loader.CanalAdapterWorker.process(CanalAdapterWorker.java:88)
	at java.lang.Thread.run(Thread.java:748)

**Comment by agapple** [comment]
auth failed for user ？检查下配置

**Comment by chendazhao** [comment]
这问题是没有官方人员来解决么？？？

**Comment by chendazhao** [comment]
这么傻逼的bug
