### ISSUE TITLE
adapter全量同步大数据量情况下出现deadlock

### ISSUE THREAD

**Issue by Shawn0Parker** [alibaba/canal#4093]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal adapter version 1.15
* mysql version 8.0

### Issue Description
使用adatper同步大数据量（100w）失败，提示如下：

```
2022-03-06 17:44:49.110 [pool-8-thread-29] ERROR c.a.otter.canal.client.adapter.rdb.service.RdbEtlService - etl failed! ==>Deadlock found when trying to get lock; try restarting transaction
com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:123) ~[mysql-connector-java-8.0.21.jar:8.0.21]
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.21.jar:8.0.21]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.21.jar:8.0.21]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[mysql-connector-java-8.0.21.jar:8.0.21]
        at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:370) ~[mysql-connector-java-8.0.21.jar:8.0.21]
        at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:498) ~[druid-1.1.9.jar:1.1.9]
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbEtlService.lambda$executeSqlImport$2(RdbEtlService.java:140) ~[na:na]
        at com.alibaba.otter.canal.client.adapter.support.Util.sqlRS(Util.java:62) ~[client-adapter.common-1.1.5-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbEtlService.executeSqlImport(RdbEtlService.java:79) ~[na:na]
        at com.alibaba.otter.canal.client.adapter.support.AbstractEtlService.lambda$importData$1(AbstractEtlService.java:91) ~[client-adapter.common-1.1.5-SNAPSHOT.jar:na]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_311]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_311]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_311]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_311]
```

**Comment by yhtomcat** [comment]
看一下数据库的隔离级别，默认rr，调整成rc
