### ISSUE TITLE
canal 1.5 同步 elasticsearch 7.4.2 日期格式化问题

### ISSUE THREAD

**Issue by zhaoyong123** [alibaba/canal#4098]
2022-03-09 10:52:51.700 [pool-2-thread-1] ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - ES sync commit error ElasticsearchException[Elasticsearch exception [type=mapper_parsing_exception, reason=failed to parse field [publish_time] of type [date] in document with id '12'. Preview of field's value: '2022-03-08T08:07:35+08:00']]; nested: ElasticsearchException[Elasticsearch exception [type=illegal_argument_exception, reason=failed to parse date field [2022-03-08T08:07:35+08:00] with format [yyyy-MM-dd HH:mm:ss]]]; nested: ElasticsearchException[Elasticsearch exception [type=date_time_parse_exception, reason=Text '2022-03-08T08:07:35+08:00' could not be parsed at index 10]];
java.lang**.RuntimeException: ES sync commit error ElasticsearchException[Elasticsearch exception [type=mapper_parsing_exception, reason=failed to parse field [publish_time] of type [date] in document with id '12'. Preview of field's value: '2022-03-08T08:07:35+08:00']];** nested: ElasticsearchException[Elasticsearch exception [type=illegal_argument_exception, reason=failed to parse date field [2022-03-08T08:07:35+08:00] with format [yyyy-MM-dd HH:mm:ss]]]; nested: ElasticsearchException[Elasticsearch exception [type=date_time_parse_exception, reason=Text '2022-03-08T08:07:35+08:00' could not be parsed at index 10]];
        at com.alibaba.otter.canal.client.adapter.es7x.support.ESConnection$ES7xBulkResponse.processFailBulkResponse(ESConnection.java:474) ~[na:na]
        at com.alibaba.otter.canal.client.adapter.es7x.support.ES7xTemplate.commit(ES7xTemplate.java:175) ~[na:na]
        at com.alibaba.otter.canal.client.adapter.es.core.service.ESSyncService.commit(ESSyncService.java:877) ~[na:na]
        at com.alibaba.otter.canal.client.adapter.es.core.ESAdapter.sync(ESAdapter.java:97) ~[na:na]
        at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.batchSync(AdapterProcessor.java:139) ~[client-adapter.launcher-1.1.5.jar:na]
        at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.lambda$null$1(AdapterProcessor.java:97) ~[client-adapter.launcher-1.1.5.jar:na]
        at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor$$Lambda$422/180256630.accept(Unknown Source) ~[na:na]
        at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890) ~[na:1.8.0_41]
        at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.lambda$null$2(AdapterProcessor.java:94) ~[client-adapter.launcher-1.1.5.jar:na]
        at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor$$Lambda$421/1632730019.call(Unknown Source) [client-adapter.launcher-1.1.5.jar:na]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_41]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_41]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_41]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_41]
2022-03-09 10:52:51.703 [Thread-4] ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - Outer adapter sync failed!  Error sync but ACK!

我想使用的日期格式是：yyyy-MM-dd HH:mm:ss 但是使用该格式同步报错
"publish_time": {
         "type": "date",
         "format": "yyyy-MM-dd HH:mm:ss"
  }

但是需要加上“strict_date_optional_time” 这个才可以。
"publish_time" : {
            "type" : "date",
            "format" : "yyyy-MM-dd HH:mm:ss || strict_date_optional_time"
}

使用 strict_date_optional_time 获取的到的 “2022-02-24T17:00:00+08:00”  该格式 不是我想要的，

请问各位大佬，还有其他解决方案吗？

**Comment by HZLHZLHZL** [comment]
需要修改源码。源码里默认将日期都加时区的。百度查下就知道了。修改完后，重新打个jar包运行就可以了。

**Comment by pengchen211** [comment]
修改源码
com.alibaba.otter.canal.client.adapter.es.core.support.ESSyncUtil.typeConvert(...)
