### ISSUE TITLE
canal 1.1.4和1.1.5同步mysql 5.6.23的binlog报错

### ISSUE THREAD

**Issue by 1099895519** [alibaba/canal#4129]
- [x] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version
   1.1.4 和 1.1.5
* mysql version
   5.6.23

### Issue Description
在同步binlog的时候报错ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[com.alibaba.otter.canal.parse.exception.CanalParseException: java.lang.IllegalArgumentException: unknow type : 37

### Actual behaviour

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
2022-04-02 18:41:22.880 [destination = example , address = /xxxxxxxxxxxxx , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[com.alibaba.otter.canal.parse.exception.CanalParseException: java.lang.IllegalArgumentException: unknow type : 37
Caused by: java.lang.IllegalArgumentException: unknow type : 37
	at com.taobao.tddl.dbsync.binlog.event.TableMapLogEvent.<init>(TableMapLogEvent.java:487)
	at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:182)
	at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:111)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:264)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:246)
	at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by 1099895519** [comment]
有大神知晓的，跪求答案

**Comment by systemzsz** [comment]
是不是某些数据类型没法处理？建议可以建一些简单的测试表来测试下。

**Comment by agapple** [comment]
type 37，这个没见过

**Comment by 1099895519** [comment]
> type 37，这个没见过

嗯嗯，艰难，准备放弃使用canal了
