### ISSUE TITLE
ErrorPacket 错误是什么情况

### ISSUE THREAD

**Issue by xghrbc1001** [alibaba/canal#413]
INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - KILL DUMP 151432475 failure:java.io.IOException: ErrorPacket [errorNumber=1094, fieldCount=-1, message=Unknown thread id: 151432475, sqlState=HY000, sqlStateMarker=#]
 with command: KILL CONNECTION 151432475
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlUpdateExecutor.update(MysqlUpdateExecutor.java:49)
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.disconnect(MysqlConnector.java:104)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.disconnect(MysqlConnection.java:64)
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:241)
        at java.lang.Thread.run(Thread.java:748)

**Comment by agapple** [comment]
升级canal版本即可
