### ISSUE TITLE
求助，启动canal server后报错

### ISSUE THREAD

**Issue by loveluckystar** [alibaba/canal#415]
2017-11-13 10:41:41.588 [destination = example , address = /127.0.0.1:3306 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta - parse faield : flush privileges
com.alibaba.druid.sql.parser.ParserException: syntax error, expect TABLES, actual IDENTIFIER, pos 16, line 1, column 6, token IDENTIFIER privileges
	at com.alibaba.druid.sql.parser.SQLParser.acceptIdentifier(SQLParser.java:60) ~[druid-1.1.5.jar:1.1.5]
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseFlush(MySqlStatementParser.java:915) ~[druid-1.1.5.jar:1.1.5]
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseStatementListDialect(MySqlStatementParser.java:762) ~[druid-1.1.5.jar:1.1.5]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:388) ~[druid-1.1.5.jar:1.1.5]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:70) ~[druid-1.1.5.jar:1.1.5]
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:461) ~[druid-1.1.5.jar:1.1.5]
	at com.alibaba.druid.sql.repository.SchemaRepository.console(SchemaRepository.java:295) ~[druid-1.1.5.jar:1.1.5]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta.apply(MemoryTableMeta.java:67) ~[canal.parse-1.0.25-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.applyHistoryOnMemory(DatabaseTableMeta.java:387) [canal.parse-1.0.25-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:121) [canal.parse-1.0.25-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:72) [canal.parse-1.0.25-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:170) [canal.parse-1.0.25-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
2017-11-13 10:41:41.590 [destination = example , address = /127.0.0.1:3306 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta - parse faield : flush privileges
com.alibaba.druid.sql.parser.ParserException: syntax error, expect TABLES, actual IDENTIFIER, pos 16, line 1, column 6, token IDENTIFIER privileges
	at com.alibaba.druid.sql.parser.SQLParser.acceptIdentifier(SQLParser.java:60) ~[druid-1.1.5.jar:1.1.5]
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseFlush(MySqlStatementParser.java:915) ~[druid-1.1.5.jar:1.1.5]
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseStatementListDialect(MySqlStatementParser.java:762) ~[druid-1.1.5.jar:1.1.5]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:388) ~[druid-1.1.5.jar:1.1.5]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:70) ~[druid-1.1.5.jar:1.1.5]
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:461) ~[druid-1.1.5.jar:1.1.5]
	at com.alibaba.druid.sql.repository.SchemaRepository.console(SchemaRepository.java:295) ~[druid-1.1.5.jar:1.1.5]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta.apply(MemoryTableMeta.java:67) ~[canal.parse-1.0.25-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.applyHistoryOnMemory(DatabaseTableMeta.java:387) [canal.parse-1.0.25-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:121) [canal.parse-1.0.25-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:72) [canal.parse-1.0.25-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:170) [canal.parse-1.0.25-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]

**Comment by DevonZhao** [comment]
看样子像是权限的问题。

**Comment by loveluckystar** [comment]
我是先启动了canal server，然后我重新执行了一次flush privileges给canal用户赋权，就一直出现这个报错。

**Comment by yangzhongj** [comment]
楼兄 这个项目活跃度还是挺高的， 我准备详细看下源码实现

**Comment by zhangshenglong521** [comment]
临时解决方案，com.alibaba.otter.canal.parse.inbound.mysql.tsdb.apply()中将ddl中的alter user 、flush privileges的语句过滤掉即可。

**Comment by agapple** [comment]
这块只会记录异常日志，本身是try catch不影响功能

**Comment by agapple** [comment]
druid 1.1.6暂时不支持flush privileges的解析，临时先绕过，已经反馈给druid的作者
