### ISSUE TITLE
canal-deployer 启动报错，这个是什么原因啊，求助 ERROR c.a.o.c.common.zookeeper.running.ServerRunningMonitor - start failed

### ISSUE THREAD

**Issue by forkgithubs** [alibaba/canal#4153]
2022-04-24 17:30:34.550 [main] INFO  com.alibaba.otter.canal.deployer.CanalLauncher - ## set default uncaught exception handler
2022-04-24 17:30:34.575 [main] INFO  com.alibaba.otter.canal.deployer.CanalLauncher - ## load canal configurations
2022-04-24 17:30:34.583 [main] INFO  com.alibaba.otter.canal.deployer.CanalStarter - ## start the canal server.
2022-04-24 17:30:34.613 [main] INFO  com.alibaba.otter.canal.deployer.CanalController - ## start the canal server[172.17.0.1(172.17.0.1):11111]
2022-04-24 17:30:35.470 [main] ERROR c.a.o.c.common.zookeeper.running.ServerRunningMonitor - start failed
com.alibaba.otter.canal.meta.exception.CanalMetaManagerException: dir[../conf] can not read/write
2022-04-24 17:30:35.478 [main] ERROR c.a.o.c.common.zookeeper.running.ServerRunningMonitor - processActiveExit failed
java.lang.NullPointerException: null
	at com.alibaba.otter.canal.meta.FileMixedMetaManager.stop(FileMixedMetaManager.java:120) ~[canal.meta-1.1.5.jar:na]
	at com.alibaba.otter.canal.instance.core.AbstractCanalInstance.stop(AbstractCanalInstance.java:122) ~[canal.instance.core-1.1.5.jar:na]
	at com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded.stop(CanalServerWithEmbedded.java:149) ~[canal.server-1.1.5.jar:na]
	at com.alibaba.otter.canal.deployer.CanalController$1.processActiveExit(CanalController.java:167) ~[canal.deployer-1.1.5.jar:na]
	at com.alibaba.otter.canal.common.zookeeper.running.ServerRunningMonitor.processActiveExit(ServerRunningMonitor.java:249) [canal.common-1.1.5.jar:na]
	at com.alibaba.otter.canal.common.zookeeper.running.ServerRunningMonitor.stop(ServerRunningMonitor.java:128) [canal.common-1.1.5.jar:na]
	at com.alibaba.otter.canal.common.zookeeper.running.ServerRunningMonitor.start(ServerRunningMonitor.java:104) [canal.common-1.1.5.jar:na]
	at com.alibaba.otter.canal.deployer.CanalController.start(CanalController.java:497) [canal.deployer-1.1.5.jar:na]
	at com.alibaba.otter.canal.deployer.CanalStarter.start(CanalStarter.java:89) [canal.deployer-1.1.5.jar:na]
	at com.alibaba.otter.canal.deployer.CanalLauncher.main(CanalLauncher.java:117) [canal.deployer-1.1.5.jar:na]

**Comment by agapple** [comment]
dir[../conf] can not read/write，检查下目录权限

**Comment by lijiwei** [comment]
你检查目录权限之后就好了吗
