### ISSUE TITLE
单体，mysql 8.0； canal Server端监听instance，已经停止对该实例的监听任务，还是一直报错。

### ISSUE THREAD

**Issue by axiaoqing** [alibaba/canal#4154]
ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example_lcrmcenter[java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:235)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:265)
	at java.lang.Thread.run(Unknown Source)

**Comment by axiaoqing** [comment]
删除 meda.dat 文件也不好使。。监听已经停掉了，还一直在打印报错

**Comment by agapple** [comment]
Could not find first log file name in binary log index file，binlog已删除需要重置位点
