### ISSUE TITLE
cannal deployer 监控mysql8.0 空指针异常

### ISSUE THREAD

**Issue by code19971001** [alibaba/canal#4159]
canal ：1.1.4/1.1.5
mysql ：8.0.26

首先使用canal 1.1.4监控mysql: 8.0然后sink到kafka，发现无消息，查看canal日志，报空指针异常。尝试连接更低版本的mysql: 5.6.50，一切正常。尝试升级 canal：1.1.5。依旧出现同样的异常。

连接mysql 8.0  canal日志如下：
```txt2022-04-30 19:09:15.236 [main] INFO  c.a.otter.canal.instance.spring.CanalInstanceWithSpring - start CannalInstance for 1-example 
2022-04-30 19:09:15.245 [main] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table filter : ^.*\..*$
2022-04-30 19:09:15.245 [main] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table black filter : ^mysql\.slave_.*$
2022-04-30 19:09:15.251 [main] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - start successful....
2022-04-30 19:09:15.323 [destination = example , address = hadoop02/192.168.134.142:3307 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> begin to find start position, it will be long time for reset or first position
2022-04-30 19:09:15.323 [destination = example , address = hadoop02/192.168.134.142:3307 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - prepare to find start position just show master status
2022-04-30 19:09:15.774 [destination = example , address = hadoop02/192.168.134.142:3307 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address hadoop02/192.168.134.142:3307 has an error, retrying. caused by 
java.lang.NullPointerException: null
	at com.alibaba.druid.sql.visitor.SQLASTOutputVisitor.visit(SQLASTOutputVisitor.java:5298) ~[druid-1.2.6.jar:1.2.6]
	at com.alibaba.druid.sql.ast.statement.SQLCheck.accept0(SQLCheck.java:49) ~[druid-1.2.6.jar:1.2.6]
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:49) ~[druid-1.2.6.jar:1.2.6]
	at com.alibaba.druid.sql.visitor.SQLASTOutputVisitor.printTableElements(SQLASTOutputVisitor.java:3493) ~[druid-1.2.6.jar:1.2.6]
	at com.alibaba.druid.sql.visitor.SQLASTOutputVisitor.visit(SQLASTOutputVisitor.java:9390) ~[druid-1.2.6.jar:1.2.6]
	at com.alibaba.druid.sql.dialect.mysql.ast.statement.MySqlCreateTableStatement.accept0(MySqlCreateTableStatement.java:125) ~[druid-1.2.6.jar:1.2.6]
	at com.alibaba.druid.sql.dialect.mysql.ast.statement.MySqlCreateTableStatement.accept0(MySqlCreateTableStatement.java:85) ~[druid-1.2.6.jar:1.2.6]
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:49) ~[druid-1.2.6.jar:1.2.6]
	at com.alibaba.druid.sql.ast.SQLObjectImpl.output(SQLObjectImpl.java:90) ~[druid-1.2.6.jar:1.2.6]
	at com.alibaba.druid.sql.ast.SQLObjectImpl.output(SQLObjectImpl.java:75) ~[druid-1.2.6.jar:1.2.6]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta.snapshot(MemoryTableMeta.java:151) ~[canal.parse-1.1.5.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.applySnapshotToDB(DatabaseTableMeta.java:290) ~[canal.parse-1.1.5.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:175) ~[canal.parse-1.1.5.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:142) ~[canal.parse-1.1.5.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:197) ~[canal.parse-1.1.5.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_141]
2022-04-30 19:09:15.776 [destination = example , address = hadoop02/192.168.134.142:3307 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[java.lang.NullPointerException
	at com.alibaba.druid.sql.visitor.SQLASTOutputVisitor.visit(SQLASTOutputVisitor.java:5298)
	at com.alibaba.druid.sql.ast.statement.SQLCheck.accept0(SQLCheck.java:49)
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:49)
	at com.alibaba.druid.sql.visitor.SQLASTOutputVisitor.printTableElements(SQLASTOutputVisitor.java:3493)
	at com.alibaba.druid.sql.visitor.SQLASTOutputVisitor.visit(SQLASTOutputVisitor.java:9390)
	at com.alibaba.druid.sql.dialect.mysql.ast.statement.MySqlCreateTableStatement.accept0(MySqlCreateTableStatement.java:125)
	at com.alibaba.druid.sql.dialect.mysql.ast.statement.MySqlCreateTableStatement.accept0(MySqlCreateTableStatement.java:85)
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:49)
	at com.alibaba.druid.sql.ast.SQLObjectImpl.output(SQLObjectImpl.java:90)
	at com.alibaba.druid.sql.ast.SQLObjectImpl.output(SQLObjectImpl.java:75)
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta.snapshot(MemoryTableMeta.java:151)
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.applySnapshotToDB(DatabaseTableMeta.java:290)
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:175)
	at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:142)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:197)
	at java.lang.Thread.run(Thread.java:748)
]
```
连接mysql 5.6  canal日志如下：
```txt
2022-04-30 19:13:45.225 [main] INFO  c.a.otter.canal.instance.spring.CanalInstanceWithSpring - start CannalInstance for 1-example 
2022-04-30 19:13:45.238 [main] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table filter : ^.*\..*$
2022-04-30 19:13:45.238 [main] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table black filter : ^mysql\.slave_.*$
2022-04-30 19:13:45.243 [main] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - start successful....
2022-04-30 19:13:45.333 [destination = example , address = hadoop02/192.168.134.142:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> begin to find start position, it will be long time for reset or first position
2022-04-30 19:13:45.333 [destination = example , address = hadoop02/192.168.134.142:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - prepare to find start position just show master status
2022-04-30 19:13:46.383 [destination = example , address = hadoop02/192.168.134.142:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> find start position successfully, EntryPosition[included=false,journalName=mysql-bin.000002,position=195,serverId=2,gtid=,timestamp=1651315794000] cost : 1043ms , the next step is binlog dump
2022-04-30 19:16:30.460 [Thread-6] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - stop CannalInstance for null-example 
2022-04-30 19:16:30.622 [Thread-6] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - stop successful....
```

**Comment by gongzh021** [comment]
我遇到了同样的问题，楼主解决了吗？

**Comment by code19971001** [comment]
> 我遇到了同样的问题，楼主解决了吗？

没有，我只是测试使用canal，最终没有选用。如果将mysql降级为5.x是可以走通的

**Comment by JTjeff** [comment]
是否是jar驱动包的问题，一般这种NullPointerException报错是application.yml文件有地方书写错误

**Comment by agapple** [comment]
估计遇到一条无法解析的DDL语句，可以尝试反解析下binlog，找下报错时的ddl语句发我

**Comment by xuyunxuyun** [comment]
我遇到的问题相同，经反复测试是tsdb出现的问题，如果不需要此功能，可以在配置文件中关闭tsdb，问题解决。
canal.instance.tsdb.enable = false

**Comment by itgcl** [comment]
> 我遇到的问题相同，经反复测试是tsdb出现的问题，如果不需要此功能，可以在配置文件中关闭tsdb，问题解决。 canal.instance.tsdb.enable = false

感谢，改为false可以了
