### ISSUE TITLE
遇到个问题，求解决

### ISSUE THREAD

**Issue by zhaoyang199108** [alibaba/canal#4181]
报错内容如下：
com.alibaba.fastjson.JSONException: syntax error, expect {, actual [, pos 1, line 1, column 2[{"id": 1523858648291274766, "member_id": "MID1410534593045422082808", "coupon_code": "YH20210907029717"},{"id": 1523858648291274771, "member_id": "MID1410534593045422082808", "coupon_code": "YH20210907029717"},{"id": 1523858648291274777, "member_id": "MID1410534593045422082808", "coupon_code": "YH20210907029717"}]
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:197) ~[fastjson-1.2.58.sec06.jar:na]
	at com.alibaba.fastjson.parser.deserializer.MapDeserializer.deserialze(MapDeserializer.java:70) ~[fastjson-1.2.58.sec06.jar:na]
	at com.alibaba.fastjson.parser.deserializer.MapDeserializer.deserialze(MapDeserializer.java:43) ~[fastjson-1.2.58.sec06.jar:na]
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:689) ~[fastjson-1.2.58.sec06.jar:na]
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:378) ~[fastjson-1.2.58.sec06.jar:na]
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:282) ~[fastjson-1.2.58.sec06.jar:na]
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:555) ~[fastjson-1.2.58.sec06.jar:na]
	at com.alibaba.otter.canal.client.adapter.es.core.support.ESSyncUtil.typeConvert(ESSyncUtil.java:240) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.es7x.support.ES7xTemplate.getValFromRS(ES7xTemplate.java:199) ~[na:na]

配置文件如下：
dataSourceKey: defaultDS # 源数据源的key, 对应上面配置的srcDataSources中的值
destination: example  # canal的instance或者MQ的topic
groupId: g1 # 对应MQ模式下的groupId, 只会同步对应groupId的数据
esMapping:
  _index: coupon_sended_and_store_test4 # es 的索引名称
  _id: _id  # es 的_id, 如果不配置该项必须配置下面的pk项_id则会由es自动分配
  sql: "SELECT
   p.id as _id,
   p.templet_code,
   p.coupon_code,
	 p.coupon_name,
	 p.batch_number,
	 p.send_channel,
	 p.form_type,
	 p.source_order_type,
	 p.source_order_code,
	 p.attribute_code,
	 p.plan_type,
	 p.plan_code,
	 p.plan_name,
	 p.activity_code,
	 p.activity_name,
	 p.compensate_reason,
	 p.gain_reason,
	 p.use_rule,
	 p.coupon_type,
	 p.target,
	 p.strategy,
	 p.full_amount,
	 p.dis_amount,
	 p.piece_amount,
	 p.discount,
	 p.max_dis_amount,
	 p.use_status,
	 p.active_time,
	 p.invalid_time,
	 p.use_time,
	 p.use_bill_type,
	 p.bill_code,
	 p.actual_reduce_amount,
	 p.member_id,
	 p.member_name,
	 p.member_phone,
	 p.equipment_code,
	 p.consume_type,
	 p.coupon_desc,
	 p.share_percentage,
	 p.delete_flag,
	 p.create_user,
	 p.create_time,
	 p.update_user,
	 p.update_time,
	 p.remark,
	 CONCAT('[',s.temp,']') as temps
        FROM
         coupon_sended_0 p left join (select coupon_code,group_concat(json_object('id',id,'coupon_code',coupon_code,'member_id',member_id)) as temp from coupon_sended_scene_store_0  group by coupon_code) s  on s.coupon_code = p.coupon_code"        # sql映射
#etlCondition: "where p.id>={}"   #etl的条件参数
commitBatch: 3000   # 提交批大小
objFields:
    temps: object

**Comment by zhaoyang199108** [comment]
感觉是objFields:没生效，大佬们有遇到过么

**Comment by xiaobai6** [comment]
请问您是怎么解决的，方便告知下吗，遇到同样的问题
