### ISSUE TITLE
1.1.5升级到1.1.6之后，第一次startup是正常的，但是stop之后再启动就会报错

### ISSUE THREAD

**Issue by tangweichun** [alibaba/canal#4186]
2022-05-24 19:55:16.050 [pool-5-thread-2] ERROR com.alibaba.otter.canal.server.CanalMQStarter - process error!
com.google.common.util.concurrent.UncheckedExecutionException: com.alibaba.fastjson2.JSONException: create instance error, class com.alibaba.otter.canal.protocol.position.Position
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2218) ~[guava-22.0.jar:na]
        at com.google.common.cache.LocalCache.get(LocalCache.java:4147) ~[guava-22.0.jar:na]
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4151) ~[guava-22.0.jar:na]
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5140) ~[guava-22.0.jar:na]
        at com.google.common.collect.MigrateMap$MigrateConcurrentMap.get(MigrateMap.java:68) ~[canal.common-1.1.6.jar:na]
        at com.alibaba.otter.canal.meta.MemoryMetaManager.getCursor(MemoryMetaManager.java:76) ~[canal.meta-1.1.6.jar:na]
        at com.alibaba.otter.canal.meta.PeriodMixedMetaManager.getCursor(PeriodMixedMetaManager.java:126) ~[canal.meta-1.1.6.jar:na]
        at com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded.subscribe(CanalServerWithEmbedded.java:180) ~[canal.server-1.1.6.jar:na]
        at com.alibaba.otter.canal.server.CanalMQStarter.worker(CanalMQStarter.java:161) [canal.server-1.1.6.jar:na]
        at com.alibaba.otter.canal.server.CanalMQStarter.access$100(CanalMQStarter.java:24) [canal.server-1.1.6.jar:na]
        at com.alibaba.otter.canal.server.CanalMQStarter$CanalMQRunnable.run(CanalMQStarter.java:223) [canal.server-1.1.6.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_192]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_192]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_192]
Caused by: com.alibaba.fastjson2.JSONException: create instance error, class com.alibaba.otter.canal.protocol.position.Position
        at com.alibaba.fastjson2.reader.ObjectReaderAdapter.createInstance0(ObjectReaderAdapter.java:178) ~[fastjson2-2.0.4.jar:na]
        at com.alibaba.fastjson2.reader.ObjectReaderAdapter.createInstance(ObjectReaderAdapter.java:233) ~[fastjson2-2.0.4.jar:na]
        at com.alibaba.fastjson2.reader.ObjectReaderBean.readObject(ObjectReaderBean.java:162) ~[fastjson2-2.0.4.jar:na]
        at com.alibaba.fastjson2.JSON.parseObject(JSON.java:459) ~[fastjson2-2.0.4.jar:na]
        at com.alibaba.otter.canal.common.utils.JsonUtils.unmarshalFromByte(JsonUtils.java:35) ~[canal.common-1.1.6.jar:na]
        at com.alibaba.otter.canal.meta.ZooKeeperMetaManager.getCursor(ZooKeeperMetaManager.java:153) ~[canal.meta-1.1.6.jar:na]
        at com.alibaba.otter.canal.meta.PeriodMixedMetaManager.lambda$start$1(PeriodMixedMetaManager.java:57) ~[canal.meta-1.1.6.jar:na]
        at com.google.common.collect.MigrateMap$1.load(MigrateMap.java:23) ~[canal.common-1.1.6.jar:na]
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3708) ~[guava-22.0.jar:na]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2416) ~[guava-22.0.jar:na]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2299) ~[guava-22.0.jar:na]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2212) ~[guava-22.0.jar:na]
        ... 13 common frames omitted

**Comment by tangweichun** [comment]
每次启动都要创建instance，但是我只是重启，老的instance都存在，感觉问题是这样，怎解？

**Comment by benyVip** [comment]
> 每次启动都要创建instance，但是我只是重启，老的instance都存在，感觉问题是这样，怎解？

这就是一个bug，json没法序列化meta里面的数据，我也遇到了

**Comment by tangweichun** [comment]
> > 每次启动都要创建instance，但是我只是重启，老的instance都存在，感觉问题是这样，怎解？
> 
> 这就是一个bug，json没法序列化meta里面的数据，我也遇到了

谢谢，你有没解决这个问题呢，不重启也没问题，关键不可能不重启

**Comment by kjyyc** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/13294906/170410528-07dfc04c-54e0-4a59-902b-4842d133dfb4.png">
我测试了下，手动序列化再反序列化LogPosition，出现同样的报错。
Caused by: com.alibaba.fastjson2.JSONException: create instance error, class java.net.InetSocketAddress
<img width="1336" alt="image" src="https://user-images.githubusercontent.com/13294906/170410945-9c0e7e58-5d8b-4e32-a413-d1cd9912ef6f.png">

看了提交记录，是5月13号升级了fastjson2。感觉是fastjson2对InetSocketAddress的反序列化支持有问题

**Comment by agapple** [comment]
问题已明确

**Comment by agapple** [comment]
https://github.com/alibaba/canal/pull/4202
