### ISSUE TITLE
canal1.0.24，以前好好的，最近新加了一个实例之后，就一直报这个错，client能消费到（不知道数据是否丢失一部分）

### ISSUE THREAD

**Issue by tdytaylor** [alibaba/canal#419]
2017-11-21 11:40:16.215 [destination = example31 , address = /localhost:30701 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - prepare to find start position just last position
 {"identity":{"slaveId":-1,"sourceAddress":{"address":"localhost","port":30701}},"postion":{"included":false,"journalName":"mysql-bin.000220","position":3614315,"serverId":1,"timestamp":1511235396000}}
2017-11-21 11:40:46.230 [destination = example31 , address = /localhost:30701 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - I/O error while reading from client socket
java.io.IOException: Unexpected End Stream
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:156) ~[canal.parse-1.0.24.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:70) ~[canal.parse-1.0.24.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:122) [canal.parse-1.0.24.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209) [canal.parse-1.0.24.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
2017-11-21 11:40:46.230 [destination = example31 , address = /localhost:30701 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - dump address localhost/localhost:30701 has an error, retrying. caused by
java.io.IOException: Unexpected End Stream
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:156) ~[canal.parse-1.0.24.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:70) ~[canal.parse-1.0.24.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:122) ~[canal.parse-1.0.24.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209) ~[canal.parse-1.0.24.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
2017-11-21 11:40:46.230 [destination = example31 , address = /localhost:30701 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example31[java.io.IOException: Unexpected End Stream
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:156)
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:70)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:122)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209)
	at java.lang.Thread.run(Thread.java:745)
]

**Comment by agapple** [comment]
是否是slaveId出现重复，被mysql端kill了链接，可以尝试一下最新的版本，增加了随机slaveId的能力

**Comment by zwxbest** [comment]
可能是两个不同的instance配置了同一个数据源。用一个instance就ok
