### ISSUE TITLE
请问有什么方法提高adapter同步进es7的消费能力？

### ISSUE THREAD

**Issue by yuyoyth** [alibaba/canal#4211]
## Question

需求：基表A表，有约800w数据、150个字段，其中有15个字段全都左关联B表，B表有300w数据、15个字段，现在要导入到es7中，使用需求上需要把A表与B表拼一个大文档。

遇到的问题：全量导入已经用logstash完成，但增量同步用adapter出现了性能问题，A表左关联了15个B表，通过了adapter的配置校验，但一条B表的更新消息，adapter就需要4-5秒完成同步，经过删减sql测试，当同时监听3个B表的关联，adapter处理性能就会显著下降（服务器cpu共48核，adapter表现处理低效的情况下，1核都没占满，内存也是大量空余），而B表是常更新表，高峰期通常每秒20-30的更新，所以常规配置相当于没法使用了。

对遇到问题尝试解决：经过粗略源码查看，发现outAdapter实例数量和groupId、key有关系，所以我把大sql拆分为主表A的基础字段、15个只监听关联字段与B表字段的sql，然后在同一个instance下添加了16个groupId、key，如果单开出其中一个group，消费能力完全足够，但当开出全部group就出现了ack对不齐的问题，所以我猜测是deployer的自带mq的topic默认只支持单消费，一个消息只有一个实例能够接收，所以此思路不行。

进一步解决：既然是mq的特性问题，考虑在中间层加入其它mq，就引入了kafka，因为kafka能够不同消费组同时消费一个topic，并且都是完整消息序列，经过简单代码测试了多group消费同一topic，确认了kafka确实有我需要的特性。但接下来我又头大了，adapter配置中，使用kafka作为数据源，当同一instance下具有两个以上的groupId时，就一直报以下两个异常：
```
javax.management.InstanceAlreadyExistsException: kafka.consumer:type=app-info,id=b30207
java.util.ConcurrentModificationException: KafkaConsumer is not safe for multi-threaded access
```
因为我单独用kafka-clients写了简单代码尝试了多个消费组同时连接、获取、同步同一topic，所以我确信这不是kafka的问题，所以这可能是bug或者设计上有特殊的考量，目前尝试adapter源码调试，还没理清这两异常出现的原因。

当前进度：没有任何进展，如果换思路就是，在deployer处设置大量的instance产生足够多的topic来供使用，不确定的是deployer压力有多大，感觉上是adapter存在问题，不想通过增大deployer的压力来弯道解决。

求助：
是否有遇到同样异常的朋友？是否解决了并能否提供下解决异常的方法？
关于这种需求有处理好的朋友吗？数据量感觉也不算是很多，场景中应该很常见才对

**Comment by yuyoyth** [comment]
贴出两个异常完整的信息：
```
2022-06-03 23:59:38.638 [Thread-35] WARN  org.apache.kafka.common.utils.AppInfoParser - Error registering AppInfo mbean
javax.management.InstanceAlreadyExistsException: kafka.consumer:type=app-info,id=b30207
	at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:437) ~[na:1.8.0_172]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1898) ~[na:1.8.0_172]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:966) ~[na:1.8.0_172]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:900) ~[na:1.8.0_172]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324) ~[na:1.8.0_172]
	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522) ~[na:1.8.0_172]
	at org.apache.kafka.common.utils.AppInfoParser.registerAppInfo(AppInfoParser.java:62) ~[connector.kafka-1.1.6-jar-with-dependencies.jar:na]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:785) [connector.kafka-1.1.6-jar-with-dependencies.jar:na]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:644) [connector.kafka-1.1.6-jar-with-dependencies.jar:na]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:624) [connector.kafka-1.1.6-jar-with-dependencies.jar:na]
	at com.alibaba.otter.canal.connector.kafka.consumer.CanalKafkaConsumer.connect(CanalKafkaConsumer.java:71) [connector.kafka-1.1.6-jar-with-dependencies.jar:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.process(AdapterProcessor.java:185) [classes/:na]
```
```
2022-06-03 23:59:38.641 [Thread-33] ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - process error!
java.util.ConcurrentModificationException: KafkaConsumer is not safe for multi-threaded access
	at org.apache.kafka.clients.consumer.KafkaConsumer.acquire(KafkaConsumer.java:1824) ~[na:na]
	at org.apache.kafka.clients.consumer.KafkaConsumer.acquireAndEnsureOpen(KafkaConsumer.java:1808) ~[na:na]
	at org.apache.kafka.clients.consumer.KafkaConsumer.commitSync(KafkaConsumer.java:1216) ~[na:na]
	at com.alibaba.otter.canal.connector.kafka.consumer.CanalKafkaConsumer.ack(CanalKafkaConsumer.java:129) ~[classes/:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.process(AdapterProcessor.java:230) ~[classes/:na]
```
```
java.util.ConcurrentModificationException: KafkaConsumer is not safe for multi-threaded access
	at org.apache.kafka.clients.consumer.KafkaConsumer.acquire(KafkaConsumer.java:1824)
	at org.apache.kafka.clients.consumer.KafkaConsumer.acquireAndEnsureOpen(KafkaConsumer.java:1808)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1103)
	at com.alibaba.otter.canal.connector.kafka.consumer.CanalKafkaConsumer.getMessage(CanalKafkaConsumer.java:96)
	at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.process(AdapterProcessor.java:208)
```
虽然两处多线程异常的报错点不同，但都是canalMsgConsumer.ack()触发，canalMsgConsumer下的消费者对象不知为何会变成其他canalMsgConsumer的消费者对象，导致ack时，消费者对象的前后处理线程对不齐，就报错了

**Comment by yuyoyth** [comment]
已定位到问题，原因在connector.core中，ExtensionLoader的getExtension方法和createExtension方法做了mode+instance名称的消费者对象重用，于是按我的这种相同instance的配置就出现了消费者对象的跨线程问题
我下了代码进行了处理，当遇到name为kafka时，直接新建对象
```
public T getExtension(String name, String key, String spiDir, String standbyDir) {
    ......
    if ("kafka".equals(name)) {
        return createExtension(name, key, spiDir, standbyDir);
    } else {
        // 默认逻辑
        ......
    }
}
```
```
private T createExtension(String name, String key, String spiDir, String standbyDir) {
    ......
    try {
        T instance;
        if ("kafka".equals(name)) {
            instance = (T) clazz.newInstance();
        } else {
            // 默认逻辑
            instance = (T) EXTENSION_KEY_INSTANCE.get(name + "-" + key);
            ......
        }
        return instance;
    } 
    ...
}
```
两个方法在ExtensionLoader有其他同名方法，改法都差不多，修改后运行，成功建立多个group消费组消费同一kafka topic的问题，各自消费各自的不冲突，测试了一下，实时性比前面说的一个消费组监控大SQL要好得多

**Comment by yuyoyth** [comment]
[connector.core-1.1.7-SNAPSHOT.zip](https://github.com/alibaba/canal/files/8837428/connector.core-1.1.7-SNAPSHOT.zip)

这个是我对处理后打的包，只针对kafka进行了特殊处理，没经过严格测试，不保证不会引入其他问题
使用方法：把adapter的lib中的connector.core删除后把这个包加进去

**Comment by yuyoyth** [comment]
@agapple

**Comment by yuyoyth** [comment]
@agapple 能否做一个官方优化？

**Comment by yuyoyth** [comment]
> 老哥 好强 deployer的自带mq我有点没看懂 我目前测试用canal同步个10w条数据到es也发现好慢

deployer配置的destinations对应的也就是adapter中的instance，deployer自己构建得有一个mq队列，每个topic以destinations命名，但这个自带mq的限制很大，每个topic只能由一个消费者组消费，多个消费者组消费就会出现ack不对齐的问题（比如1、2、3、4条消息，2个消费者组并不能每个都获得1、2、3、4条消息，而是会互相抢消息），如果要扩展成多个消费者组并且接收一样的消息去处理不同的更新任务，自带mq就不行，但kafka mq就有这个特性，所以就不使用deployer->kafka->adapter的架构，而不是deployer->adapter

另外如果学我的做法，adapter要把retry开启，因为adapter多个实例接收一样的消息后，如果配置上还同时更新一个索引，会出现冲突，其中一个会失败，retry设置后可以避免这个原因的同步丢失

慢的原因主要是，同步es的话，adapter消费一个instance，只能开一个groupId（实例数量是由instance与groupId的联合名称决定的），然后就看解析的映射配置文件，线性进行更新，遇到关联会使用source连接访问源库查关联数据，所以关联一复杂就很慢了，因为几乎没有并发

**Comment by meimansheng** [comment]
@J-Orange 后面又解决吗
