### ISSUE TITLE
启动canal报错误编码为1146的错误

### ISSUE THREAD

**Issue by clip-tail** [alibaba/canal#4219]
## canal版本
1.1.6

## 报错日志

```
2022-06-11 14:13:07.387 [destination = example , address = /127.0.0.1:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address /127.0.0.1:3306 has an error, retrying. caused by 
com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: ErrorPacket [errorNumber=1146, fieldCount=-1, message=Table 'xzw.BASE TABLE' doesn't exist, sqlState=42S02, sqlStateMarker=#]
 with command: show create table `xzw`.`t_1`;show create table `xzw`.`BASE TABLE`;
Caused by: java.io.IOException: ErrorPacket [errorNumber=1146, fieldCount=-1, message=Table 'xzw.BASE TABLE' doesn't exist, sqlState=42S02, sqlStateMarker=#]
 with command: show create table `xzw`.`t_1`;show create table `xzw`.`BASE TABLE`;
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlQueryExecutor.queryMulti(MysqlQueryExecutor.java:109) ~[canal.parse.driver-1.1.6.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.queryMulti(MysqlConnection.java:111) ~[canal.parse-1.1.6.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.dumpTableMeta(DatabaseTableMeta.java:233) ~[canal.parse-1.1.6.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:174) ~[canal.parse-1.1.6.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:142) ~[canal.parse-1.1.6.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:197) ~[canal.parse-1.1.6.jar:na]
        at java.lang.Thread.run(Thread.java:750) [na:1.8.0_331]
```

## canal的instance.properties配置

```
#################################################
## mysql serverId , v1.0.26+ will autoGen
# canal.instance.mysql.slaveId=0

# enable gtid use true/false
canal.instance.gtidon=false

# position info
canal.instance.master.address=127.0.0.1:3306
canal.instance.master.journal.name=
canal.instance.master.position=
canal.instance.master.timestamp=
canal.instance.master.gtid=

# rds oss binlog
canal.instance.rds.accesskey=
canal.instance.rds.secretkey=
canal.instance.rds.instanceId=

# table meta tsdb info
canal.instance.tsdb.enable=true
#canal.instance.tsdb.url=jdbc:mysql://127.0.0.1:3306/canal_tsdb
#canal.instance.tsdb.dbUsername=canal
#canal.instance.tsdb.dbPassword=canal

#canal.instance.standby.address =
#canal.instance.standby.journal.name =
#canal.instance.standby.position =
#canal.instance.standby.timestamp =
#canal.instance.standby.gtid=

# username/password
canal.instance.dbUsername=canal
canal.instance.dbPassword=canal
canal.instance.connectionCharset = UTF-8
# enable druid Decrypt database password
canal.instance.enableDruid=false
#canal.instance.pwdPublicKey=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALK4BUxdDltRRE5/zXpVEVPUgunvscYFtEip3pmLlhrWpacX7y7GCMo2/JM6LeHmiiNdH1FWgGCpUfircSwlWKUCAwEAAQ==

# table regex
canal.instance.filter.regex=xzw\\..*
# table black regex
canal.instance.filter.black.regex=mysql\\.slave_.*
# table field filter(format: schema1.tableName1:field1/field2,schema2.tableName2:field1/field2)
#canal.instance.filter.field=test1.t_product:id/subject/keywords,test2.t_company:id/name/contact/ch
# table field black filter(format: schema1.tableName1:field1/field2,schema2.tableName2:field1/field2)
#canal.instance.filter.black.field=test1.t_product:subject/product_image,test2.t_company:id/name/contact/ch

# mq config
canal.mq.topic=example
# dynamic topic route by schema or table regex
#canal.mq.dynamicTopic=mytest1.user,topic2:mytest2\\..*,.*\\..*
canal.mq.partition=0
# hash partition config
#canal.mq.enableDynamicQueuePartition=false
#canal.mq.partitionsNum=3
#canal.mq.dynamicTopicPartitionNum=test.*:4,mycanal:6
#canal.mq.partitionHash=test.table:id^name,.*\\..*
#################################################
```

## mysql5.7的配置

```
# For advice on how to change settings please see
# http://dev.mysql.com/doc/refman/5.7/en/server-configuration-defaults.html

[mysqld]
#
# Remove leading # and set to the amount of RAM for the most important data
# cache in MySQL. Start at 70% of total RAM for dedicated server, else 10%.
# innodb_buffer_pool_size = 128M
#
# Remove leading # to turn on a very important data integrity option: logging
# changes to the binary log between backups.
# log_bin
#
# Remove leading # to set options mainly useful for reporting servers.
# The server defaults are faster for transactions and fast SELECTs.
# Adjust sizes as needed, experiment to find the optimal values.
# join_buffer_size = 128M
# sort_buffer_size = 2M
# read_rnd_buffer_size = 2M
datadir=/var/lib/mysql
socket=/var/lib/mysql/mysql.sock

# Disabling symbolic-links is recommended to prevent assorted security risks
symbolic-links=0

log-error=/var/log/mysqld.log
pid-file=/var/run/mysqld/mysqld.pid
validate_password_policy=0
validate_password_length=5

log-bin=mysql-bin # 开启 binlog
binlog-format=ROW # 选择 ROW 模式
server_id=1 # 配置 MySQL replaction 需要定义，不要和 canal 的 slaveId 重复
```

## 已经创建过canal用户并赋予select，replication slave，replication client权限可是一起动就报找不到base table这张表，换过几个数据库和canal版本都是这样

**Comment by jimmy384** [comment]
我也遇到了，我是 docker 启动的，你是吗？这是我的情况: https://github.com/alibaba/canal/issues/4220

**Comment by clip-tail** [comment]
> 
我不是docker启的，我只直接把canal.deployer-1.1.6.tar.gz那个包部署在linux系统上的

**Comment by clip-tail** [comment]
> 我也遇到了，我是 docker 启动的，你是吗？这是我的情况: #4220

我不是docker启动的，我是直接部署canal.deployer-1.1.6.tar.gz包启动的，windows和linux都试了，都是一样的问题

**Comment by jimmy384** [comment]
release页面的包上传时间是昨天, 但1.1.6是18天前发布的，感觉有点奇怪

**Comment by jimmy384** [comment]
用源码编译出1.1.6版本启动没问题，用1.1.6的docker镜像和 github release 页面下的包都有问题，应该是发布流程出问题了吧

**Comment by clip-tail** [comment]
> 用源码编译出1.1.6版本启动没问题，用1.1.6的docker镜像和 github release 页面下的包都有问题，应该是发布流程出问题了吧

可能是的，试了一下1.1.4没问题

**Comment by jimmy384** [comment]
> 解决了吗？ 我也遇到这个问题了

今天好像重新上传包了，重新下载试试，我没试过

**Comment by azydbly** [comment]
> > 解决了吗？ 我也遇到这个问题了
> 
> 今天好像重新上传包了，重新下载试试，我没试过

重新下载了，还是不可以，请问你咋解决的

**Comment by clip-tail** [comment]
> 解决了吗？ 我也遇到这个问题了

我降版本了

**Comment by carl-chang** [comment]
有解决的吗？我也是报这个，一直提示表 BASE TABLE' doesn't exist

**Comment by clip-tail** [comment]
> 有解决的吗？我也是报这个，一直提示表 BASE TABLE' doesn't exist

暂时没有，我是先降版本了

**Comment by wujiayuan1996** [comment]
我也是，各位有解决么，我从来没有建过什么BASE TABLE这张表
Caused by: java.io.IOException: ErrorPacket [errorNumber=1146, fieldCount=-1, message=Table 'mysql.base table' doesn't exist, sqlState=42S02, sqlStateMarker=#]


com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: ErrorPacket [errorNumber=1146, fieldCount=-1, message=Table 'seata.BASE TABLE' doesn't exist, sqlState=42S02, sqlStateMarker=#]

**Comment by lb405828825** [comment]
![image](https://user-images.githubusercontent.com/16475830/176878293-d4401701-c431-4434-a2f8-accdcec1cc06.png)
我也遇到了，一直过不去。

**Comment by lixworld** [comment]
我做了以下配置就可以了：

```
canal.instance.filter.black.regex=.*\\.BASE.*
```

**Comment by lb405828825** [comment]
这是来自QQ邮箱的假期自动回复邮件。
我已收到你的邮件，阅读 后回复你

**Comment by agapple** [comment]
1.1.6-hotfix版本已修复

**Comment by lb405828825** [comment]
这是来自QQ邮箱的假期自动回复邮件。
我已收到你的邮件，阅读 后回复你
