### ISSUE TITLE
1.1.6版本中升级了fastjson2之后，CanalRabbitMQConsumer中使用JSON.parseObject转换json消息成java类会报错

### ISSUE THREAD

**Issue by jimmy384** [alibaba/canal#4221]
```java
// json中带null的会报错, 比如这个ALTER语句产生的消息
String messageData = "{\"data\":null,\"database\":\"canal-test-to1\",\"es\":1654937242000,\"id\":153,\"isDdl\":true,\"mysqlType\":null,\"old\":null,\"pkNames\":null,\"sql\":\"ALTER TABLE `canal-test-to1`.`test_table1` ADD COLUMN `birthday` date NULL\",\"sqlType\":null,\"table\":\"test_table1\",\"ts\":1654937242664,\"type\":\"ALTER\"}";
CommonMessage commonMessage = JSON.parseObject(messageData, CommonMessage.class);
System.out.println(commonMessage);
```

异常栈信息
```
Exception in thread "main" com.alibaba.fastjson2.JSONException: json format error : n
	at com.alibaba.fastjson2.reader.FieldReaderListStrMethod.readFieldValue(FieldReaderListStrMethod.java:83)
	at com.alibaba.fastjson2.reader.ObjectReaderBean.readObject(ObjectReaderBean.java:174)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:258)
```

```java
// 把null去掉就没问题
String messageData = "{\"database\":\"canal-test-to1\",\"es\":1654937242000,\"id\":153,\"isDdl\":true,\"sql\":\"ALTER TABLE `canal-test-to1`.`test_table1` ADD COLUMN `birthday` date NULL\",\"table\":\"test_table1\",\"ts\":1654937242664,\"type\":\"ALTER\"}";
CommonMessage commonMessage = JSON.parseObject(messageData, CommonMessage.class);
System.out.println(commonMessage);
```

换成旧版本的fastjson上面的代码都没问题

**Comment by agapple** [comment]
fastjson2 已升级到2.0.7，已修复
