### ISSUE TITLE
canal.deployer-1.1.6 版本启动之后报错

### ISSUE THREAD

**Issue by azydbly** [alibaba/canal#4223]
canal.deployer-1.1.6 版本启动之后， logs/example/example.log   一直在刷这个错误

2022-06-12 14:08:12.961 [main] INFO  c.a.otter.canal.instance.spring.CanalInstanceWithSpring - start CannalInstance for 1-example 
2022-06-12 14:08:12.973 [main] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table filter : ^.*\..*$
2022-06-12 14:08:12.973 [main] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table black filter : ^mysql\.slave_.*$
2022-06-12 14:08:12.979 [main] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - start successful....
2022-06-12 14:08:13.061 [destination = example , address = /127.0.0.1:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> begin to find start position, it will be long time for reset or first position
2022-06-12 14:08:13.062 [destination = example , address = /127.0.0.1:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - prepare to find start position just show master status
2022-06-12 14:08:13.476 [destination = example , address = /127.0.0.1:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address /127.0.0.1:3306 has an error, retrying. caused by 
com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: ErrorPacket [errorNumber=1146, fieldCount=-1, message=Table 'es_test.base table' doesn't exist, sqlState=42S02, sqlStateMarker=#]
 with command: show create table `es_test`.`hotel`;show create table `es_test`.`BASE TABLE`;
Caused by: java.io.IOException: ErrorPacket [errorNumber=1146, fieldCount=-1, message=Table 'es_test.base table' doesn't exist, sqlState=42S02, sqlStateMarker=#]
 with command: show create table `es_test`.`hotel`;show create table `es_test`.`BASE TABLE`;
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlQueryExecutor.queryMulti(MysqlQueryExecutor.java:109) ~[canal.parse.driver-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.queryMulti(MysqlConnection.java:111) ~[canal.parse-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.dumpTableMeta(DatabaseTableMeta.java:233) ~[canal.parse-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:174) ~[canal.parse-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:142) ~[canal.parse-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:197) ~[canal.parse-1.1.6.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]
2022-06-12 14:08:13.479 [destination = example , address = /127.0.0.1:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: ErrorPacket [errorNumber=1146, fieldCount=-1, message=Table 'es_test.base table' doesn't exist, sqlState=42S02, sqlStateMarker=#]
 with command: show create table `es_test`.`hotel`;show create table `es_test`.`BASE TABLE`;
Caused by: java.io.IOException: ErrorPacket [errorNumber=1146, fieldCount=-1, message=Table 'es_test.base table' doesn't exist, sqlState=42S02, sqlStateMarker=#]
 with command: show create table `es_test`.`hotel`;show create table `es_test`.`BASE TABLE`;
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlQueryExecutor.queryMulti(MysqlQueryExecutor.java:109)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.queryMulti(MysqlConnection.java:111)
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.dumpTableMeta(DatabaseTableMeta.java:233)
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:174)
	at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:142)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:197)
	at java.lang.Thread.run(Thread.java:748)
]

**Comment by agapple** [comment]
show databases 以及 show full tables from `" + schema + "` where Table_type = 'BASE TABLE'，看一下返回结果

**Comment by azydbly** [comment]
语句都可以正常执行
information_schema
es_test
mysql
performance_schema
sys


hotel	BASE TABLE

**Comment by azydbly** [comment]
> show databases 以及 show full tables from `" + schema + "` where Table_type = 'BASE TABLE'，看一下返回结果

语句都可以正常执行
information_schema
es_test
mysql
performance_schema
sys

hotel BASE TABLE

**Comment by zlhlevi** [comment]
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/70023619/173580776-fffdddaa-7b71-4390-a7ec-af303853e63f.png">
启动一直报这个错

**Comment by azydbly** [comment]
> <img alt="image" width="1433" src="https://user-images.githubusercontent.com/70023619/173580776-fffdddaa-7b71-4390-a7ec-af303853e63f.png">
> 
> 启动一直报这个错

你有这个 canal_manager 数据库吗？  没有的话把 bootstrap.yml 配置文件中的代码注掉，就没有这个错误了

**Comment by zlhlevi** [comment]
> 

<img width="935" alt="image" src="https://user-images.githubusercontent.com/70023619/173615124-ee2b9400-c5e1-46ce-a1be-d421b97d8125.png">
上面的报错日志中有多条show create table `canal_manager`.`BASE TABLE`;语句，由上面的源码生成，应该是这个原因导致的

**Comment by mobile664042** [comment]
我也遇到这个错误，发现是源码包与字节码包不一至啊。

字节码包的代码有bug
https://github.com/alibaba/canal/issues/4245

**Comment by agapple** [comment]
1.1.6-hotfix版本已修复
