### ISSUE TITLE
使用阿里云RocketMQ 提示找不到TBW102 主题

### ISSUE THREAD

**Issue by bain2018** [alibaba/canal#4234]
## Question

2022-06-16 10:47:00.824 [MQClientFactoryScheduledThread] WARN  RocketmqClient - get Topic [TBW102] RouteInfoFromNameServer is not exist value
2022-06-16 10:47:00.827 [MQClientFactoryScheduledThread] WARN  RocketmqClient - updateTopicRouteInfoFromNameServer Exception
org.apache.rocketmq.client.exception.MQClientException: CODE: 17  DESC: No topic route info in name server for the topic: TBW102
See http://rocketmq.apache.org/docs/faq/ for further details.
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.getTopicRouteInfoFromNameServer(MQClientAPIImpl.java:1385) ~[connector.rocketmq-1.1.6-jar-with-dependencies.jar:na]
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.getTopicRouteInfoFromNameServer(MQClientAPIImpl.java:1355) ~[connector.rocketmq-1.1.6-jar-with-dependencies.jar:na]
	at org.apache.rocketmq.client.impl.factory.MQClientInstance.updateTopicRouteInfoFromNameServer(MQClientInstance.java:622) [connector.rocketmq-1.1.6-jar-with-dependencies.jar:na]
	at org.apache.rocketmq.client.impl.factory.MQClientInstance.updateTopicRouteInfoFromNameServer(MQClientInstance.java:509) [connector.rocketmq-1.1.6-jar-with-dependencies.jar:na]
	at org.apache.rocketmq.client.impl.factory.MQClientInstance.updateTopicRouteInfoFromNameServer(MQClientInstance.java:358) [connector.rocketmq-1.1.6-jar-with-dependencies.jar:na]
	at org.apache.rocketmq.client.impl.factory.MQClientInstance$3.run(MQClientInstance.java:275) [connector.rocketmq-1.1.6-jar-with-dependencies.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_202]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_202]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_202]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_202]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_202]

**Comment by 985177520** [comment]
大佬你怎么配置链接阿里云rocketmq的我这边 rocketmq都连不上

**Comment by bain2018** [comment]
@agapple 这个会影响数据丢失吗

**Comment by yucw01** [comment]
same to me, who resolve it ??

**Comment by zjt3939** [comment]
did you had resolve it?

**Comment by otjoy** [comment]
please  fix this issue, thanks!

**Comment by axiaoqing** [comment]
+1 解决了麻烦告知一声。。

**Comment by ChenXing-tech** [comment]
I meet the same situation, aliyun ons can't receive the message.

**Comment by NeighborOldKing** [comment]
我也遇到了该问题

**Comment by NeighborOldKing** [comment]
@agapple 大佬这个是因为rocketmq版本的问题么，我使用你们发布的镜像遇到这个问题了，但本地启动master分支的代码就没有这个问题

**Comment by XJhrack** [comment]
还没有解决吗..

**Comment by skboy** [comment]
这问题还没解决吗

**Comment by GordenChoy** [comment]
遇到了一样的问题 请问怎么解决？

**Comment by axiaoqing** [comment]
不造啊，已经提桶跑路，这东西坑太多





------------------ 原始邮件 ------------------
发件人: GordenChoy ***@***.***&gt;
发送时间: 2023年11月2日 17:11
收件人: alibaba/canal ***@***.***&gt;
抄送: axiaoqing ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [alibaba/canal] 使用阿里云RocketMQ 提示找不到TBW102 主题 (Issue #4234)





 
遇到了一样的问题 请问怎么解决？

**Comment by huazaihuola** [comment]
是不是创建一个topic 就能解决这个问题

**Comment by xiaozhou822** [comment]
有谁解决了这个错了吗，麻烦告诉下，谢谢。我使用1.1.7连接阿里云rocketmq 一直会报这个错
org.apache.rocketmq.client.exception.MQClientException: CODE: 17  DESC: No topic route info in name server for the topic: TBW102

**Comment by nakeiven** [comment]
也遇到这个问题了

<img width="1041" height="256" alt="Image" src="https://github.com/user-attachments/assets/1bcc6bcf-dfa0-4bb7-9da0-49530cbe87c1" />

**Comment by nakeiven** [comment]
[参考](https://help.aliyun.com/zh/apsaramq-for-rocketmq/cloud-message-queue-rocketmq-5-x-series/use-cases/change-data-in-a-database-by-using-canal-and-apsaramq-for-rocketmq-1?spm=a2c4g.11186623.help-menu-29530.d_3_2.18521f44ri0CUw&scm=20140722.H_476221._.OR_help-T_cn~zh-V_1)

<img width="549" height="300" alt="Image" src="https://github.com/user-attachments/assets/17b71ff3-a888-4cc0-99a0-cd922975aeca" />

`canal.mq.producerGroup`  `canal.mq.namespace` 不要配置，即可正常启动
