### ISSUE TITLE
base table的问题

### ISSUE THREAD

**Issue by airywangym** [alibaba/canal#4244]
mysql 5.7 performance_schema没有base table这张表 启动报错  performance_schema又不允许建表

com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: ErrorPacket [errorNumber=1146, fieldCount=-1, message=Table 'performance_schema.base table' doesn't exist, sqlState=42S02, sqlStateMarker=#]
 with command: show create table `performance_schema`.`accounts`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`cond_instances`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_stages_current`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_stages_history`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_stages_history_long`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_stages_summary_by_account_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_stages_summary_by_host_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_stages_summary_by_thread_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_stages_summary_by_user_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_stages_summary_global_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_statements_current`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_statements_history`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_statements_history_long`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_statements_summary_by_account_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_statements_summary_by_digest`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_statements_summary_by_host_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_statements_summary_by_program`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_statements_summary_by_thread_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_statements_summary_by_user_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_statements_summary_global_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_transactions_current`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_transactions_history`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_transactions_history_long`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_transactions_summary_by_account_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_transactions_summary_by_host_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_transactions_summary_by_thread_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_transactions_summary_by_user_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_transactions_summary_global_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_waits_current`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_waits_history`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_waits_history_long`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_waits_summary_by_account_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_waits_summary_by_host_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_waits_summary_by_instance`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_waits_summary_by_thread_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_waits_summary_by_user_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_waits_summary_global_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`file_instances`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`file_summary_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`file_summary_by_instance`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`global_status`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`global_variables`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`host_cache`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`hosts`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`memory_summary_by_account_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`memory_summary_by_host_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`memory_summary_by_thread_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`memory_summary_by_user_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`memory_summary_global_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`metadata_locks`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`mutex_instances`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`objects_summary_global_by_type`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`performance_timers`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`prepared_statements_instances`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`replication_applier_configuration`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`replication_applier_status`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`replication_applier_status_by_coordinator`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`replication_applier_status_by_worker`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`replication_connection_configuration`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`replication_connection_status`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`replication_group_member_stats`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`replication_group_members`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`rwlock_instances`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`session_account_connect_attrs`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`session_connect_attrs`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`session_status`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`session_variables`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`setup_actors`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`setup_consumers`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`setup_instruments`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`setup_objects`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`setup_timers`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`socket_instances`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`socket_summary_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`socket_summary_by_instance`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`status_by_account`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`status_by_host`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`status_by_thread`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`status_by_user`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`table_handles`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`table_io_waits_summary_by_index_usage`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`table_io_waits_summary_by_table`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`table_lock_waits_summary_by_table`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`threads`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`user_variables_by_thread`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`users`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`variables_by_thread`;show create table `performance_schema`.`BASE TABLE`;
Caused by: java.io.IOException: ErrorPacket [errorNumber=1146, fieldCount=-1, message=Table 'performance_schema.base table' doesn't exist, sqlState=42S02, sqlStateMarker=#]
 with command: show create table `performance_schema`.`accounts`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`cond_instances`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_stages_current`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_stages_history`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_stages_history_long`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_stages_summary_by_account_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_stages_summary_by_host_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_stages_summary_by_thread_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_stages_summary_by_user_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_stages_summary_global_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_statements_current`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_statements_history`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_statements_history_long`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_statements_summary_by_account_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_statements_summary_by_digest`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_statements_summary_by_host_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_statements_summary_by_program`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_statements_summary_by_thread_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_statements_summary_by_user_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_statements_summary_global_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_transactions_current`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_transactions_history`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_transactions_history_long`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_transactions_summary_by_account_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_transactions_summary_by_host_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_transactions_summary_by_thread_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_transactions_summary_by_user_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_transactions_summary_global_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_waits_current`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_waits_history`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_waits_history_long`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_waits_summary_by_account_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_waits_summary_by_host_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_waits_summary_by_instance`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_waits_summary_by_thread_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_waits_summary_by_user_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`events_waits_summary_global_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`file_instances`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`file_summary_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`file_summary_by_instance`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`global_status`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`global_variables`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`host_cache`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`hosts`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`memory_summary_by_account_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`memory_summary_by_host_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`memory_summary_by_thread_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`memory_summary_by_user_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`memory_summary_global_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`metadata_locks`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`mutex_instances`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`objects_summary_global_by_type`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`performance_timers`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`prepared_statements_instances`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`replication_applier_configuration`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`replication_applier_status`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`replication_applier_status_by_coordinator`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`replication_applier_status_by_worker`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`replication_connection_configuration`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`replication_connection_status`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`replication_group_member_stats`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`replication_group_members`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`rwlock_instances`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`session_account_connect_attrs`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`session_connect_attrs`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`session_status`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`session_variables`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`setup_actors`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`setup_consumers`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`setup_instruments`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`setup_objects`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`setup_timers`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`socket_instances`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`socket_summary_by_event_name`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`socket_summary_by_instance`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`status_by_account`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`status_by_host`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`status_by_thread`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`status_by_user`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`table_handles`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`table_io_waits_summary_by_index_usage`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`table_io_waits_summary_by_table`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`table_lock_waits_summary_by_table`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`threads`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`user_variables_by_thread`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`users`;show create table `performance_schema`.`BASE TABLE`;show create table `performance_schema`.`variables_by_thread`;show create table `performance_schema`.`BASE TABLE`;
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlQueryExecutor.queryMulti(MysqlQueryExecutor.java:109) ~[canal.parse.driver-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.queryMulti(MysqlConnection.java:111) ~[canal.parse-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.dumpTableMeta(DatabaseTableMeta.java:233) ~[canal.parse-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:174) ~[canal.parse-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:142) ~[canal.parse-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:197) ~[canal.parse-1.1.6.jar:na]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_191]

**Comment by airywangym** [comment]
# table regex
canal.instance.filter.regex=.*\\..*
# table black regex
canal.instance.filter.black.regex=mysql\\.slave_.*,.*\\.base.*

黑名单处理
