### ISSUE TITLE
deployer instance关于java.nio.channels.ClosedChannelException的报错

### ISSUE THREAD

**Issue by xuhb-bill** [alibaba/canal#4246]
deployer，adapter 版本1.1.6，场景MySQL -> MySQL，使用adapter 进行全量同步数据之后，deployer 运行过程中会出现以下报错

2022-06-23 00:01:31.275 [Thread-6] ERROR c.a.otter.canal.server.netty.handler.SessionHandler - something goes wrong with channel:[id: 0x14a4ec8e, /127.0.0.1:4
6882 :> /127.0.0.1:11111], exception=java.nio.channels.ClosedChannelException
        at org.jboss.netty.channel.socket.nio.NioWorker.cleanUpWriteBuffer(NioWorker.java:649)
        at org.jboss.netty.channel.socket.nio.NioWorker.writeFromUserCode(NioWorker.java:370)
        at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleAcceptedSocket(NioServerSocketPipelineSink.java:137)
        at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:76)
        at org.jboss.netty.channel.Channels.write(Channels.java:611)
        at org.jboss.netty.channel.Channels.write(Channels.java:578)
        at com.alibaba.otter.canal.server.netty.NettyUtils.write(NettyUtils.java:49)
        at com.alibaba.otter.canal.server.netty.handler.SessionHandler.messageReceived(SessionHandler.java:201)
        at org.jboss.netty.handler.timeout.IdleStateAwareChannelHandler.handleUpstream(IdleStateAwareChannelHandler.java:48)
        at org.jboss.netty.handler.timeout.IdleStateHandler.messageReceived(IdleStateHandler.java:276)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:302)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.unfoldAndfireMessageReceived(ReplayingDecoder.java:526)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:507)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.cleanup(ReplayingDecoder.java:542)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.channelDisconnected(ReplayingDecoder.java:450)
        at org.jboss.netty.channel.Channels.fireChannelDisconnected(Channels.java:360)
        at org.jboss.netty.channel.socket.nio.NioWorker.close(NioWorker.java:599)
        at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleAcceptedSocket(NioServerSocketPipelineSink.java:119)
        at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:76)
        at org.jboss.netty.channel.Channels.close(Channels.java:720)
        at org.jboss.netty.channel.AbstractChannel.close(AbstractChannel.java:208)
        at org.jboss.netty.channel.group.DefaultChannelGroup.close(DefaultChannelGroup.java:189)
        at com.alibaba.otter.canal.server.netty.CanalServerWithNetty.stop(CanalServerWithNetty.java:109)
        at com.alibaba.otter.canal.deployer.CanalController.stop(CanalController.java:524)
        at com.alibaba.otter.canal.deployer.CanalStarter.lambda$start$0(CanalStarter.java:94)
        at java.lang.Thread.run(Thread.java:750)

**Comment by agapple** [comment]
客户端主动断链接
