### ISSUE TITLE
阿里云RDS数据库切换时会报错（Connection timed out）

### ISSUE THREAD

**Issue by laomeng2088** [alibaba/canal#426]
同步数据源时， 如果使用的是MHA的数据库，在高可用切换时， 数据库主库发生了变化, 这时 canal同步日志 发生了改变， 会报错 . 报错如下：

Caused by: java.io.IOException: connect rm-2zed22tz2539.mysql.rds.aliyuncs.com/100.114.42.154:3306 failure:java.net.ConnectException: Connection timed out
        at sun.nio.ch.Net.connect0(Native Method)
        at sun.nio.ch.Net.connect(Net.java:454)
        at sun.nio.ch.Net.connect(Net.java:446)
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:70)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.connect(MysqlConnection.java:56)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.preDump(MysqlEventParser.java:86)
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:157)
        at java.lang.Thread.run(Thread.java:745)

        at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:74)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.connect(MysqlConnection.java:56)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.preDump(MysqlEventParser.java:86)
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:157)
        at java.lang.Thread.run(Thread.java:745)

**Comment by agapple** [comment]
连不上数据库 Connection timed out
