### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by herowws** [alibaba/canal#4261]
2022-06-27 11:34:14.303 [main] INFO  c.a.otter.canal.instance.spring.CanalInstanceWithSpring - start CannalInstance for 1-example 
2022-06-27 11:34:14.312 [main] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table filter : ^.*\..*$
2022-06-27 11:34:14.312 [main] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table black filter : ^mysql\.slave_.*$
2022-06-27 11:34:14.316 [main] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - start successful....
2022-06-27 11:34:14.376 [destination = example , address = /127.0.0.1:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> begin to find start position, it will be long time for reset or first position
2022-06-27 11:34:14.376 [destination = example , address = /127.0.0.1:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - prepare to find start position just show master status
2022-06-27 11:34:14.433 [destination = example , address = /127.0.0.1:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address /127.0.0.1:3306 has an error, retrying. caused by 
com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: ErrorPacket [errorNumber=1146, fieldCount=-1, message=Table 'business.base table' doesn't exist, sqlState=42S02, sqlStateMarker=#]
 with command: show create table `business`.`pms_coupon`;show create table `business`.`BASE TABLE`;show create table `business`.`pms_coupon_user`;show create table `business`.`BASE TABLE`;show create table `business`.`pms_guarantee`;show create table `business`.`BASE TABLE`;show create table `business`.`pms_product`;show create table `business`.`BASE TABLE`;show create table `business`.`pms_product_attribute`;show create table `business`.`BASE TABLE`;show create table `business`.`pms_product_coupon`;show create table `business`.`BASE TABLE`;show create table `business`.`pms_shop`;show create table `business`.`BASE TABLE`;show create table `business`.`ums_user`;show create table `business`.`BASE TABLE`;
Caused by: java.io.IOException: ErrorPacket [errorNumber=1146, fieldCount=-1, message=Table 'business.base table' doesn't exist, sqlState=42S02, sqlStateMarker=#]
 with command: show create table `business`.`pms_coupon`;show create table `business`.`BASE TABLE`;show create table `business`.`pms_coupon_user`;show create table `business`.`BASE TABLE`;show create table `business`.`pms_guarantee`;show create table `business`.`BASE TABLE`;show create table `business`.`pms_product`;show create table `business`.`BASE TABLE`;show create table `business`.`pms_product_attribute`;show create table `business`.`BASE TABLE`;show create table `business`.`pms_product_coupon`;show create table `business`.`BASE TABLE`;show create table `business`.`pms_shop`;show create table `business`.`BASE TABLE`;show create table `business`.`ums_user`;show create table `business`.`BASE TABLE`;
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlQueryExecutor.queryMulti(MysqlQueryExecutor.java:109) ~[canal.parse.driver-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.queryMulti(MysqlConnection.java:111) ~[canal.parse-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.dumpTableMeta(DatabaseTableMeta.java:233) ~[canal.parse-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:174) ~[canal.parse-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:142) ~[canal.parse-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:197) ~[canal.parse-1.1.6.jar:na]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_211]
2022-06-27 11:34:14.435 [destination = example , address = /127.0.0.1:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: ErrorPacket [errorNumber=1146, fieldCount=-1, message=Table 'business.base table' doesn't exist, sqlState=42S02, sqlStateMarker=#]
 with command: show create table `business`.`pms_coupon`;show create table `business`.`BASE TABLE`;show create table `business`.`pms_coupon_user`;show create table `business`.`BASE TABLE`;show create table `business`.`pms_guarantee`;show create table `business`.`BASE TABLE`;show create table `business`.`pms_product`;show create table `business`.`BASE TABLE`;show create table `business`.`pms_product_attribute`;show create table `business`.`BASE TABLE`;show create table `business`.`pms_product_coupon`;show create table `business`.`BASE TABLE`;show create table `business`.`pms_shop`;show create table `business`.`BASE TABLE`;show create table `business`.`ums_user`;show create table `business`.`BASE TABLE`;
Caused by: java.io.IOException: ErrorPacket [errorNumber=1146, fieldCount=-1, message=Table 'business.base table' doesn't exist, sqlState=42S02, sqlStateMarker=#]
 with command: show create table `business`.`pms_coupon`;show create table `business`.`BASE TABLE`;show create table `business`.`pms

说某些表不存在，但是这些表都是真实存在的
![image](https://user-images.githubusercontent.com/41428542/175856244-df2b6ad7-7d08-435c-8857-8640a99461ae.png)

**Comment by herowws** [comment]
配置如下
#################################################
## mysql serverId , v1.0.26+ will autoGen
canal.instance.mysql.slaveId=80

# enable gtid use true/false
canal.instance.gtidon=false

# position info
canal.instance.master.address=127.0.0.1:3306
canal.instance.master.journal.name=
canal.instance.master.position=
canal.instance.master.timestamp=
canal.instance.master.gtid=

# rds oss binlog
canal.instance.rds.accesskey=
canal.instance.rds.secretkey=
canal.instance.rds.instanceId=

# table meta tsdb info
canal.instance.tsdb.enable=true
#canal.instance.tsdb.url=jdbc:mysql://127.0.0.1:3306/canal_tsdb
#canal.instance.tsdb.dbUsername=canal
#canal.instance.tsdb.dbPassword=canal

#canal.instance.standby.address =
#canal.instance.standby.journal.name =
#canal.instance.standby.position =
#canal.instance.standby.timestamp =
#canal.instance.standby.gtid=

# username/password
canal.instance.dbUsername=canal
canal.instance.dbPassword=admin123@@!!..
canal.instance.connectionCharset = UTF-8
# enable druid Decrypt database password
canal.instance.enableDruid=false
#canal.instance.pwdPublicKey=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALK4BUxdDltRRE5/zXpVEVPUgunvscYFtEip3pmLlhrWpacX7y7GCMo2/JM6LeHmiiNdH1FWgGCpUfircSwlWKUCAwEAAQ==

# table regex
canal.instance.filter.regex=.*\\..*
# table black regex
canal.instance.filter.black.regex=mysql\\.slave_.*
# table field filter(format: schema1.tableName1:field1/field2,schema2.tableName2:field1/field2)
#canal.instance.filter.field=test1.t_product:id/subject/keywords,test2.t_company:id/name/contact/ch
# table field black filter(format: schema1.tableName1:field1/field2,schema2.tableName2:field1/field2)
#canal.instance.filter.black.field=test1.t_product:subject/product_image,test2.t_company:id/name/contact/ch

# mq config
canal.mq.topic=canal.rk
# dynamic topic route by schema or table regex
#canal.mq.dynamicTopic=mytest1.user,topic2:mytest2\\..*,.*\\..*
canal.mq.partition=0
# hash partition config
#canal.mq.enableDynamicQueuePartition=false
#canal.mq.partitionsNum=3
#canal.mq.dynamicTopicPartitionNum=test.*:4,mycanal:6
#canal.mq.partitionHash=test.table:id^name,.*\\..*
#################################################

**Comment by herowws** [comment]
![image](https://user-images.githubusercontent.com/41428542/175856410-f9ce7b21-3869-4882-8d1d-5b9721bb415e.png)

**Comment by zxxb24ever** [comment]
好像要在黑名单把BASE TABLE过滤掉

**Comment by yreezy** [comment]
#4245 实际可以参考这个 这个是原因

**Comment by git1e** [comment]
> 

1.1.6 版本 试了下 还是不行。

**Comment by herowws** [comment]
> > 
> 
> 1.1.6 版本 试了下 还是不行。

降到1.1.5

**Comment by aotu1280** [comment]
先用把这样设置把服务起起来 canal.instance.filter.regex=.\\..
再把这个设置成想要订阅的库表，比如 canal.instance.filter.regex=test.\\..*

**Comment by goxio** [comment]
> 先这样canal.instance.filter.regex=.\..设置把服务起起来 再把这个改成要订阅的库表，比如 canal.instance.filter.regex=test.\..*

v1.1.6版本的 另外加上黑名单
canal.instance.filter.black.regex=.*\\.BASE TABLE.*

**Comment by AaronZhangL** [comment]
应该过滤掉所有SCHEMA名称下的BASE TABLE表名，修改文件[/home/admin/canal-server/conf/{your-db-schema-name}/instance.properties]中的下面设置：

canal.instance.filter.black.regex=.*\\.BASE TABLE.*

下面的写法只会过滤掉特定SCHEMA, new_energy的BASE TABLE表

canal.instance.filter.black.regex=new_energy\\.BASE.*

**Comment by agapple** [comment]
1.1.6-hotifx版本已修复
