### ISSUE TITLE
canal-1.1.5 同步数据到kafka报下标越界

### ISSUE THREAD

**Issue by dengyangguang** [alibaba/canal#4267]
## Question

ERROR c.a.o.canal.connector.kafka.producer.CanalKafkaProducer - Index: 3, Size: 3
java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
        at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[na:1.8.0_111]
        at java.util.ArrayList.get(ArrayList.java:429) ~[na:1.8.0_111]
        at com.alibaba.otter.canal.connector.core.producer.MQMessageUtils.messagePartition(MQMessageUtils.java:557) ~[connector.core-1.1.5-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.connector.kafka.producer.CanalKafkaProducer.send(CanalKafkaProducer.java:240) ~[na:na]
        at com.alibaba.otter.canal.connector.kafka.producer.CanalKafkaProducer.send(CanalKafkaProducer.java:165) ~[na:na]
        at com.alibaba.otter.canal.server.CanalMQStarter.worker(CanalMQStarter.java:185) [canal.server-1.1.5-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.server.CanalMQStarter.access$500(CanalMQStarter.java:25) [canal.server-1.1.5-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.server.CanalMQStarter$CanalMQRunnable.run(CanalMQStarter.java:227) [canal.server-1.1.5-SNAPSHOT.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]

**Comment by agapple** [comment]
先考虑升级一下最新的版本，1.1.6-hotfix
