### ISSUE TITLE
adapter 下MySQL同步到ES能正常新增,但是更新数据时候报NPE,空指针。

### ISSUE THREAD

**Issue by 0xYGC** [alibaba/canal#4270]
## Question

> canal 都是1.1.6的, MySQL是5.7  ES是7.0.0
> 能监听到同步日志 但是同步会报错
```batch
 ERROR c.a.o.canal.client.adapter.es.core.service.ESSyncService - sync error, es index: test_user, DML : Dml{destination='example', database='ldd_new_test', table='test_user', type='UPDATE', es=1656570350000, ts=1656570352302, sql='', data=[{test_user_id=7, user_name=7, age=7, address=123123, gmt_create=2022-06-30 14:18:59.0}], old=[{address=333}]}
2022-06-30 14:25:52.304 [pool-1-thread-1] ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - java.lang.NullPointerException
java.lang.RuntimeException: java.lang.NullPointerException
        at com.alibaba.otter.canal.client.adapter.es.core.service.ESSyncService.sync(ESSyncService.java:112) ~[na:na]
        at com.alibaba.otter.canal.client.adapter.es.core.service.ESSyncService.sync(ESSyncService.java:60) ~[na:na]
        at com.alibaba.otter.canal.client.adapter.es.core.ESAdapter.sync(ESAdapter.java:104) ~[na:na]
        at com.alibaba.otter.canal.client.adapter.es.core.ESAdapter.sync(ESAdapter.java:83) ~[na:na]
        at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.batchSync(AdapterProcessor.java:140) ~[client-adapter.launcher-1.1.6.jar:na]
        at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.lambda$null$1(AdapterProcessor.java:98) ~[client-adapter.launcher-1.1.6.jar:na]
        at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891) ~[na:1.8.0_181]
        at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.lambda$null$2(AdapterProcessor.java:95) ~[client-adapter.launcher-1.1.6.jar:na]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
Caused by: java.lang.NullPointerException: null
        at com.alibaba.otter.canal.client.adapter.es7x.support.ES7xTemplate.getESDataFromDmlData(ES7xTemplate.java:321) ~[na:na]
        at com.alibaba.otter.canal.client.adapter.es.core.service.ESSyncService.singleTableSimpleFiledUpdate(ESSyncService.java:814) ~[na:na]
        at com.alibaba.otter.canal.client.adapter.es.core.service.ESSyncService.update(ESSyncService.java:208) ~[na:na]
        at com.alibaba.otter.canal.client.adapter.es.core.service.ESSyncService.sync(ESSyncService.java:97) ~[na:na]
        ... 11 common frames omitted
```

**Comment by Qxx-799** [comment]
配置的sql语句中每个表必须要有别名，单表查询也得有，应该是1.1.6的bug

**Comment by JasonPengZiTing** [comment]
遇到了同样的问题，配置了别名还是未能解决，你解决了吗

**Comment by 1512033796** [comment]
> 遇到了同样的问题，配置了别名还是未能解决，你解决了吗

大佬，你的解决了吗？我也是配置了别名还是空指针

**Comment by Qxx-799** [comment]
贴一下最新的配置：
`dataSourceKey: defaultDS
destination: example
outerAdapterKey: elasticsearch
groupId: g1
esMapping:
  _index: article
  _id: _id
  relations:
    customer_order:
      name: customer
  sql: "select 
       a.id as _id,
       a.content_id,
       a.author,
       a.url,
       a.title,
       a.summary,
       a.text,
       a.source_website,
       a.publish_time ,
       a.capture_time ,
       a.capture_website,
       a.content_ext
       from 
       content_service.article a"
  etlCondition: "where a.content_id != {}"
  commitBatch: 3000`

**Comment by fangrui96** [comment]
问题一模一样，哪位大佬解决了

**Comment by fangrui96** [comment]
> 

大佬牛P啊，果然是这个问题

**Comment by qq1063734335** [comment]
> 

配置表别名后解决了

**Comment by yuweni99** [comment]
> > 
> 
> 配置表别名后解决了

我也碰到了同样的问题，能分享一下配置文件嘛，我配置了表的别名还是NPE
