### ISSUE TITLE
com.alibaba.fastjson2.JSONException: illegal character 启动报错

### ISSUE THREAD

**Issue by 15986901041** [alibaba/canal#4282]
2022-07-06 11:35:38.361 [canal-instance-scan-0] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - stop successful....
2022-07-06 11:43:05.347 [canal-instance-scan-0] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Properties resource not found: class path resource [db_sbbc_main_data/instance.properties] cannot be opened because it does not exist
2022-07-06 11:43:05.473 [canal-instance-scan-0] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Properties resource not found: class path resource [db_sbbc_main_data/instance.properties] cannot be opened because it does not exist
2022-07-06 11:43:05.876 [canal-instance-scan-0] INFO  c.a.otter.canal.instance.spring.CanalInstanceWithSpring - start CannalInstance for 1-db_sbbc_main_data 
2022-07-06 11:43:05.881 [canal-instance-scan-0] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table filter : ^db_sbbc_main_data\.maindata_spu$|^db_sbbc_main_data\.sys_dict$
2022-07-06 11:43:05.881 [canal-instance-scan-0] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table black filter : 
2022-07-06 11:43:05.909 [canal-instance-scan-0] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - stop CannalInstance for null-db_sbbc_main_data 
2022-07-06 11:43:05.933 [destination = db_sbbc_main_data , address = /127.0.0.1:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> begin to find start position, it will be long time for reset or first position
2022-07-06 11:43:05.935 [destination = db_sbbc_main_data , address = /127.0.0.1:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - parse events has an error
com.alibaba.otter.canal.parse.exception.CanalParseException: dump address /127.0.0.1:3306 has an error, retrying. 
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: com.alibaba.fastjson2.JSONException: illegal character 
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2218) ~[guava-22.0.jar:na]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4147) ~[guava-22.0.jar:na]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4151) ~[guava-22.0.jar:na]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5140) ~[guava-22.0.jar:na]
	at com.google.common.collect.MigrateMap$MigrateConcurrentMap.get(MigrateMap.java:68) ~[canal.common-1.1.6.jar:na]
	at com.alibaba.otter.canal.meta.MemoryMetaManager.listAllSubscribeInfo(MemoryMetaManager.java:72) ~[canal.meta-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.index.MetaLogPositionManager.getLatestIndexBy(MetaLogPositionManager.java:52) ~[canal.parse-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.index.FailbackLogPositionManager.getLatestIndexBy(FailbackLogPositionManager.java:68) ~[canal.parse-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPositionInternal(MysqlEventParser.java:416) ~[canal.parse-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPosition(MysqlEventParser.java:358) ~[canal.parse-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:191) ~[canal.parse-1.1.6.jar:na]
	at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_211]
Caused by: com.alibaba.fastjson2.JSONException: illegal character 
	at com.alibaba.fastjson2.JSONReaderUTF16.readFieldNameHashCode(JSONReaderUTF16.java:635) ~[fastjson2-2.0.7.jar:na]
	at com.alibaba.fastjson2.reader.ObjectReader_1.readObject(Unknown Source) ~[na:na]
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:487) ~[fastjson2-2.0.7.jar:na]
	at com.alibaba.otter.canal.common.utils.JsonUtils.unmarshalFromString(JsonUtils.java:43) ~[canal.common-1.1.6.jar:na]
	at com.alibaba.otter.canal.meta.FileMixedMetaManager.loadDataFromFile(FileMixedMetaManager.java:175) ~[canal.meta-1.1.6.jar:na]
	at com.alibaba.otter.canal.meta.FileMixedMetaManager.loadClientIdentity(FileMixedMetaManager.java:225) ~[canal.meta-1.1.6.jar:na]
	at com.google.common.collect.MigrateMap$1.load(MigrateMap.java:23) ~[canal.common-1.1.6.jar:na]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3708) ~[guava-22.0.jar:na]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2416) ~[guava-22.0.jar:na]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2299) ~[guava-22.0.jar:na]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2212) ~[guava-22.0.jar:na]
	... 11 common frames omitted
2022-07-06 11:43:05.937 [canal-instance-scan-0] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - stop successful....

版本：
canal.deployer-1.1.6
canal.admin-1.1.6
mysql5.7.37

错误描述：Instance启动失败，之前是正常运行的，今天启动就一直报这个错

**Comment by yucw01** [comment]
升级fastjson2到最新版本就可以了

**Comment by agapple** [comment]
1.1.6-hotfix已经做过修复
