### ISSUE TITLE
canal 1.1.4 报 limit excceed: 6

### ISSUE THREAD

**Issue by dreamboatofli** [alibaba/canal#4287]
## Question

Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: java.lang.IllegalArgumentException: limit excceed: 6
        at com.taobao.tddl.dbsync.binlog.LogBuffer.fillBytes(LogBuffer.java:1557) ~[canal.parse.dbsync-1.1.4.jar:na]
        at com.taobao.tddl.dbsync.binlog.LogBuffer.getData(LogBuffer.java:1578) ~[canal.parse.dbsync-1.1.4.jar:na]
        at com.taobao.tddl.dbsync.binlog.JsonConversion.parse_scalar(JsonConversion.java:174) ~[canal.parse.dbsync-1.1.4.jar:na]
        at com.taobao.tddl.dbsync.binlog.JsonConversion.parse_value(JsonConversion.java:71) ~[canal.parse.dbsync-1.1.4.jar:na]
        at com.taobao.tddl.dbsync.binlog.JsonConversion$Json_Value.element(JsonConversion.java:277) ~[canal.parse.dbsync-1.1.4.jar:na]
        at com.taobao.tddl.dbsync.binlog.JsonConversion$Json_Value.toJsonString(JsonConversion.java:290) ~[canal.parse.dbsync-1.1.4.jar:na]
        at com.taobao.tddl.dbsync.binlog.event.RowsLogBuffer.fetchValue(RowsLogBuffer.java:1093) ~[canal.parse.dbsync-1.1.4.jar:na]
        at com.taobao.tddl.dbsync.binlog.event.RowsLogBuffer.nextValue(RowsLogBuffer.java:125) ~[canal.parse.dbsync-1.1.4.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseOneRow(LogEventConvert.java:726) ~[canal.parse-1.1.4.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseRowsEvent(LogEventConvert.java:549) ~[canal.parse-1.1.4.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$DmlParserStage.onEvent(MysqlMultiStageCoprocessor.java:330) ~[canal.parse-1.1.4.jar:na]

**Comment by yutaoChina** [comment]
参考pr 2318解决，升级版本或者自己修改对应代码
