### ISSUE TITLE
canal 解析mariadb数据库binlog报错

### ISSUE THREAD

**Issue by gongqianqian** [alibaba/canal#4308]
- [x] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version 1.1.3
* mysql version
* mariadb version 10.6.28

### Issue Description
在mariadb环境下，修改表结构，在binlog里生成了alter table *** add column ***日志，canal parse到这个日志会报错，停止解析不了后面的日志了；在mysql 8.0环境下，这个解析这个日志是ok的

### Steps to reproduce
1、启动canal server；
2、在mariadb环境下，修改表结构，在binlog里生成了alter table *** add column ***日志；
3、查看canal.log，有错误日志；导致canal msg发送不出去。
### Actual behaviour

If there is an exception, please attach the exception trace:
java.io.IOException: Read Q_FLAGS2_CODE error: limit excceed: 67
	at com.taobao.tddl.dbsync.binlog.event.QueryLogEvent.unpackVariables(QueryLogEvent.java:717) ~[canal.parse.dbsync-1.1.3.jar:na]
	at com.taobao.tddl.dbsync.binlog.event.QueryLogEvent.<init>(QueryLogEvent.java:495) ~[canal.parse.dbsync-1.1.3.jar:na]
	at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:168) ~[canal.parse.dbsync-1.1.3.jar:na]
	at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:111) ~[canal.parse.dbsync-1.1.3.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:264) [canal.parse-1.1.3.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:246) [canal.parse-1.1.3.jar:na]
	at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168) [disruptor-3.4.2.jar:na]
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125) [disruptor-3.4.2.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
```
Just put your stack trace here!
```

**Comment by rocky-peng** [comment]
mariadb version 10.6.28   还是 10.6.8

**Comment by gongqianqian** [comment]
> mariadb version 10.6.28 还是 10.6.8

sorry，是10.6.8

**Comment by SwimmingTiger** [comment]
同样的问题

* canal-1.1.6-hotfix-1
* 10.7.3-MariaDB

`alter table hu60_msg add column test int default 0`

```
2022-08-15 11:34:11.873 [destination = hu60 , address = /127.0.0.1:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:hu60[com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: Read Q_FLAGS2_CODE error: limit excceed: 67
Caused by: java.io.IOException: Read Q_FLAGS2_CODE error: limit excceed: 67
        at com.taobao.tddl.dbsync.binlog.event.QueryLogEvent.unpackVariables(QueryLogEvent.java:715)
        at com.taobao.tddl.dbsync.binlog.event.QueryLogEvent.<init>(QueryLogEvent.java:495)
        at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:137)
        at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:80)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:269)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:251)
        at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168)
        at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: limit excceed: 67
        at com.taobao.tddl.dbsync.binlog.LogBuffer.getUint32(LogBuffer.java:562)
        at com.taobao.tddl.dbsync.binlog.event.QueryLogEvent.unpackVariables(QueryLogEvent.java:612)
```

**Comment by agapple** [comment]
估计是mariadb新版本有binlog格式修改，canal新版本需要follower支持下
