### ISSUE TITLE
canal支持drds1.0 binlog的增量同步吗？

### ISSUE THREAD

**Issue by qiushaoyun** [alibaba/canal#4363]
## Question

canal支持drds1.0 binlog的增量同步吗？
尝试用canal订阅drds1.0 binlog，出现解析error，日志如下：
2022-08-22 14:12:24.574 [destination = example , address = ****.drds.aliyuncs.com/****:3306 , EventParser] ERROR c.a.o
.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ERROR ## findAsPerTimestampInSpecificLogFile has an error
java.io.IOException: Received error packet: errno = 3009, sqlstate = HY000 errmsg = [14cb7c5ce5d17000][****:3306][****]target
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102) ~[canal.parse-1.1.6.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.seek(MysqlConnection.java:150) ~[canal.parse-1.1.6.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findAsPerTimestampInSpecificLogFile(MysqlEventParser.java:767) [can
al.parse-1.1.6.jar:na]

**Comment by agapple** [comment]
不支持，PolarDB-X 2.0支持canal直接对接
