### ISSUE TITLE
com.alibaba.fastjson2.JSONException: read field error : clientDatas

### ISSUE THREAD

**Issue by bain2018** [alibaba/canal#4373]
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: com.alibaba.fastjson2.JSONException: read field error : clientDatas
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2218) ~[guava-22.0.jar:na]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4147) ~[guava-22.0.jar:na]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4151) ~[guava-22.0.jar:na]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5140) ~[guava-22.0.jar:na]
	at com.google.common.collect.MigrateMap$MigrateConcurrentMap.get(MigrateMap.java:68) ~[canal.common-1.1.6.jar:na]
	at com.alibaba.otter.canal.meta.MemoryMetaManager.listAllSubscribeInfo(MemoryMetaManager.java:72) ~[canal.meta-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.index.MetaLogPositionManager.getLatestIndexBy(MetaLogPositionManager.java:52) ~[canal.parse-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.index.FailbackLogPositionManager.getLatestIndexBy(FailbackLogPositionManager.java:68) ~[canal.parse-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPositionInternal(MysqlEventParser.java:416) ~[canal.parse-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPosition(MysqlEventParser.java:358) ~[canal.parse-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:191) ~[canal.parse-1.1.6.jar:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_202]
Caused by: com.alibaba.fastjson2.JSONException: read field error : clientDatas
	at com.alibaba.fastjson2.reader.FieldReaderObjectMethod.readFieldValue(FieldReaderObjectMethod.java:92) ~[fastjson2-2.0.4.jar:na]
	at com.alibaba.fastjson2.reader.ObjectReader2.readObject(ObjectReader2.java:241) ~[fastjson2-2.0.4.jar:na]
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:258) ~[fastjson2-2.0.4.jar:na]
	at com.alibaba.otter.canal.common.utils.JsonUtils.unmarshalFromString(JsonUtils.java:51) ~[canal.common-1.1.6.jar:na]
	at com.alibaba.otter.canal.meta.FileMixedMetaManager.loadDataFromFile(FileMixedMetaManager.java:176) ~[canal.meta-1.1.6.jar:na]
	at com.alibaba.otter.canal.meta.FileMixedMetaManager.loadClientIdentity(FileMixedMetaManager.java:227) ~[canal.meta-1.1.6.jar:na]
	at com.google.common.collect.MigrateMap$1.load(MigrateMap.java:23) ~[canal.common-1.1.6.jar:na]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3708) ~[guava-22.0.jar:na]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2416) ~[guava-22.0.jar:na]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2299) ~[guava-22.0.jar:na]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2212) ~[guava-22.0.jar:na]
	... 11 common frames omitted
Caused by: com.alibaba.fastjson2.JSONException: read field error : cursor
	at com.alibaba.fastjson2.reader.FieldReaderObjectMethod.readFieldValue(FieldReaderObjectMethod.java:92) ~[fastjson2-2.0.4.jar:na]
	at com.alibaba.fastjson2.reader.ObjectReader2.readObject(ObjectReader2.java:243) ~[fastjson2-2.0.4.jar:na]
	at com.alibaba.fastjson2.reader.ObjectReaderImplList.readObject(ObjectReaderImplList.java:435) ~[fastjson2-2.0.4.jar:na]
	at com.alibaba.fastjson2.reader.FieldReaderObjectMethod.readFieldValue(FieldReaderObjectMethod.java:90) ~[fastjson2-2.0.4.jar:na]
	... 21 common frames omitted
Caused by: com.alibaba.fastjson2.JSONException: read field error : identity
	at com.alibaba.fastjson2.reader.FieldReaderObjectMethod.readFieldValue(FieldReaderObjectMethod.java:92) ~[fastjson2-2.0.4.jar:na]
	at com.alibaba.fastjson2.reader.ObjectReader2.readObject(ObjectReader2.java:241) ~[fastjson2-2.0.4.jar:na]
	at com.alibaba.fastjson2.reader.FieldReaderObjectMethod.readFieldValue(FieldReaderObjectMethod.java:90) ~[fastjson2-2.0.4.jar:na]
	... 24 common frames omitted
Caused by: com.alibaba.fastjson2.JSONException: read field error : sourceAddress
	at com.alibaba.fastjson2.reader.FieldReaderObjectMethod.readFieldValue(FieldReaderObjectMethod.java:92) ~[fastjson2-2.0.4.jar:na]
	at com.alibaba.fastjson2.reader.ObjectReader2.readObject(ObjectReader2.java:243) ~[fastjson2-2.0.4.jar:na]
	at com.alibaba.fastjson2.reader.FieldReaderObjectMethod.readFieldValue(FieldReaderObjectMethod.java:90) ~[fastjson2-2.0.4.jar:na]
	... 26 common frames omitted
Caused by: com.alibaba.fastjson2.JSONException: create instance error, class java.net.InetSocketAddress
	at com.alibaba.fastjson2.reader.ObjectReaderAdapter.createInstance0(ObjectReaderAdapter.java:178) ~[fastjson2-2.0.4.jar:na]
	at com.alibaba.fastjson2.reader.ObjectReaderAdapter.createInstance(ObjectReaderAdapter.java:233) ~[fastjson2-2.0.4.jar:na]
	at com.alibaba.fastjson2.reader.ObjectReaderBean.readObject(ObjectReaderBean.java:162) ~[fastjson2-2.0.4.jar:na]
	at com.alibaba.fastjson2.reader.FieldReaderObjectMethod.readFieldValue(FieldReaderObjectMethod.java:90) ~[fastjson2-2.0.4.jar:na]
	... 28 common frames omitted
2022-08-25 10:48:37.695 [main] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - stop successful....
2022-08-25 11:28:16.957 [main] INFO  c.a.otter.canal.instance.spring.CanalInstanceWithSpring - start CannalInstance for 1-cloud 
2022-08-25 11:28:16.963 [main] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table filter : ^yunfadan\.fa_follow_chatroom_member$|^yunfadan\.fa_follow_chatroom_accept$|^yunfadan\.fa_wechat_chatroominfo$|^yunfadan\.fa_chatroominfo_white$|^yunfadan\.fa_chatroominfo_black$|^yunfadan\.fa_official_keyword$|^yunfadan\.fa_wechat_chatroom$|^yunfadan\.fa_follow_chatroom$|^yunfadan\.fa_goods_blacklist$|^yunfadan\.fa_webchat_group$|^yunfadan\.fa_wechat_source$|^yunfadan\.fa_wechat_rebot$|^yunfadan\.fa_wechat_robot$|^yunfadan\.fa_wechat_auth$|^yunfadan\.fa_msg_reply$|^yunfadan\.fa_config$|^yunfadan\.fa_user$
2022-08-25 11:28:16.963 [main] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table black filter : ^information_schema\..*$|^performance_schema\..*$|^__recycle_bin__\..*$|^mysql\..*$|^sys\..*$
2022-08-25 11:28:16.963 [main] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - start successful....
2022-08-25 11:28:16.990 [destination = cloud , address = pc-m5ew7xiaw1bo554ov.rwlb.rds.aliyuncs.com/172.31.100.210:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> begin to find start position, it will be long time for reset or first position
2022-08-25 11:28:16.990 [destination = cloud , address = pc-m5ew7xiaw1bo554ov.rwlb.rds.aliyuncs.com/172.31.100.210:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - prepare to find start position just show master status
2022-08-25 11:28:19.889 [destination = cloud , address = pc-m5ew7xiaw1bo554ov.rwlb.rds.aliyuncs.com/172.31.100.210:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> find start position successfully, EntryPosition[included=false,journalName=mysql-bin.006380,position=155339954,serverId=22433461,gtid=,timestamp=1661398096000] cost : 2898ms , the next step is binlog dump
2022-08-25 14:59:34.607 [Thread-12] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - stop CannalInstance for null-cloud 
2022-08-25 14:59:34.681 [Thread-12] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - stop successful....
2022-08-25 14:59:37.743 [main] INFO  c.a.otter.canal.instance.spring.CanalInstanceWithSpring - start CannalInstance for 1-cloud 
2022-08-25 14:59:37.748 [main] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table filter : ^yunfadan\.fa_follow_chatroom_member$|^yunfadan\.fa_follow_chatroom_accept$|^yunfadan\.fa_wechat_chatroominfo$|^yunfadan\.fa_chatroominfo_white$|^yunfadan\.fa_chatroominfo_black$|^yunfadan\.fa_official_keyword$|^yunfadan\.fa_wechat_chatroom$|^yunfadan\.fa_follow_chatroom$|^yunfadan\.fa_goods_blacklist$|^yunfadan\.fa_webchat_group$|^yunfadan\.fa_wechat_source$|^yunfadan\.fa_wechat_rebot$|^yunfadan\.fa_wechat_robot$|^yunfadan\.fa_wechat_auth$|^yunfadan\.fa_msg_reply$|^yunfadan\.fa_config$|^yunfadan\.fa_user$
2022-08-25 14:59:37.748 [main] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table black filter : ^information_schema\..*$|^performance_schema\..*$|^__recycle_bin__\..*$|^mysql\..*$|^sys\..*$
2022-08-25 14:59:37.750 [main] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - stop CannalInstance for null-cloud 
2022-08-25 14:59:37.781 [destination = cloud , address = pc-m5ew7xiaw1bo554ov.rwlb.rds.aliyuncs.com/172.31.100.210:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> begin to find start position, it will be long time for reset or first position
2022-08-25 14:59:37.784 [destination = cloud , address = pc-m5ew7xiaw1bo554ov.rwlb.rds.aliyuncs.com/172.31.100.210:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - parse events has an error
com.alibaba.otter.canal.parse.exception.CanalParseException: dump address pc-m5ew7xiaw1bo554ov.rwlb.rds.aliyuncs.com/172.31.100.210:3306 has an error, retrying. 
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: com.alibaba.fastjson2.JSONException: read field error : clientDatas
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2218) ~[guava-22.0.jar:na]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4147) ~[guava-22.0.jar:na]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4151) ~[guava-22.0.jar:na]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5140) ~[guava-22.0.jar:na]
	at com.google.common.collect.MigrateMap$MigrateConcurrentMap.get(MigrateMap.java:68) ~[canal.common-1.1.6.jar:na]
	at com.alibaba.otter.canal.meta.MemoryMetaManager.listAllSubscribeInfo(MemoryMetaManager.java:72) ~[canal.meta-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.index.MetaLogPositionManager.getLatestIndexBy(MetaLogPositionManager.java:52) ~[canal.parse-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.index.FailbackLogPositionManager.getLatestIndexBy(FailbackLogPositionManager.java:68) ~[canal.parse-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPositionInternal(MysqlEventParser.java:416) ~[canal.parse-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPosition(MysqlEventParser.java:358) ~[canal.parse-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:191) ~[canal.parse-1.1.6.jar:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_202]
Caused by: com.alibaba.fastjson2.JSONException: read field error : clientDatas
	at com.alibaba.fastjson2.reader.FieldReaderObjectMethod.readFieldValue(FieldReaderObjectMethod.java:92) ~[fastjson2-2.0.4.jar:na]
	at com.alibaba.fastjson2.reader.ObjectReader2.readObject(ObjectReader2.java:241) ~[fastjson2-2.0.4.jar:na]
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:258) ~[fastjson2-2.0.4.jar:na]
	at com.alibaba.otter.canal.common.utils.JsonUtils.unmarshalFromString(JsonUtils.java:51) ~[canal.common-1.1.6.jar:na]
	at com.alibaba.otter.canal.meta.FileMixedMetaManager.loadDataFromFile(FileMixedMetaManager.java:176) ~[canal.meta-1.1.6.jar:na]
	at com.alibaba.otter.canal.meta.FileMixedMetaManager.loadClientIdentity(FileMixedMetaManager.java:227) ~[canal.meta-1.1.6.jar:na]
	at com.google.common.collect.MigrateMap$1.load(MigrateMap.java:23) ~[canal.common-1.1.6.jar:na]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3708) ~[guava-22.0.jar:na]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2416) ~[guava-22.0.jar:na]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2299) ~[guava-22.0.jar:na]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2212) ~[guava-22.0.jar:na]
	... 11 common frames omitted
Caused by: com.alibaba.fastjson2.JSONException: read field error : cursor
	at com.alibaba.fastjson2.reader.FieldReaderObjectMethod.readFieldValue(FieldReaderObjectMethod.java:92) ~[fastjson2-2.0.4.jar:na]
	at com.alibaba.fastjson2.reader.ObjectReader2.readObject(ObjectReader2.java:243) ~[fastjson2-2.0.4.jar:na]
	at com.alibaba.fastjson2.reader.ObjectReaderImplList.readObject(ObjectReaderImplList.java:435) ~[fastjson2-2.0.4.jar:na]
	at com.alibaba.fastjson2.reader.FieldReaderObjectMethod.readFieldValue(FieldReaderObjectMethod.java:90) ~[fastjson2-2.0.4.jar:na]
	... 21 common frames omitted
Caused by: com.alibaba.fastjson2.JSONException: read field error : identity
	at com.alibaba.fastjson2.reader.FieldReaderObjectMethod.readFieldValue(FieldReaderObjectMethod.java:92) ~[fastjson2-2.0.4.jar:na]
	at com.alibaba.fastjson2.reader.ObjectReader2.readObject(ObjectReader2.java:241) ~[fastjson2-2.0.4.jar:na]
	at com.alibaba.fastjson2.reader.FieldReaderObjectMethod.readFieldValue(FieldReaderObjectMethod.java:90) ~[fastjson2-2.0.4.jar:na]
	... 24 common frames omitted
Caused by: com.alibaba.fastjson2.JSONException: read field error : sourceAddress
	at com.alibaba.fastjson2.reader.FieldReaderObjectMethod.readFieldValue(FieldReaderObjectMethod.java:92) ~[fastjson2-2.0.4.jar:na]
	at com.alibaba.fastjson2.reader.ObjectReader2.readObject(ObjectReader2.java:243) ~[fastjson2-2.0.4.jar:na]
	at com.alibaba.fastjson2.reader.FieldReaderObjectMethod.readFieldValue(FieldReaderObjectMethod.java:90) ~[fastjson2-2.0.4.jar:na]
	... 26 common frames omitted
Caused by: com.alibaba.fastjson2.JSONException: create instance error, class java.net.InetSocketAddress
	at com.alibaba.fastjson2.reader.ObjectReaderAdapter.createInstance0(ObjectReaderAdapter.java:178) ~[fastjson2-2.0.4.jar:na]
	at com.alibaba.fastjson2.reader.ObjectReaderAdapter.createInstance(ObjectReaderAdapter.java:233) ~[fastjson2-2.0.4.jar:na]
	at com.alibaba.fastjson2.reader.ObjectReaderBean.readObject(ObjectReaderBean.java:162) ~[fastjson2-2.0.4.jar:na]
	at com.alibaba.fastjson2.reader.FieldReaderObjectMethod.readFieldValue(FieldReaderObjectMethod.java:90) ~[fastjson2-2.0.4.jar:na]
	... 28 common frames omitted

**Comment by agapple** [comment]
这个fastjson2应该修复过，可以下载1.1.6-hotfix的版本
