### ISSUE TITLE
Unsupported command: COM_BINLOG_DUMP 报这个错误，不知道是什么原因

### ISSUE THREAD

**Issue by weriong** [alibaba/canal#4393]
## Question

2022-09-06 18:32:10.505 [destination = example , address =127.0.0.1:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ERROR ## findAsPerTimestampInSpecificLogFile has an error
java.io.IOException: Received error packet: errno = 3000, sqlstate = PX000 errmsg = [qhnzquxdfxnh715zdzx7ukfgukareo] Unsupported command: COM_BINLOG_DUMP
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102) ~[canal.parse-1.1.6.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.seek(MysqlConnection.java:150) ~[canal.parse-1.1.6.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findAsPerTimestampInSpecificLogFile(MysqlEventParser.java:767) ~[canal.parse-1.1.6.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findEndPositionWithMasterIdAndTimestamp(MysqlEventParser.java:384) ~[canal.parse-1.1.6.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPositionInternal(MysqlEventParser.java:439) ~[canal.parse-1.1.6.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPosition(MysqlEventParser.java:358) ~[canal.parse-1.1.6.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:191) ~[canal.parse-1.1.6.jar:na]

**Comment by agapple** [comment]
Unsupported command: COM_BINLOG_DUMP

你连得是的啥数据库类型？
