### ISSUE TITLE
instance启动报错，求助

### ISSUE THREAD

**Issue by 1157242994** [alibaba/canal#4395]
搭建的是集群，使用canal版本是1.1.5版本，数据是mysql的5.7.36

集群管理的配置如下
canal.zkServers = 192.168.86.170:2181,192.168.86.180:2181,192.168.86.190:2181
canal.serverMode = tcp
canal.instance.tsdb.enable = true
canal.instance.tsdb.url = jdbc:mysql://192.168.86.180:3306/canal_tsdb
canal.instance.tsdb.dbUsername = root
canal.instance.tsdb.dbPassword = 123456
canal.instance.global.spring.xml = classpath:spring/default-instance.xml

instance实例配置如下
canal.instance.mysql.slaveId=12
canal.instance.gtidon=false
canal.instance.master.address=192.168.86.180:3306
canal.instance.master.journal.name=mysql-bin.000001
canal.instance.master.position=333
canal.instance.master.timestamp=
canal.instance.master.gtid=
canal.instance.dbUsername=root
canal.instance.dbPassword=123456
canal.instance.connectionCharset = UTF-8
canal.instance.enableDruid=false
canal.instance.filter.regex=acpcanaldb.*

启动instance报如下错误
2022-09-06 22:15:21.260 [Druid-ConnectionPool-Create-1911574676] ERROR com.alibaba.druid.pool.DruidDataSource - create connection SQLException, url: jdbc:mysql://192.168.86.180:3306/canal_tsdb, errorCode 0, state null
java.sql.SQLException: connect error, url jdbc:mysql://192.168.86.180:3306/canal_tsdb, driverClass org.h2.Driver
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1727) ~[druid-1.2.6.jar:1.2.6]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2801) ~[druid-1.2.6.jar:1.2.6]
![image](https://user-images.githubusercontent.com/79518581/188658535-55668787-df4e-4756-b62f-669fbb0edb7f.png)

**Comment by adminpass** [comment]
试下：
```
# url
canal.instance.tsdb.url = jdbc:mysql://192.168.86.180:3306/canal_tsdb?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true

# tsdb配置路径,在canal.conf.dir路径下
canal.instance.tsdb.spring.xml = classpath:spring/tsdb/mysql-tsdb.xml
```
