### ISSUE TITLE
canal.serverMode=rabbitMQ Windows环境启动报错(deployer-1.1.6)

### ISSUE THREAD

**Issue by xiaomu98** [alibaba/canal#4410]
Windows环境双击startup.bat命令行窗口闪退，查看canal.log日志文件报错信息如下：
2022-09-14 02:35:10.909 [main] INFO  com.alibaba.otter.canal.deployer.CanalLauncher - ## set default uncaught exception handler
2022-09-14 02:35:10.914 [main] INFO  com.alibaba.otter.canal.deployer.CanalLauncher - ## load canal configurations
2022-09-14 02:35:10.927 [main] ERROR com.alibaba.otter.canal.deployer.CanalLauncher - ## Something goes wrong when starting up the canal Server:
java.lang.IllegalStateException: Extension instance(name: rabbitmq, class: interface com.alibaba.otter.canal.connector.core.spi.CanalMQProducer)  could not be instantiated: class could not be found
	at com.alibaba.otter.canal.connector.core.spi.ExtensionLoader.createExtension(ExtensionLoader.java:169) ~[connector.core-1.1.6.jar:na]
	at com.alibaba.otter.canal.connector.core.spi.ExtensionLoader.getExtension(ExtensionLoader.java:121) ~[connector.core-1.1.6.jar:na]
	at com.alibaba.otter.canal.deployer.CanalStarter.start(CanalStarter.java:68) ~[canal.deployer-1.1.6.jar:na]
	at com.alibaba.otter.canal.deployer.CanalLauncher.main(CanalLauncher.java:124) ~[canal.deployer-1.1.6.jar:na]

版本：deployer-1.1.6
canal.properties配置文件：
#############    tcp, kafka, rocketMQ, rabbitMQ, pulsarMQ    #############
canal.serverMode = rabbitMQ

##################################################
##################################################
rabbitmq.host = 127.0.0.1:5672
rabbitmq.virtual.host = /dev
rabbitmq.exchange = canal.exchange
rabbitmq.username = dev
rabbitmq.password = dev
rabbitmq.deliveryMode =

**Comment by strongXiaochen** [comment]
可以看一下这个 [issue](https://github.com/alibaba/canal/issues/4366#issuecomment-1225899913)
