### ISSUE TITLE
我想有必要更新一下BinlogFile这个对象了

### ISSUE THREAD

**Issue by JayeShen** [alibaba/canal#4423]
## Why you need it?

企业里面使用oss中离线的Binlog恢复还是比较多的，目前BinlogFile比较老
1、最重要的是没有解析以及使用内网地址去下载文件，使用外网地址（DownloadLink）的话一是依赖于带宽，下载比较慢，二是外网也会收费，在企业一般会和阿里云搭一条专线，所以用内网地址下载是最合适的。
2、对象中变量fileName无法与rds返回的变量LogFileName对应，导致json解析异常

关于对象BinlogFile
canal-1.1.4到canal-1.1.6目前的BinlogFile 对象
public class BinlogFile {

    private Long   FileSize;
    private String LogBeginTime;
    private String LogEndTime;
    private String DownloadLink;
    private String HostInstanceID;
    private String LinkExpiredTime;
    private String fileName;

rds返回的BinlogFile 对象
	"BinLogFile": [{
				"DownloadLink": "https://log-sh-fin-v2.oss-cn-shanghai-finance-1-pub.aliyuncs.com/custins41544748/hostins16829101/mysql-bin.054005。。。。。。。。。。。。。。。。",
				"LogBeginTime": "2022-09-22T02:50:22Z",
				"LinkExpiredTime": "2022-09-24T03:26:46Z",
				"Checksum": "15055057331169856844",
				"LogEndTime": "2022-09-22T03:20:19Z",
				"RemoteStatus": "Completed",
				"IntranetDownloadLink": "http://log-sh-fin-v2.oss-cn-shanghai-finance-1-pub-internal.aliyuncs.com/custins41544748/hostins16829101/mysql-bin.054005?。。。。。。。。。。。。。。",
				"HostInstanceID": 16829101,
				"LogFileName": "mysql-bin.054005",
				"FileSize": 524317325
			},

异常日志：

2022-09-22 10:53:23.490 [rds-binlog-daemon-thread] ERROR c.a.o.c.p.inbound.mysql.rds.RdsLocalBinlogEventParser - download binlog failed
java.lang.RuntimeException: com.alibaba.fastjson.JSONException: syntax error, expect {, actual error, pos 0, fastjson-version 1.2.58
	at com.alibaba.otter.canal.parse.inbound.mysql.rds.RdsBinlogOpenApi.listBinlogFiles(RdsBinlogOpenApi.java:54) ~[canal.parse-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.rds.RdsLocalBinlogEventParser.start(RdsLocalBinlogEventParser.java:66) ~[canal.parse-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.rds.RdsBinlogEventParserProxy$4.run(RdsBinlogEventParserProxy.java:131) [canal.parse-1.1.4.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
Caused by: com.alibaba.fastjson.JSONException: syntax error, expect {, actual error, pos 0, fastjson-version 1.2.58
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:489) ~[fastjson-1.2.58.jar:na]
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseRest(JavaBeanDeserializer.java:1537) ~[fastjson-1.2.58.jar:na]
	at com.alibaba.fastjson.parser.deserializer.FastjsonASMDeserializer_6_DescribeBinlogFileResult.deserialze(Unknown Source) ~[na:na]
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:284) ~[fastjson-1.2.58.jar:na]
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:689) ~[fastjson-1.2.58.jar:na]
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:378) ~[fastjson-1.2.58.jar:na]
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:346) ~[fastjson-1.2.58.jar:na]
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:260) ~[fastjson-1.2.58.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.rds.request.DescribeBinlogFilesRequest.processResult(DescribeBinlogFilesRequest.java:50) ~[canal.parse-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.rds.request.DescribeBinlogFilesRequest.processResult(DescribeBinlogFilesRequest.java:16) ~[canal.parse-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.rds.request.AbstractRequest.doAction(AbstractRequest.java:249) ~[canal.parse-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.rds.RdsBinlogOpenApi.listBinlogFiles(RdsBinlogOpenApi.java:50) ~[canal.parse-1.1.4.jar:na]
	... 5 common frames omitted

## How it could be?

1、补充BinLogFile对象成员变量
2、优先使用内网下载binlog文件

**Comment by agapple** [comment]
可以考虑提交一个PR给我
