### ISSUE TITLE
canal server 异常 'show binlog events limit 1’

### ISSUE THREAD

**Issue by liuwenfeng554** [alibaba/canal#444]
上午binlog日志被删，下午重启任务，canal client 日志没有异常，canal server异常：
2017-12-11 19:35:30.882 [destination = fengdai_mqnotify , address = /10.20.21.11:3306 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - dump address /10.20.21.11:3306 has an error, retrying. caused by 
com.alibaba.otter.canal.parse.exception.CanalParseException: command : 'show binlog events limit 1' has an error!
Caused by: java.io.IOException: Unexpected End Stream
	at com.alibaba.otter.canal.parse.driver.mysql.utils.PacketManager.readBytesAsBuffer(PacketManager.java:22) ~[canal.parse.driver-1.0.24.jar:na]
	at com.alibaba.otter.canal.parse.driver.mysql.utils.PacketManager.readHeader(PacketManager.java:13) ~[canal.parse.driver-1.0.24.jar:na]
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlQueryExecutor.readNextPacket(MysqlQueryExecutor.java:104) ~[canal.parse.driver-1.0.24.jar:na]
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlQueryExecutor.query(MysqlQueryExecutor.java:77) ~[canal.parse.driver-1.0.24.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.query(MysqlConnection.java:73) ~[canal.parse-1.0.24.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPosition(MysqlEventParser.java:610) ~[canal.parse-1.0.24.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findByStartTimeStamp(MysqlEventParser.java:514) ~[canal.parse-1.0.24.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPositionInternal(MysqlEventParser.java:358) ~[canal.parse-1.0.24.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPosition(MysqlEventParser.java:315) ~[canal.parse-1.0.24.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:161) ~[canal.parse-1.0.24.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66]

想确认下为何为何上午日志还是能正常写入，而重启会出现这种情况

**Comment by liuwenfeng554** [comment]
@agapple

**Comment by agapple** [comment]
com.alibaba.otter.canal.parse.exception.CanalParseException: command : 'show binlog events limit 1' has an error!
Caused by: java.io.IOException: Unexpected End Stream

**Comment by liuwenfeng554** [comment]
重启下mysql或重新开启binlog就好了嘛？
