### ISSUE TITLE
连接远端数据库时报 qlstate = HY000 errmsg = dispatch command 18 not supported now

### ISSUE THREAD

**Issue by CockyCat** [alibaba/canal#4446]
## Question
连接本地库时正常，切换成远程库时报一下错误：

2022-10-10 13:31:55.330 [destination = example , address = /xxx.xxx.xxx.xxx:3306 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - I/O error while reading from client socket
java.io.IOException: Received error packet: errno = 1105, sqlstate = HY000 errmsg = dispatch command 18 not supported now, connection id[6247797] user[xxxxx] addr[111.xxx.xx.107:56398] db[xxxxx]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102) ~[canal.parse-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.seek(MysqlConnection.java:150) ~[canal.parse-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findAsPerTimestampInSpecificLogFile(MysqlEventParser.java:767) ~[canal.parse-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findByStartTimeStamp(MysqlEventParser.java:597) ~[canal.parse-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPositionInternal(MysqlEventParser.java:519) ~[canal.parse-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPosition(MysqlEventParser.java:358) ~[canal.parse-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:191) ~[canal.parse-1.1.6.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

**Comment by agapple** [comment]
你链接的是官方mysql么？command 18就是COM_BINLOG_DUMP，代表这个实例不支持binlog dump
