### ISSUE TITLE
canal1.1.6增量数据同步MySQL到es报NPE异常

### ISSUE THREAD

**Issue by deltaj77** [alibaba/canal#4447]
- canal version：1.1.6
- MySQL version: 5.7.21
- elasticSearch version：6.5.4
- canal-adapter/conf/es6/tar.yml配置如下：

> dataSourceKey: defaultDS
destination: example
outerAdapterKey: elasticsearch
groupId: g1
esMapping:
  _index: tar
  _type: tar
  _id: _id
  upsert: true
  sql: "
    select 
       t1.icmp_id as _id,
       t1.name_zh as name_zh,
       'persion' as className,
       t1.remark as reamrk,
       '' as task,
       t1.name_en as name_en
     from test001.tar t1
  "
  commitBatch: 3000

- canal-adapter 错误日志：

> 2022-10-10 14:36:47.324 [pool-2-thread-1] ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - java.lang.NullPointerException
java.lang.RuntimeException: java.lang.NullPointerException
	at com.alibaba.otter.canal.client.adapter.es.core.service.ESSyncService.sync(ESSyncService.java:112) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.es.core.service.ESSyncService.sync(ESSyncService.java:60) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.es.core.ESAdapter.sync(ESAdapter.java:104) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.es.core.ESAdapter.sync(ESAdapter.java:83) ~[na:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.batchSync(AdapterProcessor.java:140) ~[client-adapter.launcher-1.1.6.jar:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.lambda$null$1(AdapterProcessor.java:98) ~[client-adapter.launcher-1.1.6.jar:na]
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807) ~[na:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.lambda$null$2(AdapterProcessor.java:95) ~[client-adapter.launcher-1.1.6.jar:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: java.lang.NullPointerException: null
	at com.alibaba.otter.canal.client.adapter.es6x.support.ES6xTemplate.insert(ES6xTemplate.java:74) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.es.core.service.ESSyncService.singleTableSimpleFiledInsert(ESSyncService.java:444) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.es.core.service.ESSyncService.insert(ESSyncService.java:135) ~[na:na]
	at com.alibaba.otter.canal.client.adapter.es.core.service.ESSyncService.sync(ESSyncService.java:95) ~[na:na]
	... 11 common frames omitted

**Comment by yuweni99** [comment]
请问解决了嘛，我也碰到了同样的问题

**Comment by newbieking** [comment]
我遇到相似的问题，排查后发现是canal获取索引的元信息时，我并没有创建相应的索引，导致获取的相应map为空，从而产生NPE：
[ES7xTemplate::getEsType](https://github.com/alibaba/canal/blob/canal-1.1.6-hotfix-1/client-adapter/es7x/src/main/java/com/alibaba/otter/canal/client/adapter/es7x/support/ES7xTemplate.java#L403)


![Screenshot 2024-02-12 103805](https://github.com/alibaba/canal/assets/73046823/37a45899-181e-4d56-b0fc-96910a413323)

我通过创建相应的索引从而解决了该问题

**Comment by oldwhite83** [comment]
我的是1.7 版本，也同样包这个错误，sql 表名也重命名了，

**Comment by newbieking** [comment]
> 我的是1.7 版本，也同样包这个错误，sql 表名也重命名了，

你es中对应的索引创建了吗？

**Comment by yuweni99** [comment]
我忘记了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: newbieking ***@***.***&gt;
发送时间: 2024年3月6日 17:00
收件人: alibaba/canal ***@***.***&gt;
抄送: yuweni99 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [alibaba/canal] canal1.1.6增量数据同步MySQL到es报NPE异常 (Issue #4447)





  
我的是1.7 版本，也同样包这个错误，sql 表名也重命名了，
  
你es中对应的索引创建了吗？

**Comment by cynen** [comment]
貌似是需要自己手工先 去es创建对应的索引
