### ISSUE TITLE
在cannel Admin中Instance一开始可以启动，第二天重新启动就启动不了。

### ISSUE THREAD

**Issue by lizebin-dream** [alibaba/canal#4449]
## Question

日志信息如下：
2022-10-12 10:14:33.709 [canal-instance-scan-0] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Properties resource not found: class path resource [saas_dev/instance.properties] cannot be opened because it does not exist
2022-10-12 10:14:33.733 [canal-instance-scan-0] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Properties resource not found: class path resource [saas_dev/instance.properties] cannot be opened because it does not exist
2022-10-12 10:14:33.767 [canal-instance-scan-0] INFO  c.a.otter.canal.instance.spring.CanalInstanceWithSpring - start CannalInstance for 1-saas_dev 
2022-10-12 10:14:33.767 [canal-instance-scan-0] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table filter : ^wisdom_saas_goldworld_dev.s_device$|^wisdom_saas_goldworld_dev.s_person$
2022-10-12 10:14:33.768 [canal-instance-scan-0] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table black filter : ^mysql\.slave_.*$
2022-10-12 10:14:33.774 [canal-instance-scan-0] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - stop CannalInstance for null-saas_dev 
2022-10-12 10:14:33.850 [destination = saas_dev , address = rm-wz92t4rtx7ic05o1alo.mysql.rds.aliyuncs.com/47.107.202.185:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> begin to find start position, it will be long time for reset or first position
2022-10-12 10:14:33.852 [destination = saas_dev , address = rm-wz92t4rtx7ic05o1alo.mysql.rds.aliyuncs.com/47.107.202.185:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - parse events has an error
com.alibaba.otter.canal.parse.exception.CanalParseException: dump address rm-wz92t4rtx7ic05o1alo.mysql.rds.aliyuncs.com/47.107.202.185:3306 has an error, retrying. 
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: com.alibaba.fastjson2.JSONException: create object error, offset 493, character ", line 1, column 494, fastjson-version 2.0.7 {"clientDatas":[{"clientIdentity":{"clientId":1001,"destination":"saas_dev","filter":""},"cursor":{"identity":{"slaveId":-1,"sourceAddress":{"address":"xxxxxx:3306\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","port":3306}},"postion":{"gtid":"","included":false,"journalName":"mysql-bin.008610","position":432731132,"serverId":2817172031,"timestamp":1665483624000}}}],"destination":"saas_dev"}
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2218) ~[guava-22.0.jar:na]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4147) ~[guava-22.0.jar:na]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4151) ~[guava-22.0.jar:na]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5140) ~[guava-22.0.jar:na]
	at com.google.common.collect.MigrateMap$MigrateConcurrentMap.get(MigrateMap.java:68) ~[canal.common-1.1.7-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.meta.MemoryMetaManager.listAllSubscribeInfo(MemoryMetaManager.java:72) ~[canal.meta-1.1.7-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.index.MetaLogPositionManager.getLatestIndexBy(MetaLogPositionManager.java:52) ~[canal.parse-1.1.7-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.index.FailbackLogPositionManager.getLatestIndexBy(FailbackLogPositionManager.java:68) ~[canal.parse-1.1.7-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPositionInternal(MysqlEventParser.java:416) ~[canal.parse-1.1.7-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPosition(MysqlEventParser.java:358) ~[canal.parse-1.1.7-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:191) ~[canal.parse-1.1.7-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:823) ~[na:1.8.0_282]
Caused by: com.alibaba.fastjson2.JSONException: create object error, offset 493, character ", line 1, column 494, fastjson-version 2.0.7 {"clientDatas":[{"clientIdentity":{"clientId":1001,"destination":"saas_dev","filter":""},"cursor":{"identity":{"slaveId":-1,"sourceAddress":{"address":"xxxx:3306\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","port":3306}},"postion":{"gtid":"","included":false,"journalName":"mysql-bin.008610","position":432731132,"serverId":2817172031,"timestamp":1665483624000}}}],"destination":"saas_dev"}
	at com.alibaba.fastjson2.reader.ObjectReaderImplValue.readObject(ObjectReaderImplValue.java:71) ~[fastjson2-2.0.7.jar:na]
	at com.alibaba.fastjson2.JSONReader.read(JSONReader.java:1409) ~[fastjson2-2.0.7.jar:na]
	at com.alibaba.fastjson2.reader.ObjectReaderMisc.readObject(ObjectReaderMisc.java:38) ~[fastjson2-2.0.7.jar:na]
	at com.alibaba.fastjson2.reader.ObjectReader_5.readObject(Unknown Source) ~[na:na]
	at com.alibaba.fastjson2.reader.ObjectReader_4.readObject(Unknown Source) ~[na:na]
	at com.alibaba.fastjson2.reader.ObjectReader_2.readObject(Unknown Source) ~[na:na]
	at com.alibaba.fastjson2.reader.ObjectReader_1.readObject(Unknown Source) ~[na:na]
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:487) ~[fastjson2-2.0.7.jar:na]
	at com.alibaba.otter.canal.common.utils.JsonUtils.unmarshalFromString(JsonUtils.java:43) ~[canal.common-1.1.7-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.meta.FileMixedMetaManager.loadDataFromFile(FileMixedMetaManager.java:175) ~[canal.meta-1.1.7-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.meta.FileMixedMetaManager.loadClientIdentity(FileMixedMetaManager.java:225) ~[canal.meta-1.1.7-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.meta.FileMixedMetaManager$$Lambda$70/0x0000000000000000.apply(Unknown Source) ~[na:na]
	at com.google.common.collect.MigrateMap$1.load(MigrateMap.java:23) ~[canal.common-1.1.7-SNAPSHOT.jar:na]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3708) ~[guava-22.0.jar:na]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2416) ~[guava-22.0.jar:na]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2299) ~[guava-22.0.jar:na]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2212) ~[guava-22.0.jar:na]
	... 11 common frames omitted
Caused by: com.alibaba.fastjson2.JSONException: create address error
	at com.alibaba.fastjson2.reader.ObjectReaderBaseModule.lambda$getObjectReader$12(ObjectReaderBaseModule.java:1776) ~[fastjson2-2.0.7.jar:na]
	at com.alibaba.fastjson2.reader.ObjectReaderBaseModule$$Lambda$131/0x0000000000000000.apply(Unknown Source) ~[na:na]
	at com.alibaba.fastjson2.reader.ObjectReaderImplValue.readObject(ObjectReaderImplValue.java:69) ~[fastjson2-2.0.7.jar:na]
	... 27 common frames omitted
Caused by: java.net.UnknownHostException: XXXXXX:3306
	at java.net.InetAddress.getAllByName0(InetAddress.java:1281) ~[na:1.8.0_282]
	at java.net.InetAddress.getAllByName(InetAddress.java:1193) ~[na:1.8.0_282]
	at java.net.InetAddress.getAllByName(InetAddress.java:1127) ~[na:1.8.0_282]
	at java.net.InetAddress.getByName(InetAddress.java:1077) ~[na:1.8.0_282]
	at com.alibaba.fastjson2.reader.ObjectReaderBaseModule.lambda$getObjectReader$12(ObjectReaderBaseModule.java:1774) ~[fastjson2-2.0.7.jar:na]
	... 29 common frames omitted
2022-10-12 10:14:33.853 [canal-instance-scan-0] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - stop successful....

**Comment by agapple** [comment]
{"clientDatas":[{"clientIdentity":{"clientId":1001,"destination":"saas_dev","filter":""},"cursor":{"identity":{"slaveId":-1,"sourceAddress":{"address":"xxxx:3306\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","port":3306}},"postion":{"gtid":"","included":false,"journalName":"mysql-bin.008610","position":432731132,"serverId":2817172031,"timestamp":1665483624000}}}],"destination":"saas_dev"}

你这sourceAddress看上去序列化有问题，获取一下最新的版本(升级过fastjson)
