### ISSUE TITLE
canal客户端一直连接canal 并打印日志 导致磁盘很快撑爆了 有没有什么参数设置重试次数频率什么的

### ISSUE THREAD

**Issue by kaglobal** [alibaba/canal#4460]
ERROR 170980 --- [l-client-thread] t.j.c.client.client.AbstractCanalClient  : canal client 异常

com.alibaba.otter.canal.protocol.exception.CanalClientException: java.net.ConnectException: Connection refused: connect
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:189)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.connect(SimpleCanalConnector.java:113)
	at top.javatool.canal.client.client.AbstractCanalClient.process(AbstractCanalClient.java:73)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused: connect
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:465)
	at sun.nio.ch.Net.connect(Net.java:457)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:646)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:148)
	... 3 common frames omitted

**Comment by 1774393220** [comment]
解决了，我也遇到了

**Comment by 1774393220** [comment]
解决了吗？

**Comment by Comeonmcl** [comment]
解决了吗 我也遇到了

**Comment by Intvarinit** [comment]
非常奇怪，能接收数据，但是就是报错
