### ISSUE TITLE
在使用canal同步时出现    #alibaba_rds_row_id#__ not matched 异常

### ISSUE THREAD

**Issue by xiaoyaoll** [alibaba/canal#4467]
数据库 :阿里云rds
问题描述: 在使用canal同步时出现    #alibaba_rds_row_id#__ not matched 异常,
                 我们的表在创建时设置了主键,并且大部分的数据都可以成功的从目标库同步到目的库,偶发的会出现上诉问题(两百万条,有是大约350条出现上诉异常,而造成从库数据丢失),不知道如何处理.

建表语句:
![image](https://user-images.githubusercontent.com/43295453/197502959-097882f8-f34d-419e-9be4-e853ed0be3d4.png)

异常提示:
2022-10-19 15:21:25.322 [pool-11-thread-1] ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: Target column: __#alibaba_rds_row_id#__ not matched
java.lang.RuntimeException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: Target column: __#alibaba_rds_row_id#__ not matched
	at com.alibaba.otter.canal.client.adapter.rdb.RdbAdapter.sync(RdbAdapter.java:171) ~[na:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.batchSync(AdapterProcessor.java:139) ~[client-adapter.launcher-1.1.5.jar:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.lambda$null$1(AdapterProcessor.java:97) ~[client-adapter.launcher-1.1.5.jar:na]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:895) ~[na:1.8.0_291]
	at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.lambda$null$2(AdapterProcessor.java:94) ~[client-adapter.launcher-1.1.5.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_291]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_291]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_291]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_291]
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: Target column: __#alibaba_rds_row_id#__ not matched

**Comment by xiaoyaoll** [comment]
![889f406b0782ea57ab765fc583d3f95](https://user-images.githubusercontent.com/43295453/197513586-ae359ab4-ff6c-41fe-baa3-31dec849b8e8.jpg)
这是主库和从库的数量对比图

**Comment by xiaoyaoll** [comment]
通过源码发现,在批量同步时,如果出现异常就会发生回滚,达到重试的阈值后就会丢弃数据.通过排查发现有一张表没有创建主键,因而发生其他正常表数据也会丢失的问题
![2115a57e5e2fc3333cb46b11e11f454](https://user-images.githubusercontent.com/43295453/197763416-d26b04af-1d98-4034-aa28-575465e0b559.jpg)

**Comment by agapple** [comment]
1.  #alibaba_rds_row_id# ，这个是rds的隐藏主键，肯定不是你反馈的表结构
2. sync同步失败，有超时次数定义，可以设置为无穷大，也就是意味着一直重试
