### ISSUE TITLE
canal-adapter application.properties 新增数据源配置 重启adapter 

### ISSUE THREAD

**Issue by aoyousky** [alibaba/canal#4480]
## Question

canal-adapter application.properties 新增数据源配置 ，如下：
srcDataSources:
    defaultDS:
      url: jdbc:mysql://10.0.0.138:3306/hewa_test4?useUnicode=true
      username: hewa_canal
      password: canal
    hewaThirdDS:
        url: jdbc:mysql://10.0.0.138:3306/thirdparty?useUnicode=true
        username: hewa_canal
        password: canal

canalAdapters:
  - instance: hewa # canal instance Name or mq topic name
    groups:
    - groupId: g1
      outerAdapters:
#      - name: logger
      - name: rdb
        key: mysql1
        properties:
          jdbc.driverClassName: com.mysql.cj.jdbc.Driver
          jdbc.url: jdbc:mysql://10.0.0.138:3306/hewa_data_test4?useUnicode=true
          jdbc.username: hewabhvr_canal
          jdbc.password: canal
  - instance: hewa_third_party
      groups:
      - groupId: g3
        outerAdapters:
  #      - name: logger
        - name: rdb
          key: mysql3
          properties:
            jdbc.driverClassName: com.mysql.cj.jdbc.Driver
            jdbc.url: jdbc:mysql://10.0.0.138:3306/hewa_data_test4?useUnicode=true
            jdbc.username: hewabhvr_canal
            jdbc.password: canal

配置rdb文件设置不同适配器时，提示错误：
2022-11-06 15:13:09.501 [Thread-17] ERROR c.a.o.canal.client.adapter.rdb.monitor.RdbConfigMonitor - Outer adapter key not allowed modify
java.lang.RuntimeException: Outer adapter key not allowed modify
        at com.alibaba.otter.canal.client.adapter.rdb.monitor.RdbConfigMonitor$FileListener.onFileChange(RdbConfigMonitor.java:115)
        at org.apache.commons.io.monitor.FileAlterationObserver.doMatch(FileAlterationObserver.java:400)
        at org.apache.commons.io.monitor.FileAlterationObserver.checkAndNotify(FileAlterationObserver.java:334)
        at org.apache.commons.io.monitor.FileAlterationObserver.checkAndNotify(FileAlterationObserver.java:304)
        at org.apache.commons.io.monitor.FileAlterationMonitor.run(FileAlterationMonitor.java:182)
        at java.lang.Thread.run(Thread.java:745)

需要重启客户端canal-adapter服务操作，才能解决，但是我有疑问重启canal-adapter时数据同步会丢失吗？能否保证客户端数据同步不丢失，谢谢。

**Comment by zhang-yuanfu** [comment]
同步不会丢失吧，你重启的是适配器，admin在接收binlog
