### ISSUE TITLE
canal-1.0.25 引用的druid解析 dcl 语句出错 

### ISSUE THREAD

**Issue by wingerx** [alibaba/canal#450]
canal 版本: cannal-1.0.25
druid解析出错信息如下：
`
2017-12-14 14:09:15.304 [destination = example , address = /127.0.0.1:3306 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta - parse faield : CREATE USER 'wingerx'@'%' IDENTIFIED WITH 'mysql_native_password' AS '*6BB4837EB74329105EE4568DDA7DC67ED2CA2AD9'
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'ord' AS '*6BB4837EB74329105EE4568DD', expect AS, actual AS pos 64, line 1, column 62, token AS
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:284) ~[druid-1.1.6.jar:1.1.6]
2017-12-14 14:09:15.309 [destination = example , address = /127.0.0.1:3306 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta - parse faield : ALTER USER 'wingerx'@'%' IDENTIFIED WITH 'mysql_native_password' AS '*6BB4837EB74329105EE4568DDA7DC67ED2CA2AD9'
com.alibaba.druid.sql.parser.ParserException: syntax error, expect PASSWORD, actual IDENTIFIED, pos 31, line 1, column 21, token IDENTIFIED
	at com.alibaba.druid.sql.parser.SQLParser.acceptIdentifier(SQLParser.java:60) ~[druid-1.1.6.jar:1.1.6]
`

**Comment by agapple** [comment]
这个错误暂时不影响，只要不是涉及到表结构变化的DDL解析失败
