### ISSUE TITLE
canal这个报错是什么没搞懂

### ISSUE THREAD

**Issue by zj0078** [alibaba/canal#451]
canal版本  canal.deployer-1.0.23
mysql版本5.7.18-log

对方非要设置log-bin=master-bin并非log_bin=mysql-bin
不知道是不是这个引起，然后报错为

2017-12-14 18:25:40.835 [destination = cmp_source , address = /100.100.30.203:3306 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - prepare to find start position just last position
 {"identity":{"slaveId":-1,"sourceAddress":{"address":"100.100.30.203","port":3306}},"postion":{"included":false,"journalName":"master-bin.000001","position":92307730,"serverId":312,"timestamp":1513246966000}}
2017-12-14 18:25:41.257 [destination = cmp_source , address = /100.100.30.203:3306 , EventParser] WARN  com.taobao.tddl.dbsync.binlog.LogDecoder - Decoding Query failed from: master-bin.000001:92307826
java.io.IOException: Read Q_FLAGS2_CODE error: limit excceed: 71
	at com.taobao.tddl.dbsync.binlog.event.QueryLogEvent.unpackVariables(QueryLogEvent.java:650) ~[canal.parse.dbsync-1.0.23.jar:na]
	at com.taobao.tddl.dbsync.binlog.event.QueryLogEvent.<init>(QueryLogEvent.java:477) ~[canal.parse.dbsync-1.0.23.jar:na]
	at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:154) ~[canal.parse.dbsync-1.0.23.jar:na]
	at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:106) ~[canal.parse.dbsync-1.0.23.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:123) [canal.parse-1.0.23.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209) [canal.parse-1.0.23.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
Caused by: java.lang.IllegalArgumentException: limit excceed: 71
	at com.taobao.tddl.dbsync.binlog.LogBuffer.getUint32(LogBuffer.java:561) ~[canal.parse.dbsync-1.0.23.jar:na]
	at com.taobao.tddl.dbsync.binlog.event.QueryLogEvent.unpackVariables(QueryLogEvent.java:563) ~[canal.parse.dbsync-1.0.23.jar:na]
	... 6 common frames omitted

**Comment by agapple** [comment]
binlog解析错误，升级到1.0.25吧
