### ISSUE TITLE
ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - process error!

### ISSUE THREAD

**Issue by Johnny-Den** [alibaba/canal#4523]
#### 版本信息：
> canal-admin-1.1.5
> canal.deployer-1.1.6
> canal.adapter-1.1.6
> mysql-5.7.38
> elasticsearch-7.10.0

**adapters** 的 application.yml 部分配置信息
``` yml
  canalAdapters:
  - instance: example # canal instance Name or mq topic name
    groups:
    - groupId: g1
      outerAdapters:
      - name: logger
      - name: es7
        hosts: es-cn-***********************.com:9200 # 127.0.0.1:9200 for rest mode
        properties:
          mode: rest # or rest
          security.auth: elastic:************* #  only used for rest mode
          # security.auth: test:test123 #  only used for rest mode
          cluster.name: es-cn-****************
```
一直报如下错误。怀疑是 es 连接或账号问题，但程序连接访问查询 es 是没问题的。
``` log
2022-12-07 13:47:47.492 [main] INFO  org.apache.tomcat.util.net.NioSelectorPool - Using a shared selector for servlet write/read
2022-12-07 13:47:47.506 [main] INFO  o.s.boot.web.embedded.tomcat.TomcatWebServer - Tomcat started on port(s): 8081 (http) with context path ''
2022-12-07 13:47:47.510 [main] INFO  c.a.otter.canal.adapter.launcher.CanalAdapterApplication - Started CanalAdapterApplication in 3.619 seconds (JVM running for 4.102)
2022-12-07 13:47:48.500 [Thread-4] INFO  c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - =============> Start to connect destination: example <=============
2022-12-07 13:47:48.505 [Thread-4] ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - process error!
java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.readNextPacket(SimpleCanalConnector.java:412) ~[na:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.readNextPacket(SimpleCanalConnector.java:397) ~[na:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:155) ~[na:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.connect(SimpleCanalConnector.java:116) ~[na:na]
	at com.alibaba.otter.canal.connector.tcp.consumer.CanalTCPConsumer.connect(CanalTCPConsumer.java:63) ~[na:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.process(AdapterProcessor.java:185) ~[client-adapter.launcher-1.1.6.jar:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_271]
2022-12-07 13:47:49.514 [Thread-4] INFO  c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - =============> Start to connect destination: example <=============
2022-12-07 13:47:49.519 [Thread-4] ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - process error!
java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.readNextPacket(SimpleCanalConnector.java:412) ~[na:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.readNextPacket(SimpleCanalConnector.java:397) ~[na:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:155) ~[na:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.connect(SimpleCanalConnector.java:116) ~[na:na]
	at com.alibaba.otter.canal.connector.tcp.consumer.CanalTCPConsumer.connect(CanalTCPConsumer.java:63) ~[na:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.process(AdapterProcessor.java:185) ~[client-adapter.launcher-1.1.6.jar:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_271]
```

**Comment by cndarren** [comment]
可以看一下 https://github.com/alibaba/canal/issues/4358#issuecomment-1231926368 的评论，通过升级jdk版本可以解决这个问题：
当前出问题使用的jdk版本：jdk1.8
部署之后可行的jdk版本可以升级到：jdk11
