### ISSUE TITLE
aliyun rds  cannel bug

### ISSUE THREAD

**Issue by xunbudaotiantangdemeng** [alibaba/canal#4539]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version  last docker  pull image time 2022-12-19
* mysql version 8  aliyun rds 基础版 SSD云盘

### Issue Description
2022-12-20 10:05:05.336 [destination = example , address = xxxx, EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:237)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:262)
	at java.lang.Thread.run(Thread.java:748)

### Actual behaviour

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by agapple** [comment]
Could not find first log file name in binary log index file，一般是binlog被删除，需要重置位点

**Comment by laurel-he** [comment]
> Could not find first log file name in binary log index file，一般是binlog被删除，需要重置位点

我也遇到了这个问题，多谢回答，我这边原因是测试环境项目构建时每次都会重启mysql服务，bin_log也会被删掉，导致一有人构建代码我的服务就断掉，可以选择把bin_log目录挂载出来，也可以删除canal/conf/example下的meta.dat和h2.mv.db后重启canal以及adapter
