### ISSUE TITLE
Kafka producers keep reporting array out-of-bounds errors

### ISSUE THREAD

**Issue by ipconfiger** [alibaba/canal#4543]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version 1.1.6
* mysql version 2.8.1

### Issue Description
The Canal deployed in 2022-11, in 2022-12-09 The following error appeared in the log：

`2022-12-22 00:15:45.092 [pool-5-thread-2] ERROR c.a.o.canal.connector.kafka.producer.CanalKafkaProducer - 2304
java.lang.ArrayIndexOutOfBoundsException: 2304
	at com.alibaba.fastjson2.JSONWriterUTF8.writeString(JSONWriterUTF8.java:355) ~[fastjson2-2.0.7.jar:na]
	at com.alibaba.fastjson2.writer.ObjectWriterImplMap.write(ObjectWriterImplMap.java:401) ~[fastjson2-2.0.7.jar:na]
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:177) ~[fastjson2-2.0.7.jar:na]
	at com.alibaba.fastjson2.writer.ObjectWriter_8.write(Unknown Source) ~[na:na]
	at com.alibaba.fastjson2.JSON.toJSONBytes(JSON.java:1889) ~[fastjson2-2.0.7.jar:na]
	at com.alibaba.otter.canal.connector.kafka.producer.CanalKafkaProducer.send(CanalKafkaProducer.java:257) ~[na:na]
	at com.alibaba.otter.canal.connector.kafka.producer.CanalKafkaProducer.send(CanalKafkaProducer.java:168) ~[na:na]
	at com.alibaba.otter.canal.server.CanalMQStarter.worker(CanalMQStarter.java:181) [canal.server-1.1.6.jar:na]
	at com.alibaba.otter.canal.server.CanalMQStarter.access$100(CanalMQStarter.java:24) [canal.server-1.1.6.jar:na]
	at com.alibaba.otter.canal.server.CanalMQStarter$CanalMQRunnable.run(CanalMQStarter.java:223) [canal.server-1.1.6.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_352]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_352]
	at java.lang.Thread.run(Thread.java:750) [na:1.8.0_352]`

### Actual behaviour

If there is an exception, please attach the exception trace:

```
2022-12-22 00:15:45.092 [pool-5-thread-2] ERROR c.a.o.canal.connector.kafka.producer.CanalKafkaProducer - 2304
java.lang.ArrayIndexOutOfBoundsException: 2304
	at com.alibaba.fastjson2.JSONWriterUTF8.writeString(JSONWriterUTF8.java:355) ~[fastjson2-2.0.7.jar:na]
	at com.alibaba.fastjson2.writer.ObjectWriterImplMap.write(ObjectWriterImplMap.java:401) ~[fastjson2-2.0.7.jar:na]
	at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:177) ~[fastjson2-2.0.7.jar:na]
	at com.alibaba.fastjson2.writer.ObjectWriter_8.write(Unknown Source) ~[na:na]
	at com.alibaba.fastjson2.JSON.toJSONBytes(JSON.java:1889) ~[fastjson2-2.0.7.jar:na]
	at com.alibaba.otter.canal.connector.kafka.producer.CanalKafkaProducer.send(CanalKafkaProducer.java:257) ~[na:na]
	at com.alibaba.otter.canal.connector.kafka.producer.CanalKafkaProducer.send(CanalKafkaProducer.java:168) ~[na:na]
	at com.alibaba.otter.canal.server.CanalMQStarter.worker(CanalMQStarter.java:181) [canal.server-1.1.6.jar:na]
	at com.alibaba.otter.canal.server.CanalMQStarter.access$100(CanalMQStarter.java:24) [canal.server-1.1.6.jar:na]
	at com.alibaba.otter.canal.server.CanalMQStarter$CanalMQRunnable.run(CanalMQStarter.java:223) [canal.server-1.1.6.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_352]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_352]
	at java.lang.Thread.run(Thread.java:750) [na:1.8.0_352]
```

**Comment by yucong0101** [comment]
我遇到了同样的问题，不知道你是否已经解决，经过测试和查看mq发送设置的时候默认canal.mq.flatMessage是true，传输的是json格式，这个模式需要注意一点，你的mysql表里面有blob之类的二进制数据类型转换json的时候会存在报错的可能，需要对二进制数据进行序列化处理（比如base64编码）。也可以将canal.mq.flatMessage设置为false，这个时候发送的应该是binlog的原格式，可以自行解析myslq日志。
