### ISSUE TITLE
canal-canal-1.1.7-alpha-1版本不支持TLS证书认证

### ISSUE THREAD

**Issue by yunjiangs** [alibaba/canal#4559]
## Why you need it?
因为公司pulsar平台对于认证授权校验比较严格，需要TLS证书认证

## How it could be?

```
@Override
    public void connect() throws CanalClientException {
        // 连接创建客户端
        try {
            pulsarClient = PulsarClient.builder()
                    .serviceUrl(serviceUrl)
                    .authentication(AuthenticationFactory.token(roleToken))
                    .build();
        } catch (PulsarClientException e) {
            throw new RuntimeException(e);
        }
    }
```
关于这段配置无法支持TLS证书认证，运行./startup.sh后日志报错
```
ERROR c.a.o.c.c.pulsarmq.producer.CanalPulsarMQProducer - create producer failed for topic: ucTestTopic
org.apache.pulsar.client.api.PulsarClientException: java.util.concurrent.ExecutionException: org.apache.pulsar.client.api.PulsarClientException: Connection already closed
	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:1027) ~[connector.pulsarmq-1.1.7-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.apache.pulsar.client.impl.ProducerBuilderImpl.create(ProducerBuilderImpl.java:95)
 ```

希望能补充配置如下：
```
        PulsarClient pulsarClient = PulsarClient.builder()
                // 服务接入地址
                .serviceUrl(SERVICE_URL)
                **.enableTls(true)
                .tlsTrustCertsFilePath("/usr/var/pem/xxx.pem")**
                // 授权角色密钥
                .authentication(AuthenticationFactory.token(AUTHENTICATION)).build();
```
```
canal.properties当中增加pulsarmq.tlsTrustCertsFilePath=xxx.pem
```
## Other related information
希望能得到回复，十分感谢！

**Comment by yunjiangs** [comment]
pulsarmq.serverUrl = pulsar://域名:端口 可以正常使用了
pulsarmq.serverUrl = pulsar+ssl://域名:端口 报错
```
2023-01-09 08:56:49.874 [main] INFO  com.alibaba.otter.canal.deployer.CanalStarter - ## the canal server is running now ......
2023-01-09 08:56:50.982 [pulsar-client-io-1-1] WARN  org.apache.pulsar.common.util.SecurityUtility - Unable to get security provider for class org.conscrypt.OpenSSLProvider
java.lang.ClassNotFoundException: org.conscrypt.OpenSSLProvider
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[na:1.8.0_341]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[na:1.8.0_341]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[na:1.8.0_341]
	at com.alibaba.otter.canal.connector.core.spi.URLClassExtensionLoader.loadClass(URLClassExtensionLoader.java:41) ~[connector.core-1.1.7-SNAPSHOT.jar:na]
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_341]
	at java.lang.Class.forName(Class.java:264) ~[na:1.8.0_341]
	at org.apache.pulsar.common.util.SecurityUtility.loadConscryptProvider(SecurityUtility.java:121) [connector.pulsarmq-1.1.7-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.apache.pulsar.common.util.SecurityUtility.<clinit>(SecurityUtility.java:79) [connector.pulsarmq-1.1.7-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.apache.pulsar.client.impl.PulsarChannelInitializer.lambda$new$0(PulsarChannelInitializer.java:95) [connector.pulsarmq-1.1.7-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.apache.pulsar.client.util.ObjectCache.get(ObjectCache.java:48) ~[connector.pulsarmq-1.1.7-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.apache.pulsar.client.impl.PulsarChannelInitializer.lambda$initTls$1(PulsarChannelInitializer.java:140) [connector.pulsarmq-1.1.7-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.apache.pulsar.shade.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[connector.pulsarmq-1.1.7-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.apache.pulsar.shade.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[connector.pulsarmq-1.1.7-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.apache.pulsar.shade.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497) ~[connector.pulsarmq-1.1.7-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.apache.pulsar.shade.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[connector.pulsarmq-1.1.7-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.apache.pulsar.shade.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[connector.pulsarmq-1.1.7-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.apache.pulsar.shade.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[connector.pulsarmq-1.1.7-SNAPSHOT-jar-with-dependencies.jar:na]
	at java.lang.Thread.run(Thread.java:750) ~[na:1.8.0_341]
2023-01-09 08:57:11.244 [pulsar-client-io-1-1] WARN  com.scurrilous.circe.checksum.Crc32cIntChecksum - Failed to load Circe JNI library. Falling back to Java based CRC32c provider
2023-01-09 09:05:58.426 [Thread-6] INFO  com.alibaba.otter.canal.deployer.CanalStarter - ## stop the canal server
2023-01-09 09:05:58.426 [Thread-7] INFO  c.a.o.c.c.pulsarmq.producer.CanalPulsarMQProducer - ## Stop PulsarMQ producer##
2023-01-09 09:05:58.476 [Thread-6] INFO  com.alibaba.otter.canal.deployer.CanalController - ## stop the canal server[10.100.24.153(10.100.24.153):11111]

```

**Comment by agapple** [comment]
可以考虑提交一个PR给我
