### ISSUE TITLE
同步云RDS 5.7.32 时, canal 启动报错 protocol COM_BINLOG_DUMP not supported now

### ISSUE THREAD

**Issue by huaxiaoer** [alibaba/canal#4566]
## 问题
canal 启动报错 "protocol COM_BINLOG_DUMP not supported now". 
请问是不是 mysql server 配置有什么问题? 
### 环境
使用的云RDS MYSQL 版本 5.7.32-log 
mysql binlog 配置: binlog_format: ROW , log_bin: ON

canal 分支 master

## 错误详情
```
2023-01-10 16:48:34.900 [destination = dy , address = xxxx/172.16.0.255:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ERROR ## findAsPerTimestampInSpecificLogFile has an error
java.io.IOException: Received error packet: errno = 1235, sqlstate = 42000 errmsg = ERROR 1235 (42000): protocol COM_BINLOG_DUMP not supported now
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102) ~[canal.parse-1.1.7-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.seek(MysqlConnection.java:150) ~[canal.parse-1.1.7-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findAsPerTimestampInSpecificLogFile(MysqlEventParser.java:767) [canal.parse-1.1.7-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findEndPositionWithMasterIdAndTimestamp(MysqlEventParser.java:384) [canal.parse-1.1.7-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPositionInternal(MysqlEventParser.java:439) [canal.parse-1.1.7-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPosition(MysqlEventParser.java:358) [canal.parse-1.1.7-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:191) [canal.parse-1.1.7-SNAPSHOT.jar:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_201]
```

**Comment by huaxiaoer** [comment]
数据库用户也有文档里提到的权限: SELECT,  REPLICATION SLAVE, REPLICATION CLIENT

**Comment by huaxiaoer** [comment]
云厂商的问题, 和厂商沟通后已经解决

**Comment by ChanneRen** [comment]
> 云厂商的问题, 和厂商沟通后已经解决

请教下 这个最后是什么问题呢？怎么解决的呀？我这边测试也遇到了

**Comment by maben996** [comment]
我这边也遇到了这个问题，请问还有后续吗？

**Comment by ChanneRen** [comment]
这边是因为提供rds的厂商没有开通binlog同步功能，你可以跟你们服务商确认一下发自我的 iPhone在 2023年4月12日，12:13，maben996 ***@***.***> 写道：﻿
我这边也遇到了这个问题，请问还有后续吗？
