### ISSUE TITLE
canalAdmin创建实力成功，但是后台报Name or service not known

### ISSUE THREAD

**Issue by zeyuGitHup** [alibaba/canal#4572]
**主配置**
![image](https://user-images.githubusercontent.com/45196489/212309444-4afc1dde-970e-445d-ad0a-196924e359ee.png)
**节点信息**
![image](https://user-images.githubusercontent.com/45196489/212309310-d8436afe-a3f0-4c29-8ee6-d462dd227a79.png)
**创建实例信息**
![image](https://user-images.githubusercontent.com/45196489/212309591-0856bc89-ee3e-44b3-8c37-fa310c5a24d2.png)
**实例配置信息**
![image](https://user-images.githubusercontent.com/45196489/212309871-371e7c29-09f2-4fa6-8d98-ecb5c6336742.png)

**报错日志**

2023-01-13 19:03:27.055 [canal-instance-scan-0] INFO  c.a.otter.canal.instance.spring.CanalInstanceWithSpring - start CannalInstance for 1-mysql0 
2023-01-13 19:03:27.056 [canal-instance-scan-0] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table filter : ^.*\..*$
2023-01-13 19:03:27.056 [canal-instance-scan-0] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table black filter : ^.*\.BASE TABLE.*$
2023-01-13 19:03:27.058 [canal-instance-scan-0] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - start successful....
2023-01-13 19:03:27.061 [destination = mysql0 , address = /10.244.2.135:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address /10.244.2.135:3306 has an error, retrying. caused by 
com.alibaba.otter.canal.parse.exception.CanalParseException: Unknown host
Caused by: java.net.UnknownHostException: canal-server-1: canal-server-1: Name or service not known
	at java.net.InetAddress.getLocalHost(InetAddress.java:1505) ~[na:1.8.0_181]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.generateUniqueServerId(MysqlEventParser.java:331) ~[canal.parse-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.buildMysqlConnection(MysqlEventParser.java:315) ~[canal.parse-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.buildErosaConnection(MysqlEventParser.java:76) ~[canal.parse-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:170) ~[canal.parse-1.1.6.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
Caused by: java.net.UnknownHostException: canal-server-1: Name or service not known
	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method) ~[na:1.8.0_181]
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928) ~[na:1.8.0_181]
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323) ~[na:1.8.0_181]
	at java.net.InetAddress.getLocalHost(InetAddress.java:1500) ~[na:1.8.0_181]
	... 5 common frames omitted
2023-01-13 19:03:27.061 [destination = mysql0 , address = /10.244.2.135:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:mysql0[com.alibaba.otter.canal.parse.exception.CanalParseException: Unknown host
Caused by: java.net.UnknownHostException: canal-server-1: canal-server-1: Name or service not known
	at java.net.InetAddress.getLocalHost(InetAddress.java:1505)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.generateUniqueServerId(MysqlEventParser.java:331)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.buildMysqlConnection(MysqlEventParser.java:315)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.buildErosaConnection(MysqlEventParser.java:76)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:170)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.UnknownHostException: canal-server-1: Name or service not known
	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1500)
	... 5 more
]

实例就配置IP地址，用户和密码，其他都是默认配置，IP地址试过配置IP地址和域名都不行

**Comment by zeyuGitHup** [comment]
canal组件版本1.1.6

**Comment by agapple** [comment]
在canal-server机器上，检查下hostname -i，需要确保本机的serviceName和本机ip绑定

**Comment by shiminyu-patsnap** [comment]
@zeyuGitHup 大佬, 我遇到了和你一样的问题, 同1.1.6版本, 同样的Caused by: java.net.UnknownHostException: canal-server-0: canal-server-0: Name or service not known,  我在server的容器内去ping canal-server-0是能通的, 唯一可能不同的是当宿主机是银河麒麟v10,  容器内hostname和hosts如下  @agapple 大佬也帮忙看看是不是哪里不对,  当前canal-server-0是解析到10.42.0.240, 没问题
 [root@canal-server-0 admin]# hostname -i
10.42.0.240
[root@canal-server-0 admin]# cat /etc/hosts
# Kubernetes-managed hosts file.
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
fe00::0 ip6-mcastprefix
fe00::1 ip6-allnodes
fe00::2 ip6-allrouters
10.42.0.240 canal-server-0.innop-canal-server canal-server-0.innop-canal-server.default.svc.cluster.local canal-server-0

**Comment by zhangliangrr** [comment]
@shiminyu-patsnap 解决了吗？我也遇到了同样 问题，麒麟V10系统，之前centos系统没有问题
