### ISSUE TITLE
1.1.7-SNAPSHOT NPE

### ISSUE THREAD

**Issue by tangtangsara** [alibaba/canal#4573]
dump address *****/*****:3306 has an error, retrying. caused by com.alibaba.otter.canal.parse.exception.CanalParseException: java.lang.NullPointerException
           Caused by: java.lang.NullPointerException
           at com.taobao.tddl.dbsync.binlog.event.GtidLogEvent.getLastCommitted(GtidLogEvent.java:80)
           at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseGTIDLogEvent(LogEventConvert.java:178)
           at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:132)
           at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:303)
           at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:251)
           at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168)
           at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125)
           at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
           at java.util.concurrent.FutureTask.run(FutureTask.java:266)
           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
           at java.lang.Thread.run(Thread.java:748)

**Comment by agapple** [comment]
最新版已修复
