### ISSUE TITLE
在java openjdk1.8环境下运行报错

### ISSUE THREAD

**Issue by lxg07254698** [alibaba/canal#4601]
2023-02-13 17:12:05.114 [Thread-4] INFO  c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - =============> Start to connect destination: example2 <=============
2023-02-13 17:12:05.148 [Thread-4] ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - process error!
java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.readNextPacket(SimpleCanalConnector.java:412) ~[na:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.readNextPacket(SimpleCanalConnector.java:397) ~[na:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:155) ~[na:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.connect(SimpleCanalConnector.java:116) ~[na:na]
	at com.alibaba.otter.canal.connector.tcp.consumer.CanalTCPConsumer.connect(CanalTCPConsumer.java:63) ~[na:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.process(AdapterProcessor.java:185) ~[client-adapter.launcher-1.1.6.jar:na]
	at java.lang.Thread.run(Thread.java:750) ~[na:1.8.0_362]

**Comment by cndarren** [comment]
可以看一下 https://github.com/alibaba/canal/issues/4358#issuecomment-1231926368 的评论，通过升级jdk版本可以解决这个问题：
当前出问题使用的jdk版本：jdk1.8
部署之后可行的jdk版本可以升级到：jdk11

**Comment by lxg07254698** [comment]
可是不是只要版本是1.8及以上都可以吗

**Comment by lxg07254698** [comment]
我先试试，谢谢大佬了
