### ISSUE TITLE
canal-adapter  ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - process error!  Connection refused: connect

### ISSUE THREAD

**Issue by sheng91666** [alibaba/canal#4607]
canal-adapter 日志一直报这个错
`2023-02-16 16:59:10.759 [main] INFO  c.a.o.canal.adapter.launcher.loader.CanalAdapterService - ## syncSwitch refreshed.
2023-02-16 16:59:10.759 [main] INFO  c.a.o.canal.adapter.launcher.loader.CanalAdapterService - ## start the canal client adapters.
2023-02-16 16:59:10.763 [main] INFO  c.a.otter.canal.client.adapter.support.ExtensionLoader - extension classpath dir: D:\canal1.1.6\canal.adapter-1.1.6\plugin
2023-02-16 16:59:10.804 [main] INFO  c.a.o.canal.adapter.launcher.loader.CanalAdapterLoader - Load canal adapter: logger succeed
2023-02-16 16:59:10.977 [main] INFO  c.a.o.c.client.adapter.es.core.config.ESSyncConfigLoader - ## Start loading es mapping config ...
2023-02-16 16:59:11.039 [main] INFO  c.a.o.c.client.adapter.es.core.config.ESSyncConfigLoader - ## ES mapping config loaded
2023-02-16 16:59:11.397 [main] INFO  c.a.o.canal.adapter.launcher.loader.CanalAdapterLoader - Load canal adapter: es7 succeed
2023-02-16 16:59:11.404 [main] INFO  c.alibaba.otter.canal.connector.core.spi.ExtensionLoader - extension classpath dir: D:\canal1.1.6\canal.adapter-1.1.6\plugin
2023-02-16 16:59:11.425 [main] INFO  c.a.o.canal.adapter.launcher.loader.CanalAdapterLoader - Start adapter for canal-client mq topic: example-g1 succeed
2023-02-16 16:59:11.426 [main] INFO  c.a.o.canal.adapter.launcher.loader.CanalAdapterService - ## the canal client adapters are running now ......
2023-02-16 16:59:11.426 [Thread-4] INFO  c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - =============> Start to connect destination: example <=============
2023-02-16 16:59:11.432 [main] INFO  org.apache.coyote.http11.Http11NioProtocol - Starting ProtocolHandler ["http-nio-8081"]
2023-02-16 16:59:11.435 [main] INFO  org.apache.tomcat.util.net.NioSelectorPool - Using a shared selector for servlet write/read
2023-02-16 16:59:11.449 [main] INFO  o.s.boot.web.embedded.tomcat.TomcatWebServer - Tomcat started on port(s): 8081 (http) with context path ''
2023-02-16 16:59:11.451 [main] INFO  c.a.otter.canal.adapter.launcher.CanalAdapterApplication - Started CanalAdapterApplication in 6.107 seconds (JVM running for 7.081)
2023-02-16 16:59:13.463 [Thread-4] ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - process error!
com.alibaba.otter.canal.protocol.exception.CanalClientException: java.net.ConnectException: Connection refused: connect
        at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:200) ~[na:na]
        at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.connect(SimpleCanalConnector.java:116) ~[na:na]
        at com.alibaba.otter.canal.connector.tcp.consumer.CanalTCPConsumer.connect(CanalTCPConsumer.java:63) ~[na:na]
        at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.process(AdapterProcessor.java:185) ~[client-adapter.launcher-1.1.6.jar:na]
        at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_121]
Caused by: java.net.ConnectException: Connection refused: connect
        at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_121]
        at sun.nio.ch.Net.connect(Unknown Source) ~[na:1.8.0_121]
        at sun.nio.ch.Net.connect(Unknown Source) ~[na:1.8.0_121]
        at sun.nio.ch.SocketChannelImpl.connect(Unknown Source) ~[na:1.8.0_121]
        at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:152) ~[na:na]
        ... 4 common frames omitted
2023-02-16 16:59:14.474 [Thread-4] INFO  c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - =============> Start to connect destination: example <=============
2023-02-16 16:59:16.493 [Thread-4] ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - process error!
com.alibaba.otter.canal.protocol.exception.CanalClientException: java.net.ConnectException: Connection refused: connect
        at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:200) ~[na:na]
        at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.connect(SimpleCanalConnector.java:116) ~[na:na]
        at com.alibaba.otter.canal.connector.tcp.consumer.CanalTCPConsumer.connect(CanalTCPConsumer.java:63) ~[na:na]
        at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.process(AdapterProcessor.java:185) ~[client-adapter.launcher-1.1.6.jar:na]
        at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_121]
Caused by: java.net.ConnectException: Connection refused: connect
        at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_121]
        at sun.nio.ch.Net.connect(Unknown Source) ~[na:1.8.0_121]
        at sun.nio.ch.Net.connect(Unknown Source) ~[na:1.8.0_121]
        at sun.nio.ch.SocketChannelImpl.connect(Unknown Source) ~[na:1.8.0_121]
        at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:152) ~[na:na]
        ... 4 common frames omitted`

**Comment by sheng91666** [comment]
`server:
  port: 8081
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

canal.conf:
  mode: tcp #tcp kafka rocketMQ rabbitMQ
  flatMessage: true
  zookeeperHosts:
  syncBatchSize: 1000
  retries: 0
  timeout:
  accessKey:
  secretKey:
  consumerProperties:
    # canal tcp consumer
    canal.tcp.server.host: 127.0.0.1:11111
    canal.tcp.zookeeper.hosts:
    canal.tcp.batch.size: 500
    canal.tcp.username:
    canal.tcp.password:
  srcDataSources:
    defaultDS:
      url: jdbc:mysql://写的正确的?useUnicode=true
      username: root
      password: 写的正确的
  canalAdapters:
  - instance: example # canal instance Name or mq topic name
    groups:
    - groupId: g1
      outerAdapters:
      - name: logger
      - name: es7
        hosts: http://127.0.0.1:9200 # 127.0.0.1:9200 for rest mode
        properties:
          mode: rest #transport # or rest
          cluster.name: elasticsearch
          security.auth: elastic: elastic #es，没有设置密码`

**Comment by guojianming** [comment]
canal service 有启动吗

**Comment by sheng91666** [comment]
启动好了&nbsp; &nbsp;，适配器也启动好了
&nbsp;


蔡盛
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月25日(星期六) 上午9:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/canal] canal-adapter  ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - process error!  Connection refused: connect (Issue #4607)





 
canal service 有启动吗

**Comment by liaoxun** [comment]
请问你解决了吗 我也遇到这个问题

**Comment by sheng91666** [comment]
解决了
&nbsp;


蔡盛
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月11日(星期二) 下午2:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/canal] canal-adapter  ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - process error!  Connection refused: connect (Issue #4607)





 
请问你解决了吗 我也遇到这个问题

**Comment by 1774393220** [comment]
怎么解决的？
