### ISSUE TITLE
canal解析数据异常

### ISSUE THREAD

**Issue by qinwenxu** [alibaba/canal#4608]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version   1.1.4
* mysql version  5.6

### Issue Description
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: java.lang.NegativeArraySizeException: null
	at com.google.protobuf.ByteString$CodedBuilder.<init>(ByteString.java:1131) ~[protobuf-java-3.6.1.jar:na]
	at com.google.protobuf.ByteString$CodedBuilder.<init>(ByteString.java:1126) ~[protobuf-java-3.6.1.jar:na]
	at com.google.protobuf.ByteString.newCodedBuilder(ByteString.java:1122) ~[protobuf-java-3.6.1.jar:na]
	at com.google.protobuf.AbstractMessageLite.toByteString(AbstractMessageLite.java:59) ~[protobuf-java-3.6.1.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseRowsEvent(LogEventConvert.java:570) ~[canal.parse-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$DmlParserStage.onEvent(MysqlMultiStageCoprocessor.java:330) ~[canal.parse-1.1.4.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$DmlParserStage.onEvent(MysqlMultiStageCoprocessor.java:316) ~[canal.parse-1.1.4.jar:na]
	at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) ~[disruptor-3.4.2.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_242]
	at java.lang.Thread.run(Thread.java:775) ~[na:1.8.0_242]

### Actual behaviour

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by agapple** [comment]
这个版本有点老，优先考虑升级下吧
