### ISSUE TITLE
改动destination的配置文件，结果整个Canal进程都退出了，按理不是该重启吗？

### ISSUE THREAD

**Issue by zhibinliu** [alibaba/canal#461]
各位好，

我用的是1.0.24，canal deployer。
主要配置：
canal.destinations= example
canal.conf.dir = ../conf
canal.auto.scan = true
canal.auto.scan.interval = 5

canal.instance.global.mode = spring 
canal.instance.global.lazy = false
canal.instance.global.spring.xml = classpath:spring/default-instance.xml

————————————————————
然后我试着改动example/instance.properties，在black.regex中加了点东西，看到整个Canal都退出了。简单看了一下代码也没想明白为什么没重启example。

logs/example/example.log：
2017-12-20 15:31:15.241 [canal-instance-scan-0] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - stop CannalInstance for null-example 
2017-12-20 15:31:15.241 [canal-instance-scan-0] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - disConnect MysqlConnection to edc0.ecloud.com/132.122.1.162:6606...
2017-12-20 15:31:15.246 [destination = example , address = /132.122.1.162:6606 , EventParser] INFO  c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - I/O interrupted while reading from client socket
java.nio.channels.ClosedByInterruptException: null
        at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202) ~[na:1.8.0_66]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:407) ~[na:1.8.0_66]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:154) ~[canal.parse-1.0.24.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:70) ~[canal.parse-1.0.24.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:122) [canal.parse-1.0.24.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:222) [canal.parse-1.0.24.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66]
2017-12-20 15:31:15.246 [destination = example , address = /132.122.1.162:6606 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - the channel edc0.ecloud.com/132.122.1.162:6606 is not connected
2017-12-20 15:31:15.246 [destination = example , address = /132.122.1.162:6606 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - disConnect MysqlConnection to edc0.ecloud.com/132.122.1.162:6606...
2017-12-20 15:31:15.247 [destination = example , address = /132.122.1.162:6606 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - connect MysqlConnection to edc0.ecloud.com/132.122.1.162:6606...
2017-12-20 15:31:15.247 [destination = example , address = /132.122.1.162:6606 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - handshake initialization packet received, prepare the client authentication packet to send
2017-12-20 15:31:15.248 [destination = example , address = /132.122.1.162:6606 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - client authentication packet is sent out.
2017-12-20 15:31:15.248 [destination = example , address = /132.122.1.162:6606 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - disConnect MysqlConnection to edc0.ecloud.com/132.122.1.162:6606...
2017-12-20 15:31:15.249 [canal-instance-scan-0] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - stop successful....
2017-12-20 15:31:15.249 [canal-instance-scan-0] INFO  c.a.otter.canal.server.embedded.CanalServerWithEmbedded - stop CanalInstances[example] successfully

logs/canal/canal.log：
2017-12-20 15:14:05.117 [main] INFO  com.alibaba.otter.canal.deployer.CanalLauncher - ## the canal server is running now .....
.
2017-12-20 15:31:15.250 [Thread-4] INFO  com.alibaba.otter.canal.deployer.CanalLauncher - ## stop the canal server
2017-12-20 15:31:15.254 [Thread-4] INFO  com.alibaba.otter.canal.deployer.CanalController - ## stop the canal server[132.122.1
.162:11111]
2017-12-20 15:31:15.254 [Thread-4] INFO  com.alibaba.otter.canal.deployer.CanalLauncher - ## canal server is down.

怎么关闭example这个Destination，就导致了JVM的退出呢？求指教，谢谢！

**Comment by zhibinliu** [comment]
canal.pid 文件还在

**Comment by zhibinliu** [comment]
Sorry,我把canalServer的启停给注释掉了，恢复回来就好了……
