### ISSUE TITLE
canal1.1.5 对接MariaDB-10.5.11启动canal server报错空指针

### ISSUE THREAD

**Issue by maketubu7** [alibaba/canal#4629]
canal.properties
>      
      canal.register.ip =
      canal.port = 11111
      canal.admin.port = 11110
      canal.admin.user = admin
      canal.admin.passwd = 4ACFE3202A5FF5CF467898FC58AAB1D615029441
      canal.withoutNetty = false
      canal.serverMode = tcp
      canal.file.data.dir = ${canal.conf.dir}
      canal.file.flush.period = 1000
      canal.instance.memory.buffer.size = 16384
      canal.instance.memory.buffer.memunit = 1024
      canal.instance.memory.batch.mode = MEMSIZE
      canal.instance.memory.rawEntry = true
      canal.instance.detecting.enable = false
      canal.instance.detecting.sql = select 1
      canal.instance.detecting.interval.time = 3
      canal.instance.detecting.retry.threshold = 3
      canal.instance.detecting.heartbeatHaEnable = false
      canal.instance.transaction.size =  1024
      canal.instance.fallbackIntervalInSeconds = 60
      canal.instance.network.receiveBufferSize = 16384
      canal.instance.network.sendBufferSize = 16384
      canal.instance.network.soTimeout = 30
      canal.instance.filter.druid.ddl = true
      canal.instance.filter.query.dcl = true
      canal.instance.filter.query.dml = true
      canal.instance.filter.query.ddl = true
      canal.instance.filter.table.error = true
      canal.instance.filter.rows = false
      canal.instance.filter.transaction.entry = true
      canal.instance.filter.dml.insert = false
      canal.instance.filter.dml.update = false
      canal.instance.filter.dml.delete = false
      canal.instance.binlog.format = ROW,STATEMENT,MIXED
      canal.instance.binlog.image = FULL,MINIMAL,NOBLOB
      canal.instance.get.ddl.isolation = false
      canal.instance.parser.parallel = true
      canal.instance.parser.parallelBufferSize = 256
      canal.instance.tsdb.enable = false
      canal.instance.tsdb.dir = ${canal.file.data.dir:../conf}/${canal.instance.destination:}
      canal.instance.tsdb.url = jdbc:h2:${canal.instance.tsdb.dir}/h2;CACHE_SIZE=1000;MODE=MYSQL;
      canal.instance.tsdb.dbUsername = canal
      canal.instance.tsdb.dbPassword = canal
      canal.instance.tsdb.snapshot.interval = 24
      canal.instance.tsdb.snapshot.expire = 360
      canal.destinations = example
      canal.conf.dir = ../conf
      canal.auto.scan = true
      canal.auto.scan.interval = 5
      canal.auto.reset.latest.pos.mode = true
      canal.instance.tsdb.spring.xml = classpath:spring/tsdb/h2-tsdb.xml
      canal.instance.global.mode = spring
      canal.instance.global.lazy = false
      canal.instance.global.manager.address = ${canal.admin.manager}
      canal.instance.global.spring.xml = classpath:spring/file-instance.xml

example-instance.properties
     

> 
      canal.instance.gtidon=false
      canal.instance.master.address=mariadb.openstack.svc.cluster.local:3306
      canal.instance.master.position=
      canal.instance.tsdb.enable=true
      canal.instance.dbUsername=root
      canal.instance.dbPassword=database_sugon
      canal.instance.connectionCharset = UTF-8
      canal.instance.enableDruid=false
      canal.instance.filter.regex=canal_data_sync\\..*
      canal.instance.filter.black.regex=mysql\\.slave_.*

example.log

`2023-03-02 12:48:31.176 [destination = example , address = mariadb.openstack.svc.cluster.local/192.168.241.188:3306 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta - parse faield : CREATE TABLE `time_zone_name` (
  `Name` char(64) NOT NULL,
  `Time_zone_id` int(10) unsigned NOT NULL,
  PRIMARY KEY (`Name`)
) ENGINE=Aria DEFAULT CHARSET=utf8 PAGE_CHECKSUM=1 TRANSACTIONAL=1 COMMENT='Time zone names'
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'CHARSET=utf8 PAGE_CHECKSUM=1 TRANSACTIONAL=, pos 175, line 5, column 50, token IDENTIFIER PAGE_CHECKSUM
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:576) ~[druid-1.2.6.jar:1.2.6]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:602) ~[druid-1.2.6.jar:1.2.6]
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:565) ~[druid-1.2.6.jar:1.2.6]
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:587) ~[druid-1.2.6.jar:1.2.6]
	at com.alibaba.druid.sql.repository.SchemaRepository.console(SchemaRepository.java:445) ~[druid-1.2.6.jar:1.2.6]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta.apply(MemoryTableMeta.java:84) ~[canal.parse-1.1.5.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.dumpTableMeta(DatabaseTableMeta.java:225) [canal.parse-1.1.5.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:173) [canal.parse-1.1.5.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:142) [canal.parse-1.1.5.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:197) [canal.parse-1.1.5.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
2023-03-02 12:48:31.176 [destination = example , address = mariadb.openstack.svc.cluster.local/192.168.241.188:3306 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta - parse faield : CREATE TABLE `time_zone_transition` (
  `Time_zone_id` int(10) unsigned NOT NULL,
  `Transition_time` bigint(20) NOT NULL,
  `Transition_type_id` int(10) unsigned NOT NULL,
  PRIMARY KEY (`Time_zone_id`,`Transition_time`)
) ENGINE=Aria DEFAULT CHARSET=utf8 PAGE_CHECKSUM=1 TRANSACTIONAL=1 COMMENT='Time zone transitions'
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'CHARSET=utf8 PAGE_CHECKSUM=1 TRANSACTIONAL=, pos 270, line 6, column 50, token IDENTIFIER PAGE_CHECKSUM
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:576) ~[druid-1.2.6.jar:1.2.6]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:602) ~[druid-1.2.6.jar:1.2.6]
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:565) ~[druid-1.2.6.jar:1.2.6]
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:587) ~[druid-1.2.6.jar:1.2.6]
	at com.alibaba.druid.sql.repository.SchemaRepository.console(SchemaRepository.java:445) ~[druid-1.2.6.jar:1.2.6]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta.apply(MemoryTableMeta.java:84) ~[canal.parse-1.1.5.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.dumpTableMeta(DatabaseTableMeta.java:225) [canal.parse-1.1.5.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:173) [canal.parse-1.1.5.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:142) [canal.parse-1.1.5.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:197) [canal.parse-1.1.5.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
2023-03-02 12:48:31.176 [destination = example , address = mariadb.openstack.svc.cluster.local/192.168.241.188:3306 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta - parse faield : CREATE TABLE `time_zone_transition_type` (
  `Time_zone_id` int(10) unsigned NOT NULL,
  `Transition_type_id` int(10) unsigned NOT NULL,
  `Offset` int(11) NOT NULL DEFAULT 0,
  `Is_DST` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `Abbreviation` char(8) NOT NULL DEFAULT '',
  PRIMARY KEY (`Time_zone_id`,`Transition_type_id`)
) ENGINE=Aria DEFAULT CHARSET=utf8 PAGE_CHECKSUM=1 TRANSACTIONAL=1 COMMENT='Time zone transition types'
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'CHARSET=utf8 PAGE_CHECKSUM=1 TRANSACTIONAL=, pos 373, line 8, column 50, token IDENTIFIER PAGE_CHECKSUM
	at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:576) ~[druid-1.2.6.jar:1.2.6]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:602) ~[druid-1.2.6.jar:1.2.6]
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:565) ~[druid-1.2.6.jar:1.2.6]
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:587) ~[druid-1.2.6.jar:1.2.6]
	at com.alibaba.druid.sql.repository.SchemaRepository.console(SchemaRepository.java:445) ~[druid-1.2.6.jar:1.2.6]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta.apply(MemoryTableMeta.java:84) ~[canal.parse-1.1.5.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.dumpTableMeta(DatabaseTableMeta.java:225) [canal.parse-1.1.5.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:173) [canal.parse-1.1.5.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:142) [canal.parse-1.1.5.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:197) [canal.parse-1.1.5.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
2023-03-02 12:48:31.369 [destination = example , address = mariadb.openstack.svc.cluster.local/192.168.241.188:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address mariadb.openstack.svc.cluster.local/192.168.241.188:3306 has an error, retrying. caused by 
java.lang.NullPointerException: null
	at com.alibaba.druid.sql.visitor.SQLASTOutputVisitor.visit(SQLASTOutputVisitor.java:5298) ~[druid-1.2.6.jar:1.2.6]
	at com.alibaba.druid.sql.ast.statement.SQLCheck.accept0(SQLCheck.java:49) ~[druid-1.2.6.jar:1.2.6]
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:49) ~[druid-1.2.6.jar:1.2.6]
	at com.alibaba.druid.sql.visitor.SQLASTOutputVisitor.printTableElements(SQLASTOutputVisitor.java:3493) ~[druid-1.2.6.jar:1.2.6]
	at com.alibaba.druid.sql.visitor.SQLASTOutputVisitor.visit(SQLASTOutputVisitor.java:9390) ~[druid-1.2.6.jar:1.2.6]
	at com.alibaba.druid.sql.dialect.mysql.ast.statement.MySqlCreateTableStatement.accept0(MySqlCreateTableStatement.java:125) ~[druid-1.2.6.jar:1.2.6]
	at com.alibaba.druid.sql.dialect.mysql.ast.statement.MySqlCreateTableStatement.accept0(MySqlCreateTableStatement.java:85) ~[druid-1.2.6.jar:1.2.6]
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:49) ~[druid-1.2.6.jar:1.2.6]
	at com.alibaba.druid.sql.ast.SQLObjectImpl.output(SQLObjectImpl.java:90) ~[druid-1.2.6.jar:1.2.6]
	at com.alibaba.druid.sql.ast.SQLObjectImpl.output(SQLObjectImpl.java:75) ~[druid-1.2.6.jar:1.2.6]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta.snapshot(MemoryTableMeta.java:151) ~[canal.parse-1.1.5.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.applySnapshotToDB(DatabaseTableMeta.java:290) ~[canal.parse-1.1.5.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:175) ~[canal.parse-1.1.5.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:142) ~[canal.parse-1.1.5.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:197) ~[canal.parse-1.1.5.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
2023-03-02 12:48:31.370 [destination = example , address = mariadb.openstack.svc.cluster.local/192.168.241.188:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[java.lang.NullPointerException
	at com.alibaba.druid.sql.visitor.SQLASTOutputVisitor.visit(SQLASTOutputVisitor.java:5298)
	at com.alibaba.druid.sql.ast.statement.SQLCheck.accept0(SQLCheck.java:49)
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:49)
	at com.alibaba.druid.sql.visitor.SQLASTOutputVisitor.printTableElements(SQLASTOutputVisitor.java:3493)
	at com.alibaba.druid.sql.visitor.SQLASTOutputVisitor.visit(SQLASTOutputVisitor.java:9390)
	at com.alibaba.druid.sql.dialect.mysql.ast.statement.MySqlCreateTableStatement.accept0(MySqlCreateTableStatement.java:125)
	at com.alibaba.druid.sql.dialect.mysql.ast.statement.MySqlCreateTableStatement.accept0(MySqlCreateTableStatement.java:85)
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:49)
	at com.alibaba.druid.sql.ast.SQLObjectImpl.output(SQLObjectImpl.java:90)
	at com.alibaba.druid.sql.ast.SQLObjectImpl.output(SQLObjectImpl.java:75)
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta.snapshot(MemoryTableMeta.java:151)
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.applySnapshotToDB(DatabaseTableMeta.java:290)
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:175)
	at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:142)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:197)
	at java.lang.Thread.run(Thread.java:748)`

请问我需要配置额外的参数吗

**Comment by agapple** [comment]
```
CREATE TABLE time_zone_transition(Time_zone_idint(10) unsigned NOT NULL,Transition_timebigint(20) NOT NULL,Transition_type_id int(10) unsigned NOT NULL, PRIMARY KEY (Time_zone_id,Transition_time) ) ENGINE=Aria DEFAULT CHARSET=utf8 PAGE_CHECKSUM=1 TRANSACTIONAL=1 COMMENT='Time zone transitions' 
```

忽略下这张表的订阅
