### ISSUE TITLE
1.1.7版本deployer配置Mysql后启动报alibaba.druid出错

### ISSUE THREAD

**Issue by youthv** [alibaba/canal#4633]
版本：canal.deployer-1.1.7
配置：Mysql8.0源
依照教程完整无误，运行startup.sh出错。
[destination = fssk , address = /10.100.0.111:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address /10.100.0.111:3306 has an error, retrying. caused by 
java.lang.NullPointerException: null
        at com.alibaba.druid.sql.visitor.SQLASTOutputVisitor.visit(SQLASTOutputVisitor.java:5440) ~[druid-1.2.15.jar:na]
        at com.alibaba.druid.sql.ast.statement.SQLCheck.accept0(SQLCheck.java:47) ~[druid-1.2.15.jar:na]
        at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:48) ~[druid-1.2.15.jar:na]
        at com.alibaba.druid.sql.visitor.SQLASTOutputVisitor.printTableElements(SQLASTOutputVisitor.java:3566) ~[druid-1.2.15.jar:na]
        at com.alibaba.druid.sql.visitor.SQLASTOutputVisitor.visit(SQLASTOutputVisitor.java:9628) ~[druid-1.2.15.jar:na]
        at com.alibaba.druid.sql.dialect.mysql.ast.statement.MySqlCreateTableStatement.accept0(MySqlCreateTableStatement.java:133) ~[druid-1.2.15.jar:na]
        at com.alibaba.druid.sql.dialect.mysql.ast.statement.MySqlCreateTableStatement.accept0(MySqlCreateTableStatement.java:93) ~[druid-1.2.15.jar:na]
        at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:48) ~[druid-1.2.15.jar:na]
        at com.alibaba.druid.sql.ast.SQLObjectImpl.output(SQLObjectImpl.java:89) ~[druid-1.2.15.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta.snapshot(MemoryTableMeta.java:152) ~[canal.parse-1.1.7-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.applySnapshotToDB(DatabaseTableMeta.java:303) ~[canal.parse-1.1.7-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:176) ~[canal.parse-1.1.7-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:142) ~[canal.parse-1.1.7-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:197) ~[canal.parse-1.1.7-SNAPSHOT.jar:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_231]

**Comment by agapple** [comment]
提供下更完整的复现步骤：mysql版本、测试表、以及数据sql

**Comment by agapple** [comment]
提供下更完整的复现步骤：mysql版本、测试表、以及数据sql
