### ISSUE TITLE
canal同步出现死锁问题

### ISSUE THREAD

**Issue by liuwenfeng554** [alibaba/canal#465]
怎么处理死锁？
2017-12-25 14:18:54,295 (main) [INFO - com.trcloud.hamal.stream.core.operator.impl.sink.GPSinkOperator.processAutoCommit(GPSinkOperator.java:138)] current sql is: INSERT INTO ods_fina_bj.account_user("account_type","balance","bank_frozen","create_date","cust_no","del_flag","id","local_frozen","parent_id","remarks","update_date","user_id","storm_time", "etl_time") VALUES('1','0.0','0.0','2017-12-25 14:18:26','201712251418330723046283','0','8a32f14f815a40f5868ba7f0c8286cfe','0.0',null,'DTS借款人开户','2017-12-25 14:18:26','C33DBA5ADEB0415DBC4AE36CA3B66E9B','2017-12-25 14:18:26', '2017-12-25 14:18:37');
2017-12-25 14:19:04,297 (main) [ERROR - com.trcloud.hamal.stream.core.operator.impl.sink.GPSinkOperator.processAutoCommit(GPSinkOperator.java:159)] exec sql one by one failed: 
org.postgresql.util.PSQLException: ERROR: deadlock detected
  Detail: Process 71574 waits for RowExclusiveLock on relation 2388238 of database 23968; blocked by process 24634.
Process 24634 waits for ExclusiveLock on relation 2388316 of database 23968; blocked by process 59646.
Process 59646 waits for RowExclusiveLock on relation 2388238 of database 23968; blocked by process 35132.
Process 35132 waits for ExclusiveLock on relation 2388238 of database 23968; blocked by process 71574.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2182)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1911)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:173)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:622)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:458)
	at org.postgresql.jdbc.PgStatement.executeUpdate(PgStatement.java:406)
	at com.zaxxer.hikari.pool.ProxyStatement.executeUpdate(ProxyStatement.java:120)
	at com.zaxxer.hikari.pool.HikariProxyStatement.executeUpdate(HikariProxyStatement.java)
	at com.trcloud.hamal.stream.core.operator.impl.sink.GPSinkOperator.processAutoCommit(GPSinkOperator.java:139)
	at com.trcloud.hamal.stream.core.operator.impl.sink.GPSinkOperator.process(GPSinkOperator.java:92)
	at com.trcloud.hamal.stream.core.operator.impl.canal.CanalOperatorChain.start(CanalOperatorChain.java:49)
	at com.trcloud.hamal.stream.core.StreamJob.start(StreamJob.java:121)
	at com.trcloud.hamal.stream.core.JobRunner.main(JobRunner.java:46)

**Comment by wingerx** [comment]
这不是原生canal支持的吧？看报错应该是扩展抽取pg数据出现的问题...

**Comment by liuwenfeng554** [comment]
canal 有没有办法规避或解决这个问题？

**Comment by liuwenfeng554** [comment]
@wingerx
