### ISSUE TITLE
数组越界

### ISSUE THREAD

**Issue by reversemingyuc** [alibaba/canal#4691]
## Question

2023-04-21 16:22:38.733 [destination = TTDs1 , address = /10.1.11.247:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:TTDs1[com.alibaba.otter.canal.parse.exception.CanalParseException: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: java.lang.ArrayIndexOutOfBoundsException: 101
	at com.taobao.tddl.dbsync.binlog.LogBuffer.getBigDecimalCompact(LogBuffer.java:1397)
	at com.taobao.tddl.dbsync.binlog.LogBuffer.getDecimal(LogBuffer.java:1311)
	at com.taobao.tddl.dbsync.binlog.event.RowsLogBuffer.fetchValue(RowsLogBuffer.java:375)
	at com.taobao.tddl.dbsync.binlog.event.RowsLogBuffer.nextValue(RowsLogBuffer.java:132)
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseOneRow(LogEventConvert.java:753)
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseRowsEvent(LogEventConvert.java:567)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$DmlParserStage.onEvent(MysqlMultiStageCoprocessor.java:341)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$DmlParserStage.onEvent(MysqlMultiStageCoprocessor.java:327)
	at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
然后我看了下binlog的position已经远远大于canal的了 不知道是有缓存还是什么，不管修改meta.dat还是instance.properties，admin上重启instance，position位置还是没变

**Comment by reversemingyuc** [comment]
已解决 代码问题，跳过了 connector.ack(batchId);

**Comment by IE90** [comment]
兄弟，你的问题解决了嘛

**Comment by reversemingyuc** [comment]
> 兄弟，你的问题解决了嘛

我是降成1.6就没问题了

**Comment by agapple** [comment]
deciaml compact优化问题，代码已回滚修复
