### ISSUE TITLE
关于启动deployer启动报错问题Proxy does not support such usage yet: Do not support global set, sqlState=HY000, sqlStateMarker=#]

### ISSUE THREAD

**Issue by songjgDI** [alibaba/canal#4692]
## Question

1、mysql配置如下
![image](https://user-images.githubusercontent.com/40384410/234220619-71022fa0-05cf-48d2-95ea-52740508ba4f.png)
![image](https://user-images.githubusercontent.com/40384410/234220685-b0fee63a-0d51-46cd-9007-b57a076e4d9d.png)
![image](https://user-images.githubusercontent.com/40384410/234220710-13dd0c6b-462d-48e9-8c51-c3fc7dde1bf2.png)
2、instance.properties配置内容如下：
canal.instance.master.address
canal.instance.dbUsername
canal.instance.dbPassword
3、然后启动startup.sh，instance日志报错如下
2023-04-25 14:07:38.767 [main] INFO  c.a.otter.canal.instance.spring.CanalInstanceWithSpring - start CannalInstance for 1-example 
2023-04-25 14:07:38.774 [main] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table filter : ^.*\..*$
2023-04-25 14:07:38.774 [main] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table black filter : ^mysql\.slave_.*$
2023-04-25 14:07:38.777 [main] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - start successful....
2023-04-25 14:07:38.857 [destination = example , address = cd-tdsqlshard-obt13ze4.sql.tencentcdb.com/43.137.61.38:25094 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> begin to find start position, it will be long time for reset or first position
2023-04-25 14:07:38.857 [destination = example , address = cd-tdsqlshard-obt13ze4.sql.tencentcdb.com/43.137.61.38:25094 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - prepare to find start position just show master status
2023-04-25 14:07:38.880 [destination = example , address = cd-tdsqlshard-obt13ze4.sql.tencentcdb.com/43.137.61.38:25094 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.MysqlConnection - update master_binlog_checksum failed
java.io.IOException: ErrorPacket [errorNumber=650, fieldCount=-1, message=Proxy ERROR: Proxy does not support such usage yet: Do not support global set, sqlState=HY000, sqlStateMarker=#]
 with command: set @master_binlog_checksum= @@global.binlog_checksum
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlUpdateExecutor.update(MysqlUpdateExecutor.java:49) ~[canal.parse.driver-1.1.7-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.update(MysqlConnection.java:116) [canal.parse-1.1.7-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.updateSettings(MysqlConnection.java:434) [canal.parse-1.1.7-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.seek(MysqlConnection.java:123) [canal.parse-1.1.7-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findAsPerTimestampInSpecificLogFile(MysqlEventParser.java:767) [canal.parse-1.1.7-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findEndPositionWithMasterIdAndTimestamp(MysqlEventParser.java:384) [canal.parse-1.1.7-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPositionInternal(MysqlEventParser.java:439) [canal.parse-1.1.7-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPosition(MysqlEventParser.java:358) [canal.parse-1.1.7-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:191) [canal.parse-1.1.7-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:750) [na:1.8.0_372]
2023-04-25 14:07:38.896 [destination = example , address = cd-tdsqlshard-obt13ze4.sql.tencentcdb.com/43.137.61.38:25094 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - I/O error while reading from client socket
java.io.IOException: Received error packet: errno = 602, sqlstate = HY000 errmsg = Proxy ERROR: This type of SQL is not supported by group shard
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102) ~[canal.parse-1.1.7-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.seek(MysqlConnection.java:150) [canal.parse-1.1.7-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findAsPerTimestampInSpecificLogFile(MysqlEventParser.java:767) [canal.parse-1.1.7-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findEndPositionWithMasterIdAndTimestamp(MysqlEventParser.java:384) [canal.parse-1.1.7-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPositionInternal(MysqlEventParser.java:439) [canal.parse-1.1.7-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPosition(MysqlEventParser.java:358) [canal.parse-1.1.7-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:191) [canal.parse-1.1.7-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:750) [na:1.8.0_372]
2023-04-25 14:07:38.896 [destination = example , address = cd-tdsqlshard-obt13ze4.sql.tencentcdb.com/43.137.61.38:25094 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ERROR ## findAsPerTimestampInSpecificLogFile has an error
java.io.IOException: Received error packet: errno = 602, sqlstate = HY000 errmsg = Proxy ERROR: This type of SQL is not supported by group shard
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102) ~[canal.parse-1.1.7-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.seek(MysqlConnection.java:150) ~[canal.parse-1.1.7-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findAsPerTimestampInSpecificLogFile(MysqlEventParser.java:767) [canal.parse-1.1.7-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findEndPositionWithMasterIdAndTimestamp(MysqlEventParser.java:384) [canal.parse-1.1.7-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPositionInternal(MysqlEventParser.java:439) [canal.parse-1.1.7-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPosition(MysqlEventParser.java:358) [canal.parse-1.1.7-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:191) [canal.parse-1.1.7-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:750) [na:1.8.0_372]
2023-04-25 14:07:38.897 [destination = example , address = cd-tdsqlshard-obt13ze4.sql.tencentcdb.com/43.137.61.38:25094 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address cd-tdsqlshard-obt13ze4.sql.tencentcdb.com/43.137.61.38:25094 has an error, retrying. caused by 
com.alibaba.otter.canal.parse.exception.PositionNotFoundException: can't find start position for example
2023-04-25 14:07:38.899 [destination = example , address = cd-tdsqlshard-obt13ze4.sql.tencentcdb.com/43.137.61.38:25094 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[com.alibaba.otter.canal.parse.exception.PositionNotFoundException: can't find start position for example
]

这个错误该如何解决哇。。。

**Comment by agapple** [comment]
Proxy ERROR: Proxy does not support such usage yet: Do not support global set, sqlState=HY000, sqlStateMarker=#]

找TDSQL

**Comment by Dkbei** [comment]
> ## Question
> 1、mysql配置如下 ![image](https://user-images.githubusercontent.com/40384410/234220619-71022fa0-05cf-48d2-95ea-52740508ba4f.png) ![image](https://user-images.githubusercontent.com/40384410/234220685-b0fee63a-0d51-46cd-9007-b57a076e4d9d.png) ![image](https://user-images.githubusercontent.com/40384410/234220710-13dd0c6b-462d-48e9-8c51-c3fc7dde1bf2.png) 2、instance.properties配置内容如下： canal.instance.master.address canal.instance.dbUsername canal.instance.dbPassword 3、然后启动startup.sh，instance日志报错如下 2023-04-25 14:07:38.767 [main] INFO c.a.otter.canal.instance.spring.CanalInstanceWithSpring - start CannalInstance for 1-example 2023-04-25 14:07:38.774 [main] WARN c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table filter : ^._.._$ 2023-04-25 14:07:38.774 [main] WARN c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table black filter : ^mysql.slave_.*$ 2023-04-25 14:07:38.777 [main] INFO c.a.otter.canal.instance.core.AbstractCanalInstance - start successful.... 2023-04-25 14:07:38.857 [destination = example , address = cd-tdsqlshard-obt13ze4.sql.tencentcdb.com/43.137.61.38:25094 , EventParser] WARN c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> begin to find start position, it will be long time for reset or first position 2023-04-25 14:07:38.857 [destination = example , address = cd-tdsqlshard-obt13ze4.sql.tencentcdb.com/43.137.61.38:25094 , EventParser] WARN c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - prepare to find start position just show master status 2023-04-25 14:07:38.880 [destination = example , address = cd-tdsqlshard-obt13ze4.sql.tencentcdb.com/43.137.61.38:25094 , EventParser] WARN c.a.otter.canal.parse.inbound.mysql.MysqlConnection - update master_binlog_checksum failed java.io.IOException: ErrorPacket [errorNumber=650, fieldCount=-1, message=Proxy ERROR: Proxy does not support such usage yet: Do not support global set, sqlState=HY000, sqlStateMarker=#] with command: set @master_binlog_checksum= @@global.binlog_checksum at com.alibaba.otter.canal.parse.driver.mysql.MysqlUpdateExecutor.update(MysqlUpdateExecutor.java:49) ~[canal.parse.driver-1.1.7-SNAPSHOT.jar:na] at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.update(MysqlConnection.java:116) [canal.parse-1.1.7-SNAPSHOT.jar:na] at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.updateSettings(MysqlConnection.java:434) [canal.parse-1.1.7-SNAPSHOT.jar:na] at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.seek(MysqlConnection.java:123) [canal.parse-1.1.7-SNAPSHOT.jar:na] at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findAsPerTimestampInSpecificLogFile(MysqlEventParser.java:767) [canal.parse-1.1.7-SNAPSHOT.jar:na] at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findEndPositionWithMasterIdAndTimestamp(MysqlEventParser.java:384) [canal.parse-1.1.7-SNAPSHOT.jar:na] at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPositionInternal(MysqlEventParser.java:439) [canal.parse-1.1.7-SNAPSHOT.jar:na] at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPosition(MysqlEventParser.java:358) [canal.parse-1.1.7-SNAPSHOT.jar:na] at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:191) [canal.parse-1.1.7-SNAPSHOT.jar:na] at java.lang.Thread.run(Thread.java:750) [na:1.8.0_372] 2023-04-25 14:07:38.896 [destination = example , address = cd-tdsqlshard-obt13ze4.sql.tencentcdb.com/43.137.61.38:25094 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - I/O error while reading from client socket java.io.IOException: Received error packet: errno = 602, sqlstate = HY000 errmsg = Proxy ERROR: This type of SQL is not supported by group shard at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102) ~[canal.parse-1.1.7-SNAPSHOT.jar:na] at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.seek(MysqlConnection.java:150) [canal.parse-1.1.7-SNAPSHOT.jar:na] at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findAsPerTimestampInSpecificLogFile(MysqlEventParser.java:767) [canal.parse-1.1.7-SNAPSHOT.jar:na] at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findEndPositionWithMasterIdAndTimestamp(MysqlEventParser.java:384) [canal.parse-1.1.7-SNAPSHOT.jar:na] at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPositionInternal(MysqlEventParser.java:439) [canal.parse-1.1.7-SNAPSHOT.jar:na] at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPosition(MysqlEventParser.java:358) [canal.parse-1.1.7-SNAPSHOT.jar:na] at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:191) [canal.parse-1.1.7-SNAPSHOT.jar:na] at java.lang.Thread.run(Thread.java:750) [na:1.8.0_372] 2023-04-25 14:07:38.896 [destination = example , address = cd-tdsqlshard-obt13ze4.sql.tencentcdb.com/43.137.61.38:25094 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ERROR ## findAsPerTimestampInSpecificLogFile has an error java.io.IOException: Received error packet: errno = 602, sqlstate = HY000 errmsg = Proxy ERROR: This type of SQL is not supported by group shard at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102) ~[canal.parse-1.1.7-SNAPSHOT.jar:na] at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.seek(MysqlConnection.java:150) ~[canal.parse-1.1.7-SNAPSHOT.jar:na] at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findAsPerTimestampInSpecificLogFile(MysqlEventParser.java:767) [canal.parse-1.1.7-SNAPSHOT.jar:na] at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findEndPositionWithMasterIdAndTimestamp(MysqlEventParser.java:384) [canal.parse-1.1.7-SNAPSHOT.jar:na] at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPositionInternal(MysqlEventParser.java:439) [canal.parse-1.1.7-SNAPSHOT.jar:na] at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPosition(MysqlEventParser.java:358) [canal.parse-1.1.7-SNAPSHOT.jar:na] at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:191) [canal.parse-1.1.7-SNAPSHOT.jar:na] at java.lang.Thread.run(Thread.java:750) [na:1.8.0_372] 2023-04-25 14:07:38.897 [destination = example , address = cd-tdsqlshard-obt13ze4.sql.tencentcdb.com/43.137.61.38:25094 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address cd-tdsqlshard-obt13ze4.sql.tencentcdb.com/43.137.61.38:25094 has an error, retrying. caused by com.alibaba.otter.canal.parse.exception.PositionNotFoundException: can't find start position for example 2023-04-25 14:07:38.899 [destination = example , address = cd-tdsqlshard-obt13ze4.sql.tencentcdb.com/43.137.61.38:25094 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[com.alibaba.otter.canal.parse.exception.PositionNotFoundException: can't find start position for example ]
> 
> 这个错误该如何解决哇。。。

大佬，我这边也是tdsql，想请教下是否解决了呢？如何解决的呢？
