### ISSUE TITLE
canal-adapter 1.1.6

### ISSUE THREAD

**Issue by Sharkzeng** [alibaba/canal#4693]
2023-04-25 16:39:20.310 [Thread-4] INFO  c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - =============> Start to connect destination: PayOk <=============
2023-04-25 16:39:20.311 [Thread-4] ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - process error!
com.alibaba.otter.canal.protocol.exception.CanalClientException: java.net.ConnectException: Connection refused
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:200) ~[na:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.connect(SimpleCanalConnector.java:116) ~[na:na]
	at com.alibaba.otter.canal.connector.tcp.consumer.CanalTCPConsumer.connect(CanalTCPConsumer.java:63) ~[na:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.process(AdapterProcessor.java:185) ~[client-adapter.launcher-1.1.6.jar:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_71]
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_71]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_71]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_71]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_71]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:152) ~[na:na]

啥意思啊? JAVA日志 打印一堆无用的垃圾信息? 我只是个运维工具人,不懂JAVA
我想把MYSQL数据库 同步到 另外一台MYSQL 下面是ADAPTER 配置
bootstrap.yml
`canal:
  manager:
    jdbc:
      url: jdbc:mysql://127.0.0.1:3309/canal_manager_payok?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
      username: canal
      password: canal
`

application.yml
`
server:
  port: 8081
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

canal.conf:
  mode: tcp #tcp kafka rocketMQ rabbitMQ
  flatMessage: true
  zookeeperHosts:
  syncBatchSize: 1000
  retries: -1
  timeout:
  accessKey:
  secretKey:
  consumerProperties:
    # canal tcp consumer
    canal.tcp.server.host: 127.0.0.1:11111
    canal.tcp.zookeeper.hosts:
    canal.tcp.batch.size: 500
    canal.tcp.username:
    canal.tcp.password:
  srcDataSources:
    defaultDS:
      url: jdbc:mysql://192.168.0.227:3306/aesygo_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
      username: shark_bak
      password: Sharkz@1688
  canalAdapters:
  - instance: PayOk # canal instance Name or mq topic name
    groups:
    - groupId: g1
      outerAdapters:
#      - name: logger
      - name: rdb
        key: mysql1
        properties:
          jdbc.driverClassName: com.mysql.jdbc.Driver
          jdbc.url: jdbc:mysql://192.168.0.221:3309/payok?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
          jdbc.username: root
          jdbc.password: 123456
          druid.stat.enable: false
          druid.stat.slowSqlMillis: 1000

`

canal.deployer

**Comment by zzyyds520** [comment]
既然不懂就不要乱喷

**Comment by Im-SAMW** [comment]
> 既然不懂就不要乱喷

日志信息确实很不友好，而且上一个发行版还有明显Bug
