### ISSUE TITLE
canal-1.1.6数据同步异常 EOF encountered

### ISSUE THREAD

**Issue by sjh19950115** [alibaba/canal#4699]
## Question
canal-1.1.6 同步RDS数据库binlog在运行2-4小时左右就会抛出IO异常；虽然有重试机制，但是重试之后会将address重定向到本地127.0.0.1，在源码中没有看到为什么会设置成这个；
具体报错：
2023-04-27 05:31:05.375 [destination = example , address = /xxx:6007 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - I/O error while reading from client socket
java.io.IOException: EOF encountered.
	at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:113) ~[canal.parse.driver-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:170) ~[canal.parse-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:85) ~[canal.parse-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:237) [canal.parse-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:262) [canal.parse-1.1.6.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_281]
在什么情况下会出现这个问题，看了之前的issue，分别试了都还是存在这个问题；
已试策略（均无效）：
1、mysql设置: set net_write_timeout = 14400（4小时）- 增加mysql的写超时时间
2、mysql设置: set max_allowed_packet = 32M - 增加单个数据包的大小
3、canal设置：
      - 增大 canal.instance.transaction.size （单个事务的大小为65536，默认为1024）
      - 增大 canal.instance.memory.buffer.memunit （设置为2048，默认为1024）
      - 增大 canal.instance.network.receiveBufferSize、canal.instance.network.sendBufferSize 为 32768（默认为16384）
   
尝试以上方案后依旧会报出IO异常；
请问：
1、该问题的产生的情况有哪些？
2、如何解决这个问题？

**Comment by olyhao** [comment]
我也遇到了类似的问题：
ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - I/O error while reading from client socket
java.io.IOException: EOF encountered.

ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address xxx has an error, retrying. caused by
java.io.IOException: EOF encountered.


ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:xxx[java.io.IOException: EOF encountered.

**Comment by agapple** [comment]
重试之后会将address重定向到本地127.0.0.1，这个有具体的报错么？

出现EOF encountered，一般是链接被RDS主动关闭了，可以检查下是否有主从切换、proxy空闲断链等情况？
