### ISSUE TITLE
canal的客户端总是报canal报com.alibaba.otter.canal.protocol.exception.CanalClientException: java.io.IOException: end of stream when reading header这个错误

### ISSUE THREAD

**Issue by yangzhenkun** [alibaba/canal#470]

**Comment by agapple** [comment]
一般是需要客户端重试

**Comment by wenchongyang** [comment]
我也遇到同样问题关键是handshake 的时候出来的。
Caused by: java.io.IOException: end of stream when reading header
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.read(SimpleCanalConnector.java:401) ~[classes/:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.readNextPacket(SimpleCanalConnector.java:392) ~[classes/:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.readNextPacket(SimpleCanalConnector.java:373) ~[classes/:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:140) ~[classes/:na]
	... 4 common frames omitted

**Comment by dingaiminGIT** [comment]
我也遇到了
Exception in thread "main" com.alibaba.otter.canal.protocol.exception.CanalClientException: java.io.IOException: end of stream when reading header
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:190)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.connect(SimpleCanalConnector.java:114)
	at com.study.canal.SimpleCanalClientExample.main(SimpleCanalClientExample.java:20)
Caused by: java.io.IOException: end of stream when reading header
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.read(SimpleCanalConnector.java:431)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.readNextPacket(SimpleCanalConnector.java:422)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.readNextPacket(SimpleCanalConnector.java:403)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:152)
	... 2 more

**Comment by NorthWard** [comment]
server端是cluster
客户端用SimpleCanalConnector会出现这个问题
改用ClusterCanalConnector即可

**Comment by mengban0727** [comment]
> 一般是需要客户端重试

说了等于没说

**Comment by HitterWin** [comment]
使用1.1.7   我也遇到了。。。。
