### ISSUE TITLE
Canal dependency fastjson2 has bugs, please increase up to 2.0.31

### ISSUE THREAD

**Issue by DongJigong** [alibaba/canal#4706]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version
* mysql version

### Issue Description

This bug has nothing about canal, it was caused by fastjson2. fastjson2 low version has a bug. When json data has ' ', fastjson will throw a TODO exception.

`com.alibaba.fastjson2.JSONException: TODO : 
	at com.alibaba.fastjson2.JSONReaderUTF8.skipValue(JSONReaderUTF8.java:1889) ~[fastjson2-2.0.4.jar:na]
	at com.alibaba.fastjson2.reader.ObjectReaderBean.processExtra(ObjectReaderBean.java:49) ~[fastjson2-2.0.4.jar:na]
	at com.alibaba.fastjson2.reader.ObjectReaderBean.readObject(ObjectReaderBean.java:167) ~[fastjson2-2.0.4.jar:na]
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:258) ~[fastjson2-2.0.4.jar:na]
	at com.alibaba.otter.canal.client.kafka.KafkaCanalConnector.getFlatListWithoutAck(KafkaCanalConnector.java:233) ~[canal.client-1.1.6.jar:na]
	at top.javatool.canal.client.client.KafkaCanalClient.process(KafkaCanalClient.java:39) ~[classes/:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
`

### Actual behaviour

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```
`com.alibaba.fastjson2.JSONException: TODO : 
	at com.alibaba.fastjson2.JSONReaderUTF8.skipValue(JSONReaderUTF8.java:1889) ~[fastjson2-2.0.4.jar:na]
	at com.alibaba.fastjson2.reader.ObjectReaderBean.processExtra(ObjectReaderBean.java:49) ~[fastjson2-2.0.4.jar:na]
	at com.alibaba.fastjson2.reader.ObjectReaderBean.readObject(ObjectReaderBean.java:167) ~[fastjson2-2.0.4.jar:na]
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:258) ~[fastjson2-2.0.4.jar:na]
	at com.alibaba.otter.canal.client.kafka.KafkaCanalConnector.getFlatListWithoutAck(KafkaCanalConnector.java:233) ~[canal.client-1.1.6.jar:na]
	at top.javatool.canal.client.client.KafkaCanalClient.process(KafkaCanalClient.java:39) ~[classes/:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
`

**Comment by DongJigong** [comment]
I have upgrade fastjson2 to version 2.0.31.  It fixed!

**Comment by agapple** [comment]
cc75d3dda47bbb1954cadd11db07c161cf8b0fd3
