### ISSUE TITLE
同步部署在docker中的canal时连接异常

### ISSUE THREAD

**Issue by xinyt** [alibaba/canal#4717]
## Question

mysql 版本 5.7.41
canal 版本 canal.deployer-1.1.6

java.io.IOException:  connect  /ip:port failure
            at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(Mysqlconnector.java:85)~[canal.parse.driver-1.1.6.jar.bak:na]
            at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.reconnect(Mysqlconnector.java:94)~[canal.parse.driver-1.1.6.jar.bak:na]
            at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnector.reconnect(Mysqlconnector.java:93)~[canal.parse-1.1.6.jar:na]
            at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParse$MysqlDetectingTimeTask.run(MysqlEventParse.java:229)~[canal.parse.1.1.6.jar:na]
            at java.util.TimerThread.mainLoop(Timer.java:555)  [na:1.8.0_301]
            at java.util.TimerThread.run(Timer.java:505)  [na:1.8.0_301]
Caused by: java.net.SocketTimeoutException: Timeout occurred, failed to read total 4 bytes in 5000 milliseconds, actual read only 0 bytes
            at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:91)~[canal.parse.driver-1.1.6.jar.bak:na]
            at com.alibaba.otter.canal.parse.driver.mysql.utils.PacketManager.readHeader(PacketManager.java:19)~[canal.parse.driver-1.1.6.jar.bak:na]
            at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.negotiate(MysqlConnector.java:162)~[canal.parse.driver-1.1.6.jar.bak:na]
            at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:82)~[canal.parse.driver-1.1.6.jar.bak:na]

**Comment by xinyt** [comment]
怎么多出来好多删除线..
