### ISSUE TITLE
c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - Index 3667 out of bounds for length 3667

### ISSUE THREAD

**Issue by sun-tf** [alibaba/canal#4718]
ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - Index 3667 out of bounds for length 3667
java.lang.ArrayIndexOutOfBoundsException: Index 3667 out of bounds for length 3667
        at com.alibaba.fastjson2.JSONWriterUTF16.writeString(JSONWriterUTF16.java:336) ~[fastjson2-2.0.7.jar:na]
        at com.alibaba.fastjson2.writer.ObjectWriterImplMap.write(ObjectWriterImplMap.java:401) ~[fastjson2-2.0.7.jar:na]
        at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:177) ~[fastjson2-2.0.7.jar:na]
        at com.alibaba.fastjson2.writer.ObjectWriter_1.write(Unknown Source) ~[na:na]
        at com.alibaba.fastjson2.JSON.toJSONString(JSON.java:1723) ~[fastjson2-2.0.7.jar:na]
        at com.alibaba.otter.canal.client.adapter.logger.LoggerAdapterExample.sync(LoggerAdapterExample.java:39) ~[na:na]
        at com.alibaba.otter.canal.client.adapter.logger.LoggerAdapterExample.sync(LoggerAdapterExample.java:34) ~[na:na]
        at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.batchSync(AdapterProcessor.java:140) ~[client-adapter.launcher-1.1.6.jar:na]
        at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.lambda$writeOut$1(AdapterProcessor.java:98) ~[client-adapter.launcher-1.1.6.jar:na]
        at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807) ~[na:na]
        at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.lambda$writeOut$2(AdapterProcessor.java:95) ~[client-adapter.launcher-1.1.6.jar:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
2023-05-19 13:21:57.772 [Thread-3] ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - Outer adapter sync failed!  Error sync and rollback, execute times: 4

**Comment by sun-tf** [comment]
版本1.1.6，无论写入什么库都报这个错误

**Comment by sun-tf** [comment]
未新建库表
