### ISSUE TITLE
Column的value如何转成具体Java对象，而不是统一String

### ISSUE THREAD

**Issue by xunyao4dev** [alibaba/canal#4728]
```
Map<String, Object> afterData = new LinkedHashMap<>();
List<CanalEntry.Column> afterClountList = rowData.getAfterColumnsList();
for (CanalEntry.Column column : afterClountList) {
    String name = column.getName();
    JDBCType jdbcType = JDBCType.valueOf(column.getSqlType());
    Object value = parse(column.getValueBytes(), jdbcType);
    afterData.put(name, value);
}

private Object parse(ByteString value0, JDBCType jdbcType) {
    if (value0.isEmpty()) {
        return null;
    }
    CodedInputStream c = value0.newCodedInput();
    switch (jdbcType) {
        case BIT:
            return c.readBool();
        case TINYINT:
            return (byte) c.readInt32();
        case SMALLINT:
        case INTEGER:
            return c.readInt32();
        case BIGINT:
            return c.readInt64();
        case FLOAT:
        case REAL:
            return c.readFloat();
        case DOUBLE:
            return c.readDouble();
        case NUMERIC:
        case DECIMAL:
            return new BigDecimal(c.readString());
        case CHAR:
        case VARCHAR:
        case LONGVARCHAR:
            return c.readString();
        case TIMESTAMP:
            return Instant.parse(c.readString());
        case TIME:
            return LocalTime.parse(c.readString());
        case DATE:
            return LocalDate.parse(c.readString());
        case BINARY:
        case VARBINARY:
        case LONGVARBINARY:
            return c.readByteArray();
    }
    return null;
}
```

然后parse的时候就报错
```
com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
	at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:86) ~[protobuf-java-3.6.1.jar:na]
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readString(CodedInputStream.java:827) ~[protobuf-java-3.6.1.jar:na]
```

请问如何解决？

**Comment by agapple** [comment]
你按照不同的sql type，通过对象的方式进行反序列化

canal默认选择string类型表示，主要是考虑一些特殊类型无法用java对象来描述，比如'-800:00:00'的time类型、'0000-00-00'的date类型
