### ISSUE TITLE
deserializer failed 

### ISSUE THREAD

**Issue by harunatsugit** [alibaba/canal#4729]
## Question
**canal出现错误deserializer failed** 
com.alibaba.otter.canal.protocol.exception.CanalClientException: deserializer failed
	at com.alibaba.otter.canal.client.CanalMessageDeserializer.deserializer(CanalMessageDeserializer.java:54)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.receiveMessages(SimpleCanalConnector.java:340)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.getWithoutAck(SimpleCanalConnector.java:332)
	at com.alibaba.otter.canal.example.SimpleCanalClientPermanceTest.main(SimpleCanalClientPermanceTest.java:52)
Caused by: com.alibaba.otter.canal.protocol.exception.CanalClientException: something goes wrong with reason: something goes wrong with channel:[id: 0x4bc74d6b, /192.168.1.224:1164 => /172.17.0.11:11111], exception=com.alibaba.otter.canal.server.exception.CanalServerException: ack error , clientId:1001 batchId:56 is not exist , please check

**Comment by harunatsugit** [comment]
原因找到了，是有一个canal-adapter 服务在运行中。

**Comment by harunatsugit** [comment]
原因找到了，是有一个canal-adapter 服务在运行中。
