### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by IE90** [alibaba/canal#4740]
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: java.lang.ArrayIndexOutOfBoundsException: 381
    at com.taobao.tddl.dbsync.binlog.LogBuffer.getBigDecimalCompact(LogBuffer.java:1397) ~[canal.parse.dbsync-1.1.7-SNAPSHOT.jar:na]
    at com.taobao.tddl.dbsync.binlog.LogBuffer.getDecimal(LogBuffer.java:1311) ~[canal.parse.dbsync-1.1.7-SNAPSHOT.jar:na]
    at com.taobao.tddl.dbsync.binlog.event.RowsLogBuffer.fetchValue(RowsLogBuffer.java:375) ~[canal.parse.dbsync-1.1.7-SNAPSHOT.jar:na]
    at com.taobao.tddl.dbsync.binlog.event.RowsLogBuffer.nextValue(RowsLogBuffer.java:132) ~[canal.parse.dbsync-1.1.7-SNAPSHOT.jar:na]
    at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseOneRow(LogEventConvert.java:753) ~[canal.parse-1.1.7-SNAPSHOT.jar:na]
    at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseRowsEvent(LogEventConvert.java:576) ~[canal.parse-1.1.7-SNAPSHOT.jar:na]
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$DmlParserStage.onEvent(MysqlMultiStageCoprocessor.java:341) ~[canal.parse-1.1.7-SNAPSHOT.jar:na]
    at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$DmlParserStage.onEvent(MysqlMultiStageCoprocessor.java:327) ~[canal.parse-1.1.7-SNAPSHOT.jar:na]
    at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) ~[disruptor-3.4.2.jar:na]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_345]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_345]
    at java.lang.Thread.run(Thread.java:750) ~[na:1.8.0_345]
2023-05-29 16:11:23.362 [destination = pay_pre , address = /10.224.8.157:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address 10.224.8.157/10.224.8.157:3306 has an error, retrying. caused by 
com.alibaba.otter.canal.parse.exception.CanalParseException: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: java.lang.ArrayIndexOutOfBoundsException: 381
    at com.taobao.tddl.dbsync.binlog.LogBuffer.getBigDecimalCompact(LogBuffer.java:1397) ~[canal.parse.dbsync-1.1.7-SNAPSHOT.jar:na]
    at com.taobao.tddl.dbsync.binlog.LogBuffer.getDecimal(LogBuffer.java:1311) ~[canal.parse.dbsync-1.1.7-SNAPSHOT.jar:na]
    at com.taobao.tddl.dbsync.binlog.event.RowsLogBuffer.fetchValue(RowsLogBuffer.java:375) ~[canal.parse.db

您好，其他表正常，其中一个表报这个错，什么原因导致？

**Comment by agapple** [comment]
提供一下复现步骤：mysql版本、测试表、以及测试sql

**Comment by agapple** [comment]
decimal compact优化代码已回滚

**Comment by 1774393220** [comment]
更新canal/canal-server镜像解决了
