### ISSUE TITLE
MySQL 重启后，Canal 无限循环在SocketChannel.read方法内

### ISSUE THREAD

**Issue by wingerx** [alibaba/canal#475]
场景:
canal 在dump的时候，直接重启MySQL
现象：
debug 可以看到一直在这个地方循环出不去
![image](https://user-images.githubusercontent.com/33280738/34552985-e07d80aa-f15f-11e7-806c-c3183b47050c.png)

控制台日志：
![image](https://user-images.githubusercontent.com/33280738/34553015-1ed73ab2-f160-11e7-9eb2-19acbf410a08.png)

无法让Canal 重新进行dump

**Comment by wingerx** [comment]
半小时后，控制台出现如下日志：
`
2018-01-04 15:01:05.400 [Hashed wheel timer #1] WARN  c.a.o.c.server.netty.handler.ClientAuthenticationHandler - channel:[id: 0x15bf0ead, /10.10.80.108:50423 :> /10.10.80.108:11111] idle timeout exceeds, close channel to save server resources...
2018-01-04 15:01:05.403 [New I/O server worker #1-4] ERROR c.a.otter.canal.server.netty.handler.SessionHandler - something goes wrong with channel:[id: 0x571b8f50, /10.10.80.108:58807 => /10.10.80.108:11111], exception=java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:322)
	at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:281)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:201)
	at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`

Canal 仍然无法进入重新dump 状态

**Comment by wingerx** [comment]
忽略，我没有开心跳..
