### ISSUE TITLE
请问有无配置连接数据库超时的配置？报错如下：ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address /137.64.123.52:3360 has an error, retrying. caused by  com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: connect /137.64.123.52:3360 failure

### ISSUE THREAD

**Issue by xty805007911** [alibaba/canal#4773]
**启动时报了如下的错误，本人怀疑是因为网络太慢，导致超时了（报错信息显示5000ms连接超时），请问有无配置连接数据库超时的配置？**

2023-06-26 15:24:11.267 [main] INFO  c.a.otter.canal.instance.spring.CanalInstanceWithSpring - start CannalInstance for 1-example 
2023-06-26 15:24:11.282 [main] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table filter : ^.*\..*$
2023-06-26 15:24:11.283 [main] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table black filter : ^mysql\.slave_.*$
2023-06-26 15:24:11.399 [main] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - subscribe filter change to user_center.zt_user,user_center.cscp_org,user_center.cscp_roles,user_center.cscp_user_role,user_center.cscp_role_menu
2023-06-26 15:24:11.399 [main] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table filter : ^user_center.cscp_user_role$|^user_center.cscp_role_menu$|^user_center.cscp_roles$|^user_center.cscp_org$|^user_center.zt_user$
2023-06-26 15:24:11.399 [main] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - start successful....
2023-06-26 15:24:14.674 [New I/O server worker #1-1] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - subscribe filter change to user_center.zt_user,user_center.cscp_org,user_center.cscp_roles,user_center.cscp_user_role,user_center.cscp_role_menu
2023-06-26 15:24:14.674 [New I/O server worker #1-1] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table filter : ^user_center.cscp_user_role$|^user_center.cscp_role_menu$|^user_center.cscp_roles$|^user_center.cscp_org$|^user_center.zt_user$
2023-06-26 15:24:14.719 [New I/O server worker #1-1] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - subscribe filter change to user_center.zt_user,user_center.cscp_org,user_center.cscp_roles,user_center.cscp_user_role,user_center.cscp_role_menu
2023-06-26 15:24:14.719 [New I/O server worker #1-1] WARN  c.a.o.canal.parse.inbound.mysql.dbsync.LogEventConvert - --> init table filter : ^user_center.cscp_user_role$|^user_center.cscp_role_menu$|^user_center.cscp_roles$|^user_center.cscp_org$|^user_center.zt_user$
2023-06-26 15:24:16.304 [destination = example , address = /137.64.123.52:3360 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address /137.64.123.52:3360 has an error, retrying. caused by 
com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: connect /137.64.123.52:3360 failure
Caused by: java.io.IOException: connect /137.64.123.52:3360 failure
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:85) ~[canal.parse.driver-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.connect(MysqlConnection.java:89) ~[canal.parse-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.preDump(MysqlEventParser.java:87) ~[canal.parse-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:176) ~[canal.parse-1.1.6.jar:na]
	at java.lang.Thread.run(Thread.java:750) [na:1.8.0_371]
Caused by: java.net.SocketTimeoutException: Timeout occurred, failed to read total 4 bytes in 5000 milliseconds, actual read only 0 bytes
	at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:91) ~[canal.parse.driver-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.driver.mysql.utils.PacketManager.readHeader(PacketManager.java:19) ~[canal.parse.driver-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.negotiate(MysqlConnector.java:162) ~[canal.parse.driver-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:82) ~[canal.parse.driver-1.1.6.jar:na]
	... 4 common frames omitted
2023-06-26 15:24:16.306 [destination = example , address = /137.64.123.52:3360 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: connect /137.64.123.52:3360 failure
Caused by: java.io.IOException: connect /137.64.123.52:3360 failure
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:85)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.connect(MysqlConnection.java:89)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.preDump(MysqlEventParser.java:87)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:176)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.net.SocketTimeoutException: Timeout occurred, failed to read total 4 bytes in 5000 milliseconds, actual read only 0 bytes
	at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:91)
	at com.alibaba.otter.canal.parse.driver.mysql.utils.PacketManager.readHeader(PacketManager.java:19)
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.negotiate(MysqlConnector.java:162)
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:82)
	... 4 more
]
2023-06-26 15:24:37.787 [destination = example , address = /137.64.123.52:3360 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address /137.64.123.52:3360 has an error, retrying. caused by 
com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: connect /137.64.123.52:3360 failure
Caused by: java.io.IOException: connect /137.64.123.52:3360 failure
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:85) ~[canal.parse.driver-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.connect(MysqlConnection.java:89) ~[canal.parse-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.preDump(MysqlEventParser.java:87) ~[canal.parse-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:176) ~[canal.parse-1.1.6.jar:na]
	at java.lang.Thread.run(Thread.java:750) [na:1.8.0_371]
Caused by: java.net.SocketTimeoutException: Timeout occurred, failed to read total 4 bytes in 5000 milliseconds, actual read only 0 bytes
	at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:91) ~[canal.parse.driver-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.driver.mysql.utils.PacketManager.readHeader(PacketManager.java:19) ~[canal.parse.driver-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.negotiate(MysqlConnector.java:162) ~[canal.parse.driver-1.1.6.jar:na]
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:82) ~[canal.parse.driver-1.1.6.jar:na]
	... 4 common frames omitted
2023-06-26 15:24:37.789 [destination = example , address = /137.64.123.52:3360 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: connect /137.64.123.52:3360 failure
Caused by: java.io.IOException: connect /137.64.123.52:3360 failure
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:85)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.connect(MysqlConnection.java:89)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.preDump(MysqlEventParser.java:87)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:176)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.net.SocketTimeoutException: Timeout occurred, failed to read total 4 bytes in 5000 milliseconds, actual read only 0 bytes
	at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:91)
	at com.alibaba.otter.canal.parse.driver.mysql.utils.PacketManager.readHeader(PacketManager.java:19)
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.negotiate(MysqlConnector.java:162)
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:82)
	... 4 more
]

**Comment by chengithubsa** [comment]
端口没放开吧

**Comment by agapple** [comment]
Caused by: java.net.SocketTimeoutException: Timeout occurred, failed to read total 4 bytes in 5000 milliseconds, actual read only 0 bytes

这种报错一般会自动重试，一般是因为mysql没有binlog产生导致，给mysql定期产生心跳
