### ISSUE TITLE
解析报错unknow type : 254

### ISSUE THREAD

**Issue by caofqgit** [alibaba/canal#4780]
## Question

[destination =  , address =, EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:tp-mcu[com.alibaba.otter.canal.parse.exception.CanalParseException: java.lang.IllegalArgumentException: unknow type : 254
Caused by: java.lang.IllegalArgumentException: unknow type : 254
	at com.taobao.tddl.dbsync.binlog.event.TableMapLogEvent.<init>(TableMapLogEvent.java:504)
	at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:151)
	at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:80)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:269)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:251)
	at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]

**Comment by agapple** [comment]
提供一下复现的方法：mysql版本、建表语句、测试数据
