### ISSUE TITLE
无建表权限

### ISSUE THREAD

**Issue by kingcym** [alibaba/canal#4799]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version
* mysql version

### Issue Description
canal每次启动都会报错:
 WARN c.a.o.canal.parse.inbound.mysql.tsdb.dao.MetaSnapshotDAO - init meta_snapshot failed
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: CREATE command denied to user 'canal_manager'@'10.13.1.7' for table 'meta_snapshot'
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_181]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_181]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_181]
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_181]

实质该表已经创建完成,不应该每次启动都是创建表.由于公司限制账户不能有自动创建表的权限.

**Comment by agapple** [comment]
可以考虑关闭TableMetaTSDB，或者给提前建表
