### ISSUE TITLE
java.io.IOException: connect /192.xxx.xx.xx:3306 failure

### ISSUE THREAD

**Issue by HFFZZZ** [alibaba/canal#4817]
## Question

2023-07-27 17:54:29.103 [destination = example , address = /192.xxx.xx.xx:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address /192.168.1.2:3306 has an error, retrying. caused by 
com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: connect /192.168.1.2:3306 failure
Caused by: java.io.IOException: connect /192.xxx.xx.xx:3306 failure
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:85) ~[canal.parse.driver-1.1.6.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.connect(MysqlConnection.java:89) ~[canal.parse-1.1.6.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.preDump(MysqlEventParser.java:87) ~[canal.parse-1.1.6.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:176) ~[canal.parse-1.1.6.jar:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
Caused by: java.io.IOException: caching_sha2_password Auth failed
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.negotiate(MysqlConnector.java:260) ~[canal.parse.driver-1.1.6.jar:na]
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:82) ~[canal.parse.driver-1.1.6.jar:na]
        ... 4 common frames omitted

我目前使用的是mysql8.0.26
我前面的canal少了一步 将此用户设置为从机登录 和更改密码校验 
我自己的解决方法是重新把mysql中创建的 canal用户删掉了然后重新创建一个并重新授权
我前面貌似是授权有问题 导致一直没连接上本地的数据库
可以参考一下
sql 代码
-- 给此连接创建一个用户
create user canal@'%' IDENTIFIED by 'canal';
-- 修改指定用户为 slave 从机 用此用户进行登陆的就是从机
GRANT SELECT, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'canal'@'%';
-- 更改指定用户的 密码校验规则
ALTER USER 'canal'@'%' IDENTIFIED WITH mysql_native_password BY 'canal';
FLUSH PRIVILEGES;
然后重新启动 canal服务 就可以了 我的quitstart就成功运行了
但是设置了这个密码后会出现一个警告, 可以忽略也是可以成功运行的

 [MultiStageCoprocessor-other-example-0] WARN  c.a.o.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta - dup apply for sql : ALTER USER 'canal'@'%' IDENTIFIED WITH 'mysql_native_password' AS '*E3619321C1A937C46A0D8BD1DAC39F93B27D4458'

**Comment by agapple** [comment]
这个DatabaseTableMeta日志，这是一个TableMetaTSDB的审计，可以忽略
