### ISSUE TITLE
canal-adapter1.1.6版本，重启导致数据没有再同步

### ISSUE THREAD

**Issue by lss1457781731** [alibaba/canal#4845]
日志停留在了重启时同步失败时的记录。重启成功后日志再也没有打印。

2023-08-18T15:58:17.604816869+08:00 2023-08-18 07:58:16.963 [Thread-3] ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - com.alibaba.otter.canal.protocol.exception.CanalClientException: deserializer failed Error sync and rollback, execute times: 1

instance日志中显示如下报错

2023-08-18 07:54:48.957 [New I/O server worker #1-1] ERROR c.a.otter.canal.server.netty.handler.SessionHandler - something goes wrong with channel:[id: 0x554a2ec5, /20.244.99.22:60334 :> /20.244.121.37:11111], exception=java.nio.channels.ClosedChannelException
	at org.jboss.netty.channel.socket.nio.NioWorker.cleanUpWriteBuffer(NioWorker.java:649)
	at org.jboss.netty.channel.socket.nio.NioWorker.writeFromUserCode(NioWorker.java:370)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleAcceptedSocket(NioServerSocketPipelineSink.java:137)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:76)
	at org.jboss.netty.channel.Channels.write(Channels.java:611)
	at org.jboss.netty.channel.Channels.write(Channels.java:578)
	at com.alibaba.otter.canal.server.netty.NettyUtils.write(NettyUtils.java:49)
	at com.alibaba.otter.canal.server.netty.handler.SessionHandler.messageReceived(SessionHandler.java:201)
	at org.jboss.netty.handler.timeout.IdleStateAwareChannelHandler.handleUpstream(IdleStateAwareChannelHandler.java:48)
	at org.jboss.netty.handler.timeout.IdleStateHandler.messageReceived(IdleStateHandler.java:276)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:302)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.unfoldAndfireMessageReceived(ReplayingDecoder.java:526)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:507)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.cleanup(ReplayingDecoder.java:542)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.channelDisconnected(ReplayingDecoder.java:450)
	at org.jboss.netty.channel.Channels.fireChannelDisconnected(Channels.java:360)
	at org.jboss.netty.channel.socket.nio.NioWorker.close(NioWorker.java:599)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleAcceptedSocket(NioServerSocketPipelineSink.java:119)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:76)
	at org.jboss.netty.channel.Channels.close(Channels.java:720)
	at org.jboss.netty.channel.AbstractChannel.close(AbstractChannel.java:208)
	at com.alibaba.otter.canal.server.netty.handler.SessionHandler.exceptionCaught(SessionHandler.java:346)
	at org.jboss.netty.handler.timeout.IdleStateAwareChannelHandler.handleUpstream(IdleStateAwareChannelHandler.java:48)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.exceptionCaught(ReplayingDecoder.java:462)
	at org.jboss.netty.channel.Channels.fireExceptionCaught(Channels.java:432)
	at org.jboss.netty.channel.socket.nio.NioWorker.write0(NioWorker.java:510)
	at org.jboss.netty.channel.socket.nio.NioWorker.writeFromUserCode(NioWorker.java:388)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleAcceptedSocket(NioServerSocketPipelineSink.java:137)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:76)
	at org.jboss.netty.channel.Channels.write(Channels.java:611)
	at org.jboss.netty.channel.Channels.write(Channels.java:578)
	at com.alibaba.otter.canal.server.netty.NettyUtils.write(NettyUtils.java:49)
	at com.alibaba.otter.canal.server.netty.handler.SessionHandler.messageReceived(SessionHandler.java:201)
	at org.jboss.netty.handler.timeout.IdleStateAwareChannelHandler.handleUpstream(IdleStateAwareChannelHandler.java:48)
	at org.jboss.netty.handler.timeout.IdleStateHandler.messageReceived(IdleStateHandler.java:276)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:302)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.unfoldAndfireMessageReceived(ReplayingDecoder.java:526)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:507)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:444)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:274)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:261)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:350)
	at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:281)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:201)
	at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

instance 配置：
#################################################
## mysql serverId , v1.0.26+ will autoGen
canal.instance.mysql.slaveId=201

# enable gtid use true/false
canal.instance.gtidon=false

# position info
canal.instance.master.address=mysql.middleware.svc.cluster.local:3306
canal.instance.master.journal.name=
canal.instance.master.position=
canal.instance.master.timestamp=
canal.instance.master.gtid=

# rds oss binlog
canal.instance.rds.accesskey=
canal.instance.rds.secretkey=
canal.instance.rds.instanceId=

# table meta tsdb info
canal.instance.tsdb.enable=true

# username/password
canal.instance.dbUsername=*****
canal.instance.dbPassword=*****
canal.instance.connectionCharset = UTF-8
# enable druid Decrypt database password
canal.instance.enableDruid=false
#canal.instance.pwdPublicKey=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALK4BUxdDltRRE5/zXpVEVPUgunvscYFtEip3pmLlhrWpacX7y7GCMo2/JM6LeHmiiNdH1FWgGCpUfircSwlWKUCAwEAAQ==

# table regex
canal.instance.filter.regex=dms.tbl_rosbag_slice
# table black regex
canal.instance.filter.black.regex=

adapter配置：
server:
  port: 8081
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
canal.conf:
  mode: tcp #tcp kafka rocketMQ rabbitMQ
  flatMessage: true
  syncBatchSize: 1000
  timeout: 400
  batchSize: 500
  retries: -1
  accessKey:
  secretKey:
  consumerProperties:
    # canal tcp consumer
    canal.tcp.server.host: canal-server.canal:11111
    canal.tcp.batch.size: 1000
  srcDataSources:
    defaultDS:
      url: jdbc:mysql://mysql.middleware.svc.cluster.local:3306/dms?useUnicode=true
      username: ****
      password: ****
      maxActive: 50

**Comment by Toltex** [comment]
> 日志停留在了重启时同步失败时的记录。重启成功后日志再也没有打印。
> 
> 2023-08-18T15:58:17.604816869+08:00 2023-08-18 07:58:16.963 [Subproceso-3] ERROR caotter.canal.adapter.launcher.loader.AdapterProcessor - com.alibaba.otter.canal.protocol .exception.CanalClientException: el deserializador falló Error de sincronización y reversión, tiempos de ejecución: 1
> 
> instancia日志中显示如下报错
> 
> 2023-08-18 07: 54: 48.957 [Nuevo trabajador del servidor de E / S [# 1](https://github.com/alibaba/canal/issues/1) -1] ERROR caotter.canal.server.netty.handler.SessionHandler: algo sale mal con el canal: [id: 0x554a2ec5, /20.244.99.22 :60334 :> /20.244.121.37:11111], excepción=java.nio.channels.ClosedChannelException en org.jboss.netty.channel.socket.nio.NioWorker.cleanUpWriteBuffer(NioWorker.java:649) en org.jboss.netty .channel.socket.nio.NioWorker.writeFromUserCode(NioWorker.java:370) en org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleAcceptedSocket(NioServerSocketPipelineSink.java:137) en org.jboss.netty.channel.socket .nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:76) en org.jboss.netty.channel.Channels.write(Channels.java:611) en org.jboss.netty.channel.Channels.write(Channels.java:578) en com.alibaba.otter.canal.server.netty.NettyUtils.write(NettyUtils.java:49) en com.alibaba.otter.canal .server.netty.handler.SessionHandler.messageReceived(SessionHandler.java:201) en org.jboss.netty.handler.timeout.IdleStateAwareChannelHandler.handleUpstream(IdleStateAwareChannelHandler.java:48) en org.jboss.netty.handler.timeout.IdleStateHandler .messageReceived(IdleStateHandler.java:276) en org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:302) en org.jboss.netty.handler.codec.replay.ReplayingDecoder.unfoldAndfireMessageReceived(ReplayingDecoder.java:526 ) en org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:507) en org.jboss.netty.handler.codec.replay.ReplayingDecoder.cleanup(ReplayingDecoder.java:542) en org.jboss.netty.handler.codec.replay.ReplayingDecoder.channelDisconnected(ReplayingDecoder.java:450) en org.jboss .netty.channel.Channels.fireChannelDisconnected(Channels.java:360) en org.jboss.netty.channel.socket.nio.NioWorker.close(NioWorker.java:599) en org.jboss.netty.channel.socket.nio .NioServerSocketPipelineSink.handleAcceptedSocket(NioServerSocketPipelineSink.java:119) en org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:76) en org.jboss.netty.channel.Channels.close(Channels.ja va :720) en org.jboss.netty.channel.AbstractChannel.close(AbstractChannel.java:208) en com.alibaba.otter.canal.server.netty.handler.SessionHandler.exceptionCaught(SessionHandler.java:346) en org.jboss.netty.handler.timeout.IdleStateAwareChannelHandler.handleUpstream(IdleStateAwareChannelHandler.java:48) en org.jboss .netty.handler.codec.replay.ReplayingDecoder.exceptionCaught(ReplayingDecoder.java:462) en org.jboss.netty.channel.Channels.fireExceptionCaught(Channels.java:432) en org.jboss.netty.channel.socket.nio .NioWorker.write0(NioWorker.java:510) en org.jboss.netty.channel.socket.nio.NioWorker.writeFromUserCode(NioWorker.java:388) en org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleAcceptedSocket (NioServerSocketPipelineSink.java:137) en org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:76) en org.jboss.netty.channel.Channels.write(Channels.java:611) en org.jboss.netty.channel .Channels.write(Channels.java:578) en com.alibaba.otter.canal.server.netty.NettyUtils.write(NettyUtils.java:49) en com.alibaba.otter.canal.server.netty.handler.SessionHandler .messageReceived(SessionHandler.java:201) en org.jboss.netty.handler.timeout.IdleStateAwareChannelHandler.handleUpstream(IdleStateAwareChannelHandler.java:48) en org.jboss.netty.handler.timeout.IdleStateHandler.messageReceived(IdleStateHandler.java: 276 ) en org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:302) en org.jboss.netty.handler.codec.replay.ReplayingDecoder.unfoldAndfireMessageReceived(ReplayingDecoder.java:526) en org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:507) en org.jboss .netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:444) en org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:274) en org.jboss.netty.channel.Channels.fireMessageReceived (Channels.java:261) en org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:350) en org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java :281) en org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:201) en org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46) en java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) en java.base/java.util .concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) en java.base/java.lang.Thread.run(Thread.java:834)
> 
> instancia 配置：
> 
> canal.instance.mysql.slaveId=201 canal.instance.gtidon=false canal.instance.master.address=mysql.middleware.svc.cluster.local:3306 canal.instance.master.journal.name= canal.instance.master .position= canal.instance.master.timestamp= canal.instance.master.gtid= canal.instance.rds.accesskey= canal.instance.rds.secretkey= canal.instance.rds.instanceId= canal.instance.tsdb.enable =true canal.instance.dbUsername=***** canal.instance.dbPassword=***** canal.instance.connectionCharset = UTF-8 canal.instance.enableDruid=false canal.instance.filter.regex=dms. tbl_rosbag_slice canal.instance.filter.black.regex=
> 
> adaptador 配置：
> 
> servidor: puerto: 8081 resorte: jackson: formato de fecha: aaaa-MM-dd HH: mm: ss zona horaria: GMT + 8 inclusión de propiedad predeterminada: non_null canal.conf: modo: tcp #tcp kafka RocketMQ rabbitMQ flatMessage : true syncBatchSize: 1000 timeout: 400 batchSize: 500 retries: -1 accessKey: secretKey: consumerProperties: canal.tcp.server.host: canal-server.canal:11111 canal.tcp.batch.size: 1000 srcDataSources: defaultDS: url : jdbc:mysql://mysql.middleware.svc.cluster.local:3306/dms?useUnicode=true nombre de usuario: **** contraseña: **** maxActive: 50

**Comment by hd900415** [comment]
解决了吗？我也是一样的错误。
`2025-02-06 19:40:03.603 [main] INFO  c.a.o.canal.adapter.launcher.loader.CanalAdapterLoader - Load canal adapter: es7 succeed
2025-02-06 19:40:03.623 [main] INFO  c.alibaba.otter.canal.connector.core.spi.ExtensionLoader - extension classpath dir: /opt/canal-adapter/plugin
2025-02-06 19:40:03.683 [main] INFO  c.a.o.canal.adapter.launcher.loader.CanalAdapterLoader - Start adapter for canal-client mq topic: mysql8-to-es-pt-member-g1 succeed
2025-02-06 19:40:03.683 [Thread-4] INFO  c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - =============> Start to connect destination: mysql8-to-es-pt-member <=============
2025-02-06 19:40:03.684 [main] INFO  c.a.o.canal.adapter.launcher.loader.CanalAdapterService - ## the canal client adapters are running now ......
2025-02-06 19:40:03.704 [main] INFO  c.a.otter.canal.adapter.launcher.CanalAdapterApplication - Started CanalAdapterApplication in 6.457 seconds (JVM running for 8.205)
2025-02-06 19:40:03.817 [Thread-4] INFO  c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - =============> Subscribe destination: mysql8-to-es-pt-member succeed <=============
2025-02-06 19:40:03.856 [Thread-4] ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - com.alibaba.otter.canal.protocol.exception.CanalClientException: deserializer failed by something goes wrong with reason:  Error sync and rollback, execute times: 1
2025-02-06 19:40:04.358 [Thread-4] ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - com.alibaba.otter.canal.protocol.exception.CanalClientException: deserializer failed by something goes wrong with reason:  Error sync and rollback, execute times: 2
2025-02-06 19:40:04.860 [Thread-4] ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - com.alibaba.otter.canal.protocol.exception.CanalClientException: deserializer failed by something goes wrong with reason:  Error sync and rollback, execute times: 3
2025-02-06 19:40:05.362 [Thread-4] ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - com.alibaba.otter.canal.protocol.exception.CanalClientException: deserializer failed by something goes wrong with reason:  Error sync and rollback, execute times: 4`

**Comment by hd900415** [comment]
2025-02-06 19:40:03.603 [main] INFO  c.a.o.canal.adapter.launcher.loader.CanalAdapterLoader - Load canal adapter: es7 succeed
2025-02-06 19:40:03.623 [main] INFO  c.alibaba.otter.canal.connector.core.spi.ExtensionLoader - extension classpath dir: /opt/canal-adapter/plugin
2025-02-06 19:40:03.683 [main] INFO  c.a.o.canal.adapter.launcher.loader.CanalAdapterLoader - Start adapter for canal-client mq topic: mysql8-to-es-pt-member-g1 succeed
2025-02-06 19:40:03.683 [Thread-4] INFO  c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - =============> Start to connect destination: mysql8-to-es-pt-member <=============
2025-02-06 19:40:03.684 [main] INFO  c.a.o.canal.adapter.launcher.loader.CanalAdapterService - ## the canal client adapters are running now ......
2025-02-06 19:40:03.704 [main] INFO  c.a.otter.canal.adapter.launcher.CanalAdapterApplication - Started CanalAdapterApplication in 6.457 seconds (JVM running for 8.205)
2025-02-06 19:40:03.817 [Thread-4] INFO  c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - =============> Subscribe destination: mysql8-to-es-pt-member succeed <=============
**2025-02-06 19:40:03.856 [Thread-4] ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - com.alibaba.otter.canal.protocol.exception.CanalClientException: deserializer failed by something goes wrong with reason:  Error sync and rollback, execute times: 1
2025-02-06 19:40:04.358 [Thread-4] ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - com.alibaba.otter.canal.protocol.exception.CanalClientException: deserializer failed by something goes wrong with reason:  Error sync and rollback, execute times: 2
2025-02-06 19:40:04.860 [Thread-4] ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - com.alibaba.otter.canal.protocol.exception.CanalClientException: deserializer failed by something goes wrong with reason:  Error sync and rollback, execute times: 3
2025-02-06 19:40:05.362 [Thread-4] ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - com.alibaba.otter.canal.protocol.exception.CanalClientException: deserializer failed by something goes wrong with reason:  Error sync and rollback, execute times: 4**
