### ISSUE TITLE
fastjson序列化时，内存溢出

### ISSUE THREAD

**Issue by blueoo** [alibaba/canal#4865]
2023-09-06 09:36:57.997 [pool-4-thread-1] ERROR c.a.o.c.c.rabbitmq.producer.CanalRabbitMQProducer - java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError
        at com.alibaba.otter.canal.common.utils.ExecutorTemplate.waitForResult(ExecutorTemplate.java:74) ~[canal.common-1.1.6.jar:na]
        at com.alibaba.otter.canal.connector.rabbitmq.producer.CanalRabbitMQProducer.send(CanalRabbitMQProducer.java:128) ~[na:na]
        at com.alibaba.otter.canal.server.CanalMQStarter.worker(CanalMQStarter.java:181) [canal.server-1.1.6.jar:na]
        at com.alibaba.otter.canal.server.CanalMQStarter.access$100(CanalMQStarter.java:24) [canal.server-1.1.6.jar:na]
        at com.alibaba.otter.canal.server.CanalMQStarter$CanalMQRunnable.run(CanalMQStarter.java:223) [canal.server-1.1.6.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_141]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_141]
Caused by: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_141]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_141]
        at com.alibaba.otter.canal.common.utils.ExecutorTemplate.waitForResult(ExecutorTemplate.java:72) ~[canal.common-1.1.6.jar:na]
        ... 7 common frames omitted
Caused by: java.lang.OutOfMemoryError: null
        at com.alibaba.fastjson2.JSONWriterUTF8.writeString(JSONWriterUTF8.java:256) ~[fastjson2-2.0.7.jar:na]
        at com.alibaba.fastjson2.writer.ObjectWriterImplMap.write(ObjectWriterImplMap.java:401) ~[fastjson2-2.0.7.jar:na]
        at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:177) ~[fastjson2-2.0.7.jar:na]
        at com.alibaba.fastjson2.writer.ObjectWriter_2.write(Unknown Source) ~[na:na]
        at com.alibaba.fastjson2.JSON.toJSONBytes(JSON.java:1889) ~[fastjson2-2.0.7.jar:na]
        at com.alibaba.otter.canal.connector.rabbitmq.producer.CanalRabbitMQProducer.send(CanalRabbitMQProducer.java:154) ~[na:na]
        at com.alibaba.otter.canal.connector.rabbitmq.producer.CanalRabbitMQProducer.lambda$send$0(CanalRabbitMQProducer.java:125) ~[na:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_141]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_141]
        ... 3 common frames omitted
2023-09-06 09:36:58.342 [pool-4-thread-1] ERROR c.a.o.c.c.rabbitmq.producer.CanalRabbitMQProducer - java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError
        at com.alibaba.otter.canal.common.utils.ExecutorTemplate.waitForResult(ExecutorTemplate.java:74) ~[canal.common-1.1.6.jar:na]
        at com.alibaba.otter.canal.connector.rabbitmq.producer.CanalRabbitMQProducer.send(CanalRabbitMQProducer.java:128) ~[na:na]
        at com.alibaba.otter.canal.server.CanalMQStarter.worker(CanalMQStarter.java:181) [canal.server-1.1.6.jar:na]
        at com.alibaba.otter.canal.server.CanalMQStarter.access$100(CanalMQStarter.java:24) [canal.server-1.1.6.jar:na]
        at com.alibaba.otter.canal.server.CanalMQStarter$CanalMQRunnable.run(CanalMQStarter.java:223) [canal.server-1.1.6.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_141]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_141]
Caused by: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_141]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_141]
        at com.alibaba.otter.canal.common.utils.ExecutorTemplate.waitForResult(ExecutorTemplate.java:72) ~[canal.common-1.1.6.jar:na]
        ... 7 common frames omitted
Caused by: java.lang.OutOfMemoryError: null
        at com.alibaba.fastjson2.JSONWriterUTF8.writeString(JSONWriterUTF8.java:256) ~[fastjson2-2.0.7.jar:na]
        at com.alibaba.fastjson2.writer.ObjectWriterImplMap.write(ObjectWriterImplMap.java:401) ~[fastjson2-2.0.7.jar:na]
        at com.alibaba.fastjson2.writer.FieldWriterList.writeList(FieldWriterList.java:177) ~[fastjson2-2.0.7.jar:na]
        at com.alibaba.fastjson2.writer.ObjectWriter_2.write(Unknown Source) ~[na:na]
        at com.alibaba.fastjson2.JSON.toJSONBytes(JSON.java:1889) ~[fastjson2-2.0.7.jar:na]

**Comment by tangguoqiang172528725** [comment]
I meet then same problem

**Comment by agapple** [comment]
```
JSON.toJSONBytes(flatMessage, JSONWriter.Feature.WriteNulls, JSONWriter.Feature.LargeObject);
```
当前主干已做优化，开启fastjson的大对象优化
