### ISSUE TITLE
报错：NoNode for /otter/canal/destinations/example/cluster 

### ISSUE THREAD

**Issue by shaoyou520** [alibaba/canal#4889]
## Question

Exception in thread "main" org.I0Itec.zkclient.exception.ZkNoNodeException: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /otter/canal/destinations/example/cluster
	at org.I0Itec.zkclient.exception.ZkException.create(ZkException.java:47)
	at org.I0Itec.zkclient.ZkClient.retryUntilConnected(ZkClient.java:1001)
	at org.I0Itec.zkclient.ZkClient.getChildren(ZkClient.java:677)
	at org.I0Itec.zkclient.ZkClient.getChildren(ZkClient.java:673)
	at com.alibaba.otter.canal.client.impl.ClusterNodeAccessStrategy.<init>(ClusterNodeAccessStrategy.java:54)
	at com.alibaba.otter.canal.client.CanalConnectors.newClusterConnector(CanalConnectors.java:71)
	at com.alibaba.otter.canal.sample.ClusterCanalClientTest.main(ClusterCanalClientTest.java:30)
Caused by: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /otter/canal/destinations/example/cluster
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:118)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
	at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:2589)
	at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:2617)
	at org.I0Itec.zkclient.ZkConnection.getChildren(ZkConnection.java:120)
	at org.I0Itec.zkclient.ZkClient$4.call(ZkClient.java:680)
	at org.I0Itec.zkclient.ZkClient$4.call(ZkClient.java:677)
	at org.I0Itec.zkclient.ZkClient.retryUntilConnected(ZkClient.java:991)
	... 5 more

canal-admin 界面上添加的集群跟instance ， 用zk 的方式 client 连接报这个错误

**Comment by shaoyou520** [comment]
zk 里面就没有 /otter的目录

**Comment by agapple** [comment]
你要先让canal-server正常启动成功，就会自动创建zk目录
