### ISSUE TITLE
log event entry exceeded max_allowed_packet

### ISSUE THREAD

**Issue by lan1994** [alibaba/canal#491]
应该是有大事务时，会出现下面的异常，canal会解析不过去。
2018-01-12 12:45:20.537 [destination =xxxx , address = /xxxxxx , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - I/O error while reading from client socket
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = log event entry exceeded max_allowed_packet; Increase max_allowed_packet on master; the first event 'mysql-bin.007177' at 998888207, the last event read from './mysql-bin.007177' at 123, the last byte read from './mysql-bin.007177' at 998888226.
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:95) ~[canal.parse-1.0.19.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:117) [canal.parse-1.0.19.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209) [canal.parse-1.0.19.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_76]

看到有一个关于max_allowed_packet的issues，https://github.com/alibaba/canal/issues/85,  貌似是为了解决这个问题加了组包的逻辑，但是好像没有什么效果，大家有遇到这个问题的么？

**Comment by lcybo** [comment]
可以先看看binlog-row-event-max-size参数设置是多少，定义如下：
https://dev.mysql.com/doc/refman/5.7/en/replication-options-binary-log.html#option_mysqld_binlog-row-event-max-size
binlog-row-event-max-size默认是8k，max_allowed_packet默认是1M。binlog不会将总和>binlog-row-event-max-size的rows合到一个event中，除非单row的size已经超过了这个限制，并且>max_allowed_packet，这个时候只能改max_allowed_packet了。

**Comment by lcybo** [comment]
补充一点，
com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection#updateSettings
看上去是在这里设置max_allowed_packet(需要作者确认下)

**Comment by agapple** [comment]
updateSettings暂时未做max packet大小的调整

**Comment by AnakinSkyW** [comment]
怎么解决啊，我把max_allowed_packet 16mb 加到64还是会有错误

**Comment by agapple** [comment]
建议在mysql端修改全局的max_allowed_packet，canal本身支持多packet的重新组包
