### ISSUE TITLE
com.alibaba.otter.canal.deployer.CanalLauncher

### ISSUE THREAD

**Issue by zuobee** [alibaba/canal#4912]
版本  canal.deployer-1.1.7.tar.gz 操作系统 MANJARO

配置

canal.serverMode = rabbitMQ
rabbitmq.host = 127.0.0.1
rabbitmq.virtual.host = /
rabbitmq.exchange = canal
rabbitmq.username = root
rabbitmq.password = root
rabbitmq.deliveryMode =

2023-10-17 10:00:47.990 [main] INFO  com.alibaba.otter.canal.deployer.CanalLauncher - ## load canal configurations
2023-10-17 10:00:48.062 [main] ERROR com.alibaba.otter.canal.deployer.CanalLauncher - ## Something goes wrong when starting up the canal Server:
java.lang.NullPointerException: null
        at com.rabbitmq.client.impl.ChannelN.validateQueueNameLength(ChannelN.java:1606)
        at com.rabbitmq.client.impl.ChannelN.queueDeclare(ChannelN.java:960)
        at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.queueDeclare(AutorecoveringChannel.java:333)
        at com.alibaba.otter.canal.connector.rabbitmq.producer.CanalRabbitMQProducer.init(CanalRabbitMQProducer.java:75)
        at com.alibaba.otter.canal.connector.core.spi.ProxyCanalMQProducer.init(ProxyCanalMQProducer.java:31)
        at com.alibaba.otter.canal.deployer.CanalStarter.start(CanalStarter.java:72)
        at com.alibaba.otter.canal.deployer.CanalLauncher.main(CanalLauncher.java:124)

**Comment by agapple** [comment]
rabbitmq.queue = xx，这个没配置
