### ISSUE TITLE
CanalKafkaProducer fastjson2 OOM Exception

### ISSUE THREAD

**Issue by tangguoqiang172528725** [alibaba/canal#4923]
- [x] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version 1.17
* mysql version 5.7 huaweicloud 

### Issue Description
推送kafka的代码中fastjson2报内部oom错误

### Steps to reproduce

推送数据到KafkaProducer

### Expected behaviour
应该不发生OOM逐步处理数据

### Actual behaviour

2023-10-27 04:41:22.056 [pool-4-thread-3] ERROR c.a.o.canal.connector.kafka.producer.CanalKafkaProducer - null
java.lang.OutOfMemoryError: null
	at com.alibaba.fastjson2.JSONWriterUTF8.ensureCapacity(JSONWriterUTF8.java:1543)
	at com.alibaba.fastjson2.JSONWriterUTF8.writeString(JSONWriterUTF8.java:483)
	at com.alibaba.fastjson2.writer.OWG_7_14_FlatMessage.write(Unknown Source)
	at com.alibaba.fastjson2.JSON.toJSONBytes(JSON.java:2656)
	at com.alibaba.otter.canal.connector.kafka.producer.CanalKafkaProducer.send(CanalKafkaProducer.java:257)
	at com.alibaba.otter.canal.connector.kafka.producer.CanalKafkaProducer.send(CanalKafkaProducer.java:168)
	at com.alibaba.otter.canal.connector.core.spi.ProxyCanalMQProducer.send(ProxyCanalMQProducer.java:51)
	at com.alibaba.otter.canal.server.CanalMQStarter.worker(CanalMQStarter.java:181)
	at com.alibaba.otter.canal.server.CanalMQStarter.access$100(CanalMQStarter.java:24)
	at com.alibaba.otter.canal.server.CanalMQStarter$CanalMQRunnable.run(CanalMQStarter.java:223)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

**Comment by tangguoqiang172528725** [comment]
可以增加配置修复：

            // 串行分区
            List<FlatMessage> flatMessages = MQMessageUtils.messageConverter(datas, message.getId());
            for (FlatMessage flatMessage : flatMessages) {
                if (mqDestination.getPartitionHash() != null && !mqDestination.getPartitionHash().isEmpty()) {
                    FlatMessage[] partitionFlatMessage = MQMessageUtils.messagePartition(flatMessage,
                        partitionNum,
                        mqDestination.getPartitionHash(),
                        this.mqProperties.isDatabaseHash());
                    int length = partitionFlatMessage.length;
                    for (int i = 0; i < length; i++) {
                        FlatMessage flatMessagePart = partitionFlatMessage[i];
                        if (flatMessagePart != null) {
                            records.add(new ProducerRecord<>(topicName, i, null, JSON.toJSONBytes(flatMessagePart,
                                JSONWriter.Feature.WriteNulls, JSONWriter.Feature.LargeObject)));
                        }
                    }
                } else {
                    final int partition = mqDestination.getPartition() != null ? mqDestination.getPartition() : 0;
                    records.add(new ProducerRecord<>(topicName, partition, null, JSON.toJSONBytes(flatMessage,
                        JSONWriter.Feature.WriteNulls, JSONWriter.Feature.LargeObject)));
                }
            }
