### ISSUE TITLE
1.1.7版本 投递MQ前获取 LogPosition反序列化异常

### ISSUE THREAD

**Issue by CIY-GIT** [alibaba/canal#4926]
版本：1.1.7，具体堆栈如下

com.google.common.util.concurrent.UncheckedExecutionException: com.alibaba.fastjson2.JSONException: No suitable ObjectReader found forcom.alibaba.otter.canal.protocol.position.LogPosition, offset 66, character ", line 1, column 67, fastjson-version 2.0.31 {"@type":"com.alibaba.otter.canal.protocol.position.LogPosition","identity":{"slaveId":-1,"sourceAddress":{"address":"xxx","port":4331}},"postion":{"gtid":"","included":false,"journalName":"mysql-bin.000325","position":15671684,"serverId":180210228,"timestamp":1698745436000}}
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2218)
        at com.google.common.cache.LocalCache.get(LocalCache.java:4147)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4151)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5140)
        at com.google.common.collect.MigrateMap$MigrateConcurrentMap.get(MigrateMap.java:68)
        at com.alibaba.otter.canal.meta.MemoryMetaManager.getCursor(MemoryMetaManager.java:76)
        at com.alibaba.otter.canal.meta.PeriodMixedMetaManager.getCursor(PeriodMixedMetaManager.java:126)
        at com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded.subscribe(CanalServerWithEmbedded.java:181)
        at com.alibaba.otter.canal.server.CanalMQStarter.worker(CanalMQStarter.java:161)
        at com.alibaba.otter.canal.server.CanalMQStarter.access$100(CanalMQStarter.java:24)
        at com.alibaba.otter.canal.server.CanalMQStarter$CanalMQRunnable.run(CanalMQStarter.java:223)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.alibaba.fastjson2.JSONException: No suitable ObjectReader found forcom.alibaba.otter.canal.protocol.position.LogPosition, offset 66, character ", line 1, column 67, fastjson-version 2.0.31 {"@type":"com.alibaba.otter.canal.protocol.position.LogPosition","identity":{"slaveId":-1,"sourceAddress":{"address":"xxx","port":4331}},"postion":{"gtid":"","included":false,"journalName":"mysql-bin.000325","position":15671684,"serverId":180210228,"timestamp":1698745436000}}
        at com.alibaba.fastjson2.reader.ObjectReaderBean.readObject(ObjectReaderBean.java:311)
        at com.alibaba.fastjson2.JSON.parseObject(JSON.java:1249)
        at com.alibaba.otter.canal.common.utils.JsonUtils.unmarshalFromByte(JsonUtils.java:26)
        at com.alibaba.otter.canal.meta.ZooKeeperMetaManager.getCursor(ZooKeeperMetaManager.java:153)
        at com.alibaba.otter.canal.meta.PeriodMixedMetaManager.lambda$start$1(PeriodMixedMetaManager.java:57)
        at com.google.common.collect.MigrateMap$1.load(MigrateMap.java:23)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3708)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2416)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2299)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2212)
        ... 13 common frames omitted

**Comment by agapple** [comment]
本地测试看着没问题，你用的是released的二进制包？

**Comment by CIY-GIT** [comment]
基于 release 分支打包部署，在做HA测试是，发现某个同步任务切换server节点执行时，出现上述异常

**Comment by CIY-GIT** [comment]
已解决，升级 fastjson 至 2.0.40（原 2.0.31）

**Comment by CIY-GIT** [comment]
已解决，升级 fastjson 至 2.0.40（原 2.0.31）
