### ISSUE TITLE
启动运行正常，但DruidDataSource 一直报错，导致cpu飙高

### ISSUE THREAD

**Issue by zyy-zhangfaming** [alibaba/canal#4953]
版本：    image: canal/canal-server:v1.1.7
启动正常，成功作为mysql的slav，接受数据正常，但cpu一直飙高,找到该行代码是dbType没有值的nullpoint，不知道这个是连接的什么
canal.log 报错：
2023-11-14 03:53:13.595 [Druid-ConnectionPool-Create-119775511] ERROR com.alibaba.druid.pool.DruidDataSource - create connection RuntimeException
java.lang.NullPointerException: null
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1746)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2916)
2023-11-14 03:53:13.595 [Druid-ConnectionPool-Create-119775511] ERROR com.alibaba.druid.pool.DruidDataSource - create connection RuntimeException
java.lang.NullPointerException: null
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1746)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2916)
2023-11-14 03:53:13.595 [Druid-ConnectionPool-Create-119775511] ERROR com.alibaba.druid.pool.DruidDataSource - create connection RuntimeException
java.lang.NullPointerException: null
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1746)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2916)
2023-11-14 03:53:13.595 [Druid-ConnectionPool-Create-119775511] ERROR com.alibaba.druid.pool.DruidDataSource - create connection RuntimeException
java.lang.NullPointerException: null
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1746)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2916)
2023-11-14 03:53:13.595 [Druid-ConnectionPool-Create-119775511] ERROR com.alibaba.druid.pool.DruidDataSource - create connection RuntimeException
java.lang.NullPointerException: null
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1746)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2916)
2023-11-14 03:53:13.595 [Druid-ConnectionPool-Create-119775511] ERROR com.alibaba.druid.pool.DruidDataSource - create connection RuntimeException
java.lang.NullPointerException: null

**Comment by shelltea** [comment]
相同的问题，有没有解决方案？

**Comment by shuqidejidan** [comment]
我也遇到了，怎么没多少人反馈，难道是个别环境的问题？

**Comment by a377299578** [comment]
我也遇到这个问题了

**Comment by Moexi2019** [comment]
![image](https://github.com/user-attachments/assets/57f632e7-0b27-43a9-9105-754e9e682c96)

一样
