### ISSUE TITLE
instance停止后，CPU仍然100

### ISSUE THREAD

**Issue by sonymoon** [alibaba/canal#4962]
## Question

<img width="643" alt="image" src="https://github.com/alibaba/canal/assets/6781070/8691486d-fd2d-4c65-8a17-b671ad6fb2a9">

instance配置为：
canal.instance.parser.parallel = true
canal.instance.filter.druid.ddl = true
canal.instance.filter.dml.insert=false
canal.instance.filter.dml.update=false
canal.instance.filter.dml.delete=false

看了很多issue，有说建议parellel 设置为false的，但没说原因

**Comment by watler-peng** [comment]
> ## Question
> `"MultiStageCoprocessor-Parser-dts-fms-0" Id=1088 cpuUsage=99.3% deltaTime=199ms time=4163669ms RUNNABLE at com.lmax.disruptor.BlockingWaitStrategy.waitFor(BlockingWaitStrategy.java:59) at com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(ProcessingSequenceBarrier.java:56) at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:148) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)
> 
> "MultiStageCoprocessor-Parser-dts-fms-4" Id=1092 cpuUsage=99.29% deltaTime=199ms time=4169224ms RUNNABLE at com.lmax.disruptor.BlockingWaitStrategy.waitFor(BlockingWaitStrategy.java:59) at com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(ProcessingSequenceBarrier.java:56) at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:148) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)
> 
> `
> 
> instance配置为： canal.instance.parser.parallel = true canal.instance.filter.druid.ddl = true canal.instance.filter.dml.insert=false canal.instance.filter.dml.update=false canal.instance.filter.dml.delete=false
> 
> 看了很多issue，有说建议parellel 设置为false的，但没说原因

有效吗
