### ISSUE TITLE
错误是： ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address rm-***********************:3306 has an error, retrying. caused by  com.alibaba.otter.canal.parse.exception.CanalParseException: java.lang.IllegalArgumentException: unknow type : 0

### ISSUE THREAD

**Issue by haiyangasd** [alibaba/canal#4963]
数据库版本号：8.0.18
canal 版本号：1.1.7
这个错误反复出现，第一次启动无错，且binlog数据正常发送到kafka .运行几个小时后，出现该错误。
删除mdea.dat，重启服务，数据又可以正常处理，运行一段时间后，又出现上面的问题！
麻烦看一下问题，谢谢！
出现的错误是：
2023-11-22 10:24:14.091 [destination = new_company_binlog , address = rm-****************** , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address ************************* has an error, retrying. caused by 
com.alibaba.otter.canal.parse.exception.CanalParseException: java.lang.IllegalArgumentException: unknow type : 0
Caused by: java.lang.IllegalArgumentException: unknow type : 0
	at com.taobao.tddl.dbsync.binlog.event.TableMapLogEvent.<init>(TableMapLogEvent.java:504) ~[canal.parse.dbsync-1.1.7-SNAPSHOT.jar:na]
	at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:151) ~[canal.parse.dbsync-1.1.7-SNAPSHOT.jar:na]
	at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:80) ~[canal.parse.dbsync-1.1.7-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:269) ~[canal.parse-1.1.7-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:251) ~[canal.parse-1.1.7-SNAPSHOT.jar:na]
	at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168) ~[disruptor-3.4.2.jar:na]
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125) ~[disruptor-3.4.2.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_282]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_282]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_282]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_282]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_282]

**Comment by agapple** [comment]
这块之前没遇到过，可以找一下报错时位点的binlog文件发我，如果能本地复现后可以修复
