### ISSUE TITLE
canal-1.1.7-alpha-1 版本运行一段时间报错

### ISSUE THREAD

**Issue by Tucker-CH** [alibaba/canal#4999]
mysql同步到mysql,
deployer和adapter都是1.1.7版本
运行一段时间后报错停止服务，重启又正常
下面是报错日志
这是deployer的
2023-12-19 04:30:01.599 [New I/O server worker #1-2] ERROR c.a.otter.canal.server.netty.handler.SessionHandler - something goes wrong with channel:[id: 0x4c8feaa4, /127.0.0.1:60464 :> /127.0.0.1:11111], exception=java.nio.channels.ClosedChannelException
	at org.jboss.netty.channel.socket.nio.NioWorker.cleanUpWriteBuffer(NioWorker.java:649)
	at org.jboss.netty.channel.socket.nio.NioWorker.writeFromUserCode(NioWorker.java:370)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleAcceptedSocket(NioServerSocketPipelineSink.java:137)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:76)
	at org.jboss.netty.channel.Channels.write(Channels.java:611)
	at org.jboss.netty.channel.Channels.write(Channels.java:578)
	at com.alibaba.otter.canal.server.netty.NettyUtils.write(NettyUtils.java:49)
	at com.alibaba.otter.canal.server.netty.handler.SessionHandler.messageReceived(SessionHandler.java:333)
	at org.jboss.netty.handler.timeout.IdleStateAwareChannelHandler.handleUpstream(IdleStateAwareChannelHandler.java:48)
	at org.jboss.netty.handler.timeout.IdleStateHandler.messageReceived(IdleStateHandler.java:276)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:302)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.unfoldAndfireMessageReceived(ReplayingDecoder.java:526)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:507)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:444)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:274)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:261)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:350)
	at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:281)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:201)
	at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

2023-12-19 04:30:01.686 [Thread-6] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - stop CannalInstance for null-example 
2023-12-19 04:30:01.769 [Thread-6] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - stop successful....

下面是adapter的日志
2023-12-19 04:30:01.517 [Thread-4] ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - com.alibaba.otter.canal.protocol.exception.CanalClientException: java.io.IOException: end of stream when reading header Error sync and rollback, execute times: 1
2023-12-19 04:30:02.018 [Thread-4] ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - com.alibaba.otter.canal.protocol.exception.CanalClientException: java.io.IOException: Broken pipe Error sync and rollback, execute times: 2
2023-12-19 04:30:02.194 [Thread-6] INFO  c.a.o.canal.adapter.launcher.loader.CanalAdapterService - ## stop the canal client adapters
2023-12-19 04:30:02.224 [pool-9-thread-1] INFO  c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - destination example is waiting for adapters' worker thread die!
2023-12-19 04:30:02.546 [Thread-4] ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - process error!
com.alibaba.otter.canal.protocol.exception.CanalClientException: java.io.IOException: Broken pipe
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.unsubscribe(SimpleCanalConnector.java:285) ~[na:na]
	at com.alibaba.otter.canal.connector.tcp.consumer.CanalTCPConsumer.disconnect(CanalTCPConsumer.java:102) ~[na:na]
	at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.process(AdapterProcessor.java:236) ~[client-adapter.launcher-1.1.7-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_121]
Caused by: java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[na:1.8.0_121]
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47) ~[na:1.8.0_121]
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93) ~[na:1.8.0_121]
	at sun.nio.ch.IOUtil.write(IOUtil.java:65) ~[na:1.8.0_121]
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471) ~[na:1.8.0_121]
	at java.nio.channels.Channels.writeFullyImpl(Channels.java:78) ~[na:1.8.0_121]
	at java.nio.channels.Channels.writeFully(Channels.java:98) ~[na:1.8.0_121]
	at java.nio.channels.Channels.access$000(Channels.java:61) ~[na:1.8.0_121]
	at java.nio.channels.Channels$1.write(Channels.java:174) ~[na:1.8.0_121]
	at java.nio.channels.Channels$WritableByteChannelImpl.write(Channels.java:458) ~[na:1.8.0_121]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.writeWithHeader(SimpleCanalConnector.java:405) ~[na:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.writeWithHeader(SimpleCanalConnector.java:393) ~[na:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.unsubscribe(SimpleCanalConnector.java:269) ~[na:na]
	... 3 common frames omitted
2023-12-19 04:30:02.547 [pool-9-thread-1] INFO  c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - destination example adapters worker thread dead!
2023-12-19 04:30:05.276 [pool-9-thread-1] INFO  com.alibaba.druid.pool.DruidDataSource - {dataSource-2} closing ...
2023-12-19 04:30:05.283 [pool-9-thread-1] INFO  com.alibaba.druid.pool.DruidDataSource - {dataSource-2} closed
2023-12-19 04:30:05.284 [pool-9-thread-1] INFO  c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - destination example all adapters destroyed!
2023-12-19 04:30:05.284 [Thread-6] INFO  c.a.o.canal.adapter.launcher.loader.CanalAdapterLoader - All canal adapters destroyed
2023-12-19 04:30:05.284 [Thread-6] INFO  com.alibaba.druid.pool.DruidDataSource - {dataSource-1} closing ...
2023-12-19 04:30:05.284 [Thread-6] INFO  com.alibaba.druid.pool.DruidDataSource - {dataSource-1} closed
2023-12-19 04:30:05.284 [Thread-6] INFO  c.a.o.canal.adapter.launcher.loader.CanalAdapterService - ## canal client adapters are down.

**Comment by Tucker-CH** [comment]
@agapple
