### ISSUE TITLE
GtidLogEvent.java:80 Caused by: java.lang.NullPointerException

### ISSUE THREAD

**Issue by WorkJun** [alibaba/canal#5035]
canal版本号：1.1.7-SNAPSHOT
mysql版本号：5.6.16

启动server报错如下
CanalParseException: java.lang.NullPointerException
Caused by: java.lang.NullPointerException
	at com.taobao.tddl.dbsync.binlog.event.GtidLogEvent.getLastCommitted(GtidLogEvent.java:80)
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseGTIDLogEvent(LogEventConvert.java:178)
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:132)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:303)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:251)
	at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by agapple** [comment]
#4659
