### ISSUE TITLE
使用client-adapter.rdb模块进行ETL同步，源库为MySQL，数据库名有短横线，读取源数据时报SQL异常

### ISSUE THREAD

**Issue by zoemak** [alibaba/canal#5037]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version
1.1.7
* mysql version
8.0

### Issue Description

使用client-adapter.launcher启动同步客户端，使用client-adapter.rdb模块进行ETL同步，源库为MySQL，数据库名有短横线，读取源数据时报SQL异常

具体原因是源数据库名未加反引号导致

### 相关Issue：

#4482 此issue只解决了目标数据库的反引号问题，但是漏了源库的相同问题

#### 1）改源码办法：

修改com.alibaba.otter.canal.client.adapter.rdb.service.RdbEtlService#importData：
```java
    public EtlResult importData(List<String> params) {
        DbMapping dbMapping = config.getDbMapping();
        // 获取源数据源，根据数据库类型拼装数据库名和表名
        DruidDataSource dataSource = DatasourceConfig.DATA_SOURCES.get(config.getDataSourceKey());
        String sql = "SELECT * FROM " + SyncUtil.getDbTableName(dbMapping, dataSource.getDbType());
        return importData(sql, params);
    }
```

#### 2）1.1.7不改源码办法：

在同一个groupId下，创建两个Adapter，一个用来手工ELT，数据库名字要加上反引号，另一个用来自动同步，数据库名字不要加反引号；
因为同属一个destination和group，在手工ELT时会锁住自动同步task，所以不需要担心会同时写入的问题。

test_etl.yml：
```
dataSourceKey: defaultDS
destination: test
groupId: g1 # 相同group
outerAdapterKey: mysql1 # 不同outerAdapterKey
concurrent: true
dbMapping:
  database: "`data-prod`" # 反引号包裹数据库名，然后双引号再包裹反引号
  table: date_table
  targetTable: date_table
  targetPk:
    id: id
  mapAll: true
  etlCondition: "where date_val>={} and date_val<={}" # 手工同步条件
  commitBatch: 1000 # 批量提交的大小
```

test_auto.yml：
```
destination: test
groupId: g1 # 相同group
outerAdapterKey: mysql2 # 不同outerAdapterKey
concurrent: true
dbMapping:
  database: data-prod
  table: date_table
  targetTable: date_table
  targetPk:
    id: id
  mapAll: true
  commitBatch: 1000 # 批量提交的大小
```

application.yml：
```
  srcDataSources:
    defaultDS:
      url: jdbc:mysql://localhost:3306/data-prod?useUnicode=true&charset=utf8mb4&useSSL=false
      username: root
      password: 123456
  canalAdapters:
  - instance: test # canal instance Name or mq topic name
    groups:
    - groupId: g1
      outerAdapters:
        - name: rdb
          key: mysql1
          properties:
            jdbc.driverClassName: com.mysql.jdbc.Driver
            jdbc.url: jdbc:mysql://localhost:3306/test?useUnicode=true&charset=utf8mb4&useSSL=false
            jdbc.username: root
            jdbc.password: 123456
            druid.stat.enable: true
            druid.stat.slowSqlMillis: 10000
        - name: rdb
          key: mysql2
          properties:
            jdbc.driverClassName: com.mysql.jdbc.Driver
            jdbc.url: jdbc:mysql://localhost:3306/test?useUnicode=true&charset=utf8mb4&useSSL=false
            jdbc.username: root
            jdbc.password: 123456
            druid.stat.enable: true
            druid.stat.slowSqlMillis: 10000
``` 

### Actual behaviour

If there is an exception, please attach the exception trace:

```
2024-01-17 17:01:58.785 [http-nio-8081-exec-1] DEBUG c.a.otter.canal.client.adapter.rdb.service.RdbEtlService - etl sql : SELECT * FROM data-prod.date_table where date_val>=? and date_val<=?
2024-01-17 17:01:58.821 [http-nio-8081-exec-1] ERROR com.alibaba.otter.canal.client.adapter.support.Util - sqlRs has error, sql: SELECT COUNT(1) FROM ( SELECT * FROM data-prod.date_table where date_val>=? and date_val<=?) _CNT  
2024-01-17 17:01:58.823 [http-nio-8081-exec-1] ERROR c.a.otter.canal.client.adapter.rdb.service.RdbEtlService - com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-prod.date_table where date_val>='2020-01-01 00:00:00' and date_val<=' at line 1
java.lang.RuntimeException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-prod.date_table where date_val>='2020-01-01 00:00:00' and date_val<=' at line 1
	at com.alibaba.otter.canal.client.adapter.support.Util.sqlRS(Util.java:67)
	at com.alibaba.otter.canal.client.adapter.support.AbstractEtlService.importData(AbstractEtlService.java:62)
	at com.alibaba.otter.canal.client.adapter.rdb.service.RdbEtlService.importData(RdbEtlService.java:45)
	at com.alibaba.otter.canal.client.adapter.rdb.RdbAdapter.etl(RdbAdapter.java:174)
	at com.alibaba.otter.canal.adapter.launcher.rest.CommonRest.etl(CommonRest.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1064)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1726)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-prod.date_table where date_val>='2020-01-01 00:00:00' and date_val<=' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1912)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2020)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:213)
	at com.alibaba.otter.canal.client.adapter.support.Util.sqlRS(Util.java:61)
	... 54 common frames omitted

```

**Comment by zoemak** [comment]
fixed, closed
