### ISSUE TITLE
com.alibaba.druid.sql.parser.ParserException: illegal name, pos 6800, line 119, column 3, token FROM

### ISSUE THREAD

**Issue by white-bridge** [alibaba/canal#5040]
## Question

CREATE TABLE sb_users_access_token (
	id int(11) NOT NULL AUTO_INCREMENT,
	uid int(11) NOT NULL DEFAULT '0' COMMENT '用户ID',
	from tinyint(3) NOT NULL DEFAULT '0' COMMENT '来源 1QQ 2微信 3微博',
	access_code varchar(20) NOT NULL DEFAULT '' COMMENT '临时code',
	access_token varchar(200) NOT NULL DEFAULT '' COMMENT '授权token',
	expires_in int(11) NOT NULL DEFAULT '0' COMMENT '过期时间',
	refresh_token varchar(200) NOT NULL DEFAULT '' COMMENT '刷新token',
	openid varchar(255) NOT NULL DEFAULT '' COMMENT '授权用户唯一标识',
	scope varchar(60) NOT NULL COMMENT '授权范围',
	status tinyint(3) NOT NULL DEFAULT '1' COMMENT '1 ',
	json_info text NOT NULL COMMENT '个人信息',
	create_time timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '创建时间',
	unionid varchar(128) NOT NULL DEFAULT '' COMMENT 'UnionID',
	session_key varchar(128) NOT NULL DEFAULT '' COMMENT '小程序session_key',
	PRIMARY KEY (id),
	KEY uid (uid),
	KEY idx_openid_from_status (openid, from, status),
	KEY idx_access_token (access_token),
	KEY idx_uid_from_status (uid, from, status),
	KEY idx_unionid_from_status (unionid, from, status)
) ENGINE = InnoDB AUTO_INCREMENT = 7831300 CHARSET = utf8 COMMENT '用户第三方登录表';

com.alibaba.druid.sql.parser.ParserException: illegal name, pos 6800, line 119, column 3, token FROM
	at com.alibaba.druid.sql.parser.SQLExprParser.name(SQLExprParser.java:2373)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.parseColumn(MySqlExprParser.java:981)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlCreateTableParser.parseCreateTable(MySqlCreateTableParser.java:435)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseCreate(MySqlStatementParser.java:296)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:245)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:599)
	at com.alibaba.druid.sql.repository.SchemaRepository.console(SchemaRepository.java:468)
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta.apply(MemoryTableMeta.java:85)
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.buildMemFromSnapshot(DatabaseTableMeta.java:423)
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:166)
	at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:145)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:192)
	at java.lang.Thread.run(Thread.java:750)
这种怎么处理啊 我也不能改数据表的名称啊

**Comment by agapple** [comment]
https://github.com/alibaba/canal/issues/4899，应该是这个问题，最新1.1.8-alpha-1的包试试

**Comment by dyrnq** [comment]
@white-bridge 你列名中包含关键字`from`的，为啥要这样`from tinyint(3) NOT NULL DEFAULT '0' COMMENT '来源 1QQ 2微信 3微博',`
