### ISSUE TITLE
canal 1.1.6 连接 MySQL 8.3.0 报错

### ISSUE THREAD

**Issue by LiHanGod** [alibaba/canal#5061]
- [X] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [X] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version
- 1.1.6
* mysql version
- 8.3.0

### Issue Description
BASE TABLE 这个是什么
```sh
show create table `bigdata`.`user_info`;show create table `bigdata`.`BASE TABLE`;
```
### Steps to reproduce

使用Docker canal/canal-server:v1.1.6 连接 MySQL

### Expected behaviour

没有异常

### Actual behaviour

出现异常

If there is an exception, please attach the exception trace:

```
2024-03-01 23:54:30.900 [destination = example , address = mysql-local/172.19.0.10:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: ErrorPacket [errorNumber=1146, fieldCount=-1, message=Table 'bigdata.BASE TABLE' doesn't exist, sqlState=42S02, sqlStateMarker=#]
 with command: show create table `bigdata`.`user_info`;show create table `bigdata`.`BASE TABLE`;
Caused by: java.io.IOException: ErrorPacket [errorNumber=1146, fieldCount=-1, message=Table 'bigdata.BASE TABLE' doesn't exist, sqlState=42S02, sqlStateMarker=#]
 with command: show create table `bigdata`.`user_info`;show create table `bigdata`.`BASE TABLE`;
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlQueryExecutor.queryMulti(MysqlQueryExecutor.java:109)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.queryMulti(MysqlConnection.java:111)
        at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.dumpTableMeta(DatabaseTableMeta.java:233)
        at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:174)
        at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:142)
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:197)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by agapple** [comment]
canal老版本的问题，可以升级下版本

**Comment by agapple** [comment]
canal老版本的问题，可以升级下版本
