### ISSUE TITLE
Canal 1.1.7启动报错，无法识别部分DDL

### ISSUE THREAD

**Issue by dengzhihang** [alibaba/canal#5074]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

只有部分库消费会出现此类错误, 作为对比，1.1.6版本没有出现此类错误
### environment

* canal version  1.1.7
* mysql version 5.7.30

### Issue Description
WARN  c.a.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta - parse faield : CREATE TABLE  XXX
建表语句

com.alibaba.druid.sql.parser.ParserException: illegal name, pos 855938, line 13850, column 7, token UPDATE
at com.alibaba.druid.sql.parser.SQLExprParser.name(SQLExprParser.java:2370)
	at com.alibaba.druid.sql.parser.SQLExprParser.parseIndex(SQLExprParser.java:5461)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlCreateTableParser.parseConstraint(MySqlCreateTableParser.java:1709)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlCreateTableParser.parseCreateTable(MySqlCreateTableParser.java:405)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseCreate(MySqlStatementParser.java:296)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:245)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:599)
	at com.alibaba.druid.sql.repository.SchemaRepository.console(SchemaRepository.java:468)
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta.apply(MemoryTableMeta.java:85)
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.buildMemFromSnapshot(DatabaseTableMeta.java:423)
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:166)
	at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:145)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:192)
	at java.base/java.lang.Thread.run(Thread.java:831)

### Actual behaviour

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by agapple** [comment]
提供下完整的parse failed涉及的DDL语句
