### ISSUE TITLE
1.1.7版本运行一天左右就会报错，报错是说的消息太大了，但是把实例停止后重新新建一个实例运行就又没有问题了，有大佬遇到过么，球球

### ISSUE THREAD

**Issue by XJFLHM** [alibaba/canal#5081]
启动运行一天左右就会报这个错，看起来说的是消息体发送的大小超过了kafka接收的设置，但是kafka设置的大小是int的最大值，也就是2147483647，而canal集群中的设置是2147483640，按理肯定不会报错，而且我也观察了数据库中的字符长度也不会超过。但是把实例停止后重新新建一个实例运行就又没有问题了。有大佬遇到过么
![image](https://github.com/alibaba/canal/assets/162985785/6591eef4-e02b-4262-8269-2ad6bb5f6a31)

Caused by: org.apache.kafka.common.errors.RecordTooLargeException: The request included a message larger than the max message size the server will accept.
2024-03-25 10:15:40.525 [pool-10-thread-2] ERROR c.a.o.canal.connector.kafka.producer.CanalKafkaProducer - java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.RecordTooLargeException: The request included a message larger than the max message size the server will accept.
java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.RecordTooLargeException: The request included a message larger than the max message size the server will accept.
	at com.alibaba.otter.canal.connector.kafka.producer.CanalKafkaProducer.send(CanalKafkaProducer.java:186)
	at com.alibaba.otter.canal.connector.core.spi.ProxyCanalMQProducer.send(ProxyCanalMQProducer.java:51)
	at com.alibaba.otter.canal.server.CanalMQStarter.worker(CanalMQStarter.java:181)
	at com.alibaba.otter.canal.server.CanalMQStarter.access$100(CanalMQStarter.java:24)
	at com.alibaba.otter.canal.server.CanalMQStarter$CanalMQRunnable.run(CanalMQStarter.java:223)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.RecordTooLargeException: The request included a message larger than the max message size the server will accept.
	at org.apache.kafka.clients.producer.internals.FutureRecordMetadata.valueOrError(FutureRecordMetadata.java:98)
	at org.apache.kafka.clients.producer.internals.FutureRecordMetadata.get(FutureRecordMetadata.java:67)
	at org.apache.kafka.clients.producer.internals.FutureRecordMetadata.get(FutureRecordMetadata.java:30)
	at com.alibaba.otter.canal.connector.kafka.producer.CanalKafkaProducer.send(CanalKafkaProducer.java:184)
	... 7 common frames omitted

**Comment by binbingin** [comment]
应该是kafka服务端那边的message max size之类的配置要调大， canal里的是客户端配置

**Comment by XJFLHM** [comment]
> 应该是kafka服务端那边的message max size之类的配置要调大， canal里的是客户端配置

但是我已经把kafka的消息接收配置配到最大了，是int的最大数值。而且我数据里面的长度确实也没有那么长，很奇怪

**Comment by Zy-THOMAS** [comment]
topic max.message.bytes 参数设置了吗？

**Comment by forachange** [comment]
也存在类似问题。 后来调整了 canal.properties 里的 kafka.max.request.size，以及  kafka broker 端 topic 的 max.message.size 
```
bin/kafka-configs.sh --zookeeper localhost:2181 --entity-type topics --entity-name my-topic
      --alter --add-config max.message.bytes=128000
```
(参考 https://kafka.apache.org/21/documentation.html#topicconfigs)

目前运行运行正常

**Comment by agapple** [comment]
点赞LS
