### ISSUE TITLE
怎么会去找`cap`.`published`表? 这个表不存在 , 数据库cap也不存在.

### ISSUE THREAD

**Issue by ap0405140** [alibaba/canal#5085]
MySQL 8.0.34,  win10, 服务端用canal.deployer-1.1.7.tar.gz,
logs\example\example.log里报错如下? 怎么会去找`cap`.`published`表? 这个表不存在.
2024-03-30 17:39:44.471 [destination = example , address = /127.0.0.1:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address /127.0.0.1:3306 has an error, retrying. caused by 
com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: ErrorPacket [errorNumber=1049, fieldCount=-1, message=Unknown database 'cap', sqlState=42000, sqlStateMarker=#]
 with command: show create table `cap`.`published`
Caused by: java.io.IOException: ErrorPacket [errorNumber=1049, fieldCount=-1, message=Unknown database 'cap', sqlState=42000, sqlStateMarker=#]
 with command: show create table `cap`.`published`
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlQueryExecutor.query(MysqlQueryExecutor.java:61)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.query(MysqlConnection.java:106)
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.compareTableMetaDbAndMemory(DatabaseTableMeta.java:370)
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.applySnapshotToDB(DatabaseTableMeta.java:322)
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:176)
	at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:145)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:192)
	at java.lang.Thread.run(Unknown Source)

**Comment by agapple** [comment]
可以通过订阅规则过滤掉
