### ISSUE TITLE
 Value too long for column "CHARACTER VARYING"

### ISSUE THREAD

**Issue by dly667** [alibaba/canal#5086]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment
ubuntu20

* canal version
*[1.1.8-alpha](https://github.com/alibaba/canal/releases/tag/canal-1.1.8-alpha-1)

* mysql version
mysql  Ver 14.14 Distrib 5.7.42, for Linux (x86_64) using  EditLine wrapper

### Issue Description
2024-03-30 20:17:20.511 [main] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - start successful....
2024-03-30 20:17:20.512 [destination = example , address = /127.0.0.1:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - prepare to find start position just show master status
2024-03-30 20:17:20.517 [destination = example , address = /127.0.0.1:3306 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.MysqlConnection - load MySQL @@version_comment : MySQL Community Server (GPL)
2024-03-30 20:17:22.855 [destination = example , address = /127.0.0.1:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address /127.0.0.1:3306 has an error, retrying. caused by 
com.alibaba.otter.canal.parse.exception.CanalParseException: apply failed caused by : nested exception is org.apache.ibatis.type.TypeException: Could not set parameters for mapping: ParameterMapping{property='data', mode=IN, javaType=class java.lang.String, jdbcType=null, numericScale=null, resultMapId='null', jdbcTypeName='null', expression='null'}. Cause: org.apache.ibatis.type.TypeException: Error setting non null for parameter #6 with JdbcType null . Try setting a different JdbcType for this parameter or a different configuration property. Cause: org.h2.jdbc.JdbcSQLDataException: Value too long for column "CHARACTER VARYING": "{""`dev_aiguo_renew`"":""CREATE TABLE `a_ jindu_monitor_log` (\\n\\t`jindu_monitor_lo... (1407702)" [22001-210]
Caused by: org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.type.TypeException: Could not set parameters for mapping: ParameterMapping{property='data', mode=IN, javaType=class java.lang.String, jdbcType=null, numericScale=null, resultMapId='null', jdbcTypeName='null', expression='null'}. Cause: org.apache.ibatis.type.TypeException: Error setting non null for parameter #6 with JdbcType null . Try setting a different JdbcType for this parameter or a different configuration property. Cause: org.h2.jdbc.JdbcSQLDataException: Value too long for column "CHARACTER VARYING": "{""`dev_aiguo_renew`"":""CREATE TABLE `a_ jindu_monitor_log` (\\n\\t`jindu_monitor_lo... (1407702)" [22001-210]
        at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:92)
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:440)
        at com.sun.proxy.$Proxy10.insert(Unknown Source)
        at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:271)
        at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:62)
        at org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:152)
        at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:85)
        at com.sun.proxy.$Proxy11.insert(Unknown Source)
        at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.dao.MetaSnapshotDAO.insert(MetaSnapshotDAO.java:17)
        at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.applySnapshotToDB(DatabaseTableMeta.java:345)
        at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:176)
        at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:145)
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:192)
        at java.lang.Thread.run(Thread.java:750)
我试了1.1.8和1.1.7相同的错误
1.1.6运行正常
### Actual behaviour

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by zkyl0915** [comment]
> 遇见相同的问题，升级h2的jar，使用2.2.224版本替换2.1.210版本。

升级jar包后解决这个问题了吗？

**Comment by sgjr** [comment]
> > 遇见相同的问题，升级h2的jar，使用2.2.224版本替换2.1.210版本。
> 
> 升级jar包后解决这个问题了吗？

我也遇到这个问题了，升级了就可以了

**Comment by gochiel** [comment]
这个怎么升级的？

**Comment by sgjr** [comment]
> 这个怎么升级的？

下载一个jar包，替换掉旧的包就行

**Comment by bluefoxyu** [comment]
> > 这个怎么升级的？
> 
> 下载一个jar包，替换掉旧的包就行

换了Java包报了新的错误怎么办com.alibaba.otter.canal.parse.exception.CanalParseException: apply failed caused by : nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.alibaba.druid.pool.DataSourceClosedException: dataSource already closed at Mon Dec 02 14:00:24 CST 2024
### The error may exist in spring/tsdb/sql-map/sqlmap_snapshot.xml
### The error may involve com.alibaba.otter.canal.parse.inbound.mysql.tsdb.dao.MetaSnapshotMapper.findByTimestamp
### The error occurred while executing a query
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.alibaba.druid.pool.DataSourceClosedException: dataSource already closed at Mon Dec 02 14:00:24 CST 2024
Caused by: org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.alibaba.druid.pool.DataSourceClosedException: dataSource already closed at Mon Dec 02 14:00:24 CST 2024
### The error may exist in spring/tsdb/sql-map/sqlmap_snapshot.xml
### The error may involve com.alibaba.otter.canal.parse.inbound.mysql.tsdb.dao.MetaSnapshotMapper.findByTimestamp
### The error occurred while executing a query
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.alibaba.druid.pool.DataSourceClosedException: dataSource already closed at Mon Dec 02 14:00:24 CST 2024
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBati

**Comment by sgjr** [comment]
> > > 这个怎么升级的？
> > 
> > 
> > 下载一个jar包，替换掉旧的包就行
> 
> 换了Java包报了新的错误怎么办com.alibaba.otter.canal.parse.exception.CanalParseException: apply failed caused by : nested exception is org.apache.ibatis.exceptions.PersistenceException:
> 
> ### Error querying database. Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.alibaba.druid.pool.DataSourceClosedException: dataSource already closed at Mon Dec 02 14:00:24 CST 2024
> ### The error may exist in spring/tsdb/sql-map/sqlmap_snapshot.xml
> ### The error may involve com.alibaba.otter.canal.parse.inbound.mysql.tsdb.dao.MetaSnapshotMapper.findByTimestamp
> ### The error occurred while executing a query
> ### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.alibaba.druid.pool.DataSourceClosedException: dataSource already closed at Mon Dec 02 14:00:24 CST 2024
> Caused by: org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException:
> 
> ### Error querying database. Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.alibaba.druid.pool.DataSourceClosedException: dataSource already closed at Mon Dec 02 14:00:24 CST 2024
> ### The error may exist in spring/tsdb/sql-map/sqlmap_snapshot.xml
> ### The error may involve com.alibaba.otter.canal.parse.inbound.mysql.tsdb.dao.MetaSnapshotMapper.findByTimestamp
> ### The error occurred while executing a query
> ### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.alibaba.druid.pool.DataSourceClosedException: dataSource already closed at Mon Dec 02 14:00:24 CST 2024
> ```
> at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBati
> ```

更换完包之后需要将旧的元数据文件删除，重启canal-server让它重新生成，因为新的包不兼容旧包的元数据格式

**Comment by DWFLZXJ** [comment]
试过可以 折腾了好久 感谢

**Comment by yeshulin9849** [comment]
元数据文件是哪个
