### ISSUE TITLE
canal连接rabbitmq启动报错

### ISSUE THREAD

**Issue by JayLeonX** [alibaba/canal#5088]
2024-03-31 14:30:48.711 [main] INFO  com.alibaba.otter.canal.deployer.CanalLauncher - ## set default uncaught exception handler
2024-03-31 14:30:48.715 [main] INFO  com.alibaba.otter.canal.deployer.CanalLauncher - ## load canal configurations
2024-03-31 14:30:48.831 [main] ERROR com.alibaba.otter.canal.deployer.CanalLauncher - ## Something goes wrong when starting up the canal Server:
java.lang.NullPointerException: null
	at com.rabbitmq.client.impl.ChannelN.validateQueueNameLength(ChannelN.java:1606)
	at com.rabbitmq.client.impl.ChannelN.queueDeclare(ChannelN.java:960)
	at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.queueDeclare(AutorecoveringChannel.java:333)
	at com.alibaba.otter.canal.connector.rabbitmq.producer.CanalRabbitMQProducer.init(CanalRabbitMQProducer.java:75)
	at com.alibaba.otter.canal.connector.core.spi.ProxyCanalMQProducer.init(ProxyCanalMQProducer.java:31)
	at com.alibaba.otter.canal.deployer.CanalStarter.start(CanalStarter.java:72)
	at com.alibaba.otter.canal.deployer.CanalLauncher.main(CanalLauncher.java:124)

canal.properties部分配置
rabbitmq.host = 192.168.184.129
rabbitmq.virtual.host = /xzb
rabbitmq.exchange = exchange.canal-jzo2o
rabbitmq.username = xzb
rabbitmq.password = xzb
rabbitmq.deliveryMode = 2

容器启动
docker run -d \
    --name jzo2o_canal \
    -p 11111:11111 \
    -v /home/canal/instance.properties:/home/admin/canal-server/conf/example/instance.properties  \
    -v /home/canal/canal.properties:/home/admin/canal-server/conf/canal.properties \
    -v /home/canal/logs:/home/admin/canal-server/logs/xzb-canal \
    -v /home/canal/conf:/home/admin/canal-server/conf/xzb-canal \
    canal/canal-server:latest

配置文件映射我看都成功了，难道是配置问内容有问题吗

**Comment by JayLeonX** [comment]
# position info
canal.instance.master.address=192.168.184.129:23306
canal.instance.master.journal.name=mysql-bin.000001
canal.instance.master.position=0
canal.instance.master.timestamp=
canal.instance.master.gtid=

现在又变成canal.logs一直在报错：
2024-03-31 16:04:51.154 [Druid-ConnectionPool-Create-572869215] ERROR com.alibaba.druid.pool.DruidDataSource - create connection RuntimeException
java.lang.NullPointerException: null
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1746)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2916)

是mysql连接不上的问题吗，但我在客户端连接mysql都试过可以

**Comment by JayLeonX** [comment]
现在问题解决了，canal版本从1.1.7换成了1.1.5，mysql版本8.0.26，rabbitmq版本3.9.17-management-delayed

改了版本1.1.5后，又遇到`Could not find first log file name in binary log index file`问题，这个解决的话是把`canal.instance.master.journal.name=`设为空，走默认，之前一直设置为mysql-bin.000001，不行。


成功运行后，贴部分配置如下：

canal.properties
```##################################################
#########                   RabbitMQ         #############
##################################################
rabbitmq.host = 192.168.184.129
rabbitmq.virtual.host = /xzb
rabbitmq.exchange = exchange.canal-jzo2o
rabbitmq.username = xzb
rabbitmq.password = xzb
rabbitmq.deliveryMode = 2
```

instance.properties
```# position info
canal.instance.master.address=192.168.184.129:23306
canal.instance.master.journal.name=
canal.instance.master.position=
canal.instance.master.timestamp=
canal.instance.master.gtid=
```

docker启动
```
docker run -d \
    --name jayleon_canal \
    -p 11111:11111 \
    -v /home/canal/instance.properties:/home/admin/canal-server/conf/xzb-canal/instance.properties  \
    -v /home/canal/canal.properties:/home/admin/canal-server/conf/canal.properties \
    -v /home/canal/logs:/home/admin/canal-server/logs/xzb-canal \
    -v /home/canal/conf:/home/admin/canal-server/conf/xzb-canal \
    canal/canal-server:v1.1.5
```

**Comment by tidy-oly** [comment]
我也在1.1.7版本遇到了这个错误，把mq的队列名称改短就好了，希望可以帮助到你。
