### ISSUE TITLE
canal client拉取binlog，server端报错java.nio.channels.ClosedByInterruptException: null

### ISSUE THREAD

**Issue by hutao1990** [alibaba/canal#509]
-------------------------------------------------------------------------------------------
2018-01-26 14:04:56.245  INFO 121070 --- [       Thread-4] com.gome.canalmq.service.MonitorService  : lmis speed:2461.1record/sec  can
al speed:6273.7record/sec
2018-01-26 14:05:06.245  INFO 121070 --- [       Thread-4] com.gome.canalmq.service.MonitorService  : lmis speed:3666.6record/sec  can
al speed:8312.6record/sec
2018-01-26 14:05:16.246  INFO 121070 --- [       Thread-4] com.gome.canalmq.service.MonitorService  : lmis speed:4077.8record/sec  can
al speed:12065.4record/sec
2018-01-26 14:05:26.246  INFO 121070 --- [       Thread-4] com.gome.canalmq.service.MonitorService  : lmis speed:2859.6record/sec  can
al speed:6839.5record/sec
26
2018-01-26 14:05:36.246  INFO 121070 --- [       Thread-4] com.gome.canalmq.service.MonitorService  : lmis speed:329.2record/sec  cana
l speed:920.5record/sec
27
2018-01-26 14:05:46.246  INFO 121070 --- [       Thread-4] com.gome.canalmq.service.MonitorService  : lmis speed:149.3record/sec  cana
l speed:419.7record/sec
2018-01-26 14:05:56.247  INFO 121070 --- [       Thread-4] com.gome.canalmq.service.MonitorService  : lmis speed:76.4record/sec  canal
 speed:212.2record/sec
2018-01-26 14:06:06.247  INFO 121070 --- [       Thread-4] com.gome.canalmq.service.MonitorService  : lmis speed:23.6record/sec  canal
 speed:68.9record/sec
2018-01-26 14:06:16.248  INFO 121070 --- [       Thread-4] com.gome.canalmq.service.MonitorService  : lmis speed:58.0record/sec  canal
 speed:165.8record/sec
2018-01-26 14:06:26.248  INFO 121070 --- [       Thread-4] com.gome.canalmq.service.MonitorService  : lmis speed:38.7record/sec  canal
 speed:108.9record/sec
2018-01-26 14:06:36.248  INFO 121070 --- [       Thread-4] com.gome.canalmq.service.MonitorService  : lmis speed:29.9record/sec  canal
 speed:86.6record/sec
-------------------------------------------------------------------------------------------

2018-01-26 14:05:22.693 [destination = lmis65 , address = /10.128.35.65:3306 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - dump address 10.128.35.65/10.128.35.65:3306 has an error, retrying. caused by 
java.nio.channels.ClosedByInterruptException: null
        at com.alibaba.otter.canal.parse.driver.mysql.socket.SocketChannel.read(SocketChannel.java:49) ~[canal.parse.driver-1.0.25.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:151) ~[canal.parse-1.0.25.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:77) ~[canal.parse-1.0.25.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:137) ~[canal.parse-1.0.25.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:220) ~[canal.parse-1.0.25.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
2018-01-26 14:05:22.697 [destination = lmis65 , address = /10.128.35.65:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:lmis65[java.nio.channels.ClosedByInterruptException
        at com.alibaba.otter.canal.parse.driver.mysql.socket.SocketChannel.read(SocketChannel.java:49)
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:151)
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:77)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:137)
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:220)
        at java.lang.Thread.run(Thread.java:745)
]
2018-01-26 14:05:41.309 [destination = lmis65 , address = /10.128.35.65:3306 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - prepare to find start position just last position
 {"identity":{"slaveId":-1,"sourceAddress":{"address":"10.128.35.65","port":3306}},"postion":{"included":false,"journalName":"mysql-bin.003759","position":891656455,"serverId":1,"timestamp":1516929456000}}

**Comment by hutao1990** [comment]
环境 canal版本1.0.25 ，zk管理，centos7.2 ，mysql版本5.7.11

**Comment by hutao1990** [comment]
canal 1.0.25和1.0.26很慢，我换到老版本1.0.24就没问题了

**Comment by JackEggie** [comment]
我也是降到1.0.24就没问题了。在1.0.25下就会报错

```
2018-01-25 19:36:37.799 [destination = databus , address = /127.0.0.1:43306 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - parse events has an error
com.alibaba.otter.canal.parse.exception.CanalParseException: dump address /127.0.0.1:43306 has an error, retrying.
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: connect /127.0.0.1:43306 failure
Caused by: java.io.IOException: connect /127.0.0.1:43306 failure
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:72) ~[canal.parse.driver-1.0.25.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.connect(MysqlConnection.java:71) ~[canal.parse-1.0.25.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.preDump(MysqlEventParser.java:88) ~[canal.parse-1.0.25.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:160) ~[canal.parse-1.0.25.jar:na]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.7.0_79]
Caused by: java.nio.channels.ClosedByInterruptException: null
        at com.alibaba.otter.canal.parse.driver.mysql.socket.SocketChannel.read(SocketChannel.java:55) ~[canal.parse.driver-1.0.25.jar:na]
        at com.alibaba.otter.canal.parse.driver.mysql.utils.PacketManager.readHeader(PacketManager.java:12) ~[canal.parse.driver-1.0.25.jar:na]
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.negotiate(MysqlConnector.java:148) ~[canal.parse.driver-1.0.25.jar:na]
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:69) ~[canal.parse.driver-1.0.25.jar:na]
        ... 4 common frames omitted
```

**Comment by agapple** [comment]
建议升级到26版本，解决了超时时间过短以及链接mysql切回bio的模式
