### ISSUE TITLE
windows系统canal1.1.7整合rabbitmq启动canal服务报错

### ISSUE THREAD

**Issue by SaviourChu** [alibaba/canal#5091]
windows系统canal1.1.7整合rabbitmq启动canal服务报错，canal降低到canal1.1.6和canal1.1.5均能正常启动
2024-04-01 14:08:36.102 [main] INFO  com.alibaba.otter.canal.deployer.CanalLauncher - ## set default uncaught exception handler
2024-04-01 14:08:36.108 [main] INFO  com.alibaba.otter.canal.deployer.CanalLauncher - ## load canal configurations
2024-04-01 14:08:36.193 [main] ERROR com.alibaba.otter.canal.deployer.CanalLauncher - ## Something goes wrong when starting up the canal Server:
java.lang.NullPointerException: null
	at com.rabbitmq.client.impl.ChannelN.validateQueueNameLength(ChannelN.java:1606)
	at com.rabbitmq.client.impl.ChannelN.queueDeclare(ChannelN.java:960)
	at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.queueDeclare(AutorecoveringChannel.java:333)
	at com.alibaba.otter.canal.connector.rabbitmq.producer.CanalRabbitMQProducer.init(CanalRabbitMQProducer.java:75)
	at com.alibaba.otter.canal.connector.core.spi.ProxyCanalMQProducer.init(ProxyCanalMQProducer.java:31)
	at com.alibaba.otter.canal.deployer.CanalStarter.start(CanalStarter.java:72)
	at com.alibaba.otter.canal.deployer.CanalLauncher.main(CanalLauncher.java:124)

**Comment by JayLeonX** [comment]
感谢，我昨天一直用的1.1.7失败，今天换成1.1.5可以了

**Comment by xiejx618** [comment]
对于使用rabbitmq，admin界面
server管理下的几个核心配置

canal.serverMode = rabbitMQ
rabbitmq.host = localhost
rabbitmq.virtual.host = /
rabbitmq.username = test
rabbitmq.password = test
rabbitmq.exchange = canal_exchange  
rabbitmq.routingKey = canal_routing_key    #通过看源码觉得要补上的配置
rabbitmq.queue = canal_queue                    #通过看源码觉得要补上的配置
rabbitmq.deliveryMode = direct                  #有的文章设rabbitmq.deliveryMode为2也是骗人的

instance的核心配置
canal.mq.topic=canal_routing_key   #这坑货家伙. 竟然将routing key作为topic

**Comment by agapple** [comment]
https://github.com/alibaba/canal/pull/5089/files
