### ISSUE TITLE
canal.adapte.1.1.7启动报空指针

### ISSUE THREAD

**Issue by mawenbin666** [alibaba/canal#5119]
## canal.adapte.1.1.7启动报空指针
我检查了配置也没问题

`024-04-25 14:50:57.055 [main] INFO  c.a.o.c.client.adapter.es.core.config.ESSyncConfigLoader - ## ES mapping config loaded
2024-04-25 14:50:57.392 [main] INFO  c.a.o.canal.adapter.launcher.loader.CanalAdapterLoader - Load canal adapter: es7 succeed
2024-04-25 14:50:57.400 [main] INFO  c.alibaba.otter.canal.connector.core.spi.ExtensionLoader - extension classpath dir: /usr/local/canal.adapter-1.1.7/plugin
2024-04-25 14:50:57.413 [main] ERROR c.a.o.canal.adapter.launcher.loader.CanalAdapterService - ## something goes wrong when starting up the canal client adapters:
java.lang.NullPointerException: null
        at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.<init>(AdapterProcessor.java:71)
        at com.alibaba.otter.canal.adapter.launcher.loader.CanalAdapterLoader.lambda$init$0(CanalAdapterLoader.java:85)
        at java.util.HashMap.computeIfAbsent(HashMap.java:1127)
        at com.alibaba.otter.canal.adapter.launcher.loader.CanalAdapterLoader.init(CanalAdapterLoader.java:81)`

**Comment by wydpp** [comment]
检查看application.yml配置文件，看下 canal.conf是否正确，我直接复制wiki上的，是 l.conf: ，少了几个字母

**Comment by ixiaoku** [comment]
一样的啊。有解决方案吗

**Comment by shaoxiong129** [comment]
我也遇到了
