### ISSUE TITLE
npe on master when startup canal server

### ISSUE THREAD

**Issue by yuchang01** [alibaba/canal#5131]
- [ x ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ x ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version：master
* mysql version：8.x

### Issue Description

startup throw npe

```
com.alibaba.otter.canal.parse.exception.CanalParseException: apply failed caused by : null
Caused by: java.lang.NullPointerException: null
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.buildMemFromSnapshot(DatabaseTableMeta.java:444)
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:165)
	at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:145)
	at com.alibaba.otter.canal.parse.inbound
```

### Steps to reproduce

use current master

### Actual behaviour
no npe

If there is an exception, please attach the exception trace:

possible relation this commit : https://github.com/alibaba/canal/commit/c0ff058fe1d07649f0f4c870f4c318abe9103ed4

```
Just put your stack trace here!
```

**Comment by agapple** [comment]
https://github.com/alibaba/canal/commit/d66a15fe3597b7960d974ff02c07c0af9c4a765d#diff-5d1193eb0786f06fa7fe6f3f0d2c49838e7a212e67bb06eeb2782b374670295f  

fixed
