### ISSUE TITLE
example 日志报错，检测不到数据库变化更新

### ISSUE THREAD

**Issue by fukaiyi1650** [alibaba/canal#5144]
## Question

报错信息如下 
2024-05-24 13:03:42.657 [destination = example , address = /127.0.0.1:13308 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address /127.0.0.1:13308 has an error, retrying. caused by 
com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: ErrorPacket [errorNumber=1049, fieldCount=-1, message=Unknown database 'readme_to_recover_a', sqlState=42000, sqlStateMarker=#]
 with command: show full tables from `README_TO_RECOVER_A` where Table_type = 'BASE TABLE'
Caused by: java.io.IOException: ErrorPacket [errorNumber=1049, fieldCount=-1, message=Unknown database 'readme_to_recover_a', sqlState=42000, sqlStateMarker=#]
 with command: show full tables from `README_TO_RECOVER_A` where Table_type = 'BASE TABLE'
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlQueryExecutor.query(MysqlQueryExecutor.java:61)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.query(MysqlConnection.java:107)
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.dumpTableMeta(DatabaseTableMeta.java:211)
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:174)
	at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:145)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:192)
	at java.lang.Thread.run(Thread.java:748)
2024-05-24 13:03:42.658 [destination = example , address = /127.0.0.1:13308 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: ErrorPacket [errorNumber=1049, fieldCount=-1, message=Unknown database 'readme_to_recover_a', sqlState=42000, sqlStateMarker=#]
 with command: show full tables from `README_TO_RECOVER_A` where Table_type = 'BASE TABLE'
Caused by: java.io.IOException: ErrorPacket [errorNumber=1049, fieldCount=-1, message=Unknown database 'readme_to_recover_a', sqlState=42000, sqlStateMarker=#]
 with command: show full tables from `README_TO_RECOVER_A` where Table_type = 'BASE TABLE'
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlQueryExecutor.query(MysqlQueryExecutor.java:61)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.query(MysqlConnection.java:107)
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.dumpTableMeta(DatabaseTableMeta.java:211)
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:174)
	at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:145)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:192)
	at java.lang.Thread.run(Thread.java:748)

**Comment by agapple** [comment]
Caused by: java.io.IOException: ErrorPacket [errorNumber=1049, fieldCount=-1, message=Unknown database 'readme_to_recover_a', sqlState=42000, sqlStateMarker=#]
with command: show full tables from README_TO_RECOVER_A where Table_type = 'BASE TABLE'

数据库被删除了？
