### ISSUE TITLE
No enum constant com.alibaba.otter.shared.etl.model.EventType.XACOMMIT

### ISSUE THREAD

**Issue by czxin788** [alibaba/canal#5145]
otter这个问题怎么解决，怎么跳过
```
pid:1 nid:1 exception:setl:com.alibaba.otter.node.etl.select.exceptions.SelectException: java.lang.IllegalArgumentException: No enum constant com.alibaba.otter.shared.etl.model.EventType.XACOMMIT
at com.alibaba.otter.node.etl.select.selector.MessageParser.parse(MessageParser.java:218)
at com.alibaba.otter.node.etl.select.selector.canal.CanalEmbedSelector.selector(CanalEmbedSelector.java:279)
at com.alibaba.otter.node.etl.select.SelectTask.processSelect(SelectTask.java:236)
at com.alibaba.otter.node.etl.select.SelectTask.access$300(SelectTask.java:94)
at com.alibaba.otter.node.etl.select.SelectTask$1.run(SelectTask.java:208)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.IllegalArgumentException: No enum constant com.alibaba.otter.shared.etl.model.EventType.XACOMMIT
at java.lang.Enum.valueOf(Enum.java:238)
at com.alibaba.otter.shared.etl.model.EventType.valueOf(EventType.java:24)
at com.alibaba.otter.node.etl.select.selector.MessageParser.internParse(MessageParser.java:339)
at com.alibaba.otter.node.etl.select.selector.MessageParser.parse(MessageParser.java:148)
... 9 more
```

**Comment by agapple** [comment]
需要otter升级下版本

**Comment by czxin788** [comment]
已解决
fix: https://github.com/alibaba/otter/issues/1128
