### ISSUE TITLE
docker hub canal-server image

### ISSUE THREAD

**Issue by tsfeng** [alibaba/canal#5155]
docker hub 镜像
canal/canal-server:v1.1.7
sha256:3f928a1a14830e63110042ff54e9996524865e0a1ec130eb3264c51ea14acfa8
配置 mysql 8 的 instance 时，启动报错，
原因是镜像里依赖的 druid-1.2.17.jar 包存在bug

ERROR com.alibaba.druid.pool.DruidDataSource - create connection RuntimeException
java.lang.NullPointerException: null
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1746)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2916)

另外镜像里依赖的 canal 相关包还是 SNAPSHOT.jar 后缀的

是不是考虑修复一下发布的 canal/canal-server:v1.1.7

**Comment by agapple** [comment]
druid-1.2.17.jar 包存在bug，具体的bug是啥？需要更多完整的堆栈

**Comment by agapple** [comment]
druid-1.2.17.jar 包存在bug，具体的bug是啥？需要更多完整的堆栈

**Comment by cnn007** [comment]
canal/canal-server:v1.1.7  阿里云镜像下不下来了吗

**Comment by Moexi2019** [comment]
![image](https://github.com/user-attachments/assets/830154ad-3db2-4152-819b-7a946d6f86fa)
1
