### ISSUE TITLE
Found invalid event in binary log

### ISSUE THREAD

**Issue by chenlijun419166** [alibaba/canal#5158]
2024-06-07 23:17:52.328 [destination = zma_user_new2 , address = /10.21.203.1:3307 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - I/O error while reading from client socket
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Found invalid event in binary log; the first event 'mysql3307-bin.000175' at 4, the last event read from '/opt/mysql8/3307/binlog/mysql3307-bin.000175' at 125, the last byte read from '/opt/mysql8/3307/binlog/mysql3307-bin.000175' at 125.
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:102) ~[canal.parse-1.1.5.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.seek(MysqlConnection.java:151) ~[canal.parse-1.1.5.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findAsPerTimestampInSpecificLogFile(MysqlEventParser.java:761) ~[canal.parse-1.1.5.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findEndPositionWithMasterIdAndTimestamp(MysqlEventParser.java:383) ~[canal.parse-1.1.5.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPositionInternal(MysqlEventParser.java:438) ~[canal.parse-1.1.5.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPosition(MysqlEventParser.java:357) ~[canal.parse-1.1.5.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:191) ~[canal.parse-1.1.5.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

**Comment by agapple** [comment]
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Found invalid event in binary log; the first event 'mysql3307-bin.000175' at 4, the last event read from '/opt/mysql8/3307/binlog/mysql3307-bin.000175' at 125, the last byte read from '/opt/mysql8/3307/binlog/mysql3307-bin.000175' at 125.


位点错误，重置一下吧
