### ISSUE TITLE
升级canal.adapter-1.1.8-alpha启动报错

### ISSUE THREAD

**Issue by sinfar** [alibaba/canal#5160]
报错详情：
2024-06-09 03:37:51.497 [main] INFO  c.a.otter.canal.adapter.launcher.CanalAdapterApplication - Starting CanalAdapterApplication using Java 1.8.0_411 on cluster-endpoint with PID 7399 (/app/canal.adapter-1.1.8/lib/client-adapter.launcher-1.1.8-SNAPSHOT.jar started by root in /app/canal.adapter-1.1.8/bin)
2024-06-09 03:37:51.518 [main] INFO  c.a.otter.canal.adapter.launcher.CanalAdapterApplication - No active profile set, falling back to default profiles: default
2024-06-09 03:37:52.530 [main] INFO  org.springframework.cloud.context.scope.GenericScope - BeanFactory id=a6cee8d1-48d1-3e64-a5f9-a1d1e90caee9
2024-06-09 03:37:52.905 [main] INFO  o.s.boot.web.embedded.tomcat.TomcatWebServer - Tomcat initialized with port(s): 8081 (http)
2024-06-09 03:37:52.917 [main] INFO  org.apache.coyote.http11.Http11NioProtocol - Initializing ProtocolHandler ["http-nio-8081"]
2024-06-09 03:37:52.917 [main] INFO  org.apache.catalina.core.StandardService - Starting service [Tomcat]
2024-06-09 03:37:52.917 [main] INFO  org.apache.catalina.core.StandardEngine - Starting Servlet engine: [Apache Tomcat/9.0.52]
2024-06-09 03:37:52.999 [main] INFO  o.a.catalina.core.ContainerBase.[Tomcat].[localhost].[/] - Initializing Spring embedded WebApplicationContext
2024-06-09 03:37:52.999 [main] INFO  o.s.b.w.s.context.ServletWebServerApplicationContext - Root WebApplicationContext: initialization completed in 1281 ms
2024-06-09 03:37:53.741 [main] INFO  ru.yandex.clickhouse.ClickHouseDriver - Driver registered
2024-06-09 03:37:54.102 [main] INFO  com.alibaba.druid.pool.DruidDataSource - {dataSource-1} inited
2024-06-09 03:37:54.904 [main] INFO  org.apache.coyote.http11.Http11NioProtocol - Starting ProtocolHandler ["http-nio-8081"]
2024-06-09 03:37:54.944 [main] INFO  o.s.boot.web.embedded.tomcat.TomcatWebServer - Tomcat started on port(s): 8081 (http) with context path ''
2024-06-09 03:37:54.954 [main] INFO  c.a.o.canal.adapter.launcher.loader.CanalAdapterService - ## syncSwitch refreshed.
2024-06-09 03:37:54.954 [main] INFO  c.a.o.canal.adapter.launcher.loader.CanalAdapterService - ## start the canal client adapters.
2024-06-09 03:37:54.981 [main] INFO  c.a.otter.canal.client.adapter.support.ExtensionLoader - extension classpath dir: /app/canal.adapter-1.1.8/plugin
2024-06-09 03:37:55.165 [main] INFO  c.a.o.canal.adapter.launcher.loader.CanalAdapterLoader - Load canal adapter: logger succeed
2024-06-09 03:37:56.225 [main] INFO  c.a.o.c.client.adapter.es.core.config.ESSyncConfigLoader - ## Start loading es mapping config ... 
2024-06-09 03:37:56.278 [main] INFO  c.a.o.c.client.adapter.es.core.config.ESSyncConfigLoader - ## ES mapping config loaded
2024-06-09 03:37:56.931 [main] INFO  c.a.o.canal.adapter.launcher.loader.CanalAdapterLoader - Load canal adapter: es8 succeed
2024-06-09 03:37:56.939 [main] INFO  c.alibaba.otter.canal.connector.core.spi.ExtensionLoader - extension classpath dir: /app/canal.adapter-1.1.8/plugin
2024-06-09 03:37:56.961 [main] INFO  c.a.o.canal.adapter.launcher.loader.CanalAdapterLoader - Start adapter for canal-client mq topic: example-g1 succeed
2024-06-09 03:37:56.961 [main] INFO  c.a.o.canal.adapter.launcher.loader.CanalAdapterService - ## the canal client adapters are running now ......
2024-06-09 03:37:56.975 [main] INFO  c.a.otter.canal.adapter.launcher.CanalAdapterApplication - Started CanalAdapterApplication in 6.304 seconds (JVM running for 7.285)
2024-06-09 03:37:56.979 [Thread-4] INFO  c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - =============> Start to connect destination: example <=============
2024-06-09 03:37:56.988 [Thread-4] ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - process error!
java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
        at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.readNextPacket(SimpleCanalConnector.java:412)
        at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.readNextPacket(SimpleCanalConnector.java:397)
        at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:155)
        at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.connect(SimpleCanalConnector.java:116)
        at com.alibaba.otter.canal.connector.tcp.consumer.CanalTCPConsumer.connect(CanalTCPConsumer.java:64)
        at com.alibaba.otter.canal.connector.core.spi.ProxyCanalMsgConsumer.connect(ProxyCanalMsgConsumer.java:41)
        at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.process(AdapterProcessor.java:184)
        at java.lang.Thread.run(Thread.java:750)

jdk版本：1.8.0_411

貌似是不支持jdk1.8!

**Comment by Jnser** [comment]
我也碰到这问题了，请问有解决办法吗？

**Comment by wn99hatebtc** [comment]
我也是，更新JDK版本到 JDK 12 就解決了

**Comment by agapple** [comment]
java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;

>=JDK11就可以了
