### ISSUE TITLE
Canal 大量统一消息内容重复推送，导致消息延迟

### ISSUE THREAD

**Issue by ssp1523** [alibaba/canal#5196]
## Question

消息内容：

{"data":null,"database":"`test`","es":1720514631000,"gtid":"","id":213,"isDdl":true,"mysqlType":null,"old":null,"pkNames":null,"sql":"/* rds internal mark */CREATE DATABASE IF NOT EXISTS `test`","sqlType":null,"table":"","ts":1720605940595,"type":"QUERY"}

这个消息内容一直在重复推送，导致正常的表数据变更延迟高到1天以上，而且延迟时间一直在增长，使用的是1.1.8版本

**Comment by agapple** [comment]
是不是有canal消费的其他报错，导致一直在做retry，找一下root cause

**Comment by Beauxie** [comment]
这个问题解决了，目前我也遇到了

**Comment by JunierJJJ** [comment]
我也遇到了  有一条消息一直在重复发生 然后server端有报如下错误
ERROR c.a.o.canal.connector.kafka.producer.CanalKafkaProducer - java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.NotEnoughReplicasException: Messages are rejected since there are fewer in-sync replicas than required.
java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.NotEnoughReplicasException: Messages are rejected since there are fewer in-sync replicas than required.
	at com.alibaba.otter.canal.connector.kafka.producer.CanalKafkaProducer.send(CanalKafkaProducer.java:184) ~[na:na]
	at com.alibaba.otter.canal.server.CanalMQStarter.worker(CanalMQStarter.java:181) [canal.server-1.1.5.jar:na]
	at com.alibaba.otter.canal.server.CanalMQStarter.access$100(CanalMQStarter.java:25) [canal.server-1.1.5.jar:na]
	at com.alibaba.otter.canal.server.CanalMQStarter$CanalMQRunnable.run(CanalMQStarter.java:223) [canal.server-1.1.5.jar:na]

**Comment by 1162773161** [comment]
我也遇到了，佬们解决发下方案
