### ISSUE TITLE
新建instance起不来

### ISSUE THREAD

**Issue by bruse-peng** [alibaba/canal#5215]
新建instance后点击启动，起不来，报错日志如下，排查了很久也不知道啥原因
2024-07-22 19:57:00.962 [canal-instance-scan-0] ERROR c.a.o.canal.instance.spring.SpringCanalInstanceGenerator - generator instance failed.
org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 11 in XML document from class path resource [spring/default-instance.xml] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 11; columnNumber: 28; cvc-elt.1: Cannot find the declaration of element 'beans'.
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:397) ~[canal.deployer-1.1.4-jar-with-dependencies.jar:na]
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:335) ~[canal.deployer-1.1.4-jar-with-dependencies.jar:na]
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:303) ~[canal.deployer-1.1.4-jar-with-dependencies.jar:na]
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:174) ~[canal.deployer-1.1.4-jar-with-dependencies.jar:na]
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:209) ~[canal.deployer-1.1.4-jar-with-dependencies.jar:na]
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:180) ~[canal.deployer-1.1.4-jar-with-dependencies.jar:na]
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:243) ~[canal.deployer-1.1.4-jar-with-dependencies.jar:na]
	at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:127) ~[canal.deployer-1.1.4-jar-with-dependencies.jar:na]
	at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:93) ~[canal.deployer-1.1.4-jar-with-dependencies.jar:na]
	at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:130) ~[canal.deployer-1.1.4-jar-with-dependencies.jar:na]
	at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:545) ~[canal.deployer-1.1.4-jar-with-dependencies.jar:na]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:454) ~[canal.deployer-1.1.4-jar-with-dependencies.jar:na]
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139) ~[canal.deployer-1.1.4-jar-with-dependencies.jar:na]
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83) ~[canal.deployer-1.1.4-jar-with-dependencies.jar:na]
	at com.alibaba.otter.canal.instance.manager.PlainCanalInstanceGenerator.getBeanFactory(PlainCanalInstanceGenerator.java:71) ~[canal.deployer-1.1.4-jar-with-dependencies.jar:na]
	at com.alibaba.otter.canal.instance.manager.PlainCanalInstanceGenerator.generate(PlainCanalInstanceGenerator.java:52) ~[canal.deployer-1.1.4-jar-with-dependencies.jar:na]
	at com.alibaba.otter.canal.deployer.CanalController$5.generate(CanalController.java:388) [canal.deployer-1.1.4-jar-with-dependencies.jar:na]
	at com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded$1.apply(CanalServerWithEmbedded.java:85) [canal.deployer-1.1.4-jar-with-dependencies.jar:na]
	at com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded$1.apply(CanalServerWithEmbedded.java:82) [canal.deployer-1.1.4-jar-with-dependencies.jar:na]
	at com.google.common.collect.ComputingConcurrentHashMap$ComputingValueReference.compute(ComputingConcurrentHashMap.java:356) [canal.deployer-1.1.4-jar-with-dependencies.jar:na]
	at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.compute(ComputingConcurrentHashMap.java:182) [canal.deployer-1.1.4-jar-with-dependencies.jar:na]
	at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.getOrCompute(ComputingConcurrentHashMap.java:151) [canal.deployer-1.1.4-jar-with-dependencies.jar:na]
	at com.google.common.collect.ComputingConcurrentHashMap.getOrCompute(ComputingConcurrentHashMap.java:67) [canal.deployer-1.1.4-jar-with-dependencies.jar:na]
	at com.google.common.collect.MapMaker$ComputingMapAdapter.get(MapMaker.java:885) [canal.deployer-1.1.4-jar-with-dependencies.jar:na]
	at com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded.start(CanalServerWithEmbedded.java:137) [canal.deployer-1.1.4-jar-with-dependencies.jar:na]
	at com.alibaba.otter.canal.deployer.CanalController$2$1.processActiveEnter(CanalController.java:160) [canal.deployer-1.1.4-jar-with-dependencies.jar:na]
	at com.alibaba.otter.canal.common.zookeeper.running.ServerRunningMonitor.processActiveEnter(ServerRunningMonitor.java:247) [canal.deployer-1.1.4-jar-with-dependencies.jar:na]
	at com.alibaba.otter.canal.common.zookeeper.running.ServerRunningMonitor.initRunning(ServerRunningMonitor.java:150) [canal.deployer-1.1.4-jar-with-dependencies.jar:na]
	at com.alibaba.otter.canal.common.zookeeper.running.ServerRunningMonitor.start(ServerRunningMonitor.java:102) [canal.deployer-1.1.4-jar-with-dependencies.jar:na]
	at com.alibaba.otter.canal.deployer.CanalController$3.start(CanalController.java:248) [canal.deployer-1.1.4-jar-with-dependencies.jar:na]
	at com.alibaba.otter.canal.deployer.CanalController$3.reload(CanalController.java:272) [canal.deployer-1.1.4-jar-with-dependencies.jar:na]
	at com.alibaba.otter.canal.deployer.monitor.ManagerInstanceConfigMonitor.notifyReload(ManagerInstanceConfigMonitor.java:154) [canal.deployer-1.1.4-jar-with-dependencies.jar:na]
	at com.alibaba.otter.canal.deployer.monitor.ManagerInstanceConfigMonitor.lambda$scan$2(ManagerInstanceConfigMonitor.java:118) [canal.deployer-1.1.4-jar-with-dependencies.jar:na]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_232]
	at com.alibaba.otter.canal.deployer.monitor.ManagerInstanceConfigMonitor.scan(ManagerInstanceConfigMonitor.java:117) [canal.deployer-1.1.4-jar-with-dependencies.jar:na]
	at com.alibaba.otter.canal.deployer.monitor.ManagerInstanceConfigMonitor.access$000(ManagerInstanceConfigMonitor.java:29) [canal.deployer-1.1.4-jar-with-dependencies.jar:na]
	at com.alibaba.otter.canal.deployer.monitor.ManagerInstanceConfigMonitor$2.run(ManagerInstanceConfigMonitor.java:53) ~[canal.deployer-1.1.4-jar-with-dependencies.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_232]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[na:1.8.0_232]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_232]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[na:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_232]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_232]
Caused by: org.xml.sax.SAXParseException: cvc-elt.1: Cannot find the declaration of element 'beans'.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203) ~[na:1.8.0_232]
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134) ~[na:1.8.0_232]
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396) ~[na:1.8.0_232]
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327) ~[na:1.8.0_232]
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284) ~[na:1.8.0_232]
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:1901) ~[na:1.8.0_232]
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.startElement(XMLSchemaValidator.java:741) ~[na:1.8.0_232]
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374) ~[na:1.8.0_232]
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl$NSContentDriver.scanRootElementHook(XMLNSDocumentScannerImpl.java:613) ~[na:1.8.0_232]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3132) ~[na:1.8.0_232]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:852) ~[na:1.8.0_232]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602) ~[na:1.8.0_232]
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112) ~[na:1.8.0_232]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505) ~[na:1.8.0_232]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842) ~[na:1.8.0_232]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771) ~[na:1.8.0_232]
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) ~[na:1.8.0_232]
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243) ~[na:1.8.0_232]
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339) ~[na:1.8.0_232]
	at org.springframework.beans.factory.xml.DefaultDocumentLoader.loadDocument(DefaultDocumentLoader.java:75) ~[canal.deployer-1.1.4-jar-with-dependencies.jar:na]
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:389) ~[canal.deployer-1.1.4-jar-with-dependencies.jar:na]
	... 43 common frames omitted

**Comment by daMeng1024** [comment]
新建了instance，应该所有配置都要改吧，包括这里spring/default-instance.xml的。感觉这个文件是不是有空格或者配置改漏了

**Comment by bruse-peng** [comment]
> 新建了instance，应该所有配置都要改吧，包括这里spring/default-instance.xml的。感觉这个文件是不是有空格或者配置改漏了

我这边不是开发，新起一套环境，将原来的instance配置拷贝过来，只换了ip信息，在新的地方就报这个错，具体需要这么改了

**Comment by agapple** [comment]
Line 11 in XML document from class path resource [spring/default-instance.xml] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 11; columnNumber: 28; cvc-elt.1: Cannot find the declaration of element 'beans

应该是高版本的xml，复制到了低版本，中间有过spring版本升级
