### ISSUE TITLE
canal-1.1.8-alpha-2报错

### ISSUE THREAD

**Issue by YatHinLay** [alibaba/canal#5221]
详细的错误信息如下:
com.alibaba.otter.canal.parse.exception.CanalParseException: command : 'show master status' has an error!
Caused by: java.io.IOException: ErrorPacket [errorNumber=1064, fieldCount=-1, message=You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'master status' at line 1, sqlState=42000, sqlStateMarker=#]
 with command: show master status
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlQueryExecutor.query(MysqlQueryExecutor.java:61)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.query(MysqlConnection.java:107)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findEndPosition(MysqlEventParser.java:673)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findEndPositionWithMasterIdAndTimestamp(MysqlEventParser.java:383)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPositionInternal(MysqlEventParser.java:442)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.findStartPosition(MysqlEventParser.java:360)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:186)
	at java.base/java.lang.Thread.run(Thread.java:842)
使用的是Mysql8.4，binlog已开启，并且已经给canal用户授予相对应的权限。

**Comment by OnlyCodeMain** [comment]
老兄你解决了吗

**Comment by agapple** [comment]
最新的mysql 8.4？

**Comment by yuchengfeifeifei-rgb** [comment]
mysql8.4没有show master status这个命令
