### ISSUE TITLE
docker 镜像还是 1.7 版本，麻烦更新 一下最新版本

### ISSUE THREAD

**Issue by lijc210** [alibaba/canal#5232]
1.7 版本 tsdb 的 mysql 连接方式有不过，会报
2024-08-06 09:29:34.416 [Druid-ConnectionPool-Create-1224757274] ERROR com.alibaba.druid.pool.DruidDataSource - create connection SQLException, url: , errorCode 0, state null
java.sql.SQLException: connect error, url , driverClass com.mysql.jdbc.Driver
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1775)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2916)

**Comment by Gshelldong** [comment]
你有遇到我得问题吗？#5233

**Comment by lijc210** [comment]
> 你有遇到我得问题吗？#5233

我没有遇到，我用的镜像是
canal/canal-admin:latest
canal/canal-server:latest

我遇到的问题听说在canal-1.1.7-hotfix-1分支修复了，但最新镜像还没有更新

**Comment by Gshelldong** [comment]
可以看下你在k8s中的部署yaml吗 ？

**Comment by lijc210** [comment]
> 可以看下你在k8s中的部署yaml吗 ？

services:
  mysql:
    image: mysql:latest
    # restart: always
    container_name: mysql
    volumes:
      - $DOCKERCONF/mysql/data:/var/lib/mysql
      - $DOCKERCONF/mysql/conf/my.cnf:/etc/my.conf
      - $DOCKERCONF/mysql/logs:/var/log/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      # 使用宿主机的端口映射到容器的端口
      # 宿主机：容器
      - 3306:3306
  canal-admin:
    # https://github.com/alibaba/canal/wiki/Canal-Admin-Docker
    # 使用外部数据库时，需要初始化数据库
    # https://github.com/alibaba/canal/blob/master/admin/admin-web/src/main/resources/canal_manager.sql
    # 登录密码，admin，123456
    image: canal/canal-admin:latest
    container_name: canal-admin
    restart: always
    ports:
      - "8089:8089"
    environment:
      - TZ=Asia/Shanghai # 设置时区
      - server.port=8089
      - spring.datasource.address=mysql:3306
      - spring.datasource.database=canal_manager
      - spring.datasource.username=root
      - spring.datasource.password=123456
    mem_limit: 512m
  canal-server-1:
    # https://github.com/alibaba/canal/wiki/Docker-QuickStart
    image: canal/canal-server:latest
    container_name: canal-server-1
    restart: always
    # volumes:
    #   -  $DOCKERCONF/canal-server/conf/canal.properties:/home/admin/canal-server/conf/canal.properties
    # ports:
    #   - "11110:11110"
    environment:
      - TZ=Asia/Shanghai # 设置时区
      - canal.register.ip=
      - canal.admin.manager=canal-admin:8089
      - canal.admin.port=11110
      - canal.admin.user=admin
      - canal.admin.passwd=4ACFE3202A5FF5CF467898FC58AAB1D615029441
      - canal.admin.register.auto=true
      - canal.admin.register.cluster=canal-local # 先在canal-admin中添加集群名称
    mem_limit: 2048m
  canal-server-2:
    # https://github.com/alibaba/canal/wiki/Docker-QuickStart
    image: canal/canal-server:latest
    container_name: canal-server-2
    restart: always
    # volumes:
    #   -  $DOCKERCONF/canal-server/conf/canal.properties:/home/admin/canal-server/conf/canal.properties
    # ports:
    #   - "11110:11110"
    environment:
      - TZ=Asia/Shanghai # 设置时区
      - canal.register.ip=
      - canal.admin.manager=canal-admin:8089
      - canal.admin.port=11110
      - canal.admin.user=admin
      - canal.admin.passwd=4ACFE3202A5FF5CF467898FC58AAB1D615029441
      - canal.admin.register.auto=true
      - canal.admin.register.cluster=canal-local # 先在canal-admin中添加集群名称
    mem_limit: 2048m

**Comment by lijc210** [comment]
> 1.7 版本 tsdb 的 mysql 连接方式有不过，会报 2024-08-06 09:29:34.416 [Druid-ConnectionPool-Create-1224757274] ERROR com.alibaba.druid.pool.DruidDataSource - create connection SQLException, url: , errorCode 0, state null java.sql.SQLException: connect error, url , driverClass com.mysql.jdbc.Driver at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1775) at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2916)

这个问题好像也不存在了，不报了

**Comment by Gshelldong** [comment]
感谢！！！

**Comment by agapple** [comment]
> > 你有遇到我得问题吗？#5233
> 
> 我没有遇到，我用的镜像是 canal/canal-admin:latest canal/canal-server:latest
> 
> 我遇到的问题听说在canal-1.1.7-hotfix-1分支修复了，但最新镜像还没有更新

我印象中应该推送过canal-1.1.7-hotfix-1镜像

**Comment by helpisyou** [comment]
> > > 你有遇到我得问题吗？#5233
> > 
> > 
> > 我没有遇到，我用的镜像是 canal/canal-admin:latest canal/canal-server:latest
> > 我遇到的问题听说在canal-1.1.7-hotfix-1分支修复了，但最新镜像还没有更新
> 
> 我印象中应该推送过canal-1.1.7-hotfix-1镜像

没有找到这个镜像
