### ISSUE TITLE
同步失败 =》 IllegalArgumentException: Invalid format: "中文"

### ISSUE THREAD

**Issue by cc1aymore** [alibaba/canal#5260]
报错内容。请问可以跳过这个位点吗？用的canal-adapter。

```
2024-08-29 19:45:44.108 [pool-26-thread-1] ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.IllegalArgumentException: Invalid format: "沈家润"
java.lang.RuntimeException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.IllegalArgumentException: Invalid format: "沈家润"
        at com.alibaba.otter.canal.client.adapter.rdb.RdbAdapter.sync(RdbAdapter.java:157)
        at com.alibaba.otter.canal.client.adapter.ProxyOuterAdapter.sync(ProxyOuterAdapter.java:42)
        at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.batchSync(AdapterProcessor.java:139)
        at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.lambda$writeOut$1(AdapterProcessor.java:97)
        at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
        at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.lambda$writeOut$2(AdapterProcessor.java:94)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.IllegalArgumentException: Invalid format: "沈家润"
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$sync$2(RdbSyncService.java:135)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.sync(RdbSyncService.java:131)
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.sync(RdbSyncService.java:155)
        at com.alibaba.otter.canal.client.adapter.rdb.RdbAdapter.sync(RdbAdapter.java:153)
        ... 9 common frames omitted
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.IllegalArgumentException: Invalid format: "沈家润"
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$sync$2(RdbSyncService.java:133)
        ... 13 common frames omitted
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Invalid format: "沈家润"
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$sync$1(RdbSyncService.java:126)
        ... 4 common frames omitted
Caused by: java.lang.IllegalArgumentException: Invalid format: "沈家润"
        at org.joda.time.format.DateTimeParserBucket.doParseMillis(DateTimeParserBucket.java:187)
        at org.joda.time.format.DateTimeFormatter.parseMillis(DateTimeFormatter.java:826)
        at org.joda.time.convert.StringConverter.getInstantMillis(StringConverter.java:65)
        at org.joda.time.base.BaseDateTime.<init>(BaseDateTime.java:151)
        at org.joda.time.DateTime.<init>(DateTime.java:281)
        at com.alibaba.otter.canal.client.adapter.support.Util.parseDate(Util.java:241)
        at com.alibaba.otter.canal.client.adapter.rdb.support.SyncUtil.setPStmt(SyncUtil.java:258)
        at com.alibaba.otter.canal.client.adapter.rdb.support.BatchExecutor.execute(BatchExecutor.java:60)
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.insert(RdbSyncService.java:294)
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.sync(RdbSyncService.java:226)
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$sync$0(RdbSyncService.java:117)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbSyncService.lambda$sync$1(RdbSyncService.java:117)
        ... 4 common frames omitted
```

**Comment by cc1aymore** [comment]
是什么原因呢。请问
