### ISSUE TITLE
canal server1.1.4 之前一直运行正常，现在启动实例报错

### ISSUE THREAD

**Issue by yolanda0628** [alibaba/canal#5291]
ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:uopsUser[com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: Read CODE#128 error: limit excceed: 65
Caused by: java.io.IOException: Read CODE#128 error: limit excceed: 65
        at com.taobao.tddl.dbsync.binlog.event.QueryLogEvent.unpackVariables(QueryLogEvent.java:715)
        at com.taobao.tddl.dbsync.binlog.event.QueryLogEvent.<init>(QueryLogEvent.java:495)
        at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:168)
        at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:111)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:264)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:246)
        at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168)
        at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: limit excceed: 65
        at com.taobao.tddl.dbsync.binlog.LogBuffer.forward(LogBuffer.java:115)
        at com.taobao.tddl.dbsync.binlog.event.QueryLogEvent.unpackVariables(QueryLogEvent.java:702)
        ... 12 more
]

**Comment by agapple** [comment]
反馈一下mysql版本 和 canal版本

**Comment by yolanda0628** [comment]
mysql版本8.0.36-28.1  canal版本1.1.4
