### ISSUE TITLE
请问canal不支持rds的mysql5.6版本么？canalV1.0.25启动会没权限异常

### ISSUE THREAD

**Issue by millinchen** [alibaba/canal#530]
2018-02-12 11:38:47.267 [destination = example , address = rm-xxxxx.mysql.rds.aliyuncs.com/47.206.15.124:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: ErrorPacket [errorNumber=1142, fieldCount=-1, message=SHOW command denied to user 'canal_monitor'@'122.177.246.186' for table 'db', sqlState=42000, sqlStateMarker=#]
 with command: show create table `mysql`.`columns_priv`;show create table `mysql`.`db`;show create table `mysql`.`db_view`;show create table `mysql`.`dml_health_check`;show create table `mysql`.`event`;show create table `mysql`.`failover_info`;show create table `mysql`.`func`;show create table `mysql`.`general_log`;show create table `mysql`.`ha_health_check`;show create table `mysql`.`help_category`;show create table `mysql`.`help_keyword`;show create table `mysql`.`help_relation`;show create table `mysql`.`help_topic`;show create table `mysql`.`innodb_index_stats`;show create table `mysql`.`innodb_table_stats`;show create table `mysql`.`ndb_binlog_index`;show create table `mysql`.`plugin`;show create table `mysql`.`proc`;show create table `mysql`.`procs_priv`;show create table `mysql`.`proxies_priv`;show create table `mysql`.`servers`;show create table `mysql`.`slave_master_info`;show create table `mysql`.`slave_relay_log_info`;show create table `mysql`.`slave_worker_info`;show create table `mysql`.`slow_log`;show create table `mysql`.`slow_log_view`;show create table `mysql`.`tables_priv`;show create table `mysql`.`time_zone`;show create table `mysql`.`time_zone_leap_second`;show create table `mysql`.`time_zone_name`;show create table `mysql`.`time_zone_transition`;show create table `mysql`.`time_zone_transition_type`;show create table `mysql`.`user`;show create table `mysql`.`user_view`;
Caused by: java.io.IOException: ErrorPacket [errorNumber=1142, fieldCount=-1, message=SHOW command denied to user 'canal_monitor'@'122.177.246.186' for table 'db', sqlState=42000, sqlStateMarker=#]
 with command: show create table `mysql`.`columns_priv`;show create table `mysql`.`db`;show create table `mysql`.`db_view`;show create table `mysql`.`dml_health_check`;show create table `mysql`.`event`;show create table `mysql`.`failover_info`;show create table `mysql`.`func`;show create table `mysql`.`general_log`;show create table `mysql`.`ha_health_check`;show create table `mysql`.`help_category`;show create table `mysql`.`help_keyword`;show create table `mysql`.`help_relation`;show create table `mysql`.`help_topic`;show create table `mysql`.`innodb_index_stats`;show create table `mysql`.`innodb_table_stats`;show create table `mysql`.`ndb_binlog_index`;show create table `mysql`.`plugin`;show create table `mysql`.`proc`;show create table `mysql`.`procs_priv`;show create table `mysql`.`proxies_priv`;show create table `mysql`.`servers`;show create table `mysql`.`slave_master_info`;show create table `mysql`.`slave_relay_log_info`;show create table `mysql`.`slave_worker_info`;show create table `mysql`.`slow_log`;show create table `mysql`.`slow_log_view`;show create table `mysql`.`tables_priv`;show create table `mysql`.`time_zone`;show create table `mysql`.`time_zone_leap_second`;show create table `mysql`.`time_zone_name`;show create table `mysql`.`time_zone_transition`;show create table `mysql`.`time_zone_transition_type`;show create table `mysql`.`user`;show create table `mysql`.`user_view`;
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlQueryExecutor.queryMulti(MysqlQueryExecutor.java:109)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.queryMulti(MysqlConnection.java:93)
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.dumpTableMeta(DatabaseTableMeta.java:173)
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:127)
	at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:72)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:170)
	at java.lang.Thread.run(Thread.java:748)

**Comment by agapple** [comment]
1. 你可以指定订阅的表，而不是所有
2. 授权足够大的权限

**Comment by millinchen** [comment]
@agapple 我已经按你说的测试了指定订阅了某个表，结果是一样的错误，阿里云rds mysql5.6版本我提工单客服说不支持SHOW CREATE TABLE `mysql`.`db_view`;这样的权限（我用高权限权账号执行确实一直报没权限），是不是这样导致的呢？

**Comment by agapple** [comment]
是的，如果你没有指定表，那就是默认会订阅所有的表，订阅之前会全局拿一次表结构，所以会出现类似的权限报错

**Comment by shyboy0358** [comment]
在哪指定订阅的表呢？

**Comment by zuonidelaowang** [comment]
看到别人给的解决办法
canal.instance.filter.black.regex=mysql..*
把不需要订阅的库, 加入黑名单, 这样就不会报错了
