### ISSUE TITLE
com.alibaba.otter.canal.common.CanalException: com.alibaba.otter.canal.common.CanalException: instance : example config is not found

### ISSUE THREAD

**Issue by idealzouhu** [alibaba/canal#5308]
## Problem Description
Using Docker to start the server, the instance was not created successfully.
```bash
docker run -d ^
  --name canal-server ^
  --restart always ^
  -p 11111:11111 ^
  --privileged=true ^
  -e canal.destinations=example ^
  -e canal.instance.mysql.slaveId=1234  ^
  -e canal.instance.master.address=host.docker.internal:3306 ^
  -e canal.instance.dbUsername=canal ^
  -e canal.instance.dbPassword=canal ^
  -e canal.instance.connectionCharset=UTF-8 ^
  -e canal.instance.tsdb.enable=true ^
  -e canal.instance.gtidon=false ^
  -e canal.instance.filter.regex=.\*\\\\..\* ^
  -e canal.admin.manager=host.docker.internal:8089 ^
  -e canal.admin.port=11110 ^
  -e canal.admin.user=admin ^
  -e canal.admin.passwd=4ACFE3202A5FF5CF467898FC58AAB1D615029441 ^
  -m 4096m ^
  canal/canal-server:v1.1.7
```

## Error Message
```bash
sh-4.2# tail /home/admin/canal-server/logs/canal/canal.log
        at com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded.start(CanalServerWithEmbedded.java:130)
        at com.alibaba.otter.canal.deployer.CanalController$1.processActiveEnter(CanalController.java:159)
        at com.alibaba.otter.canal.common.zookeeper.running.ServerRunningMonitor.processActiveEnter(ServerRunningMonitor.java:247)
        at com.alibaba.otter.canal.common.zookeeper.running.ServerRunningMonitor.start(ServerRunningMonitor.java:100)
        at com.alibaba.otter.canal.deployer.CanalController.start(CanalController.java:538)
        at com.alibaba.otter.canal.deployer.CanalStarter.start(CanalStarter.java:88)
        at com.alibaba.otter.canal.deployer.CanalLauncher.main(CanalLauncher.java:124)
Caused by: com.alibaba.otter.canal.common.CanalException: com.alibaba.otter.canal.common.CanalException: instance : example config is not found
Caused by: com.alibaba.otter.canal.common.CanalException: instance : example config is not found
2024-10-29 04:09:07.835 [main] INFO  com.alibaba.otter.canal.deployer.CanalStarter - ## the canal server is running now ......
```

**Comment by dyrnq** [comment]
https://github.com/alibaba/canal/wiki/Canal-Admin-Guide 文档里有提，需要在canal-admin的后台操作新增example instance 的配置

**Comment by agapple** [comment]
LS正解

**Comment by lhsaq2009** [comment]
> https://github.com/alibaba/canal/wiki/Canal-Admin-Guide 文档里有提，需要在canal-admin的后台操作新增example instance 的配置

https://github.com/alibaba/canal/wiki/Docker-QuickStart，这个文档里意思，应该是不需要手动配置的呀

```
# 下载脚本
wget https://raw.githubusercontent.com/alibaba/canal/master/docker/run.sh 

# 构建一个destination name为test的队列
sh run.sh -e canal.auto.scan=false \
		  -e canal.destinations=test \
		  -e canal.instance.master.address=127.0.0.1:3306  \
		  -e canal.instance.dbUsername=canal  \
		  -e canal.instance.dbPassword=canal  \
		  -e canal.instance.connectionCharset=UTF-8 \
		  -e canal.instance.tsdb.enable=true \
		  -e canal.instance.gtidon=false  \
```

**Comment by lhsaq2009** [comment]
> > https://github.com/alibaba/canal/wiki/Canal-Admin-Guide 文档里有提，需要在canal-admin的后台操作新增example instance 的配置
> 
> [https://github.com/alibaba/canal/wiki/Docker-QuickStart，这个文档里意思，应该是不需要手动配置的呀](https://github.com/alibaba/canal/wiki/Docker-QuickStart%EF%BC%8C%E8%BF%99%E4%B8%AA%E6%96%87%E6%A1%A3%E9%87%8C%E6%84%8F%E6%80%9D%EF%BC%8C%E5%BA%94%E8%AF%A5%E6%98%AF%E4%B8%8D%E9%9C%80%E8%A6%81%E6%89%8B%E5%8A%A8%E9%85%8D%E7%BD%AE%E7%9A%84%E5%91%80)
> 
> ```
> # 下载脚本
> wget https://raw.githubusercontent.com/alibaba/canal/master/docker/run.sh 
> 
> # 构建一个destination name为test的队列
> sh run.sh -e canal.auto.scan=false \
> 		  -e canal.destinations=test \
> 		  -e canal.instance.master.address=127.0.0.1:3306  \
> 		  -e canal.instance.dbUsername=canal  \
> 		  -e canal.instance.dbPassword=canal  \
> 		  -e canal.instance.connectionCharset=UTF-8 \
> 		  -e canal.instance.tsdb.enable=true \
> 		  -e canal.instance.gtidon=false  \
> ```


应该是文档更新不及时吧
看源码

```
                PlainCanal canal = canalConfigClient.findInstance(destination, null);
                if (canal == null) {
                    throw new CanalException("instance : " + destination + " config is not found");
                }

    /**
     * 加载远程的instance.properties
     */
    public PlainCanal findInstance(String destination, String md5) {
        if (StringUtils.isEmpty(md5)) {
            md5 = "";
        }
        String url = configURL + "/api/v1/config/instance_polling/" + UrlEscapers.urlPathSegmentEscaper().escape(destination) + "?md5=" + md5;
        return queryConfig(url);
    }
```
这里确实去远程加载配置啦

**Comment by lhsaq2009** [comment]
## instance : example config is not found

> 解决：[[=> 补充：手动创建 Instance](https://github.com/alibaba/canal/issues/5308#1736699265313_428)](#1736699265313_428)

<!-- Failed to upload "image.png" -->

---

> 报错场景：参考了这篇文档：[[Docker QuickStart](https://github.com/alibaba/canal/wiki/Docker-QuickStart)](https://github.com/alibaba/canal/wiki/Docker-QuickStart)，关于 "构建一个 destination name 为 test 的队列"

<img src="https://lhsaq2009.oss-cn-hangzhou.aliyuncs.com/image/image-20250208152331914_598.png" style="width:800px;" />

> 关键错误日志输出

```shell
2025-02-08 05:39:28.530 [main] ERROR c.a.o.c.common.zookeeper.running.ServerRunningMonitor - start failed
com.google.common.util.concurrent.UncheckedExecutionException: com.alibaba.otter.canal.common.CanalException: com.alibaba.otter.canal.common.CanalException: instance : canal-study config is not found
```

> 源码分析结论：某些 instance 参数压根无效

```java
// 01、docker/run.sh，接收全部参数保存到 

	CONFIG=${@:1}
	
// 02、脚本最后启动 docker 实例，将全部参数 $CONFIG 传递过去

	cmd="docker run -d -it -h $LOCALHOST $CONFIG --name=canal-server $VOLUMNS $NET_MODE $PORTS $MEMORY canal/canal-server"
    
// 03、看看容器启动执行脚本内容

	docker inspect canal/canal-server | grep "\.sh"
	    
	# 实际执行命令：/alidata/bin/main.sh /home/admin/app.sh
	
// 04、看看 /home/admin/app.sh 接收参数情况，

    sh-4.2# zgrep -A 0 -i -E --color  "print $ENV" /home/admin/app.sh
        managerAddress=`perl -le 'print $ENV{"canal.admin.manager"}'`
    --
            adminPort=`perl -le 'print $ENV{"canal.admin.port"}'`
    --
            metricsPort=`perl -le 'print $ENV{"canal.metrics.pull.port"}'`
    --
            destination=`perl -le 'print $ENV{"canal.destinations"}'`
            destinationExpr=`perl -le 'print $ENV{"canal.destinations.expr"}'`
            multistream=`perl -le 'print $ENV{"canal.instance.multi.stream.on"}'`
            
// 05、再看看哪里抛出的 instance : canal-study config is not found

=>> com.alibaba.otter.canal.deployer.CanalStarter#start(..)
	        
    // 第一步：上下文初始化                                                                                                                           
                                                                                                                                            
    controller = new CanalController(properties);                                                                                           
    =>> com.alibaba.otter.canal.deployer.CanalController#CanalController(java.util.Properties)                                              
                                                                                                                                            
        // 初始化全局参数设置                                                                                                                        
        globalInstanceConfig = initGlobalConfig(properties);                                                                                
        =>> com.alibaba.otter.canal.deployer.CanalController#initGlobalConfig(..)                                                           
                                                                                                                                            
  ┌───▶     instanceGenerator = destination -> {                                                                                            
  │             if (config.getMode().isManager()) {         // 启用 canal-admin                                                               
  │                 PlainCanalInstanceGenerator instanceGenerator = new PlainCanalInstanceGenerator(properties);                            
  │                 return instanceGenerator.generate(destination);     
  │             }    
  │         };                  
  │                                                                                                    
  │     ServerRunningMonitors.setRunningMonitors(MigrateMap.makeComputingMap((Function<String, ServerRunningMonitor>) destination -> {      
┌─┼───▶     ServerRunningMonitor runningMonitor = new ServerRunningMonitor(serverData);                                                     
│ │         runningMonitor.setDestination(destination);                 
│ │         runningMonitor.setListener(new ServerRunningListener() {                                                                        
│ │             public void processActiveEnter() {                                                                                          
│ │             
│ │ // 第二步：服务启动                                                                                                                             
│ │            
│ │ controller.start();                                                                                                                     
│ │ =>> com.alibaba.otter.canal.deployer.CanalController#start(..)                                                                          
│ │                                                                                                                                         
│ │     embeddedCanalServer.start();                                                                                                        
│ │     =>> com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded#start()                                                         
│ │       
│ └────     canalInstances = MigrateMap.makeComputingMap(destination -> canalInstanceGenerator.generate(destination));                      
│                                                                                                                                           
│       for (Map.Entry<String, InstanceConfig> entry : instanceConfigs.entrySet()) {                                                        
│                                                                                                                                           
└──────     runningMonitor.start();                                                                                                         
            =>> com.alibaba.otter.canal.common.zookeeper.running.ServerRunningMonitor#start()
                
                =>> processActiveEnter();// 没有zk，直接启动
            		            
                    embeddedCanalServer.start(destination);
                    =>> com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded#start(..)
						
                        final CanalInstance canalInstance = canalInstances.get(destination);
                        =>> canalInstanceGenerator.generate(destination)
                            =>> com.alibaba.otter.canal.instance.manager.PlainCanalInstanceGenerator#generate(..)
                            
                            	// 加载远程的 instance.properties
                            	
                                PlainCanal canal = canalConfigClient.findInstance(destination, null);
                                =>> com.alibaba.otter.canal.instance.manager.plain.PlainCanalConfigClient#findInstance(..)

                                    String url = configURL + "/api/v1/config/instance_polling/" + ...escape(destination) + "?md5=" + md5;
                                    return queryConfig(url);

                                if (canal == null) {
                                    throw new CanalException("instance : " + destination + " config is not found");

// 06、这个接口位于 admin 模块下，压根与 docker 容器启动传递的参数无关系

    @RestController
    @RequestMapping("/api/{env}/config")
    public class PollingConfigController {

        @GetMapping(value = "/instance_polling/{destination}")
        public BaseModel<CanalInstanceConfig> instanceConfigPoll(..)				// 查询表：canal_instance_config
            =>> CanalInstanceConfig instanceConfig = CanalInstanceConfig.find.query().where().eq("name", destination).findOne();
```

**Comment by dyrnq** [comment]
对，run.sh中  example 1和example 2是 二选一的关系，一个是基于本地配置的instance，一个是基于admin远程配置，所以无需全部配置
