### ISSUE TITLE
阿里云PolarDB MYSQL版本 8.0.18  java.lang.IllegalArgumentException: unknow type : 202

### ISSUE THREAD

**Issue by sim-hank** [alibaba/canal#5310]
- [ ] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version  v1.1.7~1.1.8alpha
* mysql version  阿里云polarDB  MYSQL版本 8.0.18

### Issue Description
一开始解析binlog就报错，一条成功的都没有，哪位大佬帮忙看看

### Actual behaviour

If there is an exception, please attach the exception trace:

```
2024-10-29 01:39:53.313 [destination = xxxxxxx , address = xxxxxxxxx:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> begin to find start position, it will be long time for reset or first position
2024-10-29 01:39:53.313 [destination = xxxxxxx , address = xxxxxxxxx:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - prepare to find start position just last position
 {"identity":{"slaveId":-1,"sourceAddress":{"address":"xxxxxxx","port":3306}},"postion":{"gtid":"","included":false,"journalName":"mysql-bin.009092","position":145896894,"serverId":100221569,"timestamp":1730165930000}}
2024-10-29 01:39:53.323 [destination = xxxxxxx , address = xxxxxxxxx:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - ---> find start position successfully, EntryPosition[included=false,journalName=mysql-bin.009092,position=145896894,serverId=100221569,gtid=,timestamp=1730165930000] cost : 10ms , the next step is binlog dump
2024-10-29 01:39:53.352 [destination = xxxxxxx , address = xxxxxxxxx:3306 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.MysqlConnection - load MySQL @@version_comment : Source distribution
2024-10-29 01:39:53.359 [destination = xxxxxxx , address = xxxxxxxxx:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address xxxxxxxxx:3306 has an error, retrying. caused by 
com.alibaba.otter.canal.parse.exception.CanalParseException: java.lang.IllegalArgumentException: unknow type : 202
Caused by: java.lang.IllegalArgumentException: unknow type : 202
        at com.taobao.tddl.dbsync.binlog.event.TableMapLogEvent.<init>(TableMapLogEvent.java:504)
        at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:211)
        at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:82)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:261)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:243)
        at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168)
        at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
```

**Comment by agapple** [comment]
unknow type : 202，是不是搞了自定义的binlog类型（非mysql标准），你反馈给阿里云吧

**Comment by weichunshen89** [comment]
@sim-hank 问题原因找到了吗？
