### ISSUE TITLE
Canal Admin Helm chart 无法启动

### ISSUE THREAD

**Issue by richardeee** [alibaba/canal#5321]
## Question
通过helm chart部署canal-admin时，liveProbe和readinessProbe一直报错，Pod一直重启。
通过去掉liveProbe和readinessProbe，直接登入pod中查看进程，发现并没有进程在监听8089端口，再通过手动执行启动脚本，发现下面的报错：
`2024-11-15 09:32:15.550  INFO 469 --- [           main] c.a.o.canal.admin.CanalAdminApplication  : Starting CanalAdminApplication using Java 1.8.0_351 on canal-admin-6c47988b4-48wrg with PID 469 (/home/admin/canal-admin/lib/canal.admin-web-1.1.8-SNAPSHOT.jar started by root in /home/admin/canal-admin/bin)
2024-11-15 09:32:15.553  INFO 469 --- [           main] c.a.o.canal.admin.CanalAdminApplication  : No active profile set, falling back to 1 default profile: "default"
2024-11-15 09:32:15.656  WARN 469 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [com.alibaba.otter.canal.admin.CanalAdminApplication]; nested exception is java.io.FileNotFoundException: class path resource [org/springframework/web/servlet/config/annotation/WebMvcConfigurer.class] cannot be opened because it does not exist
2024-11-15 09:32:15.674 ERROR 469 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [com.alibaba.otter.canal.admin.CanalAdminApplication]; nested exception is java.io.FileNotFoundException: class path resource [org/springframework/web/servlet/config/annotation/WebMvcConfigurer.class] cannot be opened because it does not exist
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:188) ~[spring-context-5.3.26.jar:5.3.26]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:331) ~[spring-context-5.3.26.jar:5.3.26]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:247) ~[spring-context-5.3.26.jar:5.3.26]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:311) ~[spring-context-5.3.26.jar:5.3.26]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:112) ~[spring-context-5.3.26.jar:5.3.26]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:748) ~[spring-context-5.3.26.jar:5.3.26]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564) ~[spring-context-5.3.26.jar:5.3.26]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:780) ~[spring-boot-2.5.15.jar:2.5.15]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:453) ~[spring-boot-2.5.15.jar:2.5.15]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:343) ~[spring-boot-2.5.15.jar:2.5.15]
	at com.alibaba.otter.canal.admin.CanalAdminApplication.main(CanalAdminApplication.java:19) [canal.admin-web-1.1.8-SNAPSHOT.jar:na]
Caused by: java.io.FileNotFoundException: class path resource [org/springframework/web/servlet/config/annotation/WebMvcConfigurer.class] cannot be opened because it does not exist
	at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:199) ~[spring-core-5.3.26.jar:5.3.26]
	at org.springframework.core.type.classreading.SimpleMetadataReader.getClassReader(SimpleMetadataReader.java:55) ~[spring-core-5.3.26.jar:5.3.26]
	at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:48) ~[spring-core-5.3.26.jar:5.3.26]
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:103) ~[spring-core-5.3.26.jar:5.3.26]
	at org.springframework.boot.type.classreading.ConcurrentReferenceCachingMetadataReaderFactory.createMetadataReader(ConcurrentReferenceCachingMetadataReaderFactory.java:86) ~[spring-boot-2.5.15.jar:2.5.15]
	at org.springframework.boot.type.classreading.ConcurrentReferenceCachingMetadataReaderFactory.getMetadataReader(ConcurrentReferenceCachingMetadataReaderFactory.java:73) ~[spring-boot-2.5.15.jar:2.5.15]
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:81) ~[spring-core-5.3.26.jar:5.3.26]
	at org.springframework.context.annotation.ConfigurationClassParser.asSourceClass(ConfigurationClassParser.java:696) ~[spring-context-5.3.26.jar:5.3.26]
	at org.springframework.context.annotation.ConfigurationClassParser$SourceClass.getInterfaces(ConfigurationClassParser.java:1024) ~[spring-context-5.3.26.jar:5.3.26]
	at org.springframework.context.annotation.ConfigurationClassParser.processInterfaces(ConfigurationClassParser.java:385) ~[spring-context-5.3.26.jar:5.3.26]
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:331) ~[spring-context-5.3.26.jar:5.3.26]
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:249) ~[spring-context-5.3.26.jar:5.3.26]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:198) ~[spring-context-5.3.26.jar:5.3.26]
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:303) ~[spring-context-5.3.26.jar:5.3.26]
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:249) ~[spring-context-5.3.26.jar:5.3.26]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:206) ~[spring-context-5.3.26.jar:5.3.26]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:174) ~[spring-context-5.3.26.jar:5.3.26]
	... 10 common frames omitted`

使用的是最新版本的helm chart，canal-admin的image也是latest

**Comment by luogenhua** [comment]
同上，健康检查失败

POD日志重复输出以下内容：PS mysql已导出初始化数据库
DOCKER_DEPLOY_TYPE=VM
==> INIT /alidata/init/02init-sshd.sh
==> EXIT CODE: 0
==> INIT /alidata/init/fix-hosts.py
==> EXIT CODE: 0
==> INIT DEFAULT
==> INIT DONE
==> RUN /home/admin/app.sh
chown: changing ownership of '/home/admin/canal-admin/conf/application.yml': Read-only file system
==> START ...
start mysql ...
mysql: [Warning] Using a password on the command line interface can be insecure.
start mysql successful
start admin ...
start canal successful
==> START SUCCESSFUL ...

**Comment by mzzya** [comment]
> admin启动成功了，但是canal-server健康检查失败了 就绪情况探测失败： 获取 “http://10.20.29.178:11112/”： dial tcp 10.20.29.178：11112： connect： connection refused
> 
> [主要]错误 com.alibaba.otter.canal.deployer.CanalLauncher - ## 启动 canal 服务器时出错：com.alibaba.otter.canal.common.CanalException：加载管理器配置失败。原因：com.alibaba.otter.canal.common.CanalException：请求获取 canal 配置错误：错误[数据截断：第 1 行列“name”的数据过长]

可能是canal-server名字太长了
