### ISSUE TITLE
canal 解析datetime(3)类型时间戳报错

### ISSUE THREAD

**Issue by xwm1992** [alibaba/canal#5323]
- [x] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment

* canal version v1.1.7
* mariadb version v10.1.9

### Issue Description
使用canal 1.1.7版本，解析binlog 时间戳字段类型为datetime(3)，报错日志如下：

```
2024-11-19 10:28:48,821 WARN  [destination = destinationGroup , address = /172.21.10.254:15008 , EventParser] MysqlEventParser(AbstractEventParser.java:455) - ERROR ## parse this event has an error , last position : [EntryPosition[included=false,journalName=binlog.014380,position=54881719,serverId=184600487,gtid=0-184600487-97442573,timestamp=1731983331000]]
com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: java.lang.ArrayIndexOutOfBoundsException: -133189
	at com.taobao.tddl.dbsync.binlog.event.RowsLogBuffer.appendNumber2(RowsLogBuffer.java:1219) ~[classes/:?]
	at com.taobao.tddl.dbsync.binlog.event.RowsLogBuffer.appendNumber3(RowsLogBuffer.java:1211) ~[classes/:?]
	at com.taobao.tddl.dbsync.binlog.event.RowsLogBuffer.appendNumber4(RowsLogBuffer.java:1202) ~[classes/:?]
	at com.taobao.tddl.dbsync.binlog.event.RowsLogBuffer.fetchValue(RowsLogBuffer.java:526) ~[classes/:?]
	at com.taobao.tddl.dbsync.binlog.event.RowsLogBuffer.nextValue(RowsLogBuffer.java:132) ~[classes/:?]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseOneRow(LogEventConvert.java:778) ~[classes/:?]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseRowsEvent(LogEventConvert.java:570) ~[classes/:?]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseRowsEvent(LogEventConvert.java:506) ~[classes/:?]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:117) ~[classes/:?]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:56) ~[classes/:?]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser.parseAndProfilingIfNecessary(AbstractEventParser.java:409) [canal.parse-1.1.7.jar:?]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1$1.sink(AbstractEventParser.java:209) [canal.parse-1.1.7.jar:?]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:225) [canal.parse-1.1.7.jar:?]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$1.run(AbstractEventParser.java:265) [canal.parse-1.1.7.jar:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_351]
```
### Steps to reproduce

- **表结构为**：
```
   CREATE TABLE `cif_1000` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`cif` VARCHAR(20) NOT NULL COLLATE 'utf8_general_ci',
	`region` VARCHAR(10) NOT NULL DEFAULT 'R1' COLLATE 'utf8_general_ci',
	`data` VARCHAR(1024) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`version` SMALLINT(6) UNSIGNED NOT NULL,
	`create_time` DATETIME(3) NOT NULL,
	`update_time` DATETIME(3) NOT NULL,
	PRIMARY KEY (`id`, `region`) USING BTREE,
	UNIQUE INDEX `IDX_cif_region` (`cif`, `region`) USING BTREE,
	INDEX `IDX_update_time` (`update_time`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=COMPACT
AUTO_INCREMENT=34677
;
```
- **mysql56_temporal_format 配置为off**

### Expected behaviour
debug后发现当 mysql56_temporal_format 配置为on时，是可以正常解析datetime(3)类型字段，mysql56_temporal_format 配置为off时无法解析，报错日志如上所示。
**具体调用路径为：**
LogEventConvert.parseOneRow方法 -> buffer.nextValue(columnBuilder.getName(), i, info.type, info.meta, isBinary)方法；
当配置mysql56_temporal_format 为off时，datetime(3) 类型字段，info.type 值是为12(MYSQL_TYPE_DATETIME)，info.meta值为0；
当配置mysql56_temporal_format 为on时，datetime(3) 类型字段，info.type 值是为18(MYSQL_TYPE_DATETIME2)，info.meta值为3；

### Actual behaviour
1.配置mysql56_temporal_format 为off这个是前提，因为生产原有DB运行很多业务，已经配置为off了，没有办法配置为on，对于这部分数据需要进行同步；
2.由于配置mysql56_temporal_format 为off时解析报错，尝试将info.type与meta值修正为 18和3，将解析路径调整到走MYSQL_TYPE_DATETIME2的方式，发现仍然会解析报错，想向社区咨询，这种情况下需要怎么做才能解决这个问题呢？

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by agapple** [comment]
我用了mariadb 10.x的新版本，并没有复现你这个问题，即使配置mysql56_temporal_format为off，对应的info.meta也是18

你最好发一下对应的binlog文件给我，方便我本地复现和验证

**Comment by xwm1992** [comment]
> 我用了mariadb 10.x的新版本，并没有复现你这个问题，即使配置mysql56_temporal_format为off，对应的info.meta也是18
> 
> 你最好发一下对应的binlog文件给我，方便我本地复现和验证

![ceshi](https://github.com/user-attachments/assets/f4cf41c1-96c7-47fd-ac90-33bc116aa1de)
这是当时的一条记录，我目前怀疑mysql56_temporal_format为off后，binlog序列化也是有问题的，这个是用binlog工具导出的内容，可以看到时间戳是有问题的

**Comment by agapple** [comment]
![image](https://github.com/user-attachments/assets/f76fb732-b96f-4200-8605-ba327e226363)

我用mariadb复现了这个问题，应该算是mariadb的bug：
1.  mysql 5.7新的时间格式，支持了毫秒精度，类似于datetime(3)
2. 开启5.6时间格式的兼容参数，如果带上毫秒精度的参数，会导致binlog解析出现异常（mariadb自己的binlog工具都无法解析）

**Comment by agapple** [comment]
![image](https://github.com/user-attachments/assets/1882da99-5416-4f52-ade8-c7d8af45af58)

不带毫秒精度的时间，在mysql56_temporal_format=off时也是可以正常解析的

**Comment by xwm1992** [comment]
> ![image](https://private-user-images.githubusercontent.com/834743/398508882-1882da99-5416-4f52-ade8-c7d8af45af58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU3NDAwNTQsIm5iZiI6MTczNTczOTc1NCwicGF0aCI6Ii84MzQ3NDMvMzk4NTA4ODgyLTE4ODJkYTk5LTU0MTYtNGY1Mi1hZGU4LWM3ZDhhZjQ1YWY1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwMVQxMzU1NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZDAwZjEzZWIyYTFmZDZjNTNmNDg3NjMyNzdjNWIyM2U0OWZlMWZlYzgyYmRmOWMxMTJjMjJjMjliZDVhNWUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UOg0US111ARDSDP3rD8iwj9dce7f5eLL0TASlO9OCPY)
> 
> 不带毫秒精度的时间，在mysql56_temporal_format=off时也是可以正常解析的

是的，那看来就是我们的场景了，这种场景下有什么建议么，或者改造修复的方向也行

**Comment by agapple** [comment]
> > ![image](https://private-user-images.githubusercontent.com/834743/398508882-1882da99-5416-4f52-ade8-c7d8af45af58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU3NDAwNTQsIm5iZiI6MTczNTczOTc1NCwicGF0aCI6Ii84MzQ3NDMvMzk4NTA4ODgyLTE4ODJkYTk5LTU0MTYtNGY1Mi1hZGU4LWM3ZDhhZjQ1YWY1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwMVQxMzU1NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZDAwZjEzZWIyYTFmZDZjNTNmNDg3NjMyNzdjNWIyM2U0OWZlMWZlYzgyYmRmOWMxMTJjMjJjMjliZDVhNWUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UOg0US111ARDSDP3rD8iwj9dce7f5eLL0TASlO9OCPY)
> > 不带毫秒精度的时间，在mysql56_temporal_format=off时也是可以正常解析的
> 
> 是的，那看来就是我们的场景了，这种场景下有什么建议么，或者改造修复的方向也行

去掉毫秒精度，或者修改mysql56_temporal_format=on

**Comment by xwm1992** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/834743/398508882-1882da99-5416-4f52-ade8-c7d8af45af58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU3NDAwNTQsIm5iZiI6MTczNTczOTc1NCwicGF0aCI6Ii84MzQ3NDMvMzk4NTA4ODgyLTE4ODJkYTk5LTU0MTYtNGY1Mi1hZGU4LWM3ZDhhZjQ1YWY1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwMVQxMzU1NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZDAwZjEzZWIyYTFmZDZjNTNmNDg3NjMyNzdjNWIyM2U0OWZlMWZlYzgyYmRmOWMxMTJjMjJjMjliZDVhNWUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UOg0US111ARDSDP3rD8iwj9dce7f5eLL0TASlO9OCPY)
> > > 不带毫秒精度的时间，在mysql56_temporal_format=off时也是可以正常解析的
> > 
> > 
> > 是的，那看来就是我们的场景了，这种场景下有什么建议么，或者改造修复的方向也行
> 
> 去掉毫秒精度，或者修改mysql56_temporal_format=on

目前是考虑改为on，但是这个配置改为on之后，貌似只会对新建的表结构生效，存量的数据变更仍然会有问题
