### ISSUE TITLE
canal 启动instance实例报错， Cannot resolve reference to bean 'metaManager' while setting bean property 'metaManager'

### ISSUE THREAD

**Issue by goheader** [alibaba/canal#5338]
## Question

只需要单体，未配置高可用

canal.properties 中的zookeeper信息配置如下：
 grep -E 'zookeeper|zk' canal.properties |grep -v "#"
canal.zkServers =
canal.zookeeper.flush.period = 1000

canal.log 日志如下：

2024-12-02 11:33:50.439 [Thread-4] INFO  com.alibaba.otter.canal.deployer.CanalStarter - ## stop the canal server
2024-12-02 11:33:50.454 [Thread-4] INFO  com.alibaba.otter.canal.deployer.CanalController - ## stop the canal server[192.168.179.203(192.168.179.203):11111]
2024-12-02 11:33:50.455 [Thread-4] INFO  com.alibaba.otter.canal.deployer.CanalStarter - ## canal server is down.
2024-12-02 11:33:51.865 [main] INFO  com.alibaba.otter.canal.deployer.CanalLauncher - ## set default uncaught exception handler
2024-12-02 11:33:51.907 [main] INFO  com.alibaba.otter.canal.deployer.CanalLauncher - ## load canal configurations
2024-12-02 11:33:51.918 [main] INFO  com.alibaba.otter.canal.deployer.CanalStarter - ## start the canal server.
2024-12-02 11:33:51.959 [main] INFO  com.alibaba.otter.canal.deployer.CanalController - ## start the canal server[192.168.179.203(192.168.179.203):11111]
2024-12-02 11:33:52.451 [main] ERROR c.a.o.c.common.zookeeper.running.ServerRunningMonitor - start failed
com.google.common.util.concurrent.UncheckedExecutionException: com.alibaba.otter.canal.common.CanalException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'instance' defined in class path resource [spring/ob-default-instance.xml]: Cannot resolve reference to bean 'metaManager' while setting bean property 'metaManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'metaManager' defined in class path resource [spring/ob-default-instance.xml]: Cannot create inner bean 'com.alibaba.otter.canal.meta.ZooKeeperMetaManager#5cee5251' of type [com.alibaba.otter.canal.meta.ZooKeeperMetaManager] while setting bean property 'zooKeeperMetaManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.alibaba.otter.canal.meta.ZooKeeperMetaManager#5cee5251' defined in class path resource [spring/ob-default-instance.xml]: Cannot resolve reference to bean 'zkClientx' while setting bean property 'zkClientx'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'zkClientx' defined in class path resource [spring/ob-default-instance.xml]: Invocation of init method failed; nested exception is com.google.common.util.concurrent.UncheckedExecutionException: java.lang.ArrayIndexOutOfBoundsException: 0
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2218)
        at com.google.common.cache.LocalCache.get(LocalCache.java:4147)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4151)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5140)
        at com.google.common.collect.MigrateMap$MigrateConcurrentMap.get(MigrateMap.java:68)
        at com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded.start(CanalServerWithEmbedded.java:128)
        at com.alibaba.otter.canal.deployer.CanalController$1.processActiveEnter(CanalController.java:152)
        at com.alibaba.otter.canal.common.zookeeper.running.ServerRunningMonitor.processActiveEnter(ServerRunningMonitor.java:242)
        at com.alibaba.otter.canal.common.zookeeper.running.ServerRunningMonitor.start(ServerRunningMonitor.java:99)
        at com.alibaba.otter.canal.deployer.CanalController.start(CanalController.java:497)
        at com.alibaba.otter.canal.deployer.CanalStarter.start(CanalStarter.java:89)
        at com.alibaba.otter.canal.deployer.CanalLauncher.main(CanalLauncher.java:117)
Caused by: com.alibaba.otter.canal.common.CanalException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'instance' defined in class path resource [spring/ob-default-instance.xml]: Cannot resolve reference to bean 'metaManager' while setting bean property 'metaManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'metaManager' defined in class path resource [spring/ob-default-instance.xml]: Cannot create inner bean 'com.alibaba.otter.canal.meta.ZooKeeperMetaManager#5cee5251' of type [com.alibaba.otter.canal.meta.ZooKeeperMetaManager] while setting bean property 'zooKeeperMetaManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.alibaba.otter.canal.meta.ZooKeeperMetaManager#5cee5251' defined in class path resource [spring/ob-default-instance.xml]: Cannot resolve reference to bean 'zkClientx' while setting bean property 'zkClientx'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'zkClientx' defined in class path resource [spring/ob-default-instance.xml]: Invocation of init method failed; nested exception is com.google.common.util.concurrent.UncheckedExecutionException: java.lang.ArrayIndexOutOfBoundsException: 0
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'instance' defined in class path resource [spring/ob-default-instance.xml]: Cannot resolve reference to bean 'metaManager' while setting bean property 'metaManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'metaManager' defined in class path resource [spring/ob-default-instance.xml]: Cannot create inner bean 'com.alibaba.otter.canal.meta.ZooKeeperMetaManager#5cee5251' of type [com.alibaba.otter.canal.meta.ZooKeeperMetaManager] while setting bean property 'zooKeeperMetaManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.alibaba.otter.canal.meta.ZooKeeperMetaManager#5cee5251' defined in class path resource [spring/ob-default-instance.xml]: Cannot resolve reference to bean 'zkClientx' while setting bean property 'zkClientx'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'zkClientx' defined in class path resource [spring/ob-default-instance.xml]: Invocation of init method failed; nested exception is com.google.common.util.concurrent.UncheckedExecutionException: java.lang.ArrayIndexOutOfBoundsException: 0
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:378)
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:110)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1605)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1357)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:578)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:501)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:760)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
        at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:144)
        at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:85)
        at com.alibaba.otter.canal.instance.spring.SpringCanalInstanceGenerator.getBeanFactory(SpringCanalInstanceGenerator.java:47)
        at com.alibaba.otter.canal.instance.spring.SpringCanalInstanceGenerator.generate(SpringCanalInstanceGenerator.java:30)
        at com.alibaba.otter.canal.deployer.CanalController.lambda$initGlobalConfig$2(CanalController.java:378)
        at com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded.lambda$start$0(CanalServerWithEmbedded.java:78)
        at com.google.common.collect.MigrateMap$1.load(MigrateMap.java:23)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3708)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2416)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2299)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2212)
        at com.google.common.cache.LocalCache.get(LocalCache.java:4147)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4151)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5140)
        at com.google.common.collect.MigrateMap$MigrateConcurrentMap.get(MigrateMap.java:68)
        at com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded.start(CanalServerWithEmbedded.java:128)
        at com.alibaba.otter.canal.deployer.CanalController$1.processActiveEnter(CanalController.java:152)
        at com.alibaba.otter.canal.common.zookeeper.running.ServerRunningMonitor.processActiveEnter(ServerRunningMonitor.java:242)
        at com.alibaba.otter.canal.common.zookeeper.running.ServerRunningMonitor.start(ServerRunningMonitor.java:99)
        at com.alibaba.otter.canal.deployer.CanalController.start(CanalController.java:497)
        at com.alibaba.otter.canal.deployer.CanalStarter.start(CanalStarter.java:89)
        at com.alibaba.otter.canal.deployer.CanalLauncher.main(CanalLauncher.java:117)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'metaManager' defined in class path resource [spring/ob-default-instance.xml]: Cannot create inner bean 'com.alibaba.otter.canal.meta.ZooKeeperMetaManager#5cee5251' of type [com.alibaba.otter.canal.meta.ZooKeeperMetaManager] while setting bean property 'zooKeeperMetaManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.alibaba.otter.canal.meta.ZooKeeperMetaManager#5cee5251' defined in class path resource [spring/ob-default-instance.xml]: Cannot resolve reference to bean 'zkClientx' while setting bean property 'zkClientx'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'zkClientx' defined in class path resource [spring/ob-default-instance.xml]: Invocation of init method failed; nested exception is com.google.common.util.concurrent.UncheckedExecutionException: java.lang.ArrayIndexOutOfBoundsException: 0
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:327)
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:124)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1605)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1357)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:578)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:501)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:367)
        ... 34 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.alibaba.otter.canal.meta.ZooKeeperMetaManager#5cee5251' defined in class path resource [spring/ob-default-instance.xml]: Cannot resolve reference to bean 'zkClientx' while setting bean property 'zkClientx'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'zkClientx' defined in class path resource [spring/ob-default-instance.xml]: Invocation of init method failed; nested exception is com.google.common.util.concurrent.UncheckedExecutionException: java.lang.ArrayIndexOutOfBoundsException: 0
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:378)
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:110)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1605)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1357)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:578)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:501)
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:312)
        ... 44 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'zkClientx' defined in class path resource [spring/ob-default-instance.xml]: Invocation of init method failed; nested exception is com.google.common.util.concurrent.UncheckedExecutionException: java.lang.ArrayIndexOutOfBoundsException: 0
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1702)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:579)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:501)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:367)
        ... 50 common frames omitted
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.ArrayIndexOutOfBoundsException: 0
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2218)
        at com.google.common.cache.LocalCache.get(LocalCache.java:4147)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4151)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5140)
        at com.google.common.collect.MigrateMap$MigrateConcurrentMap.get(MigrateMap.java:68)
        at com.alibaba.otter.canal.common.zookeeper.ZkClientx.getZkClient(ZkClientx.java:28)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:280)
        at org.springframework.beans.factory.config.MethodInvokingBean.invokeWithTargetException(MethodInvokingBean.java:123)
        at org.springframework.beans.factory.config.MethodInvokingFactoryBean.afterPropertiesSet(MethodInvokingFactoryBean.java:108)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1761)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1698)
        ... 57 common frames omitted
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
        at java.util.Arrays$ArrayList.get(Arrays.java:3841)
        at com.alibaba.otter.canal.common.zookeeper.ZooKeeperx.connect(ZooKeeperx.java:68)
        at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:1228)
        at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:157)
        at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:131)
        at com.alibaba.otter.canal.common.zookeeper.ZkClientx.<init>(ZkClientx.java:56)
        at com.alibaba.otter.canal.common.zookeeper.ZkClientx.<init>(ZkClientx.java:52)
        at com.alibaba.otter.canal.common.zookeeper.ZkClientx.<init>(ZkClientx.java:40)
        at com.alibaba.otter.canal.common.zookeeper.ZkClientx.<init>(ZkClientx.java:36)
        at com.google.common.collect.MigrateMap$1.load(MigrateMap.java:23)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3708)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2416)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2299)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2212)
        ... 71 common frames omitted
2024-12-02 11:33:52.487 [main] INFO  com.alibaba.otter.canal.deployer.CanalStarter - ## the canal server is running now ......
2024-12-02 11:33:52.488 [main] DEBUG com.alibaba.otter.canal.deployer.CanalStarter - canal admin port:11110, canal admin user:admin, canal admin password: 4ACFE3202A5FF5CF467898FC58AAB1D615029441, canal ip:

**Comment by agapple** [comment]
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
at java.util.Arrays$ArrayList.get(Arrays.java:3841)
at com.alibaba.otter.canal.common.zookeeper.ZooKeeperx.connect(ZooKeeperx.java:68)
```
zookeeper的配置为空

**Comment by dc1209** [comment]
单机模式配置这两项
canal.instance.tsdb.enable = true 
canal.instance.global.spring.xml = classpath:spring/file-instance.xml
