### ISSUE TITLE
java.net.SocketException: Socket Closed

### ISSUE THREAD

**Issue by lisxu** [alibaba/canal#5341]
## canal 突然间dump不到数据了
com.alibaba.otter.canal.parse.exception.CanalParseException: dump address /192.168.100.218:3888 has an error, retrying. 
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: java.net.SocketException: Socket Closed
Caused by: java.net.SocketException: Socket Closed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read1(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:52)
	at com.alibaba.otter.canal.parse.driver.mysql.utils.PacketManager.readHeader(PacketManager.java:13)
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlQueryExecutor.readNextPacket(MysqlQueryExecutor.java:165)
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlQueryExecutor.query(MysqlQueryExecutor.java:56)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.query(MysqlConnection.java:106)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.loadBinlogFormat(MysqlConnection.java:494)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.getBinlogFormat(MysqlConnection.java:669)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.preDump(MysqlEventParser.java:95)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParserProxy$1.run(MysqlEventParserProxy.java:174)
	at java.lang.Thread.run(Unknown Source)

**Comment by agapple** [comment]
Caused by: java.net.SocketException: Socket Closed

看着是mysql服务端关闭了链接
