### ISSUE TITLE
canal server解析异常

### ISSUE THREAD

**Issue by wuqiu-ai** [alibaba/canal#5342]
## Question

异常如下：
com.alibaba.otter.canal.parse.exception.CanalParseException: com.alibaba.otter.canal.parse.exception.CanalParseException: apply history to db failed caused by : SqlMapClient operation; uncategorized SQLException for SQL []; SQL state [90098]; error code [90098];   
--- The error occurred in spring/tsdb/sql-map/sqlmap_history.xml.  
--- The error occurred while applying a parameter map.  
--- Check the meta_history.insert-InlineParameterMap.  
--- Check the statement (update failed).  
--- Cause: org.h2.jdbc.JdbcSQLException: The database has been closed [90098-196]; nested exception is com.ibatis.common.jdbc.exception.NestedSQLException:   
--- The error occurred in spring/tsdb/sql-map/sqlmap_history.xml.  
--- The error occurred while applying a parameter map.  
--- Check the meta_history.insert-InlineParameterMap.  
--- Check the statement (update failed).  
--- Cause: org.h2.jdbc.JdbcSQLException: The database has been closed [90098-196]
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: apply history to db failed caused by : SqlMapClient operation; uncategorized SQLException for SQL []; SQL state [90098]; error code [90098];   
--- The error occurred in spring/tsdb/sql-map/sqlmap_history.xml.  
--- The error occurred while applying a parameter map.  
--- Check the meta_history.insert-InlineParameterMap.  
--- Check the statement (update failed).  
--- Cause: org.h2.jdbc.JdbcSQLException: The database has been closed [90098-196]; nested exception is com.ibatis.common.jdbc.exception.NestedSQLException:   
--- The error occurred in spring/tsdb/sql-map/sqlmap_history.xml.  
--- The error occurred while applying a parameter map.  
--- Check the meta_history.insert-InlineParameterMap.  
--- Check the statement (update failed).  
--- Cause: org.h2.jdbc.JdbcSQLException: The database has been closed [90098-196]
Caused by: org.springframework.jdbc.UncategorizedSQLException: SqlMapClient operation; uncategorized SQLException for SQL []; SQL state [90098]; error code [90098];   
--- The error occurred in spring/tsdb/sql-map/sqlmap_history.xml.  
--- The error occurred while applying a parameter map.  
--- Check the meta_history.insert-InlineParameterMap.  
--- Check the statement (update failed).  
--- Cause: org.h2.jdbc.JdbcSQLException: The database has been closed [90098-196]; nested exception is com.ibatis.common.jdbc.exception.NestedSQLException:   
--- The error occurred in spring/tsdb/sql-map/sqlmap_history.xml.  
--- The error occurred while applying a parameter map.  
--- Check the meta_history.insert-InlineParameterMap.  
--- Check the statement (update failed).  
--- Cause: org.h2.jdbc.JdbcSQLException: The database has been closed [90098-196]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:83) ~[spring-jdbc-3.2.18.RELEASE.jar:3.2.18.RELEASE]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80) ~[spring-jdbc-3.2.18.RELEASE.jar:3.2.18.RELEASE]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80) ~[spring-jdbc-3.2.18.RELEASE.jar:3.2.18.RELEASE]
	at org.springframework.orm.ibatis.SqlMapClientTemplate.execute(SqlMapClientTemplate.java:206) ~[spring-orm-3.2.18.RELEASE.jar:3.2.18.RELEASE]
	at org.springframework.orm.ibatis.SqlMapClientTemplate.insert(SqlMapClientTemplate.java:367) ~[spring-orm-3.2.18.RELEASE.jar:3.2.18.RELEASE]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.dao.MetaHistoryDAO.insert(MetaHistoryDAO.java:18) ~[canal.parse-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.applyHistoryToDB(DatabaseTableMeta.java:275) ~[canal.parse-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.apply(DatabaseTableMeta.java:160) ~[canal.parse-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.TableMetaCache.apply(TableMetaCache.java:238) ~[canal.parse-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseQueryEvent(LogEventConvert.java:273) ~[canal.parse-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:118) ~[canal.parse-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:296) ~[canal.parse-1.1.5-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:250) ~[canal.parse-1.1.5-SNAPSHOT.jar:na]
	at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168) ~[disruptor-3.4.2.jar:na]
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125) ~[disruptor-3.4.2.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_172]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_172]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_172]
Caused by: com.ibatis.common.jdbc.exception.NestedSQLException:   
--- The error occurred in spring/tsdb/sql-map/sqlmap_history.xml.  
--- The error occurred while applying a parameter map.  
--- Check the meta_history.insert-InlineParameterMap.  
--- Check the statement (update failed).  
--- Cause: org.h2.jdbc.JdbcSQLException: The database has been closed [90098-196]
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeUpdate(MappedStatement.java:107) ~[ibatis-sqlmap-2.3.4.726.jar:na]
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.insert(SqlMapExecutorDelegate.java:393) ~[ibatis-sqlmap-2.3.4.726.jar:na]
	at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.insert(SqlMapSessionImpl.java:82) ~[ibatis-sqlmap-2.3.4.726.jar:na]
	at org.springframework.orm.ibatis.SqlMapClientTemplate$8.doInSqlMapClient(SqlMapClientTemplate.java:369) ~[spring-orm-3.2.18.RELEASE.jar:3.2.18.RELEASE]
	at org.springframework.orm.ibatis.SqlMapClientTemplate.execute(SqlMapClientTemplate.java:203) ~[spring-orm-3.2.18.RELEASE.jar:3.2.18.RELEASE]
	... 16 common frames omitted
Caused by: org.h2.jdbc.JdbcSQLException: The database has been closed [90098-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.message.DbException.get(DbException.java:179) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.message.DbException.get(DbException.java:155) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.message.DbException.get(DbException.java:144) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.engine.Session.getTransaction(Session.java:1636) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.engine.Session.getStatementSavepoint(Session.java:1646) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.engine.Session.setSavepoint(Session.java:825) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.command.Command.executeUpdate(Command.java:254) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:207) ~[h2-1.4.196.jar:1.4.196]
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:498) ~[druid-1.1.9.jar:1.1.9]
	at com.ibatis.sqlmap.engine.execution.SqlExecutor.executeUpdate(SqlExecutor.java:80) ~[ibatis-sqlmap-2.3.4.726.jar:na]
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.sqlExecuteUpdate(MappedStatement.java:216) ~[ibatis-sqlmap-2.3.4.726.jar:na]
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeUpdate(MappedStatement.java:94) ~[ibatis-sqlmap-2.3.4.726.jar:na]
	... 20 common frames omitted

解决方案：
重启canal通道恢复

**Comment by agapple** [comment]
Caused by: org.h2.jdbc.JdbcSQLException: The database has been closed [90098-196]

**Comment by wuqiu-ai** [comment]
The database has been closed 怎么会无缘无故关闭连接，用的是内存数据库
