### ISSUE TITLE
canal-1.1.8-alpha-2 开始测试用例编辑报错

### ISSUE THREAD

**Issue by waroyhz** [alibaba/canal#5349]
### environment

* canal version
* canal-1.1.8-alpha-2

### Issue Description

com.alibaba.otter.canal.parse测试用例编译报错
比如  com.alibaba.otter.canal.parse.inbound.mysql.tsdb.FastsqlSchemaTest 

错误信息:
```
com.alibaba.polardbx.druid.sql.parser.ParserException: syntax error, error in :'at`) /*!80000 INVISIBLE */) ENGINE=', expect ), actual null, pos 207, line 1, column 187, token HINT

	at com.alibaba.polardbx.druid.sql.parser.SQLParser.printError(SQLParser.java:531)
	at com.alibaba.polardbx.druid.sql.parser.SQLParser.accept(SQLParser.java:545)
	at com.alibaba.polardbx.druid.sql.dialect.mysql.parser.MySqlCreateTableParser.parseCreateTable(MySqlCreateTableParser.java:582)
	at com.alibaba.polardbx.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseCreate(MySqlStatementParser.java:816)
	at com.alibaba.polardbx.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:578)
	at com.alibaba.polardbx.druid.sql.SQLUtils.parseStatements(SQLUtils.java:450)
	at com.alibaba.polardbx.druid.sql.repository.SchemaRepository.console(SchemaRepository.java:470)
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.FastsqlSchemaTest.test_invisible(FastsqlSchemaTest.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
```

**Comment by waroyhz** [comment]
看起来像是com.alibaba.polardbx.druid里的版本太低了，不支持。

**Comment by agapple** [comment]
最新的https://github.com/polardb/polardbx-sql 已更新，可以本地mvn clean install后替换解析包，就可以正常运行
