### ISSUE TITLE
canalserver升级到1.0.25启动出现create connection SQLException

### ISSUE THREAD

**Issue by AnakinSkyW** [alibaba/canal#546]
2018-03-02 16:10:49.030 [Druid-ConnectionPool-Create-124634922] ERROR com.alibaba.druid.pool.DruidDataSource - create connection SQLException, url: , errorCode 0, state null
java.sql.SQLException: connect error, url , driverClass org.h2.Driver
        at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1579) ~[druid-1.1.6.jar:1.1.6]
        at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2450) ~[druid-1.1.6.jar:1.1.6]

**Comment by agapple** [comment]
启动时会初始化一个嵌入式的H2内存数据库，看看启动失败的具体原因吧
