### ISSUE TITLE
com.alibaba.otter.canal.protocol.exception.CanalClientException: java.io.IOException: Broken pipe

### ISSUE THREAD

**Issue by KingOfGreat** [alibaba/canal#550]
这个是安装完canal后运行example示例代码出现的问题
com.alibaba.otter.canal.protocol.exception.CanalClientException: java.io.IOException: Broken pipe
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.getWithoutAck(SimpleCanalConnector.java:296) ~[canal.client-1.0.25.jar:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.getWithoutAck(SimpleCanalConnector.java:269) ~[canal.client-1.0.25.jar:na]
	at com.iwaimai.CanalTest.AbstractCanalClientTest.process(AbstractCanalClientTest.java:116) ~[classes/:na]
	at com.iwaimai.CanalTest.AbstractCanalClientTest$2.run(AbstractCanalClientTest.java:83) [classes/:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_162]
Caused by: java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[na:1.8.0_162]
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47) ~[na:1.8.0_162]
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93) ~[na:1.8.0_162]
	at sun.nio.ch.IOUtil.write(IOUtil.java:65) ~[na:1.8.0_162]
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471) ~[na:1.8.0_162]
	at java.nio.channels.Channels.writeFullyImpl(Channels.java:78) ~[na:1.8.0_162]
	at java.nio.channels.Channels.writeFully(Channels.java:98) ~[na:1.8.0_162]
	at java.nio.channels.Channels.access$000(Channels.java:61) ~[na:1.8.0_162]
	at java.nio.channels.Channels$1.write(Channels.java:174) ~[na:1.8.0_162]
	at java.nio.channels.Channels$WritableByteChannelImpl.write(Channels.java:458) ~[na:1.8.0_162]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.writeWithHeader(SimpleCanalConnector.java:382) ~[canal.client-1.0.25.jar:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.writeWithHeader(SimpleCanalConnector.java:369) ~[canal.client-1.0.25.jar:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.getWithoutAck(SimpleCanalConnector.java:281) ~[canal.client-1.0.25.jar:na]
	... 4 common frames omitted
10:26:39.350 [Thread-0] ERROR c.i.C.AbstractCanalClientTest - process error!
com.alibaba.otter.canal.protocol.exception.CanalClientException: something goes wrong with reason: something goes wrong with channel:[id: 0x57943e05, /10.11.61.139:53053 => /10.11.61.139:11111], exception=com.alibaba.otter.canal.server.exception.CanalServerException: destination:example should start first

	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.receiveMessages(SimpleCanalConnector.java:317) ~[canal.client-1.0.25.jar:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.getWithoutAck(SimpleCanalConnector.java:294) ~[canal.client-1.0.25.jar:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.getWithoutAck(SimpleCanalConnector.java:269) ~[canal.client-1.0.25.jar:na]
	at com.iwaimai.CanalTest.AbstractCanalClientTest.process(AbstractCanalClientTest.java:116) ~[classes/:na]
	at com.iwaimai.CanalTest.AbstractCanalClientTest$2.run(AbstractCanalClientTest.java:83) [classes/:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_162]
10:26:39.351 [Thread-0] ERROR c.i.C.AbstractCanalClientTest - process error!
com.alibaba.otter.canal.protocol.exception.CanalClientException: something goes wrong with reason: something goes wrong with channel:[id: 0x4f01a4c1, /10.11.61.139:53054 => /10.11.61.139:11111], exception=com.alibaba.otter.canal.server.exception.CanalServerException: destination:example should start first

	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.receiveMessages(SimpleCanalConnector.java:317) ~[canal.client-1.0.25.jar:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.getWithoutAck(SimpleCanalConnector.java:294) ~[canal.client-1.0.25.jar:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.getWithoutAck(SimpleCanalConnector.java:269) ~[canal.client-1.0.25.jar:na]
	at com.iwaimai.CanalTest.AbstractCanalClientTest.process(AbstractCanalClientTest.java:116) ~[classes/:na]
	at com.iwaimai.CanalTest.AbstractCanalClientTest$2.run(AbstractCanalClientTest.java:83) [classes/:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_162]
10:26:39.352 [Thread-0] ERROR c.i.C.AbstractCanalClientTest - process error!
com.alibaba.otter.canal.protocol.exception.CanalClientException: something goes wrong with reason: something goes wrong with channel:[id: 0x7e3c718f, /10.11.61.139:53055 => /10.11.61.139:11111], exception=com.alibaba.otter.canal.server.exception.CanalServerException: destination:example should start first

	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.receiveMessages(SimpleCanalConnector.java:317) ~[canal.client-1.0.25.jar:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.getWithoutAck(SimpleCanalConnector.java:294) ~[canal.client-1.0.25.jar:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.getWithoutAck(SimpleCanalConnector.java:269) ~[canal.client-1.0.25.jar:na]
	at com.iwaimai.CanalTest.AbstractCanalClientTest.process(AbstractCanalClientTest.java:116) ~[classes/:na]
	at com.iwaimai.CanalTest.AbstractCanalClientTest$2.run(AbstractCanalClientTest.java:83) [classes/:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_162]

**Comment by agapple** [comment]
客户端做一下重试

**Comment by agapple** [comment]
升级一下26版本
