### ISSUE TITLE
javax.mail.AuthenticationFailedException: 526 Authentication failure

### ISSUE THREAD

**Issue by Wu-Jianqiang** [alibaba/canal#554]
环境：阿里云企业邮箱，SSL端口，SMTP 要求用户验证。

2018-03-12 21:51:02.457 ERROR c.a.otter.manager.biz.common.alarm.AbstractAlarmService - send alarm [AlarmMessage[message=pid:1 nid:2 exception:canal:ZjcsToDsb:java.io.IOException: socket read timeout occured ! readSize = 4, readableBytes = 0, timeout = 16000
        at com.alibaba.otter.canal.parse.driver.mysql.socket.SocketChannel.read(SocketChannel.java:172)
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:174)
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:80)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:144)
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:220)
        at java.lang.Thread.run(Thread.java:745)
,receiveKey=otterteam]] to drgoon agent error!
org.springframework.mail.MailAuthenticationException: Authentication failed; nested exception is javax.mail.AuthenticationFailedException: 526 Authentication failure[0]

        at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:392) ~[spring-context-support-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:306) ~[spring-context-support-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:296) ~[spring-context-support-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at com.alibaba.otter.manager.biz.common.alarm.DefaultAlarmService.doSendMail(DefaultAlarmService.java:62) ~[manager.biz-4.2.16-SNAPSHOT.jar:na]
        at com.alibaba.otter.manager.biz.common.alarm.DefaultAlarmService.doSend(DefaultAlarmService.java:52) ~[manager.biz-4.2.16-SNAPSHOT.jar:na]
        at com.alibaba.otter.manager.biz.common.alarm.AbstractAlarmService.sendAlarmInternal(AbstractAlarmService.java:60) [manager.biz-4.2.16-SNAPSHOT.jar:na]
        at com.alibaba.otter.manager.biz.common.alarm.AbstractAlarmService.access$000(AbstractAlarmService.java:38) [manager.biz-4.2.16-SNAPSHOT.jar:na]
        at com.alibaba.otter.manager.biz.common.alarm.AbstractAlarmService$1.run(AbstractAlarmService.java:77) [manager.biz-4.2.16-SNAPSHOT.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_79]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_79]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
Caused by: javax.mail.AuthenticationFailedException: 526 Authentication failure[0]

        at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:826) ~[mail-1.4.7.jar:1.4.7]
        at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:761) ~[mail-1.4.7.jar:1.4.7]
        at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:685) ~[mail-1.4.7.jar:1.4.7]
        at javax.mail.Service.connect(Service.java:295) ~[mail-1.4.7.jar:1.4.7]
        at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:389) ~[spring-context-support-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        ... 12 common frames omitted

**Comment by agapple** [comment]
JavaMailSenderImpl只调通了163和gmail，其他的需要做一些调试

**Comment by agapple** [comment]
可以提交一个PR给我
