### ISSUE TITLE
如何在客户端重置Canal的位置？现在的位点在远程Canal所监听的mysql binlog时间长了已经删了 message message.getId()为-1

### ISSUE THREAD

**Issue by WilliamGai** [alibaba/canal#561]
### 问题描述：  
现在的位点在远程Canal所监听的mysql binlog时间长了已经删了。  
 message message.getId()为永远为-1。  
message.getEntries().size() 永远为 0，永远读不出数据！！

### 疑问：  
请问如何在不改动 远程Canal服务的配置或其他啊哦做的情况下，客户端自己重置位置为最新的？  
就是监听最新的binlog消息，之前的binlog就忽略？？？

## Canal 服务destination配置
```
canal.instance.mysql.slaveId = 617

# position info
canal.instance.master.address = 10.1.6.226:3307
canal.instance.master.journal.name =
canal.instance.master.position =
canal.instance.master.timestamp =

#canal.instance.standby.address =
#canal.instance.standby.journal.name =
#canal.instance.standby.position =
#canal.instance.standby.timestamp =

# username/password
canal.instance.dbUsername = mescanal
canal.instance.dbPassword = mescanal
canal.instance.defaultDatabaseName =
canal.instance.connectionCharset = UTF-8

# table regex
canal.instance.filter.regex = .*\\..*
# table black regex
canal.instance.filter.black.regex =
```
## meta.data
```
cat meta.dat
{"clientDatas":[{"clientIdentity":{"clientId":1001,"destination":"mysql_b7_gaotaiunyue","filter":".*\\..*"},"cursor":{"identity":{"slaveId":-1,"sourceAddress":{"address":"10.1.6.226","port":3307}},"postion":{"included":false,"journalName":"my3307-bin.000303","position":77593731,"serverId":3307,"timestamp":1521010166000}}}],"destination":"mysql_b7_gaotaiunyue"}
```
## 这是日志代码
```
2018-03-22 10:41:54.051 [destination = mysql_b7_gaotianyue , address = /10.1.6.226:3307 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - dump address /10.1.6.226:3307 has an error, retrying. caused by
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:95) ~[canal.parse-1.0.22.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:113) ~[canal.parse-1.0.22.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:210) ~[canal.parse-1.0.22.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65]
2018-03-22 10:41:54.051 [destination = mysql_b7_gaotianyue , address = /10.1.6.226:3307 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:mysql_b7_liupengchun[java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:95)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:113)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:210)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by agapple** [comment]
Could not find first log file name in binary log index file，位点不存在

**Comment by AnakinSkyW** [comment]
同感，能不能在位点异常错误的情况下，自动重置到最新的位点

**Comment by yunyulian77** [comment]
+1,出现次数较多

**Comment by niujialin** [comment]
同上

**Comment by geckhan** [comment]
+1

**Comment by agapple** [comment]
参考FAQ :  https://github.com/alibaba/canal/wiki/FAQ

**Comment by pc-fuqq** [comment]
+1,被搞死了

**Comment by gabrywu** [comment]
确实，搞成自动的最好。要不然没法弄

**Comment by agapple** [comment]
仔细想了下这个需求，估计在测试环境会比较有用 (环境不稳定，binlog被删除之后，自动按最新的数据订阅)

可以考虑增加一个外部参数控制，允许位点不存在时自动重置到当前位点，有兴趣的同学，可以考虑提交一个PR给我

**Comment by kaysonyang** [comment]
同问
