### ISSUE TITLE
 canal.deployer-1.0.26-SNAPSHOT版本rds获取不到日志信息

### ISSUE THREAD

**Issue by PassionDs** [alibaba/canal#567]
配置在本地的mysql，然后进行操作可以获取到操作信息
配置rds上的，操作无法获取到操作信息
只配置了instance.properties，还需要配置rds_instance.properties吗？
rds上报：canal.log里面报错
2018-03-28 15:28:06.345 [New I/O server worker #1-2] ERROR c.a.otter.canal.server.netty.handler.SessionHandler - something goes wrong with channel:[id: 0x729a1c21, /192.168.10.156:64481 => /192.168.10.156:11111], exception=java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:322)
	at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:281)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:201)
	at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by agapple** [comment]
exception=java.io.IOException: 远程主机强迫关闭了一个现有的连接。

估计和canal server断链了

**Comment by PassionDs** [comment]
请问那要怎么处理呢
