### ISSUE TITLE
canal.deployer-1.0.26-SNAPSHOT报错

### ISSUE THREAD

**Issue by PassionDs** [alibaba/canal#576]
有两个instance配置，分别为example和example1里面的
正常启动过后过一会儿会客户端报错：
java.lang.NullPointerException 
at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.writeWithHeader(SimpleCanalConnector.java:358)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.ack(SimpleCanalConnector.java:318)
ack batchId的时候报的空指针
报错的代码行为：connector.ack(batchId);

**Comment by agapple** [comment]
代码行和我这边对不上，自己改动过？
