### ISSUE TITLE
无法连接canal服务端

### ISSUE THREAD

**Issue by jnliao** [alibaba/canal#580]
使用下面方法创建canal连接
`CanalConnector canalConnector = CanalConnectors.newSingleConnector(new InetSocketAddress(canalHost,Integer.parseInt(canalPort)),canalDestination,"","");
canalConnector.connect();`

但是调用connect()方法时报错。报错如下：
`
Caused by: com.alibaba.otter.canal.protocol.exception.CanalClientException: java.net.ConnectException: Connection timed out: connect
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:178)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.connect(SimpleCanalConnector.java:102)`

请问是什么原因呢？之前一直还好好的。从今天开始突然报这个错了。使用的canal版本为canal.deployer-1.0.25

**Comment by jnliao** [comment]
找到原因了，是canal服务端所在服务器的防火墙拦截了11111端口。开放此端口就好了。
