### ISSUE TITLE
1.0.26 这个版本bug造成的吗? 请问canal的版本兼容mysql5.x所有版本吗?我的是5.1.73

### ISSUE THREAD

**Issue by taiziwang** [alibaba/canal#593]
2018-04-01 14:11:50.712 [main] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Loading properties file from class path resource [canal.properties]
2018-04-01 14:11:51.147 [main] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Loading properties file from class path resource [example/instance.properties]
2018-04-01 14:11:52.319 [main] WARN  o.s.beans.GenericTypeAwarePropertyDescriptor - Invalid JavaBean property 'connectionCharset' being accessed! Ambiguous write methods found next to actually used [public void com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.setConnectionCharset(java.lang.String)]: [public void com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.setConnectionCharset(java.nio.charset.Charset)]
2018-04-01 14:11:52.700 [main] INFO  c.a.otter.canal.instance.spring.CanalInstanceWithSpring - start CannalInstance for 1-example 
2018-04-01 14:11:52.774 [main] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - start successful....
2018-04-01 14:11:52.815 [destination = example , address = /192.168.1.110:3306 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - dump address /192.168.1.110:3306 has an error, retrying. caused by 
java.lang.NoSuchMethodError: method java.net.InetSocketAddress.getHostString with signature ()Ljava.lang.String; was not found.
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.<init>(MysqlConnector.java:53) ~[canal.parse.driver-1.0.26-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.<init>(MysqlConnector.java:63) ~[canal.parse.driver-1.0.26-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.<init>(MysqlConnection.java:70) ~[canal.parse-1.0.26-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.buildMysqlConnection(MysqlEventParser.java:308) ~[canal.parse-1.0.26-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.buildErosaConnection(MysqlEventParser.java:76) ~[canal.parse-1.0.26-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:154) ~[canal.parse-1.0.26-SNAPSHOT.jar:na]
        at java.lang.Thread.run(libgcj.so.10) [na:na]
2018-04-01 14:11:52.960 [destination = example , address = /192.168.1.110:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[java.lang.NoSuchMethodError: method java.net.InetSocketAddress.getHostString with signature ()Ljava.lang.String; was not found.
   at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.<init>(MysqlConnector.java:53)
   at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.<init>(MysqlConnector.java:63)
   at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.<init>(MysqlConnection.java:70)
   at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.buildMysqlConnection(MysqlEventParser.java:308)
   at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.buildErosaConnection(MysqlEventParser.java:76)
   at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:154)
   at java.lang.Thread.run(libgcj.so.10)
]
2018-04-01 14:11:52.965 [destination = example , address = /192.168.1.110:3306 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - parse events has an error
java.lang.NullPointerException: null
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.afterDump(MysqlEventParser.java:137) ~[canal.parse-1.0.26-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:249) ~[canal.parse-1.0.26-SNAPSHOT.jar:na]
        at java.lang.Thread.run(libgcj.so.10) ~[na:na]

**Comment by agapple** [comment]
java.lang.NoSuchMethodError: method java.net.InetSocketAddress.getHostString with signature ()Ljava.lang.String; was not found.

你这是啥jdk版本啊

**Comment by shaw1111** [comment]
25版本也有这个问题。jdk1.8

**Comment by agapple** [comment]
这个我只能怀疑是jdk的问题，代码层面oracle的jdk7和jdk8我本地都跑过

**Comment by agapple** [comment]
有具体的复现方法，再reopen吧
