### ISSUE TITLE
canal运行38个小时左右，客户端报错Broken pipe，服务端没报错，什么原因

### ISSUE THREAD

**Issue by PassionDs** [alibaba/canal#601]
com.alibaba.otter.canal.protocol.exception.CanalClientException: java.io.IOException: Broken pipe
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.ack(SimpleCanalConnector.java:343)
Caused by: java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at java.nio.channels.Channels.writeFullyImpl(Channels.java:78)
	at java.nio.channels.Channels.writeFully(Channels.java:98)
	at java.nio.channels.Channels.access$000(Channels.java:61)
	at java.nio.channels.Channels$1.write(Channels.java:174)
	at java.nio.channels.Channels$WritableByteChannelImpl.write(Channels.java:458)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.writeWithHeader(SimpleCanalConnector.java:400)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.writeWithHeader(SimpleCanalConnector.java:387)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.ack(SimpleCanalConnector.java:337)
	... 6 more

**Comment by agapple** [comment]
这是被服务端主动断开连接了

**Comment by PassionDs** [comment]
服务端为什么主动断开连接了，这是不是canal的问题？或者请问要怎么处理？

**Comment by agapple** [comment]
检查server的日志

**Comment by PassionDs** [comment]
server端没报错，就客户端报错了

**Comment by DevWithLin** [comment]
我也有这个问题，请问这是咋回事？我用的是25版本的。

**Comment by agapple** [comment]
https://github.com/alibaba/canal/issues/640，关注一下这个

**Comment by tt-weixin** [comment]
> [https://github.com/alibaba/canal/issues/640，关注一下这个](https://github.com/alibaba/canal/issues/640%EF%BC%8C%E5%85%B3%E6%B3%A8%E4%B8%80%E4%B8%8B%E8%BF%99%E4%B8%AA)

大哥，你老说关注这个，这个链接里现在没东西了呀

**Comment by 982097710** [comment]
怎么解决的

**Comment by tt-weixin** [comment]
更新到1.6能用的最新版本就好了，
