### ISSUE TITLE
com.alibaba.otter.canal.protocol.exception.CanalClientException: java.io.IOException: 您的主机中的软件中止了一个已建立的连接。

### ISSUE THREAD

**Issue by gurenyuan123** [alibaba/canal#603]
2018-04-23 15:05:05.780-[ERROR]-[Thread-0]-com.clickplus.canal.AbstractCanalClientTest:151-process error!
com.alibaba.otter.canal.protocol.exception.CanalClientException: java.io.IOException: 您的主机中的软件中止了一个已建立的连接。
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.ack(SimpleCanalConnector.java:257) ~[canal.client-1.0.4.jar:na]
	at com.clickplus.canal.AbstractCanalClientTest.process(AbstractCanalClientTest.java:143) ~[classes/:na]
	at com.clickplus.canal.AbstractCanalClientTest$2.run(AbstractCanalClientTest.java:86) [classes/:na]
	at java.lang.Thread.run(Thread.java:722) [na:1.7.0_17]
Caused by: java.io.IOException: 您的主机中的软件中止了一个已建立的连接。
	at sun.nio.ch.SocketDispatcher.write0(Native Method) ~[na:1.7.0_17]
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51) ~[na:1.7.0_17]
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:94) ~[na:1.7.0_17]
	at sun.nio.ch.IOUtil.write(IOUtil.java:65) ~[na:1.7.0_17]
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:450) ~[na:1.7.0_17]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.writeWithHeader(SimpleCanalConnector.java:289) ~[canal.client-1.0.4.jar:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.ack(SimpleCanalConnector.java:253) ~[canal.client-1.0.4.jar:na]
	... 3 common frames omitted

**Comment by jnliao** [comment]
问题描述最好详细点，否则不好分析

**Comment by gurenyuan123** [comment]
@jnliao 谢谢回答，小数据量时，canal运行是没有问题的，当有大事务执行时（千级万级的insert），就会报这个错误，调大了buffersize和客户端的batchsize都没什么用

**Comment by jnliao** [comment]
我之前处理数据时也遇到过这种问题。
1、使用场景
我使用的是canal 1.0.25，客户端采用定时任务实时处理canal服务端获取的日志数据，并且每个定时任务都是使用同一个客户端链接对象。数据库瞬间更新1w条数据时，canal客户端处理数据时，运行一会就会一直报你说的这种错误——“Caused by: java.io.IOException: 您的主机中的软件中止了一个已建立的连接。”
2、解决办法
每个定时任务都使用新创建的客户端链接对象。并在任务结束时断开链接。

**Comment by agapple** [comment]
https://github.com/alibaba/canal/issues/640，关注一下这个

**Comment by ldl1205** [comment]
请问这个问题怎么解决的啊？

**Comment by ldl1205** [comment]
偶尔会有这个报错，偶尔又没有

**Comment by ab8846254** [comment]
怎么解决的啊 我也遇到了
