### ISSUE TITLE
java.nio.channels.ClosedByInterruptException

### ISSUE THREAD

**Issue by SkingXiong** [alibaba/canal#613]
2018-04-27 18:29:02.113 [destination = financial , address = /10.44.88.50:13306 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - dump address EulerOS-BaseTemplate/10.44.88.50:13306 has an error, retrying. caused by
java.nio.channels.ClosedByInterruptException: null
        at com.alibaba.otter.canal.parse.driver.mysql.socket.SocketChannel.read(SocketChannel.java:49) ~[canal.parse.driver-1.0.25.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:151) ~[canal.parse-1.0.25.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:77) ~[canal.parse-1.0.25.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:137) ~[canal.parse-1.0.25.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:220) ~[canal.parse-1.0.25.jar:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
2018-04-27 18:29:02.118 [destination = financial , address = /10.44.88.50:13306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:financial[java.nio.channels.ClosedByInterruptException
        at com.alibaba.otter.canal.parse.driver.mysql.socket.SocketChannel.read(SocketChannel.java:49)
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:151)
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:77)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:137)
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:220)
        at java.lang.Thread.run(Thread.java:748)
]

canal：1.0.25版本
destination：financial，deduct
场景：deduct一直能够监测mysql的binlog，financial监测一段时间之后抛了一个这个异常，然后canal client那边一直消费canal server的financal，但是financial不能监测binlog，重启之后又正常了，但是过一段一时间有这样重复了

**Comment by SkingXiong** [comment]
大约过了2.5hours financal destination就挂了

**Comment by agapple** [comment]
试试1.0.26版本

**Comment by devin1975** [comment]
我们用的是1.0.26，也有这个问题。在DUMP时报
java.nio.channels.ClosedByInterruptException，据网上反馈1.0.24没有这个问题，正在做降级验证。
