### ISSUE TITLE
something goes wrong when acking data from server:null

### ISSUE THREAD

**Issue by liuyanjunleo** [alibaba/canal#617]
客户端报错如下：
2018-05-03 17:26:50.735 [pool-2-thread-1]  WARN com.alibaba.otter.canal.client.impl.ClusterCanalConnector.?:? - something goes wrong when acking data from server:null
com.alibaba.otter.canal.protocol.exception.CanalClientException: java.io.IOException: Broken pipe
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.ack(SimpleCanalConnector.java:324)
	at com.alibaba.otter.canal.client.impl.ClusterCanalConnector.ack(ClusterCanalConnector.java:253)
	at com.lyj.order.es.sync.service.impl.AbstractCanalListenerServiceImpl.lambda$startListener$2(AbstractCanalListenerServiceImpl.java:137)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.writeWithHeader(SimpleCanalConnector.java:358)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.ack(SimpleCanalConnector.java:318)
	... 5 more

服务端报错如下：
ERROR com.alibaba.otter.canal.server.netty.NettyUtils 50 - ErrotCode:400 , Caused by: something goes wrong with 
channel:[id:0x0f4b9efb, /10.0.39.56:50004 => /10.0.11.161:11111], exception=com.alibaba.otter.canal.server.exception.CanalServerException: 
ack error , clientId:1001 batchld:718 is not exist , pleasecheck

请各位大牛帮忙看下是什么问题？

**Comment by liuyanjunleo** [comment]
@agapple     欢迎大神指点~

**Comment by kayleyang** [comment]
@liuyanjunleo 这个问题解决了吗
