### ISSUE TITLE
 batchId:73 is not the firstly:72

### ISSUE THREAD

**Issue by mennyzfy** [alibaba/canal#625]
2018-05-06 10:26:53.805 [destination = example , address = /127.0.0.1:3306 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - prepare to find start position just last position
 {"identity":{"slaveId":-1,"sourceAddress":{"address":"localhost","port":3306}},"postion":{"included":false,"journalName":"mysql-bin.000002","position":26359074,"serverId":1,"timestamp":1525570849000}}
2018-05-06 10:26:53.845 [destination = example , address = /127.0.0.1:3306 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - find start position : EntryPosition[included=false,journalName=mysql-bin.000002,position=26359074,serverId=1,timestamp=
1525570849000]
2018-05-06 10:29:45.154 [New I/O server worker #1-1] ERROR com.alibaba.otter.canal.server.netty.NettyUtils - ErrotCode:400 , Caused by : 
something goes wrong with channel:[id: 0x61b78711, /192.168.0.111:60228 => /192.168.0.111:11111], exception=com.alibaba.otter.canal.meta.exception.CanalMetaManagerException: batchId:72 is not the firstly:71

2018-05-06 10:29:45.171 [New I/O server worker #1-1] ERROR c.a.otter.canal.server.netty.handler.SessionHandler - something goes wrong with channel:[id: 0x61b78711, /192.168.0.111:60228 :> /192.168.0.111:11111], exception=java.nio.channels.ClosedChannelException
	at org.jboss.netty.channel.socket.nio.NioWorker.cleanUpWriteBuffer(NioWorker.java:649)
	at org.jboss.netty.channel.socket.nio.NioWorker.writeFromUserCode(NioWorker.java:370)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleAcceptedSocket(NioServerSocketPipelineSink.java:137)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:76)
	at org.jboss.netty.channel.Channels.write(Channels.java:611)
	at org.jboss.netty.channel.Channels.write(Channels.java:578)
	at com.alibaba.otter.canal.server.netty.NettyUtils.write(NettyUtils.java:28)
	at com.alibaba.otter.canal.server.netty.handler.SessionHandler.messageReceived(SessionHandler.java:144)
	at org.jboss.netty.handler.timeout.IdleStateAwareChannelHandler.handleUpstream(IdleStateAwareChannelHandler.java:48)
	at org.jboss.netty.handler.timeout.IdleStateHandler.messageReceived(IdleStateHandler.java:276)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:302)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.unfoldAndfireMessageReceived(ReplayingDecoder.java:526)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:507)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.cleanup(ReplayingDecoder.java:542)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.channelDisconnected(ReplayingDecoder.java:450)
	at org.jboss.netty.channel.Channels.fireChannelDisconnected(Channels.java:360)
	at org.jboss.netty.channel.socket.nio.NioWorker.close(NioWorker.java:599)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleAcceptedSocket(NioServerSocketPipelineSink.java:119)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:76)
	at org.jboss.netty.channel.Channels.close(Channels.java:720)
	at org.jboss.netty.channel.AbstractChannel.close(AbstractChannel.java:208)
	at org.jboss.netty.channel.ChannelFutureListener$1.operationComplete(ChannelFutureListener.java:46)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:381)
	at org.jboss.netty.channel.DefaultChannelFuture.addListener(DefaultChannelFuture.java:148)
	at com.alibaba.otter.canal.server.netty.NettyUtils.write(NettyUtils.java:30)
	at com.alibaba.otter.canal.server.netty.NettyUtils.error(NettyUtils.java:51)
	at com.alibaba.otter.canal.server.netty.handler.SessionHandler.messageReceived(SessionHandler.java:200)
	at org.jboss.netty.handler.timeout.IdleStateAwareChannelHandler.handleUpstream(IdleStateAwareChannelHandler.java:48)
	at org.jboss.netty.handler.timeout.IdleStateHandler.messageReceived(IdleStateHandler.java:276)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:302)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.unfoldAndfireMessageReceived(ReplayingDecoder.java:526)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:507)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:444)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:274)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:261)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:350)
	at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:281)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:201)
	at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by agapple** [comment]
没有顺序ack

**Comment by zwangbo** [comment]
@mennyzfy 调用getWithoutAck获取Message的时候会生成一个递增的batchId并赋值到Message的id字段。在ack的时候需要客户端保证按照获取Message的顺序来ack确认消息。

**Comment by mennyzfy** [comment]
@zwangbo 我是按照这个demo来运行的，下面是代码：
while (running) {
            try {
                MDC.put("destination", destination);
                connector.connect();
                connector.subscribe("");
                while (running) {
                    Message message = connector.getWithoutAck(batchSize); // 获取指定数量的数据
                    long batchId = message.getId();
                    int size = message.getEntries().size();
                    if (batchId == -1 || size == 0) {
                        try {
                            Thread.sleep(1000);
                        } catch (InterruptedException e) {
                        }
                    } else {
                            resolveEntry(message.getEntries());
                    }
                    connector.ack(batchId); // 提交确认
                }
            } catch (Exception e) {
                logger.error("process error!", e);
            } finally {
                connector.disconnect();
                MDC.remove("destination");
            }
        }
也是消息被消费后才确认的，而且是单线程，为什么顺序还会不一样？

**Comment by cjj137783** [comment]
@agapple  虽然，确实是由于没有顺序确认ack引起的，但是，这无形中就让我的吞吐量和tps下降了不少，我这边是通过开多线程处理的，现在只能单线程处理

**Comment by zwangbo** [comment]
@cjj137783 这一块可以考虑自己走异步处理然后做一个buffer来控制ack顺序以及ack不丢。虽然我觉得这个功能实现在canal这一边也是不错的。

**Comment by agapple** [comment]
otter的做法就是做了一个异步buffer，来顺序ack batchId

**Comment by huwenlong1023** [comment]
@mennyzfy 怎么解决的问题啊

**Comment by huwenlong1023** [comment]
为啥会漏掉一个branchID

**Comment by agapple** [comment]
参考FAQ :  https://github.com/alibaba/canal/wiki/FAQ

**Comment by fangcg** [comment]
> 问5： 出现batchId:73 is not the firstly:72 或 clientId:1001 batchId:50560 is not exist , please check
> 
> 答5：
> 
> 第一个原因是client在ack的问题，前两个异常是client没有按照顺序ack对应的batchId
> 最后一个是ack的batchId在服务端被清理了ps. 服务端发生清理只有两个原因：
> client发起过一次rollback
> server端发生过一次instance的重启，比如scan=true时发现文件变化自动restart了
> 

```shell
2019-03-11 17:30:59.443 [pool-3-thread-1] ERROR com.alibaba.otter.canal.server.CanalMQStarter - batchId:4 is not the firstly:3
com.alibaba.otter.canal.meta.exception.CanalMetaManagerException: batchId:4 is not the firstly:3
2019-03-11 17:30:59.443 [pool-3-thread-1] ERROR com.alibaba.otter.canal.server.CanalMQStarter - batchId:4 is not the firstly:3
com.alibaba.otter.canal.meta.exception.CanalMetaManagerException: batchId:4 is not the firstly:3
2019-03-11 17:31:03.150 [pool-3-thread-1] ERROR com.alibaba.otter.canal.server.CanalMQStarter - batchId:5 is not the firstly:3
com.alibaba.otter.canal.meta.exception.CanalMetaManagerException: batchId:5 is not the firstly:3
2019-03-11 17:31:03.150 [pool-3-thread-1] ERROR com.alibaba.otter.canal.server.CanalMQStarter - batchId:5 is not the firstly:3
com.alibaba.otter.canal.meta.exception.CanalMetaManagerException: batchId:5 is not the firstly:3
2019-03-11 17:31:06.558 [pool-3-thread-1] ERROR com.alibaba.otter.canal.server.CanalMQStarter - batchId:7 is not the firstly:3
com.alibaba.otter.canal.meta.exception.CanalMetaManagerException: batchId:7 is not the firstly:3
2019-03-11 17:31:06.558 [pool-3-thread-1] ERROR com.alibaba.otter.canal.server.CanalMQStarter - batchId:7 is not the firstly:3
com.alibaba.otter.canal.meta.exception.CanalMetaManagerException: batchId:7 is not the firstly:3
```

只说了原因，解决方法是什么？

**Comment by agapple** [comment]
尝试一下1.1.3最新版，1.1.x的早期版本存在漏ack的情况

**Comment by suzawalee** [comment]
> 尝试一下1.1.3最新版，1.1.x的早期版本存在漏ack的情况

1:没有rollback
2:scan=false
cannal:1.1.3 mysql:5.8 环境win10，服务端和客户端都在本机运行，当运行多个client时，依然报 batchid is not the firstly.

**Comment by agapple** [comment]
多个client需要使用cluster模式才行，否则两个client分别做了get操作，但对应的ack顺序又不一致就会报错了

**Comment by Xlinlin** [comment]
删除mete.data，重启就好了。我们这个场景还只是做来缓存的，要是数据强一致这法子不好解决

**Comment by lbx6z** [comment]
我的是canal 1.1.3, mysql5.7.21，运行单个client也会报batchid is not the firstly.
重启了server，一开始batchid都正常地增长，后来突然就开始报错。请问是否和batch has 0 row to send有关呢？
<img width="1440" alt="屏幕快照 2019-07-31 下午4 53 18 1" src="https://user-images.githubusercontent.com/6837297/62198430-2eabb180-b3b4-11e9-84b6-7d5367580b1e.png">

**Comment by lbx6z** [comment]
可以复现。下面是挂在batch 87的例子。
`
2019-07-31 17:08:48,461 DEBUG messageId is 85 batchId is 85 size is 45
2019-07-31 17:08:48,465 DEBUG batch 85 has 28 rows to send
2019-07-31 17:08:49,467 DEBUG messageId is 86 batchId is 86 size is 12
2019-07-31 17:08:49,468 DEBUG batch 86 has 4 rows to send
2019-07-31 17:08:50,469 DEBUG messageId is 87 batchId is 87 size is 2
2019-07-31 17:08:50,469 DEBUG batch 87 has 0 rows to send
2019-07-31 17:08:51,471 DEBUG messageId is 88 batchId is 88 size is 49
2019-07-31 17:08:51,476 DEBUG batch 88 has 19 rows to send
2019-07-31 17:08:52,479 DEBUG messageId is 89 batchId is 89 size is 45
2019-07-31 17:08:52,482 DEBUG batch 89 has 22 rows to send
2019-07-31 17:08:52,492 ERROR cannot get message from canal-server
com.alibaba.otter.canal.protocol.exception.CanalClientException: deserializer failed
	at com.alibaba.otter.canal.client.CanalMessageDeserializer.deserializer(CanalMessageDeserializer.java:54)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.receiveMessages(SimpleCanalConnector.java:322)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.getWithoutAck(SimpleCanalConnector.java:314)
	at com.alibaba.otter.canal.client.Ship.getMessage(Ship.java:120)
	at com.alibaba.otter.canal.client.KafkaRunnable.doLoop(KafkaRunnable.java:140)
	at com.alibaba.otter.canal.client.KafkaRunnable.run(KafkaRunnable.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.alibaba.otter.canal.protocol.exception.CanalClientException: something goes wrong with reason: something goes wrong with channel:[id: 0x0ce3b613, /10.0.2.137:55412 => /10.0.2.137:32121], exception=com.alibaba.otter.canal.meta.exception.CanalMetaManagerException: batchId:88 is not the firstly:87

	at com.alibaba.otter.canal.client.CanalMessageDeserializer.deserializer(CanalMessageDeserializer.java:46)
	... 8 more
2019-07-31 17:08:53,489 DEBUG messageId is 90 batchId is 90 size is 30
2019-07-31 17:08:53,491 DEBUG batch 90 has 10 rows to send
`

**Comment by DyzYpp** [comment]
怎么解决呢 很多都只说了原因 ack顺序问题,具体怎么解决呢

**Comment by swatchion** [comment]
> 删除mete.data，重启就好了。我们这个场景还只是做来缓存的，要是数据强一致这法子不好解决

+1
