### ISSUE TITLE
canal1.0.22 启动问题

### ISSUE THREAD

**Issue by caizhangxian** [alibaba/canal#637]
2018-05-11 00:00:24.243 [destination = yuntu-management , address = rm-wz91b2j3ypnw1fbr6o.mysql.rds.aliyuncs.com/112.74.151.78:3306 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - disconnect address rm-wz91b2j3ypnw1fbr6o.mysql.rds.aliyuncs.com/112.74.151.78:3306 has an error, retrying., caused by 
java.io.IOException: KILL DUMP 470730777 failure:java.io.IOException: ErrorPacket [errorNumber=1094, fieldCount=-1, message=Unknown thread id: 470730777, sqlState=HY000, sqlStateMarker=#]
 with command: KILL CONNECTION 470730777
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlUpdateExecutor.update(MysqlUpdateExecutor.java:49)
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.disconnect(MysqlConnector.java:104)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.disconnect(MysqlConnection.java:60)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:242)
	at java.lang.Thread.run(Thread.java:745)

**Comment by agapple** [comment]
尝试用一下最新的1.0.26版本
