### ISSUE TITLE
parser  information_schema中的表出错

### ISSUE THREAD

**Issue by tyu567567** [alibaba/canal#652]
2018-05-22 15:12:39.374 [destination = example , address = zhenghongchen.cn/60.205.220.19:3306 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta - parse faield : CREATE TEMPORARY TABLE `SYSTEM_VARIABLES` (
  `VARIABLE_NAME` varchar(64) NOT NULL DEFAULT '',
  `SESSION_VALUE` varchar(2048) DEFAULT NULL,
  `GLOBAL_VALUE` varchar(2048) DEFAULT NULL,
  `GLOBAL_VALUE_ORIGIN` varchar(64) NOT NULL DEFAULT '',
  `DEFAULT_VALUE` varchar(2048) DEFAULT NULL,
  `VARIABLE_SCOPE` varchar(64) NOT NULL DEFAULT '',
  `VARIABLE_TYPE` varchar(64) NOT NULL DEFAULT '',
  `VARIABLE_COMMENT` varchar(2048) NOT NULL DEFAULT '',
  `NUMERIC_MIN_VALUE` varchar(21) DEFAULT NULL,
  `NUMERIC_MAX_VALUE` varchar(21) DEFAULT NULL,
  `NUMERIC_BLOCK_SIZE` varchar(21) DEFAULT NULL,
  `ENUM_VALUE_LIST` longtext DEFAULT NULL,
  `READ_ONLY` varchar(3) NOT NULL DEFAULT '',
  `COMMAND_LINE_ARGUMENT` varchar(64) DEFAULT NULL
) ENGINE=Aria DEFAULT CHARSET=utf8 PAGE_CHECKSUM=0

com.alibaba.fastsql.sql.parser.ParserException: syntax error, error in :'utf8 PAGE_CHECKSUM=0', expect IDENTIFIER, actual IDENTIFIER pos 781, line 16, column 50, token IDENTIFIER PAGE_CHECKSUM
	at com.alibaba.fastsql.sql.parser.SQLParser.printError(SQLParser.java:305) ~[fastsql-2.0.0_preview_186.jar:2.0.0_preview_186]
	at com.alibaba.fastsql.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:427) ~[fastsql-2.0.0_preview_186.jar:2.0.0_preview_186]
	at com.alibaba.fastsql.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:76) ~[fastsql-2.0.0_preview_186.jar:2.0.0_preview_186]
	at com.alibaba.fastsql.sql.SQLUtils.parseStatements(SQLUtils.java:469) ~[fastsql-2.0.0_preview_186.jar:2.0.0_preview_186]
	at com.alibaba.fastsql.sql.repository.SchemaRepository.console(SchemaRepository.java:331) ~[fastsql-2.0.0_preview_186.jar:2.0.0_preview_186]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta.apply(MemoryTableMeta.java:71) ~[classes/:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.dumpTableMeta(DatabaseTableMeta.java:177) [classes/:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:127) [classes/:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:84) [classes/:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:173) [classes/:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]

**Comment by tyu567567** [comment]
找到原因是，fastsql-2.0.0_preview_186.jar对MariaDB的aria引擎的表支持的不好

版本1.0.26-SNAPSHOT
