### ISSUE TITLE
SimpleCanalClientTest 连Canal 一直报NullPointerException 错误

### ISSUE THREAD

**Issue by wantaoli** [alibaba/canal#655]
按照QuickStart 和 ClientSample 搭建了Canal 环境，但跑SimpleCanalClientTest 一直报一个NullPointerException 错误，反复对照检查了配置端口等，的确没发现什么问题，望能给点建议排查错误，具体错误信息如下：

2018-05-26 19:53:29.679 [Thread-1] ERROR com.alibaba.otter.canal.example.AbstractCanalClientTest - process error!
java.lang.NullPointerException: null
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.writeWithHeader(SimpleCanalConnector.java:392) ~[classes/:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.writeWithHeader(SimpleCanalConnector.java:380) ~[classes/:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.getWithoutAck(SimpleCanalConnector.java:292) ~[classes/:na]
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.getWithoutAck(SimpleCanalConnector.java:280) ~[classes/:na]
	at com.alibaba.otter.canal.example.AbstractCanalClientTest.process(AbstractCanalClientTest.java:125) ~[classes/:na]

**Comment by wantaoli** [comment]
问题找到了，是本地1.26 snapshot 版本的源代码没有build成功导致的，换成1.25 成功build 后，问题消失
