### ISSUE TITLE
1.0.26  com.alibaba.fastsql.sql.parser.ParserException: TODO pos 545, line 9, column 83, token NULL

### ISSUE THREAD

**Issue by wusthuke** [alibaba/canal#663]
durid 已经手动升级为：1.1.9， 启动还是报错：
`
2018-05-29 17:29:36.484 [destination = devmysql4308 , address = /192.168.100.4:3308 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta - parse faield : /* ApplicationName=IntelliJ IDEA 2017.2.5 */ CREATE TABLE best_sign_cont_task
(
  id INTEGER PRIMARY KEY NOT NULL COMMENT '主键' AUTO_INCREMENT,
  docid VARCHAR(50) NOT NULL DEFAULT '' COMMENT '合同原件的上上签id',
  pdfid VARCHAR(50) NOT NULL DEFAULT '' COMMENT '合同pdf的上上签id',
  contract_id VARCHAR(50) NOT NULL DEFAULT '' COMMENT '上上签合同id',
  finish TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0甲方未签署 1甲方已签署,表示任务完成',
  remark VARCHAR(100) NOT NULL DEFAULT '' COMMENT '备注',
  sys_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE  CURRENT_TIMESTAMP  NOT NULL COMMENT '系统时间'
)ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT '上上签合同创建任务记录'
com.alibaba.fastsql.sql.parser.ParserException: TODO pos 545, line 9, column 83, token NULL
        at com.alibaba.fastsql.sql.parser.SQLExprParser.notRationalRest(SQLExprParser.java:2557) ~[fastsql-2.0.0_preview_186.jar:2.0.0_preview_186]
        at com.alibaba.fastsql.sql.parser.SQLExprParser.relationalRest(SQLExprParser.java:2323) ~[fastsql-2.0.0_preview_186.jar:2.0.0_preview_186]
        at com.alibaba.fastsql.sql.parser.SQLExprParser.exprRest(SQLExprParser.java:109) ~[fastsql-2.0.0_preview_186.jar:2.0.0_preview_186]
        at com.alibaba.fastsql.sql.parser.SQLExprParser.expr(SQLExprParser.java:97) ~[fastsql-2.0.0_preview_186.jar:2.0.0_preview_186]
        at com.alibaba.fastsql.sql.dialect.mysql.parser.MySqlExprParser.parseColumnRest(MySqlExprParser.java:462) ~[fastsql-2.0.0_preview_186.jar:2.0.0_preview_186]
        at com.alibaba.fastsql.sql.parser.SQLExprParser.parseColumnRest(SQLExprParser.java:2801) ~[fastsql-2.0.0_preview_186.jar:2.0.0_preview_186]
        at com.alibaba.fastsql.sql.dialect.mysql.parser.MySqlExprParser.parseColumnRest(MySqlExprParser.java:545) ~[fastsql-2.0.0_preview_186.jar:2.0.0_preview_186]
        at com.alibaba.fastsql.sql.dialect.mysql.parser.MySqlExprParser.parseColumn(MySqlExprParser.java:455) ~[fastsql-2.0.0_preview_186.jar:2.0.0_preview_186]
        at com.alibaba.fastsql.sql.dialect.mysql.parser.MySqlCreateTableParser.parseCreateTable(MySqlCreateTableParser.java:170) ~[fastsql-2.0.0_preview_186.jar:2.0.0_preview_186]
        at com.alibaba.fastsql.sql.dialect.mysql.parser.MySqlStatementParser.parseCreate(MySqlStatementParser.java:239) ~[fastsql-2.0.0_preview_186.jar:2.0.0_preview_186]
        at com.alibaba.fastsql.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:165) ~[fastsql-2.0.0_preview_186.jar:2.0.0_preview_186]
        at com.alibaba.fastsql.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:76) ~[fastsql-2.0.0_preview_186.jar:2.0.0_preview_186]
        at com.alibaba.fastsql.sql.SQLUtils.parseStatements(SQLUtils.java:469) ~[fastsql-2.0.0_preview_186.jar:2.0.0_preview_186]
        at com.alibaba.fastsql.sql.repository.SchemaRepository.console(SchemaRepository.java:331) ~[fastsql-2.0.0_preview_186.jar:2.0.0_preview_186]
        at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta.apply(MemoryTableMeta.java:71) ~[canal.parse-1.0.26-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.applyHistoryOnMemory(DatabaseTableMeta.java:382) [canal.parse-1.0.26-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:121) [canal.parse-1.0.26-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:72) [canal.parse-1.0.26-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:170) [canal.parse-1.0.26-SNAPSHOT.jar:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
`

**Comment by wusthuke** [comment]
我手动下载了 fastsql_2.0.0_preview_186，定位到了问题， 问题sql： 
```sql
/* ApplicationName=DataGrip 2017.2.2 */ CREATE TABLE corp_best_sign_info
(
    id BIGINT PRIMARY KEY NOT NULL COMMENT '主键' AUTO_INCREMENT,
    best_sign_account VARCHAR(50) DEFAULT 0 NOT NULL COMMENT '上上签唯一标识',
    corp_id BIGINT DEFAULT 0 NOT NULL COMMENT '公司ID',
    corp_name VARCHAR(50) DEFAULT '' NOT NULL COMMENT '公司名称',
    biz_license_no VARCHAR(50) DEFAULT '' NOT NULL COMMENT '公司信用代码',
    authorization_name VARCHAR(50) DEFAULT '' NOT NULL COMMENT '授权人姓名',
    authorization_card VARCHAR(50) DEFAULT '' NOT NULL COMMENT '授权人身份证',
    authorization_phone VARCHAR(50) DEFAULT '' NOT NULL COMMENT '授权人电话',
    biz_license_attachmen_id BIGINT(19) DEFAULT 0 NOT NULL COMMENT '营业执照副本附件',
    identity_attachmen_id BIGINT(19) DEFAULT 0 NOT NULL COMMENT '身份证正面附件',
    license_authorization_attachmen_id BIGINT(19) DEFAULT 0 NOT NULL COMMENT '企业授权书附件',
    sign_account_status TINYINT(3) DEFAULT 0 NOT NULL COMMENT '是否开通电子签 0-未开通 1-开通中 2-已开通',
    audit_status TINYINT(3) DEFAULT 0 NOT NULL COMMENT '审核状态 1待提交、2审核中、3通过、4拒绝',
    audit_time TIMESTAMP DEFAULT '2000-01-01 00:00:00' NOT NULL COMMENT '审核通过时间',
    create_time TIMESTAMP DEFAULT '2000-01-01 00:00:00' NOT NULL COMMENT '创建时间',
    create_usertoken VARCHAR(50) DEFAULT '' NOT NULL COMMENT '添加人uk',
    create_username VARCHAR(20) DEFAULT '' NOT NULL COMMENT '添加人姓名',
    update_time TIMESTAMP DEFAULT '2000-01-01 00:00:00' NOT NULL COMMENT '变更时间',
    update_usertoken VARCHAR(50) DEFAULT '' NOT NULL COMMENT '修改人uk',
    update_username VARCHAR(20) DEFAULT '' NOT NULL COMMENT '修改人姓名',
    is_deleted TINYINT DEFAULT 0 NOT NULL COMMENT '是否删除0-未删除，1-已删除',
    sys_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE  CURRENT_TIMESTAMP  NOT NULL COMMENT '系统时间'
)ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT '企业开通上上签信息表'
```
调整后通过的sql: 
```sql
 /* ApplicationName=DataGrip 2017.2.2 */ CREATE TABLE corp_best_sign_info
(
    id BIGINT PRIMARY KEY NOT NULL COMMENT '主键' AUTO_INCREMENT,
    best_sign_account VARCHAR(50) DEFAULT 0 NOT NULL COMMENT '上上签唯一标识',
    corp_id BIGINT DEFAULT 0 NOT NULL COMMENT '公司ID',
    corp_name VARCHAR(50) DEFAULT '' NOT NULL COMMENT '公司名称',
    biz_license_no VARCHAR(50) DEFAULT '' NOT NULL COMMENT '公司信用代码',
    authorization_name VARCHAR(50) DEFAULT '' NOT NULL COMMENT '授权人姓名',
    authorization_card VARCHAR(50) DEFAULT '' NOT NULL COMMENT '授权人身份证',
    authorization_phone VARCHAR(50) DEFAULT '' NOT NULL COMMENT '授权人电话',
    biz_license_attachmen_id BIGINT(19) DEFAULT 0 NOT NULL COMMENT '营业执照副本附件',
    identity_attachmen_id BIGINT(19) DEFAULT 0 NOT NULL COMMENT '身份证正面附件',
    license_authorization_attachmen_id BIGINT(19) DEFAULT 0 NOT NULL COMMENT '企业授权书附件',
    sign_account_status TINYINT(3) DEFAULT 0 NOT NULL COMMENT '是否开通电子签 0-未开通 1-开通中 2-已开通',
    audit_status TINYINT(3) DEFAULT 0 NOT NULL COMMENT '审核状态 1待提交、2审核中、3通过、4拒绝',
    audit_time TIMESTAMP DEFAULT '2000-01-01 00:00:00' NOT NULL COMMENT '审核通过时间',
    create_time TIMESTAMP DEFAULT '2000-01-01 00:00:00' NOT NULL COMMENT '创建时间',
    create_usertoken VARCHAR(50) DEFAULT '' NOT NULL COMMENT '添加人uk',
    create_username VARCHAR(20) DEFAULT '' NOT NULL COMMENT '添加人姓名',
    update_time TIMESTAMP DEFAULT '2000-01-01 00:00:00' NOT NULL COMMENT '变更时间',
    update_usertoken VARCHAR(50) DEFAULT '' NOT NULL COMMENT '修改人uk',
    update_username VARCHAR(20) DEFAULT '' NOT NULL COMMENT '修改人姓名',
    is_deleted TINYINT DEFAULT 0 NOT NULL COMMENT '是否删除0-未删除，1-已删除',
    sys_time TIMESTAMP not null DEFAULT CURRENT_TIMESTAMP ON UPDATE  CURRENT_TIMESTAMP  COMMENT '系统时间'
)ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT '企业开通上上签信息表'
```

**Comment by agapple** [comment]
的确是存在问题
