### ISSUE TITLE
canal v1.0.25版本报错java.nio.channels.ClosedByInterruptException: null

### ISSUE THREAD

**Issue by kervin521** [alibaba/canal#671]
2018-06-05 00:50:56.419 [destination = example , address = testrds1.amazonaws.com/10.8.3.18:3306 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - dump address testrds1.corlbeqxlnts.us-west-2.rds.amazonaws.com/10.8.3.180:3306 has an error, retrying. caused by 
java.nio.channels.ClosedByInterruptException: null
	at com.alibaba.otter.canal.parse.driver.mysql.socket.SocketChannel.read(SocketChannel.java:49) ~[canal.parse.driver-1.0.25.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:151) ~[canal.parse-1.0.25.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:77) ~[canal.parse-1.0.25.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:137) ~[canal.parse-1.0.25.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:220) ~[canal.parse-1.0.25.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]
2018-06-05 00:50:56.425 [destination = example , address = testrds1.amazonaws.com/10.8.3.18:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[java.nio.channels.ClosedByInterruptException
	at com.alibaba.otter.canal.parse.driver.mysql.socket.SocketChannel.read(SocketChannel.java:49)
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:151)
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:77)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:137)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:220)
	at java.lang.Thread.run(Thread.java:748)
]

**Comment by DevWithLin** [comment]
试试 26版本的

**Comment by DevWithLin** [comment]
看下[Issue604](https://github.com/alibaba/canal/issues/640)。
