### ISSUE TITLE
java集群链接的时候报错了

### ISSUE THREAD

**Issue by fenggaopan** [alibaba/canal#691]
com.alibaba.otter.canal.protocol.exception.CanalClientException: java.io.IOException: end of stream when reading header
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.getWithoutAck(SimpleCanalConnector.java:277)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.getWithoutAck(SimpleCanalConnector.java:248)
	at com.alibaba.otter.canal.client.impl.ClusterCanalConnector.getWithoutAck(ClusterCanalConnector.java:174)
	at com.dangdang.canal.DDPimJob.run(DDPimJob.java:55)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: end of stream when reading header
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.read(SimpleCanalConnector.java:374)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.readNextPacket(SimpleCanalConnector.java:365)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.receiveMessages(SimpleCanalConnector.java:282)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.getWithoutAck(SimpleCanalConnector.java:275)

**Comment by DevWithLin** [comment]
你还是报一下版本号吧，我觉得应该加个模板的。。。。不然各式各样的问题。。。。

**Comment by DevWithLin** [comment]
看你的样子使用的是25版本的
