### ISSUE TITLE
mysql5.7.22 canal 提示  java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not open log file

### ISSUE THREAD

**Issue by programTang** [alibaba/canal#705]
2018-06-20 12:02:29.240 [destination = dev , address = /192.168.255.2:3306 , EventParser] INFO  c.a.otter.canal.parse.inbound.mysql.MysqlConnection - COM_BINLOG_DUMP with position:BinlogDumpCommandPacket[binlogPosition=309144234,slaveServerId=1201,binlogFileName=mysql-bin.000333,command=18]
2018-06-20 12:02:29.244 [destination = dev , address = /192.168.255.2:3306 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - I/O error while reading from client socket
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not open log file
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:95) ~[canal.parse-1.0.25-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:122) [canal.parse-1.0.25-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209) [canal.parse-1.0.25-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
2018-06-20 12:02:29.244 [destination = dev , address = /192.168.255.2:3306 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - dump address /192.168.255.2:3306 has an error, retrying. caused by
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not open log file
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:95) ~[canal.parse-1.0.25-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:122) ~[canal.parse-1.0.25-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209) ~[canal.parse-1.0.25-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
2018-06-20 12:02:29.244 [destination = dev , address = /192.168.255.2:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:dev[java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not open log file
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:95)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:122)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209)
	at java.lang.Thread.run(Thread.java:748)
]
2018-06-20 12:02:29.244 [destination = dev , address = /192.168.255.2:3306 , EventParser] INFO  c.alibaba.otter.canal.parse.driver.mysql.MysqlConnector - disConnect MysqlConnection to /192.168.255.2:3306...

**Comment by agapple** [comment]
Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not open log file
检查一下binlog文件和位点的有效性

**Comment by linqh1** [comment]
我也碰到这个问题了，查询了下当时出问题的log和position，没发现什么奇怪的地方啊？
![image](https://user-images.githubusercontent.com/42435177/72229426-741e0d00-35e9-11ea-9ed0-8b52c525f01a.png)
后面我把位点信息改成下一个位点的就可以了（如上图mysql-bin.000356;pos=4）

是不是canal解析的时候没有考虑到某种情况？
mysql 版本：5.6.41-log
