### ISSUE TITLE
canal启动正常 canal客户端订阅卡住

### ISSUE THREAD

**Issue by waaayane** [alibaba/canal#707]
错误日志：2018-06-20 13:43:46.730 [ZkClient-EventThread-26-vm153:2181,vm154:2181,vm155:2181] ERROR org.I0Itec.zkclient.ZkEventThread - Error handling event ZkEvent[Data of /otter/canal/destinations/yuantong_order_mysql_10.1.240.87_3307_0/1001/running changed sent to com.alibaba.otter.canal.client.impl.running.ClientRunningMonitor$1@4e7d0621]
com.alibaba.otter.canal.protocol.exception.CanalClientException: something goes wrong in initRunning method. 
	at com.alibaba.otter.canal.client.impl.running.ClientRunningMonitor.initRunning(ClientRunningMonitor.java:142)
	at com.alibaba.otter.canal.client.impl.running.ClientRunningMonitor$1.handleDataDeleted(ClientRunningMonitor.java:71)
	at org.I0Itec.zkclient.ZkClient$6.run(ZkClient.java:549)
	at org.I0Itec.zkclient.ZkEventThread.run(ZkEventThread.java:71)
Caused by: com.alibaba.otter.canal.protocol.exception.CanalClientException: java.net.ConnectException: 拒绝连接
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:171)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.access$000(SimpleCanalConnector.java:48)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector$1.processActiveEnter(SimpleCanalConnector.java:396)
	at com.alibaba.otter.canal.client.impl.running.ClientRunningMonitor.processActiveEnter(ClientRunningMonitor.java:207)
	at com.alibaba.otter.canal.client.impl.running.ClientRunningMonitor.initRunning(ClientRunningMonitor.java:118)
	... 3 common frames omitted
Caused by: java.net.ConnectException: 拒绝连接
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:454)
	at sun.nio.ch.Net.connect(Net.java:446)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.doConnect(SimpleCanalConnector.java:132)
	... 7 common frames omitted

有时候就会一直卡在这个错误上，需要重启才正常，
但有时候这个错误会出现，但最后能订阅成功，不需要重启，canal的版本是24的

**Comment by wbsch52** [comment]
我有时候也会出现这个问题, 请问你解决了吗?

**Comment by agapple** [comment]
尝试一下最新的v1.1.1
