### ISSUE TITLE
java.io.IOException: connect /xxx:3306 failure:java.io.IOException: Unexpected End

### ISSUE THREAD

**Issue by zhoushuoqi22** [alibaba/canal#710]
启动canal服务就报这个错，canal版本1.0.22
2018-06-19 11:26:44.358 [destination = example , address = /xxx:3306 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser -
 dump address /xxx:3306 has an error, retrying. caused by 
com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: connect /xxx:3306 failure:java.io.IOException: Unexpected End Stream
	at com.alibaba.otter.canal.parse.driver.mysql.utils.PacketManager.readBytesAsBuffer(PacketManager.java:22)
	at com.alibaba.otter.canal.parse.driver.mysql.utils.PacketManager.readHeader(PacketManager.java:13)
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.negotiate(MysqlConnector.java:199)
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:71)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.connect(MysqlConnection.java:52)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.preDump(MysqlEventParser.java:85)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:158)
	at java.lang.Thread.run(Thread.java:745)

Caused by: java.io.IOException: connect /xxx:3306 failure:java.io.IOException: Unexpected End Stream
	at com.alibaba.otter.canal.parse.driver.mysql.utils.PacketManager.readBytesAsBuffer(PacketManager.java:22)
	at com.alibaba.otter.canal.parse.driver.mysql.utils.PacketManager.readHeader(PacketManager.java:13)
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.negotiate(MysqlConnector.java:199)
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:71)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.connect(MysqlConnection.java:52)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.preDump(MysqlEventParser.java:85)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:158)
	at java.lang.Thread.run(Thread.java:745)

	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.connect(MysqlConnector.java:74) ~[canal.parse.driver-1.0.22.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.connect(MysqlConnection.java:52) ~[canal.parse-1.0.22.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.preDump(MysqlEventParser.java:85) ~[canal.parse-1.0.22.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:158) ~[canal.parse-1.0.22.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_11]

**Comment by zhoushuoqi22** [comment]
3306端口是通的

**Comment by agapple** [comment]
java.io.IOException: connect /xxx:3306 failure:java.io.IOException: Unexpected End Stream

**Comment by agapple** [comment]
可以试试1.0.26
