### ISSUE TITLE
com.alibaba.fastsql.sql.parser.ParserException

### ISSUE THREAD

**Issue by hyy613** [alibaba/canal#736]
场景：TSDB开启
fastsql版本：371
升级到371版本的fastsql后，目前遇见两种类型exception.

一：
Student-service 2018-07-05 17:10:13.017  WARN ???? [6 , EventParser] c.a.o.c.p.i.m.t.MemoryTableMeta          : [] parse faield : ALTER TABLE `platform`.`notice` 
CHANGE COLUMN `content` `content` VARCHAR(3000) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT '未填写' COMMENT '默认'

com.alibaba.fastsql.sql.parser.ParserException
	at com.alibaba.fastsql.sql.parser.SQLExprParser.parseCharTypeRest(SQLExprParser.java:2910) ~[Student-service.jar!/:?]
	at com.alibaba.fastsql.sql.parser.SQLExprParser.parseDataType(SQLExprParser.java:2785) ~[Student-service.jar!/:?]
	at com.alibaba.fastsql.sql.parser.SQLExprParser.parseDataType(SQLExprParser.java:2666) ~[Student-service.jar!/:?]
	at com.alibaba.fastsql.sql.dialect.mysql.parser.MySqlExprParser.parseColumn(MySqlExprParser.java:463) ~[Student-service.jar!/:?]
	at com.alibaba.fastsql.sql.dialect.mysql.parser.MySqlStatementParser.parseAlterTable(MySqlStatementParser.java:4315) ~[Student-service.jar!/:?]
	at com.alibaba.fastsql.sql.dialect.mysql.parser.MySqlStatementParser.parseAlter(MySqlStatementParser.java:3307) ~[Student-service.jar!/:?]
	at com.alibaba.fastsql.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:248) ~[Student-service.jar!/:?]
	at com.alibaba.fastsql.sql.SQLUtils.parseStatements(SQLUtils.java:500) ~[Student-service.jar!/:?]
	at com.alibaba.fastsql.sql.repository.SchemaRepository.console(SchemaRepository.java:412) ~[Student-service.jar!/:?]
	
二：
Student-service 2018-07-05 17:32:42.210  WARN ???? [6 , EventParser] c.a.o.c.p.i.m.t.MemoryTableMeta          : [] parse faield : ALTER TABLE `student`
DROP COLUMN `display_name`,
DROP COLUMN `system`,
MODIFY COLUMN `id`  bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT FIRST ,
CHANGE COLUMN `name` `student_name`  varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '' COMMENT '学生名' AFTER `id`,
MODIFY COLUMN `description`  varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '' COMMENT '学校描述' AFTER `student_name`,
MODIFY COLUMN `created_at`  timestamp NOT NULL AFTER `description`,
MODIFY COLUMN `updated_at`  timestamp NOT NULL AFTER `created_at`,
CHANGE COLUMN `creator` `created_by`  varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL AFTER `updated_at`,
CHANGE COLUMN `updated_name` `updated_by`  varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL AFTER `created_by`,
ADD COLUMN `is_deleted`  tinyint(1) NOT NULL DEFAULT 0 COMMENT '删除标记，0，未删除，1，删除' AFTER `description`

com.alibaba.fastsql.sql.parser.ParserException: syntax error, error in :'MODIFY COLUMN `id`  bigint(20) UNSIGN, pos 86, line 4, column 9, token COLUMN
	at com.alibaba.fastsql.sql.parser.SQLParser.printError(SQLParser.java:361) ~[Student-service.jar!/:?]
	at com.alibaba.fastsql.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:498) ~[Student-service.jar!/:?]
	at com.alibaba.fastsql.sql.SQLUtils.parseStatements(SQLUtils.java:500) ~[Student-service.jar!/:?]
	at com.alibaba.fastsql.sql.repository.SchemaRepository.console(SchemaRepository.java:412) ~[Student-service.jar!/:?]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.MemoryTableMeta.apply(MemoryTableMeta.java:72) [Student-service.jar!/:?]
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.apply(DatabaseTableMeta.java:104) [Student-service.jar!/:?]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.TableMetaCache.apply(TableMetaCache.java:228) [Student-service.jar!/:?]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parseQueryEvent(LogEventConvert.java:265) [Student-service.jar!/:?]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.LogEventConvert.parse(LogEventConvert.java:126) [Student-service.jar!/:?]

**Comment by agapple** [comment]
你这第二天SQL也够复杂的

**Comment by hyy613** [comment]
第一条的parseCharTypeRest导致的exception比第二条常见~~~麻烦先优先处理第一条那种case吧，多谢多谢

**Comment by hyy613** [comment]
测试发现 Alter Table中有 COLLATE 会导致解析失败。
2.0.0_preview_186版本也存在这个问题。与TSDB无关。

**Comment by agapple** [comment]
这是fastsql对DDL的解析支持的问题, 我会记录和反馈

**Comment by agapple** [comment]
最新的fastsql已经修复

**Comment by hyy613** [comment]
请问最新的sql的版本是 ？
