### ISSUE TITLE
 [v1.0.26.alpha4]parse events has an error错误

### ISSUE THREAD

**Issue by kervin521** [alibaba/canal#773]
![image](https://user-images.githubusercontent.com/9798724/43177235-d82ca3c0-8ff9-11e8-87f1-e43826acb891.png)

2018-07-25 10:52:13.662 [destination = example , address = /127.0.0.1:3306 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - parse events has an error
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@869cc59 rejected from java.util.concurrent.ThreadPoolExecutor@36f77020[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source) ~[na:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source) ~[na:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source) ~[na:1.8.0_152]
	at java.util.concurrent.AbstractExecutorService.submit(Unknown Source) ~[na:1.8.0_152]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor.start(MysqlMultiStageCoprocessor.java:120) ~[canal.parse-1.0.26-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor.reset(MysqlMultiStageCoprocessor.java:187) ~[canal.parse-1.0.26-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:306) ~[canal.parse-1.0.26-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_152]

**Comment by fanpeng1100** [comment]
相同问题啊，解决没

**Comment by kervin521** [comment]
@agapple

**Comment by agapple** [comment]
这不是root cause，找最前面的日志

**Comment by kervin521** [comment]
使用v1.0.25没有问题

**Comment by agapple** [comment]
应该是单核机器的启动失败问题，v1.1.1已修复

**Comment by kervin521** [comment]
@agapple v1.1.1正式版什么时候发布
