### ISSUE TITLE
最新版fastsql-preview 520 ： com.alibaba.fastsql.sql.parser.ParserException

### ISSUE THREAD

**Issue by hyy613** [alibaba/canal#781]
fastsql版本： 最新的520 
sql语句以及Exception：
case 1 : 
sql_6 = "CREATE INDEX `idx_t_uid` on stu_score (`uid`) COMMENT '' ALGORITHM DEFAULT LOCK DEFAULT ";
Exception in thread "main" com.alibaba.fastsql.sql.parser.ParserException: syntax error, error in :'ITHM DEFAULT LOCK DEFAULT, pos 134, line 1, column 136, token IDENTIFIER null
	at com.alibaba.fastsql.sql.parser.SQLParser.printError(SQLParser.java:363)
	at com.alibaba.fastsql.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:520)
	at com.alibaba.fastsql.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:92)
	at com.test.HelloWorld.main(HelloWorld.java:266)

case 2:
sql = "alter table test  COLLATE utf8mb4_unicode_ci" ;
Exception in thread "main" com.alibaba.fastsql.sql.parser.ParserException: syntax error, error in :'LATE utf8mb4_unicode_ci', expect =, actual null, pos 44, line 1, column 27, token IDENTIFIER utf8mb4_unicode_ci
	at com.alibaba.fastsql.sql.parser.SQLParser.printError(SQLParser.java:363)
	at com.alibaba.fastsql.sql.parser.SQLParser.accept(SQLParser.java:371)
	at com.alibaba.fastsql.sql.dialect.mysql.parser.MySqlStatementParser.parseAlterTable(MySqlStatementParser.java:4818)
	at com.alibaba.fastsql.sql.dialect.mysql.parser.MySqlStatementParser.parseAlter(MySqlStatementParser.java:3544)
	at com.alibaba.fastsql.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:264)
	at com.alibaba.fastsql.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:92)
	at com.test.HelloWorld.main(HelloWorld.java:266)

case 3：
sql_8 = "alter table task AUTO_INCREMENT = 20000000 COMMENT ='自增起始值'" ;
Exception in thread "main" com.alibaba.fastsql.sql.parser.ParserException: syntax error, error in :'0000 COMMENT ='自增起始值'', expect ON, actual =, pos 52, line 1, column 52, token =
	at com.alibaba.fastsql.sql.parser.SQLParser.printError(SQLParser.java:363)
	at com.alibaba.fastsql.sql.parser.SQLParser.accept(SQLParser.java:371)
	at com.alibaba.fastsql.sql.parser.SQLStatementParser.parseComment(SQLStatementParser.java:3488)
	at com.alibaba.fastsql.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:354)
	at com.alibaba.fastsql.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:92)
	at com.test.HelloWorld.main(HelloWorld.java:266)

**Comment by agapple** [comment]
这些是有一些问题，已反馈做修改，建议先绕过

alter table test COLLATE = utf8mb4_unicode_ci
alter table task AUTO_INCREMENT = 20000000  , COMMENT ='自增起始值'

**Comment by hyy613** [comment]
再补充一个ddl 
CREATE TABLE `app_info` (`id` bigint(20) NOT NULL, `app_name` varchar(255) NOT NULL ,PRIMARY KEY (`id`),INDEX `idx` USING BTREE (`app_name`) comment '') ;
