### ISSUE TITLE
与guava 20有兼容问题，guava 18 MapMaker.makeComputingMap方法已过时 

### ISSUE THREAD

**Issue by alan5959249** [alibaba/canal#795]
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2018-07-31 18:35:10,269 ERROR org.springframework.boot.SpringApplication [842] [main] - Application run failed
java.lang.NoSuchMethodError: com.google.common.collect.MapMaker.makeComputingMap(Lcom/google/common/base/Function;)Ljava/util/concurrent/ConcurrentMap;
	at com.google.common.collect.MigrateMap.makeComputingMap(MigrateMap.java:17) ~[canal.common-1.0.24.jar:?]
	at com.alibaba.otter.canal.common.zookeeper.ZkClientx.<clinit>(ZkClientx.java:26) ~[canal.common-1.0.24.jar:?]
	at com.alibaba.otter.canal.client.CanalConnectors.newClusterConnector(CanalConnectors.java:66) ~[canal.client-1.0.24.jar:?]
	at com.star.profile.canal.service.impl.CanalServiceImpl.canalServiceRunner(CanalServiceImpl.java:32) ~[bin/:?]
	at com.star.profile.canal.CanalClientAppliationRunner.run(CanalClientAppliationRunner.java:23) ~[bin/:?]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:788) [spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:778) [spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:335) [spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at com.star.profile.ProfileApplication.main(ProfileApplication.java:18) [bin/:?]

之前有同学说解决办法是重写CanalNodeAccessStrategy，请问大家都是怎么解决的，能给个解决思路吗

**Comment by ZhichX** [comment]
墙裂建议官方升级一下guava版本，项目中若要使用guava20+版本的新特性，有引用canal的话，就会报错 NoSuchMethodError: com.google.common.collect.MapMaker.makeComputingMap，很不方便

**Comment by agapple** [comment]
最新的master已经支持all in打包的模式，把guava的依赖jar打包进canal client

**Comment by ZhichX** [comment]
这个仅仅是canal client的升级吗？我们这边在canal server也有自定义开发，使用嵌入式方式将server当成一个agent用的，canal目前有没有整体升级一些第三方依赖的计划呢？

**Comment by agapple** [comment]
可以考虑提交PR给我
