### ISSUE TITLE
canal-1.026-alpha4 启动失败

### ISSUE THREAD

**Issue by xbloom** [alibaba/canal#817]
OS: CentOS Linux release 7.4.1708
canal : canal-1.026-alpha4
在mac中验证没有问题。linux环境 启动失败.

java stack:
`Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: java.lang.IllegalArgumentException: limit excceed: 44
Caused by: java.lang.IllegalArgumentException: limit excceed: 44
        at com.taobao.tddl.dbsync.binlog.LogBuffer.getUint8(LogBuffer.java:235) ~[canal.parse.dbsync-1.0.26-SNAPSHOT.jar:na]
        at com.taobao.tddl.dbsync.binlog.event.GtidLogEvent.<init>(GtidLogEvent.java:48) ~[canal.parse.dbsync-1.0.26-SNAPSHOT.jar:na]
        at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:364) ~[canal.parse.dbsync-1.0.26-SNAPSHOT.jar:na]
        at com.taobao.tddl.dbsync.binlog.LogDecoder.decode(LogDecoder.java:110) ~[canal.parse.dbsync-1.0.26-SNAPSHOT.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor$SimpleParserStage.onEvent(MysqlMultiStageCoprocessor.java:210) ~[canal.parse-1.0.26-SNAPSHOT.jar:na]`

**Comment by agapple** [comment]
已知问题，请下载最新的alpha-5
