### ISSUE TITLE
我在开启server后，报一个 dump address /127.0.0.1:3306 has an error ，这个是什么原因啊   

### ISSUE THREAD

**Issue by haohaozaijianghu** [alibaba/canal#847]
[destination = example , address = /127.0.0.1:3306 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - dump address /127.0.0.1:3306 has an error, retrying. caused by 
java.lang.IllegalArgumentException: null
	at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1314) ~[na:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1237) ~[na:1.8.0_144]
	at java.util.concurrent.Executors.newFixedThreadPool(Executors.java:151) ~[na:1.8.0_144]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor.start(MysqlMultiStageCoprocessor.java:84) ~[canal.parse-1.0.26-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:230) ~[canal.parse-1.0.26-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]
2018-08-16 12:21:45.933 [destination = example , address = /127.0.0.1:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[java.lang.IllegalArgumentException
	at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1314)
	at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1237)
	at java.util.concurrent.Executors.newFixedThreadPool(Executors.java:151)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor.start(MysqlMultiStageCoprocessor.java:84)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:230)
	at java.lang.Thread.run(Thread.java:748)

**Comment by kervin521** [comment]
是1.0.26 alpha的那个版本的错误？

**Comment by haohaozaijianghu** [comment]
alpha5 这个版本报的错误。

**Comment by strive2greek** [comment]
alpha5 遇到同样的问题

**Comment by strive2greek** [comment]
canal.instance.parser.parallelThreadSize 需要设置

**Comment by haohaozaijianghu** [comment]
你当时canal.instance.parser.parallelThreadSize 这个参数是配置成为多少的？

**Comment by strive2greek** [comment]
我用默认的值，原配置文档这行注释掉的

**Comment by shiyuan2he** [comment]
也遇到此问题，求帮助

**Comment by agapple** [comment]
最新的1.1.1版本已解决
