### ISSUE TITLE
在程序中设置master position报错。

### ISSUE THREAD

**Issue by ggservice007** [alibaba/canal#863]
我是直接extends MysqlEventParser
```java
 /**
   * 查询当前的binlog位置
   * @param mysqlConnection
   * @return
   */
  private EntryPosition findEndPosition(MysqlConnection mysqlConnection) {
    try {
  // ...
EntryPosition endPosition = new EntryPosition(
          "my-bin.000001", Long.valueOf(1L));

      return endPosition;
```

运行直接报错
```cmd
18:06:43.222 [destination = example , address = /117.107.241.79:3306 , EventParser] INFO  c.a.o.c.p.d.mysql.MysqlConnector - KILL DUMP 1110 failure
java.io.IOException: ErrorPacket [errorNumber=1094, fieldCount=-1, message=Unknown thread id: 1110, sqlState=HY000, sqlStateMarker=#]
 with command: KILL CONNECTION 1110
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlUpdateExecutor.update(MysqlUpdateExecutor.java:49) ~[classes/:na]
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlConnector.disconnect(MysqlConnector.java:107) ~[classes/:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.disconnect(MysqlConnection.java:93) [classes/:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:309) [classes/:na]
```

**Comment by ggservice007** [comment]
是我太low了，应该是从4L，开始。
