### ISSUE TITLE
canal-1.1.0 BioSocketChannel Timeout

### ISSUE THREAD

**Issue by fangchunsheng** [alibaba/canal#864]
`2018-08-21 05:51:48.895 [destination = zaful , address = /127.0.0.1:3306 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - prepare to find start position just last position
 {"identity":{"slaveId":-1,"sourceAddress":{"address":"127.0.0.1","port":3306}},"postion":{"gtid":"","included":false,"journalName":"binlog.002535","position":157229530,"serverId":97153,"timestamp":1534833018000}}
2018-08-21 05:51:48.895 [destination = zaful , address = /127.0.0.1:3306 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - find start position : EntryPosition[included=false,journalName=binlog.002535,position=157229530,serverId=97153,gtid=,timestamp=1534833018000]
2018-08-21 05:52:36.469 [destination = zaful , address = /127.0.0.1:3306 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - Socket timeout expired, closing connection
java.net.SocketTimeoutException: Timeout occurred, failed to read 9471 bytes in 25000 milliseconds.
	at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:123) ~[canal.parse.driver-1.0.26-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:174) ~[canal.parse-1.0.26-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:85) ~[canal.parse-1.0.26-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:206) [canal.parse-1.0.26-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:240) [canal.parse-1.0.26-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
2018-08-21 05:52:36.470 [destination = zaful , address = /127.0.0.1:3306 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - dump address 127.0.0.1/127.0.0.1:3306 has an error, retrying. **caused by 
_### **### 

> java.net.SocketTimeoutException: Timeout occurred, failed to read 9471 bytes in 25000 milliseconds

**_.**
	at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:123) ~[canal.parse.driver-1.0.26-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:174) ~[canal.parse-1.0.26-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:85) ~[canal.parse-1.0.26-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:206) ~[canal.parse-1.0.26-SNAPSHOT.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:240) ~[canal.parse-1.0.26-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
2018-08-21 05:52:36.470 [destination = zaful , address = /127.0.0.1:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:zaful[java.net.SocketTimeoutException: Timeout occurred, failed to read 9471 bytes in 25000 milliseconds.
	at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:123)
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:174)
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:85)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:206)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:240)
	at java.lang.Thread.run(Thread.java:745)
]`

程序启动 运行一段时间后，就一直报这个错！每次fetch超时后，就会kill掉和Mysql的connection，然后又重试，接着又超时，一直这样子死循环，重启也没有用，但是删除掉meta.dat后，能够正常运行一段时间，之后又会报超时的错误。 实在不能理解在有很多binlog文件没有消费的情况下，为什么读几kb数据花25s都读不完！！
有遇到相同问题的同仁吗？

**Comment by agapple** [comment]
换1.1.0版本试试

**Comment by lcybo** [comment]
@fangchunsheng ，如果你的环境能经常reproduce，建议在 
 BioSocketChannel.read(BioSocketChannel.java:123) 里面debug下，是不是 input.read(data, off + n, len - n); 这个调用真的timeout了。

PS: 看了下openjdk实现，timeout通过poll或select查看返回值是否>0。因此就算只能读到1个byte，都不算超时。

**Comment by fangchunsheng** [comment]
@agapple  不好意思  笔误写成了2.1.1 实际用的就是1.1.0

**Comment by fangchunsheng** [comment]
@lcybo  ok 我试一下  不过我们线上用的不是openjdk哈 谢谢

**Comment by nerverbe** [comment]
我这里读4个byte都会timeout，启动example也会报这个错
java.net.SocketTimeoutException: Timeout occurred, failed to read 4 bytes in 25000 milliseconds.
        at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:123) ~[canal.parse.driver-1.1.0.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:174) ~[canal.parse-1.1.0.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:77) ~[canal.parse-1.1.0.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:213) [canal.parse-1.1.0.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:248) [canal.parse-1.1.0.jar:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.7.0_191]
2018-08-22 05:24:35.190 [destination = centos1 , address = /127.0.0.1:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address /127.0.0.1:3306 has an error, retrying. caused by 
java.net.SocketTimeoutException: Timeout occurred, failed to read 4 bytes in 25000 milliseconds.
        at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:123) ~[canal.parse.driver-1.1.0.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:174) ~[canal.parse-1.1.0.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:77) ~[canal.parse-1.1.0.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:213) ~[canal.parse-1.1.0.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:248) ~[canal.parse-1.1.0.jar:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.7.0_191]
2018-08-22 05:24:35.194 [destination = centos1 , address = /127.0.0.1:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:centos1[java.net.SocketTimeoutException: Timeout occurred, failed to read 4 bytes in 25000 milliseconds.
        at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:123)
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:174)
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:77)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:213)
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:248)
        at java.lang.Thread.run(Thread.java:748)

**Comment by fangchunsheng** [comment]
@nerverbe  是的 我这边也会有这种情况 就是4个字节也会报错，我看了下代码，应该是读他的协议的head的时候会是4个字节

**Comment by lcybo** [comment]
如果确认socketInputStream的read调用有timeout，可以考虑下网络问题。
查看dump connection用的网卡有无挤占的情况。

**Comment by fangchunsheng** [comment]
@lcybo  我用canal-1.1.0 里面的dump的测试用例去到线上去跑过，用相同的binglog文件，然后相同的position,跑的时候完全没有问题，所以应该不是网络原因

**Comment by lcybo** [comment]
@fangchunsheng 你说的测试用例是MysqlDumpTest吗？
测试用例里的MysqlEventParser是线上使用的parser，用的socketChannel其实也是一致的。
看来也要考虑下MysqlEventParser外的因素， @agapple 。

**Comment by radishlee** [comment]
https://github.com/alibaba/canal/issues/951 看一下这个， 是这个问题相关么

**Comment by aiguo123** [comment]
input.read(data, off + n, len - n); 我的也是卡在这儿 请问有解决方案吗，我用的是最新1.1.5版本
