### ISSUE TITLE
一遇到mysql 进行大批量操作的时候，客户端就会报错

### ISSUE THREAD

**Issue by zyheric** [alibaba/canal#867]
com.alibaba.otter.canal.protocol.exception.CanalClientException: java.io.IOException: Broken pipe
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.ack(SimpleCanalConnector.java:339)
	at com.adups.canal.CanalHandler.handler(CanalHandler.java:72)
	at com.adups.canal.CanalClient$2.run(CanalClient.java:52)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at java.nio.channels.Channels.writeFullyImpl(Channels.java:78)
	at java.nio.channels.Channels.writeFully(Channels.java:98)
	at java.nio.channels.Channels.access$000(Channels.java:61)
	at java.nio.channels.Channels$1.write(Channels.java:174)
	at java.nio.channels.Channels$WritableByteChannelImpl.write(Channels.java:458)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.writeWithHeader(SimpleCanalConnector.java:382)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.writeWithHeader(SimpleCanalConnector.java:369)
	at com.alibaba.otter.canal.client.impl.SimpleCanalConnector.ack(SimpleCanalConnector.java:333)
	... 3 common frames omitted

**Comment by agapple** [comment]
客户端处理速度慢了，超过超时时间了？升级1.1.0试试

**Comment by zyheric** [comment]
是不是客户端ack太慢了，导致超时报错？

**Comment by 594904292** [comment]
客户端ack多长时间才不慢呢
