### ISSUE TITLE
Could not find first log file name in binary log index file

### ISSUE THREAD

**Issue by hahaha11123** [alibaba/canal#903]
错误信息：
2018-09-03 17:06:05.707 [main] INFO  c.a.otter.canal.instance.spring.CanalInstanceWithSpring - start CannalInstance for 1-example
2018-09-03 17:06:05.709 [main] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - start successful....
2018-09-03 17:06:05.781 [destination = example , address = xxxxx:3306 , EventParser] WARN  c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - prepare to find start position just last position
 {"identity":{"slaveId":-1,"sourceAddress":{"address":"xxxx","port":3306}},"postion":{"included":false,"journalName":"mysql-bin.002736","position":30948432,"serverId":2118896143,"timestamp":1535632015000}}
2018-09-03 17:06:05.886 [destination = example , address = xxxx:3306 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - I/O error while reading from client socket
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:95) ~[canal.parse-1.0.24.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:122) [canal.parse-1.0.24.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209) [canal.parse-1.0.24.jar:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.7.0_141]
2018-09-03 17:06:05.887 [destination = example , address = xxxx:3306 , EventParser] ERROR c.a.otter.canal.parse.inbound.mysql.MysqlEventParser - dump address xxxxx:3306 has an error, retrying. caused by
java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:95) ~[canal.parse-1.0.24.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:122) ~[canal.parse-1.0.24.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209) ~[canal.parse-1.0.24.jar:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.7.0_141]
2018-09-03 17:06:05.893 [destination = example , address = xxxx:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[java.io.IOException: Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file
        at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:95)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:122)
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:209)
        at java.lang.Thread.run(Thread.java:748)
]
问题应该是meta.dat中的binlog文件跟不上show master STATUS中的日志文件。
meta.dat中的文件是mysql-bin.002736:
{"clientDatas":[{"clientIdentity":{"clientId":1001,"destination":"example","filter":""},"cursor":{"identity":{"slaveId":-1,"sourceAddress":{"address":"":"xxxx","p","port":3306}},"postion":{"included":false,"journalName":"mysql-bin.002736","position":30948432,"serverId":2118896143,"timestamp":1535632015000}}}],"destination":"example"}
show master STATUS最新的文件;
mysql-bin.002752	24891270	
之前的做法是直接删除meta.dat文件，重新开始同步，但是会丢失数据。运行一段时间后又会出现该问题。请问大佬们怎么解决。

**Comment by lcybo** [comment]
mysql master会基于一定的策略去sweep binlog(根据size或时间)，如果消费的慢，meta.dat里的log就被清理了。 这种情况考虑下提升整体吞吐量吧。

**Comment by hahaha11123** [comment]
2018-09-04 09:35:33.645 [destination = example , address = xxx:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[com.alibaba.otter.canal.parse.exception.CanalParseException: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: parse row data failed.
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: column size is not match for table:`skstandard`.`tbl_20180824090548lyqbbcqqjdt68u5m`,103 vs 15
应该是由于表结构改变导致服务一直卡在这里，请问有什么好的方法可以跳过去吗，针对这种表结构改变的情况怎么处理的呢？我现在是手动修改meta.dat中的position跳过的。

**Comment by lcybo** [comment]
升级新版本吧

**Comment by Dcein** [comment]
大佬，你这个column size is not match for table问题是怎么解决的,望赐教！

**Comment by YongLinW** [comment]
本地使用的是1.1.0版本，但是还会出现column size is not match for table，望大佬赐教解决办法
