### ISSUE TITLE
1.1.0 版本canal server 启动后cpu一直100%甚至160%

### ISSUE THREAD

**Issue by yin007008** [alibaba/canal#904]
1.1.0 版本canal server 启动后cpu一直100%甚至160%，这个属于这个版本存在的问题还是使用姿势问题？
配置方面用的canal.instance.global.spring.xml = classpath:spring/default-instance.xml
，使用kafka集成的方式

不管有没有binlog下来，canal server 进程的cpu消耗基本上一直100%的样子

**Comment by rewerma** [comment]
top -Hp pid看看那个线程占cpu高，然后用jstack看看是哪个类和方法引起的

**Comment by fifichasheng** [comment]
同问题
"pool-6-thread-1" #31 prio=5 os_prio=0 tid=0x00007f85f0cdb800 nid=0x8e95 runnable [0x00007f858d6e6000]
   java.lang.Thread.State: RUNNABLE
        at com.google.common.collect.ComputingConcurrentHashMap.getOrCompute(ComputingConcurrentHashMap.java:67)
        at com.google.common.collect.MapMaker$ComputingMapAdapter.get(MapMaker.java:885)
        at com.alibaba.otter.canal.meta.MemoryMetaManager.getLastestBatch(MemoryMetaManager.java:116)
        at com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded.getWithoutAck(CanalServerWithEmbedded.java:299)
        - locked <0x0000000740028bd0> (a com.alibaba.otter.canal.instance.spring.CanalInstanceWithSpring)
        at com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded.getWithoutAck(CanalServerWithEmbedded.java:273)
        at com.alibaba.otter.canal.kafka.producer.CanalKafkaStarter.worker(CanalKafkaStarter.java:121)
        at com.alibaba.otter.canal.kafka.producer.CanalKafkaStarter.access$000(CanalKafkaStarter.java:26)
        at com.alibaba.otter.canal.kafka.producer.CanalKafkaStarter$1.run(CanalKafkaStarter.java:70)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
有死循环吧

**Comment by yin007008** [comment]
现在部署到压测环境了，没有任何binlog下载的情况下，部署了4台云机，8核心的机器，8个destination，cpu800%，求大佬解决啊


"pool-12-thread-1" #29 prio=5 os_prio=0 tid=0x00007fdee4afa000 nid=0x2394 runnable [0x00007fde6cce4000]
   java.lang.Thread.State: RUNNABLE
	at com.alibaba.otter.canal.store.model.Events.<init>(Events.java:23)
	at com.alibaba.otter.canal.store.memory.MemoryEventStoreWithBuffer.doGet(MemoryEventStoreWithBuffer.java:280)
	at com.alibaba.otter.canal.store.memory.MemoryEventStoreWithBuffer.tryGet(MemoryEventStoreWithBuffer.java:261)
	at com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded.getEvents(CanalServerWithEmbedded.java:478)
	at com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded.getWithoutAck(CanalServerWithEmbedded.java:310)
	- locked <0x0000000740492388> (a com.alibaba.otter.canal.instance.spring.CanalInstanceWithSpring)
	at com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded.getWithoutAck(CanalServerWithEmbedded.java:273)
	at com.alibaba.otter.canal.kafka.producer.CanalKafkaStarter.worker(CanalKafkaStarter.java:121)
	at com.alibaba.otter.canal.kafka.producer.CanalKafkaStarter.access$000(CanalKafkaStarter.java:26)
	at com.alibaba.otter.canal.kafka.producer.CanalKafkaStarter$1.run(CanalKafkaStarter.java:70)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


从线程dump来看就是进入死循环new  Events对象了

**Comment by yin007008** [comment]
正常有binlog拉取时候的线程栈信息如下：

"pool-11-thread-3" #73 prio=5 os_prio=0 tid=0x00007f7ae8d88800 nid=0x3e5e runnable [0x00007f7a70927000]
   java.lang.Thread.State: RUNNABLE
	at com.alibaba.otter.canal.store.helper.CanalEventUtils.createPosition(CanalEventUtils.java:76)
	at com.alibaba.otter.canal.store.memory.MemoryEventStoreWithBuffer.getFirstPosition(MemoryEventStoreWithBuffer.java:375)
	at com.alibaba.otter.canal.store.memory.MemoryEventStoreWithBuffer.getFirstPosition(MemoryEventStoreWithBuffer.java:36)
	at com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded.getWithoutAck(CanalServerWithEmbedded.java:307)
	- locked <0x00000007406361f0> (a com.alibaba.otter.canal.instance.spring.CanalInstanceWithSpring)
	at com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded.getWithoutAck(CanalServerWithEmbedded.java:273)
	at com.alibaba.otter.canal.kafka.producer.CanalKafkaStarter.worker(CanalKafkaStarter.java:121)
	at com.alibaba.otter.canal.kafka.producer.CanalKafkaStarter.access$000(CanalKafkaStarter.java:26)
	at com.alibaba.otter.canal.kafka.producer.CanalKafkaStarter$1.run(CanalKafkaStarter.java:70)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

"pool-11-thread-2" #72 prio=5 os_prio=0 tid=0x00007f7ae8d86800 nid=0x3e5d runnable [0x00007f7a70968000]
   java.lang.Thread.State: RUNNABLE
	at com.google.common.collect.MapMakerInternalMap$Segment.getEntry(MapMakerInternalMap.java:2402)
	at com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.getOrCompute(ComputingConcurrentHashMap.java:81)
	at com.google.common.collect.ComputingConcurrentHashMap.getOrCompute(ComputingConcurrentHashMap.java:67)
	at com.google.common.collect.MapMaker$ComputingMapAdapter.get(MapMaker.java:885)
	at com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded.getWithoutAck(CanalServerWithEmbedded.java:296)
	at com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded.getWithoutAck(CanalServerWithEmbedded.java:273)
	at com.alibaba.otter.canal.kafka.producer.CanalKafkaStarter.worker(CanalKafkaStarter.java:121)
	at com.alibaba.otter.canal.kafka.producer.CanalKafkaStarter.access$000(CanalKafkaStarter.java:26)
	at com.alibaba.otter.canal.kafka.producer.CanalKafkaStarter$1.run(CanalKafkaStarter.java:70)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


"pool-11-thread-1" #71 prio=5 os_prio=0 tid=0x00007f7ae8d85800 nid=0x3e5c runnable [0x00007f7a709a9000]
   java.lang.Thread.State: RUNNABLE
	at com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded.getWithoutAck(CanalServerWithEmbedded.java:317)
	- locked <0x000000074004a4d0> (a com.alibaba.otter.canal.instance.spring.CanalInstanceWithSpring)
	at com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded.getWithoutAck(CanalServerWithEmbedded.java:273)
	at com.alibaba.otter.canal.kafka.producer.CanalKafkaStarter.worker(CanalKafkaStarter.java:121)
	at com.alibaba.otter.canal.kafka.producer.CanalKafkaStarter.access$000(CanalKafkaStarter.java:26)
	at com.alibaba.otter.canal.kafka.producer.CanalKafkaStarter$1.run(CanalKafkaStarter.java:70)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by yin007008** [comment]
@rewerma 大佬这个问题帮忙看看啊

**Comment by agapple** [comment]
CanalKafkaStarter.worker估计未设置sleep时间,针对空结果时相当于无限循环在跑了, 可以优化一下

**Comment by rewerma** [comment]
修改提交了，不过有点奇怪，我这边不设sleep一直无线循环取数据没问题的，CPU正常。我这边用的是1.8的jdk，G1的收集器
