### ISSUE TITLE
1.1.0版本启动异常 无法检测到数据库变动

### ISSUE THREAD

**Issue by hanzhenchaoGit** [alibaba/canal#906]
[destination = example , address = /10.19.1.80:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: EOF encountered.
Caused by: java.io.IOException: EOF encountered.
	at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:56)
	at com.alibaba.otter.canal.parse.driver.mysql.utils.PacketManager.readHeader(PacketManager.java:12)
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlQueryExecutor.readNextPacket(MysqlQueryExecutor.java:159)
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlQueryExecutor.query(MysqlQueryExecutor.java:56)
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.query(MysqlConnection.java:102)
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.dumpTableMeta(DatabaseTableMeta.java:148)
	at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:129)
	at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:91)
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:188)
	at java.lang.Thread.run(Thread.java:748)
]

**Comment by agapple** [comment]
Caused by: java.io.IOException: EOF encountered.  检查一下数据库

**Comment by VincentLiSH** [comment]
应该是canal订阅binlog过程 相当于是mysql向canal写数据，
当遇到了某个特别大数据量的事务（例如“create table xxx_init as select * from xxx”），mysql写超时 断开了连接，set global show variables like '%timeout'; 发现net_write_timeout默认60秒；
set global net_write_timeout=28800 改为8小时

https://blog.csdn.net/cuizhu0832/article/details/100349359
