### ISSUE TITLE
example里面的报错

### ISSUE THREAD

**Issue by 13772134994** [alibaba/canal#907]
2018-09-04 11:39:04.244 [WrapperSimpleAppMain] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Loading properties file from class path resource [canal.properties]
2018-09-04 11:39:04.244 [WrapperSimpleAppMain] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Loading properties file from class path resource [example/instance.properties]
2018-09-04 11:39:04.400 [WrapperSimpleAppMain] WARN  o.s.beans.GenericTypeAwarePropertyDescriptor - Invalid JavaBean property 'connectionCharset' being accessed! Ambiguous write methods found next to actually used [public void com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.setConnectionCharset(java.nio.charset.Charset)]: [public void com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.setConnectionCharset(java.lang.String)]
2018-09-04 11:39:04.400 [WrapperSimpleAppMain] INFO  c.a.otter.canal.instance.spring.CanalInstanceWithSpring - start CannalInstance for 1-example 
2018-09-04 11:39:04.416 [WrapperSimpleAppMain] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - start successful....
2018-09-04 11:39:04.416 [canal-instance-scan-0] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - stop CannalInstance for null-example 
2018-09-04 11:39:04.432 [destination = example , address = /127.0.0.1:3308 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - parse events has an error
com.alibaba.otter.canal.parse.exception.CanalParseException: dump address /127.0.0.1:3308 has an error, retrying. 
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: java.net.SocketException: Socket Closed
Caused by: java.net.SocketException: Socket Closed
	at java.net.SocketInputStream.socketRead0(Native Method) ~[na:1.8.0_77]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[na:1.8.0_77]
	at java.net.SocketInputStream.read(SocketInputStream.java:170) ~[na:1.8.0_77]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:1.8.0_77]
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[na:1.8.0_77]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286) ~[na:1.8.0_77]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345) ~[na:1.8.0_77]
	at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:52) ~[canal.parse.driver-1.1.0.jar:na]
	at com.alibaba.otter.canal.parse.driver.mysql.utils.PacketManager.readHeader(PacketManager.java:12) ~[canal.parse.driver-1.1.0.jar:na]
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlQueryExecutor.readNextPacket(MysqlQueryExecutor.java:159) ~[canal.parse.driver-1.1.0.jar:na]
	at com.alibaba.otter.canal.parse.driver.mysql.MysqlQueryExecutor.query(MysqlQueryExecutor.java:56) ~[canal.parse.driver-1.1.0.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.query(MysqlConnection.java:102) ~[canal.parse-1.1.0.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.loadBinlogFormat(MysqlConnection.java:433) ~[canal.parse-1.1.0.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.getBinlogFormat(MysqlConnection.java:582) ~[canal.parse-1.1.0.jar:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlEventParser.preDump(MysqlEventParser.java:95) ~[canal.parse-1.1.0.jar:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:173) ~[canal.parse-1.1.0.jar:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_77]
2018-09-04 11:39:04.432 [canal-instance-scan-0] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - stop successful....

**Comment by agapple** [comment]
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: java.net.SocketException: Socket Closed
Caused by: java.net.SocketException: Socket Closed

感觉是主动关闭
