### ISSUE TITLE
最新canal.kafka-1.1.0.tar部署无法启动，调试源码也是同样的异常，求关注

### ISSUE THREAD

**Issue by wang12190529** [alibaba/canal#911]
2018-09-04 16:10:09.223 [main] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Loading properties file from class path resource [canal.properties]
2018-09-04 16:10:09.226 [main] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Loading properties file from class path resource [example/instance.properties]
2018-09-04 16:10:09.400 [main] WARN  o.s.beans.GenericTypeAwarePropertyDescriptor - Invalid JavaBean property 'connectionCharset' being accessed! Ambiguous write methods found next to actually use
d [public void com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.setConnectionCharset(java.lang.String)]: [public void com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlE
ventParser.setConnectionCharset(java.nio.charset.Charset)]
2018-09-04 16:10:09.435 [main] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Loading properties file from class path resource [canal.properties]
2018-09-04 16:10:09.435 [main] INFO  c.a.o.c.i.spring.support.PropertyPlaceholderConfigurer - Loading properties file from class path resource [example/instance.properties]
2018-09-04 16:10:09.667 [main] ERROR com.alibaba.druid.pool.DruidDataSource - testWhileIdle is true, validationQuery not set
2018-09-04 16:10:09.891 [main] INFO  c.a.otter.canal.instance.spring.CanalInstanceWithSpring - start CannalInstance for 1-example
2018-09-04 16:10:09.905 [main] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - start successful....
2018-09-04 16:10:09.948 [destination = example , address = /192.168.200.30:3306 , EventParser] WARN  c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - prepare to find start position just las
t position
 {"identity":{"slaveId":-1,"sourceAddress":{"address":"mySlave","port":3306}},"postion":{"gtid":"","included":false,"journalName":"mysql-bin.000029","position":132895982,"serverId":2,"timestamp":1
536044055000}}
2018-09-04 16:10:09.993 [Thread-7] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - stop CannalInstance for null-example
2018-09-04 16:10:09.996 [destination = example , address = /192.168.200.30:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - parse events has an error
com.alibaba.otter.canal.parse.exception.CanalParseException: dump address /192.168.200.30:3306 has an error, retrying.
Caused by: com.alibaba.otter.canal.parse.exception.CanalParseException: java.io.IOException: should execute connector.connect() first
Caused by: java.io.IOException: should execute connector.connect() first
        at com.alibaba.otter.canal.parse.driver.mysql.MysqlQueryExecutor.<init>(MysqlQueryExecutor.java:30) ~[canal.parse.driver-1.1.0.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.queryMulti(MysqlConnection.java:106) ~[canal.parse-1.1.0.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.dumpTableMeta(DatabaseTableMeta.java:175) ~[canal.parse-1.1.0.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.tsdb.DatabaseTableMeta.rollback(DatabaseTableMeta.java:129) ~[canal.parse-1.1.0.jar:na]
        at com.alibaba.otter.canal.parse.inbound.mysql.AbstractMysqlEventParser.processTableMeta(AbstractMysqlEventParser.java:91) ~[canal.parse-1.1.0.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:188) ~[canal.parse-1.1.0.jar:na]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_171]
2018-09-04 16:10:09.997 [Thread-7] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - stop successful....

**Comment by agapple** [comment]
在我们环境里无法重试，你尝试debug看一下MysqlConnection什么条件下被disconnect
