### ISSUE TITLE
zookeeper集群搭建canal启动报错?

### ISSUE THREAD

**Issue by greenHard** [alibaba/canal#916]
- Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_181]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_181]
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350) ~[zookeeper-3.4.5.jar:3.4.5-1392090]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1068) ~[zookeeper-3.4.5.jar:3.4.5-1392090]

`canal.properties:`
canal.id= 1
canal.zkServers=10.153.1.208:2888,10.153.0.183:2888,10.153.0.38:2888
canal.instance.global.spring.xml = classpath:spring/default-instance.xml

**Comment by greenHard** [comment]
是我canal连接zookeeper连接的端口号弄错了。
