### ISSUE TITLE
V1.1.0版本，源端没有数据时，dump日志的socket2.5s就timeout抛异常，导致重连

### ISSUE THREAD

**Issue by theonesmx** [alibaba/canal#951]
启动Canal，如果持续有数据，不报错。当没有数据时，2.5s就SocketTimeoutException异常，导致重连。
报错位于BioSocketChannel.read(BioSocketChannel.java:123)
查看代码，BioSocketChannel中的SO_TIMEOUT=1000，即1s，如果read()不到数据，1s就会抛出SocketTimeoutException。其中累加到入参的2.5s，就会向上抛出异常，导致重连。

**Comment by lcybo** [comment]
首先累加的timeout是25s。
其次canal开启了master heartbeat，默认没数据时每15s会获得一个heartbeat包重置超时时间。
可以从这里着手检查一下系统。

**Comment by theonesmx** [comment]
@lcybo 我描述错了，是25s，不是2.5s。
在文件DirectLogFetcher中定义了master hearbeat=15；然后READ_TIMEOUT_MILLISECONDS=(MASTER_HEARTBEAT_PERIOD_SECONDS + 10) * 1000;即read()的时候timeout=25s。
现在现象就是BioSocketChannel中的read(25)方法传入的timeout时间是25s，如果没有增量数据，超过25s，就抛出SocketTimeoutException异常了。

如你所说：
如果不开启master heartbeat的话，是不是25s就会sockettimeout异常，进行重连。
开启master heartbeat是设置配置文件中的canal.instance.detecting.enable =true 和canal.instance.detecting.heartbeatHaEnable = true么？我现在设置了没有起作用呢？是哪里没设置对么

**Comment by lcybo** [comment]
canal.instance.detecting.enable和binlog master heartbeat不是一个概念。
canal.instance.detecting.enable是fork出另一个connection由canal server发起的heartbeat。
binlog master heartbeat则是MySQL dump协议的一部分，由MySQL master发起直接在dump connection中传输。canal server 无需配置直接开启的。
https://dev.mysql.com/doc/refman/8.0/en/change-master-to.html
可以看MASTER_HEARTBEAT_PERIOD 这一段，检查下master端是否生效.

**Comment by theonesmx** [comment]
@lcybo 感谢。我看了下介绍，这个MASTER_HEARTBEAT_PERIOD 是slave端设置的吧。
canal server做为slave直接开启了已经，应该不需要Canal端设置什么了。
你让我检查master是否生效，意思是在master要设置什么？怎么检查？
在master端执行CHANGE MASTER TO MASTER_HEARTBEAT_PERIOD=20么？我命令执行成功了，但是还是25s断开，重连。

我的Canal server连接的是master.
或者说canal server为了解决半连接问题，没数据时，25s自动重连一次，是正常的。
2018-09-18 17:40:44.165 [destination = example , address = /127.0.0.1:3306 , EventParser] ERROR c.a.o.canal.parse.inbound.mysql.dbsync.DirectLogFetcher - Socket timeout expired, closing connection
java.net.SocketTimeoutException: Timeout occurred, failed to read 4 bytes in 25000 milliseconds.
	at com.alibaba.otter.canal.parse.driver.mysql.socket.BioSocketChannel.read(BioSocketChannel.java:123) ~[classes/:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch0(DirectLogFetcher.java:174) ~[classes/:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.dbsync.DirectLogFetcher.fetch(DirectLogFetcher.java:77) ~[classes/:na]
	at com.alibaba.otter.canal.parse.inbound.mysql.MysqlConnection.dump(MysqlConnection.java:213) [classes/:na]
	at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:248) [classes/:na]
	at java.lang.Thread.run(Unknown Source) [na:1.7.0_45]

**Comment by lcybo** [comment]
@theonesmx 嗯，这个feature是5.5加入的。
