### ISSUE TITLE
idle timeout exceeds, close channel to save server resources canal1.1.1版本错误 

### ISSUE THREAD

**Issue by laxhcxh** [alibaba/canal#986]
2018-10-08 18:09:07.144 [Hashed wheel timer #1] WARN  c.a.o.c.server.netty.handler.ClientAuthenticationHandler - channel:[id: 0x2d3c7336, /10.8.32.241:54621 => /10.8.32.241:11111] idle timeout exceeds, close channel to save server resources...
2018-10-08 18:09:13.279 [New I/O server worker #1-14] ERROR c.a.otter.canal.server.netty.handler.SessionHandler - something goes wrong with channel:[id: 0x4863b38b, /10.8.32.241:54622 :> /10.8.32.241:11111], exception=java.nio.channels.ClosedChannelException
        at org.jboss.netty.channel.socket.nio.NioWorker.cleanUpWriteBuffer(NioWorker.java:629)
        at org.jboss.netty.channel.socket.nio.NioWorker.close(NioWorker.java:605)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:356)
        at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:281)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:201)
        at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by agapple** [comment]
client长时间没有和canal server有交互导致，默认超时时间1小时
