### ISSUE TITLE
ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by brightsong** [alibaba/canal#999]
参照Canal Kafka QuickStart中的说明，配置了canal到kafka数据同步，启动canal-kafka后，报
`2018-10-12 15:26:32.189 [destination = example , address = /192.168.206.136:3306 , EventParser] ERROR c.a.o.c.p.inbound.mysql.rds.RdsBinlogEventParserProxy - dump address /192.168.206.136:3306 has an error, retrying. caused by 
java.lang.IllegalArgumentException: null
        at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1310) ~[na:1.7.0_79]
        at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1233) ~[na:1.7.0_79]
        at java.util.concurrent.Executors.newFixedThreadPool(Executors.java:114) ~[na:1.7.0_79]
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor.start(MysqlMultiStageCoprocessor.java:84) ~[canal.parse-1.1.0.jar:na]
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:238) ~[canal.parse-1.1.0.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
2018-10-12 15:26:32.189 [destination = example , address = /192.168.206.136:3306 , EventParser] ERROR com.alibaba.otter.canal.common.alarm.LogAlarmHandler - destination:example[java.lang.IllegalArgumentException
        at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1310)
        at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1233)
        at java.util.concurrent.Executors.newFixedThreadPool(Executors.java:114)
        at com.alibaba.otter.canal.parse.inbound.mysql.MysqlMultiStageCoprocessor.start(MysqlMultiStageCoprocessor.java:84)
        at com.alibaba.otter.canal.parse.inbound.AbstractEventParser$3.run(AbstractEventParser.java:238)
        at java.lang.Thread.run(Thread.java:745)
]`

有没有遇到这个问题的？

**Comment by brightsong** [comment]
使用环境：单机zookeeper-3.4.12，kafka_2.10-0.10.0.1，canal-kafka-1.1.0 ；

**Comment by shiyuan2he** [comment]
我也遇到一模一样的的问题，你解决了吗？

**Comment by shiyuan2he** [comment]
此问题已经解决，将服务端配置文件canal.properties 中的并行线程数关掉即可，单例单线程运行
